package com.theyawns.ecommerce.gateway.config;

import com.hazelcast.config.Config;
import com.hazelcast.config.MapConfig;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Hazelcast configuration for the API Gateway.
 *
 * <p>Creates an embedded, standalone Hazelcast instance used exclusively for
 * rate limiting state. This instance does not join any cluster — rate limit
 * counters are local to this gateway process. For multi-instance gateway
 * deployments, switch to a Hazelcast client connecting to the shared cluster.
 *
 * <p>Note: The gateway does not depend on framework-core, so Enterprise feature
 * customizers (HD Memory, TPC) are not applied here. If the gateway is later
 * integrated with the framework, inject {@code List<HazelcastConfigCustomizer>}
 * the same way the service modules do.
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
@Configuration
public class GatewayHazelcastConfig {

    /**
     * Creates an embedded Hazelcast instance for gateway rate limiting.
     *
     * <p>The instance is standalone (no cluster join) with a dedicated map
     * configured for rate limit bucket state with automatic TTL cleanup.
     *
     * @return a standalone HazelcastInstance for rate limit state
     */
    @Bean(destroyMethod = "shutdown")
    public HazelcastInstance hazelcastInstance() {
        final Config config = new Config();
        config.setInstanceName("gateway-hazelcast-" + System.identityHashCode(this));
        config.setClusterName("gateway-rate-limit");

        // Standalone — no cluster join
        config.getNetworkConfig().getJoin().getMulticastConfig().setEnabled(false);
        config.getNetworkConfig().getJoin().getAutoDetectionConfig().setEnabled(false);

        // Disable Jet (not needed for gateway)
        config.getJetConfig().setEnabled(false);

        // Rate limit map: entries auto-expire after 2 minutes
        final MapConfig rateLimitMap = new MapConfig("rate-limit");
        rateLimitMap.setTimeToLiveSeconds(120);
        config.addMapConfig(rateLimitMap);

        return Hazelcast.newHazelcastInstance(config);
    }
}
