package com.theyawns.ecommerce.gateway.config;

import org.springframework.boot.context.properties.ConfigurationProperties;

/**
 * Configuration properties for gateway rate limiting.
 *
 * <p>Rate limits are applied per client IP address using a token bucket
 * algorithm backed by Hazelcast IMap. Different limits can be configured
 * for read operations (GET, HEAD) versus write operations (POST, PUT, DELETE).
 *
 * <p>Example configuration:
 * <pre>
 * gateway:
 *   rate-limit:
 *     enabled: true
 *     read-limit: 100
 *     write-limit: 20
 * </pre>
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
@ConfigurationProperties(prefix = "gateway.rate-limit")
public class RateLimitProperties {

    /**
     * Whether rate limiting is enabled.
     */
    private boolean enabled = true;

    /**
     * Maximum requests per second for read operations (GET, HEAD) per client IP.
     */
    private int readLimit = 100;

    /**
     * Maximum requests per second for write operations (POST, PUT, DELETE, PATCH) per client IP.
     */
    private int writeLimit = 20;

    public boolean isEnabled() {
        return enabled;
    }

    public void setEnabled(final boolean enabled) {
        this.enabled = enabled;
    }

    public int getReadLimit() {
        return readLimit;
    }

    public void setReadLimit(final int readLimit) {
        this.readLimit = readLimit;
    }

    public int getWriteLimit() {
        return writeLimit;
    }

    public void setWriteLimit(final int writeLimit) {
        this.writeLimit = writeLimit;
    }
}
