package com.theyawns.ecommerce.common.events;

import com.hazelcast.nio.serialization.genericrecord.GenericRecord;
import com.hazelcast.nio.serialization.genericrecord.GenericRecordBuilder;
import com.theyawns.framework.event.DomainEvent;
import com.theyawns.ecommerce.common.domain.Customer;

import java.time.Instant;

/**
 * Event representing the creation of a new customer.
 *
 * <p>This event initializes a new customer with:
 * <ul>
 *   <li>Unique customer ID</li>
 *   <li>Email address</li>
 *   <li>Name and address</li>
 *   <li>ACTIVE status</li>
 * </ul>
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
public class CustomerCreatedEvent extends DomainEvent<Customer, String> {

    private static final long serialVersionUID = 1L;
    public static final String SCHEMA_NAME = "CustomerCreatedEvent";
    public static final String EVENT_TYPE = "CustomerCreated";

    private String email;
    private String name;
    private String address;
    private String phone;

    /**
     * Default constructor for serialization.
     */
    public CustomerCreatedEvent() {
        super();
        this.eventType = EVENT_TYPE;
    }

    /**
     * Creates a new CustomerCreatedEvent.
     *
     * @param customerId the unique customer ID
     * @param email the customer email
     * @param name the customer name
     * @param address the customer address
     */
    public CustomerCreatedEvent(String customerId, String email, String name, String address) {
        super(customerId);
        this.eventType = EVENT_TYPE;
        this.email = email;
        this.name = name;
        this.address = address;
    }

    /**
     * Creates a CustomerCreatedEvent from a GenericRecord.
     *
     * @param record the GenericRecord to hydrate from
     * @return the hydrated event
     */
    public static CustomerCreatedEvent fromGenericRecord(GenericRecord record) {
        if (record == null) {
            return null;
        }
        CustomerCreatedEvent event = new CustomerCreatedEvent();
        event.eventId = record.getString("eventId");
        event.eventType = record.getString("eventType");
        event.eventVersion = record.getString("eventVersion");
        event.source = record.getString("source");
        event.key = record.getString("key");
        event.correlationId = record.getString("correlationId");

        Long timestampMs = record.getInt64("timestamp");
        event.timestamp = timestampMs != null && timestampMs != 0 ? Instant.ofEpochMilli(timestampMs) : null;

        event.email = record.getString("email");
        event.name = record.getString("name");
        event.address = record.getString("address");
        event.phone = record.getString("phone");

        return event;
    }

    @Override
    public GenericRecord toGenericRecord() {
        return GenericRecordBuilder.compact(SCHEMA_NAME)
                .setString("eventId", eventId)
                .setString("eventType", eventType)
                .setString("eventVersion", eventVersion)
                .setString("source", source)
                .setInt64("timestamp", timestamp != null ? timestamp.toEpochMilli() : 0)
                .setString("key", key)
                .setString("correlationId", correlationId)
                .setString("sagaId", sagaId)
                .setString("sagaType", sagaType)
                .setInt32("stepNumber", stepNumber != null ? stepNumber : 0)
                .setBoolean("isCompensating", isCompensating != null && isCompensating)
                .setString("email", email)
                .setString("name", name)
                .setString("address", address)
                .setString("phone", phone)
                .build();
    }

    @Override
    public GenericRecord apply(GenericRecord domainObjectRecord) {
        // For a creation event, we ignore any existing state and create new
        Instant now = Instant.now();
        return GenericRecordBuilder.compact(Customer.SCHEMA_NAME)
                .setString("customerId", key)
                .setString("email", email)
                .setString("name", name)
                .setString("address", address)
                .setString("phone", phone)
                .setString("status", Customer.Status.ACTIVE.name())
                .setInt64("createdAt", now.toEpochMilli())
                .setInt64("updatedAt", now.toEpochMilli())
                .build();
    }

    @Override
    public String getSchemaName() {
        return SCHEMA_NAME;
    }

    // Getters and Setters

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Override
    public String toString() {
        return "CustomerCreatedEvent{" +
                "eventId='" + eventId + '\'' +
                ", customerId='" + key + '\'' +
                ", email='" + email + '\'' +
                ", name='" + name + '\'' +
                '}';
    }
}
