package com.theyawns.ecommerce.common.events;

import com.hazelcast.nio.serialization.genericrecord.GenericRecord;
import com.hazelcast.nio.serialization.genericrecord.GenericRecordBuilder;
import com.theyawns.framework.event.DomainEvent;
import com.theyawns.ecommerce.common.domain.Customer;

import java.time.Instant;

/**
 * Event representing a change in customer account status.
 *
 * <p>Status transitions:
 * <ul>
 *   <li>ACTIVE - normal operation</li>
 *   <li>SUSPENDED - temporarily disabled</li>
 *   <li>CLOSED - permanently closed</li>
 * </ul>
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
public class CustomerStatusChangedEvent extends DomainEvent<Customer, String> {

    public static final String SCHEMA_NAME = "CustomerStatusChangedEvent";
    public static final String EVENT_TYPE = "CustomerStatusChanged";

    private String newStatus;
    private String reason;

    /**
     * Default constructor for serialization.
     */
    public CustomerStatusChangedEvent() {
        super();
        this.eventType = EVENT_TYPE;
    }

    /**
     * Creates a new CustomerStatusChangedEvent.
     *
     * @param customerId the customer ID
     * @param newStatus the new status (ACTIVE, SUSPENDED, CLOSED)
     * @param reason the reason for the status change
     */
    public CustomerStatusChangedEvent(String customerId, String newStatus, String reason) {
        super(customerId);
        this.eventType = EVENT_TYPE;
        this.newStatus = newStatus;
        this.reason = reason;
    }

    /**
     * Creates a CustomerStatusChangedEvent from a GenericRecord.
     *
     * @param record the GenericRecord to hydrate from
     * @return the hydrated event
     */
    public static CustomerStatusChangedEvent fromGenericRecord(GenericRecord record) {
        if (record == null) {
            return null;
        }
        CustomerStatusChangedEvent event = new CustomerStatusChangedEvent();
        event.eventId = record.getString("eventId");
        event.eventType = record.getString("eventType");
        event.eventVersion = record.getString("eventVersion");
        event.source = record.getString("source");
        event.key = record.getString("key");
        event.correlationId = record.getString("correlationId");

        Long timestampMs = record.getInt64("timestamp");
        event.timestamp = timestampMs != null && timestampMs != 0 ? Instant.ofEpochMilli(timestampMs) : null;

        event.newStatus = record.getString("newStatus");
        event.reason = record.getString("reason");

        return event;
    }

    @Override
    public GenericRecord toGenericRecord() {
        return GenericRecordBuilder.compact(SCHEMA_NAME)
                .setString("eventId", eventId)
                .setString("eventType", eventType)
                .setString("eventVersion", eventVersion)
                .setString("source", source)
                .setInt64("timestamp", timestamp != null ? timestamp.toEpochMilli() : 0)
                .setString("key", key)
                .setString("correlationId", correlationId)
                .setString("sagaId", sagaId)
                .setString("sagaType", sagaType)
                .setInt32("stepNumber", stepNumber != null ? stepNumber : 0)
                .setBoolean("isCompensating", isCompensating != null && isCompensating)
                .setString("newStatus", newStatus)
                .setString("reason", reason)
                .build();
    }

    @Override
    public GenericRecord apply(GenericRecord currentState) {
        if (currentState == null) {
            throw new IllegalStateException("Cannot change status of a non-existent customer");
        }

        Instant now = Instant.now();
        return GenericRecordBuilder.compact(Customer.SCHEMA_NAME)
                .setString("customerId", currentState.getString("customerId"))
                .setString("email", currentState.getString("email"))
                .setString("name", currentState.getString("name"))
                .setString("address", currentState.getString("address"))
                .setString("phone", currentState.getString("phone"))
                .setString("status", newStatus)
                .setInt64("createdAt", currentState.getInt64("createdAt"))
                .setInt64("updatedAt", now.toEpochMilli())
                .build();
    }

    @Override
    public String getSchemaName() {
        return SCHEMA_NAME;
    }

    // Getters and Setters

    public String getNewStatus() {
        return newStatus;
    }

    public void setNewStatus(String newStatus) {
        this.newStatus = newStatus;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    @Override
    public String toString() {
        return "CustomerStatusChangedEvent{" +
                "eventId='" + eventId + '\'' +
                ", customerId='" + key + '\'' +
                ", newStatus='" + newStatus + '\'' +
                ", reason='" + reason + '\'' +
                '}';
    }
}
