package com.theyawns.ecommerce.common.events;

import com.hazelcast.nio.serialization.genericrecord.GenericRecord;
import com.hazelcast.nio.serialization.genericrecord.GenericRecordBuilder;
import com.theyawns.framework.event.DomainEvent;
import com.theyawns.ecommerce.common.domain.Customer;

import java.time.Instant;

/**
 * Event representing an update to customer information.
 *
 * <p>Updates can include:
 * <ul>
 *   <li>Name changes</li>
 *   <li>Address updates</li>
 *   <li>Phone number changes</li>
 * </ul>
 *
 * <p>Note: Email changes are not allowed (used as identity).
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
public class CustomerUpdatedEvent extends DomainEvent<Customer, String> {

    private static final long serialVersionUID = 1L;
    public static final String SCHEMA_NAME = "CustomerUpdatedEvent";
    public static final String EVENT_TYPE = "CustomerUpdated";

    private String name;
    private String address;
    private String phone;

    /**
     * Default constructor for serialization.
     */
    public CustomerUpdatedEvent() {
        super();
        this.eventType = EVENT_TYPE;
    }

    /**
     * Creates a new CustomerUpdatedEvent.
     *
     * @param customerId the customer ID
     * @param name the new name (null if unchanged)
     * @param address the new address (null if unchanged)
     * @param phone the new phone (null if unchanged)
     */
    public CustomerUpdatedEvent(String customerId, String name, String address, String phone) {
        super(customerId);
        this.eventType = EVENT_TYPE;
        this.name = name;
        this.address = address;
        this.phone = phone;
    }

    /**
     * Creates a CustomerUpdatedEvent from a GenericRecord.
     *
     * @param record the GenericRecord to hydrate from
     * @return the hydrated event
     */
    public static CustomerUpdatedEvent fromGenericRecord(GenericRecord record) {
        if (record == null) {
            return null;
        }
        CustomerUpdatedEvent event = new CustomerUpdatedEvent();
        event.eventId = record.getString("eventId");
        event.eventType = record.getString("eventType");
        event.eventVersion = record.getString("eventVersion");
        event.source = record.getString("source");
        event.key = record.getString("key");
        event.correlationId = record.getString("correlationId");

        Long timestampMs = record.getInt64("timestamp");
        event.timestamp = timestampMs != null && timestampMs != 0 ? Instant.ofEpochMilli(timestampMs) : null;

        event.name = record.getString("name");
        event.address = record.getString("address");
        event.phone = record.getString("phone");

        return event;
    }

    @Override
    public GenericRecord toGenericRecord() {
        return GenericRecordBuilder.compact(SCHEMA_NAME)
                .setString("eventId", eventId)
                .setString("eventType", eventType)
                .setString("eventVersion", eventVersion)
                .setString("source", source)
                .setInt64("timestamp", timestamp != null ? timestamp.toEpochMilli() : 0)
                .setString("key", key)
                .setString("correlationId", correlationId)
                .setString("sagaId", sagaId)
                .setString("sagaType", sagaType)
                .setInt32("stepNumber", stepNumber != null ? stepNumber : 0)
                .setBoolean("isCompensating", isCompensating != null && isCompensating)
                .setString("name", name)
                .setString("address", address)
                .setString("phone", phone)
                .build();
    }

    @Override
    public GenericRecord apply(GenericRecord currentState) {
        if (currentState == null) {
            throw new IllegalStateException("Cannot update a non-existent customer");
        }

        // Apply changes to existing state
        Instant now = Instant.now();
        return GenericRecordBuilder.compact(Customer.SCHEMA_NAME)
                .setString("customerId", currentState.getString("customerId"))
                .setString("email", currentState.getString("email"))
                .setString("name", name != null ? name : currentState.getString("name"))
                .setString("address", address != null ? address : currentState.getString("address"))
                .setString("phone", phone != null ? phone : currentState.getString("phone"))
                .setString("status", currentState.getString("status"))
                .setInt64("createdAt", currentState.getInt64("createdAt"))
                .setInt64("updatedAt", now.toEpochMilli())
                .build();
    }

    @Override
    public String getSchemaName() {
        return SCHEMA_NAME;
    }

    // Getters and Setters

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    @Override
    public String toString() {
        return "CustomerUpdatedEvent{" +
                "eventId='" + eventId + '\'' +
                ", customerId='" + key + '\'' +
                ", name='" + name + '\'' +
                '}';
    }
}
