package com.theyawns.ecommerce.common.events;

import com.hazelcast.nio.serialization.genericrecord.GenericRecord;
import com.hazelcast.nio.serialization.genericrecord.GenericRecordBuilder;
import com.theyawns.framework.event.DomainEvent;
import com.theyawns.framework.saga.SagaCompensationConfig;
import com.theyawns.framework.saga.SagaEvent;
import com.theyawns.ecommerce.common.domain.Order;
import com.theyawns.ecommerce.common.domain.OrderLineItem;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;

/**
 * Event representing the creation of a new order.
 *
 * <p>This event initializes a new order with:
 * <ul>
 *   <li>Unique order ID</li>
 *   <li>Customer reference</li>
 *   <li>Line items with products and quantities</li>
 *   <li>PENDING status</li>
 * </ul>
 *
 * <p>After order creation, the order service typically triggers
 * stock reservation in the inventory service.
 *
 * <p>In the Order Fulfillment saga, this is Step 0. If the saga fails,
 * this event is compensated by {@link OrderCancelledEvent}.
 *
 * @author Generated by Claude Code
 * @since 1.0
 * @see OrderCancelledEvent
 * @see SagaEvent
 */
public class OrderCreatedEvent extends DomainEvent<Order, String>
        implements SagaEvent<Order, String> {

    private static final long serialVersionUID = 1L;
    public static final String SCHEMA_NAME = "OrderCreatedEvent";
    public static final String EVENT_TYPE = "OrderCreated";

    private String customerId;
    private String customerName;
    private String customerEmail;
    private List<OrderLineItem> lineItems = new ArrayList<>();
    private String shippingAddress;
    private BigDecimal subtotal;
    private BigDecimal tax;
    private BigDecimal total;

    /**
     * Default constructor for serialization.
     */
    public OrderCreatedEvent() {
        super();
        this.eventType = EVENT_TYPE;
    }

    /**
     * Creates a new OrderCreatedEvent.
     *
     * @param orderId the unique order ID
     * @param customerId the customer ID
     * @param lineItems the order line items
     * @param shippingAddress the shipping address
     */
    public OrderCreatedEvent(String orderId, String customerId,
                             List<OrderLineItem> lineItems, String shippingAddress) {
        super(orderId);
        this.eventType = EVENT_TYPE;
        this.customerId = customerId;
        this.lineItems = lineItems != null ? lineItems : new ArrayList<>();
        this.shippingAddress = shippingAddress;
        calculateTotals();
    }

    private void calculateTotals() {
        this.subtotal = lineItems.stream()
                .map(OrderLineItem::getLineTotal)
                .filter(java.util.Objects::nonNull)
                .reduce(BigDecimal.ZERO, BigDecimal::add);

        this.tax = subtotal.multiply(new BigDecimal("0.10"));
        this.total = subtotal.add(tax);
    }

    /**
     * Creates an OrderCreatedEvent from a GenericRecord.
     *
     * @param record the GenericRecord to hydrate from
     * @return the hydrated event
     */
    public static OrderCreatedEvent fromGenericRecord(GenericRecord record) {
        if (record == null) {
            return null;
        }
        OrderCreatedEvent event = new OrderCreatedEvent();
        event.eventId = record.getString("eventId");
        event.eventType = record.getString("eventType");
        event.eventVersion = record.getString("eventVersion");
        event.source = record.getString("source");
        event.key = record.getString("key");
        event.correlationId = record.getString("correlationId");

        Long timestampMs = record.getInt64("timestamp");
        event.timestamp = timestampMs != null && timestampMs != 0 ? Instant.ofEpochMilli(timestampMs) : null;

        event.customerId = record.getString("customerId");
        event.customerName = record.getString("customerName");
        event.customerEmail = record.getString("customerEmail");
        event.shippingAddress = record.getString("shippingAddress");

        String subtotalStr = record.getString("subtotal");
        event.subtotal = subtotalStr != null ? new BigDecimal(subtotalStr) : null;

        String taxStr = record.getString("tax");
        event.tax = taxStr != null ? new BigDecimal(taxStr) : null;

        String totalStr = record.getString("total");
        event.total = totalStr != null ? new BigDecimal(totalStr) : null;

        GenericRecord[] itemRecords = record.getArrayOfGenericRecord("lineItems");
        if (itemRecords != null) {
            event.lineItems = new ArrayList<>();
            for (GenericRecord itemRecord : itemRecords) {
                event.lineItems.add(OrderLineItem.fromGenericRecord(itemRecord));
            }
        }

        return event;
    }

    @Override
    public GenericRecord toGenericRecord() {
        GenericRecord[] itemRecords = lineItems.stream()
                .map(OrderLineItem::toGenericRecord)
                .toArray(GenericRecord[]::new);

        return GenericRecordBuilder.compact(SCHEMA_NAME)
                .setString("eventId", eventId)
                .setString("eventType", eventType)
                .setString("eventVersion", eventVersion)
                .setString("source", source)
                .setInt64("timestamp", timestamp != null ? timestamp.toEpochMilli() : 0)
                .setString("key", key)
                .setString("correlationId", correlationId)
                .setString("sagaId", sagaId)
                .setString("sagaType", sagaType)
                .setInt32("stepNumber", stepNumber != null ? stepNumber : 0)
                .setBoolean("isCompensating", isCompensating != null && isCompensating)
                .setString("customerId", customerId)
                .setString("customerName", customerName)
                .setString("customerEmail", customerEmail)
                .setArrayOfGenericRecord("lineItems", itemRecords)
                .setString("shippingAddress", shippingAddress)
                .setString("subtotal", subtotal != null ? subtotal.toString() : null)
                .setString("tax", tax != null ? tax.toString() : null)
                .setString("total", total != null ? total.toString() : null)
                .build();
    }

    @Override
    public GenericRecord apply(GenericRecord domainObjectRecord) {
        GenericRecord[] itemRecords = lineItems.stream()
                .map(OrderLineItem::toGenericRecord)
                .toArray(GenericRecord[]::new);

        Instant now = Instant.now();
        return GenericRecordBuilder.compact(Order.SCHEMA_NAME)
                .setString("orderId", key)
                .setString("customerId", customerId)
                .setString("customerName", customerName)
                .setString("customerEmail", customerEmail)
                .setArrayOfGenericRecord("lineItems", itemRecords)
                .setString("subtotal", subtotal != null ? subtotal.toString() : null)
                .setString("tax", tax != null ? tax.toString() : null)
                .setString("total", total != null ? total.toString() : null)
                .setString("shippingAddress", shippingAddress)
                .setString("status", Order.Status.PENDING.name())
                .setInt64("createdAt", now.toEpochMilli())
                .setInt64("updatedAt", now.toEpochMilli())
                .build();
    }

    @Override
    public String getSchemaName() {
        return SCHEMA_NAME;
    }

    // Getters and Setters

    public String getCustomerId() {
        return customerId;
    }

    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    public String getCustomerName() {
        return customerName;
    }

    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    public String getCustomerEmail() {
        return customerEmail;
    }

    public void setCustomerEmail(String customerEmail) {
        this.customerEmail = customerEmail;
    }

    public List<OrderLineItem> getLineItems() {
        return lineItems;
    }

    public void setLineItems(List<OrderLineItem> lineItems) {
        this.lineItems = lineItems != null ? lineItems : new ArrayList<>();
        calculateTotals();
    }

    public String getShippingAddress() {
        return shippingAddress;
    }

    public void setShippingAddress(String shippingAddress) {
        this.shippingAddress = shippingAddress;
    }

    public BigDecimal getSubtotal() {
        return subtotal;
    }

    public BigDecimal getTax() {
        return tax;
    }

    public BigDecimal getTotal() {
        return total;
    }

    @Override
    public String toString() {
        return "OrderCreatedEvent{" +
                "eventId='" + eventId + '\'' +
                ", orderId='" + key + '\'' +
                ", customerId='" + customerId + '\'' +
                ", itemCount=" + lineItems.size() +
                ", total=" + total +
                '}';
    }

    // SagaEvent interface implementation

    /**
     * Returns step 0 - OrderCreated is the first step in the Order Fulfillment saga.
     *
     * @return 0 (first step)
     */
    @Override
    public int getSagaStepNumber() {
        return SagaCompensationConfig.STEP_ORDER_CREATED;
    }

    /**
     * Returns "OrderCancelled" as the compensating event type.
     *
     * @return the compensating event type
     */
    @Override
    public String getCompensatingEventType() {
        return SagaCompensationConfig.ORDER_CANCELLED;
    }

    /**
     * OrderCreatedEvent is a forward event, not a compensation event.
     *
     * @return false
     */
    @Override
    public boolean isCompensatingEvent() {
        return false;
    }

    /**
     * Returns the saga type name for Order Fulfillment.
     *
     * @return "OrderFulfillment"
     */
    @Override
    public String getSagaTypeName() {
        return SagaCompensationConfig.ORDER_FULFILLMENT_SAGA;
    }
}
