package com.theyawns.ecommerce.common.events;

import com.hazelcast.nio.serialization.genericrecord.GenericRecord;
import com.hazelcast.nio.serialization.genericrecord.GenericRecordBuilder;
import com.theyawns.framework.event.DomainEvent;
import com.theyawns.framework.saga.SagaCompensationConfig;
import com.theyawns.framework.saga.SagaEvent;
import com.theyawns.ecommerce.common.domain.Order;

import java.time.Instant;

/**
 * Event representing order cancellation.
 *
 * <p>An order can be cancelled:
 * <ul>
 *   <li>By customer request (before shipping)</li>
 *   <li>Due to payment failure</li>
 *   <li>Due to stock unavailability</li>
 *   <li>By system timeout</li>
 * </ul>
 *
 * <p>Cancellation triggers compensating actions:
 * <ul>
 *   <li>Release reserved stock</li>
 *   <li>Refund payment (if applicable)</li>
 *   <li>Send notification to customer</li>
 * </ul>
 *
 * <p>This is the compensating event for {@link OrderCreatedEvent} in the
 * Order Fulfillment saga. It undoes step 0 (order creation).
 *
 * @author Generated by Claude Code
 * @since 1.0
 * @see OrderCreatedEvent
 * @see SagaEvent
 */
public class OrderCancelledEvent extends DomainEvent<Order, String>
        implements SagaEvent<Order, String> {

    private static final long serialVersionUID = 1L;
    public static final String SCHEMA_NAME = "OrderCancelledEvent";
    public static final String EVENT_TYPE = "OrderCancelled";

    private String reason;
    private String cancelledBy;

    /**
     * Default constructor for serialization.
     */
    public OrderCancelledEvent() {
        super();
        this.eventType = EVENT_TYPE;
    }

    /**
     * Creates a new OrderCancelledEvent.
     *
     * @param orderId the order ID
     * @param reason the cancellation reason
     * @param cancelledBy who cancelled (customer, system, admin)
     */
    public OrderCancelledEvent(String orderId, String reason, String cancelledBy) {
        super(orderId);
        this.eventType = EVENT_TYPE;
        this.reason = reason;
        this.cancelledBy = cancelledBy;
    }

    /**
     * Creates an OrderCancelledEvent from a GenericRecord.
     *
     * @param record the GenericRecord to hydrate from
     * @return the hydrated event
     */
    public static OrderCancelledEvent fromGenericRecord(GenericRecord record) {
        if (record == null) {
            return null;
        }
        OrderCancelledEvent event = new OrderCancelledEvent();
        event.eventId = record.getString("eventId");
        event.eventType = record.getString("eventType");
        event.eventVersion = record.getString("eventVersion");
        event.source = record.getString("source");
        event.key = record.getString("key");
        event.correlationId = record.getString("correlationId");

        Long timestampMs = record.getInt64("timestamp");
        event.timestamp = timestampMs != null && timestampMs != 0 ? Instant.ofEpochMilli(timestampMs) : null;

        event.reason = record.getString("reason");
        event.cancelledBy = record.getString("cancelledBy");

        // Saga fields
        event.sagaId = record.getString("sagaId");
        event.sagaType = record.getString("sagaType");
        event.stepNumber = record.getInt32("stepNumber");
        event.isCompensating = record.getBoolean("isCompensating");

        return event;
    }

    @Override
    public GenericRecord toGenericRecord() {
        return GenericRecordBuilder.compact(SCHEMA_NAME)
                .setString("eventId", eventId)
                .setString("eventType", eventType)
                .setString("eventVersion", eventVersion)
                .setString("source", source)
                .setInt64("timestamp", timestamp != null ? timestamp.toEpochMilli() : 0)
                .setString("key", key)
                .setString("correlationId", correlationId)
                .setString("sagaId", sagaId)
                .setString("sagaType", sagaType)
                .setInt32("stepNumber", stepNumber != null ? stepNumber : 0)
                .setBoolean("isCompensating", isCompensating != null && isCompensating)
                .setString("reason", reason)
                .setString("cancelledBy", cancelledBy)
                .build();
    }

    @Override
    public GenericRecord apply(GenericRecord currentState) {
        if (currentState == null) {
            throw new IllegalStateException("Cannot cancel a non-existent order");
        }

        Instant now = Instant.now();
        return GenericRecordBuilder.compact(Order.SCHEMA_NAME)
                .setString("orderId", currentState.getString("orderId"))
                .setString("customerId", currentState.getString("customerId"))
                .setString("customerName", currentState.getString("customerName"))
                .setString("customerEmail", currentState.getString("customerEmail"))
                .setArrayOfGenericRecord("lineItems", currentState.getArrayOfGenericRecord("lineItems"))
                .setString("subtotal", currentState.getString("subtotal"))
                .setString("tax", currentState.getString("tax"))
                .setString("total", currentState.getString("total"))
                .setString("shippingAddress", currentState.getString("shippingAddress"))
                .setString("status", Order.Status.CANCELLED.name())
                .setInt64("createdAt", currentState.getInt64("createdAt"))
                .setInt64("updatedAt", now.toEpochMilli())
                .build();
    }

    @Override
    public String getSchemaName() {
        return SCHEMA_NAME;
    }

    // Getters and Setters

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    public String getCancelledBy() {
        return cancelledBy;
    }

    public void setCancelledBy(String cancelledBy) {
        this.cancelledBy = cancelledBy;
    }

    @Override
    public String toString() {
        return "OrderCancelledEvent{" +
                "eventId='" + eventId + '\'' +
                ", orderId='" + key + '\'' +
                ", reason='" + reason + '\'' +
                ", cancelledBy='" + cancelledBy + '\'' +
                '}';
    }

    // SagaEvent interface implementation

    /**
     * Returns step 0 - compensates the OrderCreated step.
     *
     * @return 0 (compensates first step)
     */
    @Override
    public int getSagaStepNumber() {
        return SagaCompensationConfig.STEP_ORDER_CREATED;
    }

    /**
     * Compensation events don't have their own compensating event.
     *
     * @return null
     */
    @Override
    public String getCompensatingEventType() {
        return null;
    }

    /**
     * OrderCancelledEvent is a compensation event that undoes OrderCreated.
     *
     * @return true
     */
    @Override
    public boolean isCompensatingEvent() {
        return true;
    }

    /**
     * Returns the saga type name for Order Fulfillment.
     *
     * @return "OrderFulfillment"
     */
    @Override
    public String getSagaTypeName() {
        return SagaCompensationConfig.ORDER_FULFILLMENT_SAGA;
    }
}
