package com.theyawns.ecommerce.common.events;

import com.hazelcast.nio.serialization.genericrecord.GenericRecord;
import com.hazelcast.nio.serialization.genericrecord.GenericRecordBuilder;
import com.theyawns.framework.event.DomainEvent;
import com.theyawns.ecommerce.common.domain.Order;

import java.time.Instant;

/**
 * Event representing order confirmation.
 *
 * <p>An order is confirmed when:
 * <ul>
 *   <li>Stock has been reserved for all line items</li>
 *   <li>Payment has been verified (if applicable)</li>
 *   <li>Customer information has been validated</li>
 * </ul>
 *
 * <p>After confirmation, the order status changes from PENDING to CONFIRMED.
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
public class OrderConfirmedEvent extends DomainEvent<Order, String> {

    private static final long serialVersionUID = 1L;
    public static final String SCHEMA_NAME = "OrderConfirmedEvent";
    public static final String EVENT_TYPE = "OrderConfirmed";

    private String confirmationNumber;

    /**
     * Default constructor for serialization.
     */
    public OrderConfirmedEvent() {
        super();
        this.eventType = EVENT_TYPE;
    }

    /**
     * Creates a new OrderConfirmedEvent.
     *
     * @param orderId the order ID
     * @param confirmationNumber the confirmation number
     */
    public OrderConfirmedEvent(String orderId, String confirmationNumber) {
        super(orderId);
        this.eventType = EVENT_TYPE;
        this.confirmationNumber = confirmationNumber;
    }

    /**
     * Creates an OrderConfirmedEvent from a GenericRecord.
     *
     * @param record the GenericRecord to hydrate from
     * @return the hydrated event
     */
    public static OrderConfirmedEvent fromGenericRecord(GenericRecord record) {
        if (record == null) {
            return null;
        }
        OrderConfirmedEvent event = new OrderConfirmedEvent();
        event.eventId = record.getString("eventId");
        event.eventType = record.getString("eventType");
        event.eventVersion = record.getString("eventVersion");
        event.source = record.getString("source");
        event.key = record.getString("key");
        event.correlationId = record.getString("correlationId");

        Long timestampMs = record.getInt64("timestamp");
        event.timestamp = timestampMs != null && timestampMs != 0 ? Instant.ofEpochMilli(timestampMs) : null;

        event.confirmationNumber = record.getString("confirmationNumber");

        return event;
    }

    @Override
    public GenericRecord toGenericRecord() {
        return GenericRecordBuilder.compact(SCHEMA_NAME)
                .setString("eventId", eventId)
                .setString("eventType", eventType)
                .setString("eventVersion", eventVersion)
                .setString("source", source)
                .setInt64("timestamp", timestamp != null ? timestamp.toEpochMilli() : 0)
                .setString("key", key)
                .setString("correlationId", correlationId)
                .setString("sagaId", sagaId)
                .setString("sagaType", sagaType)
                .setInt32("stepNumber", stepNumber != null ? stepNumber : 0)
                .setBoolean("isCompensating", isCompensating != null && isCompensating)
                .setString("confirmationNumber", confirmationNumber)
                .build();
    }

    @Override
    public GenericRecord apply(GenericRecord currentState) {
        if (currentState == null) {
            throw new IllegalStateException("Cannot confirm a non-existent order");
        }

        Instant now = Instant.now();
        return GenericRecordBuilder.compact(Order.SCHEMA_NAME)
                .setString("orderId", currentState.getString("orderId"))
                .setString("customerId", currentState.getString("customerId"))
                .setString("customerName", currentState.getString("customerName"))
                .setString("customerEmail", currentState.getString("customerEmail"))
                .setArrayOfGenericRecord("lineItems", currentState.getArrayOfGenericRecord("lineItems"))
                .setString("subtotal", currentState.getString("subtotal"))
                .setString("tax", currentState.getString("tax"))
                .setString("total", currentState.getString("total"))
                .setString("shippingAddress", currentState.getString("shippingAddress"))
                .setString("status", Order.Status.CONFIRMED.name())
                .setInt64("createdAt", currentState.getInt64("createdAt"))
                .setInt64("updatedAt", now.toEpochMilli())
                .build();
    }

    @Override
    public String getSchemaName() {
        return SCHEMA_NAME;
    }

    // Getters and Setters

    public String getConfirmationNumber() {
        return confirmationNumber;
    }

    public void setConfirmationNumber(String confirmationNumber) {
        this.confirmationNumber = confirmationNumber;
    }

    @Override
    public String toString() {
        return "OrderConfirmedEvent{" +
                "eventId='" + eventId + '\'' +
                ", orderId='" + key + '\'' +
                ", confirmationNumber='" + confirmationNumber + '\'' +
                '}';
    }
}
