package com.theyawns.ecommerce.common.events;

import com.hazelcast.nio.serialization.genericrecord.GenericRecord;
import com.hazelcast.nio.serialization.genericrecord.GenericRecordBuilder;
import com.theyawns.framework.event.DomainEvent;
import com.theyawns.framework.saga.SagaCompensationConfig;
import com.theyawns.framework.saga.SagaEvent;
import com.theyawns.ecommerce.common.domain.Payment;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * Event representing a failed payment attempt.
 *
 * <p>A payment failure triggers saga compensation to roll back
 * previous steps (release stock, cancel order). This event:
 * <ul>
 *   <li>Records the failure reason</li>
 *   <li>Triggers compensation for prior saga steps</li>
 *   <li>Creates a FAILED payment view entry</li>
 * </ul>
 *
 * <p>In the Order Fulfillment saga, this event at Step 2 triggers
 * compensation of Steps 1 and 0 (StockReleased, OrderCancelled).
 *
 * @author Generated by Claude Code
 * @since 2.0
 * @see PaymentProcessedEvent
 * @see SagaEvent
 */
public class PaymentFailedEvent extends DomainEvent<Payment, String>
        implements SagaEvent<Payment, String> {

    private static final long serialVersionUID = 1L;
    public static final String SCHEMA_NAME = "PaymentFailedEvent";
    public static final String EVENT_TYPE = "PaymentFailed";

    private String orderId;
    private String customerId;
    private String amount;
    private String currency;
    private String failureReason;
    private String method;

    /**
     * Default constructor for serialization.
     */
    public PaymentFailedEvent() {
        super();
        this.eventType = EVENT_TYPE;
    }

    /**
     * Creates a new PaymentFailedEvent.
     *
     * @param paymentId the payment ID
     * @param orderId the order ID
     * @param customerId the customer ID
     * @param amount the attempted payment amount
     * @param currency the currency code
     * @param failureReason the reason for failure
     * @param method the payment method attempted
     */
    public PaymentFailedEvent(String paymentId, String orderId, String customerId,
                               BigDecimal amount, String currency,
                               String failureReason, String method) {
        super(paymentId);
        this.eventType = EVENT_TYPE;
        this.orderId = orderId;
        this.customerId = customerId;
        this.amount = amount != null ? amount.toString() : null;
        this.currency = currency;
        this.failureReason = failureReason;
        this.method = method;
    }

    /**
     * Creates a PaymentFailedEvent from a GenericRecord.
     *
     * @param record the GenericRecord to hydrate from
     * @return the hydrated event
     */
    public static PaymentFailedEvent fromGenericRecord(GenericRecord record) {
        if (record == null) {
            return null;
        }
        PaymentFailedEvent event = new PaymentFailedEvent();
        event.eventId = record.getString("eventId");
        event.eventType = record.getString("eventType");
        event.eventVersion = record.getString("eventVersion");
        event.source = record.getString("source");
        event.key = record.getString("key");
        event.correlationId = record.getString("correlationId");

        Long timestampMs = record.getInt64("timestamp");
        event.timestamp = timestampMs != null && timestampMs != 0 ? Instant.ofEpochMilli(timestampMs) : null;

        event.orderId = record.getString("orderId");
        event.customerId = record.getString("customerId");
        event.amount = record.getString("amount");
        event.currency = record.getString("currency");
        event.failureReason = record.getString("failureReason");
        event.method = record.getString("method");

        // Saga fields
        event.sagaId = record.getString("sagaId");
        event.sagaType = record.getString("sagaType");
        event.stepNumber = record.getInt32("stepNumber");
        event.isCompensating = record.getBoolean("isCompensating");

        return event;
    }

    @Override
    public GenericRecord toGenericRecord() {
        return GenericRecordBuilder.compact(SCHEMA_NAME)
                .setString("eventId", eventId)
                .setString("eventType", eventType)
                .setString("eventVersion", eventVersion)
                .setString("source", source)
                .setInt64("timestamp", timestamp != null ? timestamp.toEpochMilli() : 0)
                .setString("key", key)
                .setString("correlationId", correlationId)
                .setString("sagaId", sagaId)
                .setString("sagaType", sagaType)
                .setInt32("stepNumber", stepNumber != null ? stepNumber : 0)
                .setBoolean("isCompensating", isCompensating != null && isCompensating)
                .setString("orderId", orderId)
                .setString("customerId", customerId)
                .setString("amount", amount)
                .setString("currency", currency)
                .setString("failureReason", failureReason)
                .setString("method", method)
                .build();
    }

    @Override
    public GenericRecord apply(GenericRecord currentState) {
        // PaymentFailed creates a FAILED payment view entry
        Instant now = Instant.now();
        return GenericRecordBuilder.compact(Payment.SCHEMA_NAME)
                .setString("paymentId", key)
                .setString("orderId", orderId)
                .setString("customerId", customerId)
                .setString("amount", amount)
                .setString("currency", currency)
                .setString("method", method)
                .setString("status", Payment.PaymentStatus.FAILED.name())
                .setString("transactionId", null)
                .setInt64("processedAt", now.toEpochMilli())
                .setString("failureReason", failureReason)
                .setInt64("createdAt", now.toEpochMilli())
                .setInt64("updatedAt", now.toEpochMilli())
                .build();
    }

    @Override
    public String getSchemaName() {
        return SCHEMA_NAME;
    }

    // Getters and Setters

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public String getCustomerId() {
        return customerId;
    }

    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    public String getAmount() {
        return amount;
    }

    public void setAmount(String amount) {
        this.amount = amount;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public String getFailureReason() {
        return failureReason;
    }

    public void setFailureReason(String failureReason) {
        this.failureReason = failureReason;
    }

    public String getMethod() {
        return method;
    }

    public void setMethod(String method) {
        this.method = method;
    }

    @Override
    public String toString() {
        return "PaymentFailedEvent{" +
                "eventId='" + eventId + '\'' +
                ", paymentId='" + key + '\'' +
                ", orderId='" + orderId + '\'' +
                ", amount='" + amount + '\'' +
                ", failureReason='" + failureReason + '\'' +
                '}';
    }

    // SagaEvent interface implementation

    /**
     * Returns step 2 - PaymentFailed occurs at the payment step.
     *
     * @return 2 (third step)
     */
    @Override
    public int getSagaStepNumber() {
        return SagaCompensationConfig.STEP_PAYMENT_PROCESSED;
    }

    /**
     * PaymentFailed is itself a failure event; it does not have a compensating event.
     * Instead, it triggers compensation of prior steps.
     *
     * @return null
     */
    @Override
    public String getCompensatingEventType() {
        return null;
    }

    /**
     * PaymentFailedEvent is not a compensation event; it is a failure event
     * that triggers compensation of prior steps.
     *
     * @return false
     */
    @Override
    public boolean isCompensatingEvent() {
        return false;
    }

    /**
     * Returns the saga type name for Order Fulfillment.
     *
     * @return "OrderFulfillment"
     */
    @Override
    public String getSagaTypeName() {
        return SagaCompensationConfig.ORDER_FULFILLMENT_SAGA;
    }
}
