package com.theyawns.ecommerce.common.events;

import com.hazelcast.nio.serialization.genericrecord.GenericRecord;
import com.hazelcast.nio.serialization.genericrecord.GenericRecordBuilder;
import com.theyawns.framework.event.DomainEvent;
import com.theyawns.ecommerce.common.domain.Product;

import java.math.BigDecimal;
import java.time.Instant;

/**
 * Event representing the creation of a new product.
 *
 * <p>This event initializes a new product with:
 * <ul>
 *   <li>Unique product ID</li>
 *   <li>SKU and name</li>
 *   <li>Price and initial quantity</li>
 *   <li>ACTIVE status</li>
 * </ul>
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
public class ProductCreatedEvent extends DomainEvent<Product, String> {

    public static final String SCHEMA_NAME = "ProductCreatedEvent";
    public static final String EVENT_TYPE = "ProductCreated";

    private String sku;
    private String name;
    private String description;
    private BigDecimal price;
    private int initialQuantity;
    private String category;

    /**
     * Default constructor for serialization.
     */
    public ProductCreatedEvent() {
        super();
        this.eventType = EVENT_TYPE;
    }

    /**
     * Creates a new ProductCreatedEvent.
     *
     * @param productId the unique product ID
     * @param sku the product SKU
     * @param name the product name
     * @param price the product price
     * @param initialQuantity the initial quantity on hand
     */
    public ProductCreatedEvent(String productId, String sku, String name,
                               BigDecimal price, int initialQuantity) {
        super(productId);
        this.eventType = EVENT_TYPE;
        this.sku = sku;
        this.name = name;
        this.price = price;
        this.initialQuantity = initialQuantity;
    }

    /**
     * Creates a ProductCreatedEvent from a GenericRecord.
     *
     * @param record the GenericRecord to hydrate from
     * @return the hydrated event
     */
    public static ProductCreatedEvent fromGenericRecord(GenericRecord record) {
        if (record == null) {
            return null;
        }
        ProductCreatedEvent event = new ProductCreatedEvent();
        event.eventId = record.getString("eventId");
        event.eventType = record.getString("eventType");
        event.eventVersion = record.getString("eventVersion");
        event.source = record.getString("source");
        event.key = record.getString("key");
        event.correlationId = record.getString("correlationId");

        Long timestampMs = record.getInt64("timestamp");
        event.timestamp = timestampMs != null && timestampMs != 0 ? Instant.ofEpochMilli(timestampMs) : null;

        event.sku = record.getString("sku");
        event.name = record.getString("name");
        event.description = record.getString("description");

        String priceStr = record.getString("price");
        event.price = priceStr != null ? new BigDecimal(priceStr) : null;

        event.initialQuantity = record.getInt32("initialQuantity");
        event.category = record.getString("category");

        return event;
    }

    @Override
    public GenericRecord toGenericRecord() {
        return GenericRecordBuilder.compact(SCHEMA_NAME)
                .setString("eventId", eventId)
                .setString("eventType", eventType)
                .setString("eventVersion", eventVersion)
                .setString("source", source)
                .setInt64("timestamp", timestamp != null ? timestamp.toEpochMilli() : 0)
                .setString("key", key)
                .setString("correlationId", correlationId)
                .setString("sagaId", sagaId)
                .setString("sagaType", sagaType)
                .setInt32("stepNumber", stepNumber != null ? stepNumber : 0)
                .setBoolean("isCompensating", isCompensating != null && isCompensating)
                .setString("sku", sku)
                .setString("name", name)
                .setString("description", description)
                .setString("price", price != null ? price.toString() : null)
                .setInt32("initialQuantity", initialQuantity)
                .setString("category", category)
                .build();
    }

    @Override
    public GenericRecord apply(GenericRecord domainObjectRecord) {
        Instant now = Instant.now();
        return GenericRecordBuilder.compact(Product.SCHEMA_NAME)
                .setString("productId", key)
                .setString("sku", sku)
                .setString("name", name)
                .setString("description", description)
                .setString("price", price != null ? price.toString() : null)
                .setInt32("quantityOnHand", initialQuantity)
                .setInt32("quantityReserved", 0)
                .setString("category", category)
                .setString("status", Product.Status.ACTIVE.name())
                .setInt64("createdAt", now.toEpochMilli())
                .setInt64("updatedAt", now.toEpochMilli())
                .build();
    }

    @Override
    public String getSchemaName() {
        return SCHEMA_NAME;
    }

    // Getters and Setters

    public String getSku() {
        return sku;
    }

    public void setSku(String sku) {
        this.sku = sku;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public int getInitialQuantity() {
        return initialQuantity;
    }

    public void setInitialQuantity(int initialQuantity) {
        this.initialQuantity = initialQuantity;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    @Override
    public String toString() {
        return "ProductCreatedEvent{" +
                "eventId='" + eventId + '\'' +
                ", productId='" + key + '\'' +
                ", sku='" + sku + '\'' +
                ", name='" + name + '\'' +
                ", price=" + price +
                ", quantity=" + initialQuantity +
                '}';
    }
}
