package com.theyawns.ecommerce.common.events;

import com.hazelcast.nio.serialization.genericrecord.GenericRecord;
import com.hazelcast.nio.serialization.genericrecord.GenericRecordBuilder;
import com.theyawns.ecommerce.common.domain.Product;
import com.theyawns.framework.event.DomainEvent;

import java.time.Instant;

/**
 * Event representing a failed stock reservation attempt.
 *
 * <p>Published when an order cannot be fulfilled because of insufficient stock.
 * This is a business outcome (not an infrastructure error) and triggers saga
 * compensation: the order is cancelled and the saga transitions to COMPENSATED.
 *
 * <p>Unlike infrastructure failures that go to the DLQ, this event flows through
 * the normal saga compensation path:
 * <ol>
 *   <li>Inventory service publishes StockReservationFailed to shared ITopic</li>
 *   <li>Order service listens, cancels the order, marks saga COMPENSATED</li>
 * </ol>
 *
 * @author Generated by Claude Code
 * @since 3.1
 * @see StockReservedEvent
 */
public class StockReservationFailedEvent extends DomainEvent<Product, String> {

    public static final String SCHEMA_NAME = "StockReservationFailedEvent";
    public static final String EVENT_TYPE = "StockReservationFailed";

    private String orderId;
    private String productId;
    private int requestedQuantity;
    private int availableQuantity;
    private String reason;

    /**
     * Default constructor for serialization.
     */
    public StockReservationFailedEvent() {
        super();
        this.eventType = EVENT_TYPE;
    }

    /**
     * Creates a new StockReservationFailedEvent.
     *
     * @param productId the product ID that could not be reserved
     * @param orderId the order ID that requested the reservation
     * @param requestedQuantity the quantity requested
     * @param availableQuantity the quantity actually available
     * @param reason the failure reason
     */
    public StockReservationFailedEvent(String productId, String orderId,
                                        int requestedQuantity, int availableQuantity,
                                        String reason) {
        super(productId);
        this.eventType = EVENT_TYPE;
        this.productId = productId;
        this.orderId = orderId;
        this.requestedQuantity = requestedQuantity;
        this.availableQuantity = availableQuantity;
        this.reason = reason;
    }

    /**
     * Creates a StockReservationFailedEvent from a GenericRecord.
     *
     * @param record the GenericRecord to hydrate from
     * @return the hydrated event
     */
    public static StockReservationFailedEvent fromGenericRecord(GenericRecord record) {
        if (record == null) {
            return null;
        }
        StockReservationFailedEvent event = new StockReservationFailedEvent();
        event.eventId = record.getString("eventId");
        event.eventType = record.getString("eventType");
        event.eventVersion = record.getString("eventVersion");
        event.source = record.getString("source");
        event.key = record.getString("key");
        event.correlationId = record.getString("correlationId");

        Long timestampMs = record.getInt64("timestamp");
        event.timestamp = timestampMs != null && timestampMs != 0 ? Instant.ofEpochMilli(timestampMs) : null;

        event.orderId = record.getString("orderId");
        event.productId = record.getString("productId");
        event.requestedQuantity = record.getInt32("requestedQuantity");
        event.availableQuantity = record.getInt32("availableQuantity");
        event.reason = record.getString("reason");

        // Saga fields
        event.sagaId = record.getString("sagaId");
        event.sagaType = record.getString("sagaType");

        return event;
    }

    @Override
    public GenericRecord toGenericRecord() {
        return GenericRecordBuilder.compact(SCHEMA_NAME)
                .setString("eventId", eventId)
                .setString("eventType", eventType)
                .setString("eventVersion", eventVersion)
                .setString("source", source)
                .setInt64("timestamp", timestamp != null ? timestamp.toEpochMilli() : 0)
                .setString("key", key)
                .setString("correlationId", correlationId)
                .setString("sagaId", sagaId)
                .setString("sagaType", sagaType)
                .setString("orderId", orderId)
                .setString("productId", productId)
                .setInt32("requestedQuantity", requestedQuantity)
                .setInt32("availableQuantity", availableQuantity)
                .setString("reason", reason)
                .build();
    }

    @Override
    public GenericRecord apply(GenericRecord currentState) {
        // This event does not modify product state — it's a notification event
        return currentState;
    }

    @Override
    public String getSchemaName() {
        return SCHEMA_NAME;
    }

    // Getters and Setters

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public String getProductId() {
        return productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public int getRequestedQuantity() {
        return requestedQuantity;
    }

    public void setRequestedQuantity(int requestedQuantity) {
        this.requestedQuantity = requestedQuantity;
    }

    public int getAvailableQuantity() {
        return availableQuantity;
    }

    public void setAvailableQuantity(int availableQuantity) {
        this.availableQuantity = availableQuantity;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    @Override
    public String toString() {
        return "StockReservationFailedEvent{" +
                "eventId='" + eventId + '\'' +
                ", orderId='" + orderId + '\'' +
                ", productId='" + productId + '\'' +
                ", requestedQuantity=" + requestedQuantity +
                ", availableQuantity=" + availableQuantity +
                ", reason='" + reason + '\'' +
                '}';
    }
}
