package com.theyawns.ecommerce.common.events;

import com.hazelcast.nio.serialization.genericrecord.GenericRecord;
import com.hazelcast.nio.serialization.genericrecord.GenericRecordBuilder;
import com.theyawns.framework.event.DomainEvent;
import com.theyawns.framework.saga.SagaCompensationConfig;
import com.theyawns.framework.saga.SagaEvent;
import com.theyawns.ecommerce.common.domain.Product;

import java.time.Instant;

/**
 * Event representing stock reservation for an order.
 *
 * <p>When an order is placed, stock is reserved to prevent
 * overselling. The reserved quantity is held until:
 * <ul>
 *   <li>Order is shipped (stock is deducted)</li>
 *   <li>Order is cancelled (stock is released)</li>
 * </ul>
 *
 * <p>In the Order Fulfillment saga, this is Step 1. If the saga fails,
 * this event is compensated by {@link StockReleasedEvent}.
 *
 * @author Generated by Claude Code
 * @since 1.0
 * @see StockReleasedEvent
 * @see SagaEvent
 */
public class StockReservedEvent extends DomainEvent<Product, String>
        implements SagaEvent<Product, String> {

    private static final long serialVersionUID = 1L;
    public static final String SCHEMA_NAME = "StockReservedEvent";
    public static final String EVENT_TYPE = "StockReserved";

    private int quantity;
    private String orderId;

    /**
     * Default constructor for serialization.
     */
    public StockReservedEvent() {
        super();
        this.eventType = EVENT_TYPE;
    }

    /**
     * Creates a new StockReservedEvent.
     *
     * @param productId the product ID
     * @param quantity the quantity to reserve
     * @param orderId the order ID that triggered the reservation
     */
    public StockReservedEvent(String productId, int quantity, String orderId) {
        super(productId);
        this.eventType = EVENT_TYPE;
        this.quantity = quantity;
        this.orderId = orderId;
    }

    /**
     * Creates a StockReservedEvent from a GenericRecord.
     *
     * @param record the GenericRecord to hydrate from
     * @return the hydrated event
     */
    public static StockReservedEvent fromGenericRecord(GenericRecord record) {
        if (record == null) {
            return null;
        }
        StockReservedEvent event = new StockReservedEvent();
        event.eventId = record.getString("eventId");
        event.eventType = record.getString("eventType");
        event.eventVersion = record.getString("eventVersion");
        event.source = record.getString("source");
        event.key = record.getString("key");
        event.correlationId = record.getString("correlationId");

        Long timestampMs = record.getInt64("timestamp");
        event.timestamp = timestampMs != null && timestampMs != 0 ? Instant.ofEpochMilli(timestampMs) : null;

        event.quantity = record.getInt32("quantity");
        event.orderId = record.getString("orderId");

        // Saga fields
        event.sagaId = record.getString("sagaId");
        event.sagaType = record.getString("sagaType");
        event.stepNumber = record.getInt32("stepNumber");
        event.isCompensating = record.getBoolean("isCompensating");

        return event;
    }

    @Override
    public GenericRecord toGenericRecord() {
        return GenericRecordBuilder.compact(SCHEMA_NAME)
                .setString("eventId", eventId)
                .setString("eventType", eventType)
                .setString("eventVersion", eventVersion)
                .setString("source", source)
                .setInt64("timestamp", timestamp != null ? timestamp.toEpochMilli() : 0)
                .setString("key", key)
                .setString("correlationId", correlationId)
                .setString("sagaId", sagaId)
                .setString("sagaType", sagaType)
                .setInt32("stepNumber", stepNumber != null ? stepNumber : 0)
                .setBoolean("isCompensating", isCompensating != null && isCompensating)
                .setInt32("quantity", quantity)
                .setString("orderId", orderId)
                .build();
    }

    @Override
    public GenericRecord apply(GenericRecord currentState) {
        if (currentState == null) {
            throw new IllegalStateException("Cannot reserve stock for a non-existent product");
        }

        int currentReserved = currentState.getInt32("quantityReserved");
        int newReserved = currentReserved + quantity;

        Instant now = Instant.now();
        return GenericRecordBuilder.compact(Product.SCHEMA_NAME)
                .setString("productId", currentState.getString("productId"))
                .setString("sku", currentState.getString("sku"))
                .setString("name", currentState.getString("name"))
                .setString("description", currentState.getString("description"))
                .setString("price", currentState.getString("price"))
                .setInt32("quantityOnHand", currentState.getInt32("quantityOnHand"))
                .setInt32("quantityReserved", newReserved)
                .setString("category", currentState.getString("category"))
                .setString("status", currentState.getString("status"))
                .setInt64("createdAt", currentState.getInt64("createdAt"))
                .setInt64("updatedAt", now.toEpochMilli())
                .build();
    }

    @Override
    public String getSchemaName() {
        return SCHEMA_NAME;
    }

    // Getters and Setters

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    @Override
    public String toString() {
        return "StockReservedEvent{" +
                "eventId='" + eventId + '\'' +
                ", productId='" + key + '\'' +
                ", quantity=" + quantity +
                ", orderId='" + orderId + '\'' +
                '}';
    }

    // SagaEvent interface implementation

    /**
     * Returns step 1 - StockReserved is the second step in the Order Fulfillment saga.
     *
     * @return 1 (second step)
     */
    @Override
    public int getSagaStepNumber() {
        return SagaCompensationConfig.STEP_STOCK_RESERVED;
    }

    /**
     * Returns "StockReleased" as the compensating event type.
     *
     * @return the compensating event type
     */
    @Override
    public String getCompensatingEventType() {
        return SagaCompensationConfig.STOCK_RELEASED;
    }

    /**
     * StockReservedEvent is a forward event, not a compensation event.
     *
     * @return false
     */
    @Override
    public boolean isCompensatingEvent() {
        return false;
    }

    /**
     * Returns the saga type name for Order Fulfillment.
     *
     * @return "OrderFulfillment"
     */
    @Override
    public String getSagaTypeName() {
        return SagaCompensationConfig.ORDER_FULFILLMENT_SAGA;
    }
}
