package com.theyawns.ecommerce.common.events;

import com.hazelcast.nio.serialization.genericrecord.GenericRecord;
import com.hazelcast.nio.serialization.genericrecord.GenericRecordBuilder;
import com.theyawns.framework.event.DomainEvent;
import com.theyawns.ecommerce.common.domain.Product;

import java.time.Instant;

/**
 * Event representing the release of previously reserved stock.
 *
 * <p>Stock is released when:
 * <ul>
 *   <li>An order is cancelled</li>
 *   <li>A reservation times out</li>
 *   <li>A saga compensates</li>
 * </ul>
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
public class StockReleasedEvent extends DomainEvent<Product, String> {

    private static final long serialVersionUID = 1L;
    public static final String SCHEMA_NAME = "StockReleasedEvent";
    public static final String EVENT_TYPE = "StockReleased";

    private int quantity;
    private String orderId;
    private String reason;

    /**
     * Default constructor for serialization.
     */
    public StockReleasedEvent() {
        super();
        this.eventType = EVENT_TYPE;
    }

    /**
     * Creates a new StockReleasedEvent.
     *
     * @param productId the product ID
     * @param quantity the quantity to release
     * @param orderId the order ID that triggered the release
     * @param reason the reason for releasing (e.g., "ORDER_CANCELLED")
     */
    public StockReleasedEvent(String productId, int quantity, String orderId, String reason) {
        super(productId);
        this.eventType = EVENT_TYPE;
        this.quantity = quantity;
        this.orderId = orderId;
        this.reason = reason;
    }

    /**
     * Creates a StockReleasedEvent from a GenericRecord.
     *
     * @param record the GenericRecord to hydrate from
     * @return the hydrated event
     */
    public static StockReleasedEvent fromGenericRecord(GenericRecord record) {
        if (record == null) {
            return null;
        }
        StockReleasedEvent event = new StockReleasedEvent();
        event.eventId = record.getString("eventId");
        event.eventType = record.getString("eventType");
        event.eventVersion = record.getString("eventVersion");
        event.source = record.getString("source");
        event.key = record.getString("key");
        event.correlationId = record.getString("correlationId");

        Long timestampMs = record.getInt64("timestamp");
        event.timestamp = timestampMs != null && timestampMs != 0 ? Instant.ofEpochMilli(timestampMs) : null;

        event.quantity = record.getInt32("quantity");
        event.orderId = record.getString("orderId");
        event.reason = record.getString("reason");

        // Saga fields
        event.sagaId = record.getString("sagaId");
        event.sagaType = record.getString("sagaType");
        event.stepNumber = record.getInt32("stepNumber");
        event.isCompensating = record.getBoolean("isCompensating");

        return event;
    }

    @Override
    public GenericRecord toGenericRecord() {
        return GenericRecordBuilder.compact(SCHEMA_NAME)
                .setString("eventId", eventId)
                .setString("eventType", eventType)
                .setString("eventVersion", eventVersion)
                .setString("source", source)
                .setInt64("timestamp", timestamp != null ? timestamp.toEpochMilli() : 0)
                .setString("key", key)
                .setString("correlationId", correlationId)
                .setString("sagaId", sagaId)
                .setString("sagaType", sagaType)
                .setInt32("stepNumber", stepNumber != null ? stepNumber : 0)
                .setBoolean("isCompensating", isCompensating != null && isCompensating)
                .setInt32("quantity", quantity)
                .setString("orderId", orderId)
                .setString("reason", reason)
                .build();
    }

    @Override
    public GenericRecord apply(GenericRecord currentState) {
        if (currentState == null) {
            throw new IllegalStateException("Cannot release stock for a non-existent product");
        }

        int currentReserved = currentState.getInt32("quantityReserved");
        int newReserved = Math.max(0, currentReserved - quantity);

        Instant now = Instant.now();
        return GenericRecordBuilder.compact(Product.SCHEMA_NAME)
                .setString("productId", currentState.getString("productId"))
                .setString("sku", currentState.getString("sku"))
                .setString("name", currentState.getString("name"))
                .setString("description", currentState.getString("description"))
                .setString("price", currentState.getString("price"))
                .setInt32("quantityOnHand", currentState.getInt32("quantityOnHand"))
                .setInt32("quantityReserved", newReserved)
                .setString("category", currentState.getString("category"))
                .setString("status", currentState.getString("status"))
                .setInt64("createdAt", currentState.getInt64("createdAt"))
                .setInt64("updatedAt", now.toEpochMilli())
                .build();
    }

    @Override
    public String getSchemaName() {
        return SCHEMA_NAME;
    }

    // Getters and Setters

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public String getOrderId() {
        return orderId;
    }

    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    @Override
    public String toString() {
        return "StockReleasedEvent{" +
                "eventId='" + eventId + '\'' +
                ", productId='" + key + '\'' +
                ", quantity=" + quantity +
                ", orderId='" + orderId + '\'' +
                ", reason='" + reason + '\'' +
                '}';
    }
}
