package com.theyawns.ecommerce.common.events;

import com.hazelcast.nio.serialization.genericrecord.GenericRecord;
import com.hazelcast.nio.serialization.genericrecord.GenericRecordBuilder;
import com.theyawns.ecommerce.common.domain.Product;
import com.theyawns.framework.event.DomainEvent;

import java.time.Instant;

/**
 * Event representing stock replenishment for a product.
 *
 * <p>Published when stock is added to a product, either through:
 * <ul>
 *   <li>Automatic reorder by {@code StockReplenishmentMonitor} when
 *       available quantity drops below the reorder point</li>
 *   <li>Manual replenishment via the REST API</li>
 * </ul>
 *
 * <p>The event flows through the Jet pipeline and updates the product
 * materialized view (increases {@code quantityOnHand}).
 *
 * @author Generated by Claude Code
 * @since 3.1
 * @see StockReservedEvent
 * @see StockReleasedEvent
 */
public class StockReplenishedEvent extends DomainEvent<Product, String> {

    public static final String SCHEMA_NAME = "StockReplenishedEvent";
    public static final String EVENT_TYPE = "StockReplenished";

    private int quantityAdded;
    private int newQuantityOnHand;
    private String reason;

    /**
     * Default constructor for serialization.
     */
    public StockReplenishedEvent() {
        super();
        this.eventType = EVENT_TYPE;
    }

    /**
     * Creates a new StockReplenishedEvent.
     *
     * @param productId the product ID
     * @param quantityAdded the quantity added
     * @param newQuantityOnHand the resulting total quantity on hand
     * @param reason the replenishment reason (e.g., "AUTO_REORDER", "MANUAL")
     */
    public StockReplenishedEvent(String productId, int quantityAdded,
                                  int newQuantityOnHand, String reason) {
        super(productId);
        this.eventType = EVENT_TYPE;
        this.quantityAdded = quantityAdded;
        this.newQuantityOnHand = newQuantityOnHand;
        this.reason = reason;
    }

    /**
     * Creates a StockReplenishedEvent from a GenericRecord.
     *
     * @param record the GenericRecord to hydrate from
     * @return the hydrated event
     */
    public static StockReplenishedEvent fromGenericRecord(GenericRecord record) {
        if (record == null) {
            return null;
        }
        StockReplenishedEvent event = new StockReplenishedEvent();
        event.eventId = record.getString("eventId");
        event.eventType = record.getString("eventType");
        event.eventVersion = record.getString("eventVersion");
        event.source = record.getString("source");
        event.key = record.getString("key");
        event.correlationId = record.getString("correlationId");

        Long timestampMs = record.getInt64("timestamp");
        event.timestamp = timestampMs != null && timestampMs != 0 ? Instant.ofEpochMilli(timestampMs) : null;

        event.quantityAdded = record.getInt32("quantityAdded");
        event.newQuantityOnHand = record.getInt32("newQuantityOnHand");
        event.reason = record.getString("reason");

        return event;
    }

    @Override
    public GenericRecord toGenericRecord() {
        return GenericRecordBuilder.compact(SCHEMA_NAME)
                .setString("eventId", eventId)
                .setString("eventType", eventType)
                .setString("eventVersion", eventVersion)
                .setString("source", source)
                .setInt64("timestamp", timestamp != null ? timestamp.toEpochMilli() : 0)
                .setString("key", key)
                .setString("correlationId", correlationId)
                .setInt32("quantityAdded", quantityAdded)
                .setInt32("newQuantityOnHand", newQuantityOnHand)
                .setString("reason", reason)
                .build();
    }

    @Override
    public GenericRecord apply(GenericRecord currentState) {
        if (currentState == null) {
            throw new IllegalStateException("Cannot replenish stock for a non-existent product");
        }

        int currentOnHand = currentState.getInt32("quantityOnHand");
        int updatedOnHand = currentOnHand + quantityAdded;

        Instant now = Instant.now();
        return GenericRecordBuilder.compact(Product.SCHEMA_NAME)
                .setString("productId", currentState.getString("productId"))
                .setString("sku", currentState.getString("sku"))
                .setString("name", currentState.getString("name"))
                .setString("description", currentState.getString("description"))
                .setString("price", currentState.getString("price"))
                .setInt32("quantityOnHand", updatedOnHand)
                .setInt32("quantityReserved", currentState.getInt32("quantityReserved"))
                .setString("category", currentState.getString("category"))
                .setString("status", currentState.getString("status"))
                .setInt64("createdAt", currentState.getInt64("createdAt"))
                .setInt64("updatedAt", now.toEpochMilli())
                .build();
    }

    @Override
    public String getSchemaName() {
        return SCHEMA_NAME;
    }

    // Getters and Setters

    public int getQuantityAdded() {
        return quantityAdded;
    }

    public void setQuantityAdded(int quantityAdded) {
        this.quantityAdded = quantityAdded;
    }

    public int getNewQuantityOnHand() {
        return newQuantityOnHand;
    }

    public void setNewQuantityOnHand(int newQuantityOnHand) {
        this.newQuantityOnHand = newQuantityOnHand;
    }

    public String getReason() {
        return reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    @Override
    public String toString() {
        return "StockReplenishedEvent{" +
                "eventId='" + eventId + '\'' +
                ", productId='" + key + '\'' +
                ", quantityAdded=" + quantityAdded +
                ", newQuantityOnHand=" + newQuantityOnHand +
                ", reason='" + reason + '\'' +
                '}';
    }
}
