package com.theyawns.ecommerce.order.controller;

import com.theyawns.framework.saga.SagaState;
import com.theyawns.framework.saga.SagaStateStore;
import com.theyawns.framework.saga.SagaStatus;
import com.theyawns.framework.saga.SagaStepRecord;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * REST controller for querying saga state.
 *
 * <p>Exposes saga data from the {@link SagaStateStore} via REST endpoints,
 * enabling the MCP server and monitoring tools to inspect saga progress.
 *
 * <p>Endpoints:
 * <ul>
 *   <li>GET /api/sagas/{sagaId} - Get saga state by ID</li>
 *   <li>GET /api/sagas?status={status}&amp;limit={limit} - List sagas by status</li>
 * </ul>
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
@RestController
@RequestMapping("/api/sagas")
@Tag(name = "Saga Management", description = "APIs for inspecting saga state")
public class SagaController {

    private static final Logger logger = LoggerFactory.getLogger(SagaController.class);
    private static final int DEFAULT_LIMIT = 10;

    private final SagaStateStore sagaStateStore;

    /**
     * Creates a new SagaController.
     *
     * @param sagaStateStore the saga state store
     */
    public SagaController(SagaStateStore sagaStateStore) {
        this.sagaStateStore = sagaStateStore;
    }

    /**
     * Retrieves saga state by ID.
     *
     * @param sagaId the saga identifier
     * @return the saga state as JSON, or 404 if not found
     */
    @GetMapping("/{sagaId}")
    @Operation(summary = "Get saga by ID", description = "Retrieves the current state of a saga instance")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Saga found"),
            @ApiResponse(responseCode = "404", description = "Saga not found")
    })
    public ResponseEntity<Map<String, Object>> getSaga(
            @Parameter(description = "Saga ID", required = true) @PathVariable String sagaId) {
        logger.debug("REST: Getting saga: {}", sagaId);

        return sagaStateStore.getSagaState(sagaId)
                .map(saga -> ResponseEntity.ok(toMap(saga)))
                .orElse(ResponseEntity.notFound().build());
    }

    /**
     * Lists sagas filtered by status.
     *
     * @param status optional status filter (STARTED, IN_PROGRESS, COMPLETED, COMPENSATING, COMPENSATED, FAILED, TIMED_OUT)
     * @param limit maximum number of results (default: 10)
     * @return list of saga states
     */
    @GetMapping
    @Operation(summary = "List sagas", description = "Lists sagas, optionally filtered by status")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Sagas retrieved"),
            @ApiResponse(responseCode = "400", description = "Invalid status value")
    })
    public ResponseEntity<List<Map<String, Object>>> listSagas(
            @Parameter(description = "Filter by status: STARTED, IN_PROGRESS, COMPLETED, COMPENSATING, COMPENSATED, FAILED, TIMED_OUT")
            @RequestParam(required = false) String status,
            @Parameter(description = "Maximum number of results")
            @RequestParam(defaultValue = "10") int limit) {
        logger.debug("REST: Listing sagas (status: {}, limit: {})", status, limit);

        try {
            List<SagaState> sagas;
            if (status != null && !status.isBlank()) {
                SagaStatus sagaStatus = SagaStatus.valueOf(status.toUpperCase());
                sagas = sagaStateStore.findSagasByStatus(sagaStatus);
            } else {
                // Return all non-terminal sagas plus recently completed ones
                sagas = sagaStateStore.findSagasByStatus(SagaStatus.STARTED);
                sagas = new java.util.ArrayList<>(sagas);
                sagas.addAll(sagaStateStore.findSagasByStatus(SagaStatus.IN_PROGRESS));
                sagas.addAll(sagaStateStore.findSagasByStatus(SagaStatus.COMPENSATING));
                sagas.addAll(sagaStateStore.findSagasByStatus(SagaStatus.COMPLETED));
                sagas.addAll(sagaStateStore.findSagasByStatus(SagaStatus.COMPENSATED));
                sagas.addAll(sagaStateStore.findSagasByStatus(SagaStatus.FAILED));
                sagas.addAll(sagaStateStore.findSagasByStatus(SagaStatus.TIMED_OUT));
            }

            int effectiveLimit = Math.max(1, limit);
            List<Map<String, Object>> result = sagas.stream()
                    .limit(effectiveLimit)
                    .map(this::toMap)
                    .collect(Collectors.toList());

            return ResponseEntity.ok(result);
        } catch (IllegalArgumentException e) {
            return ResponseEntity.badRequest().body(List.of(
                    Map.of("error", "Invalid status: " + status
                            + ". Valid values: STARTED, IN_PROGRESS, COMPLETED, COMPENSATING, COMPENSATED, FAILED, TIMED_OUT")
            ));
        }
    }

    /**
     * Converts a SagaState to a map for JSON serialization.
     *
     * @param saga the saga state
     * @return map representation
     */
    private Map<String, Object> toMap(SagaState saga) {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("sagaId", saga.getSagaId());
        map.put("sagaType", saga.getSagaType());
        map.put("correlationId", saga.getCorrelationId());
        map.put("status", saga.getStatus().name());
        map.put("currentStep", saga.getCurrentStep());
        map.put("totalSteps", saga.getTotalSteps());
        map.put("progressPercentage", saga.getProgressPercentage());
        map.put("startedAt", saga.getStartedAt() != null ? saga.getStartedAt().toString() : null);
        map.put("completedAt", saga.getCompletedAt() != null ? saga.getCompletedAt().toString() : null);
        map.put("durationMs", saga.getDuration().toMillis());
        map.put("deadline", saga.getDeadline() != null ? saga.getDeadline().toString() : null);
        map.put("failureReason", saga.getFailureReason());
        map.put("failedAtStep", saga.getFailedAtStep());

        List<Map<String, Object>> steps = saga.getSteps().stream()
                .map(this::stepToMap)
                .collect(Collectors.toList());
        map.put("steps", steps);

        return map;
    }

    /**
     * Converts a SagaStepRecord to a map for JSON serialization.
     *
     * @param step the step record
     * @return map representation
     */
    private Map<String, Object> stepToMap(SagaStepRecord step) {
        Map<String, Object> map = new LinkedHashMap<>();
        map.put("stepNumber", step.getStepNumber());
        map.put("stepName", step.getStepName());
        map.put("service", step.getService());
        map.put("eventType", step.getEventType());
        map.put("status", step.getStatus().name());
        map.put("timestamp", step.getTimestamp() != null ? step.getTimestamp().toString() : null);
        map.put("eventId", step.getEventId());
        map.put("failureReason", step.getFailureReason());
        return map;
    }
}
