package com.theyawns.ecommerce.account.config;

import com.hazelcast.client.HazelcastClient;
import com.hazelcast.client.config.ClientConfig;
import com.hazelcast.config.Config;
import com.hazelcast.config.EventJournalConfig;
import com.hazelcast.config.JoinConfig;
import com.hazelcast.config.MapConfig;
import com.hazelcast.config.MapStoreConfig;
import com.hazelcast.config.NetworkConfig;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.theyawns.ecommerce.common.view.CustomerViewUpdater;
import com.theyawns.ecommerce.common.domain.Customer;
import com.theyawns.framework.controller.EventSourcingController;
import com.theyawns.framework.event.DomainEvent;
import com.theyawns.framework.outbox.OutboxStore;
import com.theyawns.framework.persistence.PersistenceProperties;
import com.theyawns.framework.persistence.mapstore.EventStoreMapStore;
import com.theyawns.framework.persistence.mapstore.ViewStoreMapStore;
import com.theyawns.framework.security.identity.EventAuthenticator;
import com.theyawns.framework.store.HazelcastEventStore;
import com.theyawns.framework.view.HazelcastViewStore;
import io.micrometer.core.instrument.MeterRegistry;
import jakarta.annotation.PreDestroy;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Primary;

/**
 * Spring configuration for the Account Service.
 *
 * <p>Configures:
 * <ul>
 *   <li>Hazelcast instance with event journal</li>
 *   <li>Event store for customer events</li>
 *   <li>View store and updater for customer materialized view</li>
 *   <li>Event sourcing controller</li>
 * </ul>
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
@Configuration
public class AccountServiceConfig {

    private static final Logger logger = LoggerFactory.getLogger(AccountServiceConfig.class);

    private static final String DOMAIN_NAME = "Customer";

    @Value("${hazelcast.embedded.cluster-name:account-local}")
    private String embeddedClusterName;

    @Value("${hazelcast.cluster.name:ecommerce-cluster}")
    private String clusterName;

    @Value("${hazelcast.cluster.members:}")
    private String clusterMembers;

    @Value("${hazelcast.event-journal.capacity:10000}")
    private int eventJournalCapacity;

    @Autowired(required = false)
    private EventStoreMapStore eventStoreMapStore;

    @Autowired(required = false)
    private ViewStoreMapStore viewStoreMapStore;

    @Autowired(required = false)
    private PersistenceProperties persistenceProperties;

    private EventSourcingController<Customer, String, DomainEvent<Customer, String>> controller;

    /**
     * Creates the Hazelcast instance for the Account Service.
     *
     * <p>Uses a service-specific cluster name (default: {@code account-local}) to distinguish
     * this embedded instance from the shared cluster in Management Center.
     *
     * @return the configured Hazelcast instance
     */
    @Primary
    @Bean
    public HazelcastInstance hazelcastInstance() {
        Config config = new Config();

        // Resolve embedded cluster name: @Value → env var → default
        String effectiveEmbeddedName = embeddedClusterName;
        if (effectiveEmbeddedName == null || effectiveEmbeddedName.isEmpty()) {
            effectiveEmbeddedName = System.getenv("HAZELCAST_EMBEDDED_CLUSTER_NAME");
        }
        if (effectiveEmbeddedName == null || effectiveEmbeddedName.isEmpty()) {
            effectiveEmbeddedName = "account-local";
        }
        config.setClusterName(effectiveEmbeddedName);
        logger.info("Embedded cluster name: '{}'", effectiveEmbeddedName);

        // Resolve cluster members: @Value → env var → empty
        String effectiveClusterMembers = clusterMembers;
        if (effectiveClusterMembers == null || effectiveClusterMembers.isEmpty()) {
            effectiveClusterMembers = System.getenv("HAZELCAST_CLUSTER_MEMBERS");
        }

        // Enable event journal for pending events map (required for Jet streaming)
        int effectiveCapacity = eventJournalCapacity > 0 ? eventJournalCapacity : 10000;
        EventJournalConfig journalConfig = new EventJournalConfig()
                .setEnabled(true)
                .setCapacity(effectiveCapacity);

        // Configure pending maps for ALL domains with event journal (required for cluster-wide consistency)
        for (String domain : new String[]{"Customer", "Product", "Order"}) {
            MapConfig pendingMapConfig = new MapConfig(domain + "_PENDING")
                    .setEventJournalConfig(new EventJournalConfig()
                            .setEnabled(true)
                            .setCapacity(effectiveCapacity));
            config.addMapConfig(pendingMapConfig);
        }

        // Configure view map
        MapConfig viewMapConfig = new MapConfig(DOMAIN_NAME + "_VIEW");
        if (viewStoreMapStore != null && persistenceProperties != null) {
            MapStoreConfig viewMsc = new MapStoreConfig()
                    .setImplementation(viewStoreMapStore)
                    .setEnabled(true)
                    .setWriteDelaySeconds(persistenceProperties.getWriteDelaySeconds())
                    .setWriteBatchSize(persistenceProperties.getWriteBatchSize())
                    .setWriteCoalescing(true)
                    .setInitialLoadMode(MapStoreConfig.InitialLoadMode.EAGER);
            viewMapConfig.setMapStoreConfig(viewMsc);
            logger.info("Persistence enabled for {}_VIEW map (write-behind)", DOMAIN_NAME);
        }
        config.addMapConfig(viewMapConfig);

        // Configure event store map
        MapConfig eventStoreMapConfig = new MapConfig(DOMAIN_NAME + "_ES");
        if (eventStoreMapStore != null && persistenceProperties != null) {
            MapStoreConfig esMsc = new MapStoreConfig()
                    .setImplementation(eventStoreMapStore)
                    .setEnabled(true)
                    .setWriteDelaySeconds(persistenceProperties.getWriteDelaySeconds())
                    .setWriteBatchSize(persistenceProperties.getWriteBatchSize())
                    .setWriteCoalescing(false)
                    .setInitialLoadMode(MapStoreConfig.InitialLoadMode.LAZY);
            eventStoreMapConfig.setMapStoreConfig(esMsc);
            logger.info("Persistence enabled for {}_ES map (write-behind)", DOMAIN_NAME);
        }
        config.addMapConfig(eventStoreMapConfig);

        // Standalone embedded instance - no cluster join.
        // Cross-service communication uses the separate hazelcastClient() bean.
        NetworkConfig networkConfig = config.getNetworkConfig();
        JoinConfig joinConfig = networkConfig.getJoin();
        joinConfig.getMulticastConfig().setEnabled(false);
        joinConfig.getAutoDetectionConfig().setEnabled(false);

        // Enable Jet for stream processing pipeline
        config.getJetConfig().setEnabled(true);
        config.getJetConfig().setResourceUploadEnabled(true);

        logger.info("Creating standalone Hazelcast instance for local Jet processing (cluster: {})",
                embeddedClusterName);
        return Hazelcast.newHazelcastInstance(config);
    }

    /**
     * Creates a Hazelcast client that connects to the external shared cluster.
     *
     * <p>This client is used for cross-service communication:
     * <ul>
     *   <li>ITopic pub/sub for saga event propagation</li>
     * </ul>
     *
     * @return the Hazelcast client instance, or null if no cluster members configured
     */
    @Bean(name = "hazelcastClient")
    public HazelcastInstance hazelcastClient() {
        // Resolve cluster members: @Value → env var
        String effectiveClusterMembers = clusterMembers;
        if (effectiveClusterMembers == null || effectiveClusterMembers.isEmpty()) {
            effectiveClusterMembers = System.getenv("HAZELCAST_CLUSTER_MEMBERS");
        }

        if (effectiveClusterMembers == null || effectiveClusterMembers.isBlank()) {
            logger.info("No cluster members configured - shared Hazelcast client not created");
            return null;
        }

        // Resolve cluster name
        String effectiveClusterName = clusterName;
        if (effectiveClusterName == null || effectiveClusterName.isEmpty()) {
            effectiveClusterName = System.getenv("HAZELCAST_CLUSTER_NAME");
        }
        if (effectiveClusterName == null || effectiveClusterName.isEmpty()) {
            effectiveClusterName = "ecommerce-cluster";
        }

        ClientConfig clientConfig = new ClientConfig();
        clientConfig.setClusterName(effectiveClusterName);
        for (String member : effectiveClusterMembers.split(",")) {
            clientConfig.getNetworkConfig().addAddress(member.trim());
        }

        logger.info("Creating Hazelcast client for shared cluster: {} with members: {}",
                effectiveClusterName, effectiveClusterMembers);
        return HazelcastClient.newHazelcastClient(clientConfig);
    }

    /**
     * Creates the event store for customer events.
     *
     * @param hazelcast the Hazelcast instance
     * @return the event store
     */
    @Bean
    public HazelcastEventStore<Customer, String, DomainEvent<Customer, String>> customerEventStore(
            HazelcastInstance hazelcast) {
        return new HazelcastEventStore<>(hazelcast, DOMAIN_NAME);
    }

    /**
     * Creates the view store for the customer materialized view.
     *
     * @param hazelcast the Hazelcast instance
     * @return the view store
     */
    @Bean
    public HazelcastViewStore<String> customerViewStore(HazelcastInstance hazelcast) {
        return new HazelcastViewStore<>(hazelcast, DOMAIN_NAME);
    }

    /**
     * Creates the view updater that applies customer events to the view.
     *
     * @param viewStore the view store
     * @return the view updater
     */
    @Bean
    public CustomerViewUpdater customerViewUpdater(HazelcastViewStore<String> viewStore) {
        return new CustomerViewUpdater(viewStore);
    }

    /**
     * Creates the event sourcing controller for customer operations.
     *
     * @param hazelcastInstance the Hazelcast instance
     * @param eventStore the event store
     * @param viewUpdater the view updater
     * @param meterRegistry the metrics registry
     * @return the event sourcing controller
     */
    @Bean
    public EventSourcingController<Customer, String, DomainEvent<Customer, String>> customerController(
            HazelcastInstance hazelcastInstance,
            @org.springframework.beans.factory.annotation.Qualifier("hazelcastClient")
            @org.springframework.beans.factory.annotation.Autowired(required = false)
            HazelcastInstance hazelcastClient,
            HazelcastEventStore<Customer, String, DomainEvent<Customer, String>> eventStore,
            CustomerViewUpdater viewUpdater,
            MeterRegistry meterRegistry,
            @org.springframework.beans.factory.annotation.Autowired(required = false)
            OutboxStore outboxStore,
            @org.springframework.beans.factory.annotation.Autowired(required = false)
            EventAuthenticator eventAuthenticator) {

        controller = EventSourcingController.<Customer, String, DomainEvent<Customer, String>>builder()
                .hazelcast(hazelcastInstance)
                .sharedHazelcast(hazelcastClient)
                .domainName(DOMAIN_NAME)
                .eventStore(eventStore)
                .viewUpdater(viewUpdater)
                .viewUpdaterClass(CustomerViewUpdater.class)
                .meterRegistry(meterRegistry)
                .outboxStore(outboxStore)
                .eventAuthenticator(eventAuthenticator)
                .build();

        // Start the pipeline immediately after building the controller
        logger.info("Starting Customer event sourcing pipeline");
        controller.start();

        return controller;
    }

    /**
     * Stops the event sourcing pipeline on shutdown.
     */
    @PreDestroy
    public void stopPipeline() {
        if (controller != null && controller.isRunning()) {
            logger.info("Stopping Customer event sourcing pipeline");
            controller.stop();
        }
    }
}
