package com.theyawns.ecommerce.payment.exception;

import com.theyawns.framework.resilience.NonRetryableException;

/**
 * Exception thrown when a payment operation is invalid for the current state.
 *
 * <p>Implements {@link NonRetryableException} because an invalid payment state is a
 * deterministic business failure that will not resolve on retry.
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
public class InvalidPaymentStateException extends RuntimeException implements NonRetryableException {

    private static final long serialVersionUID = 1L;

    private final String paymentId;
    private final String currentStatus;
    private final String requestedOperation;

    /**
     * Creates a new InvalidPaymentStateException.
     *
     * @param paymentId the payment ID
     * @param currentStatus the current payment status
     * @param requestedOperation the operation that was attempted
     */
    public InvalidPaymentStateException(String paymentId, String currentStatus, String requestedOperation) {
        super(String.format("Cannot %s payment %s: current status is %s",
                requestedOperation, paymentId, currentStatus));
        this.paymentId = paymentId;
        this.currentStatus = currentStatus;
        this.requestedOperation = requestedOperation;
    }

    /**
     * Returns the payment ID.
     *
     * @return the payment ID
     */
    public String getPaymentId() {
        return paymentId;
    }

    /**
     * Returns the current status.
     *
     * @return the current status
     */
    public String getCurrentStatus() {
        return currentStatus;
    }

    /**
     * Returns the requested operation.
     *
     * @return the requested operation
     */
    public String getRequestedOperation() {
        return requestedOperation;
    }
}
