package com.theyawns.ecommerce.payment.exception;

import com.theyawns.framework.resilience.NonRetryableException;

/**
 * Exception thrown when a payment cannot be found.
 *
 * <p>Implements {@link NonRetryableException} because a missing payment is a
 * deterministic business failure that will not resolve on retry.
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
public class PaymentNotFoundException extends RuntimeException implements NonRetryableException {

    private static final long serialVersionUID = 1L;

    private final String paymentId;

    /**
     * Creates a new PaymentNotFoundException.
     *
     * @param paymentId the ID of the payment that was not found
     */
    public PaymentNotFoundException(String paymentId) {
        super("Payment not found: " + paymentId);
        this.paymentId = paymentId;
    }

    /**
     * Returns the payment ID that was not found.
     *
     * @return the payment ID
     */
    public String getPaymentId() {
        return paymentId;
    }
}
