package com.theyawns.framework.vectorstore;

/**
 * Pluggable interface for generating text embeddings.
 *
 * <p>The framework provides a default implementation using LangChain4j's
 * all-MiniLM-L6-v2 model (ONNX, runs locally, no API key required).
 * Applications can override this by defining their own {@code EmbeddingProvider}
 * bean (e.g., wrapping OpenAI, Cohere, or another embedding service).
 *
 * @author Generated by Claude Code
 * @since 2.1
 * @see LangChain4jEmbeddingProvider
 * @see VectorStoreAutoConfiguration
 */
public interface EmbeddingProvider {

    /**
     * Generates an embedding vector for the given text.
     *
     * @param text the input text to embed
     * @return a float array representing the embedding vector
     */
    float[] embed(String text);

    /**
     * Returns the dimensionality of vectors produced by this provider.
     *
     * <p>Callers can use this to verify compatibility with the vector store's
     * configured dimension.
     *
     * @return the number of dimensions in the output vectors
     */
    int getDimension();

    /**
     * Returns the name of the embedding model for logging and diagnostics.
     *
     * @return the model name
     */
    String getModelName();
}
