package com.theyawns.framework.vectorstore;

import dev.langchain4j.model.embedding.onnx.allminilml6v2.AllMiniLmL6V2EmbeddingModel;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Default {@link EmbeddingProvider} using LangChain4j's all-MiniLM-L6-v2 model.
 *
 * <p>This model runs locally via ONNX Runtime — no API key or external service required.
 * It produces 384-dimension vectors and is widely used for semantic similarity tasks.
 * The model loads on first call (~1-2 seconds) and is thread-safe thereafter.
 *
 * <p>To use a different embedding model (e.g., OpenAI, Cohere), define your own
 * {@link EmbeddingProvider} bean and it will override this default via
 * {@code @ConditionalOnMissingBean}.
 *
 * @author Generated by Claude Code
 * @since 2.1
 * @see EmbeddingProvider
 * @see VectorStoreAutoConfiguration
 */
public class LangChain4jEmbeddingProvider implements EmbeddingProvider {

    private static final Logger logger = LoggerFactory.getLogger(LangChain4jEmbeddingProvider.class);
    private static final String MODEL_NAME = "all-MiniLM-L6-v2";
    private static final int DIMENSION = 384;

    private final AllMiniLmL6V2EmbeddingModel model;

    /**
     * Creates a new provider, eagerly loading the ONNX model.
     */
    public LangChain4jEmbeddingProvider() {
        logger.info("Loading embedding model: {} (ONNX, {} dimensions)", MODEL_NAME, DIMENSION);
        this.model = new AllMiniLmL6V2EmbeddingModel();
        logger.info("Embedding model loaded: {}", MODEL_NAME);
    }

    @Override
    public float[] embed(final String text) {
        return model.embed(text).content().vector();
    }

    @Override
    public int getDimension() {
        return DIMENSION;
    }

    @Override
    public String getModelName() {
        return MODEL_NAME;
    }
}
