package com.theyawns.framework.vectorstore;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.List;
import java.util.Map;

/**
 * Reserve no-op fallback for the vector store.
 *
 * <p>This implementation silently discards embeddings and returns empty results.
 * It is <strong>not</strong> auto-wired by default — {@link SimpleVectorStoreService}
 * is the active Community Edition fallback.
 *
 * <p>This class is retained in case a business decision requires reverting Community
 * Edition to a non-functional vector store. To re-activate it, add {@code @Service}
 * and {@code @ConditionalOnCommunityFallback(EnterpriseFeature.VECTOR_STORE)}
 * annotations, and remove the same annotations from {@link SimpleVectorStoreService}.
 *
 * @author Generated by Claude Code
 * @since 2.0
 * @see VectorStoreService
 * @see SimpleVectorStoreService
 */
public class NoOpVectorStoreService implements VectorStoreService {

    private static final Logger logger = LoggerFactory.getLogger(NoOpVectorStoreService.class);

    /**
     * Creates a new NoOpVectorStoreService.
     */
    public NoOpVectorStoreService() {
        logger.info("NoOpVectorStoreService initialized (Community Edition fallback). " +
                "Vector similarity search is not available.");
    }

    @Override
    public void storeEmbedding(final String id, final float[] embedding, final Map<String, Object> metadata) {
        // No-op: embeddings are discarded in Community Edition
        logger.debug("storeEmbedding called for id={} (no-op, Community Edition)", id);
    }

    @Override
    public List<SimilarityResult> findSimilar(final float[] queryVector, final int limit) {
        return List.of();
    }

    @Override
    public List<SimilarityResult> findSimilarById(final String id, final int limit) {
        return List.of();
    }

    @Override
    public boolean isAvailable() {
        return false;
    }

    @Override
    public String getImplementationType() {
        return "No-Op (Community Edition)";
    }
}
