package com.theyawns.framework.vectorstore;

import java.util.Map;

/**
 * Represents a single result from a vector similarity search.
 *
 * <p>Contains the matched item's ID, its similarity score (0.0 to 1.0 for cosine similarity),
 * and any associated metadata (e.g., product name, category).
 *
 * @param id the unique identifier of the matched item
 * @param score the similarity score (higher is more similar; 1.0 = identical)
 * @param metadata arbitrary key-value metadata associated with the item
 *
 * @author Generated by Claude Code
 * @since 2.0
 * @see VectorStoreService#findSimilar(float[], int)
 */
public record SimilarityResult(String id, float score, Map<String, Object> metadata) {
}
