package com.theyawns.framework.vectorstore;

import com.hazelcast.core.HazelcastInstance;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.autoconfigure.condition.ConditionalOnBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Auto-configuration for the vector store abstraction (Community Edition fallback).
 *
 * <p>Activates when a {@link HazelcastInstance} bean is present. Provides a
 * {@link SimpleVectorStoreService} safety-net bean via {@code @ConditionalOnMissingBean}.
 *
 * <p>When the {@code framework-enterprise} module is on the classpath (built with
 * {@code -Penterprise}), the {@code EnterpriseVectorStoreAutoConfiguration} runs first
 * and registers a {@code HazelcastVectorStoreService} using Hazelcast's native
 * {@code VectorCollection} with HNSW indexing. In that case, this fallback is skipped.
 *
 * <p>When built without the enterprise profile (the default), no Enterprise bean exists,
 * and this configuration creates the {@link SimpleVectorStoreService} fallback with
 * working IMap-based cosine similarity search.
 *
 * @author Generated by Claude Code
 * @since 2.0
 * @see VectorStoreService
 * @see VectorStoreProperties
 * @see SimpleVectorStoreService
 */
@Configuration
@EnableConfigurationProperties(VectorStoreProperties.class)
@ConditionalOnBean(HazelcastInstance.class)
public class VectorStoreAutoConfiguration {

    private static final Logger logger = LoggerFactory.getLogger(VectorStoreAutoConfiguration.class);

    /**
     * Creates a default {@link EmbeddingProvider} using LangChain4j's all-MiniLM-L6-v2 model.
     *
     * <p>Applications can override this by defining their own {@code EmbeddingProvider} bean
     * (e.g., wrapping OpenAI, Cohere, or another embedding service).
     *
     * @return a LangChain4j-based embedding provider
     */
    @Bean
    @ConditionalOnMissingBean(EmbeddingProvider.class)
    public EmbeddingProvider embeddingProvider() {
        logger.info("Creating default EmbeddingProvider (LangChain4j all-MiniLM-L6-v2)");
        return new LangChain4jEmbeddingProvider();
    }

    /**
     * Fallback: creates a SimpleVectorStoreService if no other VectorStoreService bean exists.
     *
     * <p>This covers the default Community Edition path and edge cases where the
     * enterprise module is not on the classpath. The {@code @Service} annotation on
     * {@link SimpleVectorStoreService} will normally handle bean creation via component
     * scanning; this bean definition serves as a safety net for auto-configuration-only
     * setups.
     *
     * @param hazelcast the Hazelcast instance for IMap storage
     * @param properties the vector store configuration properties
     * @return a simple IMap-based vector store service
     */
    @Bean
    @ConditionalOnMissingBean(VectorStoreService.class)
    public VectorStoreService vectorStoreService(HazelcastInstance hazelcast,
                                                 VectorStoreProperties properties) {
        logger.info("No VectorStoreService bean found; creating SimpleVectorStoreService fallback");
        return new SimpleVectorStoreService(hazelcast, properties);
    }
}
