package com.theyawns.framework.vectorstore;

import com.hazelcast.core.HazelcastInstance;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.autoconfigure.condition.ConditionalOnBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Auto-configuration for the vector store abstraction.
 *
 * <p>Activates when a {@link HazelcastInstance} bean is present. Conditionally creates
 * either {@link SimpleVectorStoreService} (Enterprise) or {@link NoOpVectorStoreService}
 * (Community fallback) based on the edition detection system.
 *
 * <p>The actual bean selection is driven by {@code @ConditionalOnEnterpriseFeature} and
 * {@code @ConditionalOnCommunityFallback} annotations on the service classes themselves.
 * This configuration only enables property binding and provides a safety-net
 * {@code @ConditionalOnMissingBean} fallback.
 *
 * @author Generated by Claude Code
 * @since 2.0
 * @see VectorStoreService
 * @see VectorStoreProperties
 */
@Configuration
@EnableConfigurationProperties(VectorStoreProperties.class)
@ConditionalOnBean(HazelcastInstance.class)
public class VectorStoreAutoConfiguration {

    private static final Logger logger = LoggerFactory.getLogger(VectorStoreAutoConfiguration.class);

    /**
     * Fallback: creates a NoOpVectorStoreService if no other VectorStoreService bean exists.
     *
     * <p>This handles edge cases where neither conditional annotation matches
     * (e.g., edition detection not yet configured). The {@code @Service} annotations
     * on {@link SimpleVectorStoreService} and {@link NoOpVectorStoreService} will
     * normally handle bean creation via component scanning; this bean definition
     * serves as a safety net for auto-configuration-only setups.
     *
     * @return a no-op vector store service
     */
    @Bean
    @ConditionalOnMissingBean(VectorStoreService.class)
    public VectorStoreService vectorStoreService() {
        logger.info("No VectorStoreService bean found; creating NoOpVectorStoreService fallback");
        return new NoOpVectorStoreService();
    }
}
