package com.theyawns.framework.vectorstore;

import org.springframework.boot.context.properties.ConfigurationProperties;

/**
 * Configuration properties for the vector store.
 *
 * <p>Binds to the {@code framework.vectorstore} prefix in application.yml:
 * <pre>{@code
 * framework:
 *   vectorstore:
 *     collection-name: product-vectors
 *     dimension: 128
 *     max-connections: 16
 *     ef-construction: 200
 *     metric: COSINE
 *     index-name: default
 * }</pre>
 *
 * <p>The {@code maxConnections}, {@code efConstruction}, {@code metric}, and
 * {@code indexName} properties are used by the Enterprise {@code HazelcastVectorStoreService}
 * for HNSW index configuration.
 *
 * @author Generated by Claude Code
 * @since 2.0
 * @see VectorStoreAutoConfiguration
 */
@ConfigurationProperties(prefix = "framework.vectorstore")
public class VectorStoreProperties {

    /**
     * Name of the Hazelcast collection or map used to store vectors.
     */
    private String collectionName = "product-vectors";

    /**
     * Dimensionality of the embedding vectors.
     */
    private int dimension = 128;

    /**
     * Maximum connections per node in HNSW graph (Enterprise only).
     */
    private int maxConnections = 16;

    /**
     * Construction-time beam width for HNSW index (Enterprise only).
     */
    private int efConstruction = 200;

    /**
     * Distance metric for vector similarity: COSINE, DOT, or EUCLIDEAN (Enterprise only).
     */
    private String metric = "COSINE";

    /**
     * Name of the HNSW index within the VectorCollection (Enterprise only).
     */
    private String indexName = "default";

    /**
     * Creates a new VectorStoreProperties with default values.
     */
    public VectorStoreProperties() {
        // Default constructor
    }

    /**
     * Returns the collection name.
     *
     * @return collection name
     */
    public String getCollectionName() {
        return collectionName;
    }

    /**
     * Sets the collection name.
     *
     * @param collectionName the collection name
     */
    public void setCollectionName(String collectionName) {
        this.collectionName = collectionName;
    }

    /**
     * Returns the embedding dimension.
     *
     * @return dimension
     */
    public int getDimension() {
        return dimension;
    }

    /**
     * Sets the embedding dimension.
     *
     * @param dimension the dimension
     */
    public void setDimension(int dimension) {
        this.dimension = dimension;
    }

    /**
     * Returns the max connections for HNSW (Enterprise only).
     *
     * @return max connections
     */
    public int getMaxConnections() {
        return maxConnections;
    }

    /**
     * Sets the max connections for HNSW (Enterprise only).
     *
     * @param maxConnections the max connections
     */
    public void setMaxConnections(int maxConnections) {
        this.maxConnections = maxConnections;
    }

    /**
     * Returns the ef construction parameter for HNSW (Enterprise only).
     *
     * @return ef construction
     */
    public int getEfConstruction() {
        return efConstruction;
    }

    /**
     * Sets the ef construction parameter for HNSW (Enterprise only).
     *
     * @param efConstruction the ef construction
     */
    public void setEfConstruction(int efConstruction) {
        this.efConstruction = efConstruction;
    }

    /**
     * Returns the distance metric (Enterprise only).
     *
     * @return metric name (COSINE, DOT, or EUCLIDEAN)
     */
    public String getMetric() {
        return metric;
    }

    /**
     * Sets the distance metric (Enterprise only).
     *
     * @param metric the metric name
     */
    public void setMetric(String metric) {
        this.metric = metric;
    }

    /**
     * Returns the HNSW index name (Enterprise only).
     *
     * @return index name
     */
    public String getIndexName() {
        return indexName;
    }

    /**
     * Sets the HNSW index name (Enterprise only).
     *
     * @param indexName the index name
     */
    public void setIndexName(String indexName) {
        this.indexName = indexName;
    }
}
