package com.theyawns.framework.vectorstore;

import java.util.List;
import java.util.Map;

/**
 * Abstraction for vector similarity search operations.
 *
 * <p>Provides a unified API for storing embeddings and performing similarity searches.
 * Two implementations exist:
 * <ul>
 *   <li>{@link SimpleVectorStoreService} — Enterprise path using {@code IMap<String, float[]>}
 *       with brute-force cosine similarity</li>
 *   <li>{@link NoOpVectorStoreService} — Community fallback returning empty results</li>
 * </ul>
 *
 * <p>Callers should check {@link #isAvailable()} before assuming results will be returned.
 *
 * @author Generated by Claude Code
 * @since 2.0
 * @see SimilarityResult
 */
public interface VectorStoreService {

    /**
     * Stores an embedding vector with associated metadata.
     *
     * @param id unique identifier for the embedding (e.g., product ID)
     * @param embedding the vector embedding
     * @param metadata arbitrary key-value metadata (e.g., name, category)
     */
    void storeEmbedding(String id, float[] embedding, Map<String, Object> metadata);

    /**
     * Finds items most similar to the given query vector.
     *
     * @param queryVector the vector to search against
     * @param limit maximum number of results to return
     * @return list of similarity results ordered by descending score, or empty if unavailable
     */
    List<SimilarityResult> findSimilar(float[] queryVector, int limit);

    /**
     * Finds items most similar to the item identified by the given ID.
     *
     * <p>Looks up the stored embedding for {@code id} and delegates to
     * {@link #findSimilar(float[], int)}, excluding the query item itself.
     *
     * @param id the ID of the item to find similar items for
     * @param limit maximum number of results to return
     * @return list of similarity results ordered by descending score, or empty if unavailable
     */
    List<SimilarityResult> findSimilarById(String id, int limit);

    /**
     * Returns whether this vector store implementation is functional.
     *
     * @return {@code true} if the vector store can perform searches, {@code false} otherwise
     */
    boolean isAvailable();

    /**
     * Returns a human-readable name for this implementation.
     *
     * @return implementation type name (e.g., "IMap-Based Cosine Similarity" or "No-Op (Community)")
     */
    String getImplementationType();
}
