package com.theyawns.framework.config;

import com.hazelcast.config.Config;
import com.hazelcast.config.JoinConfig;
import com.hazelcast.config.NetworkConfig;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Configures embedded Hazelcast instance discovery for per-service clustering.
 *
 * <p>When clustering is enabled (typically in Kubernetes), replicas of the same
 * service form their own embedded cluster using Hazelcast's built-in Kubernetes
 * DNS discovery. This allows distributed Jet pipeline processing across replicas.
 *
 * <p>When clustering is disabled (default), the embedded instance runs standalone
 * with no discovery — preserving the original single-replica behavior for
 * Docker Compose and local development.
 *
 * <p>This utility is called by each service's {@code hazelcastInstance()} bean
 * to replace the hardcoded discovery-disable pattern with a configurable one.
 *
 * <p>Port 5801 is used by default to avoid collision with the shared cluster's 5701.
 *
 * @author Generated by Claude Code
 * @since 3.1
 * @see <a href="../../../../../../../docs/architecture/adr/013-per-service-embedded-clustering.md">ADR 013</a>
 */
public final class EmbeddedClusteringConfigurer {

    private static final Logger logger = LoggerFactory.getLogger(EmbeddedClusteringConfigurer.class);

    /** Default port for embedded instances, chosen to avoid conflict with shared cluster (5701). */
    public static final int DEFAULT_PORT = 5801;

    private EmbeddedClusteringConfigurer() {
        // Utility class — no instantiation
    }

    /**
     * Configures network discovery on the given Hazelcast {@link Config}.
     *
     * <p>When {@code enabled} is {@code true} and {@code discoveryMode} is {@code "dns"},
     * Kubernetes DNS-based discovery is activated using the given {@code serviceDns} hostname.
     * This lets same-service replicas find each other and form a per-service embedded cluster.
     *
     * <p>When {@code enabled} is {@code true} and {@code discoveryMode} is {@code "tcp-ip"},
     * TCP/IP discovery is activated using the given {@code serviceDns} as a comma-separated
     * list of member addresses (e.g., {@code "order-service:5801,order-service-2:5801"}).
     * This mode is used for Docker Compose multi-replica testing.
     *
     * <p>When {@code enabled} is {@code false} (the default), all discovery mechanisms
     * are disabled and the instance runs as a standalone cluster-of-1.
     *
     * @param config        the Hazelcast Config to modify (mutated in place)
     * @param enabled       whether per-service clustering is enabled
     * @param discoveryMode the discovery mechanism ({@code "dns"} for Kubernetes, {@code "tcp-ip"} for Docker Compose)
     * @param serviceDns    the headless service DNS name (dns mode) or comma-separated members (tcp-ip mode)
     * @param port          the port for the embedded instance (default: 5801)
     */
    public static void configure(final Config config, final boolean enabled,
                                  final String discoveryMode, final String serviceDns,
                                  final int port) {
        NetworkConfig net = config.getNetworkConfig();
        net.setPort(port);
        net.setPortAutoIncrement(true);

        JoinConfig join = net.getJoin();
        join.getAutoDetectionConfig().setEnabled(false);
        join.getMulticastConfig().setEnabled(false);

        if (enabled && serviceDns != null && !serviceDns.isBlank()) {
            if ("dns".equals(discoveryMode)) {
                join.getKubernetesConfig()
                        .setEnabled(true)
                        .setProperty("service-dns", serviceDns);
                logger.info("Embedded clustering ENABLED: mode=dns, serviceDns={}, port={}",
                        serviceDns, port);
            } else if ("tcp-ip".equals(discoveryMode)) {
                join.getTcpIpConfig().setEnabled(true);
                for (String member : serviceDns.split(",")) {
                    join.getTcpIpConfig().addMember(member.trim());
                }
                logger.info("Embedded clustering ENABLED: mode=tcp-ip, members={}, port={}",
                        serviceDns, port);
            } else {
                logger.warn("Unknown discovery mode '{}' — falling back to standalone", discoveryMode);
            }
        } else if (enabled) {
            logger.info("Embedded clustering enabled but no service address configured — standalone mode, port={}", port);
        } else {
            logger.info("Embedded clustering DISABLED: standalone mode, port={}", port);
        }
    }
}
