package com.theyawns.framework.config;

import com.hazelcast.core.HazelcastInstance;
import io.micrometer.core.instrument.MeterRegistry;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Import;

/**
 * Spring Boot auto-configuration for the event sourcing framework.
 *
 * <p>This configuration is automatically applied when:
 * <ul>
 *   <li>Hazelcast is on the classpath</li>
 *   <li>Spring Boot Actuator is on the classpath (for metrics)</li>
 * </ul>
 *
 * <p>Imports:
 * <ul>
 *   <li>{@link HazelcastConfig} - Hazelcast instance configuration</li>
 *   <li>{@link MetricsConfig} - Micrometer metrics configuration</li>
 * </ul>
 *
 * <p>Usage in services:
 * <pre>{@code
 * // In your Spring Boot application, the framework auto-configures
 * // Just inject the HazelcastInstance and MeterRegistry
 *
 * @Service
 * public class CustomerService {
 *
 *     private final EventSourcingController<Customer, String, CustomerEvent> controller;
 *
 *     @Autowired
 *     public CustomerService(HazelcastInstance hazelcast, MeterRegistry registry) {
 *         // Create event store
 *         EventStore<Customer, String, CustomerEvent> eventStore =
 *             new HazelcastEventStore<>(hazelcast, "Customer");
 *
 *         // Create view store and updater
 *         HazelcastViewStore<String> viewStore =
 *             new HazelcastViewStore<>(hazelcast, "Customer");
 *         ViewUpdater<String> viewUpdater = new CustomerViewUpdater(viewStore);
 *
 *         // Build controller
 *         this.controller = EventSourcingController.<Customer, String, CustomerEvent>builder()
 *             .hazelcast(hazelcast)
 *             .domainName("Customer")
 *             .eventStore(eventStore)
 *             .viewUpdater(viewUpdater)
 *             .meterRegistry(registry)
 *             .build();
 *
 *         // Start the pipeline
 *         this.controller.start();
 *     }
 * }
 * }</pre>
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
@AutoConfiguration
@ConditionalOnClass({HazelcastInstance.class, MeterRegistry.class})
@Import({HazelcastConfig.class, MetricsConfig.class})
public class FrameworkAutoConfiguration {

    private static final Logger logger = LoggerFactory.getLogger(FrameworkAutoConfiguration.class);

    /**
     * Constructor - logs that auto-configuration is active.
     */
    public FrameworkAutoConfiguration() {
        logger.info("Event Sourcing Framework auto-configuration enabled");
    }

    /**
     * Provides a default meter registry if none is configured.
     * This is a fallback - Spring Boot Actuator usually provides one.
     *
     * @return a simple meter registry
     */
    @Bean
    @ConditionalOnMissingBean(MeterRegistry.class)
    public MeterRegistry meterRegistry() {
        logger.warn("No MeterRegistry found, creating SimpleMeterRegistry. " +
                "Consider adding spring-boot-starter-actuator for production metrics.");
        return new io.micrometer.core.instrument.simple.SimpleMeterRegistry();
    }
}
