package com.theyawns.framework.config;

import com.hazelcast.config.NativeMemoryConfig;
import com.hazelcast.memory.MemorySize;
import com.hazelcast.memory.MemoryUnit;
import com.theyawns.framework.edition.ConditionalOnEnterpriseFeature;
import com.theyawns.framework.edition.EditionAutoConfiguration;
import com.theyawns.framework.edition.EditionDetector.EnterpriseFeature;
import com.theyawns.framework.edition.EditionProperties;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.boot.autoconfigure.AutoConfigureAfter;
import org.springframework.context.annotation.Bean;

/**
 * Auto-configuration that registers {@link HazelcastConfigCustomizer} and
 * {@link HazelcastClientConfigCustomizer} beans for Enterprise-only features.
 *
 * <p>Each customizer bean is guarded by {@link ConditionalOnEnterpriseFeature},
 * so it is only created when Enterprise Edition is detected and the feature is
 * not explicitly disabled.
 *
 * <p>Service configuration classes inject these customizers and apply them to
 * their Hazelcast Config before instance creation.
 *
 * @author Generated by Claude Code
 * @since 2.0
 * @see HazelcastConfigCustomizer
 * @see HazelcastClientConfigCustomizer
 */
@AutoConfiguration
@AutoConfigureAfter(EditionAutoConfiguration.class)
public class HazelcastFeatureAutoConfiguration {

    private static final Logger logger = LoggerFactory.getLogger(HazelcastFeatureAutoConfiguration.class);

    /**
     * Customizer that enables HD Memory (Native Memory) on the embedded Hazelcast instance.
     *
     * <p>Configures:
     * <ul>
     *   <li>Native memory enabled</li>
     *   <li>Memory pool capacity from {@code framework.features.hd-memory.capacity-mb}</li>
     *   <li>Allocator type from {@code framework.features.hd-memory.allocator-type}</li>
     * </ul>
     *
     * @param properties the edition properties for reading HD Memory settings
     * @return a config customizer that enables HD Memory
     */
    @Bean
    @ConditionalOnEnterpriseFeature(EnterpriseFeature.HD_MEMORY)
    public HazelcastConfigCustomizer hdMemoryConfigCustomizer(EditionProperties properties) {
        return config -> {
            final EditionProperties.HdMemoryFeatureConfig hdConfig = properties.getFeatures().getHdMemory();
            final int capacityMb = hdConfig.getCapacityMb();
            final NativeMemoryConfig.MemoryAllocatorType allocatorType =
                    NativeMemoryConfig.MemoryAllocatorType.valueOf(hdConfig.getAllocatorType().toUpperCase());

            config.getNativeMemoryConfig()
                    .setEnabled(true)
                    .setSize(new MemorySize(capacityMb, MemoryUnit.MEGABYTES))
                    .setAllocatorType(allocatorType);

            logger.info("HD Memory enabled: capacity={}MB, allocator={}", capacityMb, allocatorType);
        };
    }

    /**
     * Customizer that enables Thread-Per-Core (TPC) on the embedded Hazelcast instance.
     *
     * <p>Configures:
     * <ul>
     *   <li>TPC enabled</li>
     *   <li>Eventloop count from {@code framework.features.tpc.eventloop-count} (0 = auto-detect)</li>
     * </ul>
     *
     * <p>Note: TPC is {@code @Beta} in Hazelcast 5.6.
     *
     * @param properties the edition properties for reading TPC settings
     * @return a config customizer that enables TPC
     */
    @Bean
    @ConditionalOnEnterpriseFeature(EnterpriseFeature.THREAD_PER_CORE)
    public HazelcastConfigCustomizer tpcConfigCustomizer(EditionProperties properties) {
        return config -> {
            final EditionProperties.TpcFeatureConfig tpcConfig = properties.getFeatures().getTpc();
            final int eventloopCount = tpcConfig.getEventloopCount();

            config.getTpcConfig().setEnabled(true);
            if (eventloopCount > 0) {
                config.getTpcConfig().setEventloopCount(eventloopCount);
            }

            logger.info("TPC enabled: eventloopCount={}", eventloopCount > 0 ? eventloopCount : "auto");
        };
    }

    /**
     * Customizer that enables Thread-Per-Core (TPC) on the Hazelcast client instance.
     *
     * <p>Only applied when {@code framework.features.tpc.client-enabled=true} (default).
     *
     * @param properties the edition properties for reading TPC settings
     * @return a client config customizer that enables TPC
     */
    @Bean
    @ConditionalOnEnterpriseFeature(EnterpriseFeature.THREAD_PER_CORE)
    public HazelcastClientConfigCustomizer tpcClientConfigCustomizer(EditionProperties properties) {
        return clientConfig -> {
            final EditionProperties.TpcFeatureConfig tpcConfig = properties.getFeatures().getTpc();
            if (tpcConfig.isClientEnabled()) {
                clientConfig.getTpcConfig().setEnabled(true);
                logger.info("TPC enabled on Hazelcast client");
            }
        };
    }
}
