package com.theyawns.framework.config;

import com.hazelcast.client.config.ClientConfig;

/**
 * Callback interface for customizing a Hazelcast {@link ClientConfig} before
 * client instance creation.
 *
 * <p>Symmetric with {@link HazelcastConfigCustomizer} for the client side.
 * Used for features like TPC that also need client-side configuration.
 *
 * @author Generated by Claude Code
 * @since 2.0
 * @see HazelcastConfigCustomizer
 * @see HazelcastFeatureAutoConfiguration
 */
@FunctionalInterface
public interface HazelcastClientConfigCustomizer {

    /**
     * Customizes the given Hazelcast ClientConfig before client creation.
     *
     * @param clientConfig the Hazelcast ClientConfig to customize
     */
    void customize(ClientConfig clientConfig);
}
