package com.theyawns.framework.config;

import com.hazelcast.config.Config;
import com.hazelcast.config.EventJournalConfig;
import com.hazelcast.config.EvictionConfig;
import com.hazelcast.config.IndexConfig;
import com.hazelcast.config.IndexType;
import com.hazelcast.config.JoinConfig;
import com.hazelcast.config.MapConfig;
import com.hazelcast.config.MaxSizePolicy;
import com.hazelcast.config.TcpIpConfig;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.Arrays;
import java.util.List;

/**
 * Spring configuration for Hazelcast Community Edition.
 * Provides a pre-configured HazelcastInstance suitable for event sourcing.
 *
 * <p>Key configurations:
 * <ul>
 *   <li>Event Journal enabled for pending events maps</li>
 *   <li>Backup configuration for reliability</li>
 *   <li>Near cache for fast view reads</li>
 * </ul>
 *
 * <p>This configuration uses only Community Edition features:
 * <ul>
 *   <li>FlakeIdGenerator for sequence numbers</li>
 *   <li>IMap for storage</li>
 *   <li>ITopic for pub/sub</li>
 *   <li>Jet for pipeline processing</li>
 *   <li>Event Journal for change capture</li>
 * </ul>
 *
 * <p>To customize, provide your own HazelcastInstance bean and this
 * auto-configuration will back off.
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
@Configuration
public class HazelcastConfig {

    private static final Logger logger = LoggerFactory.getLogger(HazelcastConfig.class);

    @Value("${hazelcast.cluster-name:event-sourcing-cluster}")
    private String clusterName;

    @Value("${hazelcast.event-journal.capacity:10000}")
    private int eventJournalCapacity;

    @Value("${hazelcast.event-journal.time-to-live-seconds:3600}")
    private int eventJournalTtlSeconds;

    @Value("${hazelcast.map.backup-count:1}")
    private int backupCount;

    @Value("${hazelcast.network.port:5701}")
    private int networkPort;

    @Value("${hazelcast.network.port-auto-increment:true}")
    private boolean portAutoIncrement;

    @Value("${hazelcast.completions.max-size:50000}")
    private int completionsMaxSize;

    @Value("${hazelcast.eviction.event-store.max-size:0}")
    private int esEvictionMaxSize;

    @Value("${hazelcast.eviction.event-store.policy:NONE}")
    private String esEvictionPolicy;

    @Value("${hazelcast.eviction.view-store.max-size:0}")
    private int viewEvictionMaxSize;

    @Value("${hazelcast.eviction.view-store.policy:NONE}")
    private String viewEvictionPolicy;

    @Value("${hazelcast.dlq.ttl-seconds:3600}")
    private int dlqTtlSeconds;

    @Value("${hazelcast.dlq.max-size:1000}")
    private int dlqMaxSize;

    @Autowired(required = false)
    private List<HazelcastConfigCustomizer> configCustomizers;

    /**
     * Comma-separated list of cluster member addresses for TCP/IP discovery.
     * If set, TCP/IP join is used instead of multicast (required for Docker).
     * Example: "hazelcast-1:5701,hazelcast-2:5701,hazelcast-3:5701"
     */
    @Value("${hazelcast.cluster.members:#{null}}")
    private String clusterMembers;

    /**
     * Creates a Hazelcast instance configured for event sourcing.
     * Only created if no other HazelcastInstance bean is defined.
     *
     * @return the configured HazelcastInstance
     */
    @Bean
    @ConditionalOnMissingBean(HazelcastInstance.class)
    public HazelcastInstance hazelcastInstance() {
        Config config = new Config();
        config.setClusterName(clusterName);

        // Network configuration
        config.getNetworkConfig()
                .setPort(networkPort)
                .setPortAutoIncrement(portAutoIncrement);

        // Configure cluster discovery
        configureClusterDiscovery(config);

        // Configure pending events maps with Event Journal
        configurePendingMaps(config);

        // Configure event store maps
        configureEventStoreMaps(config);

        // Configure view maps
        configureViewMaps(config);

        // Configure completions maps
        configureCompletionsMaps(config);

        // Configure outbox maps with indexes for efficient polling
        configureOutboxMaps(config);

        // Configure DLQ maps with TTL and eviction
        configureDlqMaps(config);

        // Enable Jet
        config.getJetConfig().setEnabled(true);

        // Apply framework-level customizers (e.g., HD Memory, TPC)
        if (configCustomizers != null) {
            configCustomizers.forEach(c -> c.customize(config));
        }

        logger.info("Creating Hazelcast instance with cluster name: {}", clusterName);
        return Hazelcast.newHazelcastInstance(config);
    }

    /**
     * Configures maps for pending events with Event Journal enabled.
     * These maps trigger the Jet pipeline via their event journals.
     */
    private void configurePendingMaps(Config config) {
        MapConfig pendingMapConfig = new MapConfig("*_PENDING");
        pendingMapConfig.setBackupCount(backupCount);

        // Enable Event Journal - required for Jet pipeline source
        EventJournalConfig journalConfig = new EventJournalConfig()
                .setEnabled(true)
                .setCapacity(eventJournalCapacity)
                .setTimeToLiveSeconds(eventJournalTtlSeconds);
        pendingMapConfig.setEventJournalConfig(journalConfig);

        config.addMapConfig(pendingMapConfig);
        logger.debug("Configured pending maps with event journal capacity: {}", eventJournalCapacity);
    }

    /**
     * Configures maps for event storage.
     * Default: no eviction (events are permanent). When {@code hazelcast.eviction.event-store.max-size}
     * is set to a value &gt; 0, LRU/LFU eviction is applied to prevent OOM in long-running demos.
     */
    private void configureEventStoreMaps(Config config) {
        MapConfig eventStoreMapConfig = new MapConfig("*_ES");
        eventStoreMapConfig.setBackupCount(backupCount);

        if (esEvictionMaxSize > 0) {
            EvictionConfig evictionConfig = new EvictionConfig()
                    .setMaxSizePolicy(MaxSizePolicy.PER_NODE)
                    .setSize(esEvictionMaxSize)
                    .setEvictionPolicy(com.hazelcast.config.EvictionPolicy.valueOf(esEvictionPolicy));
            eventStoreMapConfig.setEvictionConfig(evictionConfig);
            logger.info("Configured event store maps with {} eviction, max-size: {}", esEvictionPolicy, esEvictionMaxSize);
        } else {
            eventStoreMapConfig.getEvictionConfig()
                    .setEvictionPolicy(com.hazelcast.config.EvictionPolicy.NONE);
            logger.debug("Configured event store maps with no eviction (backup count: {})", backupCount);
        }

        config.addMapConfig(eventStoreMapConfig);
    }

    /**
     * Configures maps for materialized views.
     * These can be rebuilt from events if needed. When {@code hazelcast.eviction.view-store.max-size}
     * is set to a value &gt; 0, LRU/LFU eviction is applied.
     */
    private void configureViewMaps(Config config) {
        MapConfig viewMapConfig = new MapConfig("*_VIEW");
        viewMapConfig.setBackupCount(backupCount);

        // Allow backup reads for faster queries
        viewMapConfig.setReadBackupData(true);

        if (viewEvictionMaxSize > 0) {
            EvictionConfig evictionConfig = new EvictionConfig()
                    .setMaxSizePolicy(MaxSizePolicy.PER_NODE)
                    .setSize(viewEvictionMaxSize)
                    .setEvictionPolicy(com.hazelcast.config.EvictionPolicy.valueOf(viewEvictionPolicy));
            viewMapConfig.setEvictionConfig(evictionConfig);
            logger.info("Configured view maps with {} eviction, max-size: {}", viewEvictionPolicy, viewEvictionMaxSize);
        } else {
            logger.debug("Configured view maps with no eviction, read-backup-data enabled");
        }

        config.addMapConfig(viewMapConfig);
    }

    /**
     * Configures maps for completion tracking.
     * Entries expire after 1 hour (TTL) and are bounded by max-size per node
     * to prevent unbounded growth during extended demo sessions.
     */
    private void configureCompletionsMaps(Config config) {
        MapConfig completionsMapConfig = new MapConfig("*_COMPLETIONS");
        completionsMapConfig.setBackupCount(backupCount);

        // Completions can be evicted after TTL
        completionsMapConfig.setTimeToLiveSeconds(3600); // 1 hour

        // Safety net: bound map size per node to prevent OOM in multi-hour runs
        if (completionsMaxSize > 0) {
            EvictionConfig evictionConfig = new EvictionConfig()
                    .setMaxSizePolicy(MaxSizePolicy.PER_NODE)
                    .setSize(completionsMaxSize)
                    .setEvictionPolicy(com.hazelcast.config.EvictionPolicy.LRU);
            completionsMapConfig.setEvictionConfig(evictionConfig);
        }

        config.addMapConfig(completionsMapConfig);
        logger.debug("Configured completions maps with 1 hour TTL, max-size: {}", completionsMaxSize);
    }

    /**
     * Configures the outbox map with indexes for efficient polling.
     * A HASH index on {@code status} avoids full-scan deserialization for
     * equality predicates. A SORTED index on {@code createdAt} enables
     * server-side ordering inside {@code PagingPredicate}.
     */
    private void configureOutboxMaps(Config config) {
        MapConfig outboxMapConfig = new MapConfig("framework_OUTBOX");
        outboxMapConfig.setBackupCount(backupCount);
        outboxMapConfig.addIndexConfig(
                new IndexConfig(IndexType.HASH, "status"));
        outboxMapConfig.addIndexConfig(
                new IndexConfig(IndexType.SORTED, "createdAt"));

        // TTL: delivered entries should be cleaned up within 1 hour
        outboxMapConfig.setTimeToLiveSeconds(3600);

        // Safety-net eviction to prevent unbounded growth
        EvictionConfig outboxEviction = new EvictionConfig()
                .setMaxSizePolicy(MaxSizePolicy.PER_NODE)
                .setSize(10000)
                .setEvictionPolicy(com.hazelcast.config.EvictionPolicy.LRU);
        outboxMapConfig.setEvictionConfig(outboxEviction);

        config.addMapConfig(outboxMapConfig);
        logger.debug("Configured outbox map with HASH(status) and SORTED(createdAt) indexes, " +
                "1 hour TTL, LRU eviction max 10000 per node");
    }

    /**
     * Configures the DLQ map with TTL and bounded eviction.
     * Without this, the DLQ IMap is created dynamically with no eviction,
     * growing unbounded during long-running sessions.
     */
    private void configureDlqMaps(Config config) {
        MapConfig dlqMapConfig = new MapConfig("framework_DLQ");
        dlqMapConfig.setBackupCount(backupCount);
        dlqMapConfig.setTimeToLiveSeconds(dlqTtlSeconds);

        EvictionConfig evictionConfig = new EvictionConfig()
                .setMaxSizePolicy(MaxSizePolicy.PER_NODE)
                .setSize(dlqMaxSize)
                .setEvictionPolicy(com.hazelcast.config.EvictionPolicy.LRU);
        dlqMapConfig.setEvictionConfig(evictionConfig);

        config.addMapConfig(dlqMapConfig);
        logger.debug("Configured DLQ map with {} second TTL, LRU eviction max {} per node",
                dlqTtlSeconds, dlqMaxSize);
    }

    /**
     * Configures cluster discovery mechanism.
     * Uses TCP/IP join if cluster members are specified (Docker/production),
     * otherwise falls back to multicast for local development.
     */
    private void configureClusterDiscovery(Config config) {
        JoinConfig joinConfig = config.getNetworkConfig().getJoin();

        if (clusterMembers != null && !clusterMembers.trim().isEmpty()) {
            // Docker/Production mode: Use TCP/IP discovery
            joinConfig.getMulticastConfig().setEnabled(false);

            TcpIpConfig tcpIpConfig = joinConfig.getTcpIpConfig();
            tcpIpConfig.setEnabled(true);

            List<String> members = Arrays.asList(clusterMembers.split(","));
            for (String member : members) {
                tcpIpConfig.addMember(member.trim());
            }

            logger.info("Configured TCP/IP cluster discovery with members: {}", clusterMembers);
        } else {
            // Development mode: Use multicast for auto-discovery
            joinConfig.getMulticastConfig().setEnabled(true);
            joinConfig.getTcpIpConfig().setEnabled(false);

            logger.info("Configured multicast cluster discovery for local development");
        }
    }
}
