package com.theyawns.framework.config;

import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.Tag;
import io.micrometer.core.instrument.binder.jvm.ClassLoaderMetrics;
import io.micrometer.core.instrument.binder.jvm.JvmGcMetrics;
import io.micrometer.core.instrument.binder.jvm.JvmMemoryMetrics;
import io.micrometer.core.instrument.binder.jvm.JvmThreadMetrics;
import io.micrometer.core.instrument.binder.system.ProcessorMetrics;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.actuate.autoconfigure.metrics.MeterRegistryCustomizer;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.Arrays;

/**
 * Metrics configuration for the event sourcing framework.
 * Configures Micrometer for Prometheus export with common tags.
 *
 * <p>Provides:
 * <ul>
 *   <li>Common tags for all metrics (application, version)</li>
 *   <li>JVM metrics (memory, GC, threads)</li>
 *   <li>Processor metrics</li>
 * </ul>
 *
 * <p>Event sourcing specific metrics are created by:
 * <ul>
 *   <li>{@link com.theyawns.framework.pipeline.PipelineMetrics}</li>
 *   <li>{@link com.theyawns.framework.controller.EventSourcingController}</li>
 * </ul>
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
@Configuration
@ConditionalOnClass(MeterRegistry.class)
public class MetricsConfig {

    private static final Logger logger = LoggerFactory.getLogger(MetricsConfig.class);

    @Value("${spring.application.name:event-sourcing-framework}")
    private String applicationName;

    @Value("${spring.application.version:1.0.0}")
    private String applicationVersion;

    /**
     * Customizes the meter registry with common tags.
     *
     * @return the meter registry customizer
     */
    @Bean
    public MeterRegistryCustomizer<MeterRegistry> metricsCommonTags() {
        return registry -> {
            registry.config()
                    .commonTags(Arrays.asList(
                            Tag.of("application", applicationName),
                            Tag.of("version", applicationVersion)
                    ));
            logger.info("Configured metrics with common tags: application={}, version={}",
                    applicationName, applicationVersion);
        };
    }

    /**
     * Binds JVM memory metrics.
     *
     * @return the JVM memory metrics binder
     */
    @Bean
    public JvmMemoryMetrics jvmMemoryMetrics() {
        return new JvmMemoryMetrics();
    }

    /**
     * Binds JVM garbage collection metrics.
     *
     * @return the JVM GC metrics binder
     */
    @Bean
    public JvmGcMetrics jvmGcMetrics() {
        return new JvmGcMetrics();
    }

    /**
     * Binds JVM thread metrics.
     *
     * @return the JVM thread metrics binder
     */
    @Bean
    public JvmThreadMetrics jvmThreadMetrics() {
        return new JvmThreadMetrics();
    }

    /**
     * Binds class loader metrics.
     *
     * @return the class loader metrics binder
     */
    @Bean
    public ClassLoaderMetrics classLoaderMetrics() {
        return new ClassLoaderMetrics();
    }

    /**
     * Binds processor/CPU metrics.
     *
     * @return the processor metrics binder
     */
    @Bean
    public ProcessorMetrics processorMetrics() {
        return new ProcessorMetrics();
    }
}
