package com.theyawns.framework.config;

import com.theyawns.framework.tracing.EventSpanDecorator;
import io.micrometer.tracing.Tracer;
import io.opentelemetry.exporter.otlp.trace.OtlpGrpcSpanExporter;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Distributed tracing configuration for the event sourcing framework.
 *
 * <p>Configures OpenTelemetry trace export via OTLP to Jaeger and provides
 * the {@link EventSpanDecorator} bean for manual span creation around
 * event processing, pipeline stages, and saga steps.
 *
 * <p>Tracing is enabled by default but can be disabled via:
 * <pre>
 * management.tracing.enabled=false
 * </pre>
 *
 * <p>The OTLP endpoint defaults to localhost:4317 (Jaeger OTLP gRPC)
 * and can be overridden via:
 * <pre>
 * management.otlp.tracing.endpoint=http://jaeger:4317
 * </pre>
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
@Configuration
@ConditionalOnClass(Tracer.class)
@ConditionalOnProperty(name = "management.tracing.enabled", havingValue = "true", matchIfMissing = true)
public class TracingConfig {

    private static final Logger logger = LoggerFactory.getLogger(TracingConfig.class);

    /**
     * Creates the OTLP gRPC span exporter for sending traces to Jaeger.
     *
     * @param endpoint the OTLP collector endpoint
     * @return the configured span exporter
     */
    @Bean
    public OtlpGrpcSpanExporter otlpGrpcSpanExporter(
            @Value("${management.otlp.tracing.endpoint:http://localhost:4317}") String endpoint) {
        logger.info("Configuring OTLP trace exporter: endpoint={}", endpoint);
        return OtlpGrpcSpanExporter.builder()
                .setEndpoint(endpoint)
                .build();
    }

    /**
     * Creates the EventSpanDecorator for manual span creation around
     * event processing operations.
     *
     * <p>This bean is injected into {@link com.theyawns.framework.controller.EventSourcingController}
     * and saga listeners to create spans for event handling, pipeline stages,
     * and saga step execution.
     *
     * @param tracer the Micrometer tracer (auto-configured by Spring Boot)
     * @return the event span decorator
     */
    @Bean
    public EventSpanDecorator eventSpanDecorator(Tracer tracer) {
        logger.info("Configuring EventSpanDecorator for distributed tracing");
        return new EventSpanDecorator(tracer);
    }
}
