package com.theyawns.ecommerce.mcp.tools;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.theyawns.ecommerce.mcp.client.ServiceClientOperations;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * Tests for {@link GetMetricsTool}.
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
@DisplayName("GetMetricsTool")
@ExtendWith(MockitoExtension.class)
class GetMetricsToolTest {

    @Mock
    private ServiceClientOperations serviceClient;

    private GetMetricsTool getMetricsTool;
    private final ObjectMapper objectMapper = new ObjectMapper();

    @BeforeEach
    void setUp() {
        getMetricsTool = new GetMetricsTool(serviceClient);
    }

    @Test
    @DisplayName("should return metrics summary")
    void shouldReturnMetricsSummary() throws JsonProcessingException {
        Map<String, Object> metrics = Map.of(
                "sagas", Map.of(
                        "total", 10,
                        "completed", 7,
                        "failed", 2,
                        "inProgress", 1
                ),
                "events", Map.of(
                        "eventsSubmitted", 50.0,
                        "eventsProcessed", 48.0,
                        "eventsFailed", 2.0
                )
        );
        when(serviceClient.getMetricsSummary()).thenReturn(metrics);

        String result = getMetricsTool.getMetrics();

        verify(serviceClient).getMetricsSummary();
        Map<String, Object> parsed = objectMapper.readValue(result, new TypeReference<>() {});
        assertNotNull(parsed.get("sagas"));
        assertNotNull(parsed.get("events"));
    }

    @Test
    @DisplayName("should return error when service client throws exception")
    void shouldReturnErrorOnException() throws JsonProcessingException {
        when(serviceClient.getMetricsSummary()).thenThrow(new RuntimeException("Connection refused"));

        String result = getMetricsTool.getMetrics();

        Map<String, Object> parsed = objectMapper.readValue(result, new TypeReference<>() {});
        assertTrue(parsed.containsKey("error"));
        assertTrue(parsed.get("error").toString().contains("Connection refused"));
    }
}
