package com.theyawns.ecommerce.mcp.tools;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.theyawns.ecommerce.mcp.client.ServiceClientOperations;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * Tests for {@link InspectSagaTool}.
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
@DisplayName("InspectSagaTool")
@ExtendWith(MockitoExtension.class)
class InspectSagaToolTest {

    @Mock
    private ServiceClientOperations serviceClient;

    private InspectSagaTool inspectSagaTool;
    private final ObjectMapper objectMapper = new ObjectMapper();

    @BeforeEach
    void setUp() {
        inspectSagaTool = new InspectSagaTool(serviceClient);
    }

    @Test
    @DisplayName("should return saga state for valid saga ID")
    void shouldReturnSagaState() throws JsonProcessingException {
        Map<String, Object> saga = Map.of(
                "sagaId", "saga-123",
                "sagaType", "OrderFulfillment",
                "status", "COMPLETED",
                "currentStep", 4,
                "totalSteps", 4,
                "steps", List.of()
        );
        when(serviceClient.getSaga("saga-123")).thenReturn(saga);

        String result = inspectSagaTool.inspectSaga("saga-123");

        verify(serviceClient).getSaga("saga-123");
        Map<String, Object> parsed = objectMapper.readValue(result, new TypeReference<>() {});
        assertEquals("saga-123", parsed.get("sagaId"));
        assertEquals("OrderFulfillment", parsed.get("sagaType"));
        assertEquals("COMPLETED", parsed.get("status"));
    }

    @Test
    @DisplayName("should return error map when saga not found")
    void shouldReturnErrorWhenNotFound() throws JsonProcessingException {
        Map<String, Object> errorResponse = Map.of(
                "error", "Saga not found",
                "sagaId", "nonexistent",
                "status", 404
        );
        when(serviceClient.getSaga("nonexistent")).thenReturn(errorResponse);

        String result = inspectSagaTool.inspectSaga("nonexistent");

        verify(serviceClient).getSaga("nonexistent");
        Map<String, Object> parsed = objectMapper.readValue(result, new TypeReference<>() {});
        assertTrue(parsed.containsKey("error"));
    }

    @Test
    @DisplayName("should return error when service client throws exception")
    void shouldReturnErrorOnException() throws JsonProcessingException {
        when(serviceClient.getSaga("saga-err")).thenThrow(new RuntimeException("Connection refused"));

        String result = inspectSagaTool.inspectSaga("saga-err");

        Map<String, Object> parsed = objectMapper.readValue(result, new TypeReference<>() {});
        assertTrue(parsed.containsKey("error"));
        assertTrue(parsed.get("error").toString().contains("Connection refused"));
    }
}
