package com.theyawns.ecommerce.mcp.tools;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.theyawns.ecommerce.mcp.client.ServiceClientOperations;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * Tests for {@link InspectDlqEntryTool}.
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
@DisplayName("InspectDlqEntryTool")
@ExtendWith(MockitoExtension.class)
class InspectDlqEntryToolTest {

    @Mock
    private ServiceClientOperations serviceClient;

    private InspectDlqEntryTool inspectDlqEntryTool;
    private final ObjectMapper objectMapper = new ObjectMapper();

    @BeforeEach
    void setUp() {
        inspectDlqEntryTool = new InspectDlqEntryTool(serviceClient);
    }

    @Test
    @DisplayName("should return DLQ entry details for valid ID")
    void shouldReturnDlqEntryDetails() throws JsonProcessingException {
        Map<String, Object> entry = Map.of(
                "dlqEntryId", "dlq-123",
                "eventType", "OrderCreated",
                "failureReason", "Connection timeout",
                "replayCount", 0,
                "status", "PENDING"
        );
        when(serviceClient.getDlqEntry(null, "dlq-123")).thenReturn(entry);

        String result = inspectDlqEntryTool.inspectDlqEntry("dlq-123", null);

        verify(serviceClient).getDlqEntry(null, "dlq-123");
        Map<String, Object> parsed = objectMapper.readValue(result, new TypeReference<>() {});
        assertEquals("dlq-123", parsed.get("dlqEntryId"));
        assertEquals("OrderCreated", parsed.get("eventType"));
        assertEquals("Connection timeout", parsed.get("failureReason"));
    }

    @Test
    @DisplayName("should pass service name to client when provided")
    void shouldPassServiceName() throws JsonProcessingException {
        Map<String, Object> entry = Map.of("dlqEntryId", "dlq-456", "status", "PENDING");
        when(serviceClient.getDlqEntry("inventory", "dlq-456")).thenReturn(entry);

        String result = inspectDlqEntryTool.inspectDlqEntry("dlq-456", "inventory");

        verify(serviceClient).getDlqEntry("inventory", "dlq-456");
        Map<String, Object> parsed = objectMapper.readValue(result, new TypeReference<>() {});
        assertEquals("dlq-456", parsed.get("dlqEntryId"));
    }

    @Test
    @DisplayName("should return error when service client throws exception")
    void shouldReturnErrorOnException() throws JsonProcessingException {
        when(serviceClient.getDlqEntry(null, "dlq-err"))
                .thenThrow(new RuntimeException("Service unavailable"));

        String result = inspectDlqEntryTool.inspectDlqEntry("dlq-err", null);

        Map<String, Object> parsed = objectMapper.readValue(result, new TypeReference<>() {});
        assertTrue(parsed.containsKey("error"));
        assertTrue(parsed.get("error").toString().contains("Service unavailable"));
    }
}
