package com.theyawns.ecommerce.mcp.tools;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.theyawns.ecommerce.mcp.client.ServiceClientOperations;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * Tests for {@link ListDlqEntriesTool}.
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
@DisplayName("ListDlqEntriesTool")
@ExtendWith(MockitoExtension.class)
class ListDlqEntriesToolTest {

    @Mock
    private ServiceClientOperations serviceClient;

    private ListDlqEntriesTool listDlqEntriesTool;
    private final ObjectMapper objectMapper = new ObjectMapper();

    @BeforeEach
    void setUp() {
        listDlqEntriesTool = new ListDlqEntriesTool(serviceClient);
    }

    @Test
    @DisplayName("should return DLQ entries with pending count")
    void shouldReturnDlqEntriesWithPendingCount() throws JsonProcessingException {
        List<Map<String, Object>> entries = List.of(
                Map.of("dlqEntryId", "dlq-1", "eventType", "OrderCreated", "status", "PENDING"),
                Map.of("dlqEntryId", "dlq-2", "eventType", "StockReserved", "status", "PENDING")
        );
        when(serviceClient.listDlqEntries(null, 20)).thenReturn(entries);
        when(serviceClient.getDlqCount(null)).thenReturn(Map.of("pendingCount", 2));

        String result = listDlqEntriesTool.listDlqEntries(null, null);

        verify(serviceClient).listDlqEntries(null, 20);
        verify(serviceClient).getDlqCount(null);
        Map<String, Object> parsed = objectMapper.readValue(result, new TypeReference<>() {});
        assertNotNull(parsed.get("entries"));
        assertEquals(2, parsed.get("count"));
        assertNotNull(parsed.get("pendingCount"));
    }

    @Test
    @DisplayName("should use custom limit when provided")
    void shouldUseCustomLimit() throws JsonProcessingException {
        when(serviceClient.listDlqEntries("inventory", 5)).thenReturn(List.of());
        when(serviceClient.getDlqCount("inventory")).thenReturn(Map.of("pendingCount", 0));

        String result = listDlqEntriesTool.listDlqEntries("inventory", 5);

        verify(serviceClient).listDlqEntries("inventory", 5);
        Map<String, Object> parsed = objectMapper.readValue(result, new TypeReference<>() {});
        assertEquals(0, parsed.get("count"));
    }

    @Test
    @DisplayName("should default limit to 20 when null or zero")
    void shouldDefaultLimitWhenNullOrZero() throws JsonProcessingException {
        when(serviceClient.listDlqEntries(null, 20)).thenReturn(List.of());
        when(serviceClient.getDlqCount(null)).thenReturn(Map.of("pendingCount", 0));

        listDlqEntriesTool.listDlqEntries(null, 0);

        verify(serviceClient).listDlqEntries(null, 20);
    }

    @Test
    @DisplayName("should return error when service client throws exception")
    void shouldReturnErrorOnException() throws JsonProcessingException {
        when(serviceClient.listDlqEntries(null, 20))
                .thenThrow(new RuntimeException("Connection refused"));

        String result = listDlqEntriesTool.listDlqEntries(null, null);

        Map<String, Object> parsed = objectMapper.readValue(result, new TypeReference<>() {});
        assertTrue(parsed.containsKey("error"));
        assertTrue(parsed.get("error").toString().contains("Connection refused"));
    }
}
