package com.theyawns.ecommerce.mcp.tools;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.theyawns.ecommerce.mcp.client.ServiceClientOperations;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * Tests for {@link QueryViewTool}.
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
@DisplayName("QueryViewTool")
@ExtendWith(MockitoExtension.class)
class QueryViewToolTest {

    @Mock
    private ServiceClientOperations serviceClient;

    private QueryViewTool queryViewTool;
    private final ObjectMapper objectMapper = new ObjectMapper();

    @BeforeEach
    void setUp() {
        queryViewTool = new QueryViewTool(serviceClient);
    }

    @Test
    @DisplayName("should query specific entity by key")
    void shouldQueryByKey() throws JsonProcessingException {
        Map<String, Object> customer = Map.of(
                "customerId", "c1",
                "name", "Alice",
                "email", "alice@example.com"
        );
        when(serviceClient.getEntity("customer", "c1")).thenReturn(customer);

        String result = queryViewTool.queryView("customer", "c1", null);

        verify(serviceClient).getEntity("customer", "c1");
        Map<String, Object> parsed = objectMapper.readValue(result, new TypeReference<>() {});
        assertNotNull(parsed.get("customerId"));
    }

    @Test
    @DisplayName("should list entities when key is null")
    void shouldListEntitiesWhenKeyNull() throws JsonProcessingException {
        List<Map<String, Object>> customers = List.of(
                Map.of("customerId", "c1", "name", "Alice"),
                Map.of("customerId", "c2", "name", "Bob")
        );
        when(serviceClient.listEntities("customer", 10)).thenReturn(customers);

        String result = queryViewTool.queryView("customer", null, null);

        verify(serviceClient).listEntities("customer", 10);
        Map<String, Object> parsed = objectMapper.readValue(result, new TypeReference<>() {});
        assertNotNull(parsed.get("entities"));
        assertNotNull(parsed.get("count"));
    }

    @Test
    @DisplayName("should list entities when key is blank")
    void shouldListEntitiesWhenKeyBlank() {
        when(serviceClient.listEntities("product", 5)).thenReturn(List.of());

        queryViewTool.queryView("product", "  ", 5);

        verify(serviceClient).listEntities("product", 5);
    }

    @Test
    @DisplayName("should use custom limit when listing")
    void shouldUseCustomLimit() {
        when(serviceClient.listEntities("order", 25)).thenReturn(List.of());

        queryViewTool.queryView("order", null, 25);

        verify(serviceClient).listEntities("order", 25);
    }

    @Test
    @DisplayName("should default to limit 10 when limit is null")
    void shouldDefaultLimit() {
        when(serviceClient.listEntities("payment", 10)).thenReturn(List.of());

        queryViewTool.queryView("payment", null, null);

        verify(serviceClient).listEntities("payment", 10);
    }

    @Test
    @DisplayName("should return error for unknown view")
    void shouldReturnErrorForUnknownView() throws JsonProcessingException {
        when(serviceClient.getEntity(eq("unknown"), eq("id1")))
                .thenThrow(new IllegalArgumentException("Unknown view: unknown"));

        String result = queryViewTool.queryView("unknown", "id1", null);

        Map<String, Object> parsed = objectMapper.readValue(result, new TypeReference<>() {});
        assertTrue(parsed.containsKey("error"));
    }
}
