package com.theyawns.ecommerce.mcp.tools;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.theyawns.ecommerce.mcp.client.ServiceClientOperations;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * Tests for {@link ReplayDlqEntryTool}.
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
@DisplayName("ReplayDlqEntryTool")
@ExtendWith(MockitoExtension.class)
class ReplayDlqEntryToolTest {

    @Mock
    private ServiceClientOperations serviceClient;

    private ReplayDlqEntryTool replayDlqEntryTool;
    private final ObjectMapper objectMapper = new ObjectMapper();

    @BeforeEach
    void setUp() {
        replayDlqEntryTool = new ReplayDlqEntryTool(serviceClient);
    }

    @Test
    @DisplayName("should replay DLQ entry successfully")
    void shouldReplayDlqEntry() throws JsonProcessingException {
        Map<String, Object> replayResult = Map.of(
                "dlqEntryId", "dlq-123",
                "status", "REPLAYED",
                "message", "Event republished to topic"
        );
        when(serviceClient.replayDlqEntry(null, "dlq-123")).thenReturn(replayResult);

        String result = replayDlqEntryTool.replayDlqEntry("dlq-123", null);

        verify(serviceClient).replayDlqEntry(null, "dlq-123");
        Map<String, Object> parsed = objectMapper.readValue(result, new TypeReference<>() {});
        assertEquals("dlq-123", parsed.get("dlqEntryId"));
        assertEquals("REPLAYED", parsed.get("status"));
    }

    @Test
    @DisplayName("should pass service name to client when provided")
    void shouldPassServiceName() throws JsonProcessingException {
        Map<String, Object> replayResult = Map.of("dlqEntryId", "dlq-456", "status", "REPLAYED");
        when(serviceClient.replayDlqEntry("inventory", "dlq-456")).thenReturn(replayResult);

        String result = replayDlqEntryTool.replayDlqEntry("dlq-456", "inventory");

        verify(serviceClient).replayDlqEntry("inventory", "dlq-456");
        Map<String, Object> parsed = objectMapper.readValue(result, new TypeReference<>() {});
        assertEquals("dlq-456", parsed.get("dlqEntryId"));
    }

    @Test
    @DisplayName("should return error when service client throws exception")
    void shouldReturnErrorOnException() throws JsonProcessingException {
        when(serviceClient.replayDlqEntry(null, "dlq-err"))
                .thenThrow(new RuntimeException("Entry not found"));

        String result = replayDlqEntryTool.replayDlqEntry("dlq-err", null);

        Map<String, Object> parsed = objectMapper.readValue(result, new TypeReference<>() {});
        assertTrue(parsed.containsKey("error"));
        assertTrue(parsed.get("error").toString().contains("Entry not found"));
    }
}
