package com.theyawns.ecommerce.mcp.tools;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.theyawns.ecommerce.mcp.client.ServiceClientOperations;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * Tests for {@link SubmitEventTool}.
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
@DisplayName("SubmitEventTool")
@ExtendWith(MockitoExtension.class)
class SubmitEventToolTest {

    @Mock
    private ServiceClientOperations serviceClient;

    private SubmitEventTool submitEventTool;
    private final ObjectMapper objectMapper = new ObjectMapper();

    @BeforeEach
    void setUp() {
        submitEventTool = new SubmitEventTool(serviceClient);
    }

    @Test
    @DisplayName("should dispatch CreateCustomer to account service")
    void shouldDispatchCreateCustomer() throws JsonProcessingException {
        Map<String, Object> response = Map.of("customerId", "c1", "name", "Alice");
        when(serviceClient.createEntity(eq("customer"), any())).thenReturn(response);

        String result = submitEventTool.submitEvent("CreateCustomer",
                "{\"name\":\"Alice\",\"email\":\"alice@example.com\"}");

        verify(serviceClient).createEntity(eq("customer"), any());
        Map<String, Object> parsed = objectMapper.readValue(result, new TypeReference<>() {});
        assertNotNull(parsed.get("result"));
    }

    @Test
    @DisplayName("should dispatch CreateProduct to inventory service")
    void shouldDispatchCreateProduct() throws JsonProcessingException {
        Map<String, Object> response = Map.of("productId", "p1");
        when(serviceClient.createEntity(eq("product"), any())).thenReturn(response);

        String result = submitEventTool.submitEvent("CreateProduct",
                "{\"sku\":\"SKU-1\",\"name\":\"Widget\",\"price\":\"9.99\",\"quantityOnHand\":100}");

        verify(serviceClient).createEntity(eq("product"), any());
        assertNotNull(result);
    }

    @Test
    @DisplayName("should dispatch CreateOrder to order service")
    void shouldDispatchCreateOrder() {
        when(serviceClient.createEntity(eq("order"), any())).thenReturn(Map.of("orderId", "o1"));

        submitEventTool.submitEvent("CreateOrder",
                "{\"customerId\":\"c1\",\"lineItems\":[{\"productId\":\"p1\",\"quantity\":2}]}");

        verify(serviceClient).createEntity(eq("order"), any());
    }

    @Test
    @DisplayName("should dispatch CancelOrder with orderId")
    void shouldDispatchCancelOrder() {
        when(serviceClient.performAction(eq("order"), eq("o1"), eq("cancel"), any(), eq(true)))
                .thenReturn(Map.of("orderId", "o1", "status", "CANCELLED"));

        submitEventTool.submitEvent("CancelOrder",
                "{\"orderId\":\"o1\",\"reason\":\"Customer request\",\"cancelledBy\":\"customer\"}");

        verify(serviceClient).performAction(eq("order"), eq("o1"), eq("cancel"), any(), eq(true));
    }

    @Test
    @DisplayName("should dispatch ReserveStock with productId")
    void shouldDispatchReserveStock() {
        when(serviceClient.performAction(eq("product"), eq("p1"), eq("stock/reserve"), any(), eq(false)))
                .thenReturn(Map.of("productId", "p1"));

        submitEventTool.submitEvent("ReserveStock",
                "{\"productId\":\"p1\",\"quantity\":5,\"orderId\":\"o1\"}");

        verify(serviceClient).performAction(eq("product"), eq("p1"), eq("stock/reserve"), any(), eq(false));
    }

    @Test
    @DisplayName("should dispatch ProcessPayment to payment service")
    void shouldDispatchProcessPayment() {
        when(serviceClient.createEntity(eq("payment"), any())).thenReturn(Map.of("paymentId", "pay1"));

        submitEventTool.submitEvent("ProcessPayment",
                "{\"orderId\":\"o1\",\"customerId\":\"c1\",\"amount\":\"99.99\",\"currency\":\"USD\"}");

        verify(serviceClient).createEntity(eq("payment"), any());
    }

    @Test
    @DisplayName("should dispatch RefundPayment with paymentId")
    void shouldDispatchRefundPayment() {
        when(serviceClient.performAction(eq("payment"), eq("pay1"), eq("refund"), any(), eq(false)))
                .thenReturn(Map.of("paymentId", "pay1", "status", "REFUNDED"));

        submitEventTool.submitEvent("RefundPayment",
                "{\"paymentId\":\"pay1\",\"reason\":\"Defective product\"}");

        verify(serviceClient).performAction(eq("payment"), eq("pay1"), eq("refund"), any(), eq(false));
    }

    @Test
    @DisplayName("should return error for unknown event type")
    void shouldReturnErrorForUnknownEventType() throws JsonProcessingException {
        String result = submitEventTool.submitEvent("UnknownEvent", "{}");

        Map<String, Object> parsed = objectMapper.readValue(result, new TypeReference<>() {});
        assertTrue(parsed.containsKey("error"));
        assertTrue(parsed.get("error").toString().contains("Unknown event type"));
    }

    @Test
    @DisplayName("should return error for invalid JSON payload")
    void shouldReturnErrorForInvalidJson() throws JsonProcessingException {
        String result = submitEventTool.submitEvent("CreateCustomer", "not-json");

        Map<String, Object> parsed = objectMapper.readValue(result, new TypeReference<>() {});
        assertTrue(parsed.containsKey("error"));
        assertTrue(parsed.get("error").toString().contains("Invalid JSON"));
    }

    @Test
    @DisplayName("should return error when required field is missing for CancelOrder")
    void shouldReturnErrorWhenOrderIdMissing() throws JsonProcessingException {
        String result = submitEventTool.submitEvent("CancelOrder",
                "{\"reason\":\"Customer request\"}");

        Map<String, Object> parsed = objectMapper.readValue(result, new TypeReference<>() {});
        assertTrue(parsed.containsKey("error"));
        assertTrue(parsed.get("error").toString().contains("orderId"));
    }
}
