package com.theyawns.framework.outbox;

import org.springframework.boot.context.properties.ConfigurationProperties;

import java.time.Duration;

/**
 * Configuration properties for the transactional outbox.
 *
 * <p>Example configuration in application.yml:
 * <pre>{@code
 * framework:
 *   outbox:
 *     enabled: true
 *     poll-interval: 1s
 *     max-batch-size: 50
 *     max-retries: 5
 *     entry-ttl: 24h
 * }</pre>
 *
 * @author Generated by Claude Code
 * @since 3.0
 * @see OutboxAutoConfiguration
 */
@ConfigurationProperties(prefix = "framework.outbox")
public class OutboxProperties {

    /**
     * Whether the outbox pattern is enabled.
     * Default: true
     */
    private boolean enabled = true;

    /**
     * How often the OutboxPublisher polls for pending entries.
     * Default: 1 second
     */
    private Duration pollInterval = Duration.ofSeconds(1);

    /**
     * Maximum number of entries to process per poll cycle.
     * Default: 50
     */
    private int maxBatchSize = 50;

    /**
     * Maximum number of delivery retries before marking an entry as FAILED.
     * Default: 5
     */
    private int maxRetries = 5;

    /**
     * How long DELIVERED entries survive before eviction.
     * Default: 24 hours
     */
    private Duration entryTtl = Duration.ofHours(24);

    /**
     * Creates a new OutboxProperties with default values.
     */
    public OutboxProperties() {
        // Default constructor
    }

    /**
     * Returns whether the outbox pattern is enabled.
     *
     * @return true if enabled
     */
    public boolean isEnabled() {
        return enabled;
    }

    /**
     * Sets whether the outbox pattern is enabled.
     *
     * @param enabled true to enable the outbox
     */
    public void setEnabled(final boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * Returns the poll interval.
     *
     * @return the poll interval
     */
    public Duration getPollInterval() {
        return pollInterval;
    }

    /**
     * Sets the poll interval.
     *
     * @param pollInterval the poll interval
     */
    public void setPollInterval(final Duration pollInterval) {
        this.pollInterval = pollInterval;
    }

    /**
     * Returns the maximum batch size per poll cycle.
     *
     * @return the max batch size
     */
    public int getMaxBatchSize() {
        return maxBatchSize;
    }

    /**
     * Sets the maximum batch size per poll cycle.
     *
     * @param maxBatchSize the max batch size (must be >= 1)
     */
    public void setMaxBatchSize(final int maxBatchSize) {
        if (maxBatchSize < 1) {
            throw new IllegalArgumentException("maxBatchSize must be at least 1, got: " + maxBatchSize);
        }
        this.maxBatchSize = maxBatchSize;
    }

    /**
     * Returns the maximum number of delivery retries.
     *
     * @return the max retries
     */
    public int getMaxRetries() {
        return maxRetries;
    }

    /**
     * Sets the maximum number of delivery retries.
     *
     * @param maxRetries the max retries (must be >= 1)
     */
    public void setMaxRetries(final int maxRetries) {
        if (maxRetries < 1) {
            throw new IllegalArgumentException("maxRetries must be at least 1, got: " + maxRetries);
        }
        this.maxRetries = maxRetries;
    }

    /**
     * Returns the entry TTL for DELIVERED entries.
     *
     * @return the entry TTL
     */
    public Duration getEntryTtl() {
        return entryTtl;
    }

    /**
     * Sets the entry TTL for DELIVERED entries.
     *
     * @param entryTtl the entry TTL
     */
    public void setEntryTtl(final Duration entryTtl) {
        this.entryTtl = entryTtl;
    }

    @Override
    public String toString() {
        return "OutboxProperties{" +
                "enabled=" + enabled +
                ", pollInterval=" + pollInterval +
                ", maxBatchSize=" + maxBatchSize +
                ", maxRetries=" + maxRetries +
                ", entryTtl=" + entryTtl +
                '}';
    }
}
