package com.theyawns.framework.outbox;

import com.hazelcast.nio.serialization.genericrecord.GenericRecord;

import java.time.Instant;
import java.util.Objects;

/**
 * Represents an entry in the transactional outbox.
 *
 * <p>Each outbox entry stores a domain event that needs to be published
 * to the shared cluster's ITopic. The {@link OutboxPublisher} polls
 * for PENDING entries and delivers them, marking each as DELIVERED
 * on success or incrementing the retry count on failure.
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
public class OutboxEntry {

    /**
     * Unique identifier for this outbox entry (matches the domain event's eventId).
     */
    private String eventId;

    /**
     * The event type / topic name (e.g., "OrderCreated", "StockReserved").
     */
    private String eventType;

    /**
     * The serialized event record to publish to the shared cluster ITopic.
     */
    private GenericRecord eventRecord;

    /**
     * Number of delivery attempts so far.
     */
    private int retryCount;

    /**
     * Current delivery status.
     */
    private Status status;

    /**
     * When this entry was created.
     */
    private Instant createdAt;

    /**
     * When the last delivery attempt occurred.
     */
    private Instant lastAttemptAt;

    /**
     * Reason for the most recent failure, if any.
     */
    private String failureReason;

    /**
     * UUID of the cluster member that claimed this entry for delivery.
     * Only set when status is {@link Status#CLAIMED}.
     */
    private String claimantId;

    /**
     * When this entry was claimed for delivery.
     * Only set when status is {@link Status#CLAIMED}.
     */
    private Instant claimedAt;

    /**
     * No-arg constructor used by {@link #reconstitute} for deserialization.
     */
    public OutboxEntry() {
    }

    /**
     * Reconstitutes an OutboxEntry from stored field values.
     *
     * <p>Package-private — used by {@link HazelcastOutboxStore} when
     * reading entries from the IMap's Compact-serialized GenericRecords.
     *
     * @param eventId the event identifier
     * @param eventType the event type
     * @param eventRecord the serialized event record
     * @param retryCount the number of delivery attempts
     * @param status the current status
     * @param createdAt the creation timestamp
     * @param lastAttemptAt the last attempt timestamp (nullable)
     * @param failureReason the failure reason (nullable)
     * @return a reconstituted outbox entry
     */
    static OutboxEntry reconstitute(final String eventId, final String eventType,
            final GenericRecord eventRecord, final int retryCount, final Status status,
            final Instant createdAt, final Instant lastAttemptAt, final String failureReason) {
        return reconstitute(eventId, eventType, eventRecord, retryCount, status,
                createdAt, lastAttemptAt, failureReason, null, null);
    }

    /**
     * Reconstitutes an OutboxEntry from stored field values, including claim fields.
     *
     * @param eventId the event identifier
     * @param eventType the event type
     * @param eventRecord the serialized event record
     * @param retryCount the number of delivery attempts
     * @param status the current status
     * @param createdAt the creation timestamp
     * @param lastAttemptAt the last attempt timestamp (nullable)
     * @param failureReason the failure reason (nullable)
     * @param claimantId the claiming member UUID (nullable)
     * @param claimedAt the claim timestamp (nullable)
     * @return a reconstituted outbox entry
     */
    static OutboxEntry reconstitute(final String eventId, final String eventType,
            final GenericRecord eventRecord, final int retryCount, final Status status,
            final Instant createdAt, final Instant lastAttemptAt, final String failureReason,
            final String claimantId, final Instant claimedAt) {
        final OutboxEntry entry = new OutboxEntry();
        entry.eventId = eventId;
        entry.eventType = eventType;
        entry.eventRecord = eventRecord;
        entry.retryCount = retryCount;
        entry.status = status;
        entry.createdAt = createdAt;
        entry.lastAttemptAt = lastAttemptAt;
        entry.failureReason = failureReason;
        entry.claimantId = claimantId;
        entry.claimedAt = claimedAt;
        return entry;
    }

    /**
     * Creates a new outbox entry in PENDING status.
     *
     * @param eventId the domain event's unique identifier
     * @param eventType the event type / topic name
     * @param eventRecord the serialized event record
     */
    public OutboxEntry(final String eventId, final String eventType, final GenericRecord eventRecord) {
        this.eventId = Objects.requireNonNull(eventId, "eventId cannot be null");
        this.eventType = Objects.requireNonNull(eventType, "eventType cannot be null");
        this.eventRecord = Objects.requireNonNull(eventRecord, "eventRecord cannot be null");
        this.retryCount = 0;
        this.status = Status.PENDING;
        this.createdAt = Instant.now();
        this.lastAttemptAt = null;
        this.failureReason = null;
    }

    /**
     * Returns the event identifier.
     *
     * @return the event ID
     */
    public String getEventId() {
        return eventId;
    }

    /**
     * Returns the event type (topic name).
     *
     * @return the event type
     */
    public String getEventType() {
        return eventType;
    }

    /**
     * Returns the serialized event record.
     *
     * @return the event record
     */
    public GenericRecord getEventRecord() {
        return eventRecord;
    }

    /**
     * Returns the number of delivery attempts.
     *
     * @return retry count
     */
    public int getRetryCount() {
        return retryCount;
    }

    /**
     * Sets the retry count.
     *
     * @param retryCount the new retry count
     */
    public void setRetryCount(final int retryCount) {
        this.retryCount = retryCount;
    }

    /**
     * Returns the current delivery status.
     *
     * @return the status
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Sets the delivery status.
     *
     * @param status the new status
     */
    public void setStatus(final Status status) {
        this.status = Objects.requireNonNull(status, "status cannot be null");
    }

    /**
     * Returns when this entry was created.
     *
     * @return creation timestamp
     */
    public Instant getCreatedAt() {
        return createdAt;
    }

    /**
     * Returns when the last delivery attempt occurred.
     *
     * @return last attempt timestamp, or null if no attempt yet
     */
    public Instant getLastAttemptAt() {
        return lastAttemptAt;
    }

    /**
     * Sets the last attempt timestamp.
     *
     * @param lastAttemptAt the timestamp of the last delivery attempt
     */
    public void setLastAttemptAt(final Instant lastAttemptAt) {
        this.lastAttemptAt = lastAttemptAt;
    }

    /**
     * Returns the failure reason from the most recent attempt.
     *
     * @return the failure reason, or null if no failure
     */
    public String getFailureReason() {
        return failureReason;
    }

    /**
     * Sets the failure reason.
     *
     * @param failureReason the reason for the most recent failure
     */
    public void setFailureReason(final String failureReason) {
        this.failureReason = failureReason;
    }

    /**
     * Returns the UUID of the cluster member that claimed this entry.
     *
     * @return the claimant member UUID, or null if not claimed
     */
    public String getClaimantId() {
        return claimantId;
    }

    /**
     * Sets the claimant member UUID.
     *
     * @param claimantId the UUID of the claiming member
     */
    public void setClaimantId(final String claimantId) {
        this.claimantId = claimantId;
    }

    /**
     * Returns when this entry was claimed for delivery.
     *
     * @return the claim timestamp, or null if not claimed
     */
    public Instant getClaimedAt() {
        return claimedAt;
    }

    /**
     * Sets the claim timestamp.
     *
     * @param claimedAt the timestamp when the entry was claimed
     */
    public void setClaimedAt(final Instant claimedAt) {
        this.claimedAt = claimedAt;
    }

    @Override
    public String toString() {
        return "OutboxEntry{" +
                "eventId='" + eventId + '\'' +
                ", eventType='" + eventType + '\'' +
                ", retryCount=" + retryCount +
                ", status=" + status +
                ", createdAt=" + createdAt +
                ", lastAttemptAt=" + lastAttemptAt +
                ", claimantId='" + claimantId + '\'' +
                ", claimedAt=" + claimedAt +
                '}';
    }

    /**
     * Delivery status of an outbox entry.
     */
    public enum Status {
        /** Awaiting delivery to shared cluster. */
        PENDING,
        /** Claimed by a cluster member for delivery (atomic CAS from PENDING). */
        CLAIMED,
        /** Successfully delivered to shared cluster ITopic. */
        DELIVERED,
        /** Permanently failed after exhausting retries. */
        FAILED
    }
}
