package com.theyawns.framework.outbox;

import java.util.List;

/**
 * Interface for the transactional outbox store.
 *
 * <p>The outbox store durably persists events that need to be published
 * to the shared cluster. The {@link OutboxPublisher} polls this store
 * for pending entries and delivers them.
 *
 * <p>Implementations should be backed by a durable store (e.g., Hazelcast IMap)
 * to survive process restarts.
 *
 * @author Generated by Claude Code
 * @since 3.0
 * @see HazelcastOutboxStore
 * @see OutboxPublisher
 */
public interface OutboxStore {

    /**
     * Writes a new outbox entry in PENDING status.
     *
     * @param entry the outbox entry to write
     */
    void write(OutboxEntry entry);

    /**
     * Polls for pending outbox entries, ordered by creation time (oldest first).
     *
     * @param maxBatchSize the maximum number of entries to return
     * @return list of pending entries, may be empty
     */
    List<OutboxEntry> pollPending(int maxBatchSize);

    /**
     * Marks an outbox entry as successfully delivered.
     *
     * @param eventId the event identifier
     */
    void markDelivered(String eventId);

    /**
     * Marks an outbox entry as permanently failed.
     *
     * @param eventId the event identifier
     * @param reason the failure reason
     */
    void markFailed(String eventId, String reason);

    /**
     * Increments the retry count for an entry and records the failure reason.
     *
     * @param eventId the event identifier
     * @param failureReason the reason for the failed attempt
     */
    void incrementRetryCount(String eventId, String failureReason);

    /**
     * Returns the number of entries currently in PENDING status.
     *
     * @return the pending entry count
     */
    long pendingCount();

    /**
     * Atomically claims up to {@code maxBatchSize} PENDING entries for the given
     * cluster member. Uses compare-and-swap semantics: only entries in PENDING
     * status are transitioned to CLAIMED.
     *
     * <p>In a single-member deployment, CAS always succeeds. In a multi-member
     * deployment, only one member wins each entry's CAS — preventing duplicate
     * delivery.
     *
     * @param maxBatchSize the maximum number of entries to claim
     * @param claimantId the UUID of the claiming cluster member
     * @return list of successfully claimed entries, may be empty
     */
    List<OutboxEntry> claimPending(int maxBatchSize, String claimantId);

    /**
     * Releases entries that have been CLAIMED for longer than the given timeout,
     * reverting them to PENDING so another member can retry.
     *
     * <p>This handles the case where a member claims entries but crashes before
     * delivering them.
     *
     * @param staleTimeoutMs entries claimed longer ago than this (in millis) are released
     * @return the number of entries released
     */
    int releaseExpiredClaims(long staleTimeoutMs);
}
