package com.theyawns.ecommerce.order.saga;

import com.hazelcast.config.Config;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.theyawns.framework.saga.HazelcastSagaStateStore;
import com.theyawns.framework.saga.SagaCompensationConfig;
import com.theyawns.framework.saga.SagaState;
import com.theyawns.framework.saga.SagaStateStore;
import com.theyawns.framework.saga.SagaStatus;
import io.micrometer.core.instrument.simple.SimpleMeterRegistry;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.TestMethodOrder;

import java.time.Duration;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Integration test for the Order Fulfillment Saga compensation path.
 *
 * <p>Validates the complete compensation flow when payment fails:
 * <ol>
 *   <li>OrderCreated (step 0) - Order service creates order and starts saga</li>
 *   <li>StockReserved (step 1) - Inventory service reserves stock</li>
 *   <li>PaymentFailed (step 2) - Payment service fails, triggers compensation</li>
 *   <li>StockReleased (compensate step 1) - Inventory releases reserved stock</li>
 *   <li>OrderCancelled (compensate step 0) - Order service cancels order, saga COMPENSATED</li>
 * </ol>
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
@DisplayName("Order Fulfillment Saga - Compensation Path Integration")
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class OrderFulfillmentSagaCompensationTest {

    private HazelcastInstance hazelcast;
    private SagaStateStore sagaStateStore;

    // Test data
    private final String sagaId = UUID.randomUUID().toString();
    private final String correlationId = UUID.randomUUID().toString();

    @BeforeAll
    void setUp() {
        Config config = new Config();
        config.setClusterName("saga-compensation-test-" + System.currentTimeMillis());
        hazelcast = Hazelcast.newHazelcastInstance(config);

        sagaStateStore = new HazelcastSagaStateStore(hazelcast, new SimpleMeterRegistry());
    }

    @AfterAll
    void tearDown() {
        if (hazelcast != null) {
            hazelcast.shutdown();
        }
    }

    @Test
    @DisplayName("should compensate saga when payment fails")
    @org.junit.jupiter.api.Order(1)
    void shouldCompensateSagaWhenPaymentFails() {
        // ===== Step 0: Order Created - Start Saga =====
        SagaState state = sagaStateStore.startSaga(
                sagaId,
                SagaCompensationConfig.ORDER_FULFILLMENT_SAGA,
                correlationId,
                4,
                Duration.ofSeconds(60)
        );

        assertNotNull(state);
        assertEquals(SagaStatus.STARTED, state.getStatus());

        // Record step 0 completed (OrderCreated published)
        state = sagaStateStore.recordStepCompleted(
                sagaId,
                SagaCompensationConfig.STEP_ORDER_CREATED,
                SagaCompensationConfig.ORDER_CREATED,
                SagaCompensationConfig.ORDER_SERVICE,
                "evt-order-created"
        );

        assertEquals(SagaStatus.IN_PROGRESS, state.getStatus());
        assertEquals(1, state.getCurrentStep());

        // ===== Step 1: Stock Reserved - Inventory Service =====
        state = sagaStateStore.recordStepCompleted(
                sagaId,
                SagaCompensationConfig.STEP_STOCK_RESERVED,
                SagaCompensationConfig.STOCK_RESERVED,
                SagaCompensationConfig.INVENTORY_SERVICE,
                "evt-stock-reserved"
        );

        assertEquals(SagaStatus.IN_PROGRESS, state.getStatus());
        assertEquals(2, state.getCurrentStep());

        // ===== Step 2: Payment FAILS - Payment Service =====
        state = sagaStateStore.recordStepFailed(
                sagaId,
                SagaCompensationConfig.STEP_PAYMENT_PROCESSED,
                SagaCompensationConfig.PAYMENT_FAILED,
                SagaCompensationConfig.PAYMENT_SERVICE,
                "Payment declined by processor"
        );

        assertEquals(SagaStatus.COMPENSATING, state.getStatus());
        assertNotNull(state.getFailureReason());
        assertEquals("Payment declined by processor", state.getFailureReason());
        assertEquals(SagaCompensationConfig.STEP_PAYMENT_PROCESSED, state.getFailedAtStep());

        // ===== Compensation Step: Stock Released - Inventory Service =====
        state = sagaStateStore.recordCompensationStep(
                sagaId,
                SagaCompensationConfig.STEP_STOCK_RESERVED,
                SagaCompensationConfig.STOCK_RELEASED,
                SagaCompensationConfig.INVENTORY_SERVICE
        );

        // Still compensating (order cancellation pending)
        assertEquals(SagaStatus.COMPENSATING, state.getStatus());

        // ===== Compensation Step: Order Cancelled - Order Service =====
        state = sagaStateStore.recordCompensationStep(
                sagaId,
                SagaCompensationConfig.STEP_ORDER_CREATED,
                SagaCompensationConfig.ORDER_CANCELLED,
                SagaCompensationConfig.ORDER_SERVICE
        );

        // Still COMPENSATING until completeSaga is called
        assertEquals(SagaStatus.COMPENSATING, state.getStatus());

        // ===== Finalize: Mark saga as COMPENSATED =====
        state = sagaStateStore.completeSaga(sagaId, SagaStatus.COMPENSATED);

        assertEquals(SagaStatus.COMPENSATED, state.getStatus());
        assertTrue(state.getStatus().isTerminal());
        assertTrue(state.getStatus().isFailure());
        assertNotNull(state.getCompletedAt());
    }

    @Test
    @DisplayName("should track compensated saga state correctly")
    @org.junit.jupiter.api.Order(2)
    void shouldTrackCompensatedSagaState() {
        Optional<SagaState> sagaOpt = sagaStateStore.getSagaState(sagaId);
        assertTrue(sagaOpt.isPresent());

        SagaState finalState = sagaOpt.get();
        assertEquals(SagaStatus.COMPENSATED, finalState.getStatus());
        assertEquals(sagaId, finalState.getSagaId());
        assertEquals(SagaCompensationConfig.ORDER_FULFILLMENT_SAGA, finalState.getSagaType());
        assertEquals("Payment declined by processor", finalState.getFailureReason());
    }

    @Test
    @DisplayName("should find compensated saga by status")
    @org.junit.jupiter.api.Order(3)
    void shouldFindCompensatedSagaByStatus() {
        List<SagaState> compensatedSagas = sagaStateStore.findSagasByStatus(SagaStatus.COMPENSATED);
        assertNotNull(compensatedSagas);
        assertTrue(compensatedSagas.size() >= 1);
        assertTrue(compensatedSagas.stream().anyMatch(s -> s.getSagaId().equals(sagaId)));
    }

    @Test
    @DisplayName("should not find compensated saga as active")
    @org.junit.jupiter.api.Order(4)
    void shouldNotFindCompensatedSagaAsActive() {
        List<SagaState> activeSagas = sagaStateStore.findActiveSagas();
        assertTrue(activeSagas.stream().noneMatch(s -> s.getSagaId().equals(sagaId)));
    }

    @Test
    @DisplayName("should not report compensated saga as timed out")
    @org.junit.jupiter.api.Order(5)
    void shouldNotReportCompensatedSagaAsTimedOut() {
        List<SagaState> timedOut = sagaStateStore.findTimedOutSagas();
        assertTrue(timedOut.stream().noneMatch(s -> s.getSagaId().equals(sagaId)));
    }

    @Test
    @DisplayName("should propagate compensation context through events")
    @org.junit.jupiter.api.Order(6)
    void shouldPropagateCompensationContextThroughEvents() {
        // Verify compensation events carry correct saga context
        com.theyawns.ecommerce.common.events.PaymentFailedEvent paymentFailed =
                new com.theyawns.ecommerce.common.events.PaymentFailedEvent(
                        "pay-1", "order-1", "cust-1",
                        new java.math.BigDecimal("22.00"), "USD",
                        "Insufficient funds", "CREDIT_CARD"
                );
        paymentFailed.setSagaId(sagaId);
        paymentFailed.setCorrelationId(correlationId);
        paymentFailed.setSagaType(SagaCompensationConfig.ORDER_FULFILLMENT_SAGA);
        paymentFailed.setStepNumber(SagaCompensationConfig.STEP_PAYMENT_PROCESSED);

        com.hazelcast.nio.serialization.genericrecord.GenericRecord failedRecord =
                paymentFailed.toGenericRecord();
        assertEquals(sagaId, failedRecord.getString("sagaId"));
        assertEquals("Insufficient funds", failedRecord.getString("failureReason"));

        // StockReleasedEvent with compensation context
        com.theyawns.ecommerce.common.events.StockReleasedEvent stockReleased =
                new com.theyawns.ecommerce.common.events.StockReleasedEvent(
                        "prod-1", 2, "order-1", "Payment failed"
                );
        stockReleased.setSagaId(sagaId);
        stockReleased.setCorrelationId(correlationId);
        stockReleased.setIsCompensating(true);

        com.hazelcast.nio.serialization.genericrecord.GenericRecord releasedRecord =
                stockReleased.toGenericRecord();
        assertEquals(sagaId, releasedRecord.getString("sagaId"));
        assertEquals(true, releasedRecord.getBoolean("isCompensating"));
        assertEquals("Payment failed", releasedRecord.getString("reason"));

        // OrderCancelledEvent with compensation context
        com.theyawns.ecommerce.common.events.OrderCancelledEvent orderCancelled =
                new com.theyawns.ecommerce.common.events.OrderCancelledEvent(
                        "order-1", "Payment failed", "system"
                );
        orderCancelled.setSagaId(sagaId);
        orderCancelled.setCorrelationId(correlationId);
        orderCancelled.setIsCompensating(true);

        com.hazelcast.nio.serialization.genericrecord.GenericRecord cancelledRecord =
                orderCancelled.toGenericRecord();
        assertEquals(sagaId, cancelledRecord.getString("sagaId"));
        assertEquals(true, cancelledRecord.getBoolean("isCompensating"));
        assertEquals("system", cancelledRecord.getString("cancelledBy"));
    }
}
