package com.theyawns.ecommerce.order.saga;

import com.hazelcast.config.Config;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.nio.serialization.genericrecord.GenericRecord;
import com.hazelcast.nio.serialization.genericrecord.GenericRecordBuilder;
import com.hazelcast.topic.Message;
import com.theyawns.ecommerce.common.domain.Order;
import com.theyawns.ecommerce.common.domain.OrderLineItem;
import com.theyawns.ecommerce.common.events.OrderConfirmedEvent;
import com.theyawns.ecommerce.common.events.OrderCreatedEvent;
import com.theyawns.ecommerce.common.events.PaymentProcessedEvent;
import com.theyawns.ecommerce.common.events.StockReservedEvent;
import com.theyawns.ecommerce.order.service.OrderOperations;
import com.theyawns.framework.saga.HazelcastSagaStateStore;
import com.theyawns.framework.saga.SagaCompensationConfig;
import com.theyawns.framework.saga.SagaState;
import com.theyawns.framework.saga.SagaStateStore;
import com.theyawns.framework.saga.SagaStatus;
import io.micrometer.core.instrument.simple.SimpleMeterRegistry;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;
import org.junit.jupiter.api.TestMethodOrder;

import java.math.BigDecimal;
import java.time.Duration;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import java.util.concurrent.CompletableFuture;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Integration test for the Order Fulfillment Saga happy path.
 *
 * <p>Validates the complete choreographed saga flow:
 * <ol>
 *   <li>OrderCreated (step 0) - Order service creates order and starts saga</li>
 *   <li>StockReserved (step 1) - Inventory service reserves stock</li>
 *   <li>PaymentProcessed (step 2) - Payment service processes payment</li>
 *   <li>OrderConfirmed (step 3) - Order service confirms order, saga COMPLETED</li>
 * </ol>
 *
 * <p>This test simulates the saga state tracking that occurs at each service
 * boundary, verifying that the SagaStateStore correctly tracks the saga
 * through all steps to completion.
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
@DisplayName("Order Fulfillment Saga - Happy Path Integration")
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class OrderFulfillmentSagaIntegrationTest {

    private HazelcastInstance hazelcast;
    private SagaStateStore sagaStateStore;

    // Test data
    private final String sagaId = UUID.randomUUID().toString();
    private final String correlationId = UUID.randomUUID().toString();
    private final String orderId = UUID.randomUUID().toString();
    private final String customerId = UUID.randomUUID().toString();
    private final String productId = "prod-001";
    private final String paymentId = UUID.randomUUID().toString();

    @BeforeAll
    void setUp() {
        Config config = new Config();
        config.setClusterName("saga-integration-test-" + System.currentTimeMillis());
        hazelcast = Hazelcast.newHazelcastInstance(config);

        sagaStateStore = new HazelcastSagaStateStore(hazelcast, new SimpleMeterRegistry());
    }

    @AfterAll
    void tearDown() {
        if (hazelcast != null) {
            hazelcast.shutdown();
        }
    }

    @Test
    @DisplayName("should complete full Order Fulfillment saga happy path")
    @org.junit.jupiter.api.Order(1)
    void shouldCompleteFullSagaHappyPath() {
        // ===== Step 0: Order Created - Start Saga =====
        SagaState state = sagaStateStore.startSaga(
                sagaId,
                SagaCompensationConfig.ORDER_FULFILLMENT_SAGA,
                correlationId,
                4,
                Duration.ofSeconds(60)
        );

        assertNotNull(state);
        assertEquals(SagaStatus.STARTED, state.getStatus());
        assertEquals(SagaCompensationConfig.ORDER_FULFILLMENT_SAGA, state.getSagaType());
        assertEquals(correlationId, state.getCorrelationId());

        // Record step 0 completed (OrderCreated published)
        // currentStep advances to stepNumber + 1
        state = sagaStateStore.recordStepCompleted(
                sagaId,
                SagaCompensationConfig.STEP_ORDER_CREATED,
                SagaCompensationConfig.ORDER_CREATED,
                SagaCompensationConfig.ORDER_SERVICE,
                "evt-order-created"
        );

        assertEquals(SagaStatus.IN_PROGRESS, state.getStatus());
        assertEquals(1, state.getCurrentStep()); // 0 + 1

        // ===== Step 1: Stock Reserved - Inventory Service =====
        state = sagaStateStore.recordStepCompleted(
                sagaId,
                SagaCompensationConfig.STEP_STOCK_RESERVED,
                SagaCompensationConfig.STOCK_RESERVED,
                SagaCompensationConfig.INVENTORY_SERVICE,
                "evt-stock-reserved"
        );

        assertEquals(SagaStatus.IN_PROGRESS, state.getStatus());
        assertEquals(2, state.getCurrentStep()); // 1 + 1

        // ===== Step 2: Payment Processed - Payment Service =====
        state = sagaStateStore.recordStepCompleted(
                sagaId,
                SagaCompensationConfig.STEP_PAYMENT_PROCESSED,
                SagaCompensationConfig.PAYMENT_PROCESSED,
                SagaCompensationConfig.PAYMENT_SERVICE,
                "evt-payment-processed"
        );

        assertEquals(SagaStatus.IN_PROGRESS, state.getStatus());
        assertEquals(3, state.getCurrentStep()); // 2 + 1

        // ===== Step 3: Order Confirmed - Order Service =====
        // When the last step completes (stepNumber >= totalSteps - 1),
        // SagaState automatically transitions to COMPLETED
        state = sagaStateStore.recordStepCompleted(
                sagaId,
                SagaCompensationConfig.STEP_ORDER_CONFIRMED,
                SagaCompensationConfig.ORDER_CONFIRMED,
                SagaCompensationConfig.ORDER_SERVICE,
                "evt-order-confirmed"
        );

        assertEquals(SagaStatus.COMPLETED, state.getStatus());
        assertEquals(4, state.getCurrentStep()); // 3 + 1
        assertTrue(state.getStatus().isTerminal());
        assertTrue(state.getStatus().isSuccessful());
    }

    @Test
    @DisplayName("should track saga state correctly through all steps")
    @org.junit.jupiter.api.Order(2)
    void shouldTrackSagaStateCorrectly() {
        // Verify the completed saga is queryable
        Optional<SagaState> sagaOpt = sagaStateStore.getSagaState(sagaId);
        assertTrue(sagaOpt.isPresent());

        SagaState finalState = sagaOpt.get();
        assertEquals(SagaStatus.COMPLETED, finalState.getStatus());
        assertEquals(sagaId, finalState.getSagaId());
        assertEquals(SagaCompensationConfig.ORDER_FULFILLMENT_SAGA, finalState.getSagaType());
    }

    @Test
    @DisplayName("should find saga by type")
    @org.junit.jupiter.api.Order(3)
    void shouldFindSagaByType() {
        List<SagaState> sagas = sagaStateStore.findSagasByType(
                SagaCompensationConfig.ORDER_FULFILLMENT_SAGA);
        assertNotNull(sagas);
        assertTrue(sagas.size() >= 1);
        assertTrue(sagas.stream().anyMatch(s -> s.getSagaId().equals(sagaId)));
    }

    @Test
    @DisplayName("should find saga by correlation ID")
    @org.junit.jupiter.api.Order(4)
    void shouldFindSagaByCorrelationId() {
        List<SagaState> sagas = sagaStateStore.findSagasByCorrelationId(correlationId);
        assertNotNull(sagas);
        assertEquals(1, sagas.size());
        assertEquals(sagaId, sagas.get(0).getSagaId());
    }

    @Test
    @DisplayName("should find completed sagas by status")
    @org.junit.jupiter.api.Order(5)
    void shouldFindCompletedSagasByStatus() {
        List<SagaState> completedSagas = sagaStateStore.findSagasByStatus(SagaStatus.COMPLETED);
        assertNotNull(completedSagas);
        assertTrue(completedSagas.size() >= 1);
        assertTrue(completedSagas.stream().anyMatch(s -> s.getSagaId().equals(sagaId)));
    }

    @Test
    @DisplayName("should propagate saga context through events")
    @org.junit.jupiter.api.Order(6)
    void shouldPropagateSagaContextThroughEvents() {
        // Verify that events carry saga context correctly
        String testSagaId = UUID.randomUUID().toString();
        String testCorrelationId = UUID.randomUUID().toString();

        // OrderCreatedEvent with saga context
        OrderCreatedEvent orderEvent = new OrderCreatedEvent(
                orderId,
                customerId,
                Arrays.asList(new OrderLineItem(productId, "Widget", "SKU-001", 2, new BigDecimal("10.00"))),
                "123 Main St"
        );
        orderEvent.setSagaId(testSagaId);
        orderEvent.setSagaType(SagaCompensationConfig.ORDER_FULFILLMENT_SAGA);
        orderEvent.setStepNumber(SagaCompensationConfig.STEP_ORDER_CREATED);
        orderEvent.setIsCompensating(false);
        orderEvent.setCorrelationId(testCorrelationId);

        // Serialize and verify saga fields are preserved
        GenericRecord orderRecord = orderEvent.toGenericRecord();
        assertEquals(testSagaId, orderRecord.getString("sagaId"));
        assertEquals(SagaCompensationConfig.ORDER_FULFILLMENT_SAGA, orderRecord.getString("sagaType"));
        assertEquals(SagaCompensationConfig.STEP_ORDER_CREATED, orderRecord.getInt32("stepNumber"));
        assertEquals(false, orderRecord.getBoolean("isCompensating"));
        assertEquals(testCorrelationId, orderRecord.getString("correlationId"));

        // StockReservedEvent with saga context
        StockReservedEvent stockEvent = new StockReservedEvent(productId, 2, orderId);
        stockEvent.setSagaId(testSagaId);
        stockEvent.setSagaType(SagaCompensationConfig.ORDER_FULFILLMENT_SAGA);
        stockEvent.setStepNumber(SagaCompensationConfig.STEP_STOCK_RESERVED);
        stockEvent.setIsCompensating(false);
        stockEvent.setCorrelationId(testCorrelationId);
        stockEvent.setCustomerId(customerId);
        stockEvent.setAmount("22.00");
        stockEvent.setCurrency("USD");
        stockEvent.setMethod("CREDIT_CARD");

        GenericRecord stockRecord = stockEvent.toGenericRecord();
        assertEquals(testSagaId, stockRecord.getString("sagaId"));
        assertEquals(SagaCompensationConfig.STEP_STOCK_RESERVED, stockRecord.getInt32("stepNumber"));
        assertEquals(customerId, stockRecord.getString("customerId"));
        assertEquals("22.00", stockRecord.getString("amount"));
        assertEquals(orderId, stockRecord.getString("orderId"));

        // PaymentProcessedEvent with saga context
        PaymentProcessedEvent paymentEvent = new PaymentProcessedEvent(
                paymentId, orderId, customerId,
                new BigDecimal("22.00"), "USD", "txn-123", "CREDIT_CARD"
        );
        paymentEvent.setSagaId(testSagaId);
        paymentEvent.setSagaType(SagaCompensationConfig.ORDER_FULFILLMENT_SAGA);
        paymentEvent.setStepNumber(SagaCompensationConfig.STEP_PAYMENT_PROCESSED);
        paymentEvent.setCorrelationId(testCorrelationId);

        GenericRecord paymentRecord = paymentEvent.toGenericRecord();
        assertEquals(testSagaId, paymentRecord.getString("sagaId"));
        assertEquals(SagaCompensationConfig.STEP_PAYMENT_PROCESSED, paymentRecord.getInt32("stepNumber"));
        assertEquals(orderId, paymentRecord.getString("orderId"));

        // OrderConfirmedEvent with saga context
        OrderConfirmedEvent confirmEvent = new OrderConfirmedEvent(orderId, "CONF-123");
        confirmEvent.setSagaId(testSagaId);
        confirmEvent.setSagaType(SagaCompensationConfig.ORDER_FULFILLMENT_SAGA);
        confirmEvent.setStepNumber(SagaCompensationConfig.STEP_ORDER_CONFIRMED);
        confirmEvent.setCorrelationId(testCorrelationId);

        GenericRecord confirmRecord = confirmEvent.toGenericRecord();
        assertEquals(testSagaId, confirmRecord.getString("sagaId"));
        assertEquals(SagaCompensationConfig.STEP_ORDER_CONFIRMED, confirmRecord.getInt32("stepNumber"));
    }

    @Test
    @DisplayName("should have no timed-out sagas after successful completion")
    @org.junit.jupiter.api.Order(7)
    void shouldHaveNoTimedOutSagas() {
        List<SagaState> timedOut = sagaStateStore.findTimedOutSagas();
        // Our completed saga should not be timed out
        assertTrue(timedOut.stream().noneMatch(s -> s.getSagaId().equals(sagaId)));
    }
}
