package com.theyawns.framework.controller;

import java.io.Serializable;
import java.util.Objects;

/**
 * Metadata for events that are part of a distributed saga.
 * Sagas are long-running transactions that span multiple services
 * and use compensating actions for rollback.
 *
 * <p>Key fields:
 * <ul>
 *   <li><strong>sagaId</strong>: Unique identifier for the saga instance</li>
 *   <li><strong>sagaType</strong>: Type of saga (e.g., "OrderFulfillment")</li>
 *   <li><strong>stepNumber</strong>: Position in the saga sequence</li>
 *   <li><strong>isCompensating</strong>: True if this is a rollback event</li>
 * </ul>
 *
 * <p>Example usage:
 * <pre>{@code
 * SagaMetadata saga = SagaMetadata.builder()
 *     .sagaId("saga-123")
 *     .sagaType("OrderFulfillment")
 *     .stepNumber(2)
 *     .build();
 *
 * controller.handleEvent(stockReservedEvent, correlationId, saga);
 *
 * // For compensation (rollback)
 * SagaMetadata compensation = saga.toCompensating();
 * controller.handleEvent(stockReleasedEvent, correlationId, compensation);
 * }</pre>
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
public class SagaMetadata implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String sagaId;
    private final String sagaType;
    private final int stepNumber;
    private final boolean isCompensating;

    /**
     * Private constructor - use builder.
     */
    private SagaMetadata(Builder builder) {
        this.sagaId = Objects.requireNonNull(builder.sagaId, "sagaId cannot be null");
        this.sagaType = Objects.requireNonNull(builder.sagaType, "sagaType cannot be null");
        this.stepNumber = builder.stepNumber;
        this.isCompensating = builder.isCompensating;
    }

    /**
     * Creates a new SagaMetadata for a compensating (rollback) action.
     *
     * @return a new SagaMetadata with isCompensating=true
     */
    public SagaMetadata toCompensating() {
        return builder()
                .sagaId(this.sagaId)
                .sagaType(this.sagaType)
                .stepNumber(this.stepNumber)
                .compensating(true)
                .build();
    }

    /**
     * Creates a new SagaMetadata for the next step in the saga.
     *
     * @return a new SagaMetadata with incremented step number
     */
    public SagaMetadata nextStep() {
        return builder()
                .sagaId(this.sagaId)
                .sagaType(this.sagaType)
                .stepNumber(this.stepNumber + 1)
                .compensating(false)
                .build();
    }

    // Getters

    /**
     * Returns the unique saga instance identifier.
     *
     * @return the saga ID
     */
    public String getSagaId() {
        return sagaId;
    }

    /**
     * Returns the saga type (e.g., "OrderFulfillment").
     *
     * @return the saga type
     */
    public String getSagaType() {
        return sagaType;
    }

    /**
     * Returns the position in the saga sequence (0-indexed).
     *
     * @return the step number
     */
    public int getStepNumber() {
        return stepNumber;
    }

    /**
     * Returns whether this is a compensating (rollback) action.
     *
     * @return true if compensating
     */
    public boolean getIsCompensating() {
        return isCompensating;
    }

    /**
     * Alias for getIsCompensating().
     *
     * @return true if compensating
     */
    public boolean isCompensating() {
        return isCompensating;
    }

    @Override
    public String toString() {
        return "SagaMetadata{" +
                "sagaId='" + sagaId + '\'' +
                ", sagaType='" + sagaType + '\'' +
                ", stepNumber=" + stepNumber +
                ", isCompensating=" + isCompensating +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        SagaMetadata that = (SagaMetadata) o;
        return stepNumber == that.stepNumber &&
                isCompensating == that.isCompensating &&
                Objects.equals(sagaId, that.sagaId) &&
                Objects.equals(sagaType, that.sagaType);
    }

    @Override
    public int hashCode() {
        return Objects.hash(sagaId, sagaType, stepNumber, isCompensating);
    }

    // Builder

    /**
     * Creates a new builder for SagaMetadata.
     *
     * @return a new builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Builder for SagaMetadata.
     */
    public static class Builder {

        private String sagaId;
        private String sagaType;
        private int stepNumber = 0;
        private boolean isCompensating = false;

        /**
         * Sets the saga ID.
         *
         * @param sagaId the unique saga instance identifier
         * @return this builder
         */
        public Builder sagaId(String sagaId) {
            this.sagaId = sagaId;
            return this;
        }

        /**
         * Sets the saga type.
         *
         * @param sagaType the type of saga
         * @return this builder
         */
        public Builder sagaType(String sagaType) {
            this.sagaType = sagaType;
            return this;
        }

        /**
         * Sets the step number.
         *
         * @param stepNumber the position in the saga sequence
         * @return this builder
         */
        public Builder stepNumber(int stepNumber) {
            this.stepNumber = stepNumber;
            return this;
        }

        /**
         * Sets whether this is a compensating action.
         *
         * @param compensating true if this is a rollback action
         * @return this builder
         */
        public Builder compensating(boolean compensating) {
            this.isCompensating = compensating;
            return this;
        }

        /**
         * Builds the SagaMetadata.
         *
         * @return the configured SagaMetadata
         * @throws NullPointerException if required fields are missing
         */
        public SagaMetadata build() {
            return new SagaMetadata(this);
        }
    }
}
