package com.theyawns.framework.security.identity;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Auto-configuration for service identity and event authentication.
 *
 * <p>Activates only when {@code framework.security.service-identity.enabled=true}.
 * When active, creates:
 * <ul>
 *   <li>{@link ServiceIdentity} — holds service name and HMAC key</li>
 *   <li>{@link EventAuthenticator} — wraps/unwraps events with authentication</li>
 * </ul>
 *
 * <p>When not active (default), no service identity beans are created, and
 * events are published without authentication envelopes (backward compatible).
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
@Configuration
@ConditionalOnProperty(name = "framework.security.service-identity.enabled", havingValue = "true")
@EnableConfigurationProperties(ServiceIdentityProperties.class)
public class ServiceIdentityAutoConfiguration {

    private static final Logger logger = LoggerFactory.getLogger(ServiceIdentityAutoConfiguration.class);

    /**
     * Creates the {@link ServiceIdentity} bean.
     *
     * @param properties the service identity configuration properties
     * @return the configured ServiceIdentity
     */
    @Bean
    public ServiceIdentity serviceIdentity(final ServiceIdentityProperties properties) {
        logger.info("Creating ServiceIdentity for service '{}'", properties.getName());
        return new ServiceIdentity(properties.getName(), properties.getSharedSecret());
    }

    /**
     * Creates the {@link EventAuthenticator} bean.
     *
     * @param serviceIdentity the service identity for signing/verification
     * @return the configured EventAuthenticator
     */
    @Bean
    public EventAuthenticator eventAuthenticator(final ServiceIdentity serviceIdentity) {
        logger.info("Creating EventAuthenticator with service identity: {}", serviceIdentity);
        return new EventAuthenticator(serviceIdentity);
    }
}
