package com.theyawns.framework.security.identity;

import org.springframework.boot.context.properties.ConfigurationProperties;

import java.util.Objects;

/**
 * Configuration properties for service identity and inter-service event authentication.
 *
 * <p>Each microservice in the framework can be configured with a unique identity
 * and a shared secret used for HMAC-SHA256 signing of events published to ITopic.
 * This provides message-level authentication for cross-service saga events.
 *
 * <p>Example configuration:
 * <pre>{@code
 * framework:
 *   security:
 *     service-identity:
 *       enabled: true
 *       name: order-service
 *       shared-secret: my-secret-key-change-in-production
 * }</pre>
 *
 * <p>When {@code enabled} is {@code false} (default), events are published without
 * authentication envelopes, preserving backward compatibility.
 *
 * @author Generated by Claude Code
 * @since 3.0
 * @see ServiceIdentity
 * @see EventAuthenticator
 */
@ConfigurationProperties(prefix = "framework.security.service-identity")
public class ServiceIdentityProperties {

    /**
     * Whether service identity authentication is enabled.
     * Default: false (events published without signing).
     */
    private boolean enabled = false;

    /**
     * The unique name of this service instance (e.g., "order-service", "inventory-service").
     */
    private String name;

    /**
     * The shared secret key used for HMAC-SHA256 event signing.
     * All services in the cluster must share the same secret.
     */
    private String sharedSecret;

    /**
     * Creates a new ServiceIdentityProperties with default values.
     */
    public ServiceIdentityProperties() {
        // Default constructor
    }

    /**
     * Returns whether service identity authentication is enabled.
     *
     * @return true if event signing/verification is enabled
     */
    public boolean isEnabled() {
        return enabled;
    }

    /**
     * Sets whether service identity authentication is enabled.
     *
     * @param enabled true to enable event signing/verification
     */
    public void setEnabled(final boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * Returns the service name.
     *
     * @return the unique service name
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the service name.
     *
     * @param name the unique service name
     */
    public void setName(final String name) {
        this.name = name;
    }

    /**
     * Returns the shared secret key.
     *
     * @return the HMAC shared secret
     */
    public String getSharedSecret() {
        return sharedSecret;
    }

    /**
     * Sets the shared secret key.
     *
     * @param sharedSecret the HMAC shared secret
     * @throws NullPointerException if sharedSecret is null
     */
    public void setSharedSecret(final String sharedSecret) {
        this.sharedSecret = Objects.requireNonNull(sharedSecret, "sharedSecret cannot be null");
    }

    @Override
    public String toString() {
        return "ServiceIdentityProperties{" +
                "enabled=" + enabled +
                ", name='" + name + '\'' +
                ", sharedSecret='[REDACTED]'" +
                '}';
    }
}
