package com.theyawns.ecommerce.order.domain;

import com.hazelcast.nio.serialization.genericrecord.GenericRecord;
import com.hazelcast.nio.serialization.genericrecord.GenericRecordBuilder;
import com.theyawns.ecommerce.common.domain.Order;
import com.theyawns.ecommerce.common.domain.OrderLineItem;
import com.theyawns.ecommerce.common.events.OrderCancelledEvent;
import com.theyawns.ecommerce.common.events.OrderConfirmedEvent;
import com.theyawns.ecommerce.common.events.OrderCreatedEvent;
import com.theyawns.framework.view.HazelcastViewStore;
import com.theyawns.framework.view.ViewUpdater;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.time.Instant;

/**
 * ViewUpdater implementation for the Order domain.
 * Handles applying order events to the materialized view.
 *
 * <p>Supported events:
 * <ul>
 *   <li>{@link OrderCreatedEvent} - Creates new order entry</li>
 *   <li>{@link OrderConfirmedEvent} - Updates order status to CONFIRMED</li>
 *   <li>{@link OrderCancelledEvent} - Updates order status to CANCELLED</li>
 * </ul>
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
public class OrderViewUpdater extends ViewUpdater<String> {

    private static final Logger logger = LoggerFactory.getLogger(OrderViewUpdater.class);

    /**
     * Creates a new OrderViewUpdater.
     *
     * @param viewStore the view store to update
     */
    public OrderViewUpdater(HazelcastViewStore<String> viewStore) {
        super(viewStore);
    }

    @Override
    protected String extractKey(GenericRecord eventRecord) {
        return getStringField(eventRecord, "key");
    }

    @Override
    protected GenericRecord applyEvent(GenericRecord eventRecord, GenericRecord currentState) {
        String eventType = getEventType(eventRecord);

        logger.debug("Applying event type: {} to order view", eventType);

        return switch (eventType) {
            case OrderCreatedEvent.EVENT_TYPE -> applyOrderCreated(eventRecord);
            case OrderConfirmedEvent.EVENT_TYPE -> applyOrderConfirmed(eventRecord, currentState);
            case OrderCancelledEvent.EVENT_TYPE -> applyOrderCancelled(eventRecord, currentState);
            default -> {
                logger.warn("Unknown event type: {}", eventType);
                yield currentState;
            }
        };
    }

    /**
     * Applies an OrderCreatedEvent to create a new order view entry.
     *
     * @param eventRecord the event record
     * @return the new order view state
     */
    private GenericRecord applyOrderCreated(GenericRecord eventRecord) {
        Instant now = Instant.now();

        // Get line items from event
        GenericRecord[] lineItems = eventRecord.getArrayOfGenericRecord("lineItems");
        if (lineItems == null) {
            lineItems = new GenericRecord[0];
        }

        return GenericRecordBuilder.compact(Order.SCHEMA_NAME)
                .setString("orderId", getStringField(eventRecord, "key"))
                .setString("customerId", getStringField(eventRecord, "customerId"))
                .setString("customerName", getStringField(eventRecord, "customerName"))
                .setString("customerEmail", getStringField(eventRecord, "customerEmail"))
                .setArrayOfGenericRecord("lineItems", lineItems)
                .setString("subtotal", getStringField(eventRecord, "subtotal"))
                .setString("tax", getStringField(eventRecord, "tax"))
                .setString("total", getStringField(eventRecord, "total"))
                .setString("shippingAddress", getStringField(eventRecord, "shippingAddress"))
                .setString("status", Order.Status.PENDING.name())
                .setInt64("createdAt", now.toEpochMilli())
                .setInt64("updatedAt", now.toEpochMilli())
                .build();
    }

    /**
     * Applies an OrderConfirmedEvent to update order status to CONFIRMED.
     *
     * @param eventRecord the event record
     * @param currentState the current order state
     * @return the updated order view state
     */
    private GenericRecord applyOrderConfirmed(GenericRecord eventRecord, GenericRecord currentState) {
        if (currentState == null) {
            logger.error("Cannot confirm non-existent order: {}",
                    getStringField(eventRecord, "key"));
            return null;
        }

        Instant now = Instant.now();
        return GenericRecordBuilder.compact(Order.SCHEMA_NAME)
                .setString("orderId", currentState.getString("orderId"))
                .setString("customerId", currentState.getString("customerId"))
                .setString("customerName", currentState.getString("customerName"))
                .setString("customerEmail", currentState.getString("customerEmail"))
                .setArrayOfGenericRecord("lineItems", currentState.getArrayOfGenericRecord("lineItems"))
                .setString("subtotal", currentState.getString("subtotal"))
                .setString("tax", currentState.getString("tax"))
                .setString("total", currentState.getString("total"))
                .setString("shippingAddress", currentState.getString("shippingAddress"))
                .setString("status", Order.Status.CONFIRMED.name())
                .setInt64("createdAt", currentState.getInt64("createdAt"))
                .setInt64("updatedAt", now.toEpochMilli())
                .build();
    }

    /**
     * Applies an OrderCancelledEvent to update order status to CANCELLED.
     *
     * @param eventRecord the event record
     * @param currentState the current order state
     * @return the updated order view state
     */
    private GenericRecord applyOrderCancelled(GenericRecord eventRecord, GenericRecord currentState) {
        if (currentState == null) {
            logger.error("Cannot cancel non-existent order: {}",
                    getStringField(eventRecord, "key"));
            return null;
        }

        Instant now = Instant.now();
        return GenericRecordBuilder.compact(Order.SCHEMA_NAME)
                .setString("orderId", currentState.getString("orderId"))
                .setString("customerId", currentState.getString("customerId"))
                .setString("customerName", currentState.getString("customerName"))
                .setString("customerEmail", currentState.getString("customerEmail"))
                .setArrayOfGenericRecord("lineItems", currentState.getArrayOfGenericRecord("lineItems"))
                .setString("subtotal", currentState.getString("subtotal"))
                .setString("tax", currentState.getString("tax"))
                .setString("total", currentState.getString("total"))
                .setString("shippingAddress", currentState.getString("shippingAddress"))
                .setString("status", Order.Status.CANCELLED.name())
                .setInt64("createdAt", currentState.getInt64("createdAt"))
                .setInt64("updatedAt", now.toEpochMilli())
                .build();
    }
}
