package com.theyawns.ecommerce.account;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Spring Boot application entry point for the Account Service.
 *
 * <p>The Account Service manages customer accounts including:
 * <ul>
 *   <li>Customer creation</li>
 *   <li>Customer information updates</li>
 *   <li>Account status management (active, suspended, closed)</li>
 * </ul>
 *
 * <p>This service uses the event sourcing framework to:
 * <ul>
 *   <li>Publish domain events for all customer operations</li>
 *   <li>Maintain a materialized view for fast customer lookups</li>
 *   <li>Support event replay for view reconstruction</li>
 * </ul>
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
@SpringBootApplication(scanBasePackages = {
        "com.theyawns.ecommerce.account",
        "com.theyawns.framework"
})
public class AccountServiceApplication {

    /**
     * Main entry point for the Account Service.
     *
     * @param args command line arguments
     */
    public static void main(String[] args) {
        SpringApplication.run(AccountServiceApplication.class, args);
    }
}
