package com.theyawns.framework.store;

import com.hazelcast.nio.serialization.genericrecord.GenericRecord;
import com.theyawns.framework.domain.DomainObject;
import com.theyawns.framework.event.DomainEvent;

import java.time.Instant;
import java.util.List;
import java.util.Optional;

/**
 * Interface for persisting and querying domain events.
 * The EventStore is the source of truth in an event-sourced system.
 *
 * <p>Key responsibilities:
 * <ul>
 *   <li>Append events with assigned sequence numbers</li>
 *   <li>Query events by domain object key</li>
 *   <li>Query events by type or time range</li>
 *   <li>Support event replay for rebuilding views</li>
 * </ul>
 *
 * <p>Events are stored as GenericRecord for flexibility and schema evolution.
 * The PartitionedSequenceKey ensures events for the same domain object are
 * co-located on the same Hazelcast partition.
 *
 * <p>Example usage:
 * <pre>{@code
 * // Append an event
 * PartitionedSequenceKey<String> key = new PartitionedSequenceKey<>(seq, customerId);
 * eventStore.append(key, customerCreatedEvent);
 *
 * // Query events for a customer
 * List<GenericRecord> events = eventStore.getEventsByKey("cust-123");
 *
 * // Replay all events (for view rebuild)
 * eventStore.replayAll(event -> viewUpdater.apply(event));
 * }</pre>
 *
 * @param <D> The domain object type
 * @param <K> The domain object key type
 * @param <E> The event type
 * @author Generated by Claude Code
 * @since 1.0
 */
public interface EventStore<D extends DomainObject<K>, K, E extends DomainEvent<D, K>> {

    /**
     * Appends an event to the store with the given key.
     *
     * @param key the partitioned sequence key for the event
     * @param event the event to append
     */
    void append(PartitionedSequenceKey<K> key, E event);

    /**
     * Appends a GenericRecord event to the store.
     * Used when the event is already serialized.
     *
     * @param key the partitioned sequence key for the event
     * @param eventRecord the event as a GenericRecord
     */
    void append(PartitionedSequenceKey<K> key, GenericRecord eventRecord);

    /**
     * Retrieves a specific event by its key.
     *
     * @param key the partitioned sequence key
     * @return the event record if found, empty otherwise
     */
    Optional<GenericRecord> get(PartitionedSequenceKey<K> key);

    /**
     * Retrieves all events for a specific domain object, ordered by sequence.
     *
     * @param domainObjectKey the domain object's key
     * @return list of events ordered by sequence number
     */
    List<GenericRecord> getEventsByKey(K domainObjectKey);

    /**
     * Retrieves events for a domain object starting from a specific sequence.
     * Useful for incremental replay.
     *
     * @param domainObjectKey the domain object's key
     * @param fromSequence the sequence number to start from (exclusive)
     * @return list of events after the given sequence
     */
    List<GenericRecord> getEventsByKeyFromSequence(K domainObjectKey, long fromSequence);

    /**
     * Retrieves events of a specific type.
     *
     * @param eventType the event type to filter by
     * @return list of events of the specified type
     */
    List<GenericRecord> getEventsByType(String eventType);

    /**
     * Retrieves events within a time range.
     *
     * @param from the start of the time range (inclusive)
     * @param to the end of the time range (exclusive)
     * @return list of events within the time range
     */
    List<GenericRecord> getEventsByTimeRange(Instant from, Instant to);

    /**
     * Retrieves events of a specific type within a time range.
     *
     * @param eventType the event type to filter by
     * @param from the start of the time range (inclusive)
     * @param to the end of the time range (exclusive)
     * @return list of events matching the criteria
     */
    List<GenericRecord> getEventsByTypeAndTimeRange(String eventType, Instant from, Instant to);

    /**
     * Returns the total number of events in the store.
     *
     * @return the event count
     */
    long count();

    /**
     * Returns the number of events for a specific domain object.
     *
     * @param domainObjectKey the domain object's key
     * @return the event count for that domain object
     */
    long countByKey(K domainObjectKey);

    /**
     * Replays all events in sequence order to the given consumer.
     * Used for rebuilding materialized views from scratch.
     *
     * @param consumer the consumer to receive each event
     */
    void replayAll(java.util.function.Consumer<GenericRecord> consumer);

    /**
     * Replays events for a specific domain object to the given consumer.
     *
     * @param domainObjectKey the domain object's key
     * @param consumer the consumer to receive each event
     */
    void replayByKey(K domainObjectKey, java.util.function.Consumer<GenericRecord> consumer);

    /**
     * Returns the name of this event store.
     *
     * @return the store name
     */
    String getStoreName();

    /**
     * Returns the latest sequence number in the store.
     * Returns -1 if the store is empty.
     *
     * @return the latest sequence number or -1
     */
    long getLatestSequence();

    /**
     * Returns the latest sequence number for a specific domain object.
     * Returns -1 if no events exist for that key.
     *
     * @param domainObjectKey the domain object's key
     * @return the latest sequence number for that key or -1
     */
    long getLatestSequenceByKey(K domainObjectKey);
}
