package com.theyawns.framework.store;

import com.hazelcast.function.FunctionEx;
import com.hazelcast.jet.core.ProcessorSupplier;
import com.theyawns.framework.domain.DomainObject;
import com.theyawns.framework.event.DomainEvent;

import java.io.Serializable;

/**
 * Serializable function for creating HazelcastEventStore instances within Jet pipelines.
 *
 * <p>This class solves the lambda serialization problem in distributed Jet pipelines.
 * Since lambdas that capture external variables may not serialize properly across
 * cluster nodes, this concrete class implements FunctionEx to provide a serializable
 * alternative.
 *
 * @param <D> The domain object type
 * @param <K> The domain object key type
 * @param <E> The event type
 * @author Generated by Claude Code
 * @since 1.0
 */
public class EventStoreServiceCreator<D extends DomainObject<K>, K extends Comparable<K>,
        E extends DomainEvent<D, K>> implements FunctionEx<ProcessorSupplier.Context, HazelcastEventStore<D, K, E>>, Serializable {

    private static final long serialVersionUID = 1L;

    private final String domainName;

    /**
     * Creates a new EventStoreServiceCreator.
     *
     * @param domainName the domain name for the event store
     */
    public EventStoreServiceCreator(String domainName) {
        this.domainName = domainName;
    }

    @Override
    public HazelcastEventStore<D, K, E> applyEx(ProcessorSupplier.Context ctx) throws Exception {
        return new HazelcastEventStore<>(ctx.hazelcastInstance(), domainName);
    }
}
