package com.theyawns.ecommerce.payment.saga;

import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.topic.ITopic;
import com.hazelcast.topic.Message;
import com.hazelcast.topic.MessageListener;
import com.hazelcast.nio.serialization.genericrecord.GenericRecord;
import com.theyawns.ecommerce.common.events.PaymentRefundedEvent;
import com.theyawns.ecommerce.common.events.StockReservedEvent;
import com.theyawns.ecommerce.payment.service.PaymentOperations;
import com.theyawns.framework.resilience.ResilienceException;
import com.theyawns.framework.resilience.ResilientOperations;
import com.theyawns.framework.tracing.EventSpanDecorator;
import io.micrometer.tracing.Span;
import jakarta.annotation.PostConstruct;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

import java.util.concurrent.CompletableFuture;
import java.util.function.Supplier;

/**
 * Saga event listener for the Payment Service.
 *
 * <p>Listens for saga-related events that trigger payment actions:
 * <ul>
 *   <li>{@link StockReservedEvent} - Triggers payment processing (saga step 2)</li>
 *   <li>PaymentRefundRequested - Triggers payment refund (saga compensation)</li>
 * </ul>
 *
 * <p>This component connects the Payment Service to the choreographed saga
 * for order fulfillment. When stock is successfully reserved (step 1),
 * the payment service automatically processes the payment (step 2).
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
@Component
public class PaymentSagaListener {

    private static final Logger logger = LoggerFactory.getLogger(PaymentSagaListener.class);

    private final PaymentOperations paymentService;
    private final HazelcastInstance hazelcast;
    private EventSpanDecorator eventSpanDecorator;
    private ResilientOperations resilientServiceInvoker;

    /**
     * Creates a new PaymentSagaListener.
     *
     * @param paymentService the payment service
     * @param hazelcast the shared Hazelcast client for cross-service topic subscriptions
     */
    public PaymentSagaListener(PaymentOperations paymentService,
                               @Qualifier("hazelcastClient") HazelcastInstance hazelcast) {
        this.paymentService = paymentService;
        this.hazelcast = hazelcast;
    }

    /**
     * Sets the event span decorator for distributed tracing (optional).
     *
     * @param eventSpanDecorator the span decorator
     */
    @Autowired(required = false)
    public void setEventSpanDecorator(EventSpanDecorator eventSpanDecorator) {
        this.eventSpanDecorator = eventSpanDecorator;
    }

    /**
     * Sets the resilient service invoker for circuit breaker protection (optional).
     *
     * <p>When set, all saga service calls are wrapped with circuit breaker and retry
     * decoration. When not set (e.g., resilience disabled), calls delegate directly.
     *
     * @param resilientServiceInvoker the resilient service invoker
     */
    @Autowired(required = false)
    public void setResilientOperations(ResilientOperations resilientServiceInvoker) {
        this.resilientServiceInvoker = resilientServiceInvoker;
    }

    /**
     * Executes an async operation with circuit breaker protection if available.
     *
     * @param name the circuit breaker instance name
     * @param operation the async operation to execute
     * @param <T> the return type
     * @return the CompletableFuture result
     */
    private <T> CompletableFuture<T> executeWithResilience(
            final String name, final Supplier<CompletableFuture<T>> operation) {
        if (resilientServiceInvoker != null) {
            return resilientServiceInvoker.executeAsync(name, operation);
        }
        return operation.get();
    }

    /**
     * Registers listeners for saga-related topics on startup.
     */
    @PostConstruct
    public void registerListeners() {
        logger.info("Registering payment saga event listeners");

        ITopic<GenericRecord> stockReservedTopic = hazelcast.getTopic("StockReserved");
        stockReservedTopic.addMessageListener(new StockReservedListener());

        ITopic<GenericRecord> refundRequestedTopic = hazelcast.getTopic("PaymentRefundRequested");
        refundRequestedTopic.addMessageListener(new PaymentRefundRequestedListener());

        logger.info("Payment saga listeners registered successfully");
    }

    /**
     * Listener for StockReserved events.
     * When stock is reserved as part of a saga, processes the payment.
     *
     * <p>Package-private for testability.
     */
    class StockReservedListener implements MessageListener<GenericRecord> {

        @Override
        public void onMessage(Message<GenericRecord> message) {
            GenericRecord record = message.getMessageObject();

            String sagaId = record.getString("sagaId");
            if (sagaId == null || sagaId.isEmpty()) {
                logger.debug("StockReserved event without sagaId - not a saga event, ignoring");
                return;
            }

            String orderId = record.getString("orderId");
            String correlationId = record.getString("correlationId");

            logger.info("Received StockReserved saga event: orderId={}, sagaId={}", orderId, sagaId);

            Span span = null;
            if (eventSpanDecorator != null) {
                span = eventSpanDecorator.startSagaSpan("StockReserved", sagaId,
                        "OrderFulfillment", 2);
            }
            final Span currentSpan = span;

            // Extract payment details from the event context
            // In a real system, these would come from the order or a shared saga context
            String customerId = record.getString("customerId");
            String amount = record.getString("amount");
            String currency = record.getString("currency");
            String method = record.getString("method");

            try {
                executeWithResilience("payment-processing",
                        () -> paymentService.processPaymentForOrder(
                                orderId,
                                customerId != null ? customerId : "unknown",
                                amount != null ? amount : "0.00",
                                currency != null ? currency : "USD",
                                method,
                                sagaId,
                                correlationId
                        )
                ).whenComplete((payment, error) -> {
                    if (error != null) {
                        if (error instanceof ResilienceException) {
                            logger.warn("Circuit breaker open for payment-processing, " +
                                    "saga step deferred: orderId={}, sagaId={}",
                                    orderId, sagaId);
                        } else {
                            logger.error("Failed to process saga payment for order: {} (sagaId: {})",
                                    orderId, sagaId, error);
                        }
                        if (eventSpanDecorator != null) {
                            eventSpanDecorator.recordError(currentSpan, error);
                        }
                    } else {
                        logger.info("Saga payment completed: paymentId={}, status={}, orderId={}, sagaId={}",
                                payment.getPaymentId(), payment.getStatus(), orderId, sagaId);
                    }
                    if (eventSpanDecorator != null) {
                        eventSpanDecorator.endSpan(currentSpan);
                    }
                });
            } catch (Exception e) {
                logger.error("Error initiating saga payment for order: {} (sagaId: {})",
                        orderId, sagaId, e);
                if (eventSpanDecorator != null) {
                    eventSpanDecorator.recordError(currentSpan, e);
                    eventSpanDecorator.endSpan(currentSpan);
                }
            }
        }
    }

    /**
     * Listener for PaymentRefundRequested events.
     * When saga compensation requires a refund, processes the refund.
     *
     * <p>Package-private for testability.
     */
    class PaymentRefundRequestedListener implements MessageListener<GenericRecord> {

        @Override
        public void onMessage(Message<GenericRecord> message) {
            GenericRecord record = message.getMessageObject();

            String paymentId = record.getString("paymentId");
            String sagaId = record.getString("sagaId");
            String correlationId = record.getString("correlationId");
            String reason = record.getString("reason");
            final String finalReason = (reason == null || reason.isEmpty()) ? "Saga compensation" : reason;

            logger.info("Received PaymentRefundRequested: paymentId={}, sagaId={}", paymentId, sagaId);

            Span span = null;
            if (eventSpanDecorator != null) {
                span = eventSpanDecorator.startSagaSpan("PaymentRefundRequested",
                        sagaId != null ? sagaId : "unknown", "OrderFulfillment", 2);
            }
            final Span currentSpan = span;

            try {
                executeWithResilience("payment-refund",
                        () -> paymentService.refundPaymentForSaga(
                                paymentId,
                                finalReason,
                                sagaId,
                                correlationId
                        )
                ).whenComplete((payment, error) -> {
                    if (error != null) {
                        if (error instanceof ResilienceException) {
                            logger.warn("Circuit breaker open for payment-refund, " +
                                    "saga compensation deferred: paymentId={}, sagaId={}",
                                    paymentId, sagaId);
                        } else {
                            logger.error("Failed to refund payment {} for saga: {}",
                                    paymentId, sagaId, error);
                        }
                        if (eventSpanDecorator != null) {
                            eventSpanDecorator.recordError(currentSpan, error);
                        }
                    } else {
                        logger.info("Saga payment refunded: paymentId={}, sagaId={}",
                                paymentId, sagaId);
                    }
                    if (eventSpanDecorator != null) {
                        eventSpanDecorator.endSpan(currentSpan);
                    }
                });
            } catch (Exception e) {
                logger.error("Error initiating saga refund for payment: {} (sagaId: {})",
                        paymentId, sagaId, e);
                if (eventSpanDecorator != null) {
                    eventSpanDecorator.recordError(currentSpan, e);
                    eventSpanDecorator.endSpan(currentSpan);
                }
            }
        }
    }
}
