package com.theyawns.framework.view;

import com.hazelcast.nio.serialization.genericrecord.GenericRecord;

import java.util.Collection;
import java.util.Optional;
import java.util.function.Predicate;

/**
 * Interface for materialized view storage and retrieval.
 * Materialized views provide fast read access to denormalized data
 * derived from event streams.
 *
 * <p>Key characteristics:
 * <ul>
 *   <li>Views are eventually consistent with the event store</li>
 *   <li>Optimized for read performance</li>
 *   <li>Can be rebuilt from the event store at any time</li>
 *   <li>Support various query patterns</li>
 * </ul>
 *
 * @param <K> The key type for view entries
 * @author Generated by Claude Code
 * @since 1.0
 */
public interface MaterializedViewStore<K> {

    /**
     * Retrieves a view entry by its key.
     *
     * @param key the key of the entry to retrieve
     * @return an Optional containing the entry if found, empty otherwise
     */
    Optional<GenericRecord> get(K key);

    /**
     * Stores or updates a view entry.
     *
     * @param key the key for the entry
     * @param value the GenericRecord value to store
     */
    void put(K key, GenericRecord value);

    /**
     * Removes a view entry.
     *
     * @param key the key of the entry to remove
     * @return the removed value, or null if not found
     */
    GenericRecord remove(K key);

    /**
     * Checks if an entry exists for the given key.
     *
     * @param key the key to check
     * @return true if an entry exists, false otherwise
     */
    boolean containsKey(K key);

    /**
     * Returns all keys in this view.
     *
     * @return collection of all keys
     */
    Collection<K> keys();

    /**
     * Returns all values in this view.
     *
     * @return collection of all values
     */
    Collection<GenericRecord> values();

    /**
     * Queries the view using a predicate filter.
     *
     * @param predicate the filter condition
     * @return collection of matching entries
     */
    Collection<GenericRecord> query(Predicate<GenericRecord> predicate);

    /**
     * Returns the number of entries in this view.
     *
     * @return the entry count
     */
    int size();

    /**
     * Clears all entries from this view.
     * Used during view rebuilding.
     */
    void clear();

    /**
     * Returns the name of this view.
     *
     * @return the view name
     */
    String getViewName();
}