package com.theyawns.framework.view;

import java.io.Serializable;

/**
 * Factory interface for creating ViewUpdater instances within distributed pipelines.
 *
 * <p>Since ViewUpdater has a transient ViewStore field that is lost during serialization,
 * this factory allows the pipeline to create fresh ViewUpdater instances with a new
 * ViewStore obtained from the pipeline's ProcessorContext.
 *
 * <p>Example usage:
 * <pre>{@code
 * ViewUpdaterFactory<String> factory = viewStore -> new CustomerViewUpdater(viewStore);
 *
 * EventSourcingPipeline.<Customer, String, DomainEvent<Customer, String>>builder()
 *     .hazelcast(hazelcast)
 *     .domainName("Customer")
 *     .eventStore(eventStore)
 *     .viewUpdaterFactory(factory)
 *     .meterRegistry(meterRegistry)
 *     .build();
 * }</pre>
 *
 * @param <K> The key type for the view entries
 * @author Generated by Claude Code
 * @since 1.0
 */
@FunctionalInterface
public interface ViewUpdaterFactory<K> extends Serializable {

    /**
     * Creates a new ViewUpdater instance with the given ViewStore.
     *
     * @param viewStore the view store to use
     * @return a new ViewUpdater instance
     */
    ViewUpdater<K> create(HazelcastViewStore<K> viewStore);
}
