package com.theyawns.framework.view;

import com.hazelcast.function.FunctionEx;
import com.hazelcast.jet.core.ProcessorSupplier;

import java.io.Serializable;
import java.lang.reflect.Constructor;

/**
 * Serializable function for creating ViewUpdater instances within Jet pipelines.
 *
 * <p>This class solves the lambda serialization problem in distributed Jet pipelines.
 * Since lambdas and method references may not serialize properly across cluster nodes,
 * this concrete class uses reflection to create ViewUpdater instances.
 *
 * <p>The creator stores the ViewUpdater class name and uses reflection to instantiate
 * it with a fresh ViewStore on each cluster node.
 *
 * @param <K> The key type for the view entries
 * @author Generated by Claude Code
 * @since 1.0
 */
public class ViewUpdaterServiceCreator<K> implements FunctionEx<ProcessorSupplier.Context, ViewUpdater<K>>, Serializable {

    private static final long serialVersionUID = 1L;

    private final String domainName;
    private final String viewUpdaterClassName;

    /**
     * Creates a new ViewUpdaterServiceCreator.
     *
     * @param domainName the domain name (used for the ViewStore)
     * @param viewUpdaterClass the ViewUpdater class to instantiate
     */
    public ViewUpdaterServiceCreator(String domainName, Class<? extends ViewUpdater<K>> viewUpdaterClass) {
        this.domainName = domainName;
        this.viewUpdaterClassName = viewUpdaterClass.getName();
    }

    @Override
    @SuppressWarnings("unchecked")
    public ViewUpdater<K> applyEx(ProcessorSupplier.Context ctx) throws Exception {
        HazelcastViewStore<K> viewStore = new HazelcastViewStore<>(ctx.hazelcastInstance(), domainName);

        // Load the class and instantiate using reflection
        Class<?> viewUpdaterClass = Class.forName(viewUpdaterClassName);
        Constructor<?> constructor = viewUpdaterClass.getConstructor(HazelcastViewStore.class);
        return (ViewUpdater<K>) constructor.newInstance(viewStore);
    }
}
