package com.theyawns.framework.persistence.postgres.repository;

import com.theyawns.framework.persistence.postgres.entity.EventStoreEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

/**
 * JPA repository for the {@code domain_events} table.
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
@Repository
public interface EventStoreRepository
        extends JpaRepository<EventStoreEntity, EventStoreEntity.EventStoreId> {

    /**
     * Finds an event by map name and map key.
     */
    Optional<EventStoreEntity> findByMapNameAndMapKey(String mapName, String mapKey);

    /**
     * Finds all map keys for a given map name.
     */
    @Query("SELECT e.mapKey FROM EventStoreEntity e WHERE e.mapName = :mapName")
    List<String> findAllMapKeysByMapName(@Param("mapName") String mapName);

    /**
     * Deletes an event by map name and map key.
     */
    @Modifying
    @Transactional
    void deleteByMapNameAndMapKey(String mapName, String mapKey);
}
