package com.theyawns.framework.persistence.postgres.repository;

import com.theyawns.framework.persistence.postgres.entity.ViewStoreEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Modifying;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

/**
 * JPA repository for the {@code domain_views} table.
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
@Repository
public interface ViewStoreRepository
        extends JpaRepository<ViewStoreEntity, ViewStoreEntity.ViewStoreId> {

    /**
     * Finds a view entry by view name and view key.
     */
    Optional<ViewStoreEntity> findByViewNameAndViewKey(String viewName, String viewKey);

    /**
     * Finds all view keys for a given view name.
     */
    @Query("SELECT v.viewKey FROM ViewStoreEntity v WHERE v.viewName = :viewName")
    List<String> findAllViewKeysByViewName(@Param("viewName") String viewName);

    /**
     * Deletes a view entry by view name and view key.
     */
    @Modifying
    @Transactional
    void deleteByViewNameAndViewKey(String viewName, String viewKey);

    /**
     * Deletes all view entries for a given view name.
     */
    @Modifying
    @Transactional
    void deleteAllByViewName(String viewName);
}
