package com.theyawns.ecommerce.common.dto;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.util.Objects;

/**
 * Data Transfer Object for Customer information.
 * Used for REST API requests and responses.
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
public class CustomerDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    private String customerId;

    @NotBlank(message = "Email is required")
    @Email(message = "Email must be valid")
    private String email;

    @NotBlank(message = "Name is required")
    @Size(min = 2, max = 100, message = "Name must be between 2 and 100 characters")
    private String name;

    private String address;

    private String phone;

    private String status;

    /**
     * Default constructor.
     */
    public CustomerDTO() {
    }

    /**
     * Constructor with required fields.
     *
     * @param email the customer email
     * @param name the customer name
     * @param address the customer address
     */
    public CustomerDTO(String email, String name, String address) {
        this.email = email;
        this.name = name;
        this.address = address;
    }

    /**
     * Full constructor.
     *
     * @param customerId the customer ID
     * @param email the customer email
     * @param name the customer name
     * @param address the customer address
     * @param phone the customer phone
     * @param status the customer status
     */
    public CustomerDTO(String customerId, String email, String name,
                       String address, String phone, String status) {
        this.customerId = customerId;
        this.email = email;
        this.name = name;
        this.address = address;
        this.phone = phone;
        this.status = status;
    }

    // Getters and Setters

    public String getCustomerId() {
        return customerId;
    }

    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        CustomerDTO that = (CustomerDTO) o;
        return Objects.equals(customerId, that.customerId) &&
                Objects.equals(email, that.email);
    }

    @Override
    public int hashCode() {
        return Objects.hash(customerId, email);
    }

    @Override
    public String toString() {
        return "CustomerDTO{" +
                "customerId='" + customerId + '\'' +
                ", email='" + email + '\'' +
                ", name='" + name + '\'' +
                ", status='" + status + '\'' +
                '}';
    }
}
