package com.theyawns.ecommerce.common.dto;

import java.util.Collections;
import java.util.Map;

/**
 * Standard HTTP response for orchestrated saga step endpoints.
 *
 * <p>Used by inventory-service and payment-service orchestrated endpoints
 * to return a uniform response to the saga orchestrator in order-service.
 *
 * @param success whether the step succeeded
 * @param data additional data from the step (e.g., paymentId, reservationId)
 * @param errorMessage error message if the step failed
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
public record OrchestratedStepResponse(
        boolean success,
        Map<String, Object> data,
        String errorMessage
) {

    /**
     * Creates a successful response with data.
     *
     * @param data the response data
     * @return a success response
     */
    public static OrchestratedStepResponse success(final Map<String, Object> data) {
        return new OrchestratedStepResponse(true, data != null ? data : Collections.emptyMap(), null);
    }

    /**
     * Creates a failure response with an error message.
     *
     * @param errorMessage the error message
     * @return a failure response
     */
    public static OrchestratedStepResponse failure(final String errorMessage) {
        return new OrchestratedStepResponse(false, Collections.emptyMap(), errorMessage);
    }
}
