package com.theyawns.ecommerce.common.dto;

import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Objects;

/**
 * Data Transfer Object for Product information.
 * Used for REST API requests and responses.
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
public class ProductDTO implements Serializable {

    private static final long serialVersionUID = 1L;

    private String productId;

    @NotBlank(message = "SKU is required")
    @Size(max = 50, message = "SKU must be at most 50 characters")
    private String sku;

    @NotBlank(message = "Name is required")
    @Size(min = 2, max = 200, message = "Name must be between 2 and 200 characters")
    private String name;

    @Size(max = 1000, message = "Description must be at most 1000 characters")
    private String description;

    @DecimalMin(value = "0.01", message = "Price must be at least 0.01")
    private BigDecimal price;

    @Min(value = 0, message = "Quantity cannot be negative")
    private int quantityOnHand;

    @Min(value = 0, message = "Reserved quantity cannot be negative")
    private int quantityReserved;

    private String category;

    private String status;

    /**
     * Default constructor.
     */
    public ProductDTO() {
    }

    /**
     * Constructor with required fields.
     *
     * @param sku the product SKU
     * @param name the product name
     * @param price the product price
     * @param quantityOnHand the initial quantity
     */
    public ProductDTO(String sku, String name, BigDecimal price, int quantityOnHand) {
        this.sku = sku;
        this.name = name;
        this.price = price;
        this.quantityOnHand = quantityOnHand;
    }

    /**
     * Full constructor.
     *
     * @param productId the product ID
     * @param sku the product SKU
     * @param name the product name
     * @param description the product description
     * @param price the product price
     * @param quantityOnHand the quantity on hand
     * @param quantityReserved the reserved quantity
     * @param category the product category
     * @param status the product status
     */
    public ProductDTO(String productId, String sku, String name, String description,
                      BigDecimal price, int quantityOnHand, int quantityReserved,
                      String category, String status) {
        this.productId = productId;
        this.sku = sku;
        this.name = name;
        this.description = description;
        this.price = price;
        this.quantityOnHand = quantityOnHand;
        this.quantityReserved = quantityReserved;
        this.category = category;
        this.status = status;
    }

    /**
     * Returns the available quantity (on hand minus reserved).
     *
     * @return available quantity
     */
    public int getAvailableQuantity() {
        return quantityOnHand - quantityReserved;
    }

    // Getters and Setters

    public String getProductId() {
        return productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public String getSku() {
        return sku;
    }

    public void setSku(String sku) {
        this.sku = sku;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public int getQuantityOnHand() {
        return quantityOnHand;
    }

    public void setQuantityOnHand(int quantityOnHand) {
        this.quantityOnHand = quantityOnHand;
    }

    public int getQuantityReserved() {
        return quantityReserved;
    }

    public void setQuantityReserved(int quantityReserved) {
        this.quantityReserved = quantityReserved;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ProductDTO that = (ProductDTO) o;
        return Objects.equals(productId, that.productId) &&
                Objects.equals(sku, that.sku);
    }

    @Override
    public int hashCode() {
        return Objects.hash(productId, sku);
    }

    @Override
    public String toString() {
        return "ProductDTO{" +
                "productId='" + productId + '\'' +
                ", sku='" + sku + '\'' +
                ", name='" + name + '\'' +
                ", price=" + price +
                ", availableQuantity=" + getAvailableQuantity() +
                ", status='" + status + '\'' +
                '}';
    }
}
