package com.theyawns.framework.persistence.postgres.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.OffsetDateTime;

/**
 * JPA entity for the {@code domain_dead_letters} table.
 *
 * <p>Uses {@code dlq_entry_id} as the primary key.
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
@Entity
@Table(name = "domain_dead_letters")
public class DeadLetterEntity {

    @Id
    @Column(name = "dlq_entry_id", length = 255, nullable = false)
    private String dlqEntryId;

    @Column(name = "original_event_id", length = 255, nullable = false)
    private String originalEventId;

    @Column(name = "event_type", length = 255, nullable = false)
    private String eventType;

    @Column(name = "topic_name", length = 255, nullable = false)
    private String topicName;

    @Column(name = "event_data", columnDefinition = "jsonb")
    @JdbcTypeCode(SqlTypes.JSON)
    private String eventData;

    @Column(name = "failure_reason", columnDefinition = "TEXT")
    private String failureReason;

    @Column(name = "failure_timestamp_millis", nullable = false)
    private long failureTimestampMillis;

    @Column(name = "source_service", length = 255)
    private String sourceService;

    @Column(name = "saga_id", length = 255)
    private String sagaId;

    @Column(name = "correlation_id", length = 255)
    private String correlationId;

    @Column(name = "replay_count", nullable = false)
    private int replayCount;

    @Column(name = "status", length = 20, nullable = false)
    private String status;

    @Column(name = "created_at")
    private OffsetDateTime createdAt;

    @Column(name = "updated_at")
    private OffsetDateTime updatedAt;

    /**
     * Default constructor for JPA.
     */
    public DeadLetterEntity() {
    }

    /**
     * Full constructor.
     */
    public DeadLetterEntity(String dlqEntryId, String originalEventId, String eventType,
                            String topicName, String eventData, String failureReason,
                            long failureTimestampMillis, String sourceService, String sagaId,
                            String correlationId, int replayCount, String status) {
        this.dlqEntryId = dlqEntryId;
        this.originalEventId = originalEventId;
        this.eventType = eventType;
        this.topicName = topicName;
        this.eventData = eventData;
        this.failureReason = failureReason;
        this.failureTimestampMillis = failureTimestampMillis;
        this.sourceService = sourceService;
        this.sagaId = sagaId;
        this.correlationId = correlationId;
        this.replayCount = replayCount;
        this.status = status;
    }

    public String getDlqEntryId() { return dlqEntryId; }
    public void setDlqEntryId(String dlqEntryId) { this.dlqEntryId = dlqEntryId; }

    public String getOriginalEventId() { return originalEventId; }
    public void setOriginalEventId(String originalEventId) { this.originalEventId = originalEventId; }

    public String getEventType() { return eventType; }
    public void setEventType(String eventType) { this.eventType = eventType; }

    public String getTopicName() { return topicName; }
    public void setTopicName(String topicName) { this.topicName = topicName; }

    public String getEventData() { return eventData; }
    public void setEventData(String eventData) { this.eventData = eventData; }

    public String getFailureReason() { return failureReason; }
    public void setFailureReason(String failureReason) { this.failureReason = failureReason; }

    public long getFailureTimestampMillis() { return failureTimestampMillis; }
    public void setFailureTimestampMillis(long failureTimestampMillis) { this.failureTimestampMillis = failureTimestampMillis; }

    public String getSourceService() { return sourceService; }
    public void setSourceService(String sourceService) { this.sourceService = sourceService; }

    public String getSagaId() { return sagaId; }
    public void setSagaId(String sagaId) { this.sagaId = sagaId; }

    public String getCorrelationId() { return correlationId; }
    public void setCorrelationId(String correlationId) { this.correlationId = correlationId; }

    public int getReplayCount() { return replayCount; }
    public void setReplayCount(int replayCount) { this.replayCount = replayCount; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }

    public OffsetDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(OffsetDateTime createdAt) { this.createdAt = createdAt; }

    public OffsetDateTime getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(OffsetDateTime updatedAt) { this.updatedAt = updatedAt; }
}
