package com.theyawns.framework.persistence.postgres.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

import java.time.OffsetDateTime;

/**
 * JPA entity for the {@code domain_outbox} table.
 *
 * <p>Uses {@code event_id} as the primary key (single column, not composite).
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
@Entity
@Table(name = "domain_outbox")
public class OutboxEntity {

    @Id
    @Column(name = "event_id", length = 255, nullable = false)
    private String eventId;

    @Column(name = "event_type", length = 255, nullable = false)
    private String eventType;

    @Column(name = "event_data", nullable = false, columnDefinition = "jsonb")
    @JdbcTypeCode(SqlTypes.JSON)
    private String eventData;

    @Column(name = "retry_count", nullable = false)
    private int retryCount;

    @Column(name = "status", length = 20, nullable = false)
    private String status;

    @Column(name = "created_at_millis", nullable = false)
    private long createdAtMillis;

    @Column(name = "last_attempt_at_millis")
    private Long lastAttemptAtMillis;

    @Column(name = "failure_reason", columnDefinition = "TEXT")
    private String failureReason;

    @Column(name = "claimant_id", length = 255)
    private String claimantId;

    @Column(name = "claimed_at_millis")
    private Long claimedAtMillis;

    @Column(name = "created_at")
    private OffsetDateTime createdAt;

    @Column(name = "updated_at")
    private OffsetDateTime updatedAt;

    /**
     * Default constructor for JPA.
     */
    public OutboxEntity() {
    }

    /**
     * Full constructor.
     */
    public OutboxEntity(String eventId, String eventType, String eventData,
                        int retryCount, String status, long createdAtMillis,
                        Long lastAttemptAtMillis, String failureReason,
                        String claimantId, Long claimedAtMillis) {
        this.eventId = eventId;
        this.eventType = eventType;
        this.eventData = eventData;
        this.retryCount = retryCount;
        this.status = status;
        this.createdAtMillis = createdAtMillis;
        this.lastAttemptAtMillis = lastAttemptAtMillis;
        this.failureReason = failureReason;
        this.claimantId = claimantId;
        this.claimedAtMillis = claimedAtMillis;
    }

    public String getEventId() { return eventId; }
    public void setEventId(String eventId) { this.eventId = eventId; }

    public String getEventType() { return eventType; }
    public void setEventType(String eventType) { this.eventType = eventType; }

    public String getEventData() { return eventData; }
    public void setEventData(String eventData) { this.eventData = eventData; }

    public int getRetryCount() { return retryCount; }
    public void setRetryCount(int retryCount) { this.retryCount = retryCount; }

    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }

    public long getCreatedAtMillis() { return createdAtMillis; }
    public void setCreatedAtMillis(long createdAtMillis) { this.createdAtMillis = createdAtMillis; }

    public Long getLastAttemptAtMillis() { return lastAttemptAtMillis; }
    public void setLastAttemptAtMillis(Long lastAttemptAtMillis) { this.lastAttemptAtMillis = lastAttemptAtMillis; }

    public String getFailureReason() { return failureReason; }
    public void setFailureReason(String failureReason) { this.failureReason = failureReason; }

    public String getClaimantId() { return claimantId; }
    public void setClaimantId(String claimantId) { this.claimantId = claimantId; }

    public Long getClaimedAtMillis() { return claimedAtMillis; }
    public void setClaimedAtMillis(Long claimedAtMillis) { this.claimedAtMillis = claimedAtMillis; }

    public OffsetDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(OffsetDateTime createdAt) { this.createdAt = createdAt; }

    public OffsetDateTime getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(OffsetDateTime updatedAt) { this.updatedAt = updatedAt; }
}
