package com.theyawns.ecommerce.mcp.client;

import java.util.List;
import java.util.Map;

/**
 * Interface for REST client operations against eCommerce microservices.
 *
 * <p>Extracted from {@link ServiceClient} to support mocking in tests on Java 25+,
 * where Mockito's inline mock maker cannot mock concrete classes.
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
public interface ServiceClientOperations {

    /**
     * Retrieves a single entity by ID.
     *
     * @param viewName the view name (customer, product, order, payment)
     * @param id the entity ID
     * @return the entity as a map, or an error map if not found
     */
    Map<String, Object> getEntity(String viewName, String id);

    /**
     * Lists entities from a service, up to the specified limit.
     *
     * @param viewName the view name
     * @param limit the maximum number of entities to return
     * @return list of entities as maps
     */
    List<Map<String, Object>> listEntities(String viewName, int limit);

    /**
     * Creates a new entity by POSTing to the service.
     *
     * @param viewName the view name
     * @param payload the entity data as a map
     * @return the created entity as a map
     */
    Map<String, Object> createEntity(String viewName, Map<String, Object> payload);

    /**
     * Performs an action on an entity.
     *
     * @param viewName the view name
     * @param id the entity ID
     * @param action the action path
     * @param payload the action payload
     * @param usePatch true to use PATCH, false to use POST
     * @return the result as a map
     */
    Map<String, Object> performAction(String viewName, String id, String action,
                                       Map<String, Object> payload, boolean usePatch);

    /**
     * Retrieves event history for a domain entity.
     *
     * @param viewName the view name
     * @param id the entity ID
     * @param limit the maximum number of events to return
     * @return list of events as maps
     */
    List<Map<String, Object>> getEventHistory(String viewName, String id, int limit);
}
