package com.theyawns.ecommerce.mcp.client;

import java.util.List;
import java.util.Map;

/**
 * Interface for REST client operations against eCommerce microservices.
 *
 * <p>Extracted from {@link ServiceClient} to support mocking in tests on Java 25+,
 * where Mockito's inline mock maker cannot mock concrete classes.
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
public interface ServiceClientOperations {

    /**
     * Retrieves a single entity by ID.
     *
     * @param viewName the view name (customer, product, order, payment)
     * @param id the entity ID
     * @return the entity as a map, or an error map if not found
     */
    Map<String, Object> getEntity(String viewName, String id);

    /**
     * Lists entities from a service, up to the specified limit.
     *
     * @param viewName the view name
     * @param limit the maximum number of entities to return
     * @return list of entities as maps
     */
    List<Map<String, Object>> listEntities(String viewName, int limit);

    /**
     * Creates a new entity by POSTing to the service.
     *
     * @param viewName the view name
     * @param payload the entity data as a map
     * @return the created entity as a map
     */
    Map<String, Object> createEntity(String viewName, Map<String, Object> payload);

    /**
     * Performs an action on an entity.
     *
     * @param viewName the view name
     * @param id the entity ID
     * @param action the action path
     * @param payload the action payload
     * @param usePatch true to use PATCH, false to use POST
     * @return the result as a map
     */
    Map<String, Object> performAction(String viewName, String id, String action,
                                       Map<String, Object> payload, boolean usePatch);

    /**
     * Retrieves event history for a domain entity.
     *
     * @param viewName the view name
     * @param id the entity ID
     * @param limit the maximum number of events to return
     * @return list of events as maps
     */
    List<Map<String, Object>> getEventHistory(String viewName, String id, int limit);

    /**
     * Retrieves saga state by ID from the order service.
     *
     * @param sagaId the saga identifier
     * @return the saga state as a map
     */
    Map<String, Object> getSaga(String sagaId);

    /**
     * Lists sagas from the order service, optionally filtered by status and type.
     *
     * @param status optional status filter (e.g., "COMPLETED", "FAILED")
     * @param type optional saga type filter (e.g., "OrderFulfillment", "OrderFulfillmentOrchestrated")
     * @param limit the maximum number of sagas to return
     * @return list of saga states as maps
     */
    List<Map<String, Object>> listSagas(String status, String type, int limit);

    /**
     * Lists sagas from the order service, optionally filtered by status.
     *
     * @param status optional status filter (e.g., "COMPLETED", "FAILED")
     * @param limit the maximum number of sagas to return
     * @return list of saga states as maps
     */
    default List<Map<String, Object>> listSagas(String status, int limit) {
        return listSagas(status, null, limit);
    }

    /**
     * Creates an order using the orchestrated saga pattern.
     *
     * @param payload the order data as a map
     * @return the created order as a map
     */
    Map<String, Object> createOrchestratedOrder(Map<String, Object> payload);

    /**
     * Retrieves an aggregated metrics summary from the order service.
     *
     * @return the metrics summary as a map
     */
    Map<String, Object> getMetricsSummary();

    // ========================================================================
    // DLQ operations
    // ========================================================================

    /**
     * Lists DLQ entries from a service.
     *
     * @param serviceName optional service name to target (null defaults to order-service)
     * @param limit the maximum number of entries to return
     * @return list of DLQ entries as maps
     */
    List<Map<String, Object>> listDlqEntries(String serviceName, int limit);

    /**
     * Gets a single DLQ entry by ID from a service.
     *
     * @param serviceName optional service name to target (null defaults to order-service)
     * @param id the DLQ entry ID
     * @return the DLQ entry as a map
     */
    Map<String, Object> getDlqEntry(String serviceName, String id);

    /**
     * Gets the count of pending DLQ entries from a service.
     *
     * @param serviceName optional service name to target (null defaults to order-service)
     * @return the count as a map
     */
    Map<String, Object> getDlqCount(String serviceName);

    /**
     * Replays a DLQ entry by ID.
     *
     * @param serviceName optional service name to target (null defaults to order-service)
     * @param id the DLQ entry ID
     * @return the replay result as a map
     */
    Map<String, Object> replayDlqEntry(String serviceName, String id);

    /**
     * Discards a DLQ entry by ID.
     *
     * @param serviceName optional service name to target (null defaults to order-service)
     * @param id the DLQ entry ID
     * @return the discard result as a map
     */
    Map<String, Object> discardDlqEntry(String serviceName, String id);

    // ========================================================================
    // Fault injection operations
    // ========================================================================

    /**
     * Enables fault injection on a service.
     *
     * @param serviceName the service name (e.g., "inventory")
     * @param message the failure message to inject
     * @return the fault injection state as a map
     */
    Map<String, Object> enableFaultInjection(String serviceName, String message);

    /**
     * Disables fault injection on a service.
     *
     * @param serviceName the service name
     * @return the fault injection state as a map
     */
    Map<String, Object> disableFaultInjection(String serviceName);

    /**
     * Gets the current fault injection state from a service.
     *
     * @param serviceName the service name
     * @return the fault injection state as a map
     */
    Map<String, Object> getFaultInjectionState(String serviceName);
}
