package com.theyawns.framework.idempotency;

import com.hazelcast.core.HazelcastInstance;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.simple.SimpleMeterRegistry;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.springframework.boot.autoconfigure.AutoConfigurations;
import org.springframework.boot.test.context.runner.ApplicationContextRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;

/**
 * Tests for {@link IdempotencyAutoConfiguration}.
 *
 * <p>Uses {@link ApplicationContextRunner} pattern to test auto-configuration
 * behavior without starting a full Spring context.
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
@DisplayName("IdempotencyAutoConfiguration - Auto-configuration behavior")
class IdempotencyAutoConfigurationTest {

    private final ApplicationContextRunner contextRunner = new ApplicationContextRunner()
            .withConfiguration(AutoConfigurations.of(IdempotencyAutoConfiguration.class))
            .withPropertyValues(
                    "framework.edition.license.env-var=NONEXISTENT_TEST_LICENSE_VAR_12345");

    @Nested
    @DisplayName("Default configuration")
    class DefaultConfiguration {

        @Test
        @DisplayName("should create IdempotencyGuard bean by default when HazelcastInstance exists")
        void shouldCreateBeansByDefault() {
            contextRunner
                    .withUserConfiguration(HazelcastAndMeterConfig.class)
                    .run(context -> {
                        assertThat(context).hasSingleBean(IdempotencyGuard.class);
                        assertThat(context).hasSingleBean(IdempotencyProperties.class);
                    });
        }

        @Test
        @DisplayName("should create beans when enabled property is not set (matchIfMissing)")
        void shouldCreateBeansWhenPropertyNotSet() {
            contextRunner
                    .withUserConfiguration(HazelcastAndMeterConfig.class)
                    .run(context -> {
                        assertThat(context).hasSingleBean(IdempotencyGuard.class);
                    });
        }
    }

    @Nested
    @DisplayName("Disabled configuration")
    class DisabledConfiguration {

        @Test
        @DisplayName("should not create beans when framework.idempotency.enabled is false")
        void shouldNotCreateBeansWhenDisabled() {
            contextRunner
                    .withUserConfiguration(HazelcastAndMeterConfig.class)
                    .withPropertyValues("framework.idempotency.enabled=false")
                    .run(context -> {
                        assertThat(context).doesNotHaveBean(IdempotencyGuard.class);
                    });
        }
    }

    @Nested
    @DisplayName("Missing dependencies")
    class MissingDependencies {

        @Test
        @DisplayName("should not create beans when HazelcastInstance is absent")
        void shouldNotCreateBeansWhenHazelcastAbsent() {
            contextRunner
                    .withUserConfiguration(MeterRegistryOnlyConfig.class)
                    .run(context -> {
                        assertThat(context).doesNotHaveBean(IdempotencyGuard.class);
                    });
        }
    }

    @Nested
    @DisplayName("Property binding")
    class PropertyBinding {

        @Test
        @DisplayName("should bind idempotency properties from configuration")
        void shouldBindIdempotencyProperties() {
            contextRunner
                    .withUserConfiguration(HazelcastAndMeterConfig.class)
                    .withPropertyValues(
                            "framework.idempotency.map-name=custom_PROCESSED",
                            "framework.idempotency.ttl=30m"
                    )
                    .run(context -> {
                        IdempotencyProperties props =
                                context.getBean(IdempotencyProperties.class);
                        assertThat(props.getMapName()).isEqualTo("custom_PROCESSED");
                        assertThat(props.getTtl().toMinutes()).isEqualTo(30);
                    });
        }
    }

    // ========== Test Configuration Classes ==========

    @Configuration
    static class HazelcastAndMeterConfig {

        @Bean
        HazelcastInstance hazelcastInstance() {
            return mock(HazelcastInstance.class);
        }

        @Bean
        MeterRegistry meterRegistry() {
            return new SimpleMeterRegistry();
        }
    }

    @Configuration
    static class MeterRegistryOnlyConfig {

        @Bean
        MeterRegistry meterRegistry() {
            return new SimpleMeterRegistry();
        }
    }
}
