package com.theyawns.framework.idempotency;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.time.Duration;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Tests for {@link IdempotencyProperties}.
 *
 * <p>Validates default values and property setters.
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
@DisplayName("IdempotencyProperties - Idempotency guard configuration properties")
class IdempotencyPropertiesTest {

    private IdempotencyProperties properties;

    @BeforeEach
    void setUp() {
        properties = new IdempotencyProperties();
    }

    @Nested
    @DisplayName("Default values")
    class DefaultValues {

        @Test
        @DisplayName("should default enabled to true")
        void shouldDefaultEnabledToTrue() {
            // Assert
            assertThat(properties.isEnabled()).isTrue();
        }

        @Test
        @DisplayName("should default mapName to framework_PROCESSED_EVENTS")
        void shouldDefaultMapNameToFrameworkProcessedEvents() {
            // Assert
            assertThat(properties.getMapName()).isEqualTo("framework_PROCESSED_EVENTS");
        }

        @Test
        @DisplayName("should default ttl to 1 hour")
        void shouldDefaultTtlToOneHour() {
            // Assert
            assertThat(properties.getTtl()).isEqualTo(Duration.ofHours(1));
        }
    }

    @Nested
    @DisplayName("Property setters")
    class PropertySetters {

        @Test
        @DisplayName("should update enabled property")
        void shouldUpdateEnabledProperty() {
            // Act
            properties.setEnabled(false);

            // Assert
            assertThat(properties.isEnabled()).isFalse();
        }

        @Test
        @DisplayName("should update mapName property")
        void shouldUpdateMapNameProperty() {
            // Act
            properties.setMapName("custom_PROCESSED");

            // Assert
            assertThat(properties.getMapName()).isEqualTo("custom_PROCESSED");
        }

        @Test
        @DisplayName("should update ttl property")
        void shouldUpdateTtlProperty() {
            // Act
            properties.setTtl(Duration.ofMinutes(30));

            // Assert
            assertThat(properties.getTtl()).isEqualTo(Duration.ofMinutes(30));
        }
    }

    @Nested
    @DisplayName("toString")
    class ToStringTests {

        @Test
        @DisplayName("should include all properties in toString")
        void shouldIncludeAllPropertiesInToString() {
            // Act
            String result = properties.toString();

            // Assert
            assertThat(result).contains("IdempotencyProperties");
            assertThat(result).contains("enabled=true");
            assertThat(result).contains("framework_PROCESSED_EVENTS");
            assertThat(result).contains("PT1H");
        }
    }
}
