package com.theyawns.ecommerce.order.service;

import com.theyawns.ecommerce.common.domain.Order;
import com.theyawns.ecommerce.common.dto.OrderDTO;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;

/**
 * Service interface for order operations.
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
public interface OrderOperations {

    /**
     * Creates a new order.
     *
     * @param dto the order data
     * @return a future that completes with the created order
     */
    CompletableFuture<Order> createOrder(OrderDTO dto);

    /**
     * Retrieves an order by ID.
     *
     * @param orderId the order ID
     * @return the order if found
     */
    Optional<Order> getOrder(String orderId);

    /**
     * Retrieves all orders for a customer.
     *
     * @param customerId the customer ID
     * @return list of orders for the customer
     */
    List<Order> getOrdersByCustomer(String customerId);

    /**
     * Confirms an order (stock reserved, payment verified).
     *
     * @param orderId the order ID
     * @return a future that completes with the confirmed order
     */
    CompletableFuture<Order> confirmOrder(String orderId);

    /**
     * Confirms an order as part of a saga.
     *
     * @param orderId the order ID
     * @param sagaId the saga instance ID
     * @param correlationId the correlation ID
     * @return a future that completes with the confirmed order
     */
    CompletableFuture<Order> confirmOrderForSaga(String orderId, String sagaId, String correlationId);

    /**
     * Cancels an order.
     *
     * @param orderId the order ID
     * @param reason the cancellation reason
     * @param cancelledBy who cancelled (customer, system, admin)
     * @return a future that completes with the cancelled order
     */
    CompletableFuture<Order> cancelOrder(String orderId, String reason, String cancelledBy);

    /**
     * Cancels an order as part of saga compensation.
     *
     * <p>Records the compensation step and marks the saga as COMPENSATED.
     *
     * @param orderId the order ID
     * @param reason the cancellation reason
     * @param sagaId the saga instance ID
     * @param correlationId the correlation ID
     * @return a future that completes with the cancelled order
     */
    CompletableFuture<Order> cancelOrderForSaga(String orderId, String reason,
                                                  String sagaId, String correlationId);

    /**
     * Checks if an order exists.
     *
     * @param orderId the order ID
     * @return true if the order exists
     */
    boolean orderExists(String orderId);

    /**
     * Lists all orders, up to the specified limit.
     *
     * @param limit the maximum number of orders to return
     * @return list of orders
     */
    List<Order> listAll(int limit);

    /**
     * Retrieves the event history for an order.
     *
     * @param orderId the order ID
     * @param limit the maximum number of events to return
     * @return list of events as maps
     */
    List<Map<String, Object>> getEventHistory(String orderId, int limit);
}
