package com.theyawns.framework.config;

import com.hazelcast.config.Config;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Tests for {@link EmbeddedClusteringConfigurer}.
 *
 * <p>Uses real {@link Config} instances (not mocks) since Hazelcast concrete
 * classes cannot be mocked on Java 25.
 *
 * @author Generated by Claude Code
 * @since 3.1
 */
@DisplayName("EmbeddedClusteringConfigurer - Embedded discovery configuration")
class EmbeddedClusteringConfigurerTest {

    private Config config;

    @BeforeEach
    void setUp() {
        config = new Config();
    }

    @Nested
    @DisplayName("Standalone mode (clustering disabled)")
    class StandaloneMode {

        @Test
        @DisplayName("should disable multicast discovery")
        void shouldDisableMulticastDiscovery() {
            EmbeddedClusteringConfigurer.configure(config, false, "dns", null, 5801);

            assertThat(config.getNetworkConfig().getJoin().getMulticastConfig().isEnabled()).isFalse();
        }

        @Test
        @DisplayName("should disable auto-detection discovery")
        void shouldDisableAutoDetectionDiscovery() {
            EmbeddedClusteringConfigurer.configure(config, false, "dns", null, 5801);

            assertThat(config.getNetworkConfig().getJoin().getAutoDetectionConfig().isEnabled()).isFalse();
        }

        @Test
        @DisplayName("should not enable Kubernetes discovery")
        void shouldNotEnableKubernetesDiscovery() {
            EmbeddedClusteringConfigurer.configure(config, false, "dns", null, 5801);

            assertThat(config.getNetworkConfig().getJoin().getKubernetesConfig().isEnabled()).isFalse();
        }

        @Test
        @DisplayName("should set the specified port")
        void shouldSetSpecifiedPort() {
            EmbeddedClusteringConfigurer.configure(config, false, "dns", null, 5801);

            assertThat(config.getNetworkConfig().getPort()).isEqualTo(5801);
        }

        @Test
        @DisplayName("should enable port auto-increment")
        void shouldEnablePortAutoIncrement() {
            EmbeddedClusteringConfigurer.configure(config, false, "dns", null, 5801);

            assertThat(config.getNetworkConfig().isPortAutoIncrement()).isTrue();
        }

        @Test
        @DisplayName("should not enable Kubernetes when enabled is true but serviceDns is null")
        void shouldNotEnableKubernetesWhenServiceDnsIsNull() {
            EmbeddedClusteringConfigurer.configure(config, true, "dns", null, 5801);

            assertThat(config.getNetworkConfig().getJoin().getKubernetesConfig().isEnabled()).isFalse();
        }

        @Test
        @DisplayName("should not enable Kubernetes when enabled is true but serviceDns is blank")
        void shouldNotEnableKubernetesWhenServiceDnsIsBlank() {
            EmbeddedClusteringConfigurer.configure(config, true, "dns", "  ", 5801);

            assertThat(config.getNetworkConfig().getJoin().getKubernetesConfig().isEnabled()).isFalse();
        }

        @Test
        @DisplayName("should not enable Kubernetes when discoveryMode is not dns")
        void shouldNotEnableKubernetesWhenDiscoveryModeIsNotDns() {
            EmbeddedClusteringConfigurer.configure(config, true, "tcp-ip",
                    "order-service-hz-embedded.default.svc.cluster.local", 5801);

            assertThat(config.getNetworkConfig().getJoin().getKubernetesConfig().isEnabled()).isFalse();
        }
    }

    @Nested
    @DisplayName("Kubernetes DNS clustering mode")
    class KubernetesDnsMode {

        @Test
        @DisplayName("should enable Kubernetes discovery when all conditions are met")
        void shouldEnableKubernetesDiscovery() {
            EmbeddedClusteringConfigurer.configure(config, true, "dns",
                    "order-service-hz-embedded.default.svc.cluster.local", 5801);

            assertThat(config.getNetworkConfig().getJoin().getKubernetesConfig().isEnabled()).isTrue();
        }

        @Test
        @DisplayName("should set service-dns property on Kubernetes config")
        void shouldSetServiceDnsProperty() {
            final String dns = "order-service-hz-embedded.default.svc.cluster.local";
            EmbeddedClusteringConfigurer.configure(config, true, "dns", dns, 5801);

            assertThat(config.getNetworkConfig().getJoin().getKubernetesConfig()
                    .getProperty("service-dns")).isEqualTo(dns);
        }

        @Test
        @DisplayName("should still disable multicast when Kubernetes is enabled")
        void shouldStillDisableMulticastWhenKubernetesEnabled() {
            EmbeddedClusteringConfigurer.configure(config, true, "dns",
                    "order-service-hz-embedded.default.svc.cluster.local", 5801);

            assertThat(config.getNetworkConfig().getJoin().getMulticastConfig().isEnabled()).isFalse();
        }

        @Test
        @DisplayName("should still disable auto-detection when Kubernetes is enabled")
        void shouldStillDisableAutoDetectionWhenKubernetesEnabled() {
            EmbeddedClusteringConfigurer.configure(config, true, "dns",
                    "order-service-hz-embedded.default.svc.cluster.local", 5801);

            assertThat(config.getNetworkConfig().getJoin().getAutoDetectionConfig().isEnabled()).isFalse();
        }

        @Test
        @DisplayName("should use custom port")
        void shouldUseCustomPort() {
            EmbeddedClusteringConfigurer.configure(config, true, "dns",
                    "order-service-hz-embedded.default.svc.cluster.local", 5901);

            assertThat(config.getNetworkConfig().getPort()).isEqualTo(5901);
        }
    }

    @Nested
    @DisplayName("TCP-IP clustering mode")
    class TcpIpMode {

        @Test
        @DisplayName("should enable TCP-IP discovery when mode is tcp-ip")
        void shouldEnableTcpIpDiscovery() {
            EmbeddedClusteringConfigurer.configure(config, true, "tcp-ip",
                    "order-service:5801,order-service-2:5801", 5801);

            assertThat(config.getNetworkConfig().getJoin().getTcpIpConfig().isEnabled()).isTrue();
        }

        @Test
        @DisplayName("should add all members from comma-separated list")
        void shouldAddAllMembers() {
            EmbeddedClusteringConfigurer.configure(config, true, "tcp-ip",
                    "order-service:5801,order-service-2:5801,order-service-3:5801", 5801);

            assertThat(config.getNetworkConfig().getJoin().getTcpIpConfig().getMembers())
                    .contains("order-service:5801", "order-service-2:5801", "order-service-3:5801");
        }

        @Test
        @DisplayName("should not enable Kubernetes discovery in TCP-IP mode")
        void shouldNotEnableKubernetesInTcpIpMode() {
            EmbeddedClusteringConfigurer.configure(config, true, "tcp-ip",
                    "order-service:5801", 5801);

            assertThat(config.getNetworkConfig().getJoin().getKubernetesConfig().isEnabled()).isFalse();
        }

        @Test
        @DisplayName("should still disable multicast in TCP-IP mode")
        void shouldStillDisableMulticastInTcpIpMode() {
            EmbeddedClusteringConfigurer.configure(config, true, "tcp-ip",
                    "order-service:5801", 5801);

            assertThat(config.getNetworkConfig().getJoin().getMulticastConfig().isEnabled()).isFalse();
        }

        @Test
        @DisplayName("should trim whitespace from member addresses")
        void shouldTrimWhitespaceFromMembers() {
            EmbeddedClusteringConfigurer.configure(config, true, "tcp-ip",
                    "order-service:5801 , order-service-2:5801 ", 5801);

            assertThat(config.getNetworkConfig().getJoin().getTcpIpConfig().getMembers())
                    .contains("order-service:5801", "order-service-2:5801");
        }
    }

    @Nested
    @DisplayName("Default port constant")
    class DefaultPort {

        @Test
        @DisplayName("should expose DEFAULT_PORT as 5801")
        void shouldExposeDefaultPortAs5801() {
            assertThat(EmbeddedClusteringConfigurer.DEFAULT_PORT).isEqualTo(5801);
        }
    }
}
