package com.theyawns.framework.config;

import com.hazelcast.config.Config;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.List;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Tests for {@link HazelcastConfigCustomizer} functional interface.
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
@DisplayName("HazelcastConfigCustomizer - Functional interface contract")
class HazelcastConfigCustomizerTest {

    @Test
    @DisplayName("should accept lambda implementation")
    void shouldAcceptLambdaImplementation() {
        final HazelcastConfigCustomizer customizer = config ->
                config.setClusterName("customized");

        final Config config = new Config();
        customizer.customize(config);

        assertThat(config.getClusterName()).isEqualTo("customized");
    }

    @Test
    @DisplayName("should compose multiple customizers")
    void shouldComposeMultipleCustomizers() {
        final HazelcastConfigCustomizer first = config ->
                config.setClusterName("first");
        final HazelcastConfigCustomizer second = config ->
                config.setInstanceName("second");

        final Config config = new Config();
        List.of(first, second).forEach(c -> c.customize(config));

        assertThat(config.getClusterName()).isEqualTo("first");
        assertThat(config.getInstanceName()).isEqualTo("second");
    }

    @Test
    @DisplayName("should allow customizers to override each other")
    void shouldAllowCustomizersToOverrideEachOther() {
        final HazelcastConfigCustomizer first = config ->
                config.setClusterName("first");
        final HazelcastConfigCustomizer second = config ->
                config.setClusterName("second");

        final Config config = new Config();
        List.of(first, second).forEach(c -> c.customize(config));

        assertThat(config.getClusterName()).isEqualTo("second");
    }
}
