package com.theyawns.framework.config;

import com.hazelcast.config.Config;
import com.hazelcast.config.NativeMemoryConfig;
import com.hazelcast.memory.MemorySize;
import com.hazelcast.memory.MemoryUnit;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Unit tests for the HD Memory config customizer logic.
 *
 * <p>Tests the customizer lambda that would be created by
 * {@link HazelcastFeatureAutoConfiguration#hdMemoryConfigCustomizer}.
 * Validates the customizer correctly enables NativeMemoryConfig with
 * the specified capacity and allocator type on a real {@link Config}.
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
@DisplayName("HD Memory Config Customizer - Applies NativeMemoryConfig correctly")
class HdMemoryConfigCustomizerTest {

    @Test
    @DisplayName("should enable native memory with specified capacity and allocator")
    void shouldEnableNativeMemoryWithSpecifiedSettings() {
        final int capacityMb = 1024;
        final NativeMemoryConfig.MemoryAllocatorType allocatorType =
                NativeMemoryConfig.MemoryAllocatorType.POOLED;

        final HazelcastConfigCustomizer customizer = config -> {
            config.getNativeMemoryConfig()
                    .setEnabled(true)
                    .setSize(new MemorySize(capacityMb, MemoryUnit.MEGABYTES))
                    .setAllocatorType(allocatorType);
        };

        final Config config = new Config();
        customizer.customize(config);

        final NativeMemoryConfig nativeMemoryConfig = config.getNativeMemoryConfig();
        assertThat(nativeMemoryConfig.isEnabled()).isTrue();
        assertThat(nativeMemoryConfig.getSize().megaBytes()).isEqualTo(capacityMb);
        assertThat(nativeMemoryConfig.getAllocatorType()).isEqualTo(allocatorType);
    }

    @Test
    @DisplayName("should enable native memory with STANDARD allocator")
    void shouldEnableWithStandardAllocator() {
        final HazelcastConfigCustomizer customizer = config -> {
            config.getNativeMemoryConfig()
                    .setEnabled(true)
                    .setSize(new MemorySize(512, MemoryUnit.MEGABYTES))
                    .setAllocatorType(NativeMemoryConfig.MemoryAllocatorType.STANDARD);
        };

        final Config config = new Config();
        customizer.customize(config);

        assertThat(config.getNativeMemoryConfig().getAllocatorType())
                .isEqualTo(NativeMemoryConfig.MemoryAllocatorType.STANDARD);
    }

    @Test
    @DisplayName("should not enable native memory when customizer is not applied")
    void shouldNotEnableWhenNotApplied() {
        final Config config = new Config();
        assertThat(config.getNativeMemoryConfig().isEnabled()).isFalse();
    }
}
