package com.theyawns.ecommerce.order.exception;

import java.time.Instant;
import java.util.Map;

/**
 * Standard error response for REST API errors.
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
public class ErrorResponse {

    private final String message;
    private final String errorCode;
    private final Instant timestamp;
    private final Map<String, String> details;

    /**
     * Creates an error response without details.
     *
     * @param message the error message
     * @param errorCode the error code
     */
    public ErrorResponse(String message, String errorCode) {
        this(message, errorCode, null);
    }

    /**
     * Creates an error response with details.
     *
     * @param message the error message
     * @param errorCode the error code
     * @param details additional error details
     */
    public ErrorResponse(String message, String errorCode, Map<String, String> details) {
        this.message = message;
        this.errorCode = errorCode;
        this.timestamp = Instant.now();
        this.details = details;
    }

    public String getMessage() {
        return message;
    }

    public String getErrorCode() {
        return errorCode;
    }

    public Instant getTimestamp() {
        return timestamp;
    }

    public Map<String, String> getDetails() {
        return details;
    }
}
