package com.theyawns.ecommerce.order.exception;

import com.theyawns.framework.resilience.NonRetryableException;

/**
 * Exception thrown when an order cannot be found.
 *
 * <p>Implements {@link NonRetryableException} because a missing order is a
 * deterministic business failure that will not resolve on retry.
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
public class OrderNotFoundException extends RuntimeException implements NonRetryableException {

    private static final long serialVersionUID = 1L;

    private final String orderId;

    /**
     * Creates a new OrderNotFoundException.
     *
     * @param orderId the ID of the order that was not found
     */
    public OrderNotFoundException(String orderId) {
        super("Order not found: " + orderId);
        this.orderId = orderId;
    }

    /**
     * Returns the order ID that was not found.
     *
     * @return the order ID
     */
    public String getOrderId() {
        return orderId;
    }
}
