package com.theyawns.ecommerce.inventory.saga;

import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.nio.serialization.genericrecord.GenericRecord;
import com.hazelcast.topic.ITopic;
import com.hazelcast.topic.Message;
import com.hazelcast.topic.MessageListener;
import com.theyawns.ecommerce.common.events.OrderCreatedEvent;
import com.theyawns.ecommerce.inventory.service.ProductService;
import jakarta.annotation.PostConstruct;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

/**
 * Saga event listener for the Inventory Service.
 *
 * <p>Listens for saga-related events that trigger inventory actions:
 * <ul>
 *   <li>{@link OrderCreatedEvent} - Triggers stock reservation (saga step 1)</li>
 * </ul>
 *
 * <p>This component connects the Inventory Service to the choreographed saga
 * for order fulfillment. When an order is created (step 0), the inventory
 * service automatically reserves stock for the order's line items (step 1).
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
@Component
public class InventorySagaListener {

    private static final Logger logger = LoggerFactory.getLogger(InventorySagaListener.class);

    private final ProductService inventoryService;
    private final HazelcastInstance hazelcast;

    /**
     * Creates a new InventorySagaListener.
     *
     * @param inventoryService the inventory service for stock operations
     * @param hazelcast the Hazelcast instance for topic subscriptions
     */
    public InventorySagaListener(ProductService inventoryService, HazelcastInstance hazelcast) {
        this.inventoryService = inventoryService;
        this.hazelcast = hazelcast;
    }

    /**
     * Registers listeners for saga-related topics on startup.
     */
    @PostConstruct
    public void registerListeners() {
        logger.info("Registering inventory saga event listeners");

        ITopic<GenericRecord> orderCreatedTopic = hazelcast.getTopic("OrderCreated");
        orderCreatedTopic.addMessageListener(new OrderCreatedListener());

        logger.info("Inventory saga listeners registered successfully");
    }

    /**
     * Listener for OrderCreated events.
     *
     * <p>When an order is created as part of a saga, reserves stock for each
     * line item. The saga context (sagaId, correlationId) and payment context
     * (customerId, amount, currency) are propagated to the StockReservedEvent
     * for downstream processing by the Payment Service.
     */
    class OrderCreatedListener implements MessageListener<GenericRecord> {

        @Override
        public void onMessage(Message<GenericRecord> message) {
            GenericRecord record = message.getMessageObject();

            String sagaId = record.getString("sagaId");
            if (sagaId == null || sagaId.isEmpty()) {
                logger.debug("OrderCreated event without sagaId - not a saga event, ignoring");
                return;
            }

            String orderId = record.getString("key");
            String correlationId = record.getString("correlationId");
            String customerId = record.getString("customerId");

            logger.info("Received OrderCreated saga event: orderId={}, sagaId={}", orderId, sagaId);

            // Extract order total and payment context for downstream payment processing
            String total = record.getString("total");
            String currency = "USD"; // Default currency

            // Reserve stock for each line item
            // For the happy path, we reserve the first line item and propagate payment context
            GenericRecord[] lineItems = record.getArrayOfGenericRecord("lineItems");
            if (lineItems == null || lineItems.length == 0) {
                logger.warn("OrderCreated event has no line items: orderId={}, sagaId={}", orderId, sagaId);
                return;
            }

            // Reserve stock for each line item in the order
            for (GenericRecord lineItem : lineItems) {
                String productId = lineItem.getString("productId");
                int quantity = lineItem.getInt32("quantity");

                try {
                    inventoryService.reserveStockForSaga(
                            productId,
                            quantity,
                            orderId,
                            sagaId,
                            correlationId,
                            customerId,
                            total,
                            currency,
                            "CREDIT_CARD" // Default payment method
                    ).whenComplete((product, error) -> {
                        if (error != null) {
                            logger.error("Failed to reserve stock for product {} in saga: {} (orderId: {})",
                                    productId, sagaId, orderId, error);
                            // Compensation will be handled in Day 7
                        } else {
                            logger.info("Stock reserved for saga: productId={}, quantity={}, orderId={}, sagaId={}",
                                    productId, quantity, orderId, sagaId);
                        }
                    });
                } catch (Exception e) {
                    logger.error("Error initiating stock reservation for product {} in saga: {} (orderId: {})",
                            productId, sagaId, orderId, e);
                    // Compensation will be handled in Day 7
                }
            }
        }
    }
}
