package com.theyawns.framework.event;

import com.theyawns.framework.domain.DomainObject;

import java.util.concurrent.CompletableFuture;

/**
 * Interface for publishing domain events to the event bus.
 * Implementations handle the actual delivery mechanism (e.g., Hazelcast topics).
 *
 * <p>Publishers are responsible for:
 * <ul>
 *   <li>Delivering events to all registered subscribers</li>
 *   <li>Ensuring reliable delivery (at-least-once semantics)</li>
 *   <li>Supporting both sync and async publishing</li>
 * </ul>
 *
 * @param <D> The domain object type
 * @param <K> The key type of the domain object
 * @author Generated by Claude Code
 * @since 1.0
 */
public interface EventPublisher<D extends DomainObject<K>, K> {

    /**
     * Publishes an event asynchronously to all subscribers.
     *
     * @param event the event to publish
     * @return a future that completes when the event has been accepted for delivery
     */
    CompletableFuture<Void> publish(DomainEvent<D, K> event);

    /**
     * Publishes an event synchronously, blocking until delivery is confirmed.
     *
     * @param event the event to publish
     */
    void publishSync(DomainEvent<D, K> event);

    /**
     * Returns the topic name this publisher sends to.
     *
     * @return the topic name
     */
    String getTopicName();
}