package com.theyawns.framework.resilience;

/**
 * Marker interface for exceptions that should not trigger retry attempts.
 *
 * <p>Business exceptions like "insufficient stock" or "payment declined" will never
 * succeed on retry — they represent deterministic failures that must be handled
 * immediately rather than retried with exponential backoff.
 *
 * <p>Implement this interface on any exception class to skip retry. The exception
 * will still propagate through the circuit breaker (counting as a failure) and be
 * wrapped in {@link ResilienceException}.
 *
 * <p>This is a marker interface (rather than a base class) because service exceptions
 * already extend {@code RuntimeException} — a marker lets them opt in without
 * changing their inheritance hierarchy.
 *
 * <p>Example:
 * <pre>{@code
 * public class InsufficientStockException extends RuntimeException
 *         implements NonRetryableException {
 *     // ...
 * }
 * }</pre>
 *
 * @author Generated by Claude Code
 * @since 3.0
 * @see ResilienceAutoConfiguration
 * @see ResilientServiceInvoker
 */
public interface NonRetryableException {
    // Marker interface — business exceptions implement this to skip retry
}
