package com.theyawns.framework.resilience;

import org.springframework.boot.context.properties.ConfigurationProperties;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

/**
 * Configuration properties for Resilience4j circuit breaker and retry integration.
 *
 * <p>Provides configurable settings for:
 * <ul>
 *   <li>Global enable/disable toggle</li>
 *   <li>Default circuit breaker parameters</li>
 *   <li>Default retry parameters</li>
 *   <li>Per-instance overrides for named circuit breakers and retries</li>
 * </ul>
 *
 * <p>Example configuration in application.yml:
 * <pre>{@code
 * framework:
 *   resilience:
 *     enabled: true
 *     circuit-breaker:
 *       failure-rate-threshold: 50
 *       wait-duration-in-open-state: 10s
 *       sliding-window-size: 10
 *       sliding-window-type: COUNT_BASED
 *       minimum-number-of-calls: 5
 *       permitted-number-of-calls-in-half-open-state: 3
 *     retry:
 *       max-attempts: 3
 *       wait-duration: 500ms
 *       enable-exponential-backoff: true
 *       exponential-backoff-multiplier: 2.0
 *     instances:
 *       orderSaga:
 *         circuit-breaker:
 *           failure-rate-threshold: 70
 *         retry:
 *           max-attempts: 5
 * }</pre>
 *
 * @author Generated by Claude Code
 * @since 3.0
 * @see ResilienceAutoConfiguration
 * @see ResilientServiceInvoker
 */
@ConfigurationProperties(prefix = "framework.resilience")
public class ResilienceProperties {

    /**
     * Whether resilience features (circuit breaker, retry) are enabled.
     * Default: true
     */
    private boolean enabled = true;

    /**
     * Default circuit breaker configuration applied to all instances
     * unless overridden per-instance.
     */
    private CircuitBreakerProperties circuitBreaker = new CircuitBreakerProperties();

    /**
     * Default retry configuration applied to all instances
     * unless overridden per-instance.
     */
    private RetryProperties retry = new RetryProperties();

    /**
     * Per-instance overrides for named circuit breakers and retries.
     * Key: instance name (e.g., "orderSaga", "paymentListener")
     * Value: instance-specific configuration overrides
     */
    private Map<String, InstanceProperties> instances = new HashMap<>();

    /**
     * Creates a new ResilienceProperties with default values.
     */
    public ResilienceProperties() {
        // Default constructor
    }

    /**
     * Returns whether resilience features are enabled.
     *
     * @return true if enabled
     */
    public boolean isEnabled() {
        return enabled;
    }

    /**
     * Sets whether resilience features are enabled.
     *
     * @param enabled true to enable resilience features
     */
    public void setEnabled(final boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * Returns the default circuit breaker configuration.
     *
     * @return circuit breaker properties
     */
    public CircuitBreakerProperties getCircuitBreaker() {
        return circuitBreaker;
    }

    /**
     * Sets the default circuit breaker configuration.
     *
     * @param circuitBreaker circuit breaker properties
     */
    public void setCircuitBreaker(final CircuitBreakerProperties circuitBreaker) {
        this.circuitBreaker = Objects.requireNonNull(circuitBreaker, "circuitBreaker cannot be null");
    }

    /**
     * Returns the default retry configuration.
     *
     * @return retry properties
     */
    public RetryProperties getRetry() {
        return retry;
    }

    /**
     * Sets the default retry configuration.
     *
     * @param retry retry properties
     */
    public void setRetry(final RetryProperties retry) {
        this.retry = Objects.requireNonNull(retry, "retry cannot be null");
    }

    /**
     * Returns per-instance configuration overrides.
     *
     * @return map of instance name to instance properties
     */
    public Map<String, InstanceProperties> getInstances() {
        return instances;
    }

    /**
     * Sets per-instance configuration overrides.
     *
     * @param instances map of instance name to instance properties
     */
    public void setInstances(final Map<String, InstanceProperties> instances) {
        this.instances = instances != null ? instances : new HashMap<>();
    }

    /**
     * Resolves the circuit breaker properties for a named instance,
     * falling back to the default if no per-instance override exists.
     *
     * @param name the instance name
     * @return the resolved circuit breaker properties
     */
    public CircuitBreakerProperties getCircuitBreakerForInstance(final String name) {
        final InstanceProperties instance = instances.get(name);
        if (instance != null && instance.getCircuitBreaker() != null) {
            return instance.getCircuitBreaker();
        }
        return circuitBreaker;
    }

    /**
     * Resolves the retry properties for a named instance,
     * falling back to the default if no per-instance override exists.
     *
     * @param name the instance name
     * @return the resolved retry properties
     */
    public RetryProperties getRetryForInstance(final String name) {
        final InstanceProperties instance = instances.get(name);
        if (instance != null && instance.getRetry() != null) {
            return instance.getRetry();
        }
        return retry;
    }

    @Override
    public String toString() {
        return "ResilienceProperties{" +
                "enabled=" + enabled +
                ", circuitBreaker=" + circuitBreaker +
                ", retry=" + retry +
                ", instances=" + instances.size() +
                '}';
    }

    /**
     * Circuit breaker configuration properties.
     *
     * <p>Maps to Resilience4j {@code CircuitBreakerConfig} settings.
     *
     * @author Generated by Claude Code
     * @since 3.0
     */
    public static class CircuitBreakerProperties {

        /**
         * Failure rate threshold percentage (0-100) above which the circuit opens.
         * Default: 50
         */
        private float failureRateThreshold = 50;

        /**
         * Duration the circuit breaker stays open before transitioning to half-open.
         * Default: 10 seconds
         */
        private Duration waitDurationInOpenState = Duration.ofSeconds(10);

        /**
         * Size of the sliding window used to record call outcomes.
         * Default: 10
         */
        private int slidingWindowSize = 10;

        /**
         * Type of sliding window: COUNT_BASED or TIME_BASED.
         * Default: COUNT_BASED
         */
        private SlidingWindowType slidingWindowType = SlidingWindowType.COUNT_BASED;

        /**
         * Minimum number of calls required before the circuit breaker can evaluate the failure rate.
         * Default: 5
         */
        private int minimumNumberOfCalls = 5;

        /**
         * Number of calls permitted when the circuit breaker is half-open.
         * Default: 3
         */
        private int permittedNumberOfCallsInHalfOpenState = 3;

        /**
         * Creates a new CircuitBreakerProperties with default values.
         */
        public CircuitBreakerProperties() {
            // Default constructor
        }

        /**
         * Returns the failure rate threshold percentage.
         *
         * @return failure rate threshold (0-100)
         */
        public float getFailureRateThreshold() {
            return failureRateThreshold;
        }

        /**
         * Sets the failure rate threshold percentage.
         *
         * @param failureRateThreshold threshold (0-100)
         * @throws IllegalArgumentException if value is not between 0 and 100
         */
        public void setFailureRateThreshold(final float failureRateThreshold) {
            if (failureRateThreshold < 0 || failureRateThreshold > 100) {
                throw new IllegalArgumentException(
                        "failureRateThreshold must be between 0 and 100, got: " + failureRateThreshold);
            }
            this.failureRateThreshold = failureRateThreshold;
        }

        /**
         * Returns the wait duration in the open state.
         *
         * @return wait duration
         */
        public Duration getWaitDurationInOpenState() {
            return waitDurationInOpenState;
        }

        /**
         * Sets the wait duration in the open state.
         *
         * @param waitDurationInOpenState duration to wait before transitioning to half-open
         */
        public void setWaitDurationInOpenState(final Duration waitDurationInOpenState) {
            this.waitDurationInOpenState = Objects.requireNonNull(
                    waitDurationInOpenState, "waitDurationInOpenState cannot be null");
        }

        /**
         * Returns the sliding window size.
         *
         * @return sliding window size
         */
        public int getSlidingWindowSize() {
            return slidingWindowSize;
        }

        /**
         * Sets the sliding window size.
         *
         * @param slidingWindowSize window size (must be >= 1)
         * @throws IllegalArgumentException if value is less than 1
         */
        public void setSlidingWindowSize(final int slidingWindowSize) {
            if (slidingWindowSize < 1) {
                throw new IllegalArgumentException(
                        "slidingWindowSize must be at least 1, got: " + slidingWindowSize);
            }
            this.slidingWindowSize = slidingWindowSize;
        }

        /**
         * Returns the sliding window type.
         *
         * @return sliding window type
         */
        public SlidingWindowType getSlidingWindowType() {
            return slidingWindowType;
        }

        /**
         * Sets the sliding window type.
         *
         * @param slidingWindowType COUNT_BASED or TIME_BASED
         */
        public void setSlidingWindowType(final SlidingWindowType slidingWindowType) {
            this.slidingWindowType = Objects.requireNonNull(
                    slidingWindowType, "slidingWindowType cannot be null");
        }

        /**
         * Returns the minimum number of calls.
         *
         * @return minimum number of calls
         */
        public int getMinimumNumberOfCalls() {
            return minimumNumberOfCalls;
        }

        /**
         * Sets the minimum number of calls.
         *
         * @param minimumNumberOfCalls minimum calls (must be >= 1)
         * @throws IllegalArgumentException if value is less than 1
         */
        public void setMinimumNumberOfCalls(final int minimumNumberOfCalls) {
            if (minimumNumberOfCalls < 1) {
                throw new IllegalArgumentException(
                        "minimumNumberOfCalls must be at least 1, got: " + minimumNumberOfCalls);
            }
            this.minimumNumberOfCalls = minimumNumberOfCalls;
        }

        /**
         * Returns the permitted number of calls in half-open state.
         *
         * @return permitted calls in half-open state
         */
        public int getPermittedNumberOfCallsInHalfOpenState() {
            return permittedNumberOfCallsInHalfOpenState;
        }

        /**
         * Sets the permitted number of calls in half-open state.
         *
         * @param permittedNumberOfCallsInHalfOpenState permitted calls (must be >= 1)
         * @throws IllegalArgumentException if value is less than 1
         */
        public void setPermittedNumberOfCallsInHalfOpenState(final int permittedNumberOfCallsInHalfOpenState) {
            if (permittedNumberOfCallsInHalfOpenState < 1) {
                throw new IllegalArgumentException(
                        "permittedNumberOfCallsInHalfOpenState must be at least 1, got: "
                                + permittedNumberOfCallsInHalfOpenState);
            }
            this.permittedNumberOfCallsInHalfOpenState = permittedNumberOfCallsInHalfOpenState;
        }

        @Override
        public String toString() {
            return "CircuitBreakerProperties{" +
                    "failureRateThreshold=" + failureRateThreshold +
                    ", waitDurationInOpenState=" + waitDurationInOpenState +
                    ", slidingWindowSize=" + slidingWindowSize +
                    ", slidingWindowType=" + slidingWindowType +
                    ", minimumNumberOfCalls=" + minimumNumberOfCalls +
                    ", permittedNumberOfCallsInHalfOpenState=" + permittedNumberOfCallsInHalfOpenState +
                    '}';
        }
    }

    /**
     * Retry configuration properties.
     *
     * <p>Maps to Resilience4j {@code RetryConfig} settings.
     *
     * @author Generated by Claude Code
     * @since 3.0
     */
    public static class RetryProperties {

        /**
         * Maximum number of retry attempts (including the initial call).
         * Default: 3
         */
        private int maxAttempts = 3;

        /**
         * Wait duration between retries.
         * Default: 500ms
         */
        private Duration waitDuration = Duration.ofMillis(500);

        /**
         * Whether to use exponential backoff for retry intervals.
         * Default: true
         */
        private boolean enableExponentialBackoff = true;

        /**
         * Multiplier for exponential backoff.
         * Default: 2.0
         */
        private double exponentialBackoffMultiplier = 2.0;

        /**
         * Creates a new RetryProperties with default values.
         */
        public RetryProperties() {
            // Default constructor
        }

        /**
         * Returns the maximum number of retry attempts.
         *
         * @return max attempts
         */
        public int getMaxAttempts() {
            return maxAttempts;
        }

        /**
         * Sets the maximum number of retry attempts.
         *
         * @param maxAttempts max attempts (must be >= 1)
         * @throws IllegalArgumentException if value is less than 1
         */
        public void setMaxAttempts(final int maxAttempts) {
            if (maxAttempts < 1) {
                throw new IllegalArgumentException("maxAttempts must be at least 1, got: " + maxAttempts);
            }
            this.maxAttempts = maxAttempts;
        }

        /**
         * Returns the wait duration between retries.
         *
         * @return wait duration
         */
        public Duration getWaitDuration() {
            return waitDuration;
        }

        /**
         * Sets the wait duration between retries.
         *
         * @param waitDuration duration between retries
         */
        public void setWaitDuration(final Duration waitDuration) {
            this.waitDuration = Objects.requireNonNull(waitDuration, "waitDuration cannot be null");
        }

        /**
         * Returns whether exponential backoff is enabled.
         *
         * @return true if exponential backoff is enabled
         */
        public boolean isEnableExponentialBackoff() {
            return enableExponentialBackoff;
        }

        /**
         * Sets whether exponential backoff is enabled.
         *
         * @param enableExponentialBackoff true to enable exponential backoff
         */
        public void setEnableExponentialBackoff(final boolean enableExponentialBackoff) {
            this.enableExponentialBackoff = enableExponentialBackoff;
        }

        /**
         * Returns the exponential backoff multiplier.
         *
         * @return multiplier
         */
        public double getExponentialBackoffMultiplier() {
            return exponentialBackoffMultiplier;
        }

        /**
         * Sets the exponential backoff multiplier.
         *
         * @param exponentialBackoffMultiplier multiplier (must be >= 1.0)
         * @throws IllegalArgumentException if value is less than 1.0
         */
        public void setExponentialBackoffMultiplier(final double exponentialBackoffMultiplier) {
            if (exponentialBackoffMultiplier < 1.0) {
                throw new IllegalArgumentException(
                        "exponentialBackoffMultiplier must be at least 1.0, got: " + exponentialBackoffMultiplier);
            }
            this.exponentialBackoffMultiplier = exponentialBackoffMultiplier;
        }

        @Override
        public String toString() {
            return "RetryProperties{" +
                    "maxAttempts=" + maxAttempts +
                    ", waitDuration=" + waitDuration +
                    ", enableExponentialBackoff=" + enableExponentialBackoff +
                    ", exponentialBackoffMultiplier=" + exponentialBackoffMultiplier +
                    '}';
        }
    }

    /**
     * Per-instance override properties for named resilience instances.
     *
     * <p>Allows overriding circuit breaker and retry configuration for specific
     * named instances (e.g., "orderSaga", "paymentListener").
     *
     * @author Generated by Claude Code
     * @since 3.0
     */
    public static class InstanceProperties {

        /**
         * Circuit breaker overrides for this instance, or null to use defaults.
         */
        private CircuitBreakerProperties circuitBreaker;

        /**
         * Retry overrides for this instance, or null to use defaults.
         */
        private RetryProperties retry;

        /**
         * Creates a new InstanceProperties with no overrides.
         */
        public InstanceProperties() {
            // Default constructor
        }

        /**
         * Returns the circuit breaker overrides for this instance.
         *
         * @return circuit breaker properties, or null if using defaults
         */
        public CircuitBreakerProperties getCircuitBreaker() {
            return circuitBreaker;
        }

        /**
         * Sets the circuit breaker overrides for this instance.
         *
         * @param circuitBreaker circuit breaker properties
         */
        public void setCircuitBreaker(final CircuitBreakerProperties circuitBreaker) {
            this.circuitBreaker = circuitBreaker;
        }

        /**
         * Returns the retry overrides for this instance.
         *
         * @return retry properties, or null if using defaults
         */
        public RetryProperties getRetry() {
            return retry;
        }

        /**
         * Sets the retry overrides for this instance.
         *
         * @param retry retry properties
         */
        public void setRetry(final RetryProperties retry) {
            this.retry = retry;
        }

        @Override
        public String toString() {
            return "InstanceProperties{" +
                    "circuitBreaker=" + circuitBreaker +
                    ", retry=" + retry +
                    '}';
        }
    }

    /**
     * Sliding window type for circuit breaker measurement.
     *
     * @author Generated by Claude Code
     * @since 3.0
     */
    public enum SlidingWindowType {
        /** Count-based sliding window. */
        COUNT_BASED,
        /** Time-based sliding window. */
        TIME_BASED
    }
}
