package com.theyawns.framework.resilience;

/**
 * Exception thrown when a resilient operation fails after exhausting all retries
 * or when the circuit breaker rejects the call.
 *
 * <p>Wraps the underlying cause with diagnostic context including the operation name,
 * making it easier to identify which resilient operation failed in logs and monitoring.
 *
 * @author Generated by Claude Code
 * @since 3.0
 * @see ResilientServiceInvoker
 */
public class ResilienceException extends RuntimeException {

    private static final long serialVersionUID = 1L;

    /**
     * The name of the operation that failed.
     */
    private final String operationName;

    /**
     * Creates a new ResilienceException with the specified operation name and cause.
     *
     * @param message descriptive error message
     * @param operationName the name of the resilient operation that failed
     * @param cause the underlying exception
     */
    public ResilienceException(final String message, final String operationName, final Throwable cause) {
        super(message, cause);
        this.operationName = operationName;
    }

    /**
     * Creates a new ResilienceException with the specified operation name.
     *
     * @param message descriptive error message
     * @param operationName the name of the resilient operation that failed
     */
    public ResilienceException(final String message, final String operationName) {
        super(message);
        this.operationName = operationName;
    }

    /**
     * Returns the name of the operation that failed.
     *
     * @return the operation name
     */
    public String getOperationName() {
        return operationName;
    }
}
