package com.theyawns.framework.idempotency;

import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.map.IMap;
import io.micrometer.core.instrument.MeterRegistry;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Objects;
import java.util.concurrent.TimeUnit;

/**
 * Hazelcast IMap-backed implementation of {@link IdempotencyGuard}.
 *
 * <p>Uses {@code putIfAbsent} on an IMap to atomically claim event IDs.
 * Event IDs expire after the configured TTL, allowing the same event
 * to be reprocessed if it arrives much later (which would indicate a
 * new, legitimate delivery rather than a duplicate).
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
public class HazelcastIdempotencyGuard implements IdempotencyGuard {

    private static final Logger logger = LoggerFactory.getLogger(HazelcastIdempotencyGuard.class);

    private final IMap<String, Long> processedEventsMap;
    private final long ttlMillis;
    private final MeterRegistry meterRegistry;

    /**
     * Creates a new HazelcastIdempotencyGuard.
     *
     * @param hazelcast the Hazelcast instance (shared cluster preferred)
     * @param properties the idempotency configuration properties
     * @param meterRegistry the meter registry for metrics
     */
    public HazelcastIdempotencyGuard(final HazelcastInstance hazelcast,
                                      final IdempotencyProperties properties,
                                      final MeterRegistry meterRegistry) {
        Objects.requireNonNull(hazelcast, "hazelcast cannot be null");
        Objects.requireNonNull(properties, "properties cannot be null");
        this.processedEventsMap = hazelcast.getMap(properties.getMapName());
        this.ttlMillis = properties.getTtl().toMillis();
        this.meterRegistry = Objects.requireNonNull(meterRegistry, "meterRegistry cannot be null");
        logger.info("Initialized HazelcastIdempotencyGuard with map: {}, ttl: {}",
                properties.getMapName(), properties.getTtl());
    }

    @Override
    public boolean tryProcess(final String eventId) {
        Objects.requireNonNull(eventId, "eventId cannot be null");

        Long previous = processedEventsMap.putIfAbsent(
                eventId, System.currentTimeMillis(), ttlMillis, TimeUnit.MILLISECONDS);

        boolean firstTime = (previous == null);
        meterRegistry.counter("idempotency.checks",
                "result", firstTime ? "miss" : "hit").increment();

        if (!firstTime) {
            logger.debug("Duplicate event detected: eventId={}", eventId);
        }

        return firstTime;
    }
}
