package com.theyawns.framework.idempotency;

import com.hazelcast.core.HazelcastInstance;
import io.micrometer.core.instrument.MeterRegistry;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.autoconfigure.condition.ConditionalOnBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Auto-configuration for the idempotency guard.
 *
 * <p>Enabled by default. Provides:
 * <ul>
 *   <li>{@link IdempotencyGuard} — prefers shared cluster, falls back to embedded</li>
 * </ul>
 *
 * <p>To disable, set:
 * <pre>
 * framework.idempotency.enabled=false
 * </pre>
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
@Configuration
@ConditionalOnProperty(name = "framework.idempotency.enabled", matchIfMissing = true)
@ConditionalOnBean(HazelcastInstance.class)
@EnableConfigurationProperties(IdempotencyProperties.class)
public class IdempotencyAutoConfiguration {

    private static final Logger logger = LoggerFactory.getLogger(IdempotencyAutoConfiguration.class);

    /**
     * Creates the IdempotencyGuard bean.
     * Prefers the shared cluster for cross-service deduplication, falls back to embedded.
     *
     * @param hazelcastInstance the @Primary embedded Hazelcast instance
     * @param sharedHazelcast the shared Hazelcast client (nullable)
     * @param properties the idempotency properties
     * @param meterRegistry the meter registry
     * @return the idempotency guard
     */
    @Bean
    @ConditionalOnMissingBean
    public IdempotencyGuard idempotencyGuard(
            final HazelcastInstance hazelcastInstance,
            @Qualifier("hazelcastClient")
            @Autowired(required = false)
            final HazelcastInstance sharedHazelcast,
            final IdempotencyProperties properties,
            final MeterRegistry meterRegistry) {
        HazelcastInstance hz = sharedHazelcast != null ? sharedHazelcast : hazelcastInstance;
        logger.info("Creating HazelcastIdempotencyGuard bean (instance={}, ttl={})",
                sharedHazelcast != null ? "shared cluster" : "embedded",
                properties.getTtl());
        return new HazelcastIdempotencyGuard(hz, properties, meterRegistry);
    }
}
