package com.theyawns.framework.idempotency;

import org.springframework.boot.context.properties.ConfigurationProperties;

import java.time.Duration;

/**
 * Configuration properties for the idempotency guard.
 *
 * <p>Example configuration in application.yml:
 * <pre>{@code
 * framework:
 *   idempotency:
 *     enabled: true
 *     map-name: framework_PROCESSED_EVENTS
 *     ttl: 1h
 * }</pre>
 *
 * @author Generated by Claude Code
 * @since 3.0
 * @see IdempotencyAutoConfiguration
 */
@ConfigurationProperties(prefix = "framework.idempotency")
public class IdempotencyProperties {

    /**
     * Whether the idempotency guard is enabled.
     * Default: true
     */
    private boolean enabled = true;

    /**
     * IMap name for tracking processed event IDs.
     * Default: framework_PROCESSED_EVENTS
     */
    private String mapName = "framework_PROCESSED_EVENTS";

    /**
     * How long to remember processed event IDs.
     * Default: 1 hour
     */
    private Duration ttl = Duration.ofHours(1);

    /**
     * Creates a new IdempotencyProperties with default values.
     */
    public IdempotencyProperties() {
        // Default constructor
    }

    /**
     * Returns whether the idempotency guard is enabled.
     *
     * @return true if enabled
     */
    public boolean isEnabled() {
        return enabled;
    }

    /**
     * Sets whether the idempotency guard is enabled.
     *
     * @param enabled true to enable idempotency checking
     */
    public void setEnabled(final boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * Returns the IMap name for processed events.
     *
     * @return the map name
     */
    public String getMapName() {
        return mapName;
    }

    /**
     * Sets the IMap name for processed events.
     *
     * @param mapName the map name
     */
    public void setMapName(final String mapName) {
        this.mapName = mapName;
    }

    /**
     * Returns the TTL for processed event IDs.
     *
     * @return the TTL
     */
    public Duration getTtl() {
        return ttl;
    }

    /**
     * Sets the TTL for processed event IDs.
     *
     * @param ttl the TTL
     */
    public void setTtl(final Duration ttl) {
        this.ttl = ttl;
    }

    @Override
    public String toString() {
        return "IdempotencyProperties{" +
                "enabled=" + enabled +
                ", mapName='" + mapName + '\'' +
                ", ttl=" + ttl +
                '}';
    }
}
