package com.theyawns.framework.idempotency;

/**
 * Interface for idempotency checking using atomic check-and-claim semantics.
 *
 * <p>The idempotency guard ensures that each event is processed at most once,
 * even when at-least-once delivery (via the outbox pattern) may produce
 * duplicate messages. Implementations use {@code putIfAbsent} semantics
 * to atomically claim an event ID.
 *
 * <p>Extracted as an interface for Java 25 Mockito compatibility.
 *
 * @author Generated by Claude Code
 * @since 3.0
 * @see HazelcastIdempotencyGuard
 */
public interface IdempotencyGuard {

    /**
     * Atomically checks whether the given event has already been processed
     * and claims it if not.
     *
     * <p>Returns {@code true} if this caller is the first to claim the event
     * (the event should be processed). Returns {@code false} if the event
     * was already claimed (duplicate — skip processing).
     *
     * @param eventId the unique event identifier to check
     * @return true if this caller claimed the event (first time), false if duplicate
     */
    boolean tryProcess(String eventId);
}
