package com.theyawns.ecommerce.order.domain;

import com.hazelcast.config.Config;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.nio.serialization.genericrecord.GenericRecord;
import com.theyawns.ecommerce.common.domain.Customer;
import com.theyawns.ecommerce.common.events.CustomerCreatedEvent;
import com.theyawns.ecommerce.common.events.CustomerStatusChangedEvent;
import com.theyawns.ecommerce.common.events.CustomerUpdatedEvent;
import com.theyawns.framework.view.HazelcastViewStore;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;

import java.util.Optional;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Unit tests for CustomerCacheViewUpdater.
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
@DisplayName("CustomerCacheViewUpdater")
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class CustomerCacheViewUpdaterTest {

    private static final String DOMAIN_NAME = "CustomerCacheTest";

    private HazelcastInstance hazelcast;
    private HazelcastViewStore<String> viewStore;
    private CustomerCacheViewUpdater viewUpdater;

    @BeforeAll
    void setUpHazelcast() {
        Config config = new Config();
        config.setClusterName("customer-cache-test-" + System.currentTimeMillis());
        hazelcast = Hazelcast.newHazelcastInstance(config);
        viewStore = new HazelcastViewStore<>(hazelcast, DOMAIN_NAME);
        viewUpdater = new CustomerCacheViewUpdater(viewStore);
    }

    @AfterAll
    void tearDownHazelcast() {
        if (hazelcast != null) {
            hazelcast.shutdown();
        }
    }

    @BeforeEach
    void clearView() {
        viewStore.clear();
    }

    @Nested
    @DisplayName("CustomerCreatedEvent handling")
    class CustomerCreatedEventTests {

        @Test
        @DisplayName("should create cache entry with all fields")
        void shouldCreateCacheEntryWithAllFields() {
            String customerId = UUID.randomUUID().toString();

            CustomerCreatedEvent event = new CustomerCreatedEvent(
                    customerId,
                    "john@example.com",
                    "John Doe",
                    "123 Main St"
            );
            event.setPhone("555-1234");

            GenericRecord result = viewUpdater.update(event.toGenericRecord());

            assertNotNull(result);
            assertEquals(customerId, result.getString("customerId"));
            assertEquals("john@example.com", result.getString("email"));
            assertEquals("John Doe", result.getString("name"));
            assertEquals("123 Main St", result.getString("address"));
            assertEquals("555-1234", result.getString("phone"));
            assertEquals(Customer.Status.ACTIVE.name(), result.getString("status"));
            assertTrue(result.getInt64("cachedAt") > 0);
            assertTrue(result.getInt64("updatedAt") > 0);
        }

        @Test
        @DisplayName("should store entry in view store")
        void shouldStoreEntryInViewStore() {
            String customerId = UUID.randomUUID().toString();

            CustomerCreatedEvent event = new CustomerCreatedEvent(
                    customerId,
                    "store@example.com",
                    "Store Test",
                    "456 Oak Ave"
            );

            viewUpdater.update(event.toGenericRecord());

            Optional<GenericRecord> stored = viewStore.get(customerId);
            assertTrue(stored.isPresent());
            assertEquals("store@example.com", stored.get().getString("email"));
        }
    }

    @Nested
    @DisplayName("CustomerUpdatedEvent handling")
    class CustomerUpdatedEventTests {

        @Test
        @DisplayName("should update customer details")
        void shouldUpdateCustomerDetails() {
            String customerId = createCustomer();

            CustomerUpdatedEvent event = new CustomerUpdatedEvent(
                    customerId,
                    "Jane Doe Updated",
                    "789 Pine St",
                    "555-9999"
            );

            GenericRecord result = viewUpdater.update(event.toGenericRecord());

            assertNotNull(result);
            assertEquals("Jane Doe Updated", result.getString("name"));
            assertEquals("789 Pine St", result.getString("address"));
            assertEquals("555-9999", result.getString("phone"));
        }

        @Test
        @DisplayName("should preserve unchanged fields")
        void shouldPreserveUnchangedFields() {
            String customerId = createCustomer();

            // Update only name
            CustomerUpdatedEvent event = new CustomerUpdatedEvent(
                    customerId,
                    "Only Name Changed",
                    null,
                    null
            );

            GenericRecord result = viewUpdater.update(event.toGenericRecord());

            assertNotNull(result);
            assertEquals("Only Name Changed", result.getString("name"));
            // Original address should be preserved
            assertEquals("Test Address", result.getString("address"));
        }

        @Test
        @DisplayName("should return null for non-existent customer")
        void shouldReturnNullForNonExistentCustomer() {
            CustomerUpdatedEvent event = new CustomerUpdatedEvent(
                    "non-existent",
                    "Test",
                    null,
                    null
            );

            GenericRecord result = viewUpdater.update(event.toGenericRecord());

            assertFalse(viewStore.containsKey("non-existent"));
        }
    }

    @Nested
    @DisplayName("CustomerStatusChangedEvent handling")
    class CustomerStatusChangedEventTests {

        @Test
        @DisplayName("should update status to SUSPENDED")
        void shouldUpdateStatusToSuspended() {
            String customerId = createCustomer();

            CustomerStatusChangedEvent event = new CustomerStatusChangedEvent(
                    customerId,
                    Customer.Status.SUSPENDED.name(),
                    "Payment issues"
            );

            GenericRecord result = viewUpdater.update(event.toGenericRecord());

            assertNotNull(result);
            assertEquals(Customer.Status.SUSPENDED.name(), result.getString("status"));
        }

        @Test
        @DisplayName("should update status to CLOSED")
        void shouldUpdateStatusToClosed() {
            String customerId = createCustomer();

            CustomerStatusChangedEvent event = new CustomerStatusChangedEvent(
                    customerId,
                    Customer.Status.CLOSED.name(),
                    "Customer request"
            );

            GenericRecord result = viewUpdater.update(event.toGenericRecord());

            assertNotNull(result);
            assertEquals(Customer.Status.CLOSED.name(), result.getString("status"));
        }

        @Test
        @DisplayName("should preserve other fields on status change")
        void shouldPreserveOtherFieldsOnStatusChange() {
            String customerId = createCustomer();

            Optional<GenericRecord> before = viewStore.get(customerId);
            String originalEmail = before.get().getString("email");
            String originalName = before.get().getString("name");

            CustomerStatusChangedEvent event = new CustomerStatusChangedEvent(
                    customerId,
                    Customer.Status.SUSPENDED.name(),
                    "Test"
            );

            GenericRecord result = viewUpdater.update(event.toGenericRecord());

            assertEquals(originalEmail, result.getString("email"));
            assertEquals(originalName, result.getString("name"));
        }

        @Test
        @DisplayName("should return null for non-existent customer")
        void shouldReturnNullForNonExistentCustomer() {
            CustomerStatusChangedEvent event = new CustomerStatusChangedEvent(
                    "non-existent",
                    Customer.Status.CLOSED.name(),
                    "Test"
            );

            GenericRecord result = viewUpdater.update(event.toGenericRecord());

            assertFalse(viewStore.containsKey("non-existent"));
        }
    }

    /**
     * Helper method to create a customer and return its ID.
     */
    private String createCustomer() {
        String customerId = UUID.randomUUID().toString();

        CustomerCreatedEvent event = new CustomerCreatedEvent(
                customerId,
                "test@example.com",
                "Test Customer",
                "Test Address"
        );

        viewUpdater.update(event.toGenericRecord());
        return customerId;
    }
}
