package com.theyawns.ecommerce.order.domain;

import com.hazelcast.config.Config;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.nio.serialization.genericrecord.GenericRecord;
import com.theyawns.ecommerce.common.domain.Order;
import com.theyawns.ecommerce.common.domain.OrderLineItem;
import com.theyawns.ecommerce.common.events.OrderCancelledEvent;
import com.theyawns.ecommerce.common.events.OrderConfirmedEvent;
import com.theyawns.ecommerce.common.events.OrderCreatedEvent;
import com.theyawns.framework.view.HazelcastViewStore;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Unit tests for OrderViewUpdater.
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
@DisplayName("OrderViewUpdater")
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class OrderViewUpdaterTest {

    private static final String DOMAIN_NAME = "OrderViewTest";

    private HazelcastInstance hazelcast;
    private HazelcastViewStore<String> viewStore;
    private OrderViewUpdater viewUpdater;

    @BeforeAll
    void setUpHazelcast() {
        Config config = new Config();
        config.setClusterName("order-view-test-" + System.currentTimeMillis());
        hazelcast = Hazelcast.newHazelcastInstance(config);
        viewStore = new HazelcastViewStore<>(hazelcast, DOMAIN_NAME);
        viewUpdater = new OrderViewUpdater(viewStore);
    }

    @AfterAll
    void tearDownHazelcast() {
        if (hazelcast != null) {
            hazelcast.shutdown();
        }
    }

    @BeforeEach
    void clearView() {
        viewStore.clear();
    }

    @Nested
    @DisplayName("OrderCreatedEvent handling")
    class OrderCreatedEventTests {

        @Test
        @DisplayName("should create view entry with all fields")
        void shouldCreateViewEntryWithAllFields() {
            String orderId = UUID.randomUUID().toString();
            String customerId = UUID.randomUUID().toString();

            List<OrderLineItem> lineItems = Arrays.asList(
                    new OrderLineItem("prod-1", "Widget", "SKU-001", 2, new BigDecimal("15.00"))
            );

            OrderCreatedEvent event = new OrderCreatedEvent(
                    orderId,
                    customerId,
                    lineItems,
                    "456 Oak Ave"
            );
            event.setCustomerName("Jane Smith");
            event.setCustomerEmail("jane@example.com");

            GenericRecord result = viewUpdater.update(event.toGenericRecord());

            assertNotNull(result);
            assertEquals(orderId, result.getString("orderId"));
            assertEquals(customerId, result.getString("customerId"));
            assertEquals("Jane Smith", result.getString("customerName"));
            assertEquals("jane@example.com", result.getString("customerEmail"));
            assertEquals("456 Oak Ave", result.getString("shippingAddress"));
            assertEquals(Order.Status.PENDING.name(), result.getString("status"));
            assertTrue(result.getInt64("createdAt") > 0);
            assertTrue(result.getInt64("updatedAt") > 0);
        }

        @Test
        @DisplayName("should store entry in view store")
        void shouldStoreEntryInViewStore() {
            String orderId = UUID.randomUUID().toString();

            List<OrderLineItem> lineItems = Arrays.asList(
                    new OrderLineItem("prod-1", "Stored Widget", "SKU-001", 1, new BigDecimal("9.99"))
            );

            OrderCreatedEvent event = new OrderCreatedEvent(
                    orderId,
                    "cust-1",
                    lineItems,
                    "Store Address"
            );

            viewUpdater.update(event.toGenericRecord());

            Optional<GenericRecord> stored = viewStore.get(orderId);
            assertTrue(stored.isPresent());
            assertEquals("cust-1", stored.get().getString("customerId"));
        }

        @Test
        @DisplayName("should handle order with multiple line items")
        void shouldHandleOrderWithMultipleLineItems() {
            String orderId = UUID.randomUUID().toString();

            List<OrderLineItem> lineItems = Arrays.asList(
                    new OrderLineItem("prod-1", "Item 1", "SKU-001", 2, new BigDecimal("10.00")),
                    new OrderLineItem("prod-2", "Item 2", "SKU-002", 3, new BigDecimal("5.00")),
                    new OrderLineItem("prod-3", "Item 3", "SKU-003", 1, new BigDecimal("20.00"))
            );

            OrderCreatedEvent event = new OrderCreatedEvent(
                    orderId,
                    "cust-1",
                    lineItems,
                    "Multi Item Address"
            );

            GenericRecord result = viewUpdater.update(event.toGenericRecord());

            assertNotNull(result);
            GenericRecord[] storedLineItems = result.getArrayOfGenericRecord("lineItems");
            assertEquals(3, storedLineItems.length);
        }
    }

    @Nested
    @DisplayName("OrderConfirmedEvent handling")
    class OrderConfirmedEventTests {

        @Test
        @DisplayName("should update status to CONFIRMED")
        void shouldUpdateStatusToConfirmed() {
            String orderId = createOrder();

            OrderConfirmedEvent event = new OrderConfirmedEvent(orderId, "CONF-TEST");
            GenericRecord result = viewUpdater.update(event.toGenericRecord());

            assertNotNull(result);
            assertEquals(Order.Status.CONFIRMED.name(), result.getString("status"));
        }

        @Test
        @DisplayName("should update timestamp on confirmation")
        void shouldUpdateTimestampOnConfirmation() {
            String orderId = createOrder();

            Optional<GenericRecord> before = viewStore.get(orderId);
            long createdAt = before.get().getInt64("createdAt");
            long originalUpdatedAt = before.get().getInt64("updatedAt");

            // Small delay
            try {
                Thread.sleep(10);
            } catch (InterruptedException e) {
                Thread.currentThread().interrupt();
            }

            OrderConfirmedEvent event = new OrderConfirmedEvent(orderId, "CONF-TEST");
            GenericRecord result = viewUpdater.update(event.toGenericRecord());

            assertEquals(createdAt, result.getInt64("createdAt"));
            assertTrue(result.getInt64("updatedAt") >= originalUpdatedAt);
        }

        @Test
        @DisplayName("should return null for non-existent order")
        void shouldReturnNullForNonExistentOrder() {
            OrderConfirmedEvent event = new OrderConfirmedEvent("non-existent", "CONF-TEST");
            GenericRecord result = viewUpdater.update(event.toGenericRecord());

            assertFalse(viewStore.containsKey("non-existent"));
        }
    }

    @Nested
    @DisplayName("OrderCancelledEvent handling")
    class OrderCancelledEventTests {

        @Test
        @DisplayName("should update status to CANCELLED")
        void shouldUpdateStatusToCancelled() {
            String orderId = createOrder();

            OrderCancelledEvent event = new OrderCancelledEvent(orderId, "Test reason", "test");
            GenericRecord result = viewUpdater.update(event.toGenericRecord());

            assertNotNull(result);
            assertEquals(Order.Status.CANCELLED.name(), result.getString("status"));
        }

        @Test
        @DisplayName("should preserve order data on cancellation")
        void shouldPreserveOrderDataOnCancellation() {
            String orderId = createOrder();

            Optional<GenericRecord> before = viewStore.get(orderId);
            String customerId = before.get().getString("customerId");
            String shippingAddress = before.get().getString("shippingAddress");

            OrderCancelledEvent event = new OrderCancelledEvent(orderId, "Test reason", "test");
            GenericRecord result = viewUpdater.update(event.toGenericRecord());

            assertEquals(customerId, result.getString("customerId"));
            assertEquals(shippingAddress, result.getString("shippingAddress"));
        }

        @Test
        @DisplayName("should return null for non-existent order")
        void shouldReturnNullForNonExistentOrder() {
            OrderCancelledEvent event = new OrderCancelledEvent("non-existent", "Test", "test");
            GenericRecord result = viewUpdater.update(event.toGenericRecord());

            assertFalse(viewStore.containsKey("non-existent"));
        }
    }

    /**
     * Helper method to create an order and return its ID.
     */
    private String createOrder() {
        String orderId = UUID.randomUUID().toString();

        List<OrderLineItem> lineItems = Arrays.asList(
                new OrderLineItem("prod-1", "Test Product", "SKU-001", 1, new BigDecimal("29.99"))
        );

        OrderCreatedEvent event = new OrderCreatedEvent(
                orderId,
                "test-customer",
                lineItems,
                "Test Address"
        );

        viewUpdater.update(event.toGenericRecord());
        return orderId;
    }
}
