package com.theyawns.ecommerce.mcp.client;

import com.theyawns.ecommerce.mcp.config.McpServerProperties;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

/**
 * Tests for {@link ServiceClient}.
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
@DisplayName("ServiceClient")
class ServiceClientTest {

    private McpServerProperties properties;
    private ServiceClient serviceClient;

    @BeforeEach
    void setUp() {
        properties = new McpServerProperties();
        properties.setAccountUrl("http://localhost:8081");
        properties.setInventoryUrl("http://localhost:8082");
        properties.setOrderUrl("http://localhost:8083");
        properties.setPaymentUrl("http://localhost:8084");
        serviceClient = new ServiceClient(properties);
    }

    @Test
    @DisplayName("should resolve customer view URL")
    void shouldResolveCustomerUrl() {
        assertEquals("http://localhost:8081/api/customers", serviceClient.resolveUrl("customer"));
    }

    @Test
    @DisplayName("should resolve product view URL")
    void shouldResolveProductUrl() {
        assertEquals("http://localhost:8082/api/products", serviceClient.resolveUrl("product"));
    }

    @Test
    @DisplayName("should resolve order view URL")
    void shouldResolveOrderUrl() {
        assertEquals("http://localhost:8083/api/orders", serviceClient.resolveUrl("order"));
    }

    @Test
    @DisplayName("should resolve payment view URL")
    void shouldResolvePaymentUrl() {
        assertEquals("http://localhost:8084/api/payments", serviceClient.resolveUrl("payment"));
    }

    @Test
    @DisplayName("should resolve view name case-insensitively")
    void shouldResolveCaseInsensitively() {
        assertEquals("http://localhost:8081/api/customers", serviceClient.resolveUrl("Customer"));
        assertEquals("http://localhost:8082/api/products", serviceClient.resolveUrl("PRODUCT"));
    }

    @Test
    @DisplayName("should throw for unknown view name")
    void shouldThrowForUnknownView() {
        IllegalArgumentException exception = assertThrows(
                IllegalArgumentException.class,
                () -> serviceClient.resolveUrl("unknown"));

        assertEquals("Unknown view: unknown. Available views: customer, product, order, payment",
                exception.getMessage());
    }

    @Test
    @DisplayName("should use custom URLs from properties")
    void shouldUseCustomUrls() {
        properties.setAccountUrl("http://accounts:9081");
        properties.setInventoryUrl("http://inventory:9082");

        assertEquals("http://accounts:9081/api/customers", serviceClient.resolveUrl("customer"));
        assertEquals("http://inventory:9082/api/products", serviceClient.resolveUrl("product"));
    }
}
