package com.theyawns.framework.persistence.postgres;

import com.theyawns.framework.persistence.PersistableOutboxEntry;
import com.theyawns.framework.persistence.postgres.repository.OutboxRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.EnableAutoConfiguration;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

import java.util.List;
import java.util.Optional;
import java.util.stream.StreamSupport;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Integration tests for {@link PostgresOutboxStorePersistence} using Testcontainers PostgreSQL.
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
@DisplayName("PostgresOutboxStorePersistence - PostgreSQL integration tests")
@SpringBootTest(
        classes = PostgresOutboxStorePersistenceTest.TestConfig.class,
        properties = {
                "framework.persistence.enabled=true",
                "framework.edition.license.env-var=NONEXISTENT_TEST_LICENSE_VAR_12345",
                "spring.autoconfigure.exclude="
                        + "com.theyawns.framework.config.FrameworkAutoConfiguration,"
                        + "com.theyawns.framework.edition.EditionAutoConfiguration,"
                        + "com.theyawns.framework.vectorstore.VectorStoreAutoConfiguration,"
                        + "com.theyawns.framework.resilience.ResilienceAutoConfiguration,"
                        + "com.theyawns.framework.outbox.OutboxAutoConfiguration,"
                        + "com.theyawns.framework.dlq.DeadLetterQueueAutoConfiguration,"
                        + "com.theyawns.framework.idempotency.IdempotencyAutoConfiguration,"
                        + "com.theyawns.framework.saga.orchestrator.SagaOrchestratorAutoConfiguration,"
                        + "com.theyawns.framework.security.SecurityAutoConfiguration,"
                        + "com.theyawns.framework.security.PermitAllSecurityAutoConfiguration,"
                        + "com.theyawns.framework.security.identity.ServiceIdentityAutoConfiguration,"
                        + "org.springframework.boot.autoconfigure.hazelcast.HazelcastAutoConfiguration,"
                        + "com.hazelcast.spring.HazelcastObjectExtractionConfiguration"
        }
)
@Testcontainers
class PostgresOutboxStorePersistenceTest {

    @Container
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:16-alpine")
            .withDatabaseName("testdb")
            .withUsername("test")
            .withPassword("test");

    @DynamicPropertySource
    static void configureProperties(DynamicPropertyRegistry registry) {
        registry.add("spring.datasource.url", postgres::getJdbcUrl);
        registry.add("spring.datasource.username", postgres::getUsername);
        registry.add("spring.datasource.password", postgres::getPassword);
        registry.add("spring.flyway.enabled", () -> "true");
        registry.add("spring.jpa.hibernate.ddl-auto", () -> "validate");
    }

    @Autowired
    private OutboxRepository repository;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    private PostgresOutboxStorePersistence persistence;

    @BeforeEach
    void setUp() {
        persistence = new PostgresOutboxStorePersistence(repository, jdbcTemplate);
        repository.deleteAll();
    }

    @Test
    @DisplayName("should persist and load a single outbox entry")
    void shouldPersistAndLoadSingleEntry() {
        // Arrange
        PersistableOutboxEntry entry = new PersistableOutboxEntry(
                "evt-001", "CustomerCreatedEvent",
                "{\"_schemaType\":\"CustomerCreatedEvent\",\"_fieldKinds\":{\"name\":\"STRING\"},\"_fields\":{\"name\":\"John\"}}",
                0, "PENDING", 1700000000000L,
                null, null, null, null);

        // Act
        persistence.persist(entry);
        Optional<PersistableOutboxEntry> loaded = persistence.load("evt-001");

        // Assert
        assertTrue(loaded.isPresent());
        PersistableOutboxEntry result = loaded.get();
        assertEquals("evt-001", result.eventId());
        assertEquals("CustomerCreatedEvent", result.eventType());
        assertTrue(result.eventData().contains("John"));
        assertEquals(0, result.retryCount());
        assertEquals("PENDING", result.status());
        assertEquals(1700000000000L, result.createdAtMillis());
        assertNull(result.lastAttemptAtMillis());
        assertNull(result.failureReason());
        assertNull(result.claimantId());
        assertNull(result.claimedAtMillis());
    }

    @Test
    @DisplayName("should upsert outbox entry (update status)")
    void shouldUpsertEntry() {
        // Arrange
        PersistableOutboxEntry initial = new PersistableOutboxEntry(
                "evt-001", "TestEvent", "{\"_schemaType\":\"TestEvent\",\"_fieldKinds\":{},\"_fields\":{}}",
                0, "PENDING", 1700000000000L,
                null, null, null, null);
        persistence.persist(initial);

        // Act — update same key to CLAIMED status
        PersistableOutboxEntry claimed = new PersistableOutboxEntry(
                "evt-001", "TestEvent", "{\"_schemaType\":\"TestEvent\",\"_fieldKinds\":{},\"_fields\":{}}",
                0, "CLAIMED", 1700000000000L,
                1700000001000L, null, "member-1", 1700000001000L);
        persistence.persist(claimed);

        // Assert
        Optional<PersistableOutboxEntry> loaded = persistence.load("evt-001");
        assertTrue(loaded.isPresent());
        assertEquals("CLAIMED", loaded.get().status());
        assertEquals("member-1", loaded.get().claimantId());
        assertEquals(1700000001000L, loaded.get().claimedAtMillis());
    }

    @Test
    @DisplayName("should persist a batch of outbox entries")
    void shouldPersistBatch() {
        // Arrange
        String eventData = "{\"_schemaType\":\"Evt\",\"_fieldKinds\":{},\"_fields\":{}}";
        List<PersistableOutboxEntry> entries = List.of(
                new PersistableOutboxEntry("evt-001", "Evt", eventData,
                        0, "PENDING", 100L, null, null, null, null),
                new PersistableOutboxEntry("evt-002", "Evt", eventData,
                        0, "PENDING", 200L, null, null, null, null),
                new PersistableOutboxEntry("evt-003", "Evt", eventData,
                        1, "FAILED", 300L, 350L, "timeout", null, null)
        );

        // Act
        persistence.persistBatch(entries);

        // Assert
        assertEquals(3, repository.count());
        assertTrue(persistence.load("evt-001").isPresent());
        assertTrue(persistence.load("evt-002").isPresent());

        PersistableOutboxEntry failed = persistence.load("evt-003").orElseThrow();
        assertEquals("FAILED", failed.status());
        assertEquals(1, failed.retryCount());
        assertEquals("timeout", failed.failureReason());
    }

    @Test
    @DisplayName("should batch upsert existing entries")
    void shouldBatchUpsertExistingEntries() {
        // Arrange
        String eventData = "{\"_schemaType\":\"Evt\",\"_fieldKinds\":{},\"_fields\":{}}";
        persistence.persist(new PersistableOutboxEntry("evt-001", "Evt", eventData,
                0, "PENDING", 100L, null, null, null, null));

        // Act — batch includes existing key with updated status
        List<PersistableOutboxEntry> batch = List.of(
                new PersistableOutboxEntry("evt-001", "Evt", eventData,
                        0, "DELIVERED", 100L, 150L, null, null, null),
                new PersistableOutboxEntry("evt-002", "Evt", eventData,
                        0, "PENDING", 200L, null, null, null, null)
        );
        persistence.persistBatch(batch);

        // Assert
        assertEquals(2, repository.count());
        assertEquals("DELIVERED", persistence.load("evt-001").orElseThrow().status());
    }

    @Test
    @DisplayName("should load only non-delivered keys")
    void shouldLoadNonDeliveredKeys() {
        // Arrange
        String eventData = "{\"_schemaType\":\"Evt\",\"_fieldKinds\":{},\"_fields\":{}}";
        persistence.persist(new PersistableOutboxEntry("evt-001", "Evt", eventData,
                0, "PENDING", 100L, null, null, null, null));
        persistence.persist(new PersistableOutboxEntry("evt-002", "Evt", eventData,
                0, "CLAIMED", 200L, null, null, "m1", 200L));
        persistence.persist(new PersistableOutboxEntry("evt-003", "Evt", eventData,
                0, "DELIVERED", 300L, 350L, null, null, null));
        persistence.persist(new PersistableOutboxEntry("evt-004", "Evt", eventData,
                2, "FAILED", 400L, 450L, "error", null, null));

        // Act
        List<String> keys = StreamSupport.stream(
                persistence.loadNonDeliveredKeys().spliterator(), false).toList();

        // Assert — DELIVERED excluded, PENDING + CLAIMED + FAILED returned
        assertEquals(3, keys.size());
        assertTrue(keys.contains("evt-001"));
        assertTrue(keys.contains("evt-002"));
        assertTrue(keys.contains("evt-004"));
        assertFalse(keys.contains("evt-003")); // DELIVERED excluded
    }

    @Test
    @DisplayName("should delete a single outbox entry")
    void shouldDeleteSingleEntry() {
        // Arrange
        String eventData = "{\"_schemaType\":\"Evt\",\"_fieldKinds\":{},\"_fields\":{}}";
        persistence.persist(new PersistableOutboxEntry("evt-001", "Evt", eventData,
                0, "PENDING", 100L, null, null, null, null));

        // Act
        persistence.delete("evt-001");

        // Assert
        assertFalse(persistence.load("evt-001").isPresent());
    }

    @Test
    @DisplayName("should return empty when entry not found")
    void shouldReturnEmptyWhenNotFound() {
        // Act
        Optional<PersistableOutboxEntry> result = persistence.load("nonexistent");

        // Assert
        assertFalse(result.isPresent());
    }

    @Test
    @DisplayName("should report availability when database is reachable")
    void shouldReportAvailability() {
        assertTrue(persistence.isAvailable());
    }

    @Configuration
    @EnableAutoConfiguration
    static class TestConfig {
    }
}
