package com.theyawns.ecommerce.order.cache;

import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.nio.serialization.genericrecord.GenericRecord;
import com.hazelcast.topic.ITopic;
import com.hazelcast.topic.Message;
import com.hazelcast.topic.MessageListener;
import com.theyawns.ecommerce.common.events.CustomerCreatedEvent;
import com.theyawns.ecommerce.common.events.CustomerStatusChangedEvent;
import com.theyawns.ecommerce.common.events.CustomerUpdatedEvent;
import com.theyawns.ecommerce.order.domain.CustomerCacheViewUpdater;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.UUID;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.doReturn;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * Unit tests for CustomerCacheListener.
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
@DisplayName("CustomerCacheListener")
@ExtendWith(MockitoExtension.class)
class CustomerCacheListenerTest {

    @Mock
    private HazelcastInstance hazelcastClient;

    @Mock
    private CustomerCacheViewUpdater viewUpdater;

    @Mock
    private ITopic<GenericRecord> customerCreatedTopic;

    @Mock
    private ITopic<GenericRecord> customerUpdatedTopic;

    @Mock
    private ITopic<GenericRecord> customerStatusChangedTopic;

    private CustomerCacheListener listener;

    @BeforeEach
    void setUp() {
        listener = new CustomerCacheListener(hazelcastClient, viewUpdater);
    }

    @Test
    @DisplayName("should register listeners for all three customer event topics")
    void shouldRegisterListenersForAllTopics() {
        doReturn(customerCreatedTopic).when(hazelcastClient)
                .getTopic(CustomerCreatedEvent.EVENT_TYPE);
        doReturn(customerUpdatedTopic).when(hazelcastClient)
                .getTopic(CustomerUpdatedEvent.EVENT_TYPE);
        doReturn(customerStatusChangedTopic).when(hazelcastClient)
                .getTopic(CustomerStatusChangedEvent.EVENT_TYPE);

        listener.registerListeners();

        verify(customerCreatedTopic).addMessageListener(any(MessageListener.class));
        verify(customerUpdatedTopic).addMessageListener(any(MessageListener.class));
        verify(customerStatusChangedTopic).addMessageListener(any(MessageListener.class));
    }

    @Test
    @DisplayName("should not register listeners when hazelcast client is null")
    void shouldNotRegisterWhenClientIsNull() {
        CustomerCacheListener nullListener = new CustomerCacheListener(null, viewUpdater);

        nullListener.registerListeners();

        verify(viewUpdater, never()).updateDirect(any());
    }

    @Test
    @DisplayName("should subscribe to correct topic names")
    void shouldSubscribeToCorrectTopicNames() {
        doReturn(customerCreatedTopic).when(hazelcastClient)
                .getTopic(CustomerCreatedEvent.EVENT_TYPE);
        doReturn(customerUpdatedTopic).when(hazelcastClient)
                .getTopic(CustomerUpdatedEvent.EVENT_TYPE);
        doReturn(customerStatusChangedTopic).when(hazelcastClient)
                .getTopic(CustomerStatusChangedEvent.EVENT_TYPE);

        listener.registerListeners();

        verify(hazelcastClient).getTopic("CustomerCreated");
        verify(hazelcastClient).getTopic("CustomerUpdated");
        verify(hazelcastClient).getTopic("CustomerStatusChanged");
    }

    @Test
    @DisplayName("should delegate event processing to view updater")
    @SuppressWarnings("unchecked")
    void shouldDelegateToViewUpdater() {
        ArgumentCaptor<MessageListener<GenericRecord>> captor =
                ArgumentCaptor.forClass(MessageListener.class);

        doReturn(customerCreatedTopic).when(hazelcastClient)
                .getTopic(CustomerCreatedEvent.EVENT_TYPE);
        doReturn(customerUpdatedTopic).when(hazelcastClient)
                .getTopic(CustomerUpdatedEvent.EVENT_TYPE);
        doReturn(customerStatusChangedTopic).when(hazelcastClient)
                .getTopic(CustomerStatusChangedEvent.EVENT_TYPE);

        listener.registerListeners();

        verify(customerCreatedTopic).addMessageListener(captor.capture());

        // Simulate a message arriving on the topic
        GenericRecord event = new CustomerCreatedEvent(
                UUID.randomUUID().toString(), "test@example.com", "Test", "123 St"
        ).toGenericRecord();

        Message<GenericRecord> message = mock(Message.class);
        when(message.getMessageObject()).thenReturn(event);

        captor.getValue().onMessage(message);

        verify(viewUpdater, times(1)).updateDirect(event);
    }
}
