package com.theyawns.ecommerce.order.config;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Contact;
import io.swagger.v3.oas.models.info.Info;
import io.swagger.v3.oas.models.info.License;
import io.swagger.v3.oas.models.servers.Server;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.List;

/**
 * OpenAPI/Swagger configuration for Order Service.
 *
 * <p>Access documentation at:
 * <ul>
 *   <li>Swagger UI: /swagger-ui.html</li>
 *   <li>OpenAPI JSON: /v3/api-docs</li>
 *   <li>OpenAPI YAML: /v3/api-docs.yaml</li>
 * </ul>
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
@Configuration
public class OpenApiConfig {

    @Value("${server.port:8083}")
    private int serverPort;

    /**
     * Configures OpenAPI documentation.
     *
     * @return OpenAPI configuration
     */
    @Bean
    public OpenAPI orderServiceOpenAPI() {
        return new OpenAPI()
                .info(new Info()
                        .title("Order Service API")
                        .description("Order management microservice. " +
                                "Provides APIs for order lifecycle management including creation, " +
                                "confirmation, and cancellation using event sourcing patterns.")
                        .version("1.0.0")
                        .contact(new Contact()
                                .name("Hazelcast Microservices Framework")
                                .url("https://github.com/theyawns/hazelcast-microservices-framework"))
                        .license(new License()
                                .name("Apache 2.0")
                                .url("https://www.apache.org/licenses/LICENSE-2.0")))
                .servers(List.of(
                        new Server()
                                .url("http://localhost:" + serverPort)
                                .description("Local development server"),
                        new Server()
                                .url("http://order-service:8083")
                                .description("Docker container")));
    }
}
