package com.theyawns.ecommerce.order.config;

import com.hazelcast.config.Config;
import com.hazelcast.config.EventJournalConfig;
import com.hazelcast.config.MapConfig;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.theyawns.ecommerce.common.domain.Order;
import com.theyawns.ecommerce.order.domain.OrderViewUpdater;
import com.theyawns.framework.controller.EventSourcingController;
import com.theyawns.framework.event.DomainEvent;
import com.theyawns.framework.store.HazelcastEventStore;
import com.theyawns.framework.view.HazelcastViewStore;
import io.micrometer.core.instrument.MeterRegistry;
import jakarta.annotation.PostConstruct;
import jakarta.annotation.PreDestroy;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Spring configuration for the Order Service.
 *
 * <p>Configures:
 * <ul>
 *   <li>Hazelcast instance with event journal</li>
 *   <li>Event store for order events</li>
 *   <li>View store and updater for order materialized view</li>
 *   <li>Event sourcing controller</li>
 * </ul>
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
@Configuration
public class OrderServiceConfig {

    private static final Logger logger = LoggerFactory.getLogger(OrderServiceConfig.class);

    private static final String DOMAIN_NAME = "Order";

    @Value("${hazelcast.cluster.name:ecommerce-cluster}")
    private String clusterName;

    @Value("${hazelcast.event-journal.capacity:10000}")
    private int eventJournalCapacity;

    private EventSourcingController<Order, String, DomainEvent<Order, String>> controller;

    /**
     * Creates the Hazelcast instance for the Order Service.
     *
     * @return the configured Hazelcast instance
     */
    @Bean
    public HazelcastInstance hazelcastInstance() {
        Config config = new Config();
        config.setClusterName(clusterName);

        // Enable event journal for pending events map (required for Jet streaming)
        EventJournalConfig journalConfig = new EventJournalConfig()
                .setEnabled(true)
                .setCapacity(eventJournalCapacity);

        MapConfig pendingMapConfig = new MapConfig(DOMAIN_NAME + "_PENDING")
                .setEventJournalConfig(journalConfig);
        config.addMapConfig(pendingMapConfig);

        // Configure view map
        MapConfig viewMapConfig = new MapConfig(DOMAIN_NAME + "_VIEW");
        config.addMapConfig(viewMapConfig);

        // Configure event store map
        MapConfig eventStoreMapConfig = new MapConfig(DOMAIN_NAME + "_ES");
        config.addMapConfig(eventStoreMapConfig);

        // Configure customer orders index map (for getOrdersByCustomer)
        MapConfig customerOrdersMapConfig = new MapConfig("CustomerOrders");
        config.addMapConfig(customerOrdersMapConfig);

        logger.info("Creating Hazelcast instance for cluster: {}", clusterName);
        return Hazelcast.newHazelcastInstance(config);
    }

    /**
     * Creates the event store for order events.
     *
     * @param hazelcast the Hazelcast instance
     * @return the event store
     */
    @Bean
    public HazelcastEventStore<Order, String, DomainEvent<Order, String>> orderEventStore(
            HazelcastInstance hazelcast) {
        return new HazelcastEventStore<>(hazelcast, DOMAIN_NAME);
    }

    /**
     * Creates the view store for the order materialized view.
     *
     * @param hazelcast the Hazelcast instance
     * @return the view store
     */
    @Bean
    public HazelcastViewStore<String> orderViewStore(HazelcastInstance hazelcast) {
        return new HazelcastViewStore<>(hazelcast, DOMAIN_NAME);
    }

    /**
     * Creates the view updater that applies order events to the view.
     *
     * @param viewStore the view store
     * @return the view updater
     */
    @Bean
    public OrderViewUpdater orderViewUpdater(HazelcastViewStore<String> viewStore) {
        return new OrderViewUpdater(viewStore);
    }

    /**
     * Creates the event sourcing controller for order operations.
     *
     * @param hazelcast the Hazelcast instance
     * @param eventStore the event store
     * @param viewUpdater the view updater
     * @param meterRegistry the metrics registry
     * @return the event sourcing controller
     */
    @Bean
    public EventSourcingController<Order, String, DomainEvent<Order, String>> orderController(
            HazelcastInstance hazelcast,
            HazelcastEventStore<Order, String, DomainEvent<Order, String>> eventStore,
            OrderViewUpdater viewUpdater,
            MeterRegistry meterRegistry) {

        controller = EventSourcingController.<Order, String, DomainEvent<Order, String>>builder()
                .hazelcast(hazelcast)
                .domainName(DOMAIN_NAME)
                .eventStore(eventStore)
                .viewUpdater(viewUpdater)
                .meterRegistry(meterRegistry)
                .build();

        return controller;
    }

    /**
     * Starts the event sourcing pipeline after the controller is created.
     */
    @PostConstruct
    public void startPipeline() {
        if (controller != null) {
            logger.info("Starting Order event sourcing pipeline");
            controller.start();
        }
    }

    /**
     * Stops the event sourcing pipeline on shutdown.
     */
    @PreDestroy
    public void stopPipeline() {
        if (controller != null && controller.isRunning()) {
            logger.info("Stopping Order event sourcing pipeline");
            controller.stop();
        }
    }
}
