package com.theyawns.ecommerce.order.config;

import com.hazelcast.client.HazelcastClient;
import com.hazelcast.client.config.ClientConfig;
import com.hazelcast.config.Config;
import com.hazelcast.config.EventJournalConfig;
import com.hazelcast.config.EvictionPolicy;
import com.hazelcast.config.JoinConfig;
import com.hazelcast.config.MapConfig;
import com.hazelcast.config.MapStoreConfig;
import com.hazelcast.config.MaxSizePolicy;
import com.hazelcast.config.NetworkConfig;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.theyawns.ecommerce.common.domain.Order;
import com.theyawns.ecommerce.order.domain.CustomerCacheViewUpdater;
import com.theyawns.ecommerce.order.domain.CustomerOrderSummaryViewUpdater;
import com.theyawns.ecommerce.order.domain.EnrichedOrderViewUpdater;
import com.theyawns.ecommerce.common.view.OrderViewUpdater;
import com.theyawns.ecommerce.order.domain.ProductAvailabilityViewUpdater;
import com.theyawns.framework.config.HazelcastClientConfigCustomizer;
import com.theyawns.framework.config.HazelcastConfigCustomizer;
import com.theyawns.framework.controller.EventSourcingController;
import com.theyawns.framework.event.DomainEvent;
import com.theyawns.framework.outbox.OutboxStore;
import com.theyawns.framework.persistence.PersistenceProperties;
import com.theyawns.framework.persistence.mapstore.EventStoreMapStore;
import com.theyawns.framework.persistence.mapstore.ViewStoreMapStore;
import com.theyawns.framework.security.identity.EventAuthenticator;
import com.theyawns.framework.saga.HazelcastSagaStateStore;
import com.theyawns.framework.saga.SagaStateStore;
import com.theyawns.framework.store.HazelcastEventStore;
import com.theyawns.framework.view.HazelcastViewStore;
import io.micrometer.core.instrument.MeterRegistry;
import jakarta.annotation.PreDestroy;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.DependsOn;
import org.springframework.context.annotation.Primary;

import java.util.List;

/**
 * Spring configuration for the Order Service.
 *
 * <p>Configures:
 * <ul>
 *   <li>Hazelcast instance with event journal</li>
 *   <li>Event store for order events</li>
 *   <li>View store and updater for order materialized view</li>
 *   <li>Customer cache view store (denormalized customer data)</li>
 *   <li>Product availability view store (denormalized product data)</li>
 *   <li>Enriched order view store (orders with customer/product data)</li>
 *   <li>Customer order summary view store (aggregated order stats)</li>
 *   <li>Event sourcing controller</li>
 * </ul>
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
@Configuration
public class OrderServiceConfig {

    private static final Logger logger = LoggerFactory.getLogger(OrderServiceConfig.class);

    private static final String DOMAIN_NAME = "Order";
    private static final String CUSTOMER_CACHE_NAME = "CustomerCache";
    private static final String PRODUCT_AVAILABILITY_NAME = "ProductAvailability";
    private static final String ENRICHED_ORDER_NAME = "EnrichedOrder";
    private static final String CUSTOMER_ORDER_SUMMARY_NAME = "CustomerOrderSummary";

    @Value("${hazelcast.embedded.cluster-name:order-local}")
    private String embeddedClusterName;

    @Value("${hazelcast.cluster.name:ecommerce-cluster}")
    private String clusterName;

    @Value("${hazelcast.cluster.members:}")
    private String clusterMembers;

    @Value("${hazelcast.event-journal.capacity:10000}")
    private int eventJournalCapacity;

    @Autowired(required = false)
    private List<HazelcastConfigCustomizer> configCustomizers;

    @Autowired(required = false)
    private List<HazelcastClientConfigCustomizer> clientConfigCustomizers;

    private EventSourcingController<Order, String, DomainEvent<Order, String>> controller;

    /**
     * Creates the Hazelcast instance for the Order Service.
     *
     * <p>Uses a service-specific cluster name (default: {@code order-local}) to distinguish
     * this embedded instance from the shared cluster in Management Center.
     *
     * <p>MapStore persistence is NOT configured here because hazelcast-spring's
     * {@code BeanFactoryPostProcessor} forces early creation of this bean, before
     * auto-configuration beans (MapStore, PersistenceProperties) are available.
     * MapStore is attached later by the {@link #persistenceAttacher} bean.
     *
     * @return the configured Hazelcast instance
     */
    @Primary
    @Bean
    public HazelcastInstance hazelcastInstance() {
        Config config = new Config();

        // Resolve embedded cluster name: @Value → env var → default
        String effectiveEmbeddedName = embeddedClusterName;
        if (effectiveEmbeddedName == null || effectiveEmbeddedName.isEmpty()) {
            effectiveEmbeddedName = System.getenv("HAZELCAST_EMBEDDED_CLUSTER_NAME");
        }
        if (effectiveEmbeddedName == null || effectiveEmbeddedName.isEmpty()) {
            effectiveEmbeddedName = "order-local";
        }
        config.setClusterName(effectiveEmbeddedName);
        logger.info("Embedded cluster name: '{}'", effectiveEmbeddedName);

        // Resolve cluster members: @Value → env var → empty
        String effectiveClusterMembers = clusterMembers;
        if (effectiveClusterMembers == null || effectiveClusterMembers.isEmpty()) {
            effectiveClusterMembers = System.getenv("HAZELCAST_CLUSTER_MEMBERS");
        }

        // Enable event journal for pending events map (required for Jet streaming)
        int effectiveCapacity = eventJournalCapacity > 0 ? eventJournalCapacity : 10000;

        // Configure pending maps for ALL domains with event journal (required for cluster-wide consistency)
        for (String domain : new String[]{"Customer", "Product", "Order"}) {
            MapConfig pendingMapConfig = new MapConfig(domain + "_PENDING")
                    .setEventJournalConfig(new EventJournalConfig()
                            .setEnabled(true)
                            .setCapacity(effectiveCapacity));
            config.addMapConfig(pendingMapConfig);
        }

        // Configure view and event store maps (MapStore attached later by persistenceAttacher)
        config.addMapConfig(new MapConfig(DOMAIN_NAME + "_VIEW"));
        config.addMapConfig(new MapConfig(DOMAIN_NAME + "_ES"));

        // Configure customer orders index map (for getOrdersByCustomer)
        config.addMapConfig(new MapConfig("CustomerOrders"));

        // Configure cross-service materialized view maps
        config.addMapConfig(new MapConfig(CUSTOMER_CACHE_NAME + "_VIEW"));
        config.addMapConfig(new MapConfig(PRODUCT_AVAILABILITY_NAME + "_VIEW"));
        config.addMapConfig(new MapConfig(ENRICHED_ORDER_NAME + "_VIEW"));
        config.addMapConfig(new MapConfig(CUSTOMER_ORDER_SUMMARY_NAME + "_VIEW"));

        // Standalone embedded instance - no cluster join.
        // Cross-service communication uses the separate hazelcastClient() bean.
        NetworkConfig networkConfig = config.getNetworkConfig();
        JoinConfig joinConfig = networkConfig.getJoin();
        joinConfig.getMulticastConfig().setEnabled(false);
        joinConfig.getAutoDetectionConfig().setEnabled(false);

        // Enable Jet for stream processing pipeline
        config.getJetConfig().setEnabled(true);
        config.getJetConfig().setResourceUploadEnabled(true);

        // Apply framework-level customizers (e.g., HD Memory, TPC)
        if (configCustomizers != null) {
            configCustomizers.forEach(c -> c.customize(config));
        }

        logger.info("Creating standalone Hazelcast instance for local Jet processing (cluster: {})",
                embeddedClusterName);
        return Hazelcast.newHazelcastInstance(config);
    }

    /**
     * Creates a Hazelcast client that connects to the external shared cluster.
     *
     * <p>This client is used for cross-service communication:
     * <ul>
     *   <li>ITopic pub/sub for saga event propagation</li>
     *   <li>Shared saga state IMap</li>
     * </ul>
     *
     * <p>The embedded HazelcastInstance handles local Jet pipeline processing,
     * while this client handles distributed communication.
     *
     * @return the Hazelcast client instance, or null if no cluster members configured
     */
    @Bean(name = "hazelcastClient")
    public HazelcastInstance hazelcastClient() {
        // Resolve cluster members: @Value → env var
        String effectiveClusterMembers = clusterMembers;
        if (effectiveClusterMembers == null || effectiveClusterMembers.isEmpty()) {
            effectiveClusterMembers = System.getenv("HAZELCAST_CLUSTER_MEMBERS");
        }

        if (effectiveClusterMembers == null || effectiveClusterMembers.isBlank()) {
            logger.info("No cluster members configured - shared Hazelcast client not created");
            return null;
        }

        // Resolve cluster name
        String effectiveClusterName = clusterName;
        if (effectiveClusterName == null || effectiveClusterName.isEmpty()) {
            effectiveClusterName = System.getenv("HAZELCAST_CLUSTER_NAME");
        }
        if (effectiveClusterName == null || effectiveClusterName.isEmpty()) {
            effectiveClusterName = "ecommerce-cluster";
        }

        ClientConfig clientConfig = new ClientConfig();
        clientConfig.setClusterName(effectiveClusterName);
        for (String member : effectiveClusterMembers.split(",")) {
            clientConfig.getNetworkConfig().addAddress(member.trim());
        }

        // Apply framework-level client customizers (e.g., TPC)
        if (clientConfigCustomizers != null) {
            clientConfigCustomizers.forEach(c -> c.customize(clientConfig));
        }

        logger.info("Creating Hazelcast client for shared cluster: {} with members: {}",
                effectiveClusterName, effectiveClusterMembers);
        return HazelcastClient.newHazelcastClient(clientConfig);
    }

    /**
     * Attaches MapStore persistence to event store and view maps.
     *
     * <p>This bean runs during normal Spring bean creation (after auto-configuration
     * beans are available), modifying the live Hazelcast config to add MapStore
     * before any {@code getMap()} calls. The {@code hazelcastInstance()} bean is
     * forced early by hazelcast-spring's BeanFactoryPostProcessor, before persistence
     * beans exist — so MapStore must be attached in this separate phase.
     *
     * @param hazelcastInstance the embedded Hazelcast instance
     * @param esMapStoreProvider optional event store MapStore
     * @param viewMapStoreProvider optional view store MapStore
     * @param propsProvider optional persistence properties
     * @return marker object (bean exists to enforce ordering via @DependsOn)
     */
    @Bean
    public Object persistenceAttacher(
            HazelcastInstance hazelcastInstance,
            ObjectProvider<EventStoreMapStore> esMapStoreProvider,
            ObjectProvider<ViewStoreMapStore> viewMapStoreProvider,
            ObjectProvider<PersistenceProperties> propsProvider) {

        EventStoreMapStore esMapStore = esMapStoreProvider.getIfAvailable();
        ViewStoreMapStore viewMapStore = viewMapStoreProvider.getIfAvailable();
        PersistenceProperties props = propsProvider.getIfAvailable();

        if (esMapStore != null && viewMapStore != null && props != null) {
            // Attach MapStore to event store map
            MapConfig esConfig = hazelcastInstance.getConfig().getMapConfig(DOMAIN_NAME + "_ES");
            esConfig.setMapStoreConfig(new MapStoreConfig()
                    .setImplementation(esMapStore)
                    .setEnabled(true)
                    .setWriteDelaySeconds(props.getWriteDelaySeconds())
                    .setWriteBatchSize(props.getWriteBatchSize())
                    .setWriteCoalescing(false)
                    .setInitialLoadMode(MapStoreConfig.InitialLoadMode.LAZY));
            logger.info("Persistence enabled for {}_ES map (write-behind)", DOMAIN_NAME);

            PersistenceProperties.EvictionConfig esEviction = props.getEventStoreEviction();
            if (esEviction.isEnabled()) {
                esConfig.getEvictionConfig()
                        .setEvictionPolicy(EvictionPolicy.valueOf(esEviction.getEvictionPolicy()))
                        .setMaxSizePolicy(MaxSizePolicy.valueOf(esEviction.getMaxSizePolicy()))
                        .setSize(esEviction.getMaxSize());
                if (esEviction.getMaxIdleSeconds() > 0) {
                    esConfig.setMaxIdleSeconds(esEviction.getMaxIdleSeconds());
                }
                logger.info("Eviction enabled for {}_ES (maxSize={}, policy={})",
                        DOMAIN_NAME, esEviction.getMaxSize(), esEviction.getEvictionPolicy());
            }

            // Attach MapStore to view map
            MapConfig viewConfig = hazelcastInstance.getConfig().getMapConfig(DOMAIN_NAME + "_VIEW");
            viewConfig.setMapStoreConfig(new MapStoreConfig()
                    .setImplementation(viewMapStore)
                    .setEnabled(true)
                    .setWriteDelaySeconds(props.getWriteDelaySeconds())
                    .setWriteBatchSize(props.getWriteBatchSize())
                    .setWriteCoalescing(true)
                    .setInitialLoadMode(MapStoreConfig.InitialLoadMode.LAZY));
            logger.info("Persistence enabled for {}_VIEW map (write-behind)", DOMAIN_NAME);

            PersistenceProperties.EvictionConfig viewEviction = props.getViewStoreEviction();
            if (viewEviction.isEnabled()) {
                viewConfig.getEvictionConfig()
                        .setEvictionPolicy(EvictionPolicy.valueOf(viewEviction.getEvictionPolicy()))
                        .setMaxSizePolicy(MaxSizePolicy.valueOf(viewEviction.getMaxSizePolicy()))
                        .setSize(viewEviction.getMaxSize());
                if (viewEviction.getMaxIdleSeconds() > 0) {
                    viewConfig.setMaxIdleSeconds(viewEviction.getMaxIdleSeconds());
                }
                logger.info("Eviction enabled for {}_VIEW (maxSize={}, policy={}, maxIdle={}s)",
                        DOMAIN_NAME, viewEviction.getMaxSize(), viewEviction.getEvictionPolicy(),
                        viewEviction.getMaxIdleSeconds());
            }
        } else {
            logger.info("Persistence not available — {}_ES and {}_VIEW maps will use in-memory only",
                    DOMAIN_NAME, DOMAIN_NAME);
        }

        return "persistence-attached";
    }

    /**
     * Creates the event store for order events.
     *
     * @param hazelcast the Hazelcast instance
     * @return the event store
     */
    @Bean
    @DependsOn("persistenceAttacher")
    public HazelcastEventStore<Order, String, DomainEvent<Order, String>> orderEventStore(
            HazelcastInstance hazelcast) {
        return new HazelcastEventStore<>(hazelcast, DOMAIN_NAME);
    }

    /**
     * Creates the view store for the order materialized view.
     *
     * @param hazelcast the Hazelcast instance
     * @return the view store
     */
    @Bean
    @DependsOn("persistenceAttacher")
    public HazelcastViewStore<String> orderViewStore(HazelcastInstance hazelcast) {
        return new HazelcastViewStore<>(hazelcast, DOMAIN_NAME);
    }

    /**
     * Creates the view updater that applies order events to the view.
     *
     * @param orderViewStore the view store
     * @return the view updater
     */
    @Bean
    public OrderViewUpdater orderViewUpdater(HazelcastViewStore<String> orderViewStore) {
        return new OrderViewUpdater(orderViewStore);
    }

    // ============================================================
    // Cross-Service Materialized Views
    // ============================================================

    /**
     * Creates the customer cache view store (denormalized customer data).
     *
     * @param hazelcast the Hazelcast instance
     * @return the customer cache view store
     */
    @Bean
    public HazelcastViewStore<String> customerCacheViewStore(HazelcastInstance hazelcast) {
        return new HazelcastViewStore<>(hazelcast, CUSTOMER_CACHE_NAME);
    }

    /**
     * Creates the customer cache view updater.
     *
     * @param customerCacheViewStore the customer cache view store
     * @return the customer cache view updater
     */
    @Bean
    public CustomerCacheViewUpdater customerCacheViewUpdater(
            HazelcastViewStore<String> customerCacheViewStore) {
        return new CustomerCacheViewUpdater(customerCacheViewStore);
    }

    /**
     * Creates the product availability view store (denormalized product data).
     *
     * @param hazelcast the Hazelcast instance
     * @return the product availability view store
     */
    @Bean
    public HazelcastViewStore<String> productAvailabilityViewStore(HazelcastInstance hazelcast) {
        return new HazelcastViewStore<>(hazelcast, PRODUCT_AVAILABILITY_NAME);
    }

    /**
     * Creates the product availability view updater.
     *
     * @param productAvailabilityViewStore the product availability view store
     * @return the product availability view updater
     */
    @Bean
    public ProductAvailabilityViewUpdater productAvailabilityViewUpdater(
            HazelcastViewStore<String> productAvailabilityViewStore) {
        return new ProductAvailabilityViewUpdater(productAvailabilityViewStore);
    }

    /**
     * Creates the enriched order view store (orders with customer/product data).
     *
     * @param hazelcast the Hazelcast instance
     * @return the enriched order view store
     */
    @Bean
    public HazelcastViewStore<String> enrichedOrderViewStore(HazelcastInstance hazelcast) {
        return new HazelcastViewStore<>(hazelcast, ENRICHED_ORDER_NAME);
    }

    /**
     * Creates the enriched order view updater.
     *
     * @param enrichedOrderViewStore the enriched order view store
     * @param customerCacheViewStore the customer cache view store
     * @param productAvailabilityViewStore the product availability view store
     * @return the enriched order view updater
     */
    @Bean
    public EnrichedOrderViewUpdater enrichedOrderViewUpdater(
            HazelcastViewStore<String> enrichedOrderViewStore,
            HazelcastViewStore<String> customerCacheViewStore,
            HazelcastViewStore<String> productAvailabilityViewStore) {
        return new EnrichedOrderViewUpdater(
                enrichedOrderViewStore,
                customerCacheViewStore,
                productAvailabilityViewStore);
    }

    /**
     * Creates the customer order summary view store (aggregated order stats).
     *
     * @param hazelcast the Hazelcast instance
     * @return the customer order summary view store
     */
    @Bean
    public HazelcastViewStore<String> customerOrderSummaryViewStore(HazelcastInstance hazelcast) {
        return new HazelcastViewStore<>(hazelcast, CUSTOMER_ORDER_SUMMARY_NAME);
    }

    /**
     * Creates the customer order summary view updater.
     *
     * @param customerOrderSummaryViewStore the customer order summary view store
     * @return the customer order summary view updater
     */
    @Bean
    public CustomerOrderSummaryViewUpdater customerOrderSummaryViewUpdater(
            HazelcastViewStore<String> customerOrderSummaryViewStore) {
        return new CustomerOrderSummaryViewUpdater(customerOrderSummaryViewStore);
    }

    /**
     * Creates the saga state store for saga tracking.
     *
     * @param hazelcastInstance the Hazelcast instance
     * @param meterRegistry the metrics registry
     * @return the saga state store
     */
    @Bean
    public SagaStateStore sagaStateStore(
            @org.springframework.beans.factory.annotation.Qualifier("hazelcastClient")
            @org.springframework.beans.factory.annotation.Autowired(required = false)
            HazelcastInstance hazelcastClient,
            HazelcastInstance hazelcastInstance,
            MeterRegistry meterRegistry) {
        // Use shared cluster for saga state if available, otherwise fall back to embedded
        HazelcastInstance hz = hazelcastClient != null ? hazelcastClient : hazelcastInstance;
        return new HazelcastSagaStateStore(hz, meterRegistry);
    }

    /**
     * Creates the event sourcing controller for order operations.
     *
     * @param hazelcastInstance the Hazelcast instance
     * @param eventStore the event store
     * @param viewUpdater the view updater
     * @param meterRegistry the metrics registry
     * @return the event sourcing controller
     */
    @Bean
    public EventSourcingController<Order, String, DomainEvent<Order, String>> orderEventSourcingController(
            HazelcastInstance hazelcastInstance,
            @org.springframework.beans.factory.annotation.Qualifier("hazelcastClient")
            @org.springframework.beans.factory.annotation.Autowired(required = false)
            HazelcastInstance hazelcastClient,
            HazelcastEventStore<Order, String, DomainEvent<Order, String>> eventStore,
            OrderViewUpdater viewUpdater,
            MeterRegistry meterRegistry,
            @org.springframework.beans.factory.annotation.Autowired(required = false)
            OutboxStore outboxStore,
            @org.springframework.beans.factory.annotation.Autowired(required = false)
            EventAuthenticator eventAuthenticator) {

        controller = EventSourcingController.<Order, String, DomainEvent<Order, String>>builder()
                .hazelcast(hazelcastInstance)
                .sharedHazelcast(hazelcastClient)
                .domainName(DOMAIN_NAME)
                .eventStore(eventStore)
                .viewUpdater(viewUpdater)
                .viewUpdaterClass(OrderViewUpdater.class)
                .meterRegistry(meterRegistry)
                .outboxStore(outboxStore)
                .eventAuthenticator(eventAuthenticator)
                .build();

        // Start the pipeline immediately after building the controller
        logger.info("Starting Order event sourcing pipeline");
        controller.start();

        return controller;
    }

    /**
     * Stops the event sourcing pipeline on shutdown.
     */
    @PreDestroy
    public void stopPipeline() {
        if (controller != null && controller.isRunning()) {
            logger.info("Stopping Order event sourcing pipeline");
            controller.stop();
        }
    }
}
