package com.theyawns.ecommerce.order.config;

import com.hazelcast.config.Config;
import com.hazelcast.config.EventJournalConfig;
import com.hazelcast.config.JoinConfig;
import com.hazelcast.config.MapConfig;
import com.hazelcast.config.NetworkConfig;
import com.hazelcast.config.TcpIpConfig;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.theyawns.ecommerce.common.domain.Order;
import com.theyawns.ecommerce.order.domain.CustomerCacheViewUpdater;
import com.theyawns.ecommerce.order.domain.CustomerOrderSummaryViewUpdater;
import com.theyawns.ecommerce.order.domain.EnrichedOrderViewUpdater;
import com.theyawns.ecommerce.common.view.OrderViewUpdater;
import com.theyawns.ecommerce.order.domain.ProductAvailabilityViewUpdater;
import com.theyawns.framework.controller.EventSourcingController;
import com.theyawns.framework.event.DomainEvent;
import com.theyawns.framework.saga.HazelcastSagaStateStore;
import com.theyawns.framework.saga.SagaStateStore;
import com.theyawns.framework.store.HazelcastEventStore;
import com.theyawns.framework.view.HazelcastViewStore;
import io.micrometer.core.instrument.MeterRegistry;
import jakarta.annotation.PreDestroy;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Spring configuration for the Order Service.
 *
 * <p>Configures:
 * <ul>
 *   <li>Hazelcast instance with event journal</li>
 *   <li>Event store for order events</li>
 *   <li>View store and updater for order materialized view</li>
 *   <li>Customer cache view store (denormalized customer data)</li>
 *   <li>Product availability view store (denormalized product data)</li>
 *   <li>Enriched order view store (orders with customer/product data)</li>
 *   <li>Customer order summary view store (aggregated order stats)</li>
 *   <li>Event sourcing controller</li>
 * </ul>
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
@Configuration
public class OrderServiceConfig {

    private static final Logger logger = LoggerFactory.getLogger(OrderServiceConfig.class);

    private static final String DOMAIN_NAME = "Order";
    private static final String CUSTOMER_CACHE_NAME = "CustomerCache";
    private static final String PRODUCT_AVAILABILITY_NAME = "ProductAvailability";
    private static final String ENRICHED_ORDER_NAME = "EnrichedOrder";
    private static final String CUSTOMER_ORDER_SUMMARY_NAME = "CustomerOrderSummary";

    @Value("${hazelcast.cluster.name:ecommerce-cluster}")
    private String clusterName;

    @Value("${hazelcast.cluster.members:}")
    private String clusterMembers;

    @Value("${hazelcast.event-journal.capacity:10000}")
    private int eventJournalCapacity;

    private EventSourcingController<Order, String, DomainEvent<Order, String>> controller;

    /**
     * Creates the Hazelcast instance for the Order Service.
     *
     * @return the configured Hazelcast instance
     */
    @Bean
    public HazelcastInstance hazelcastInstance() {
        Config config = new Config();
        String effectiveClusterName = (clusterName != null && !clusterName.isEmpty())
                ? clusterName
                : "ecommerce-cluster";
        logger.info("Cluster name from config: '{}', effective: '{}'", clusterName, effectiveClusterName);
        config.setClusterName(effectiveClusterName);

        // Enable event journal for pending events map (required for Jet streaming)
        int effectiveCapacity = eventJournalCapacity > 0 ? eventJournalCapacity : 10000;
        EventJournalConfig journalConfig = new EventJournalConfig()
                .setEnabled(true)
                .setCapacity(effectiveCapacity);

        // Configure pending maps for ALL domains with event journal (required for cluster-wide consistency)
        for (String domain : new String[]{"Customer", "Product", "Order"}) {
            MapConfig pendingMapConfig = new MapConfig(domain + "_PENDING")
                    .setEventJournalConfig(new EventJournalConfig()
                            .setEnabled(true)
                            .setCapacity(effectiveCapacity));
            config.addMapConfig(pendingMapConfig);
        }

        // Configure view map
        MapConfig viewMapConfig = new MapConfig(DOMAIN_NAME + "_VIEW");
        config.addMapConfig(viewMapConfig);

        // Configure event store map
        MapConfig eventStoreMapConfig = new MapConfig(DOMAIN_NAME + "_ES");
        config.addMapConfig(eventStoreMapConfig);

        // Configure customer orders index map (for getOrdersByCustomer)
        MapConfig customerOrdersMapConfig = new MapConfig("CustomerOrders");
        config.addMapConfig(customerOrdersMapConfig);

        // Configure customer cache view map (denormalized customer data)
        MapConfig customerCacheMapConfig = new MapConfig(CUSTOMER_CACHE_NAME + "_VIEW");
        config.addMapConfig(customerCacheMapConfig);

        // Configure product availability view map (denormalized product data)
        MapConfig productAvailabilityMapConfig = new MapConfig(PRODUCT_AVAILABILITY_NAME + "_VIEW");
        config.addMapConfig(productAvailabilityMapConfig);

        // Configure enriched order view map (orders with customer/product data)
        MapConfig enrichedOrderMapConfig = new MapConfig(ENRICHED_ORDER_NAME + "_VIEW");
        config.addMapConfig(enrichedOrderMapConfig);

        // Configure customer order summary view map (aggregated order stats)
        MapConfig customerOrderSummaryMapConfig = new MapConfig(CUSTOMER_ORDER_SUMMARY_NAME + "_VIEW");
        config.addMapConfig(customerOrderSummaryMapConfig);

        // Configure network discovery - disable multicast to prevent accidental cluster formation
        // with other services. Use TCP-IP if HAZELCAST_CLUSTER_MEMBERS is specified.
        NetworkConfig networkConfig = config.getNetworkConfig();
        JoinConfig joinConfig = networkConfig.getJoin();
        joinConfig.getMulticastConfig().setEnabled(false);
        joinConfig.getAutoDetectionConfig().setEnabled(false);

        if (clusterMembers != null && !clusterMembers.isBlank()) {
            TcpIpConfig tcpIpConfig = joinConfig.getTcpIpConfig();
            tcpIpConfig.setEnabled(true);
            for (String member : clusterMembers.split(",")) {
                tcpIpConfig.addMember(member.trim());
            }
            logger.info("TCP-IP discovery enabled with members: {}", clusterMembers);
        } else {
            logger.info("No cluster members configured - running as single-member cluster");
        }

        // Enable Jet for stream processing pipeline
        config.getJetConfig().setEnabled(true);
        config.getJetConfig().setResourceUploadEnabled(true);

        logger.info("Creating Hazelcast instance for cluster: {} with Jet enabled", clusterName);
        return Hazelcast.newHazelcastInstance(config);
    }

    /**
     * Creates the event store for order events.
     *
     * @param hazelcast the Hazelcast instance
     * @return the event store
     */
    @Bean
    public HazelcastEventStore<Order, String, DomainEvent<Order, String>> orderEventStore(
            HazelcastInstance hazelcast) {
        return new HazelcastEventStore<>(hazelcast, DOMAIN_NAME);
    }

    /**
     * Creates the view store for the order materialized view.
     *
     * @param hazelcast the Hazelcast instance
     * @return the view store
     */
    @Bean
    public HazelcastViewStore<String> orderViewStore(HazelcastInstance hazelcast) {
        return new HazelcastViewStore<>(hazelcast, DOMAIN_NAME);
    }

    /**
     * Creates the view updater that applies order events to the view.
     *
     * @param viewStore the view store
     * @return the view updater
     */
    @Bean
    public OrderViewUpdater orderViewUpdater(HazelcastViewStore<String> orderViewStore) {
        return new OrderViewUpdater(orderViewStore);
    }

    // ============================================================
    // Cross-Service Materialized Views
    // ============================================================

    /**
     * Creates the customer cache view store (denormalized customer data).
     *
     * @param hazelcast the Hazelcast instance
     * @return the customer cache view store
     */
    @Bean
    public HazelcastViewStore<String> customerCacheViewStore(HazelcastInstance hazelcast) {
        return new HazelcastViewStore<>(hazelcast, CUSTOMER_CACHE_NAME);
    }

    /**
     * Creates the customer cache view updater.
     *
     * @param customerCacheViewStore the customer cache view store
     * @return the customer cache view updater
     */
    @Bean
    public CustomerCacheViewUpdater customerCacheViewUpdater(
            HazelcastViewStore<String> customerCacheViewStore) {
        return new CustomerCacheViewUpdater(customerCacheViewStore);
    }

    /**
     * Creates the product availability view store (denormalized product data).
     *
     * @param hazelcast the Hazelcast instance
     * @return the product availability view store
     */
    @Bean
    public HazelcastViewStore<String> productAvailabilityViewStore(HazelcastInstance hazelcast) {
        return new HazelcastViewStore<>(hazelcast, PRODUCT_AVAILABILITY_NAME);
    }

    /**
     * Creates the product availability view updater.
     *
     * @param productAvailabilityViewStore the product availability view store
     * @return the product availability view updater
     */
    @Bean
    public ProductAvailabilityViewUpdater productAvailabilityViewUpdater(
            HazelcastViewStore<String> productAvailabilityViewStore) {
        return new ProductAvailabilityViewUpdater(productAvailabilityViewStore);
    }

    /**
     * Creates the enriched order view store (orders with customer/product data).
     *
     * @param hazelcast the Hazelcast instance
     * @return the enriched order view store
     */
    @Bean
    public HazelcastViewStore<String> enrichedOrderViewStore(HazelcastInstance hazelcast) {
        return new HazelcastViewStore<>(hazelcast, ENRICHED_ORDER_NAME);
    }

    /**
     * Creates the enriched order view updater.
     *
     * @param enrichedOrderViewStore the enriched order view store
     * @param customerCacheViewStore the customer cache view store
     * @param productAvailabilityViewStore the product availability view store
     * @return the enriched order view updater
     */
    @Bean
    public EnrichedOrderViewUpdater enrichedOrderViewUpdater(
            HazelcastViewStore<String> enrichedOrderViewStore,
            HazelcastViewStore<String> customerCacheViewStore,
            HazelcastViewStore<String> productAvailabilityViewStore) {
        return new EnrichedOrderViewUpdater(
                enrichedOrderViewStore,
                customerCacheViewStore,
                productAvailabilityViewStore);
    }

    /**
     * Creates the customer order summary view store (aggregated order stats).
     *
     * @param hazelcast the Hazelcast instance
     * @return the customer order summary view store
     */
    @Bean
    public HazelcastViewStore<String> customerOrderSummaryViewStore(HazelcastInstance hazelcast) {
        return new HazelcastViewStore<>(hazelcast, CUSTOMER_ORDER_SUMMARY_NAME);
    }

    /**
     * Creates the customer order summary view updater.
     *
     * @param customerOrderSummaryViewStore the customer order summary view store
     * @return the customer order summary view updater
     */
    @Bean
    public CustomerOrderSummaryViewUpdater customerOrderSummaryViewUpdater(
            HazelcastViewStore<String> customerOrderSummaryViewStore) {
        return new CustomerOrderSummaryViewUpdater(customerOrderSummaryViewStore);
    }

    /**
     * Creates the saga state store for saga tracking.
     *
     * @param hazelcast the Hazelcast instance
     * @param meterRegistry the metrics registry
     * @return the saga state store
     */
    @Bean
    public SagaStateStore sagaStateStore(HazelcastInstance hazelcast, MeterRegistry meterRegistry) {
        return new HazelcastSagaStateStore(hazelcast, meterRegistry);
    }

    /**
     * Creates the event sourcing controller for order operations.
     *
     * @param hazelcast the Hazelcast instance
     * @param eventStore the event store
     * @param viewUpdater the view updater
     * @param meterRegistry the metrics registry
     * @return the event sourcing controller
     */
    @Bean
    public EventSourcingController<Order, String, DomainEvent<Order, String>> orderEventSourcingController(
            HazelcastInstance hazelcast,
            HazelcastEventStore<Order, String, DomainEvent<Order, String>> eventStore,
            OrderViewUpdater viewUpdater,
            MeterRegistry meterRegistry) {

        controller = EventSourcingController.<Order, String, DomainEvent<Order, String>>builder()
                .hazelcast(hazelcast)
                .domainName(DOMAIN_NAME)
                .eventStore(eventStore)
                .viewUpdater(viewUpdater)
                .viewUpdaterClass(OrderViewUpdater.class)
                .meterRegistry(meterRegistry)
                .build();

        // Start the pipeline immediately after building the controller
        logger.info("Starting Order event sourcing pipeline");
        controller.start();

        return controller;
    }

    /**
     * Stops the event sourcing pipeline on shutdown.
     */
    @PreDestroy
    public void stopPipeline() {
        if (controller != null && controller.isRunning()) {
            logger.info("Stopping Order event sourcing pipeline");
            controller.stop();
        }
    }
}
