package com.theyawns.ecommerce.account.domain;

import com.hazelcast.config.Config;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.nio.serialization.genericrecord.GenericRecord;
import com.hazelcast.nio.serialization.genericrecord.GenericRecordBuilder;
import com.theyawns.ecommerce.common.domain.Customer;
import com.theyawns.ecommerce.common.events.CustomerCreatedEvent;
import com.theyawns.ecommerce.common.events.CustomerStatusChangedEvent;
import com.theyawns.ecommerce.common.events.CustomerUpdatedEvent;
import com.theyawns.framework.view.HazelcastViewStore;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;

import java.time.Instant;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;

/**
 * Unit tests for CustomerViewUpdater.
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
@DisplayName("CustomerViewUpdater")
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class CustomerViewUpdaterTest {

    private HazelcastInstance hazelcast;
    private HazelcastViewStore<String> viewStore;
    private CustomerViewUpdater viewUpdater;

    @BeforeAll
    void setUpHazelcast() {
        Config config = new Config();
        config.setClusterName("view-updater-test-" + System.currentTimeMillis());
        hazelcast = Hazelcast.newHazelcastInstance(config);
        viewStore = new HazelcastViewStore<>(hazelcast, "CustomerTest");
        viewUpdater = new CustomerViewUpdater(viewStore);
    }

    @AfterAll
    void tearDownHazelcast() {
        if (hazelcast != null) {
            hazelcast.shutdown();
        }
    }

    @Nested
    @DisplayName("CustomerCreatedEvent handling")
    class CustomerCreatedEventTests {

        @Test
        @DisplayName("should create new customer view from event")
        void shouldCreateNewCustomerViewFromEvent() {
            CustomerCreatedEvent event = new CustomerCreatedEvent(
                    "cust-123",
                    "test@example.com",
                    "John Doe",
                    "123 Main St"
            );
            event.setPhone("555-1234");

            GenericRecord eventRecord = event.toGenericRecord();
            GenericRecord result = viewUpdater.applyEvent(eventRecord, null);

            assertNotNull(result);
            assertEquals("cust-123", result.getString("customerId"));
            assertEquals("test@example.com", result.getString("email"));
            assertEquals("John Doe", result.getString("name"));
            assertEquals("123 Main St", result.getString("address"));
            assertEquals("555-1234", result.getString("phone"));
            assertEquals(Customer.Status.ACTIVE.name(), result.getString("status"));
        }

        @Test
        @DisplayName("should extract key from event record")
        void shouldExtractKeyFromEventRecord() {
            CustomerCreatedEvent event = new CustomerCreatedEvent(
                    "cust-456",
                    "test@example.com",
                    "Jane Doe",
                    "456 Oak Ave"
            );

            GenericRecord eventRecord = event.toGenericRecord();
            String key = viewUpdater.extractKey(eventRecord);

            assertEquals("cust-456", key);
        }
    }

    @Nested
    @DisplayName("CustomerUpdatedEvent handling")
    class CustomerUpdatedEventTests {

        @Test
        @DisplayName("should update existing customer view")
        void shouldUpdateExistingCustomerView() {
            GenericRecord currentState = createCustomerRecord("cust-123", "test@example.com",
                    "John Doe", "123 Main St", "555-1234", "ACTIVE");

            CustomerUpdatedEvent event = new CustomerUpdatedEvent(
                    "cust-123",
                    "John Smith",
                    "456 New St",
                    "555-9999"
            );

            GenericRecord eventRecord = event.toGenericRecord();
            GenericRecord result = viewUpdater.applyEvent(eventRecord, currentState);

            assertNotNull(result);
            assertEquals("cust-123", result.getString("customerId"));
            assertEquals("test@example.com", result.getString("email"));
            assertEquals("John Smith", result.getString("name"));
            assertEquals("456 New St", result.getString("address"));
            assertEquals("555-9999", result.getString("phone"));
            assertEquals("ACTIVE", result.getString("status"));
        }

        @Test
        @DisplayName("should preserve unchanged fields")
        void shouldPreserveUnchangedFields() {
            GenericRecord currentState = createCustomerRecord("cust-123", "test@example.com",
                    "John Doe", "123 Main St", "555-1234", "ACTIVE");

            CustomerUpdatedEvent event = new CustomerUpdatedEvent(
                    "cust-123",
                    "John Smith",
                    null,
                    null
            );

            GenericRecord eventRecord = event.toGenericRecord();
            GenericRecord result = viewUpdater.applyEvent(eventRecord, currentState);

            assertNotNull(result);
            assertEquals("John Smith", result.getString("name"));
            assertEquals("123 Main St", result.getString("address"));
            assertEquals("555-1234", result.getString("phone"));
        }

        @Test
        @DisplayName("should return null when customer does not exist")
        void shouldReturnNullWhenCustomerDoesNotExist() {
            CustomerUpdatedEvent event = new CustomerUpdatedEvent(
                    "cust-123",
                    "John Smith",
                    "456 New St",
                    "555-9999"
            );

            GenericRecord eventRecord = event.toGenericRecord();
            GenericRecord result = viewUpdater.applyEvent(eventRecord, null);

            assertNull(result);
        }
    }

    @Nested
    @DisplayName("CustomerStatusChangedEvent handling")
    class CustomerStatusChangedEventTests {

        @Test
        @DisplayName("should change customer status")
        void shouldChangeCustomerStatus() {
            GenericRecord currentState = createCustomerRecord("cust-123", "test@example.com",
                    "John Doe", "123 Main St", "555-1234", "ACTIVE");

            CustomerStatusChangedEvent event = new CustomerStatusChangedEvent(
                    "cust-123",
                    "SUSPENDED",
                    "Payment overdue"
            );

            GenericRecord eventRecord = event.toGenericRecord();
            GenericRecord result = viewUpdater.applyEvent(eventRecord, currentState);

            assertNotNull(result);
            assertEquals("SUSPENDED", result.getString("status"));
            assertEquals("John Doe", result.getString("name"));
        }

        @Test
        @DisplayName("should return null when customer does not exist")
        void shouldReturnNullWhenCustomerDoesNotExist() {
            CustomerStatusChangedEvent event = new CustomerStatusChangedEvent(
                    "cust-123",
                    "CLOSED",
                    "Account terminated"
            );

            GenericRecord eventRecord = event.toGenericRecord();
            GenericRecord result = viewUpdater.applyEvent(eventRecord, null);

            assertNull(result);
        }
    }

    @Nested
    @DisplayName("Unknown event type handling")
    class UnknownEventTypeTests {

        @Test
        @DisplayName("should return current state for unknown event type")
        void shouldReturnCurrentStateForUnknownEventType() {
            GenericRecord currentState = createCustomerRecord("cust-123", "test@example.com",
                    "John Doe", "123 Main St", "555-1234", "ACTIVE");

            GenericRecord unknownEvent = GenericRecordBuilder.compact("UnknownEvent")
                    .setString("eventType", "UnknownEvent")
                    .setString("key", "cust-123")
                    .build();

            GenericRecord result = viewUpdater.applyEvent(unknownEvent, currentState);

            assertEquals(currentState, result);
        }
    }

    /**
     * Helper method to create a customer GenericRecord for testing.
     */
    private GenericRecord createCustomerRecord(String customerId, String email, String name,
                                                String address, String phone, String status) {
        Instant now = Instant.now();
        return GenericRecordBuilder.compact(Customer.SCHEMA_NAME)
                .setString("customerId", customerId)
                .setString("email", email)
                .setString("name", name)
                .setString("address", address)
                .setString("phone", phone)
                .setString("status", status)
                .setInt64("createdAt", now.toEpochMilli())
                .setInt64("updatedAt", now.toEpochMilli())
                .build();
    }
}
