package com.theyawns.ecommerce.order.controller;

import com.theyawns.ecommerce.common.domain.Order;
import com.theyawns.ecommerce.common.dto.OrderDTO;
import com.theyawns.ecommerce.common.dto.OrderLineItemDTO;
import com.theyawns.ecommerce.order.exception.GlobalExceptionHandler;
import com.theyawns.ecommerce.order.exception.InvalidOrderStateException;
import com.theyawns.ecommerce.order.exception.OrderNotFoundException;
import com.theyawns.ecommerce.order.service.OrderOperations;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;

import java.math.BigDecimal;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.asyncDispatch;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.patch;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.request;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * Integration tests for OrderController REST endpoints.
 * Uses standalone MockMvc setup with interface mocking.
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
@ExtendWith(MockitoExtension.class)
@DisplayName("OrderController Integration Tests")
class OrderControllerIntegrationTest {

    private MockMvc mockMvc;

    @Mock
    private OrderOperations orderService;

    @InjectMocks
    private OrderController orderController;

    @BeforeEach
    void setUp() {
        mockMvc = MockMvcBuilders.standaloneSetup(orderController)
                .setControllerAdvice(new GlobalExceptionHandler())
                .build();
    }

    @Nested
    @DisplayName("POST /api/orders")
    class CreateOrderEndpointTests {

        @Test
        @DisplayName("should create order and return 201")
        void shouldCreateOrderAndReturn201() throws Exception {
            Order order = createTestOrder("order-123", "cust-123", Order.Status.PENDING);

            when(orderService.createOrder(any(OrderDTO.class)))
                    .thenReturn(CompletableFuture.completedFuture(order));

            MvcResult mvcResult = mockMvc.perform(post("/api/orders")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("""
                                    {
                                        "customerId": "cust-123",
                                        "customerName": "John Doe",
                                        "shippingAddress": "123 Main St",
                                        "lineItems": [
                                            {
                                                "productId": "prod-1",
                                                "productName": "Test Widget",
                                                "sku": "SKU-001",
                                                "quantity": 2,
                                                "unitPrice": 10.00
                                            }
                                        ]
                                    }
                                    """))
                    .andExpect(request().asyncStarted())
                    .andReturn();

            mockMvc.perform(asyncDispatch(mvcResult))
                    .andExpect(status().isCreated())
                    .andExpect(jsonPath("$.orderId").value("order-123"))
                    .andExpect(jsonPath("$.customerId").value("cust-123"))
                    .andExpect(jsonPath("$.status").value("PENDING"));
        }

        @Test
        @DisplayName("should return 400 for invalid order data")
        void shouldReturn400ForInvalidOrderData() throws Exception {
            mockMvc.perform(post("/api/orders")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("""
                                    {
                                        "customerId": "",
                                        "lineItems": []
                                    }
                                    """))
                    .andExpect(status().isBadRequest());
        }
    }

    @Nested
    @DisplayName("GET /api/orders/{id}")
    class GetOrderEndpointTests {

        @Test
        @DisplayName("should return order when found")
        void shouldReturnOrderWhenFound() throws Exception {
            Order order = createTestOrder("order-123", "cust-123", Order.Status.PENDING);

            when(orderService.getOrder("order-123")).thenReturn(Optional.of(order));

            mockMvc.perform(get("/api/orders/order-123"))
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$.orderId").value("order-123"))
                    .andExpect(jsonPath("$.customerId").value("cust-123"))
                    .andExpect(jsonPath("$.status").value("PENDING"));
        }

        @Test
        @DisplayName("should return 404 when order not found")
        void shouldReturn404WhenOrderNotFound() throws Exception {
            when(orderService.getOrder("nonexistent")).thenReturn(Optional.empty());

            mockMvc.perform(get("/api/orders/nonexistent"))
                    .andExpect(status().isNotFound());
        }
    }

    @Nested
    @DisplayName("GET /api/orders/customer/{customerId}")
    class GetOrdersByCustomerEndpointTests {

        @Test
        @DisplayName("should return orders for customer")
        void shouldReturnOrdersForCustomer() throws Exception {
            Order order1 = createTestOrder("order-1", "cust-123", Order.Status.PENDING);
            Order order2 = createTestOrder("order-2", "cust-123", Order.Status.CONFIRMED);

            when(orderService.getOrdersByCustomer("cust-123"))
                    .thenReturn(Arrays.asList(order1, order2));

            mockMvc.perform(get("/api/orders/customer/cust-123"))
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$").isArray())
                    .andExpect(jsonPath("$.length()").value(2))
                    .andExpect(jsonPath("$[0].orderId").value("order-1"))
                    .andExpect(jsonPath("$[1].orderId").value("order-2"));
        }

        @Test
        @DisplayName("should return empty list when no orders for customer")
        void shouldReturnEmptyListWhenNoOrdersForCustomer() throws Exception {
            when(orderService.getOrdersByCustomer("cust-empty"))
                    .thenReturn(Collections.emptyList());

            mockMvc.perform(get("/api/orders/customer/cust-empty"))
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$").isArray())
                    .andExpect(jsonPath("$.length()").value(0));
        }
    }

    @Nested
    @DisplayName("PATCH /api/orders/{id}/confirm")
    class ConfirmOrderEndpointTests {

        @Test
        @DisplayName("should confirm order and return 200")
        void shouldConfirmOrderAndReturn200() throws Exception {
            Order confirmedOrder = createTestOrder("order-123", "cust-123", Order.Status.CONFIRMED);

            when(orderService.confirmOrder("order-123"))
                    .thenReturn(CompletableFuture.completedFuture(confirmedOrder));

            MvcResult mvcResult = mockMvc.perform(patch("/api/orders/order-123/confirm"))
                    .andExpect(request().asyncStarted())
                    .andReturn();

            mockMvc.perform(asyncDispatch(mvcResult))
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$.orderId").value("order-123"))
                    .andExpect(jsonPath("$.status").value("CONFIRMED"));
        }

        @Test
        @DisplayName("should return 404 when order not found")
        void shouldReturn404WhenOrderNotFound() throws Exception {
            when(orderService.confirmOrder("nonexistent"))
                    .thenThrow(new OrderNotFoundException("nonexistent"));

            mockMvc.perform(patch("/api/orders/nonexistent/confirm"))
                    .andExpect(status().isNotFound())
                    .andExpect(jsonPath("$.errorCode").value("ORDER_NOT_FOUND"));
        }

        @Test
        @DisplayName("should return 409 when order cannot be confirmed")
        void shouldReturn409WhenOrderCannotBeConfirmed() throws Exception {
            when(orderService.confirmOrder("order-123"))
                    .thenThrow(new InvalidOrderStateException("order-123", "CANCELLED", "confirm"));

            mockMvc.perform(patch("/api/orders/order-123/confirm"))
                    .andExpect(status().isConflict())
                    .andExpect(jsonPath("$.errorCode").value("INVALID_ORDER_STATE"));
        }
    }

    @Nested
    @DisplayName("PATCH /api/orders/{id}/cancel")
    class CancelOrderEndpointTests {

        @Test
        @DisplayName("should cancel order and return 200")
        void shouldCancelOrderAndReturn200() throws Exception {
            Order cancelledOrder = createTestOrder("order-123", "cust-123", Order.Status.CANCELLED);

            when(orderService.cancelOrder(eq("order-123"), eq("Customer request"), eq("customer")))
                    .thenReturn(CompletableFuture.completedFuture(cancelledOrder));

            MvcResult mvcResult = mockMvc.perform(patch("/api/orders/order-123/cancel")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("""
                                    {
                                        "reason": "Customer request",
                                        "cancelledBy": "customer"
                                    }
                                    """))
                    .andExpect(request().asyncStarted())
                    .andReturn();

            mockMvc.perform(asyncDispatch(mvcResult))
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$.orderId").value("order-123"))
                    .andExpect(jsonPath("$.status").value("CANCELLED"));
        }

        @Test
        @DisplayName("should return 404 when order not found")
        void shouldReturn404WhenOrderNotFound() throws Exception {
            when(orderService.cancelOrder(eq("nonexistent"), anyString(), anyString()))
                    .thenThrow(new OrderNotFoundException("nonexistent"));

            mockMvc.perform(patch("/api/orders/nonexistent/cancel")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("""
                                    {
                                        "reason": "Test",
                                        "cancelledBy": "test"
                                    }
                                    """))
                    .andExpect(status().isNotFound())
                    .andExpect(jsonPath("$.errorCode").value("ORDER_NOT_FOUND"));
        }

        @Test
        @DisplayName("should return 409 when order cannot be cancelled")
        void shouldReturn409WhenOrderCannotBeCancelled() throws Exception {
            when(orderService.cancelOrder(eq("order-123"), anyString(), anyString()))
                    .thenThrow(new InvalidOrderStateException("order-123", "SHIPPED", "cancel"));

            mockMvc.perform(patch("/api/orders/order-123/cancel")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("""
                                    {
                                        "reason": "Test",
                                        "cancelledBy": "test"
                                    }
                                    """))
                    .andExpect(status().isConflict())
                    .andExpect(jsonPath("$.errorCode").value("INVALID_ORDER_STATE"));
        }

        @Test
        @DisplayName("should return 400 for invalid cancel request")
        void shouldReturn400ForInvalidCancelRequest() throws Exception {
            mockMvc.perform(patch("/api/orders/order-123/cancel")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("""
                                    {
                                        "reason": "",
                                        "cancelledBy": ""
                                    }
                                    """))
                    .andExpect(status().isBadRequest());
        }
    }

    /**
     * Helper method to create a test order.
     */
    private Order createTestOrder(String orderId, String customerId, Order.Status status) {
        Order order = new Order();
        order.setOrderId(orderId);
        order.setCustomerId(customerId);
        order.setCustomerName("Test Customer");
        order.setShippingAddress("Test Address");
        order.setStatus(status);
        order.setSubtotal(new BigDecimal("20.00"));
        order.setTax(new BigDecimal("2.00"));
        order.setTotal(new BigDecimal("22.00"));
        return order;
    }
}
