package com.theyawns.ecommerce.order.controller;

import com.theyawns.framework.saga.SagaState;
import com.theyawns.framework.saga.SagaStateStore;
import com.theyawns.framework.saga.SagaStatus;
import com.theyawns.framework.saga.SagaStepRecord;
import com.theyawns.framework.saga.StepStatus;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.http.ResponseEntity;

import java.time.Duration;
import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

/**
 * Tests for {@link SagaController}.
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
@DisplayName("SagaController")
@ExtendWith(MockitoExtension.class)
class SagaControllerTest {

    @Mock
    private SagaStateStore sagaStateStore;

    private SagaController sagaController;

    @BeforeEach
    void setUp() {
        sagaController = new SagaController(sagaStateStore);
    }

    @Nested
    @DisplayName("GET /api/sagas/{sagaId}")
    class GetSagaTests {

        @Test
        @DisplayName("should return saga state when found")
        void shouldReturnSagaStateWhenFound() {
            SagaState saga = createTestSaga("saga-123", "OrderFulfillment", SagaStatus.COMPLETED);
            when(sagaStateStore.getSagaState("saga-123")).thenReturn(Optional.of(saga));

            ResponseEntity<Map<String, Object>> response = sagaController.getSaga("saga-123");

            assertEquals(200, response.getStatusCode().value());
            Map<String, Object> body = response.getBody();
            assertNotNull(body);
            assertEquals("saga-123", body.get("sagaId"));
            assertEquals("OrderFulfillment", body.get("sagaType"));
            assertEquals("COMPLETED", body.get("status"));
        }

        @Test
        @DisplayName("should return 404 when saga not found")
        void shouldReturn404WhenNotFound() {
            when(sagaStateStore.getSagaState("nonexistent")).thenReturn(Optional.empty());

            ResponseEntity<Map<String, Object>> response = sagaController.getSaga("nonexistent");

            assertEquals(404, response.getStatusCode().value());
        }

        @Test
        @DisplayName("should include step details in response")
        void shouldIncludeStepDetails() {
            SagaState saga = createTestSagaWithSteps("saga-456", "OrderFulfillment");
            when(sagaStateStore.getSagaState("saga-456")).thenReturn(Optional.of(saga));

            ResponseEntity<Map<String, Object>> response = sagaController.getSaga("saga-456");

            Map<String, Object> body = response.getBody();
            assertNotNull(body);
            @SuppressWarnings("unchecked")
            List<Map<String, Object>> steps = (List<Map<String, Object>>) body.get("steps");
            assertNotNull(steps);
            assertEquals(2, steps.size());
            assertEquals("OrderCreated", steps.get(0).get("eventType"));
            assertEquals("COMPLETED", steps.get(0).get("status"));
        }
    }

    @Nested
    @DisplayName("GET /api/sagas")
    class ListSagasTests {

        @Test
        @DisplayName("should list sagas filtered by status")
        void shouldListSagasByStatus() {
            List<SagaState> sagas = List.of(
                    createTestSaga("saga-1", "OrderFulfillment", SagaStatus.COMPLETED),
                    createTestSaga("saga-2", "OrderFulfillment", SagaStatus.COMPLETED)
            );
            when(sagaStateStore.findSagasByStatus(SagaStatus.COMPLETED)).thenReturn(sagas);

            ResponseEntity<List<Map<String, Object>>> response =
                    sagaController.listSagas("COMPLETED", 10);

            assertEquals(200, response.getStatusCode().value());
            List<Map<String, Object>> body = response.getBody();
            assertNotNull(body);
            assertEquals(2, body.size());
            verify(sagaStateStore).findSagasByStatus(SagaStatus.COMPLETED);
        }

        @Test
        @DisplayName("should respect limit parameter")
        void shouldRespectLimit() {
            List<SagaState> sagas = List.of(
                    createTestSaga("saga-1", "OrderFulfillment", SagaStatus.FAILED),
                    createTestSaga("saga-2", "OrderFulfillment", SagaStatus.FAILED),
                    createTestSaga("saga-3", "OrderFulfillment", SagaStatus.FAILED)
            );
            when(sagaStateStore.findSagasByStatus(SagaStatus.FAILED)).thenReturn(sagas);

            ResponseEntity<List<Map<String, Object>>> response =
                    sagaController.listSagas("FAILED", 2);

            List<Map<String, Object>> body = response.getBody();
            assertNotNull(body);
            assertEquals(2, body.size());
        }

        @Test
        @DisplayName("should return 400 for invalid status")
        void shouldReturn400ForInvalidStatus() {
            ResponseEntity<List<Map<String, Object>>> response =
                    sagaController.listSagas("INVALID_STATUS", 10);

            assertEquals(400, response.getStatusCode().value());
            List<Map<String, Object>> body = response.getBody();
            assertNotNull(body);
            assertTrue(body.get(0).containsKey("error"));
        }

        @Test
        @DisplayName("should handle case-insensitive status")
        void shouldHandleCaseInsensitiveStatus() {
            when(sagaStateStore.findSagasByStatus(SagaStatus.FAILED)).thenReturn(List.of());

            ResponseEntity<List<Map<String, Object>>> response =
                    sagaController.listSagas("failed", 10);

            assertEquals(200, response.getStatusCode().value());
            verify(sagaStateStore).findSagasByStatus(SagaStatus.FAILED);
        }
    }

    /**
     * Helper to create a test saga state.
     */
    private SagaState createTestSaga(String sagaId, String sagaType, SagaStatus status) {
        return SagaState.builder()
                .sagaId(sagaId)
                .sagaType(sagaType)
                .status(status)
                .startedAt(Instant.now().minusSeconds(5))
                .completedAt(status.isTerminal() ? Instant.now() : null)
                .currentStep(status == SagaStatus.COMPLETED ? 4 : 2)
                .totalSteps(4)
                .deadline(Instant.now().plusSeconds(25))
                .failedAtStep(-1)
                .build();
    }

    /**
     * Helper to create a test saga with step records.
     */
    private SagaState createTestSagaWithSteps(String sagaId, String sagaType) {
        List<SagaStepRecord> steps = List.of(
                SagaStepRecord.builder()
                        .stepNumber(0)
                        .stepName("OrderCreated")
                        .service("order-service")
                        .eventType("OrderCreated")
                        .status(StepStatus.COMPLETED)
                        .eventId("evt-1")
                        .build(),
                SagaStepRecord.builder()
                        .stepNumber(1)
                        .stepName("StockReserved")
                        .service("inventory-service")
                        .eventType("StockReserved")
                        .status(StepStatus.COMPLETED)
                        .eventId("evt-2")
                        .build()
        );

        return SagaState.builder()
                .sagaId(sagaId)
                .sagaType(sagaType)
                .status(SagaStatus.IN_PROGRESS)
                .startedAt(Instant.now().minusSeconds(3))
                .currentStep(2)
                .totalSteps(4)
                .steps(steps)
                .deadline(Instant.now().plusSeconds(27))
                .failedAtStep(-1)
                .build();
    }
}
