package com.theyawns.framework.edition;

import com.hazelcast.config.Config;
import com.hazelcast.core.HazelcastInstance;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

/**
 * Tests for {@link EditionDetector}.
 *
 * <p>Tests detection logic with mocked HazelcastInstance. Uses the absence
 * of the HZ_LICENSEKEY environment variable (which is not set in test
 * environments) to test Community Edition paths.
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
@DisplayName("EditionDetector - Edition detection logic")
class EditionDetectorTest {

    private HazelcastInstance mockHazelcast;
    private EditionProperties properties;

    @BeforeEach
    void setUp() {
        mockHazelcast = mock(HazelcastInstance.class);
        properties = new EditionProperties();

        // Use real Config (not mockable on Java 25 with Mockito inline)
        final Config config = new Config();
        when(mockHazelcast.getConfig()).thenReturn(config);
    }

    @Nested
    @DisplayName("Community Edition detection")
    class CommunityEdition {

        @Test
        @DisplayName("should detect Community when mode is community")
        void shouldDetectCommunityWhenModeIsCommunity() {
            properties.getEdition().setMode("community");

            final EditionDetector detector = new EditionDetector(properties, mockHazelcast);
            detector.detectEdition();

            assertThat(detector.getEdition()).isEqualTo(EditionDetector.Edition.COMMUNITY);
            assertThat(detector.isCommunity()).isTrue();
            assertThat(detector.isEnterprise()).isFalse();
        }

        @Test
        @DisplayName("should detect Community when mode is auto and no license")
        void shouldDetectCommunityWhenAutoAndNoLicense() {
            properties.getEdition().setMode("auto");
            // Use a non-existent env var to guarantee no license
            properties.getLicense().setEnvVar("NONEXISTENT_TEST_LICENSE_VAR_12345");

            final EditionDetector detector = new EditionDetector(properties, mockHazelcast);
            detector.detectEdition();

            assertThat(detector.getEdition()).isEqualTo(EditionDetector.Edition.COMMUNITY);
            assertThat(detector.isCommunity()).isTrue();
            assertThat(detector.isLicensePresent()).isFalse();
        }

        @Test
        @DisplayName("should have no available features for Community Edition")
        void shouldHaveNoFeaturesForCommunity() {
            properties.getEdition().setMode("community");

            final EditionDetector detector = new EditionDetector(properties, mockHazelcast);
            detector.detectEdition();

            assertThat(detector.getAvailableFeatures()).isEmpty();
            assertThat(detector.isFeatureAvailable(EditionDetector.EnterpriseFeature.VECTOR_STORE))
                    .isFalse();
            assertThat(detector.isFeatureAvailable(EditionDetector.EnterpriseFeature.CP_SUBSYSTEM))
                    .isFalse();
        }
    }

    @Nested
    @DisplayName("Enterprise Edition detection")
    class EnterpriseEdition {

        @Test
        @DisplayName("should detect Enterprise when mode is enterprise (even without license, with warn)")
        void shouldDetectEnterpriseWhenModeIsEnterprise() {
            properties.getEdition().setMode("enterprise");
            properties.getLicense().setMissingBehavior("warn");
            properties.getLicense().setEnvVar("NONEXISTENT_TEST_LICENSE_VAR_12345");

            final EditionDetector detector = new EditionDetector(properties, mockHazelcast);
            detector.detectEdition();

            // Enterprise mode is set even without license (warn behavior just logs)
            assertThat(detector.getEdition()).isEqualTo(EditionDetector.Edition.ENTERPRISE);
            assertThat(detector.isEnterprise()).isTrue();
        }

        @Test
        @DisplayName("should throw when mode is enterprise, no license, and missing-behavior=fail")
        void shouldThrowWhenEnterpriseNoLicenseAndFail() {
            properties.getEdition().setMode("enterprise");
            properties.getLicense().setMissingBehavior("fail");
            properties.getLicense().setEnvVar("NONEXISTENT_TEST_LICENSE_VAR_12345");

            final EditionDetector detector = new EditionDetector(properties, mockHazelcast);

            assertThatThrownBy(detector::detectEdition)
                    .isInstanceOf(EditionConfigurationException.class)
                    .hasMessageContaining("Enterprise Edition requested but license not found")
                    .hasMessageContaining("NONEXISTENT_TEST_LICENSE_VAR_12345");
        }

        @Test
        @DisplayName("should not throw when mode is enterprise, no license, and missing-behavior=silent")
        void shouldNotThrowWhenEnterpriseSilent() {
            properties.getEdition().setMode("enterprise");
            properties.getLicense().setMissingBehavior("silent");
            properties.getLicense().setEnvVar("NONEXISTENT_TEST_LICENSE_VAR_12345");

            final EditionDetector detector = new EditionDetector(properties, mockHazelcast);
            detector.detectEdition();

            assertThat(detector.getEdition()).isEqualTo(EditionDetector.Edition.ENTERPRISE);
        }
    }

    @Nested
    @DisplayName("Unknown mode handling")
    class UnknownMode {

        @Test
        @DisplayName("should fall back to auto behavior for unknown mode")
        void shouldFallBackToAutoForUnknownMode() {
            properties.getEdition().setMode("bogus");
            properties.getLicense().setEnvVar("NONEXISTENT_TEST_LICENSE_VAR_12345");

            final EditionDetector detector = new EditionDetector(properties, mockHazelcast);
            detector.detectEdition();

            // No license present, so auto -> community
            assertThat(detector.getEdition()).isEqualTo(EditionDetector.Edition.COMMUNITY);
        }
    }

    @Nested
    @DisplayName("EnterpriseFeature enum")
    class EnterpriseFeatureEnum {

        @Test
        @DisplayName("should have correct display names and descriptions")
        void shouldHaveCorrectDisplayNamesAndDescriptions() {
            assertThat(EditionDetector.EnterpriseFeature.VECTOR_STORE.getDisplayName())
                    .isEqualTo("Vector Store");
            assertThat(EditionDetector.EnterpriseFeature.VECTOR_STORE.getDescription())
                    .isEqualTo("Similarity search for recommendations");

            assertThat(EditionDetector.EnterpriseFeature.CP_SUBSYSTEM.getDisplayName())
                    .isEqualTo("CP Subsystem");
            assertThat(EditionDetector.EnterpriseFeature.CP_SUBSYSTEM.getDescription())
                    .isEqualTo("Strong consistency primitives");
        }

        @Test
        @DisplayName("should have all expected features")
        void shouldHaveAllExpectedFeatures() {
            assertThat(EditionDetector.EnterpriseFeature.values()).hasSize(7);
        }

        @Test
        @DisplayName("should have correct TPC metadata")
        void shouldHaveCorrectTpcMetadata() {
            assertThat(EditionDetector.EnterpriseFeature.THREAD_PER_CORE.getDisplayName())
                    .isEqualTo("Thread-Per-Core");
            assertThat(EditionDetector.EnterpriseFeature.THREAD_PER_CORE.getDescription())
                    .isEqualTo("High-throughput thread-per-core networking");
        }
    }

    @Nested
    @DisplayName("Logging control")
    class LoggingControl {

        @Test
        @DisplayName("should detect edition even when logging is disabled")
        void shouldDetectEditionWhenLoggingDisabled() {
            properties.getEdition().setMode("community");
            properties.getObservability().setLogEditionStatus(false);
            properties.getObservability().setLogFeatureStatus(false);

            final EditionDetector detector = new EditionDetector(properties, mockHazelcast);
            detector.detectEdition();

            assertThat(detector.getEdition()).isEqualTo(EditionDetector.Edition.COMMUNITY);
        }
    }
}
