package com.theyawns.ecommerce.order.service;

import com.hazelcast.config.Config;
import com.hazelcast.config.EventJournalConfig;
import com.hazelcast.config.MapConfig;
import com.hazelcast.core.Hazelcast;
import com.hazelcast.core.HazelcastInstance;
import com.theyawns.ecommerce.common.domain.Order;
import com.theyawns.ecommerce.common.dto.OrderDTO;
import com.theyawns.ecommerce.common.dto.OrderLineItemDTO;
import com.theyawns.ecommerce.order.domain.OrderViewUpdater;
import com.theyawns.framework.controller.EventSourcingController;
import com.theyawns.framework.event.DomainEvent;
import com.theyawns.framework.saga.SagaStateStore;
import com.theyawns.framework.store.HazelcastEventStore;
import com.theyawns.framework.view.HazelcastViewStore;
import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.simple.SimpleMeterRegistry;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestInstance;

import java.math.BigDecimal;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.mockito.Mockito.mock;

/**
 * Tests for business metrics recording in OrderService.
 *
 * <p>Verifies that order.revenue, order.items.count, and order.items.quantity
 * counters are incremented correctly when orders are created.
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
@DisplayName("OrderService - Business Metrics")
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
class OrderServiceBusinessMetricsTest {

    private static final String DOMAIN_NAME = "OrderMetricsTest";

    private HazelcastInstance hazelcast;
    private SimpleMeterRegistry meterRegistry;
    private OrderService orderService;
    private EventSourcingController<Order, String, DomainEvent<Order, String>> controller;

    @BeforeAll
    void setUpHazelcast() {
        Config config = new Config();
        config.setClusterName("order-metrics-test-" + System.currentTimeMillis());
        config.getNetworkConfig().getJoin().getMulticastConfig().setEnabled(false);
        config.getNetworkConfig().getJoin().getAutoDetectionConfig().setEnabled(false);
        config.getJetConfig().setEnabled(true);
        config.getJetConfig().setResourceUploadEnabled(true);

        config.addMapConfig(new MapConfig(DOMAIN_NAME + "_PENDING")
                .setEventJournalConfig(new EventJournalConfig()
                        .setEnabled(true)
                        .setCapacity(10000)));

        hazelcast = Hazelcast.newHazelcastInstance(config);
    }

    @AfterAll
    void tearDownHazelcast() {
        if (controller != null && controller.isRunning()) {
            controller.stop();
        }
        if (hazelcast != null) {
            hazelcast.shutdown();
        }
    }

    @BeforeEach
    void setUp() {
        meterRegistry = new SimpleMeterRegistry();

        HazelcastEventStore<Order, String, DomainEvent<Order, String>> eventStore =
                new HazelcastEventStore<>(hazelcast, DOMAIN_NAME);
        HazelcastViewStore<String> viewStore = new HazelcastViewStore<>(hazelcast, DOMAIN_NAME);
        OrderViewUpdater viewUpdater = new OrderViewUpdater(viewStore);

        controller = EventSourcingController.<Order, String, DomainEvent<Order, String>>builder()
                .hazelcast(hazelcast)
                .domainName(DOMAIN_NAME)
                .eventStore(eventStore)
                .viewUpdater(viewUpdater)
                .viewUpdaterClass(OrderViewUpdater.class)
                .meterRegistry(meterRegistry)
                .build();
        controller.start();

        // SagaStateStore is an interface — safe to mock on Java 25
        SagaStateStore sagaStateStore = mock(SagaStateStore.class);

        // productAvailabilityViewStore — use a real one (won't have data, but prices are in DTO)
        HazelcastViewStore<String> productViewStore = new HazelcastViewStore<>(hazelcast, "ProductAvailability");

        orderService = new OrderService(controller, hazelcast, sagaStateStore, productViewStore, meterRegistry);
    }

    @Nested
    @DisplayName("Revenue metrics")
    class RevenueMetricsTests {

        @Test
        @DisplayName("should record revenue from order line items")
        void shouldRecordRevenue() throws Exception {
            // Arrange
            OrderDTO dto = createOrderDTO(
                    List.of(
                            createLineItemDTO("prod-1", "Widget", "WDG-001", 2, new BigDecimal("29.99")),
                            createLineItemDTO("prod-2", "Gadget", "GDG-001", 1, new BigDecimal("49.99"))
                    )
            );

            // Act
            orderService.createOrder(dto).get();

            // Assert — revenue = (2 * 29.99) + (1 * 49.99) = 109.97
            Counter revenueCounter = meterRegistry.find("order.revenue").counter();
            assertNotNull(revenueCounter, "order.revenue counter should be registered");
            assertEquals(109.97, revenueCounter.count(), 0.01, "Revenue should match sum of (price * qty)");
        }

        @Test
        @DisplayName("should accumulate revenue across multiple orders")
        void shouldAccumulateRevenue() throws Exception {
            // Arrange
            OrderDTO dto1 = createOrderDTO(
                    List.of(createLineItemDTO("prod-1", "Widget", "WDG-001", 1, new BigDecimal("10.00")))
            );
            OrderDTO dto2 = createOrderDTO(
                    List.of(createLineItemDTO("prod-2", "Gadget", "GDG-001", 3, new BigDecimal("20.00")))
            );

            // Act
            orderService.createOrder(dto1).get();
            orderService.createOrder(dto2).get();

            // Assert — revenue = 10.00 + 60.00 = 70.00
            Counter revenueCounter = meterRegistry.find("order.revenue").counter();
            assertNotNull(revenueCounter);
            assertEquals(70.00, revenueCounter.count(), 0.01);
        }
    }

    @Nested
    @DisplayName("Item count metrics")
    class ItemCountMetricsTests {

        @Test
        @DisplayName("should record line item count")
        void shouldRecordLineItemCount() throws Exception {
            // Arrange
            OrderDTO dto = createOrderDTO(
                    List.of(
                            createLineItemDTO("prod-1", "Widget", "WDG-001", 2, new BigDecimal("10.00")),
                            createLineItemDTO("prod-2", "Gadget", "GDG-001", 1, new BigDecimal("20.00")),
                            createLineItemDTO("prod-3", "Doohickey", "DHK-001", 5, new BigDecimal("5.00"))
                    )
            );

            // Act
            orderService.createOrder(dto).get();

            // Assert — 3 line items
            Counter itemCountCounter = meterRegistry.find("order.items.count").counter();
            assertNotNull(itemCountCounter, "order.items.count counter should be registered");
            assertEquals(3.0, itemCountCounter.count(), 0.01, "Should count number of line items");
        }

        @Test
        @DisplayName("should record total quantity across line items")
        void shouldRecordTotalQuantity() throws Exception {
            // Arrange
            OrderDTO dto = createOrderDTO(
                    List.of(
                            createLineItemDTO("prod-1", "Widget", "WDG-001", 2, new BigDecimal("10.00")),
                            createLineItemDTO("prod-2", "Gadget", "GDG-001", 1, new BigDecimal("20.00")),
                            createLineItemDTO("prod-3", "Doohickey", "DHK-001", 5, new BigDecimal("5.00"))
                    )
            );

            // Act
            orderService.createOrder(dto).get();

            // Assert — total quantity = 2 + 1 + 5 = 8
            Counter quantityCounter = meterRegistry.find("order.items.quantity").counter();
            assertNotNull(quantityCounter, "order.items.quantity counter should be registered");
            assertEquals(8.0, quantityCounter.count(), 0.01, "Should count total quantity across all items");
        }
    }

    @Nested
    @DisplayName("Orchestrated order metrics")
    class OrchestratedOrderMetricsTests {

        @Test
        @DisplayName("should record metrics for orchestrated orders too")
        void shouldRecordMetricsForOrchestratedOrders() throws Exception {
            // Arrange
            OrderDTO dto = createOrderDTO(
                    List.of(
                            createLineItemDTO("prod-1", "Widget", "WDG-001", 4, new BigDecimal("25.00"))
                    )
            );

            // Act
            orderService.createOrderPlain(dto).get();

            // Assert
            Counter revenueCounter = meterRegistry.find("order.revenue").counter();
            assertNotNull(revenueCounter);
            assertEquals(100.00, revenueCounter.count(), 0.01, "Revenue = 4 * 25.00");

            Counter itemCountCounter = meterRegistry.find("order.items.count").counter();
            assertNotNull(itemCountCounter);
            assertEquals(1.0, itemCountCounter.count(), 0.01, "1 line item");

            Counter quantityCounter = meterRegistry.find("order.items.quantity").counter();
            assertNotNull(quantityCounter);
            assertEquals(4.0, quantityCounter.count(), 0.01, "Quantity = 4");
        }
    }

    // --- Helper methods ---

    private OrderDTO createOrderDTO(List<OrderLineItemDTO> lineItems) {
        OrderDTO dto = new OrderDTO();
        dto.setCustomerId("customer-" + System.nanoTime());
        dto.setCustomerName("Test Customer");
        dto.setCustomerEmail("test@example.com");
        dto.setShippingAddress("123 Test St");
        dto.setLineItems(lineItems);
        return dto;
    }

    private OrderLineItemDTO createLineItemDTO(
            String productId, String productName, String sku,
            int quantity, BigDecimal unitPrice) {
        OrderLineItemDTO dto = new OrderLineItemDTO();
        dto.setProductId(productId);
        dto.setProductName(productName);
        dto.setSku(sku);
        dto.setQuantity(quantity);
        dto.setUnitPrice(unitPrice);
        return dto;
    }
}
