package com.theyawns.framework.tracing;

import com.theyawns.framework.event.DomainEvent;
import io.micrometer.tracing.Span;
import io.micrometer.tracing.Tracer;
import io.micrometer.tracing.test.simple.SimpleSpan;
import io.micrometer.tracing.test.simple.SimpleTracer;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Unit tests for {@link EventSpanDecorator}.
 *
 * <p>Uses Micrometer's SimpleTracer for in-memory span verification
 * without requiring an actual tracing backend.
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
@DisplayName("EventSpanDecorator - Distributed tracing span creation")
class EventSpanDecoratorTest {

    private SimpleTracer simpleTracer;
    private EventSpanDecorator decorator;

    @BeforeEach
    void setUp() {
        simpleTracer = new SimpleTracer();
        decorator = new EventSpanDecorator(simpleTracer);
    }

    @Test
    @DisplayName("should create event span with event attributes")
    void shouldCreateEventSpanWithAttributes() {
        // Arrange
        TestEvent event = new TestEvent("key-1");
        event.setEventType("CustomerCreated");
        event.setSource("account-service");
        event.setCorrelationId("corr-123");

        // Act
        Span span = decorator.startEventSpan(event);
        decorator.endSpan(span);

        // Assert
        assertNotNull(span);
        SimpleSpan simpleSpan = simpleTracer.lastSpan();
        assertNotNull(simpleSpan);
        assertEquals("handle-event", simpleSpan.getName());
        assertEquals("CustomerCreated", simpleSpan.getTags().get("event.type"));
        assertEquals("account-service", simpleSpan.getTags().get("event.source"));
        assertEquals("corr-123", simpleSpan.getTags().get("correlation.id"));
    }

    @Test
    @DisplayName("should create event span with saga attributes")
    void shouldCreateEventSpanWithSagaAttributes() {
        // Arrange
        TestEvent event = new TestEvent("key-1");
        event.setEventType("OrderCreated");
        event.setCorrelationId("corr-456");
        event.setSagaId("saga-789");
        event.setSagaType("OrderFulfillment");
        event.setStepNumber(0);
        event.setIsCompensating(false);

        // Act
        Span span = decorator.startEventSpan(event);
        decorator.endSpan(span);

        // Assert
        SimpleSpan simpleSpan = simpleTracer.lastSpan();
        assertNotNull(simpleSpan);
        assertEquals("saga-789", simpleSpan.getTags().get("saga.id"));
        assertEquals("OrderFulfillment", simpleSpan.getTags().get("saga.type"));
        assertEquals("0", simpleSpan.getTags().get("saga.step"));
    }

    @Test
    @DisplayName("should create event span with compensating flag")
    void shouldCreateEventSpanWithCompensatingFlag() {
        // Arrange
        TestEvent event = new TestEvent("key-1");
        event.setEventType("StockReleased");
        event.setSagaId("saga-789");
        event.setSagaType("OrderFulfillment");
        event.setIsCompensating(true);

        // Act
        Span span = decorator.startEventSpan(event);
        decorator.endSpan(span);

        // Assert
        SimpleSpan simpleSpan = simpleTracer.lastSpan();
        assertEquals("true", simpleSpan.getTags().get("saga.compensating"));
    }

    @Test
    @DisplayName("should create pipeline span with stage name")
    void shouldCreatePipelineSpan() {
        // Act
        Span span = decorator.startPipelineSpan("persist", "CustomerCreated", "evt-123");
        decorator.endSpan(span);

        // Assert
        SimpleSpan simpleSpan = simpleTracer.lastSpan();
        assertNotNull(simpleSpan);
        assertEquals("pipeline-persist", simpleSpan.getName());
        assertEquals("persist", simpleSpan.getTags().get("pipeline.stage"));
        assertEquals("CustomerCreated", simpleSpan.getTags().get("event.type"));
        assertEquals("evt-123", simpleSpan.getTags().get("event.id"));
    }

    @Test
    @DisplayName("should create saga span with step attributes")
    void shouldCreateSagaSpan() {
        // Act
        Span span = decorator.startSagaSpan("StockReserved", "saga-001",
                "OrderFulfillment", 1);
        decorator.endSpan(span);

        // Assert
        SimpleSpan simpleSpan = simpleTracer.lastSpan();
        assertNotNull(simpleSpan);
        assertEquals("saga-StockReserved", simpleSpan.getName());
        assertEquals("saga-001", simpleSpan.getTags().get("saga.id"));
        assertEquals("OrderFulfillment", simpleSpan.getTags().get("saga.type"));
        assertEquals("1", simpleSpan.getTags().get("saga.step"));
        assertEquals("StockReserved", simpleSpan.getTags().get("event.type"));
    }

    @Test
    @DisplayName("should record error on span")
    void shouldRecordErrorOnSpan() {
        // Arrange
        Span span = decorator.startPipelineSpan("persist", "OrderCreated", "evt-456");
        RuntimeException error = new RuntimeException("persist failed");

        // Act
        decorator.recordError(span, error);
        decorator.endSpan(span);

        // Assert
        SimpleSpan simpleSpan = simpleTracer.lastSpan();
        assertNotNull(simpleSpan);
        assertNotNull(simpleSpan.getError());
        assertEquals("persist failed", simpleSpan.getError().getMessage());
    }

    @Test
    @DisplayName("should handle null span gracefully in endSpan")
    void shouldHandleNullSpanInEndSpan() {
        // Act & Assert - should not throw
        decorator.endSpan(null);
    }

    @Test
    @DisplayName("should handle null span gracefully in recordError")
    void shouldHandleNullSpanInRecordError() {
        // Act & Assert - should not throw
        decorator.recordError(null, new RuntimeException("test"));
    }

    @Test
    @DisplayName("should handle null event fields gracefully")
    void shouldHandleNullEventFieldsGracefully() {
        // Arrange
        TestEvent event = new TestEvent("key-1");
        // eventType, source, correlationId all null

        // Act
        Span span = decorator.startEventSpan(event);
        decorator.endSpan(span);

        // Assert
        SimpleSpan simpleSpan = simpleTracer.lastSpan();
        assertNotNull(simpleSpan);
        assertEquals("unknown", simpleSpan.getTags().get("event.type"));
        assertEquals("unknown", simpleSpan.getTags().get("event.source"));
    }

    @Test
    @DisplayName("should return tracer from getter")
    void shouldReturnTracer() {
        // Act
        Tracer tracer = decorator.getTracer();

        // Assert
        assertNotNull(tracer);
        assertTrue(tracer instanceof SimpleTracer);
    }

    /**
     * Minimal test event implementation for unit testing.
     */
    private static class TestEvent extends DomainEvent<TestDomainObject, String> {

        TestEvent(String key) {
            super(key);
        }

        @Override
        public com.hazelcast.nio.serialization.genericrecord.GenericRecord toGenericRecord() {
            return null;
        }

        @Override
        public com.hazelcast.nio.serialization.genericrecord.GenericRecord apply(
                com.hazelcast.nio.serialization.genericrecord.GenericRecord domainObjectRecord) {
            return domainObjectRecord;
        }

        @Override
        public String getSchemaName() {
            return "TestEvent";
        }
    }

    /**
     * Minimal test domain object for unit testing.
     */
    private static class TestDomainObject implements com.theyawns.framework.domain.DomainObject<String> {

        @Override
        public String getKey() {
            return "test";
        }

        @Override
        public com.hazelcast.nio.serialization.genericrecord.GenericRecord toGenericRecord() {
            return null;
        }

        @Override
        public String getSchemaName() {
            return "TestDomainObject";
        }
    }
}
