package com.theyawns.framework.edition;

import org.springframework.context.annotation.Conditional;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks a bean as the Community Edition fallback for an Enterprise feature.
 *
 * <p>The bean is created when the Enterprise feature is NOT available, either because:
 * <ul>
 *   <li>Community Edition is being used (no license), or</li>
 *   <li>The feature is explicitly disabled ({@code enabled: false})</li>
 * </ul>
 *
 * <p>Usage example:
 * <pre>{@code
 * @Service
 * @ConditionalOnCommunityFallback(EditionDetector.EnterpriseFeature.VECTOR_STORE)
 * public class NoOpVectorStoreService implements VectorStoreService {
 *     // Community fallback - returns empty results
 * }
 * }</pre>
 *
 * @author Generated by Claude Code
 * @since 2.0
 * @see ConditionalOnEnterpriseFeature
 * @see OnCommunityFallbackCondition
 */
@Target({ElementType.TYPE, ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Conditional(OnCommunityFallbackCondition.class)
public @interface ConditionalOnCommunityFallback {

    /**
     * The Enterprise feature this bean provides a fallback for.
     *
     * @return the enterprise feature
     */
    EditionDetector.EnterpriseFeature value();
}
