package com.theyawns.framework.edition;

import org.springframework.context.annotation.Conditional;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Marks a bean that requires a specific Enterprise feature.
 *
 * <p>The bean is only created if:
 * <ol>
 *   <li>Enterprise Edition is available (license key set), AND</li>
 *   <li>The specific feature is enabled in configuration (not set to {@code false})</li>
 * </ol>
 *
 * <p>If the feature's {@code enabled} property is set to {@code true} (required) but
 * Enterprise is not available, an {@link EditionConfigurationException} is thrown at startup.
 *
 * <p>Usage example:
 * <pre>{@code
 * @Service
 * @ConditionalOnEnterpriseFeature(EditionDetector.EnterpriseFeature.VECTOR_STORE)
 * public class HazelcastVectorStoreService implements VectorStoreService {
 *     // Enterprise implementation
 * }
 * }</pre>
 *
 * @author Generated by Claude Code
 * @since 2.0
 * @see ConditionalOnCommunityFallback
 * @see OnEnterpriseFeatureCondition
 */
@Target({ElementType.TYPE, ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Conditional(OnEnterpriseFeatureCondition.class)
public @interface ConditionalOnEnterpriseFeature {

    /**
     * The Enterprise feature required by this bean.
     *
     * @return the required enterprise feature
     */
    EditionDetector.EnterpriseFeature value();
}
