package com.theyawns.framework.edition;

import com.hazelcast.core.HazelcastInstance;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.autoconfigure.condition.ConditionalOnBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Auto-configuration for Hazelcast edition detection and feature management.
 *
 * <p>This configuration is enabled by default when a {@link HazelcastInstance} bean
 * is present. It provides:
 * <ul>
 *   <li>{@link EditionProperties} - Configuration properties bound from application.yml</li>
 *   <li>{@link EditionDetector} - Edition detection and feature availability service</li>
 *   <li>{@link EditionInfoContributor} - Actuator info endpoint contributor</li>
 * </ul>
 *
 * <p>Required dependencies:
 * <ul>
 *   <li>{@link HazelcastInstance} - For runtime feature detection</li>
 * </ul>
 *
 * @author Generated by Claude Code
 * @since 2.0
 * @see EditionProperties
 * @see EditionDetector
 * @see EditionInfoContributor
 */
@Configuration
@EnableConfigurationProperties(EditionProperties.class)
@ConditionalOnBean(HazelcastInstance.class)
public class EditionAutoConfiguration {

    private static final Logger logger = LoggerFactory.getLogger(EditionAutoConfiguration.class);

    /**
     * Creates the EditionDetector bean.
     *
     * @param properties the edition configuration properties
     * @param hazelcast the Hazelcast instance for runtime feature detection
     * @return the edition detector instance
     */
    @Bean
    @ConditionalOnMissingBean(EditionDetector.class)
    public EditionDetector editionDetector(
            EditionProperties properties,
            HazelcastInstance hazelcast) {
        logger.info("Creating EditionDetector bean (mode={})", properties.getMode());
        return new EditionDetector(properties, hazelcast);
    }

    /**
     * Creates the EditionInfoContributor bean for Actuator.
     *
     * <p>Only created when {@code framework.observability.expose-in-actuator} is true (default).
     *
     * @param editionDetector the edition detector
     * @param properties the edition properties
     * @return the info contributor instance
     */
    @Bean
    @ConditionalOnMissingBean(EditionInfoContributor.class)
    @ConditionalOnProperty(name = "framework.observability.expose-in-actuator",
            havingValue = "true", matchIfMissing = true)
    public EditionInfoContributor editionInfoContributor(
            EditionDetector editionDetector,
            EditionProperties properties) {
        logger.info("Creating EditionInfoContributor bean for /actuator/info");
        return new EditionInfoContributor(editionDetector, properties);
    }
}
