package com.theyawns.framework.edition;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.Condition;
import org.springframework.context.annotation.ConditionContext;
import org.springframework.core.type.AnnotatedTypeMetadata;

import java.util.Map;

/**
 * Spring {@link Condition} implementation for {@link ConditionalOnCommunityFallback}.
 *
 * <p>Inverse logic of {@link OnEnterpriseFeatureCondition}. The fallback bean is created when
 * the Enterprise feature is NOT available.
 *
 * <p>Logic:
 * <ul>
 *   <li>{@code enabled=false} -> match (feature disabled, use fallback)</li>
 *   <li>Enterprise not available -> match (no Enterprise, use fallback)</li>
 *   <li>Enterprise available + {@code enabled=auto} or {@code true} -> no match</li>
 * </ul>
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
class OnCommunityFallbackCondition implements Condition {

    private static final Logger logger = LoggerFactory.getLogger(OnCommunityFallbackCondition.class);

    @Override
    public boolean matches(ConditionContext context, AnnotatedTypeMetadata metadata) {
        final Map<String, Object> attrs = metadata.getAnnotationAttributes(
                ConditionalOnCommunityFallback.class.getName()
        );

        if (attrs == null) {
            return false;
        }

        final EditionDetector.EnterpriseFeature feature =
                (EditionDetector.EnterpriseFeature) attrs.get("value");

        // Derive property key from enum name: VECTOR_STORE -> framework.features.vector-store.enabled
        final String featureKey = feature.name().toLowerCase().replace("_", "-");
        final String enabledProp = "framework.features." + featureKey + ".enabled";
        final String enabled = context.getEnvironment().getProperty(enabledProp, "auto");

        if ("false".equalsIgnoreCase(enabled)) {
            logger.debug("Feature {} explicitly disabled, using Community fallback", feature.name());
            return true;
        }

        final boolean isEnterprise = OnEnterpriseFeatureCondition.isEnterpriseAvailable(context);

        if (!isEnterprise) {
            logger.debug("Enterprise not available for feature {}, using Community fallback",
                    feature.name());
            return true;
        }

        return false;
    }
}
