package com.theyawns.framework.edition;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.Condition;
import org.springframework.context.annotation.ConditionContext;
import org.springframework.core.type.AnnotatedTypeMetadata;

import java.util.Map;

/**
 * Spring {@link Condition} implementation for {@link ConditionalOnEnterpriseFeature}.
 *
 * <p>Evaluates at context startup (before beans are created) by reading configuration
 * properties and environment variables directly. Does not depend on {@link EditionDetector}
 * being initialized.
 *
 * <p>Logic:
 * <ul>
 *   <li>{@code enabled=false} -> no match (feature disabled)</li>
 *   <li>{@code enabled=true} + no Enterprise -> throw {@link EditionConfigurationException}</li>
 *   <li>{@code enabled=true} + Enterprise -> match</li>
 *   <li>{@code enabled=auto} + Enterprise -> match</li>
 *   <li>{@code enabled=auto} + no Enterprise -> no match</li>
 * </ul>
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
class OnEnterpriseFeatureCondition implements Condition {

    private static final Logger logger = LoggerFactory.getLogger(OnEnterpriseFeatureCondition.class);

    @Override
    public boolean matches(ConditionContext context, AnnotatedTypeMetadata metadata) {
        final Map<String, Object> attrs = metadata.getAnnotationAttributes(
                ConditionalOnEnterpriseFeature.class.getName()
        );

        if (attrs == null) {
            return false;
        }

        final EditionDetector.EnterpriseFeature feature =
                (EditionDetector.EnterpriseFeature) attrs.get("value");

        // Derive property key from enum name: VECTOR_STORE -> framework.features.vector-store.enabled
        final String featureKey = feature.name().toLowerCase().replace("_", "-");
        final String enabledProp = "framework.features." + featureKey + ".enabled";
        final String enabled = context.getEnvironment().getProperty(enabledProp, "auto");

        if ("false".equalsIgnoreCase(enabled)) {
            logger.debug("Feature {} explicitly disabled", feature.name());
            return false;
        }

        final boolean isEnterprise = isEnterpriseAvailable(context);

        if ("true".equalsIgnoreCase(enabled) && !isEnterprise) {
            final String licenseEnvVar = context.getEnvironment().getProperty(
                    "framework.edition.license.env-var", "HZ_LICENSEKEY"
            );
            throw new EditionConfigurationException(
                    String.format(
                            "Feature '%s' is set to 'true' (required) but Enterprise Edition " +
                            "is not available. Either set %s environment variable or change " +
                            "feature setting to 'auto' or 'false'.",
                            feature.name(), licenseEnvVar
                    )
            );
        }

        if (isEnterprise) {
            logger.debug("Feature {} enabled (Enterprise available)", feature.name());
        }

        return isEnterprise;
    }

    /**
     * Determines Enterprise availability from environment at condition evaluation time.
     */
    static boolean isEnterpriseAvailable(ConditionContext context) {
        final String licenseEnvVar = context.getEnvironment().getProperty(
                "framework.edition.license.env-var", "HZ_LICENSEKEY"
        );
        final String license = System.getenv(licenseEnvVar);
        final boolean licensePresent = license != null && !license.isBlank();

        final String mode = context.getEnvironment().getProperty(
                "framework.edition.mode", "auto"
        );

        return switch (mode.toLowerCase()) {
            case "enterprise" -> true;
            case "community" -> false;
            case "auto" -> licensePresent;
            default -> licensePresent;
        };
    }
}
