package com.theyawns.framework.saga.orchestrator;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * A {@link SagaOrchestratorListener} that logs all lifecycle events at INFO level.
 *
 * <p>Provides visibility into saga execution progress, step completions,
 * and compensation flows without requiring external monitoring infrastructure.
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
public class LoggingSagaOrchestratorListener implements SagaOrchestratorListener {

    private static final Logger logger = LoggerFactory.getLogger(LoggingSagaOrchestratorListener.class);

    @Override
    public void onSagaStarted(final String sagaId, final SagaDefinition definition, final SagaContext context) {
        logger.info("Saga started: sagaId={}, name={}, steps={}", sagaId, definition.getName(),
                definition.getStepCount());
    }

    @Override
    public void onStepStarted(final String sagaId, final String stepName, final int stepIndex) {
        logger.info("Step started: sagaId={}, step={}, index={}", sagaId, stepName, stepIndex);
    }

    @Override
    public void onStepCompleted(final String sagaId, final String stepName, final SagaStepResult result) {
        if (result.isSuccess()) {
            logger.info("Step completed successfully: sagaId={}, step={}", sagaId, stepName);
        } else {
            logger.info("Step completed with {}: sagaId={}, step={}, error={}",
                    result.getStatus(), sagaId, stepName,
                    result.getErrorMessage().orElse("unknown"));
        }
    }

    @Override
    public void onCompensationStarted(final String sagaId, final String failedStepName,
                                       final int stepsToCompensate) {
        logger.info("Compensation started: sagaId={}, failedStep={}, stepsToCompensate={}",
                sagaId, failedStepName, stepsToCompensate);
    }

    @Override
    public void onCompensationStepCompleted(final String sagaId, final String stepName,
                                             final SagaStepResult result) {
        if (result.isSuccess()) {
            logger.info("Compensation step completed: sagaId={}, step={}", sagaId, stepName);
        } else {
            logger.info("Compensation step failed: sagaId={}, step={}, error={}",
                    sagaId, stepName, result.getErrorMessage().orElse("unknown"));
        }
    }

    @Override
    public void onSagaCompleted(final String sagaId, final SagaOrchestratorResult result) {
        logger.info("Saga completed: sagaId={}, status={}, stepsCompleted={}, stepsCompensated={}",
                sagaId, result.getStatus(), result.getStepsCompleted(), result.getStepsCompensated());
    }
}
