package com.theyawns.framework.saga.orchestrator;

import java.util.concurrent.CompletableFuture;

/**
 * Functional interface for a saga step's forward action.
 *
 * <p>A saga action performs the primary operation for a step (e.g., reserving stock,
 * processing payment). The action receives a {@link SagaContext} containing data from
 * previous steps and returns a {@link CompletableFuture} that resolves to a
 * {@link SagaStepResult} indicating success or failure.
 *
 * <p>Example:
 * <pre>{@code
 * SagaAction reserveStock = context -> {
 *     String productId = context.get("productId", String.class);
 *     int quantity = context.get("quantity", Integer.class);
 *     return inventoryService.reserve(productId, quantity)
 *         .thenApply(reservationId -> SagaStepResult.success(
 *             Map.of("reservationId", reservationId)
 *         ));
 * };
 * }</pre>
 *
 * @author Generated by Claude Code
 * @since 3.0
 * @see SagaCompensation
 * @see SagaStep
 */
@FunctionalInterface
public interface SagaAction {

    /**
     * Executes the forward action for a saga step.
     *
     * @param context the saga context containing data from previous steps
     * @return a future resolving to the step result
     */
    CompletableFuture<SagaStepResult> execute(SagaContext context);
}
