package com.theyawns.framework.saga.orchestrator;

import java.util.Collections;
import java.util.Map;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Mutable, thread-safe key-value context for passing data between saga steps.
 *
 * <p>Each saga execution has its own {@code SagaContext} instance that steps use to
 * share data. For example, a "ReserveStock" step might store a reservation ID that
 * a subsequent "ProcessPayment" step needs:
 *
 * <pre>{@code
 * // In ReserveStock action:
 * context.put("reservationId", reservationId);
 *
 * // In ProcessPayment action:
 * String reservationId = context.get("reservationId", String.class);
 * }</pre>
 *
 * <p>The context is backed by a {@link ConcurrentHashMap}, making it safe for
 * concurrent access across async step executions.
 *
 * @author Generated by Claude Code
 * @since 3.0
 * @see SagaAction
 * @see SagaOrchestrator
 */
public final class SagaContext {

    /**
     * Thread-safe backing store for context data.
     */
    private final ConcurrentHashMap<String, Object> data;

    /**
     * Creates a new empty SagaContext.
     */
    public SagaContext() {
        this.data = new ConcurrentHashMap<>();
    }

    /**
     * Creates a SagaContext pre-populated with the given entries.
     *
     * @param initialData the initial data entries (must not be null)
     */
    private SagaContext(final Map<String, Object> initialData) {
        this.data = new ConcurrentHashMap<>(initialData);
    }

    /**
     * Creates a new empty SagaContext.
     *
     * @return a new empty context
     */
    public static SagaContext create() {
        return new SagaContext();
    }

    /**
     * Creates a SagaContext pre-populated with the given entries.
     *
     * @param initialData the initial data entries (must not be null)
     * @return a new context containing the initial data
     * @throws NullPointerException if initialData is null
     */
    public static SagaContext of(final Map<String, Object> initialData) {
        Objects.requireNonNull(initialData, "initialData must not be null");
        return new SagaContext(initialData);
    }

    /**
     * Retrieves a value by key.
     *
     * @param key the key to look up (must not be null)
     * @return the value, or null if not present
     * @throws NullPointerException if key is null
     */
    public Object get(final String key) {
        Objects.requireNonNull(key, "key must not be null");
        return data.get(key);
    }

    /**
     * Retrieves a value by key, cast to the specified type.
     *
     * @param key the key to look up (must not be null)
     * @param type the expected type class (must not be null)
     * @param <T> the expected type
     * @return the value cast to type T, or null if not present
     * @throws NullPointerException if key or type is null
     * @throws ClassCastException if the value cannot be cast to the given type
     */
    public <T> T get(final String key, final Class<T> type) {
        Objects.requireNonNull(key, "key must not be null");
        Objects.requireNonNull(type, "type must not be null");
        return type.cast(data.get(key));
    }

    /**
     * Retrieves a value by key, or returns the default if not present.
     *
     * @param key the key to look up (must not be null)
     * @param defaultValue the value to return if key is not present
     * @return the value, or defaultValue if not present
     * @throws NullPointerException if key is null
     */
    public Object getOrDefault(final String key, final Object defaultValue) {
        Objects.requireNonNull(key, "key must not be null");
        return data.getOrDefault(key, defaultValue);
    }

    /**
     * Stores a key-value pair in the context.
     *
     * @param key the key (must not be null)
     * @param value the value (must not be null)
     * @throws NullPointerException if key or value is null
     */
    public void put(final String key, final Object value) {
        Objects.requireNonNull(key, "key must not be null");
        Objects.requireNonNull(value, "value must not be null");
        data.put(key, value);
    }

    /**
     * Checks whether the context contains a given key.
     *
     * @param key the key to check (must not be null)
     * @return true if the key exists
     * @throws NullPointerException if key is null
     */
    public boolean containsKey(final String key) {
        Objects.requireNonNull(key, "key must not be null");
        return data.containsKey(key);
    }

    /**
     * Returns the number of entries in the context.
     *
     * @return the number of entries
     */
    public int size() {
        return data.size();
    }

    /**
     * Returns an unmodifiable view of the context data.
     *
     * @return unmodifiable map of all context entries
     */
    public Map<String, Object> asUnmodifiableMap() {
        return Collections.unmodifiableMap(data);
    }

    @Override
    public String toString() {
        return "SagaContext{data=" + data + "}";
    }
}
