package com.theyawns.framework.saga.orchestrator;

import java.time.Duration;
import java.util.Objects;
import java.util.Optional;

/**
 * Immutable definition of a single step within a saga.
 *
 * <p>A saga step has a forward {@link SagaAction} and an optional {@link SagaCompensation}.
 * Steps that are terminal (e.g., the last step in a saga with no side effects to undo) may
 * omit compensation using {@link Builder#noCompensation()}.
 *
 * <p>Steps support per-step timeouts and retry configuration:
 * <pre>{@code
 * SagaStep step = SagaStep.builder("ProcessPayment")
 *     .action(ctx -> paymentService.charge(ctx))
 *     .compensation(ctx -> paymentService.refund(ctx))
 *     .timeout(Duration.ofSeconds(30))
 *     .maxRetries(2)
 *     .retryDelay(Duration.ofMillis(1000))
 *     .build();
 * }</pre>
 *
 * @author Generated by Claude Code
 * @since 3.0
 * @see SagaAction
 * @see SagaCompensation
 * @see SagaDefinition
 */
public final class SagaStep {

    /** Default retry delay of 500 milliseconds. */
    private static final Duration DEFAULT_RETRY_DELAY = Duration.ofMillis(500);

    /** Default step timeout of 30 seconds. */
    private static final Duration DEFAULT_TIMEOUT = Duration.ofSeconds(30);

    /**
     * The unique name of this step within the saga.
     */
    private final String name;

    /**
     * The forward action to execute.
     */
    private final SagaAction action;

    /**
     * The compensation (rollback) action, or null if no compensation.
     */
    private final SagaCompensation compensation;

    /**
     * Maximum time allowed for this step to complete.
     */
    private final Duration timeout;

    /**
     * Maximum number of retry attempts (0 means no retries).
     */
    private final int maxRetries;

    /**
     * Delay between retry attempts.
     */
    private final Duration retryDelay;

    /**
     * Private constructor; use {@link #builder(String)}.
     */
    private SagaStep(final String name, final SagaAction action, final SagaCompensation compensation,
                     final Duration timeout, final int maxRetries, final Duration retryDelay) {
        this.name = name;
        this.action = action;
        this.compensation = compensation;
        this.timeout = timeout;
        this.maxRetries = maxRetries;
        this.retryDelay = retryDelay;
    }

    /**
     * Creates a new builder for a saga step.
     *
     * @param name the unique step name (must not be null or blank)
     * @return a new builder
     * @throws NullPointerException if name is null
     * @throws IllegalArgumentException if name is blank
     */
    public static Builder builder(final String name) {
        Objects.requireNonNull(name, "name must not be null");
        if (name.isBlank()) {
            throw new IllegalArgumentException("name must not be blank");
        }
        return new Builder(name);
    }

    /**
     * Returns the step name.
     *
     * @return the name
     */
    public String getName() {
        return name;
    }

    /**
     * Returns the forward action.
     *
     * @return the action
     */
    public SagaAction getAction() {
        return action;
    }

    /**
     * Returns the compensation action, if defined.
     *
     * @return optional compensation
     */
    public Optional<SagaCompensation> getCompensation() {
        return Optional.ofNullable(compensation);
    }

    /**
     * Returns true if this step has a compensation action.
     *
     * @return true if compensation is defined
     */
    public boolean hasCompensation() {
        return compensation != null;
    }

    /**
     * Returns the step timeout.
     *
     * @return the timeout duration
     */
    public Duration getTimeout() {
        return timeout;
    }

    /**
     * Returns the maximum number of retries.
     *
     * @return max retries (0 means no retries)
     */
    public int getMaxRetries() {
        return maxRetries;
    }

    /**
     * Returns the delay between retries.
     *
     * @return the retry delay
     */
    public Duration getRetryDelay() {
        return retryDelay;
    }

    @Override
    public boolean equals(final Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        final SagaStep sagaStep = (SagaStep) o;
        return Objects.equals(name, sagaStep.name);
    }

    @Override
    public int hashCode() {
        return Objects.hash(name);
    }

    @Override
    public String toString() {
        return "SagaStep{name='" + name + "'"
                + ", hasCompensation=" + (compensation != null)
                + ", timeout=" + timeout
                + ", maxRetries=" + maxRetries
                + "}";
    }

    /**
     * Builder for creating {@link SagaStep} instances.
     */
    public static final class Builder {

        private final String name;
        private SagaAction action;
        private SagaCompensation compensation;
        private Duration timeout = DEFAULT_TIMEOUT;
        private int maxRetries = 0;
        private Duration retryDelay = DEFAULT_RETRY_DELAY;

        private Builder(final String name) {
            this.name = name;
        }

        /**
         * Sets the forward action for this step.
         *
         * @param action the action (must not be null)
         * @return this builder
         * @throws NullPointerException if action is null
         */
        public Builder action(final SagaAction action) {
            this.action = Objects.requireNonNull(action, "action must not be null");
            return this;
        }

        /**
         * Sets the compensation (rollback) action for this step.
         *
         * @param compensation the compensation action (must not be null)
         * @return this builder
         * @throws NullPointerException if compensation is null
         */
        public Builder compensation(final SagaCompensation compensation) {
            this.compensation = Objects.requireNonNull(compensation, "compensation must not be null");
            return this;
        }

        /**
         * Explicitly marks this step as having no compensation.
         *
         * <p>This is a documentation aid — by default, steps have no compensation.
         * Calling this method makes the intent explicit.
         *
         * @return this builder
         */
        public Builder noCompensation() {
            this.compensation = null;
            return this;
        }

        /**
         * Sets the timeout for this step.
         *
         * @param timeout the timeout duration (must not be null, must be positive)
         * @return this builder
         * @throws NullPointerException if timeout is null
         * @throws IllegalArgumentException if timeout is zero or negative
         */
        public Builder timeout(final Duration timeout) {
            Objects.requireNonNull(timeout, "timeout must not be null");
            if (timeout.isZero() || timeout.isNegative()) {
                throw new IllegalArgumentException("timeout must be positive");
            }
            this.timeout = timeout;
            return this;
        }

        /**
         * Sets the maximum number of retry attempts for this step.
         *
         * @param maxRetries the max retries (must be non-negative)
         * @return this builder
         * @throws IllegalArgumentException if maxRetries is negative
         */
        public Builder maxRetries(final int maxRetries) {
            if (maxRetries < 0) {
                throw new IllegalArgumentException("maxRetries must be non-negative");
            }
            this.maxRetries = maxRetries;
            return this;
        }

        /**
         * Sets the delay between retry attempts.
         *
         * @param retryDelay the delay (must not be null, must be non-negative)
         * @return this builder
         * @throws NullPointerException if retryDelay is null
         * @throws IllegalArgumentException if retryDelay is negative
         */
        public Builder retryDelay(final Duration retryDelay) {
            Objects.requireNonNull(retryDelay, "retryDelay must not be null");
            if (retryDelay.isNegative()) {
                throw new IllegalArgumentException("retryDelay must be non-negative");
            }
            this.retryDelay = retryDelay;
            return this;
        }

        /**
         * Builds the immutable {@link SagaStep}.
         *
         * @return the saga step
         * @throws IllegalStateException if action is not set
         */
        public SagaStep build() {
            if (action == null) {
                throw new IllegalStateException("action must be set");
            }
            return new SagaStep(name, action, compensation, timeout, maxRetries, retryDelay);
        }
    }
}
