package com.theyawns.framework.saga.orchestrator;

import com.theyawns.framework.saga.SagaStatus;

import java.time.Duration;
import java.time.Instant;
import java.util.Objects;
import java.util.Optional;

/**
 * Immutable result of a completed saga orchestration.
 *
 * <p>Contains the final status, timing information, step completion counts, and
 * failure details. Use the static factory methods to create instances:
 * <pre>{@code
 * // Successful saga
 * SagaOrchestratorResult result = SagaOrchestratorResult.success(
 *     "saga-123", "OrderFulfillment", startTime, 3);
 *
 * // Compensated saga (rolled back after failure)
 * SagaOrchestratorResult result = SagaOrchestratorResult.compensated(
 *     "saga-123", "OrderFulfillment", startTime, 2, 2,
 *     "ProcessPayment", "Insufficient funds");
 * }</pre>
 *
 * <p>Reuses the existing {@link SagaStatus} enum for status representation.
 *
 * @author Generated by Claude Code
 * @since 3.0
 * @see SagaStatus
 * @see SagaOrchestrator
 */
public final class SagaOrchestratorResult {

    /**
     * The saga instance ID.
     */
    private final String sagaId;

    /**
     * The saga definition name.
     */
    private final String sagaName;

    /**
     * The final status of the saga.
     */
    private final SagaStatus status;

    /**
     * When the saga started.
     */
    private final Instant startedAt;

    /**
     * When the saga completed (success, compensation, failure, or timeout).
     */
    private final Instant completedAt;

    /**
     * Number of steps that completed successfully.
     */
    private final int stepsCompleted;

    /**
     * Number of steps that were compensated (rolled back).
     */
    private final int stepsCompensated;

    /**
     * The reason for failure, if applicable.
     */
    private final String failureReason;

    /**
     * The step name where failure occurred, if applicable.
     */
    private final String failedAtStep;

    /**
     * Private constructor; use static factory methods.
     */
    private SagaOrchestratorResult(final String sagaId, final String sagaName, final SagaStatus status,
                                   final Instant startedAt, final Instant completedAt,
                                   final int stepsCompleted, final int stepsCompensated,
                                   final String failureReason, final String failedAtStep) {
        this.sagaId = Objects.requireNonNull(sagaId, "sagaId must not be null");
        this.sagaName = Objects.requireNonNull(sagaName, "sagaName must not be null");
        this.status = Objects.requireNonNull(status, "status must not be null");
        this.startedAt = Objects.requireNonNull(startedAt, "startedAt must not be null");
        this.completedAt = Objects.requireNonNull(completedAt, "completedAt must not be null");
        this.stepsCompleted = stepsCompleted;
        this.stepsCompensated = stepsCompensated;
        this.failureReason = failureReason;
        this.failedAtStep = failedAtStep;
    }

    /**
     * Creates a result for a successfully completed saga.
     *
     * @param sagaId the saga instance ID
     * @param sagaName the saga definition name
     * @param startedAt when the saga started
     * @param stepsCompleted number of steps completed
     * @return a success result
     */
    public static SagaOrchestratorResult success(final String sagaId, final String sagaName,
                                                  final Instant startedAt, final int stepsCompleted) {
        return new SagaOrchestratorResult(sagaId, sagaName, SagaStatus.COMPLETED,
                startedAt, Instant.now(), stepsCompleted, 0, null, null);
    }

    /**
     * Creates a result for a saga that was compensated after a failure.
     *
     * @param sagaId the saga instance ID
     * @param sagaName the saga definition name
     * @param startedAt when the saga started
     * @param stepsCompleted number of steps that completed before failure
     * @param stepsCompensated number of steps that were compensated
     * @param failedAtStep the step where failure occurred
     * @param failureReason the reason for failure
     * @return a compensated result
     */
    public static SagaOrchestratorResult compensated(final String sagaId, final String sagaName,
                                                      final Instant startedAt, final int stepsCompleted,
                                                      final int stepsCompensated, final String failedAtStep,
                                                      final String failureReason) {
        return new SagaOrchestratorResult(sagaId, sagaName, SagaStatus.COMPENSATED,
                startedAt, Instant.now(), stepsCompleted, stepsCompensated, failureReason, failedAtStep);
    }

    /**
     * Creates a result for a saga that failed and could not be fully compensated.
     *
     * @param sagaId the saga instance ID
     * @param sagaName the saga definition name
     * @param startedAt when the saga started
     * @param stepsCompleted number of steps that completed before failure
     * @param stepsCompensated number of steps that were compensated
     * @param failedAtStep the step where failure occurred
     * @param failureReason the reason for failure
     * @return a failed result
     */
    public static SagaOrchestratorResult failed(final String sagaId, final String sagaName,
                                                 final Instant startedAt, final int stepsCompleted,
                                                 final int stepsCompensated, final String failedAtStep,
                                                 final String failureReason) {
        return new SagaOrchestratorResult(sagaId, sagaName, SagaStatus.FAILED,
                startedAt, Instant.now(), stepsCompleted, stepsCompensated, failureReason, failedAtStep);
    }

    /**
     * Creates a result for a saga that is still in progress.
     *
     * <p>Used by {@link SagaOrchestrator#getStatus(String)} to report the current
     * state of an active saga.
     *
     * @param sagaId the saga instance ID
     * @param sagaName the saga definition name
     * @param startedAt when the saga started
     * @param stepsCompleted number of steps completed so far
     * @return an in-progress result
     */
    public static SagaOrchestratorResult inProgress(final String sagaId, final String sagaName,
                                                      final Instant startedAt, final int stepsCompleted) {
        return new SagaOrchestratorResult(sagaId, sagaName, SagaStatus.IN_PROGRESS,
                startedAt, Instant.now(), stepsCompleted, 0, null, null);
    }

    /**
     * Creates a result for a saga that timed out.
     *
     * @param sagaId the saga instance ID
     * @param sagaName the saga definition name
     * @param startedAt when the saga started
     * @param stepsCompleted number of steps that completed before timeout
     * @param failedAtStep the step where timeout occurred (may be null)
     * @return a timed-out result
     */
    public static SagaOrchestratorResult timedOut(final String sagaId, final String sagaName,
                                                   final Instant startedAt, final int stepsCompleted,
                                                   final String failedAtStep) {
        return new SagaOrchestratorResult(sagaId, sagaName, SagaStatus.TIMED_OUT,
                startedAt, Instant.now(), stepsCompleted, 0, "Saga timed out", failedAtStep);
    }

    /**
     * Returns the saga instance ID.
     *
     * @return the saga ID
     */
    public String getSagaId() {
        return sagaId;
    }

    /**
     * Returns the saga definition name.
     *
     * @return the saga name
     */
    public String getSagaName() {
        return sagaName;
    }

    /**
     * Returns the final status.
     *
     * @return the status
     */
    public SagaStatus getStatus() {
        return status;
    }

    /**
     * Returns when the saga started.
     *
     * @return the start time
     */
    public Instant getStartedAt() {
        return startedAt;
    }

    /**
     * Returns when the saga completed.
     *
     * @return the completion time
     */
    public Instant getCompletedAt() {
        return completedAt;
    }

    /**
     * Returns the duration from start to completion.
     *
     * @return the elapsed duration
     */
    public Duration getDuration() {
        return Duration.between(startedAt, completedAt);
    }

    /**
     * Returns the number of steps that completed successfully.
     *
     * @return steps completed count
     */
    public int getStepsCompleted() {
        return stepsCompleted;
    }

    /**
     * Returns the number of steps that were compensated.
     *
     * @return steps compensated count
     */
    public int getStepsCompensated() {
        return stepsCompensated;
    }

    /**
     * Returns the failure reason, if applicable.
     *
     * @return optional failure reason
     */
    public Optional<String> getFailureReason() {
        return Optional.ofNullable(failureReason);
    }

    /**
     * Returns the step where failure occurred, if applicable.
     *
     * @return optional failed step name
     */
    public Optional<String> getFailedAtStep() {
        return Optional.ofNullable(failedAtStep);
    }

    /**
     * Returns true if the saga completed successfully.
     *
     * @return true if successful
     */
    public boolean isSuccessful() {
        return status == SagaStatus.COMPLETED;
    }

    /**
     * Returns true if the saga was compensated.
     *
     * @return true if compensated
     */
    public boolean isCompensated() {
        return status == SagaStatus.COMPENSATED;
    }

    /**
     * Returns true if the saga failed.
     *
     * @return true if failed
     */
    public boolean isFailed() {
        return status == SagaStatus.FAILED;
    }

    /**
     * Returns true if the saga timed out.
     *
     * @return true if timed out
     */
    public boolean isTimedOut() {
        return status == SagaStatus.TIMED_OUT;
    }

    @Override
    public String toString() {
        return "SagaOrchestratorResult{sagaId='" + sagaId + "'"
                + ", sagaName='" + sagaName + "'"
                + ", status=" + status
                + ", stepsCompleted=" + stepsCompleted
                + ", stepsCompensated=" + stepsCompensated
                + (failedAtStep != null ? ", failedAtStep='" + failedAtStep + "'" : "")
                + ", duration=" + getDuration()
                + "}";
    }
}
