package com.theyawns.framework.saga.orchestrator;

import java.util.Collections;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

/**
 * Immutable result of a saga step execution.
 *
 * <p>Each step action or compensation returns a {@code SagaStepResult} indicating
 * success, failure, or timeout. Successful results may carry data that downstream
 * steps need (e.g., a payment transaction ID).
 *
 * <p>Use the static factory methods to create results:
 * <pre>{@code
 * // Success with no data
 * return SagaStepResult.success();
 *
 * // Success with data for downstream steps
 * return SagaStepResult.success(Map.of("paymentId", txnId));
 *
 * // Failure with error message
 * return SagaStepResult.failure("Insufficient funds");
 *
 * // Timeout
 * return SagaStepResult.timeout("Payment gateway did not respond in time");
 * }</pre>
 *
 * @author Generated by Claude Code
 * @since 3.0
 * @see SagaAction
 * @see SagaCompensation
 */
public final class SagaStepResult {

    /**
     * The possible outcomes of a saga step.
     */
    public enum Status {
        /** Step completed successfully. */
        SUCCESS,
        /** Step failed. */
        FAILURE,
        /** Step timed out before completing. */
        TIMEOUT
    }

    /**
     * The outcome status.
     */
    private final Status status;

    /**
     * Optional data produced by a successful step.
     */
    private final Map<String, Object> data;

    /**
     * Optional error message for failure or timeout.
     */
    private final String errorMessage;

    /**
     * Private constructor; use static factory methods.
     *
     * @param status the outcome status
     * @param data optional data from a successful step
     * @param errorMessage optional error message
     */
    private SagaStepResult(final Status status, final Map<String, Object> data, final String errorMessage) {
        this.status = Objects.requireNonNull(status, "status must not be null");
        this.data = data != null ? Collections.unmodifiableMap(data) : Collections.emptyMap();
        this.errorMessage = errorMessage;
    }

    /**
     * Creates a successful result with no data.
     *
     * @return a success result
     */
    public static SagaStepResult success() {
        return new SagaStepResult(Status.SUCCESS, null, null);
    }

    /**
     * Creates a successful result carrying data for downstream steps.
     *
     * @param data the data to pass downstream (must not be null)
     * @return a success result with data
     * @throws NullPointerException if data is null
     */
    public static SagaStepResult success(final Map<String, Object> data) {
        Objects.requireNonNull(data, "data must not be null");
        return new SagaStepResult(Status.SUCCESS, data, null);
    }

    /**
     * Creates a failure result with an error message.
     *
     * @param errorMessage the error message (must not be null)
     * @return a failure result
     * @throws NullPointerException if errorMessage is null
     */
    public static SagaStepResult failure(final String errorMessage) {
        Objects.requireNonNull(errorMessage, "errorMessage must not be null");
        return new SagaStepResult(Status.FAILURE, null, errorMessage);
    }

    /**
     * Creates a timeout result with an error message.
     *
     * @param errorMessage the timeout description (must not be null)
     * @return a timeout result
     * @throws NullPointerException if errorMessage is null
     */
    public static SagaStepResult timeout(final String errorMessage) {
        Objects.requireNonNull(errorMessage, "errorMessage must not be null");
        return new SagaStepResult(Status.TIMEOUT, null, errorMessage);
    }

    /**
     * Returns the outcome status.
     *
     * @return the status
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Returns true if the step succeeded.
     *
     * @return true if SUCCESS
     */
    public boolean isSuccess() {
        return status == Status.SUCCESS;
    }

    /**
     * Returns true if the step failed.
     *
     * @return true if FAILURE
     */
    public boolean isFailure() {
        return status == Status.FAILURE;
    }

    /**
     * Returns true if the step timed out.
     *
     * @return true if TIMEOUT
     */
    public boolean isTimeout() {
        return status == Status.TIMEOUT;
    }

    /**
     * Returns the data produced by a successful step.
     *
     * @return unmodifiable map of data (empty if no data)
     */
    public Map<String, Object> getData() {
        return data;
    }

    /**
     * Returns the error message, if any.
     *
     * @return optional containing the error message, or empty for success
     */
    public Optional<String> getErrorMessage() {
        return Optional.ofNullable(errorMessage);
    }

    @Override
    public String toString() {
        return "SagaStepResult{status=" + status
                + (data.isEmpty() ? "" : ", data=" + data)
                + (errorMessage != null ? ", errorMessage='" + errorMessage + "'" : "")
                + "}";
    }
}
