package com.theyawns.ecommerce.mcp.config;

import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.stereotype.Component;

/**
 * Configuration properties for MCP server service URLs.
 *
 * <p>Maps to properties under the {@code mcp.services} prefix. Each property
 * holds the base URL for one of the eCommerce microservices.
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
@Component
@ConfigurationProperties(prefix = "mcp.services")
public class McpServerProperties {

    /**
     * Base URL for the Account Service (default: http://localhost:8081).
     */
    private String accountUrl = "http://localhost:8081";

    /**
     * Base URL for the Inventory Service (default: http://localhost:8082).
     */
    private String inventoryUrl = "http://localhost:8082";

    /**
     * Base URL for the Order Service (default: http://localhost:8083).
     */
    private String orderUrl = "http://localhost:8083";

    /**
     * Base URL for the Payment Service (default: http://localhost:8084).
     */
    private String paymentUrl = "http://localhost:8084";

    public String getAccountUrl() {
        return accountUrl;
    }

    public void setAccountUrl(String accountUrl) {
        this.accountUrl = accountUrl;
    }

    public String getInventoryUrl() {
        return inventoryUrl;
    }

    public void setInventoryUrl(String inventoryUrl) {
        this.inventoryUrl = inventoryUrl;
    }

    public String getOrderUrl() {
        return orderUrl;
    }

    public void setOrderUrl(String orderUrl) {
        this.orderUrl = orderUrl;
    }

    public String getPaymentUrl() {
        return paymentUrl;
    }

    public void setPaymentUrl(String paymentUrl) {
        this.paymentUrl = paymentUrl;
    }
}
