package com.theyawns.ecommerce.mcp.config;

import com.theyawns.ecommerce.mcp.tools.GetEventHistoryTool;
import com.theyawns.ecommerce.mcp.tools.QueryViewTool;
import com.theyawns.ecommerce.mcp.tools.SubmitEventTool;
import org.springframework.ai.tool.ToolCallbackProvider;
import org.springframework.ai.tool.method.MethodToolCallbackProvider;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Configuration for registering MCP tool callbacks.
 *
 * <p>Registers all MCP tools with the Spring AI MCP server so they are
 * exposed to AI assistants via the {@code tools/list} JSON-RPC method.
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
@Configuration
public class McpToolConfig {

    /**
     * Registers tool callbacks for the MCP server.
     *
     * @param queryView the query view tool
     * @param submitEvent the submit event tool
     * @param getEventHistory the event history tool
     * @return the tool callback provider
     */
    @Bean
    public ToolCallbackProvider mcpTools(QueryViewTool queryView,
                                         SubmitEventTool submitEvent,
                                         GetEventHistoryTool getEventHistory) {
        return MethodToolCallbackProvider.builder()
                .toolObjects(queryView, submitEvent, getEventHistory)
                .build();
    }
}
