package com.theyawns.ecommerce.order.saga.orchestrated;

import com.theyawns.ecommerce.common.domain.Order;
import com.theyawns.ecommerce.order.exception.GlobalExceptionHandler;
import com.theyawns.ecommerce.order.service.OrderOperations;
import com.theyawns.framework.saga.SagaStatus;
import com.theyawns.framework.saga.orchestrator.SagaContext;
import com.theyawns.framework.saga.orchestrator.SagaDefinition;
import com.theyawns.framework.saga.orchestrator.SagaOrchestrator;
import com.theyawns.framework.saga.orchestrator.SagaOrchestratorResult;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;

import java.time.Instant;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.asyncDispatch;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.request;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * Tests for {@link OrchestratedOrderController}.
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
@ExtendWith(MockitoExtension.class)
@DisplayName("OrchestratedOrderController - REST endpoints")
class OrchestratedOrderControllerTest {

    private MockMvc mockMvc;

    @Mock
    private SagaOrchestrator orchestrator;

    @Mock
    private OrderFulfillmentSagaFactory sagaFactory;

    @Mock
    private OrderOperations orderOps;

    @BeforeEach
    void setUp() {
        OrchestratedOrderController controller =
                new OrchestratedOrderController(orchestrator, sagaFactory, orderOps);
        mockMvc = MockMvcBuilders.standaloneSetup(controller)
                .setControllerAdvice(new GlobalExceptionHandler())
                .build();
    }

    @Nested
    @DisplayName("POST /api/orders/orchestrated")
    class CreateOrder {

        @Test
        @DisplayName("should return 201 on successful saga completion")
        void shouldReturn201OnSuccess() throws Exception {
            // Arrange
            SagaDefinition mockDef = SagaDefinition.builder()
                    .name("OrderFulfillment")
                    .step("Step1").action(ctx -> CompletableFuture.completedFuture(null))
                            .noCompensation().build()
                    .build();
            when(sagaFactory.create()).thenReturn(mockDef);

            SagaOrchestratorResult successResult = SagaOrchestratorResult.success(
                    "saga-1", "OrderFulfillment", Instant.now(), 4);

            // The orchestrator mock must populate "orderId" in the context,
            // because the real orchestrator would execute CreateOrder which sets it.
            when(orchestrator.start(anyString(), any(), any())).thenAnswer(invocation -> {
                SagaContext ctx = invocation.getArgument(2, SagaContext.class);
                ctx.put("orderId", "order-1");
                return CompletableFuture.completedFuture(successResult);
            });

            Order order = createTestOrder();
            when(orderOps.getOrder("order-1")).thenReturn(Optional.of(order));

            // Act
            MvcResult mvcResult = mockMvc.perform(post("/api/orders/orchestrated")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("""
                                    {
                                        "customerId": "cust-1",
                                        "lineItems": [
                                            {
                                                "productId": "prod-1",
                                                "productName": "Widget",
                                                "quantity": 2,
                                                "unitPrice": 29.99
                                            }
                                        ],
                                        "shippingAddress": "123 Main St"
                                    }
                                    """))
                    .andExpect(request().asyncStarted())
                    .andReturn();

            // Assert
            mockMvc.perform(asyncDispatch(mvcResult))
                    .andExpect(status().isCreated())
                    .andExpect(jsonPath("$.orderId").value("order-1"));

            verify(orchestrator).start(anyString(), any(SagaDefinition.class), any(SagaContext.class));
        }

        @Test
        @DisplayName("should return 409 on saga failure")
        void shouldReturn409OnFailure() throws Exception {
            // Arrange
            SagaDefinition mockDef = SagaDefinition.builder()
                    .name("OrderFulfillment")
                    .step("Step1").action(ctx -> CompletableFuture.completedFuture(null))
                            .noCompensation().build()
                    .build();
            when(sagaFactory.create()).thenReturn(mockDef);

            SagaOrchestratorResult failResult = SagaOrchestratorResult.compensated(
                    "saga-1", "OrderFulfillment", Instant.now(), 2, 2,
                    "ProcessPayment", "Insufficient funds");
            when(orchestrator.start(anyString(), any(), any()))
                    .thenReturn(CompletableFuture.completedFuture(failResult));

            // Act
            MvcResult mvcResult = mockMvc.perform(post("/api/orders/orchestrated")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("""
                                    {
                                        "customerId": "cust-1",
                                        "lineItems": [
                                            {
                                                "productId": "prod-1",
                                                "productName": "Widget",
                                                "quantity": 2,
                                                "unitPrice": 29.99
                                            }
                                        ],
                                        "shippingAddress": "123 Main St"
                                    }
                                    """))
                    .andExpect(request().asyncStarted())
                    .andReturn();

            // Assert
            mockMvc.perform(asyncDispatch(mvcResult))
                    .andExpect(status().isConflict());
        }
    }

    private Order createTestOrder() {
        Order order = new Order();
        order.setOrderId("order-1");
        order.setCustomerId("cust-1");
        order.setStatus(Order.Status.CONFIRMED);
        return order;
    }
}
