package com.theyawns.ecommerce.order.saga.orchestrated;

import com.theyawns.ecommerce.order.service.OrderOperations;
import com.theyawns.framework.saga.orchestrator.SagaDefinition;
import com.theyawns.framework.saga.orchestrator.SagaStep;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.time.Duration;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Tests for {@link OrderFulfillmentSagaFactory}.
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
@ExtendWith(MockitoExtension.class)
@DisplayName("OrderFulfillmentSagaFactory - Saga definition")
class OrderFulfillmentSagaFactoryTest {

    @Mock
    private OrderOperations orderOps;

    @Mock
    private SagaServiceClientOperations serviceClient;

    private OrderFulfillmentSagaFactory factory;

    @BeforeEach
    void setUp() {
        factory = new OrderFulfillmentSagaFactory(orderOps, serviceClient);
    }

    @Nested
    @DisplayName("Saga structure")
    class SagaStructure {

        @Test
        @DisplayName("should create saga with 4 steps")
        void shouldCreateSagaWith4Steps() {
            SagaDefinition definition = factory.create();

            assertThat(definition.getStepCount()).isEqualTo(4);
        }

        @Test
        @DisplayName("should have correct saga name")
        void shouldHaveCorrectSagaName() {
            SagaDefinition definition = factory.create();

            assertThat(definition.getName()).isEqualTo("OrderFulfillment");
        }

        @Test
        @DisplayName("should have correct step names in order")
        void shouldHaveCorrectStepNames() {
            SagaDefinition definition = factory.create();

            assertThat(definition.getStep(0).getName()).isEqualTo("CreateOrder");
            assertThat(definition.getStep(1).getName()).isEqualTo("ReserveStock");
            assertThat(definition.getStep(2).getName()).isEqualTo("ProcessPayment");
            assertThat(definition.getStep(3).getName()).isEqualTo("ConfirmOrder");
        }

        @Test
        @DisplayName("should have 60-second saga timeout")
        void shouldHave60SecondSagaTimeout() {
            SagaDefinition definition = factory.create();

            assertThat(definition.getSagaTimeout()).isPresent();
            assertThat(definition.getSagaTimeout().get()).isEqualTo(Duration.ofSeconds(60));
        }
    }

    @Nested
    @DisplayName("Step configuration")
    class StepConfiguration {

        @Test
        @DisplayName("steps 0-2 should have compensation")
        void shouldHaveCompensationForFirstThreeSteps() {
            SagaDefinition definition = factory.create();

            assertThat(definition.getStep(0).hasCompensation()).isTrue();
            assertThat(definition.getStep(1).hasCompensation()).isTrue();
            assertThat(definition.getStep(2).hasCompensation()).isTrue();
        }

        @Test
        @DisplayName("step 3 (ConfirmOrder) should have no compensation")
        void shouldHaveNoCompensationForFinalStep() {
            SagaDefinition definition = factory.create();

            assertThat(definition.getStep(3).hasCompensation()).isFalse();
        }

        @Test
        @DisplayName("steps 0-2 should have 15-second timeout")
        void shouldHave15SecondTimeoutForFirstThreeSteps() {
            SagaDefinition definition = factory.create();

            assertThat(definition.getStep(0).getTimeout()).isEqualTo(Duration.ofSeconds(15));
            assertThat(definition.getStep(1).getTimeout()).isEqualTo(Duration.ofSeconds(15));
            assertThat(definition.getStep(2).getTimeout()).isEqualTo(Duration.ofSeconds(15));
        }

        @Test
        @DisplayName("step 3 (ConfirmOrder) should have 10-second timeout")
        void shouldHave10SecondTimeoutForFinalStep() {
            SagaDefinition definition = factory.create();

            assertThat(definition.getStep(3).getTimeout()).isEqualTo(Duration.ofSeconds(10));
        }

        @Test
        @DisplayName("all steps should have actions")
        void allStepsShouldHaveActions() {
            SagaDefinition definition = factory.create();

            for (int i = 0; i < definition.getStepCount(); i++) {
                assertThat(definition.getStep(i).getAction()).isNotNull();
            }
        }
    }
}
