package com.theyawns.ecommerce.payment;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * Spring Boot application entry point for the Payment Service.
 *
 * <p>The Payment Service manages payment processing including:
 * <ul>
 *   <li>Payment processing (capture) for orders</li>
 *   <li>Payment refunds</li>
 *   <li>Payment status tracking</li>
 *   <li>Saga integration for order fulfillment</li>
 * </ul>
 *
 * <p>This service uses the event sourcing framework to:
 * <ul>
 *   <li>Publish domain events for all payment operations</li>
 *   <li>Maintain a materialized view for fast payment lookups</li>
 *   <li>Support event replay for view reconstruction</li>
 * </ul>
 *
 * <p>In the Order Fulfillment saga, this service handles step 2:
 * <ul>
 *   <li>Listens for StockReserved events to trigger payment</li>
 *   <li>Publishes PaymentProcessed or PaymentFailed events</li>
 *   <li>Handles PaymentRefundRequested for saga compensation</li>
 * </ul>
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
@SpringBootApplication(scanBasePackages = {
        "com.theyawns.ecommerce.payment",
        "com.theyawns.framework"
})
public class PaymentServiceApplication {

    /**
     * Main entry point for the Payment Service.
     *
     * @param args command line arguments
     */
    public static void main(String[] args) {
        SpringApplication.run(PaymentServiceApplication.class, args);
    }
}
