package com.theyawns.framework.dlq;

import com.hazelcast.core.HazelcastInstance;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.simple.SimpleMeterRegistry;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.springframework.boot.autoconfigure.AutoConfigurations;
import org.springframework.boot.test.context.runner.ApplicationContextRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.Mockito.mock;

/**
 * Tests for {@link DeadLetterQueueAutoConfiguration}.
 *
 * <p>Uses {@link ApplicationContextRunner} pattern to test auto-configuration
 * behavior without starting a full Spring context.
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
@DisplayName("DeadLetterQueueAutoConfiguration - Auto-configuration behavior")
class DeadLetterQueueAutoConfigurationTest {

    private final ApplicationContextRunner contextRunner = new ApplicationContextRunner()
            .withConfiguration(AutoConfigurations.of(DeadLetterQueueAutoConfiguration.class))
            .withPropertyValues(
                    "framework.edition.license.env-var=NONEXISTENT_TEST_LICENSE_VAR_12345");

    @Nested
    @DisplayName("Default configuration")
    class DefaultConfiguration {

        @Test
        @DisplayName("should create all beans by default when HazelcastInstance exists")
        void shouldCreateAllBeansByDefault() {
            contextRunner
                    .withUserConfiguration(HazelcastAndMeterConfig.class)
                    .run(context -> {
                        assertThat(context).hasSingleBean(DeadLetterQueueOperations.class);
                        assertThat(context).hasSingleBean(DeadLetterQueueController.class);
                        assertThat(context).hasSingleBean(DeadLetterQueueProperties.class);
                    });
        }

        @Test
        @DisplayName("should create beans when enabled property is not set (matchIfMissing)")
        void shouldCreateBeansWhenPropertyNotSet() {
            contextRunner
                    .withUserConfiguration(HazelcastAndMeterConfig.class)
                    .run(context -> {
                        assertThat(context).hasSingleBean(DeadLetterQueueOperations.class);
                    });
        }
    }

    @Nested
    @DisplayName("Disabled configuration")
    class DisabledConfiguration {

        @Test
        @DisplayName("should not create beans when framework.dlq.enabled is false")
        void shouldNotCreateBeansWhenDisabled() {
            contextRunner
                    .withUserConfiguration(HazelcastAndMeterConfig.class)
                    .withPropertyValues("framework.dlq.enabled=false")
                    .run(context -> {
                        assertThat(context).doesNotHaveBean(DeadLetterQueueOperations.class);
                        assertThat(context).doesNotHaveBean(DeadLetterQueueController.class);
                    });
        }
    }

    @Nested
    @DisplayName("Missing dependencies")
    class MissingDependencies {

        @Test
        @DisplayName("should not create beans when HazelcastInstance is absent")
        void shouldNotCreateBeansWhenHazelcastAbsent() {
            contextRunner
                    .withUserConfiguration(MeterRegistryOnlyConfig.class)
                    .run(context -> {
                        assertThat(context).doesNotHaveBean(DeadLetterQueueOperations.class);
                        assertThat(context).doesNotHaveBean(DeadLetterQueueController.class);
                    });
        }
    }

    @Nested
    @DisplayName("Property binding")
    class PropertyBinding {

        @Test
        @DisplayName("should bind DLQ properties from configuration")
        void shouldBindDlqProperties() {
            contextRunner
                    .withUserConfiguration(HazelcastAndMeterConfig.class)
                    .withPropertyValues(
                            "framework.dlq.map-name=custom_DLQ",
                            "framework.dlq.max-replay-attempts=5",
                            "framework.dlq.entry-ttl=24h"
                    )
                    .run(context -> {
                        DeadLetterQueueProperties props =
                                context.getBean(DeadLetterQueueProperties.class);
                        assertThat(props.getMapName()).isEqualTo("custom_DLQ");
                        assertThat(props.getMaxReplayAttempts()).isEqualTo(5);
                        assertThat(props.getEntryTtl().toHours()).isEqualTo(24);
                    });
        }
    }

    // ========== Test Configuration Classes ==========

    @Configuration
    static class HazelcastAndMeterConfig {

        @Bean
        HazelcastInstance hazelcastInstance() {
            return mock(HazelcastInstance.class);
        }

        @Bean
        MeterRegistry meterRegistry() {
            return new SimpleMeterRegistry();
        }
    }

    @Configuration
    static class MeterRegistryOnlyConfig {

        @Bean
        MeterRegistry meterRegistry() {
            return new SimpleMeterRegistry();
        }
    }
}
