package com.theyawns.framework.dlq;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.time.Duration;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Tests for {@link DeadLetterQueueProperties}.
 *
 * <p>Validates default values and property validation.
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
@DisplayName("DeadLetterQueueProperties - DLQ configuration properties")
class DeadLetterQueuePropertiesTest {

    private DeadLetterQueueProperties properties;

    @BeforeEach
    void setUp() {
        properties = new DeadLetterQueueProperties();
    }

    @Nested
    @DisplayName("Default values")
    class DefaultValues {

        @Test
        @DisplayName("should default enabled to true")
        void shouldDefaultEnabledToTrue() {
            // Assert
            assertThat(properties.isEnabled()).isTrue();
        }

        @Test
        @DisplayName("should default mapName to framework_DLQ")
        void shouldDefaultMapNameToFrameworkDlq() {
            // Assert
            assertThat(properties.getMapName()).isEqualTo("framework_DLQ");
        }

        @Test
        @DisplayName("should default maxReplayAttempts to 3")
        void shouldDefaultMaxReplayAttemptsToThree() {
            // Assert
            assertThat(properties.getMaxReplayAttempts()).isEqualTo(3);
        }

        @Test
        @DisplayName("should default entryTtl to 168 hours (7 days)")
        void shouldDefaultEntryTtlTo168Hours() {
            // Assert
            assertThat(properties.getEntryTtl()).isEqualTo(Duration.ofHours(168));
        }
    }

    @Nested
    @DisplayName("Property setters")
    class PropertySetters {

        @Test
        @DisplayName("should update enabled property")
        void shouldUpdateEnabledProperty() {
            // Act
            properties.setEnabled(false);

            // Assert
            assertThat(properties.isEnabled()).isFalse();
        }

        @Test
        @DisplayName("should update mapName property")
        void shouldUpdateMapNameProperty() {
            // Act
            properties.setMapName("custom_DLQ");

            // Assert
            assertThat(properties.getMapName()).isEqualTo("custom_DLQ");
        }

        @Test
        @DisplayName("should update maxReplayAttempts property")
        void shouldUpdateMaxReplayAttemptsProperty() {
            // Act
            properties.setMaxReplayAttempts(5);

            // Assert
            assertThat(properties.getMaxReplayAttempts()).isEqualTo(5);
        }

        @Test
        @DisplayName("should update entryTtl property")
        void shouldUpdateEntryTtlProperty() {
            // Act
            properties.setEntryTtl(Duration.ofHours(24));

            // Assert
            assertThat(properties.getEntryTtl()).isEqualTo(Duration.ofHours(24));
        }
    }

    @Nested
    @DisplayName("Validation")
    class Validation {

        @Test
        @DisplayName("should throw IllegalArgumentException when maxReplayAttempts is zero")
        void shouldThrowWhenMaxReplayAttemptsIsZero() {
            // Act & Assert
            assertThatThrownBy(() -> properties.setMaxReplayAttempts(0))
                    .isInstanceOf(IllegalArgumentException.class)
                    .hasMessageContaining("maxReplayAttempts must be at least 1");
        }

        @Test
        @DisplayName("should throw IllegalArgumentException when maxReplayAttempts is negative")
        void shouldThrowWhenMaxReplayAttemptsIsNegative() {
            // Act & Assert
            assertThatThrownBy(() -> properties.setMaxReplayAttempts(-1))
                    .isInstanceOf(IllegalArgumentException.class)
                    .hasMessageContaining("maxReplayAttempts must be at least 1");
        }

        @Test
        @DisplayName("should accept maxReplayAttempts of exactly 1")
        void shouldAcceptMaxReplayAttemptsOfOne() {
            // Act
            properties.setMaxReplayAttempts(1);

            // Assert
            assertThat(properties.getMaxReplayAttempts()).isEqualTo(1);
        }
    }

    @Nested
    @DisplayName("toString")
    class ToStringTests {

        @Test
        @DisplayName("should include all properties in toString")
        void shouldIncludeAllPropertiesInToString() {
            // Act
            String result = properties.toString();

            // Assert
            assertThat(result).contains("DeadLetterQueueProperties");
            assertThat(result).contains("enabled=true");
            assertThat(result).contains("framework_DLQ");
            assertThat(result).contains("maxReplayAttempts=3");
            assertThat(result).contains("168");
        }
    }
}
