package com.theyawns.framework.dlq;

import com.hazelcast.nio.serialization.genericrecord.GenericRecord;
import com.hazelcast.nio.serialization.genericrecord.GenericRecordBuilder;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Tests for {@link DeadLetterEntry}.
 *
 * <p>Validates builder construction, field access, required field validation,
 * and status transitions.
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
@DisplayName("DeadLetterEntry - DLQ entry construction and state management")
class DeadLetterEntryTest {

    private static final String EVENT_ID = "evt-001";
    private static final String EVENT_TYPE = "OrderCreated";
    private static final String TOPIC_NAME = "OrderCreated";
    private static final String FAILURE_REASON = "Connection refused";
    private static final String SOURCE_SERVICE = "inventory-service";
    private static final String SAGA_ID = "saga-001";
    private static final String CORRELATION_ID = "corr-001";

    private GenericRecord createTestRecord() {
        return GenericRecordBuilder.compact("TestEvent")
                .setString("eventId", "test-1")
                .setString("eventType", "TestCreated")
                .build();
    }

    private DeadLetterEntry createFullEntry() {
        return DeadLetterEntry.builder()
                .originalEventId(EVENT_ID)
                .eventType(EVENT_TYPE)
                .topicName(TOPIC_NAME)
                .eventRecord(createTestRecord())
                .failureReason(FAILURE_REASON)
                .sourceService(SOURCE_SERVICE)
                .sagaId(SAGA_ID)
                .correlationId(CORRELATION_ID)
                .build();
    }

    @Nested
    @DisplayName("Builder construction")
    class BuilderConstruction {

        @Test
        @DisplayName("should build entry with all fields set")
        void shouldBuildEntryWithAllFieldsSet() {
            // Arrange & Act
            DeadLetterEntry entry = createFullEntry();

            // Assert
            assertThat(entry.getDlqEntryId()).isNotNull().isNotEmpty();
            assertThat(entry.getOriginalEventId()).isEqualTo(EVENT_ID);
            assertThat(entry.getEventType()).isEqualTo(EVENT_TYPE);
            assertThat(entry.getTopicName()).isEqualTo(TOPIC_NAME);
            assertThat(entry.getEventRecord()).isNotNull();
            assertThat(entry.getFailureReason()).isEqualTo(FAILURE_REASON);
            assertThat(entry.getFailureTimestamp()).isNotNull();
            assertThat(entry.getSourceService()).isEqualTo(SOURCE_SERVICE);
            assertThat(entry.getSagaId()).isEqualTo(SAGA_ID);
            assertThat(entry.getCorrelationId()).isEqualTo(CORRELATION_ID);
        }

        @Test
        @DisplayName("should build entry with only required fields")
        void shouldBuildEntryWithOnlyRequiredFields() {
            // Arrange & Act
            DeadLetterEntry entry = DeadLetterEntry.builder()
                    .originalEventId(EVENT_ID)
                    .eventType(EVENT_TYPE)
                    .topicName(TOPIC_NAME)
                    .failureReason(FAILURE_REASON)
                    .build();

            // Assert
            assertThat(entry.getDlqEntryId()).isNotNull();
            assertThat(entry.getOriginalEventId()).isEqualTo(EVENT_ID);
            assertThat(entry.getEventType()).isEqualTo(EVENT_TYPE);
            assertThat(entry.getTopicName()).isEqualTo(TOPIC_NAME);
            assertThat(entry.getFailureReason()).isEqualTo(FAILURE_REASON);
            assertThat(entry.getEventRecord()).isNull();
            assertThat(entry.getSourceService()).isNull();
            assertThat(entry.getSagaId()).isNull();
            assertThat(entry.getCorrelationId()).isNull();
        }

        @Test
        @DisplayName("should generate unique DLQ entry IDs")
        void shouldGenerateUniqueDlqEntryIds() {
            // Arrange & Act
            DeadLetterEntry entry1 = createFullEntry();
            DeadLetterEntry entry2 = createFullEntry();

            // Assert
            assertThat(entry1.getDlqEntryId()).isNotEqualTo(entry2.getDlqEntryId());
        }

        @Test
        @DisplayName("should initialize replay count to zero")
        void shouldInitializeReplayCountToZero() {
            // Arrange & Act
            DeadLetterEntry entry = createFullEntry();

            // Assert
            assertThat(entry.getReplayCount()).isZero();
        }

        @Test
        @DisplayName("should initialize status to PENDING")
        void shouldInitializeStatusToPending() {
            // Arrange & Act
            DeadLetterEntry entry = createFullEntry();

            // Assert
            assertThat(entry.getStatus()).isEqualTo(DeadLetterEntry.Status.PENDING);
        }

        @Test
        @DisplayName("should set failure timestamp to current time")
        void shouldSetFailureTimestampToCurrentTime() {
            // Arrange
            long beforeCreation = System.currentTimeMillis();

            // Act
            DeadLetterEntry entry = createFullEntry();

            // Assert
            long afterCreation = System.currentTimeMillis();
            long entryTimestampMs = entry.getFailureTimestamp().toEpochMilli();
            assertThat(entryTimestampMs).isBetween(beforeCreation, afterCreation);
        }
    }

    @Nested
    @DisplayName("Required field validation")
    class RequiredFieldValidation {

        @Test
        @DisplayName("should throw NullPointerException when originalEventId is null")
        void shouldThrowWhenOriginalEventIdIsNull() {
            // Arrange
            DeadLetterEntry.Builder builder = DeadLetterEntry.builder()
                    .eventType(EVENT_TYPE)
                    .topicName(TOPIC_NAME)
                    .failureReason(FAILURE_REASON);

            // Act & Assert
            assertThatThrownBy(builder::build)
                    .isInstanceOf(NullPointerException.class)
                    .hasMessageContaining("originalEventId");
        }

        @Test
        @DisplayName("should throw NullPointerException when eventType is null")
        void shouldThrowWhenEventTypeIsNull() {
            // Arrange
            DeadLetterEntry.Builder builder = DeadLetterEntry.builder()
                    .originalEventId(EVENT_ID)
                    .topicName(TOPIC_NAME)
                    .failureReason(FAILURE_REASON);

            // Act & Assert
            assertThatThrownBy(builder::build)
                    .isInstanceOf(NullPointerException.class)
                    .hasMessageContaining("eventType");
        }

        @Test
        @DisplayName("should throw NullPointerException when topicName is null")
        void shouldThrowWhenTopicNameIsNull() {
            // Arrange
            DeadLetterEntry.Builder builder = DeadLetterEntry.builder()
                    .originalEventId(EVENT_ID)
                    .eventType(EVENT_TYPE)
                    .failureReason(FAILURE_REASON);

            // Act & Assert
            assertThatThrownBy(builder::build)
                    .isInstanceOf(NullPointerException.class)
                    .hasMessageContaining("topicName");
        }

        @Test
        @DisplayName("should throw NullPointerException when failureReason is null")
        void shouldThrowWhenFailureReasonIsNull() {
            // Arrange
            DeadLetterEntry.Builder builder = DeadLetterEntry.builder()
                    .originalEventId(EVENT_ID)
                    .eventType(EVENT_TYPE)
                    .topicName(TOPIC_NAME);

            // Act & Assert
            assertThatThrownBy(builder::build)
                    .isInstanceOf(NullPointerException.class)
                    .hasMessageContaining("failureReason");
        }
    }

    @Nested
    @DisplayName("Status transitions")
    class StatusTransitions {

        @Test
        @DisplayName("should transition from PENDING to REPLAYED")
        void shouldTransitionFromPendingToReplayed() {
            // Arrange
            DeadLetterEntry entry = createFullEntry();

            // Act
            entry.setStatus(DeadLetterEntry.Status.REPLAYED);

            // Assert
            assertThat(entry.getStatus()).isEqualTo(DeadLetterEntry.Status.REPLAYED);
        }

        @Test
        @DisplayName("should transition from PENDING to DISCARDED")
        void shouldTransitionFromPendingToDiscarded() {
            // Arrange
            DeadLetterEntry entry = createFullEntry();

            // Act
            entry.setStatus(DeadLetterEntry.Status.DISCARDED);

            // Assert
            assertThat(entry.getStatus()).isEqualTo(DeadLetterEntry.Status.DISCARDED);
        }

        @Test
        @DisplayName("should throw NullPointerException when setting null status")
        void shouldThrowWhenSettingNullStatus() {
            // Arrange
            DeadLetterEntry entry = createFullEntry();

            // Act & Assert
            assertThatThrownBy(() -> entry.setStatus(null))
                    .isInstanceOf(NullPointerException.class)
                    .hasMessageContaining("status");
        }

        @Test
        @DisplayName("should allow incrementing replay count")
        void shouldAllowIncrementingReplayCount() {
            // Arrange
            DeadLetterEntry entry = createFullEntry();

            // Act
            entry.setReplayCount(1);
            entry.setReplayCount(2);

            // Assert
            assertThat(entry.getReplayCount()).isEqualTo(2);
        }
    }

    @Nested
    @DisplayName("toString")
    class ToStringTests {

        @Test
        @DisplayName("should include key fields in toString")
        void shouldIncludeKeyFieldsInToString() {
            // Arrange
            DeadLetterEntry entry = createFullEntry();

            // Act
            String result = entry.toString();

            // Assert
            assertThat(result).contains("DeadLetterEntry");
            assertThat(result).contains(EVENT_ID);
            assertThat(result).contains(EVENT_TYPE);
            assertThat(result).contains(TOPIC_NAME);
            assertThat(result).contains(FAILURE_REASON);
            assertThat(result).contains(SOURCE_SERVICE);
            assertThat(result).contains(SAGA_ID);
            assertThat(result).contains("PENDING");
        }
    }
}
