package com.theyawns.framework.dlq;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.springframework.http.ResponseEntity;

import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Tests for {@link FaultInjectionController}.
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
@DisplayName("FaultInjectionController")
class FaultInjectionControllerTest {

    private FaultInjectionState state;
    private FaultInjectionController controller;

    @BeforeEach
    void setUp() {
        state = new FaultInjectionState();
        controller = new FaultInjectionController(state);
    }

    @Nested
    @DisplayName("GET /api/admin/fault")
    class GetFaultInjection {

        @Test
        @DisplayName("should return current state when disabled")
        void shouldReturnDisabledState() {
            ResponseEntity<Map<String, Object>> response = controller.getFaultInjection();

            assertThat(response.getStatusCode().value()).isEqualTo(200);
            assertThat(response.getBody()).containsEntry("enabled", false);
        }

        @Test
        @DisplayName("should return current state when enabled")
        void shouldReturnEnabledState() {
            state.setEnabled(true);
            state.setFailureMessage("Custom msg");

            ResponseEntity<Map<String, Object>> response = controller.getFaultInjection();

            assertThat(response.getBody()).containsEntry("enabled", true);
            assertThat(response.getBody()).containsEntry("failureMessage", "Custom msg");
        }
    }

    @Nested
    @DisplayName("POST /api/admin/fault")
    class SetFaultInjection {

        @Test
        @DisplayName("should enable fault injection")
        void shouldEnable() {
            ResponseEntity<Map<String, Object>> response =
                    controller.setFaultInjection(true, "Test failure");

            assertThat(response.getStatusCode().value()).isEqualTo(200);
            assertThat(response.getBody()).containsEntry("enabled", true);
            assertThat(response.getBody()).containsEntry("failureMessage", "Test failure");
            assertThat(state.isEnabled()).isTrue();
        }

        @Test
        @DisplayName("should disable fault injection")
        void shouldDisable() {
            state.setEnabled(true);
            ResponseEntity<Map<String, Object>> response =
                    controller.setFaultInjection(false, null);

            assertThat(response.getBody()).containsEntry("enabled", false);
            assertThat(state.isEnabled()).isFalse();
        }

        @Test
        @DisplayName("should keep existing message when null provided")
        void shouldKeepExistingMessage() {
            state.setFailureMessage("Existing");
            controller.setFaultInjection(true, null);

            assertThat(state.getFailureMessage()).isEqualTo("Existing");
        }
    }
}
