package com.theyawns.ecommerce.account.controller;

import com.theyawns.ecommerce.account.exception.GlobalExceptionHandler;
import com.theyawns.ecommerce.account.service.CustomerService;
import com.theyawns.ecommerce.common.domain.Customer;
import com.theyawns.ecommerce.common.dto.CustomerDTO;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.http.MediaType;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;

import java.util.Optional;
import java.util.concurrent.CompletableFuture;

import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.asyncDispatch;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.patch;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.request;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

/**
 * Integration tests for AccountController REST endpoints.
 * Uses standalone MockMvc setup with interface mocking.
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
@ExtendWith(MockitoExtension.class)
@DisplayName("AccountController Integration Tests")
class AccountControllerIntegrationTest {

    private MockMvc mockMvc;

    @Mock
    private CustomerService customerService;

    @InjectMocks
    private AccountController accountController;

    @BeforeEach
    void setUp() {
        mockMvc = MockMvcBuilders.standaloneSetup(accountController)
                .setControllerAdvice(new GlobalExceptionHandler())
                .build();
    }

    @Nested
    @DisplayName("POST /api/customers")
    class CreateCustomerEndpointTests {

        @Test
        @DisplayName("should create customer and return 201")
        void shouldCreateCustomerAndReturn201() throws Exception {
            Customer customer = new Customer("cust-123", "test@example.com", "John Doe", "123 Main St");
            customer.setPhone("555-1234");

            when(customerService.createCustomer(any(CustomerDTO.class)))
                    .thenReturn(CompletableFuture.completedFuture(customer));

            MvcResult mvcResult = mockMvc.perform(post("/api/customers")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("""
                                    {
                                        "email": "test@example.com",
                                        "name": "John Doe",
                                        "address": "123 Main St",
                                        "phone": "555-1234"
                                    }
                                    """))
                    .andExpect(request().asyncStarted())
                    .andReturn();

            mockMvc.perform(asyncDispatch(mvcResult))
                    .andExpect(status().isCreated())
                    .andExpect(jsonPath("$.customerId").value("cust-123"))
                    .andExpect(jsonPath("$.email").value("test@example.com"))
                    .andExpect(jsonPath("$.name").value("John Doe"))
                    .andExpect(jsonPath("$.address").value("123 Main St"))
                    .andExpect(jsonPath("$.phone").value("555-1234"));
        }
    }

    @Nested
    @DisplayName("GET /api/customers/{id}")
    class GetCustomerEndpointTests {

        @Test
        @DisplayName("should return customer when found")
        void shouldReturnCustomerWhenFound() throws Exception {
            Customer customer = new Customer("cust-123", "test@example.com", "John Doe", "123 Main St");
            customer.setPhone("555-1234");

            when(customerService.getCustomer("cust-123")).thenReturn(Optional.of(customer));

            mockMvc.perform(get("/api/customers/cust-123"))
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$.customerId").value("cust-123"))
                    .andExpect(jsonPath("$.email").value("test@example.com"))
                    .andExpect(jsonPath("$.name").value("John Doe"));
        }

        @Test
        @DisplayName("should return 404 when customer not found")
        void shouldReturn404WhenCustomerNotFound() throws Exception {
            when(customerService.getCustomer("nonexistent")).thenReturn(Optional.empty());

            mockMvc.perform(get("/api/customers/nonexistent"))
                    .andExpect(status().isNotFound());
        }
    }

    @Nested
    @DisplayName("PUT /api/customers/{id}")
    class UpdateCustomerEndpointTests {

        @Test
        @DisplayName("should update customer and return 200")
        void shouldUpdateCustomerAndReturn200() throws Exception {
            Customer customer = new Customer("cust-123", "test@example.com", "Jane Smith", "456 Oak Ave");
            customer.setPhone("555-9999");

            when(customerService.updateCustomer(eq("cust-123"), any(CustomerDTO.class)))
                    .thenReturn(CompletableFuture.completedFuture(customer));

            MvcResult mvcResult = mockMvc.perform(put("/api/customers/cust-123")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("""
                                    {
                                        "email": "test@example.com",
                                        "name": "Jane Smith",
                                        "address": "456 Oak Ave",
                                        "phone": "555-9999"
                                    }
                                    """))
                    .andExpect(request().asyncStarted())
                    .andReturn();

            mockMvc.perform(asyncDispatch(mvcResult))
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$.name").value("Jane Smith"))
                    .andExpect(jsonPath("$.address").value("456 Oak Ave"))
                    .andExpect(jsonPath("$.phone").value("555-9999"));
        }
    }

    @Nested
    @DisplayName("PATCH /api/customers/{id}/status")
    class ChangeStatusEndpointTests {

        @Test
        @DisplayName("should change status and return 200")
        void shouldChangeStatusAndReturn200() throws Exception {
            Customer customer = new Customer("cust-123", "test@example.com", "John Doe", "123 Main St");
            customer.setStatus(Customer.Status.SUSPENDED);

            when(customerService.changeStatus(eq("cust-123"), eq("SUSPENDED"), anyString()))
                    .thenReturn(CompletableFuture.completedFuture(customer));

            MvcResult mvcResult = mockMvc.perform(patch("/api/customers/cust-123/status")
                            .contentType(MediaType.APPLICATION_JSON)
                            .content("""
                                    {
                                        "status": "SUSPENDED",
                                        "reason": "Payment overdue"
                                    }
                                    """))
                    .andExpect(request().asyncStarted())
                    .andReturn();

            mockMvc.perform(asyncDispatch(mvcResult))
                    .andExpect(status().isOk())
                    .andExpect(jsonPath("$.status").value("SUSPENDED"));
        }
    }
}
