package com.theyawns.ecommerce.common.saga;

import com.theyawns.framework.saga.CompensationRegistry;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Configuration;

import jakarta.annotation.PostConstruct;

/**
 * Configures compensation mappings for eCommerce domain events.
 * Registers the event pairs for the Order Fulfillment saga.
 *
 * <p>The Order Fulfillment saga has the following steps:
 * <ol>
 *   <li>OrderCreated (order-service) - Step 0</li>
 *   <li>StockReserved (inventory-service) - Step 1</li>
 *   <li>PaymentProcessed (payment-service) - Step 2</li>
 *   <li>OrderConfirmed (order-service) - Step 3</li>
 * </ol>
 *
 * <p>Compensation events (executed in reverse order on failure):
 * <ul>
 *   <li>PaymentProcessed -&gt; PaymentRefunded</li>
 *   <li>StockReserved -&gt; StockReleased</li>
 *   <li>OrderCreated -&gt; OrderCancelled</li>
 * </ul>
 *
 * <p><strong>Important:</strong> This registry maps <em>forward events to compensation events</em>
 * only. <strong>Failure trigger events</strong> such as {@code PaymentFailedEvent} and
 * {@code StockReservationFailedEvent} are <em>not</em> registered here. Those events are plain
 * {@link com.theyawns.framework.event.DomainEvent DomainEvent}s that saga listeners subscribe to
 * directly via Hazelcast ITopic. This is by design: failure events cause compensation of prior
 * steps, but they do not need compensation themselves.
 *
 * @author Generated by Claude Code
 * @since 2.0
 * @see CompensationRegistry
 * @see SagaCompensationConfig
 */
@Configuration
public class ECommerceCompensationConfig {

    private static final Logger logger = LoggerFactory.getLogger(ECommerceCompensationConfig.class);

    // Saga type names
    public static final String ORDER_FULFILLMENT_SAGA = "OrderFulfillment";
    public static final String CUSTOMER_ONBOARDING_SAGA = "CustomerOnboarding";

    // Event type constants for Order Fulfillment Saga
    public static final String ORDER_CREATED = "OrderCreated";
    public static final String ORDER_CANCELLED = "OrderCancelled";
    public static final String ORDER_CONFIRMED = "OrderConfirmed";
    public static final String STOCK_RESERVED = "StockReserved";
    public static final String STOCK_RELEASED = "StockReleased";
    public static final String PAYMENT_PROCESSED = "PaymentProcessed";
    public static final String PAYMENT_FAILED = "PaymentFailed";
    public static final String PAYMENT_REFUNDED = "PaymentRefunded";
    public static final String STOCK_RESERVATION_FAILED = "StockReservationFailed";

    // Service name constants
    public static final String ORDER_SERVICE = "order-service";
    public static final String INVENTORY_SERVICE = "inventory-service";
    public static final String PAYMENT_SERVICE = "payment-service";
    public static final String ACCOUNT_SERVICE = "account-service";

    // Step numbers for Order Fulfillment Saga
    public static final int STEP_ORDER_CREATED = 0;
    public static final int STEP_STOCK_RESERVED = 1;
    public static final int STEP_PAYMENT_PROCESSED = 2;
    public static final int STEP_ORDER_CONFIRMED = 3;

    private final CompensationRegistry compensationRegistry;

    /**
     * Creates the eCommerce compensation configuration.
     *
     * @param compensationRegistry the registry to configure
     */
    @Autowired
    public ECommerceCompensationConfig(CompensationRegistry compensationRegistry) {
        this.compensationRegistry = compensationRegistry;
    }

    /**
     * Registers all eCommerce compensation mappings on startup.
     */
    @PostConstruct
    public void registerCompensations() {
        logger.info("Registering eCommerce compensation mappings");

        // Order Fulfillment Saga compensations
        registerOrderFulfillmentCompensations();

        logger.info("Registered {} compensation mappings", compensationRegistry.size());
    }

    /**
     * Registers compensation mappings for the Order Fulfillment saga.
     *
     * <p>Saga flow:
     * <pre>
     * Step 0: OrderCreated (order-service)
     *    |
     *    v
     * Step 1: StockReserved (inventory-service)
     *    |
     *    v
     * Step 2: PaymentProcessed (payment-service)
     *    |
     *    v
     * Step 3: OrderConfirmed (order-service) - Final step, no compensation
     * </pre>
     *
     * <p>On failure at any step, compensate in reverse:
     * <pre>
     * PaymentProcessed -> PaymentRefunded
     * StockReserved -> StockReleased
     * OrderCreated -> OrderCancelled
     * </pre>
     */
    private void registerOrderFulfillmentCompensations() {
        // Step 0: OrderCreated -> OrderCancelled
        compensationRegistry.register(
                ECommerceCompensationConfig.ORDER_CREATED,
                ECommerceCompensationConfig.ORDER_CANCELLED,
                ECommerceCompensationConfig.ORDER_SERVICE,
                ECommerceCompensationConfig.STEP_ORDER_CREATED
        );

        // Step 1: StockReserved -> StockReleased
        compensationRegistry.register(
                ECommerceCompensationConfig.STOCK_RESERVED,
                ECommerceCompensationConfig.STOCK_RELEASED,
                ECommerceCompensationConfig.INVENTORY_SERVICE,
                ECommerceCompensationConfig.STEP_STOCK_RESERVED
        );

        // Step 2: PaymentProcessed -> PaymentRefunded
        compensationRegistry.register(
                ECommerceCompensationConfig.PAYMENT_PROCESSED,
                ECommerceCompensationConfig.PAYMENT_REFUNDED,
                ECommerceCompensationConfig.PAYMENT_SERVICE,
                ECommerceCompensationConfig.STEP_PAYMENT_PROCESSED
        );

        // Step 3: OrderConfirmed - no compensation (final success state)
        // The OrderConfirmed step doesn't need compensation as it's the terminal success state

        logger.debug("Registered Order Fulfillment saga compensations: " +
                "OrderCreated->OrderCancelled, StockReserved->StockReleased, " +
                "PaymentProcessed->PaymentRefunded");
    }
}
