package com.theyawns.ecommerce.gateway;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

/**
 * API Gateway entry point.
 *
 * <p>Routes incoming requests to the appropriate downstream microservice
 * using Spring Cloud Gateway. This module uses WebFlux (non-blocking)
 * and does not participate in event sourcing.
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
@SpringBootApplication
public class GatewayApplication {

    public static void main(final String[] args) {
        SpringApplication.run(GatewayApplication.class, args);
    }
}
