package com.theyawns.framework.saga;

import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.topic.ITopic;
import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.MeterRegistry;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.ApplicationEventPublisher;

import java.util.List;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.atomic.AtomicInteger;

/**
 * Default implementation of {@link SagaCompensator}.
 *
 * <p>Coordinates compensation across services by:
 * <ol>
 *   <li>Looking up compensation mappings from the {@link CompensationRegistry}</li>
 *   <li>Publishing compensation request events via Hazelcast topic</li>
 *   <li>Updating saga state in the {@link SagaStateStore}</li>
 *   <li>Recording metrics for observability</li>
 * </ol>
 *
 * <p>Compensation events are published to a topic named "{sagaType}-compensation"
 * which responsible services subscribe to. Each service handles compensation
 * for its own domain events.
 *
 * <p>Example flow for order fulfillment saga:
 * <pre>
 * 1. Payment fails at step 3
 * 2. DefaultSagaCompensator.compensate() is called
 * 3. Publishes "StockReleased" request to inventory-service (compensate step 2)
 * 4. Publishes "OrderCancelled" request to order-service (compensate step 1)
 * 5. Returns CompensationResult with status
 * </pre>
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
public class DefaultSagaCompensator implements SagaCompensator {

    private static final Logger logger = LoggerFactory.getLogger(DefaultSagaCompensator.class);

    public static final String COMPENSATION_TOPIC_SUFFIX = "-compensation";

    private final SagaStateStore sagaStateStore;
    private final CompensationRegistry compensationRegistry;
    private final HazelcastInstance hazelcast;
    private final ApplicationEventPublisher eventPublisher;
    private final MeterRegistry meterRegistry;

    // Metrics
    private final Counter compensationsStarted;
    private final Counter compensationsCompleted;
    private final Counter compensationsFailed;
    private final Counter stepsCompensated;

    /**
     * Creates a new DefaultSagaCompensator.
     *
     * @param sagaStateStore the saga state store
     * @param compensationRegistry the compensation mapping registry
     * @param hazelcast the Hazelcast instance for topic publishing
     * @param eventPublisher Spring's application event publisher
     * @param meterRegistry the metrics registry (may be null)
     */
    public DefaultSagaCompensator(SagaStateStore sagaStateStore,
                                   CompensationRegistry compensationRegistry,
                                   HazelcastInstance hazelcast,
                                   ApplicationEventPublisher eventPublisher,
                                   MeterRegistry meterRegistry) {
        this.sagaStateStore = Objects.requireNonNull(sagaStateStore, "sagaStateStore cannot be null");
        this.compensationRegistry = Objects.requireNonNull(compensationRegistry, "compensationRegistry cannot be null");
        this.hazelcast = Objects.requireNonNull(hazelcast, "hazelcast cannot be null");
        this.eventPublisher = eventPublisher;
        this.meterRegistry = meterRegistry;

        // Initialize metrics
        if (meterRegistry != null) {
            this.compensationsStarted = meterRegistry.counter("saga.compensations.started");
            this.compensationsCompleted = meterRegistry.counter("saga.compensations.completed");
            this.compensationsFailed = meterRegistry.counter("saga.compensations.failed");
            this.stepsCompensated = meterRegistry.counter("saga.compensation.steps");
        } else {
            this.compensationsStarted = null;
            this.compensationsCompleted = null;
            this.compensationsFailed = null;
            this.stepsCompensated = null;
        }

        logger.info("Initialized DefaultSagaCompensator");
    }

    @Override
    public CompletableFuture<CompensationResult> compensate(SagaState sagaState) {
        Objects.requireNonNull(sagaState, "sagaState cannot be null");

        String sagaId = sagaState.getSagaId();
        logger.info("Starting compensation for saga: {} type: {}", sagaId, sagaState.getSagaType());

        if (compensationsStarted != null) {
            compensationsStarted.increment();
        }

        // Check if compensation is possible
        if (!canCompensate(sagaState)) {
            logger.debug("No compensation needed for saga: {}", sagaId);
            return CompletableFuture.completedFuture(
                    CompensationResult.noCompensationNeeded(sagaId)
            );
        }

        // Mark saga as compensating
        try {
            sagaStateStore.recordCompensationStarted(sagaId);
        } catch (Exception e) {
            logger.error("Failed to start compensation for saga: {}", sagaId, e);
            return CompletableFuture.completedFuture(
                    CompensationResult.failure(sagaId, 0, 0, "Failed to start compensation: " + e.getMessage())
            );
        }

        // Get steps needing compensation (in reverse order)
        List<SagaStepRecord> stepsToCompensate = sagaState.getStepsNeedingCompensation();
        logger.debug("Saga {} has {} steps requiring compensation", sagaId, stepsToCompensate.size());

        // Compensate each step
        return compensateSteps(sagaState, stepsToCompensate);
    }

    private CompletableFuture<CompensationResult> compensateSteps(SagaState sagaState,
                                                                    List<SagaStepRecord> steps) {
        String sagaId = sagaState.getSagaId();
        AtomicInteger successCount = new AtomicInteger(0);
        AtomicInteger failCount = new AtomicInteger(0);
        StringBuilder failureReasons = new StringBuilder();

        // Process steps sequentially for proper ordering
        CompletableFuture<Void> chain = CompletableFuture.completedFuture(null);

        for (SagaStepRecord step : steps) {
            chain = chain.thenCompose(v -> {
                return compensateStep(sagaState, step)
                        .thenAccept(result -> {
                            if (result.isSuccess()) {
                                successCount.incrementAndGet();
                            } else {
                                failCount.incrementAndGet();
                                if (failureReasons.length() > 0) {
                                    failureReasons.append("; ");
                                }
                                failureReasons.append("Step ")
                                        .append(step.getStepNumber())
                                        .append(": ")
                                        .append(result.failureReason());
                            }
                        });
            });
        }

        return chain.thenApply(v -> {
            CompensationResult result;
            if (failCount.get() == 0) {
                // All steps compensated successfully
                try {
                    sagaStateStore.completeSaga(sagaId, SagaStatus.COMPENSATED);
                } catch (Exception e) {
                    logger.error("Failed to mark saga as compensated: {}", sagaId, e);
                }

                if (compensationsCompleted != null) {
                    compensationsCompleted.increment();
                }

                result = CompensationResult.success(sagaId, successCount.get());
                logger.info("Compensation completed for saga: {} steps compensated: {}",
                        sagaId, successCount.get());
            } else {
                // Some steps failed
                if (compensationsFailed != null) {
                    compensationsFailed.increment();
                }

                result = CompensationResult.failure(sagaId, successCount.get(),
                        failCount.get(), failureReasons.toString());
                logger.error("Compensation partially failed for saga: {} success: {} failed: {}",
                        sagaId, successCount.get(), failCount.get());
            }

            return result;
        }).exceptionally(ex -> {
            logger.error("Unexpected error during compensation for saga: {}", sagaId, ex);
            if (compensationsFailed != null) {
                compensationsFailed.increment();
            }
            return CompensationResult.failure(sagaId, successCount.get(),
                    steps.size() - successCount.get(), ex.getMessage());
        });
    }

    @Override
    public CompletableFuture<CompensationResult> compensateStep(SagaState sagaState,
                                                                  SagaStepRecord stepRecord) {
        Objects.requireNonNull(sagaState, "sagaState cannot be null");
        Objects.requireNonNull(stepRecord, "stepRecord cannot be null");

        String sagaId = sagaState.getSagaId();
        String eventType = stepRecord.getEventType();
        int stepNumber = stepRecord.getStepNumber();

        logger.debug("Compensating step {} ({}) for saga: {}", stepNumber, eventType, sagaId);

        // Look up compensation mapping
        Optional<CompensationRegistry.CompensationMapping> mapping =
                compensationRegistry.getCompensation(eventType);

        if (mapping.isEmpty()) {
            logger.warn("No compensation mapping for event type: {} in saga: {}", eventType, sagaId);
            return CompletableFuture.completedFuture(
                    CompensationResult.failure(sagaId, 0, 1,
                            "No compensation mapping for: " + eventType)
            );
        }

        String compensatingEventType = mapping.get().compensatingEventType();
        String responsibleService = mapping.get().service();

        try {
            // Create and publish compensation request
            CompensationRequest request = new CompensationRequest(
                    sagaId,
                    sagaState.getSagaType(),
                    sagaState.getCorrelationId(),
                    stepNumber,
                    eventType,
                    compensatingEventType,
                    responsibleService,
                    stepRecord.getEventId()
            );

            // Publish to Hazelcast topic for the responsible service
            String topicName = responsibleService + COMPENSATION_TOPIC_SUFFIX;
            ITopic<CompensationRequest> topic = hazelcast.getTopic(topicName);
            topic.publish(request);

            logger.debug("Published compensation request to topic {}: {}", topicName, compensatingEventType);

            // Also publish as Spring event for local listeners
            if (eventPublisher != null) {
                eventPublisher.publishEvent(request);
            }

            // Record the compensation step in the saga state
            sagaStateStore.recordCompensationStep(sagaId, stepNumber,
                    compensatingEventType, responsibleService);

            if (stepsCompensated != null) {
                stepsCompensated.increment();
            }

            return CompletableFuture.completedFuture(
                    CompensationResult.success(sagaId, 1)
            );

        } catch (Exception e) {
            logger.error("Failed to compensate step {} for saga: {}", stepNumber, sagaId, e);
            return CompletableFuture.completedFuture(
                    CompensationResult.failure(sagaId, 0, 1, e.getMessage())
            );
        }
    }

    @Override
    public boolean canCompensate(SagaState sagaState) {
        if (sagaState == null) {
            return false;
        }

        // Cannot compensate terminal states (except TIMED_OUT which triggers compensation)
        SagaStatus status = sagaState.getStatus();
        if (status == SagaStatus.COMPLETED ||
                status == SagaStatus.COMPENSATED ||
                status == SagaStatus.FAILED) {
            return false;
        }

        // Check if there are steps that need compensation
        List<SagaStepRecord> stepsNeedingCompensation = sagaState.getStepsNeedingCompensation();
        if (stepsNeedingCompensation.isEmpty()) {
            return false;
        }

        // Verify at least one step has a compensation mapping
        return stepsNeedingCompensation.stream()
                .anyMatch(step -> compensationRegistry.hasCompensation(step.getEventType()));
    }

    /**
     * Request object sent to services to trigger compensation.
     * Published to Hazelcast topics for cross-service communication.
     */
    public record CompensationRequest(
            String sagaId,
            String sagaType,
            String correlationId,
            int stepNumber,
            String originalEventType,
            String compensatingEventType,
            String responsibleService,
            String originalEventId
    ) implements java.io.Serializable {

        private static final long serialVersionUID = 1L;
    }
}
