package com.theyawns.framework.saga;

import com.hazelcast.core.HazelcastInstance;
import io.micrometer.core.instrument.MeterRegistry;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.autoconfigure.condition.ConditionalOnBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.scheduling.annotation.EnableScheduling;

/**
 * Auto-configuration for saga timeout detection components.
 *
 * <p>This configuration is enabled by default and provides:
 * <ul>
 *   <li>{@link SagaTimeoutConfig} - Configuration properties bound from application.yml</li>
 *   <li>{@link SagaCompensator} - Default compensator implementation</li>
 *   <li>{@link SagaTimeoutDetector} - Scheduled timeout detection service</li>
 * </ul>
 *
 * <p>To disable timeout detection, set:
 * <pre>
 * saga.timeout.enabled=false
 * </pre>
 *
 * <p>Required dependencies:
 * <ul>
 *   <li>{@link HazelcastInstance} - For distributed operations</li>
 *   <li>{@link SagaStateStore} - For saga state queries</li>
 *   <li>{@link CompensationRegistry} - For compensation mappings</li>
 * </ul>
 *
 * @author Generated by Claude Code
 * @since 2.0
 * @see SagaTimeoutConfig
 * @see SagaTimeoutDetector
 * @see SagaCompensator
 */
@Configuration
@EnableScheduling
@EnableConfigurationProperties(SagaTimeoutConfig.class)
@ConditionalOnBean({HazelcastInstance.class, SagaStateStore.class, CompensationRegistry.class})
public class SagaTimeoutAutoConfiguration {

    private static final Logger logger = LoggerFactory.getLogger(SagaTimeoutAutoConfiguration.class);

    /**
     * Creates the default SagaCompensator bean.
     *
     * @param sagaStateStore the saga state store
     * @param compensationRegistry the compensation registry
     * @param hazelcast the Hazelcast instance
     * @param eventPublisher Spring's event publisher
     * @param meterRegistry the metrics registry (optional)
     * @return the compensator instance
     */
    @Bean
    @ConditionalOnMissingBean(SagaCompensator.class)
    public SagaCompensator sagaCompensator(
            SagaStateStore sagaStateStore,
            CompensationRegistry compensationRegistry,
            HazelcastInstance hazelcast,
            ApplicationEventPublisher eventPublisher,
            MeterRegistry meterRegistry) {
        logger.info("Creating DefaultSagaCompensator bean");
        return new DefaultSagaCompensator(
                sagaStateStore,
                compensationRegistry,
                hazelcast,
                eventPublisher,
                meterRegistry
        );
    }

    /**
     * Creates the SagaTimeoutDetector bean.
     *
     * <p>Only created when saga.timeout.enabled is true (default).
     *
     * @param sagaStateStore the saga state store
     * @param compensator the saga compensator
     * @param config the timeout configuration
     * @param hazelcast the Hazelcast instance
     * @param eventPublisher Spring's event publisher
     * @param meterRegistry the metrics registry (optional)
     * @return the timeout detector instance
     */
    @Bean
    @ConditionalOnProperty(name = "saga.timeout.enabled", havingValue = "true", matchIfMissing = true)
    @ConditionalOnMissingBean(SagaTimeoutDetector.class)
    public SagaTimeoutDetector sagaTimeoutDetector(
            SagaStateStore sagaStateStore,
            SagaCompensator compensator,
            SagaTimeoutConfig config,
            HazelcastInstance hazelcast,
            ApplicationEventPublisher eventPublisher,
            MeterRegistry meterRegistry) {
        logger.info("Creating SagaTimeoutDetector bean with check interval: {}",
                config.getCheckInterval());
        return new SagaTimeoutDetector(
                sagaStateStore,
                compensator,
                config,
                hazelcast,
                eventPublisher,
                meterRegistry
        );
    }
}
