package com.theyawns.framework.saga;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Spring configuration for saga compensation infrastructure.
 * Sets up the CompensationRegistry bean and registers default mappings.
 *
 * <p>This configuration creates a singleton CompensationRegistry that can be
 * customized by applications. Services can add their own compensation mappings
 * by injecting the registry and calling register().
 *
 * <p>Example custom configuration:
 * <pre>
 * &#64;Configuration
 * public class MyServiceSagaConfig {
 *
 *     &#64;Autowired
 *     public void configureCompensations(CompensationRegistry registry) {
 *         registry.register("MyEvent", "MyCompensatingEvent", "my-service");
 *     }
 * }
 * </pre>
 *
 * @author Generated by Claude Code
 * @since 2.0
 * @see CompensationRegistry
 */
@Configuration
public class SagaCompensationConfig {

    private static final Logger logger = LoggerFactory.getLogger(SagaCompensationConfig.class);

    /**
     * Creates the CompensationRegistry bean.
     * Only created if no other CompensationRegistry bean exists.
     *
     * @return a new CompensationRegistry instance
     */
    @Bean
    @ConditionalOnMissingBean
    public CompensationRegistry compensationRegistry() {
        logger.info("Creating CompensationRegistry bean");
        return new CompensationRegistry();
    }

    /**
     * Order fulfillment saga type name.
     * Used to identify events participating in this saga.
     */
    public static final String ORDER_FULFILLMENT_SAGA = "OrderFulfillment";

    /**
     * Customer onboarding saga type name.
     */
    public static final String CUSTOMER_ONBOARDING_SAGA = "CustomerOnboarding";

    // Event type constants for Order Fulfillment Saga
    public static final String ORDER_CREATED = "OrderCreated";
    public static final String ORDER_CANCELLED = "OrderCancelled";
    public static final String ORDER_CONFIRMED = "OrderConfirmed";
    public static final String STOCK_RESERVED = "StockReserved";
    public static final String STOCK_RELEASED = "StockReleased";
    public static final String PAYMENT_PROCESSED = "PaymentProcessed";
    public static final String PAYMENT_FAILED = "PaymentFailed";
    public static final String PAYMENT_REFUNDED = "PaymentRefunded";
    public static final String STOCK_RESERVATION_FAILED = "StockReservationFailed";

    // Service name constants
    public static final String ORDER_SERVICE = "order-service";
    public static final String INVENTORY_SERVICE = "inventory-service";
    public static final String PAYMENT_SERVICE = "payment-service";
    public static final String ACCOUNT_SERVICE = "account-service";

    // Step numbers for Order Fulfillment Saga
    public static final int STEP_ORDER_CREATED = 0;
    public static final int STEP_STOCK_RESERVED = 1;
    public static final int STEP_PAYMENT_PROCESSED = 2;
    public static final int STEP_ORDER_CONFIRMED = 3;
}
