package com.theyawns.framework.saga;

import org.springframework.context.ApplicationEvent;

import java.io.Serializable;
import java.time.Duration;
import java.time.Instant;
import java.util.Objects;

/**
 * Event published when a saga exceeds its timeout deadline.
 *
 * <p>This event is published:
 * <ul>
 *   <li>As a Spring ApplicationEvent for local listeners</li>
 *   <li>To a Hazelcast topic for cross-service notification</li>
 * </ul>
 *
 * <p>Listeners can use this event to:
 * <ul>
 *   <li>Log/alert on saga timeouts</li>
 *   <li>Update dashboards and monitoring</li>
 *   <li>Trigger manual intervention workflows</li>
 *   <li>Perform additional cleanup</li>
 * </ul>
 *
 * <p>Example listener:
 * <pre>{@code
 * @EventListener
 * public void onSagaTimedOut(SagaTimedOutEvent event) {
 *     logger.warn("Saga timed out: {} type: {} duration: {}",
 *         event.getSagaId(),
 *         event.getSagaType(),
 *         event.getDuration());
 *
 *     // Alert operations team
 *     alertService.sendAlert("Saga timeout", event.getDetails());
 * }
 * }</pre>
 *
 * @author Generated by Claude Code
 * @since 2.0
 * @see SagaTimeoutDetector
 * @see SagaCompensator
 */
public class SagaTimedOutEvent extends ApplicationEvent implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * Hazelcast topic name for cross-service saga timeout notifications.
     */
    public static final String TIMEOUT_TOPIC = "saga-timeouts";

    private final TimeoutDetails details;

    /**
     * Creates a new SagaTimedOutEvent.
     *
     * @param source the object that published the event
     * @param sagaState the saga state at time of timeout
     */
    public SagaTimedOutEvent(Object source, SagaState sagaState) {
        super(source);
        Objects.requireNonNull(sagaState, "sagaState cannot be null");
        this.details = TimeoutDetails.from(sagaState);
    }

    /**
     * Creates a new SagaTimedOutEvent with explicit details.
     *
     * @param source the object that published the event
     * @param details the timeout details
     */
    public SagaTimedOutEvent(Object source, TimeoutDetails details) {
        super(source);
        this.details = Objects.requireNonNull(details, "details cannot be null");
    }

    /**
     * Returns the timeout details.
     *
     * @return timeout details
     */
    public TimeoutDetails getDetails() {
        return details;
    }

    /**
     * Returns the saga ID.
     *
     * @return saga ID
     */
    public String getSagaId() {
        return details.sagaId();
    }

    /**
     * Returns the saga type.
     *
     * @return saga type
     */
    public String getSagaType() {
        return details.sagaType();
    }

    /**
     * Returns the correlation ID.
     *
     * @return correlation ID
     */
    public String getCorrelationId() {
        return details.correlationId();
    }

    /**
     * Returns the duration from start to timeout.
     *
     * @return duration
     */
    public Duration getDuration() {
        return details.duration();
    }

    /**
     * Returns the step the saga was at when it timed out.
     *
     * @return current step
     */
    public int getCurrentStep() {
        return details.currentStep();
    }

    /**
     * Returns the total number of steps in the saga.
     *
     * @return total steps
     */
    public int getTotalSteps() {
        return details.totalSteps();
    }

    @Override
    public String toString() {
        return "SagaTimedOutEvent{" + details + '}';
    }

    /**
     * Serializable details of a saga timeout.
     * Can be published to Hazelcast topics for cross-service notification.
     */
    public record TimeoutDetails(
            String sagaId,
            String sagaType,
            String correlationId,
            Instant startedAt,
            Instant deadline,
            Instant timedOutAt,
            Duration duration,
            int currentStep,
            int totalSteps,
            SagaStatus statusAtTimeout,
            String initiatingService,
            String initiatingEventId
    ) implements Serializable {

        private static final long serialVersionUID = 1L;

        /**
         * Creates TimeoutDetails from a SagaState.
         *
         * @param state the saga state
         * @return timeout details
         */
        public static TimeoutDetails from(SagaState state) {
            Instant now = Instant.now();
            return new TimeoutDetails(
                    state.getSagaId(),
                    state.getSagaType(),
                    state.getCorrelationId(),
                    state.getStartedAt(),
                    state.getDeadline(),
                    now,
                    Duration.between(state.getStartedAt(), now),
                    state.getCurrentStep(),
                    state.getTotalSteps(),
                    state.getStatus(),
                    state.getInitiatingService(),
                    state.getInitiatingEventId()
            );
        }

        /**
         * Returns the progress percentage at timeout.
         *
         * @return progress as percentage (0-100)
         */
        public int getProgressPercentage() {
            if (totalSteps == 0) return 0;
            return (currentStep * 100) / totalSteps;
        }

        /**
         * Returns how long past the deadline the saga was when it timed out.
         *
         * @return duration past deadline
         */
        public Duration getOverdueBy() {
            if (deadline == null || timedOutAt == null) {
                return Duration.ZERO;
            }
            Duration overdue = Duration.between(deadline, timedOutAt);
            return overdue.isNegative() ? Duration.ZERO : overdue;
        }

        @Override
        public String toString() {
            return "TimeoutDetails{" +
                    "sagaId='" + sagaId + '\'' +
                    ", sagaType='" + sagaType + '\'' +
                    ", duration=" + duration.toMillis() + "ms" +
                    ", progress=" + getProgressPercentage() + "%" +
                    ", overdueBy=" + getOverdueBy().toMillis() + "ms" +
                    '}';
        }
    }
}
