package com.theyawns.framework.saga;

import com.hazelcast.nio.serialization.genericrecord.GenericRecord;
import com.hazelcast.nio.serialization.genericrecord.GenericRecordBuilder;

import java.io.Serializable;
import java.time.Instant;
import java.util.Objects;

/**
 * Record of a single step within a saga.
 * Tracks the execution status, timing, and any failure information.
 *
 * <p>Each step in a saga is recorded to enable:
 * <ul>
 *   <li>Progress tracking and visibility</li>
 *   <li>Compensation (knowing which steps to roll back)</li>
 *   <li>Debugging and audit trails</li>
 *   <li>Timeout detection</li>
 * </ul>
 *
 * <p>Example:
 * <pre>{@code
 * SagaStepRecord step = SagaStepRecord.builder()
 *     .stepNumber(2)
 *     .stepName("ReserveStock")
 *     .service("inventory-service")
 *     .eventType("StockReserved")
 *     .status(StepStatus.COMPLETED)
 *     .build();
 * }</pre>
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
public class SagaStepRecord implements Serializable {

    private static final long serialVersionUID = 1L;

    public static final String SCHEMA_NAME = "SagaStepRecord";

    private final int stepNumber;
    private final String stepName;
    private final String service;
    private final String eventType;
    private final StepStatus status;
    private final Instant timestamp;
    private final String eventId;
    private final String failureReason;

    private SagaStepRecord(Builder builder) {
        this.stepNumber = builder.stepNumber;
        this.stepName = builder.stepName;
        this.service = builder.service;
        this.eventType = builder.eventType;
        this.status = builder.status != null ? builder.status : StepStatus.PENDING;
        this.timestamp = builder.timestamp != null ? builder.timestamp : Instant.now();
        this.eventId = builder.eventId;
        this.failureReason = builder.failureReason;
    }

    // Getters

    /**
     * Returns the step number (0-indexed position in saga).
     *
     * @return the step number
     */
    public int getStepNumber() {
        return stepNumber;
    }

    /**
     * Returns the human-readable step name.
     *
     * @return the step name
     */
    public String getStepName() {
        return stepName;
    }

    /**
     * Returns the service responsible for this step.
     *
     * @return the service name
     */
    public String getService() {
        return service;
    }

    /**
     * Returns the event type that completes this step.
     *
     * @return the event type
     */
    public String getEventType() {
        return eventType;
    }

    /**
     * Returns the current status of this step.
     *
     * @return the step status
     */
    public StepStatus getStatus() {
        return status;
    }

    /**
     * Returns when this step was recorded/updated.
     *
     * @return the timestamp
     */
    public Instant getTimestamp() {
        return timestamp;
    }

    /**
     * Returns the event ID that completed this step (if any).
     *
     * @return the event ID, or null if step not completed
     */
    public String getEventId() {
        return eventId;
    }

    /**
     * Returns the failure reason (if step failed).
     *
     * @return the failure reason, or null if not failed
     */
    public String getFailureReason() {
        return failureReason;
    }

    /**
     * Creates a new step record with updated status.
     *
     * @param newStatus the new status
     * @return a new step record with updated status
     */
    public SagaStepRecord withStatus(StepStatus newStatus) {
        return builder()
                .stepNumber(this.stepNumber)
                .stepName(this.stepName)
                .service(this.service)
                .eventType(this.eventType)
                .status(newStatus)
                .timestamp(Instant.now())
                .eventId(this.eventId)
                .failureReason(this.failureReason)
                .build();
    }

    /**
     * Creates a new step record marking completion.
     *
     * @param eventId the event ID that completed this step
     * @return a new completed step record
     */
    public SagaStepRecord completed(String eventId) {
        return builder()
                .stepNumber(this.stepNumber)
                .stepName(this.stepName)
                .service(this.service)
                .eventType(this.eventType)
                .status(StepStatus.COMPLETED)
                .timestamp(Instant.now())
                .eventId(eventId)
                .build();
    }

    /**
     * Creates a new step record marking failure.
     *
     * @param reason the failure reason
     * @return a new failed step record
     */
    public SagaStepRecord failed(String reason) {
        return builder()
                .stepNumber(this.stepNumber)
                .stepName(this.stepName)
                .service(this.service)
                .eventType(this.eventType)
                .status(StepStatus.FAILED)
                .timestamp(Instant.now())
                .failureReason(reason)
                .build();
    }

    /**
     * Serializes this step record to a GenericRecord.
     *
     * @return GenericRecord representation
     */
    public GenericRecord toGenericRecord() {
        return GenericRecordBuilder.compact(SCHEMA_NAME)
                .setInt32("stepNumber", stepNumber)
                .setString("stepName", stepName)
                .setString("service", service)
                .setString("eventType", eventType)
                .setString("status", status.name())
                .setInt64("timestamp", timestamp.toEpochMilli())
                .setString("eventId", eventId)
                .setString("failureReason", failureReason)
                .build();
    }

    /**
     * Deserializes a step record from a GenericRecord.
     *
     * @param record the GenericRecord
     * @return the deserialized step record
     */
    public static SagaStepRecord fromGenericRecord(GenericRecord record) {
        return builder()
                .stepNumber(record.getInt32("stepNumber"))
                .stepName(record.getString("stepName"))
                .service(record.getString("service"))
                .eventType(record.getString("eventType"))
                .status(StepStatus.valueOf(record.getString("status")))
                .timestamp(Instant.ofEpochMilli(record.getInt64("timestamp")))
                .eventId(record.getString("eventId"))
                .failureReason(record.getString("failureReason"))
                .build();
    }

    @Override
    public String toString() {
        return "SagaStepRecord{" +
                "stepNumber=" + stepNumber +
                ", stepName='" + stepName + '\'' +
                ", service='" + service + '\'' +
                ", status=" + status +
                ", timestamp=" + timestamp +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        SagaStepRecord that = (SagaStepRecord) o;
        return stepNumber == that.stepNumber &&
                Objects.equals(stepName, that.stepName) &&
                Objects.equals(service, that.service) &&
                Objects.equals(eventType, that.eventType) &&
                status == that.status;
    }

    @Override
    public int hashCode() {
        return Objects.hash(stepNumber, stepName, service, eventType, status);
    }

    /**
     * Creates a new builder for SagaStepRecord.
     *
     * @return a new builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Builder for SagaStepRecord.
     */
    public static class Builder {
        private int stepNumber;
        private String stepName;
        private String service;
        private String eventType;
        private StepStatus status;
        private Instant timestamp;
        private String eventId;
        private String failureReason;

        public Builder stepNumber(int stepNumber) {
            this.stepNumber = stepNumber;
            return this;
        }

        public Builder stepName(String stepName) {
            this.stepName = stepName;
            return this;
        }

        public Builder service(String service) {
            this.service = service;
            return this;
        }

        public Builder eventType(String eventType) {
            this.eventType = eventType;
            return this;
        }

        public Builder status(StepStatus status) {
            this.status = status;
            return this;
        }

        public Builder timestamp(Instant timestamp) {
            this.timestamp = timestamp;
            return this;
        }

        public Builder eventId(String eventId) {
            this.eventId = eventId;
            return this;
        }

        public Builder failureReason(String failureReason) {
            this.failureReason = failureReason;
            return this;
        }

        public SagaStepRecord build() {
            return new SagaStepRecord(this);
        }
    }
}
