package com.theyawns.framework.saga;

import com.hazelcast.nio.serialization.genericrecord.GenericRecord;
import com.hazelcast.nio.serialization.genericrecord.GenericRecordBuilder;

import java.io.Serializable;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;

/**
 * Represents the current state of a saga instance.
 * Tracks progress through saga steps, handles compensation, and enforces timeouts.
 *
 * <p>A saga is a sequence of local transactions where each transaction
 * publishes events that trigger the next transaction. If a step fails,
 * compensation transactions are executed to undo the preceding steps.
 *
 * <p>This class supports both:
 * <ul>
 *   <li><strong>Choreography</strong>: Services react to events independently (Phase 2)</li>
 *   <li><strong>Orchestration</strong>: Central coordinator drives saga (future)</li>
 * </ul>
 *
 * <p>Example saga flow:
 * <pre>
 * SagaState saga = SagaState.start("saga-123", "OrderFulfillment", 4, Duration.ofSeconds(30));
 * saga = saga.recordStepCompleted(0, "OrderCreated", "order-service", "evt-1");
 * saga = saga.recordStepCompleted(1, "StockReserved", "inventory-service", "evt-2");
 * saga = saga.recordStepFailed(2, "PaymentFailed", "payment-service", "Insufficient funds");
 * saga = saga.startCompensation();
 * saga = saga.recordCompensationStep(1, "StockReleased", "inventory-service");
 * saga = saga.complete(SagaStatus.COMPENSATED);
 * </pre>
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
public class SagaState implements Serializable {

    private static final long serialVersionUID = 1L;

    public static final String SCHEMA_NAME = "SagaState";

    // Saga identification
    private final String sagaId;
    private final String sagaType;
    private final String correlationId;

    // Status tracking
    private final SagaStatus status;
    private final Instant startedAt;
    private final Instant completedAt;

    // Step tracking
    private final int currentStep;
    private final int totalSteps;
    private final List<SagaStepRecord> steps;

    // Timeout configuration
    private final Instant deadline;

    // Originating context
    private final String initiatingService;
    private final String initiatingEventId;

    // Failure tracking
    private final String failureReason;
    private final int failedAtStep;

    private SagaState(Builder builder) {
        this.sagaId = Objects.requireNonNull(builder.sagaId, "sagaId cannot be null");
        this.sagaType = Objects.requireNonNull(builder.sagaType, "sagaType cannot be null");
        this.correlationId = builder.correlationId;
        this.status = builder.status != null ? builder.status : SagaStatus.STARTED;
        this.startedAt = builder.startedAt != null ? builder.startedAt : Instant.now();
        this.completedAt = builder.completedAt;
        this.currentStep = builder.currentStep;
        this.totalSteps = builder.totalSteps;
        this.steps = builder.steps != null ? new ArrayList<>(builder.steps) : new ArrayList<>();
        this.deadline = builder.deadline;
        this.initiatingService = builder.initiatingService;
        this.initiatingEventId = builder.initiatingEventId;
        this.failureReason = builder.failureReason;
        this.failedAtStep = builder.failedAtStep;
    }

    /**
     * Creates a new saga instance.
     *
     * @param sagaId unique saga identifier
     * @param sagaType type of saga (e.g., "OrderFulfillment")
     * @param totalSteps total number of steps in the saga
     * @param timeout maximum duration before timeout
     * @return a new saga state in STARTED status
     */
    public static SagaState start(String sagaId, String sagaType, int totalSteps, Duration timeout) {
        return builder()
                .sagaId(sagaId)
                .sagaType(sagaType)
                .totalSteps(totalSteps)
                .status(SagaStatus.STARTED)
                .deadline(Instant.now().plus(timeout))
                .build();
    }

    /**
     * Creates a new saga instance with correlation ID.
     *
     * @param sagaId unique saga identifier
     * @param sagaType type of saga
     * @param correlationId correlation ID linking related events
     * @param totalSteps total number of steps
     * @param timeout maximum duration before timeout
     * @return a new saga state in STARTED status
     */
    public static SagaState start(String sagaId, String sagaType, String correlationId,
                                   int totalSteps, Duration timeout) {
        return builder()
                .sagaId(sagaId)
                .sagaType(sagaType)
                .correlationId(correlationId)
                .totalSteps(totalSteps)
                .status(SagaStatus.STARTED)
                .deadline(Instant.now().plus(timeout))
                .build();
    }

    // State transition methods

    /**
     * Records that a step has completed successfully.
     *
     * @param stepNumber the step number (0-indexed)
     * @param eventType the event type that completed the step
     * @param service the service that completed the step
     * @param eventId the ID of the completing event
     * @return updated saga state
     */
    public SagaState recordStepCompleted(int stepNumber, String eventType,
                                          String service, String eventId) {
        List<SagaStepRecord> newSteps = new ArrayList<>(this.steps);

        SagaStepRecord stepRecord = SagaStepRecord.builder()
                .stepNumber(stepNumber)
                .stepName(eventType)
                .service(service)
                .eventType(eventType)
                .status(StepStatus.COMPLETED)
                .eventId(eventId)
                .build();

        // Update or add the step record
        updateOrAddStep(newSteps, stepRecord);

        SagaStatus newStatus = (stepNumber >= totalSteps - 1) ?
                SagaStatus.COMPLETED : SagaStatus.IN_PROGRESS;

        return toBuilder()
                .currentStep(stepNumber + 1)
                .steps(newSteps)
                .status(newStatus)
                .completedAt(newStatus == SagaStatus.COMPLETED ? Instant.now() : null)
                .build();
    }

    /**
     * Records that a step has failed.
     *
     * @param stepNumber the step number that failed
     * @param eventType the event type
     * @param service the service where failure occurred
     * @param reason the failure reason
     * @return updated saga state
     */
    public SagaState recordStepFailed(int stepNumber, String eventType,
                                       String service, String reason) {
        List<SagaStepRecord> newSteps = new ArrayList<>(this.steps);

        SagaStepRecord stepRecord = SagaStepRecord.builder()
                .stepNumber(stepNumber)
                .stepName(eventType)
                .service(service)
                .eventType(eventType)
                .status(StepStatus.FAILED)
                .failureReason(reason)
                .build();

        updateOrAddStep(newSteps, stepRecord);

        return toBuilder()
                .currentStep(stepNumber)
                .steps(newSteps)
                .status(SagaStatus.COMPENSATING)
                .failureReason(reason)
                .failedAtStep(stepNumber)
                .build();
    }

    /**
     * Marks the saga as starting compensation.
     *
     * @return updated saga state in COMPENSATING status
     */
    public SagaState startCompensation() {
        return toBuilder()
                .status(SagaStatus.COMPENSATING)
                .build();
    }

    /**
     * Records that a compensation step has completed.
     *
     * @param stepNumber the step being compensated
     * @param eventType the compensation event type
     * @param service the service performing compensation
     * @return updated saga state
     */
    public SagaState recordCompensationStep(int stepNumber, String eventType, String service) {
        List<SagaStepRecord> newSteps = new ArrayList<>(this.steps);

        // Find and update the original step
        for (int i = 0; i < newSteps.size(); i++) {
            SagaStepRecord step = newSteps.get(i);
            if (step.getStepNumber() == stepNumber) {
                newSteps.set(i, step.withStatus(StepStatus.COMPENSATED));
                break;
            }
        }

        return toBuilder()
                .steps(newSteps)
                .build();
    }

    /**
     * Marks the saga as complete with the given outcome.
     *
     * @param outcome the final status (COMPLETED, COMPENSATED, FAILED)
     * @return updated saga state
     */
    public SagaState complete(SagaStatus outcome) {
        if (!outcome.isTerminal()) {
            throw new IllegalArgumentException("Cannot complete saga with non-terminal status: " + outcome);
        }
        return toBuilder()
                .status(outcome)
                .completedAt(Instant.now())
                .build();
    }

    /**
     * Marks the saga as timed out.
     *
     * @return updated saga state
     */
    public SagaState timedOut() {
        return toBuilder()
                .status(SagaStatus.TIMED_OUT)
                .completedAt(Instant.now())
                .failureReason("Saga exceeded deadline")
                .build();
    }

    // Query methods

    /**
     * Returns true if the saga has exceeded its deadline.
     *
     * @return true if timed out
     */
    public boolean isTimedOut() {
        return deadline != null && Instant.now().isAfter(deadline) && status.isActive();
    }

    /**
     * Returns the duration since the saga started.
     *
     * @return duration since start
     */
    public Duration getDuration() {
        Instant end = completedAt != null ? completedAt : Instant.now();
        return Duration.between(startedAt, end);
    }

    /**
     * Returns the steps that need compensation (completed steps in reverse order).
     *
     * @return list of steps needing compensation
     */
    public List<SagaStepRecord> getStepsNeedingCompensation() {
        List<SagaStepRecord> needsCompensation = steps.stream()
                .filter(s -> s.getStatus().needsCompensation())
                .collect(Collectors.toList());
        Collections.reverse(needsCompensation);
        return needsCompensation;
    }

    /**
     * Returns progress as a percentage (0-100).
     *
     * @return progress percentage
     */
    public int getProgressPercentage() {
        if (totalSteps == 0) return 0;
        return (currentStep * 100) / totalSteps;
    }

    // Getters

    public String getSagaId() {
        return sagaId;
    }

    public String getSagaType() {
        return sagaType;
    }

    public String getCorrelationId() {
        return correlationId;
    }

    public SagaStatus getStatus() {
        return status;
    }

    public Instant getStartedAt() {
        return startedAt;
    }

    public Instant getCompletedAt() {
        return completedAt;
    }

    public int getCurrentStep() {
        return currentStep;
    }

    public int getTotalSteps() {
        return totalSteps;
    }

    public List<SagaStepRecord> getSteps() {
        return Collections.unmodifiableList(steps);
    }

    public Instant getDeadline() {
        return deadline;
    }

    public String getInitiatingService() {
        return initiatingService;
    }

    public String getInitiatingEventId() {
        return initiatingEventId;
    }

    public String getFailureReason() {
        return failureReason;
    }

    public int getFailedAtStep() {
        return failedAtStep;
    }

    // Serialization

    /**
     * Serializes this saga state to a GenericRecord.
     *
     * @return GenericRecord representation
     */
    public GenericRecord toGenericRecord() {
        GenericRecord[] stepRecords = steps.stream()
                .map(SagaStepRecord::toGenericRecord)
                .toArray(GenericRecord[]::new);

        return GenericRecordBuilder.compact(SCHEMA_NAME)
                .setString("sagaId", sagaId)
                .setString("sagaType", sagaType)
                .setString("correlationId", correlationId)
                .setString("status", status.name())
                .setInt64("startedAt", startedAt.toEpochMilli())
                .setNullableInt64("completedAt", completedAt != null ? completedAt.toEpochMilli() : null)
                .setInt32("currentStep", currentStep)
                .setInt32("totalSteps", totalSteps)
                .setArrayOfGenericRecord("steps", stepRecords)
                .setNullableInt64("deadline", deadline != null ? deadline.toEpochMilli() : null)
                .setString("initiatingService", initiatingService)
                .setString("initiatingEventId", initiatingEventId)
                .setString("failureReason", failureReason)
                .setInt32("failedAtStep", failedAtStep)
                .build();
    }

    /**
     * Deserializes a saga state from a GenericRecord.
     *
     * @param record the GenericRecord
     * @return the deserialized saga state
     */
    public static SagaState fromGenericRecord(GenericRecord record) {
        List<SagaStepRecord> steps = new ArrayList<>();
        GenericRecord[] stepRecords = record.getArrayOfGenericRecord("steps");
        if (stepRecords != null) {
            for (GenericRecord stepRecord : stepRecords) {
                steps.add(SagaStepRecord.fromGenericRecord(stepRecord));
            }
        }

        Long completedAtMillis = record.getNullableInt64("completedAt");
        Long deadlineMillis = record.getNullableInt64("deadline");

        return builder()
                .sagaId(record.getString("sagaId"))
                .sagaType(record.getString("sagaType"))
                .correlationId(record.getString("correlationId"))
                .status(SagaStatus.valueOf(record.getString("status")))
                .startedAt(Instant.ofEpochMilli(record.getInt64("startedAt")))
                .completedAt(completedAtMillis != null ? Instant.ofEpochMilli(completedAtMillis) : null)
                .currentStep(record.getInt32("currentStep"))
                .totalSteps(record.getInt32("totalSteps"))
                .steps(steps)
                .deadline(deadlineMillis != null ? Instant.ofEpochMilli(deadlineMillis) : null)
                .initiatingService(record.getString("initiatingService"))
                .initiatingEventId(record.getString("initiatingEventId"))
                .failureReason(record.getString("failureReason"))
                .failedAtStep(record.getInt32("failedAtStep"))
                .build();
    }

    @Override
    public String toString() {
        return "SagaState{" +
                "sagaId='" + sagaId + '\'' +
                ", sagaType='" + sagaType + '\'' +
                ", status=" + status +
                ", currentStep=" + currentStep + "/" + totalSteps +
                ", duration=" + getDuration().toMillis() + "ms" +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        SagaState sagaState = (SagaState) o;
        return Objects.equals(sagaId, sagaState.sagaId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(sagaId);
    }

    // Helper methods

    private void updateOrAddStep(List<SagaStepRecord> steps, SagaStepRecord newStep) {
        for (int i = 0; i < steps.size(); i++) {
            if (steps.get(i).getStepNumber() == newStep.getStepNumber()) {
                steps.set(i, newStep);
                return;
            }
        }
        steps.add(newStep);
    }

    // Builder

    public static Builder builder() {
        return new Builder();
    }

    private Builder toBuilder() {
        return builder()
                .sagaId(this.sagaId)
                .sagaType(this.sagaType)
                .correlationId(this.correlationId)
                .status(this.status)
                .startedAt(this.startedAt)
                .completedAt(this.completedAt)
                .currentStep(this.currentStep)
                .totalSteps(this.totalSteps)
                .steps(this.steps)
                .deadline(this.deadline)
                .initiatingService(this.initiatingService)
                .initiatingEventId(this.initiatingEventId)
                .failureReason(this.failureReason)
                .failedAtStep(this.failedAtStep);
    }

    public static class Builder {
        private String sagaId;
        private String sagaType;
        private String correlationId;
        private SagaStatus status;
        private Instant startedAt;
        private Instant completedAt;
        private int currentStep;
        private int totalSteps;
        private List<SagaStepRecord> steps;
        private Instant deadline;
        private String initiatingService;
        private String initiatingEventId;
        private String failureReason;
        private int failedAtStep = -1;

        public Builder sagaId(String sagaId) {
            this.sagaId = sagaId;
            return this;
        }

        public Builder sagaType(String sagaType) {
            this.sagaType = sagaType;
            return this;
        }

        public Builder correlationId(String correlationId) {
            this.correlationId = correlationId;
            return this;
        }

        public Builder status(SagaStatus status) {
            this.status = status;
            return this;
        }

        public Builder startedAt(Instant startedAt) {
            this.startedAt = startedAt;
            return this;
        }

        public Builder completedAt(Instant completedAt) {
            this.completedAt = completedAt;
            return this;
        }

        public Builder currentStep(int currentStep) {
            this.currentStep = currentStep;
            return this;
        }

        public Builder totalSteps(int totalSteps) {
            this.totalSteps = totalSteps;
            return this;
        }

        public Builder steps(List<SagaStepRecord> steps) {
            this.steps = steps;
            return this;
        }

        public Builder deadline(Instant deadline) {
            this.deadline = deadline;
            return this;
        }

        public Builder initiatingService(String initiatingService) {
            this.initiatingService = initiatingService;
            return this;
        }

        public Builder initiatingEventId(String initiatingEventId) {
            this.initiatingEventId = initiatingEventId;
            return this;
        }

        public Builder failureReason(String failureReason) {
            this.failureReason = failureReason;
            return this;
        }

        public Builder failedAtStep(int failedAtStep) {
            this.failedAtStep = failedAtStep;
            return this;
        }

        public SagaState build() {
            return new SagaState(this);
        }
    }
}
