package com.theyawns.framework.saga;

import com.theyawns.framework.domain.DomainObject;

/**
 * Marker interface for events that participate in sagas.
 * Extends domain events with saga-specific contracts for compensation support.
 *
 * <p>Events implementing this interface can be tracked through saga execution
 * and automatically compensated on failure. Each saga event declares:
 * <ul>
 *   <li>Its step number in the saga sequence</li>
 *   <li>The event type that compensates (undoes) this event</li>
 *   <li>Whether this event itself is a compensation event</li>
 * </ul>
 *
 * <p>Example implementation:
 * <pre>
 * public class StockReservedEvent extends DomainEvent&lt;Product, String&gt;
 *     implements SagaEvent&lt;Product, String&gt; {
 *
 *     &#64;Override
 *     public int getSagaStepNumber() {
 *         return 2; // Second step in OrderFulfillment saga
 *     }
 *
 *     &#64;Override
 *     public String getCompensatingEventType() {
 *         return "StockReleased"; // Event that undoes stock reservation
 *     }
 *
 *     &#64;Override
 *     public boolean isCompensatingEvent() {
 *         return false; // This is a forward event, not compensation
 *     }
 * }
 * </pre>
 *
 * <p>The {@link CompensationRegistry} uses this interface to look up how
 * to compensate events when a saga needs to roll back.
 *
 * @param <D> The domain object type this event affects
 * @param <K> The key type of the domain object
 * @author Generated by Claude Code
 * @since 2.0
 * @see CompensationRegistry
 * @see SagaState
 */
public interface SagaEvent<D extends DomainObject<K>, K> {

    /**
     * Returns the step number for this event in a saga sequence.
     *
     * <p>Step numbers should be 0-indexed and consecutive within a saga type.
     * For example, in an OrderFulfillment saga:
     * <ul>
     *   <li>Step 0: OrderCreated</li>
     *   <li>Step 1: StockReserved</li>
     *   <li>Step 2: PaymentProcessed</li>
     *   <li>Step 3: OrderConfirmed</li>
     * </ul>
     *
     * @return the zero-indexed step number in the saga sequence
     */
    int getSagaStepNumber();

    /**
     * Returns the event type that compensates (undoes) this event.
     *
     * <p>When a saga needs to roll back, the system uses this method to
     * determine which event should be triggered to undo the effects of
     * this event.
     *
     * <p>Returns {@code null} if this event does not need compensation.
     * This is typically the case for:
     * <ul>
     *   <li>Events that are already compensation events</li>
     *   <li>Events with no side effects to undo</li>
     *   <li>The final step in a saga (nothing to compensate after success)</li>
     * </ul>
     *
     * <p>Examples:
     * <ul>
     *   <li>StockReserved -&gt; "StockReleased"</li>
     *   <li>PaymentProcessed -&gt; "PaymentRefunded"</li>
     *   <li>OrderCreated -&gt; "OrderCancelled"</li>
     * </ul>
     *
     * @return the event type name of the compensating event, or null if none
     */
    String getCompensatingEventType();

    /**
     * Returns true if this event is a compensation (rollback) event.
     *
     * <p>Compensation events are triggered when a saga needs to undo
     * previously completed steps. They are processed differently:
     * <ul>
     *   <li>They don't trigger further saga steps</li>
     *   <li>They are tracked in the SagaState as compensation progress</li>
     *   <li>They don't have their own compensating events</li>
     * </ul>
     *
     * <p>Examples of compensation events:
     * <ul>
     *   <li>StockReleased (compensates StockReserved)</li>
     *   <li>PaymentRefunded (compensates PaymentProcessed)</li>
     *   <li>OrderCancelled (compensates OrderCreated)</li>
     * </ul>
     *
     * @return true if this is a compensation event, false if it's a forward event
     */
    boolean isCompensatingEvent();

    /**
     * Returns the saga type this event participates in.
     *
     * <p>This is a convenience method that returns the saga type name.
     * The default implementation returns null, meaning the event can
     * participate in any saga. Override to restrict to a specific saga.
     *
     * <p>Examples: "OrderFulfillment", "CustomerOnboarding", "PaymentProcessing"
     *
     * @return the saga type name, or null if unrestricted
     */
    default String getSagaTypeName() {
        return null;
    }

    /**
     * Returns true if this event requires acknowledgment before the saga proceeds.
     *
     * <p>Some events (like payment processing) may require explicit acknowledgment
     * before the saga should continue. The default is false (no explicit ack needed).
     *
     * @return true if explicit acknowledgment is required
     */
    default boolean requiresAcknowledgment() {
        return false;
    }

    /**
     * Returns the maximum time in milliseconds to wait for this step to complete.
     *
     * <p>If this timeout is exceeded, the saga may be marked as timed out
     * and compensation triggered. The default is -1, meaning use the saga's
     * overall timeout instead of a step-specific one.
     *
     * @return step timeout in milliseconds, or -1 to use saga default
     */
    default long getStepTimeoutMillis() {
        return -1;
    }
}
