package com.theyawns.framework.saga;

import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.Timer;

import java.time.Duration;
import java.util.Objects;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicLong;

/**
 * Metrics collection for saga operations.
 * Provides instrumentation using Micrometer with cached counters and timers
 * for high-performance metric recording.
 *
 * <p>Key metrics collected:
 * <ul>
 *   <li>Saga lifecycle counters (started, completed, compensated, failed)</li>
 *   <li>Step counters (completed, failed, compensation steps)</li>
 *   <li>Saga duration timers with percentiles (overall, compensation)</li>
 *   <li>Active/compensating saga gauges</li>
 *   <li>Timeout detection counters</li>
 * </ul>
 *
 * <p>All counters and timers are tagged with {@code sagaType} for
 * fine-grained monitoring per saga definition.
 *
 * <p>Example usage:
 * <pre>{@code
 * SagaMetrics metrics = new SagaMetrics(meterRegistry);
 * metrics.recordSagaStarted("OrderFulfillment");
 * metrics.recordStepCompleted("OrderFulfillment");
 * metrics.recordSagaDuration("OrderFulfillment", Duration.ofMillis(250));
 * }</pre>
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
public class SagaMetrics {

    public static final String PREFIX = "saga";

    private final MeterRegistry meterRegistry;

    // Cached counters and timers for performance
    private final ConcurrentMap<String, Counter> counterCache;
    private final ConcurrentMap<String, Timer> timerCache;

    // Lifecycle gauges backed by AtomicLong
    private final AtomicLong sagasStartedTotal = new AtomicLong(0);
    private final AtomicLong sagasCompletedTotal = new AtomicLong(0);
    private final AtomicLong sagasCompensatedTotal = new AtomicLong(0);
    private final AtomicLong sagasFailedTotal = new AtomicLong(0);
    private final AtomicLong sagasTimedOutTotal = new AtomicLong(0);

    // Active saga tracking gauges
    private final AtomicLong sagasActiveCount = new AtomicLong(0);
    private final AtomicLong sagasCompensatingCount = new AtomicLong(0);

    /**
     * Creates a SagaMetrics instance.
     *
     * @param meterRegistry the Micrometer registry for metrics
     * @throws NullPointerException if meterRegistry is null
     */
    public SagaMetrics(MeterRegistry meterRegistry) {
        this.meterRegistry = Objects.requireNonNull(meterRegistry, "meterRegistry cannot be null");
        this.counterCache = new ConcurrentHashMap<>();
        this.timerCache = new ConcurrentHashMap<>();

        registerGauges();
    }

    private void registerGauges() {
        meterRegistry.gauge(PREFIX + ".started.total", sagasStartedTotal);
        meterRegistry.gauge(PREFIX + ".completed.total", sagasCompletedTotal);
        meterRegistry.gauge(PREFIX + ".compensated.total", sagasCompensatedTotal);
        meterRegistry.gauge(PREFIX + ".failed.total", sagasFailedTotal);
        meterRegistry.gauge(PREFIX + ".timedout.total", sagasTimedOutTotal);
        meterRegistry.gauge("sagas.active.count", sagasActiveCount);
        meterRegistry.gauge("sagas.compensating.count", sagasCompensatingCount);
    }

    // ========== Saga Lifecycle ==========

    /**
     * Records that a saga was started.
     * Also increments the active saga count.
     *
     * @param sagaType the saga type name
     */
    public void recordSagaStarted(String sagaType) {
        sagasStartedTotal.incrementAndGet();
        sagasActiveCount.incrementAndGet();
        getCounter("started", sagaType).increment();
    }

    /**
     * Records that a saga completed successfully.
     * Decrements the active saga count.
     *
     * @param sagaType the saga type name
     */
    public void recordSagaCompleted(String sagaType) {
        sagasCompletedTotal.incrementAndGet();
        sagasActiveCount.decrementAndGet();
        getCounter("completed", sagaType).increment();
    }

    /**
     * Records that a saga was compensated.
     * Decrements the active saga count and the compensating count.
     *
     * @param sagaType the saga type name
     */
    public void recordSagaCompensated(String sagaType) {
        sagasCompensatedTotal.incrementAndGet();
        sagasActiveCount.decrementAndGet();
        sagasCompensatingCount.decrementAndGet();
        getCounter("compensated", sagaType).increment();
    }

    /**
     * Records that a saga failed.
     * Decrements the active saga count.
     *
     * @param sagaType the saga type name
     */
    public void recordSagaFailed(String sagaType) {
        sagasFailedTotal.incrementAndGet();
        sagasActiveCount.decrementAndGet();
        getCounter("failed", sagaType).increment();
    }

    /**
     * Records that a saga timed out.
     * Decrements the active saga count.
     *
     * @param sagaType the saga type name
     */
    public void recordSagaTimedOut(String sagaType) {
        sagasTimedOutTotal.incrementAndGet();
        sagasActiveCount.decrementAndGet();
        getCounter("timedout", sagaType).increment();
    }

    // ========== Step Metrics ==========

    /**
     * Records that a saga step was completed.
     *
     * @param sagaType the saga type name
     */
    public void recordStepCompleted(String sagaType) {
        getCounter("steps.completed", sagaType).increment();
    }

    /**
     * Records that a saga step failed.
     *
     * @param sagaType the saga type name
     */
    public void recordStepFailed(String sagaType) {
        getCounter("steps.failed", sagaType).increment();
    }

    /**
     * Records that a compensation step was executed.
     *
     * @param sagaType the saga type name
     */
    public void recordCompensationStep(String sagaType) {
        getCounter("compensation.steps", sagaType).increment();
    }

    /**
     * Records that compensation was started for a saga.
     * Increments the compensating saga count.
     *
     * @param sagaType the saga type name
     */
    public void recordCompensationStarted(String sagaType) {
        sagasCompensatingCount.incrementAndGet();
        getCounter("compensation.started", sagaType).increment();
    }

    /**
     * Records that compensation completed successfully for a saga.
     *
     * @param sagaType the saga type name
     */
    public void recordCompensationCompleted(String sagaType) {
        getCounter("compensation.completed", sagaType).increment();
    }

    /**
     * Records that compensation failed for a saga.
     *
     * @param sagaType the saga type name
     */
    public void recordCompensationFailed(String sagaType) {
        getCounter("compensation.failed", sagaType).increment();
    }

    // ========== Duration Metrics ==========

    /**
     * Records the duration of a single saga step.
     *
     * @param sagaType the saga type name
     * @param stepName the step name
     * @param duration the step duration
     */
    public void recordStepDuration(String sagaType, String stepName, Duration duration) {
        if (duration != null) {
            getStepTimer(sagaType, stepName)
                    .record(duration.toNanos(), TimeUnit.NANOSECONDS);
        }
    }

    /**
     * Records the overall duration of a completed saga.
     *
     * @param sagaType the saga type name
     * @param duration the saga duration
     */
    public void recordSagaDuration(String sagaType, Duration duration) {
        if (duration != null) {
            getTimer("duration", sagaType)
                    .record(duration.toNanos(), TimeUnit.NANOSECONDS);
        }
    }

    /**
     * Records the duration of a compensation process.
     *
     * @param sagaType the saga type name
     * @param duration the compensation duration
     */
    public void recordCompensationDuration(String sagaType, Duration duration) {
        if (duration != null) {
            getTimer("compensation.duration", sagaType)
                    .record(duration.toNanos(), TimeUnit.NANOSECONDS);
        }
    }

    // ========== Gauge Accessors ==========

    /**
     * Returns the total number of sagas started.
     *
     * @return total sagas started
     */
    public long getSagasStartedTotal() {
        return sagasStartedTotal.get();
    }

    /**
     * Returns the total number of sagas completed successfully.
     *
     * @return total sagas completed
     */
    public long getSagasCompletedTotal() {
        return sagasCompletedTotal.get();
    }

    /**
     * Returns the total number of sagas compensated.
     *
     * @return total sagas compensated
     */
    public long getSagasCompensatedTotal() {
        return sagasCompensatedTotal.get();
    }

    /**
     * Returns the total number of sagas failed.
     *
     * @return total sagas failed
     */
    public long getSagasFailedTotal() {
        return sagasFailedTotal.get();
    }

    /**
     * Returns the total number of sagas timed out.
     *
     * @return total sagas timed out
     */
    public long getSagasTimedOutTotal() {
        return sagasTimedOutTotal.get();
    }

    /**
     * Returns the current number of active (in-progress) sagas.
     *
     * @return active saga count
     */
    public long getSagasActiveCount() {
        return sagasActiveCount.get();
    }

    /**
     * Returns the current number of sagas undergoing compensation.
     *
     * @return compensating saga count
     */
    public long getSagasCompensatingCount() {
        return sagasCompensatingCount.get();
    }

    /**
     * Returns the Micrometer registry used by this instance.
     *
     * @return the meter registry
     */
    public MeterRegistry getMeterRegistry() {
        return meterRegistry;
    }

    // ========== Internal Helpers ==========

    private Counter getCounter(String name, String sagaType) {
        String key = name + ":" + sagaType;
        return counterCache.computeIfAbsent(key, k ->
                Counter.builder(PREFIX + "." + name)
                        .tag("sagaType", sagaType)
                        .register(meterRegistry)
        );
    }

    private Timer getTimer(String name, String sagaType) {
        String key = name + ":" + sagaType;
        return timerCache.computeIfAbsent(key, k ->
                Timer.builder(PREFIX + "." + name)
                        .tag("sagaType", sagaType)
                        .publishPercentiles(0.5, 0.95, 0.99)
                        .register(meterRegistry)
        );
    }

    private Timer getStepTimer(String sagaType, String stepName) {
        String key = "step.duration:" + sagaType + ":" + stepName;
        return timerCache.computeIfAbsent(key, k ->
                Timer.builder(PREFIX + ".step.duration")
                        .tag("sagaType", sagaType)
                        .tag("stepName", stepName)
                        .publishPercentiles(0.5, 0.95, 0.99)
                        .register(meterRegistry)
        );
    }
}
