package com.theyawns.framework.saga;

/**
 * Represents the current status of a saga instance.
 *
 * <p>Saga lifecycle:
 * <pre>
 * STARTED → IN_PROGRESS → COMPLETED (happy path)
 *                       → COMPENSATING → COMPENSATED (rollback path)
 *                       → FAILED (unrecoverable error)
 *                       → TIMED_OUT (deadline exceeded)
 * </pre>
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
public enum SagaStatus {

    /**
     * Saga has been initiated but no steps have completed yet.
     */
    STARTED,

    /**
     * Saga is actively processing steps.
     */
    IN_PROGRESS,

    /**
     * All steps completed successfully.
     */
    COMPLETED,

    /**
     * A step failed and compensation is in progress.
     */
    COMPENSATING,

    /**
     * All compensation steps completed successfully.
     */
    COMPENSATED,

    /**
     * Saga failed and could not be compensated.
     */
    FAILED,

    /**
     * Saga exceeded its deadline without completing.
     */
    TIMED_OUT;

    /**
     * Returns true if the saga is in a terminal state (no more transitions expected).
     *
     * @return true if terminal
     */
    public boolean isTerminal() {
        return this == COMPLETED || this == COMPENSATED || this == FAILED || this == TIMED_OUT;
    }

    /**
     * Returns true if the saga is still active (may have more transitions).
     *
     * @return true if active
     */
    public boolean isActive() {
        return this == STARTED || this == IN_PROGRESS || this == COMPENSATING;
    }

    /**
     * Returns true if the saga completed successfully.
     *
     * @return true if successful
     */
    public boolean isSuccessful() {
        return this == COMPLETED;
    }

    /**
     * Returns true if the saga is in a failure/rollback state.
     *
     * @return true if failed or rolling back
     */
    public boolean isFailure() {
        return this == COMPENSATING || this == COMPENSATED || this == FAILED || this == TIMED_OUT;
    }
}
