package com.theyawns.framework.saga;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Spring configuration for saga compensation infrastructure.
 * Sets up the CompensationRegistry bean and registers default mappings.
 *
 * <p>This configuration creates a singleton CompensationRegistry that can be
 * customized by applications. Services can add their own compensation mappings
 * by injecting the registry and calling register().
 *
 * <p>Example custom configuration:
 * <pre>
 * &#64;Configuration
 * public class MyServiceSagaConfig {
 *
 *     &#64;Autowired
 *     public void configureCompensations(CompensationRegistry registry) {
 *         registry.register("MyEvent", "MyCompensatingEvent", "my-service");
 *     }
 * }
 * </pre>
 *
 * @author Generated by Claude Code
 * @since 2.0
 * @see CompensationRegistry
 */
@Configuration
public class SagaCompensationConfig {

    private static final Logger logger = LoggerFactory.getLogger(SagaCompensationConfig.class);

    /**
     * Creates the CompensationRegistry bean.
     * Only created if no other CompensationRegistry bean exists.
     *
     * @return a new CompensationRegistry instance
     */
    @Bean
    @ConditionalOnMissingBean
    public CompensationRegistry compensationRegistry() {
        logger.info("Creating CompensationRegistry bean");
        return new CompensationRegistry();
    }

}
