package com.theyawns.framework.saga;

import java.util.concurrent.CompletableFuture;

/**
 * Interface for triggering saga compensation (rollback) operations.
 *
 * <p>When a saga fails or times out, the compensator is responsible for
 * undoing the effects of previously completed steps. This is done by
 * triggering compensation events for each step that needs to be rolled back.
 *
 * <p>Compensation typically happens in reverse order of execution:
 * <pre>
 * Original saga:  Step1 → Step2 → Step3 (failed)
 * Compensation:   Compensate(Step2) → Compensate(Step1)
 * </pre>
 *
 * <p>The compensator works with the {@link CompensationRegistry} to determine
 * which events compensate which steps, and uses the messaging infrastructure
 * to publish compensation events.
 *
 * <p>Example usage:
 * <pre>{@code
 * SagaCompensator compensator = ...;
 * SagaState timedOutSaga = ...;
 *
 * CompletableFuture<CompensationResult> result = compensator.compensate(timedOutSaga);
 * result.thenAccept(r -> {
 *     if (r.isSuccess()) {
 *         logger.info("Compensation completed for saga: {}", timedOutSaga.getSagaId());
 *     } else {
 *         logger.error("Compensation failed: {}", r.getFailureReason());
 *     }
 * });
 * }</pre>
 *
 * @author Generated by Claude Code
 * @since 2.0
 * @see CompensationRegistry
 * @see SagaState
 * @see SagaTimeoutDetector
 */
public interface SagaCompensator {

    /**
     * Initiates compensation for a saga.
     *
     * <p>This method identifies which steps need compensation and triggers
     * the appropriate compensation events for each. Compensation is performed
     * in reverse order of the original step execution.
     *
     * @param sagaState the saga state containing steps to compensate
     * @return CompletableFuture that completes when compensation is initiated
     */
    CompletableFuture<CompensationResult> compensate(SagaState sagaState);

    /**
     * Compensates a specific step of a saga.
     *
     * <p>Used when fine-grained control over compensation is needed,
     * or when retrying a specific compensation step.
     *
     * @param sagaState the saga state
     * @param stepRecord the specific step to compensate
     * @return CompletableFuture that completes when compensation is initiated
     */
    CompletableFuture<CompensationResult> compensateStep(SagaState sagaState, SagaStepRecord stepRecord);

    /**
     * Checks if compensation can be performed for a saga.
     *
     * <p>A saga can be compensated if:
     * <ul>
     *   <li>It has at least one completed step that needs compensation</li>
     *   <li>Compensation mappings exist for the steps</li>
     *   <li>The saga is not already in a terminal state</li>
     * </ul>
     *
     * @param sagaState the saga state to check
     * @return true if compensation can be initiated
     */
    boolean canCompensate(SagaState sagaState);

    /**
     * Represents the result of a compensation operation.
     */
    record CompensationResult(
            String sagaId,
            boolean success,
            int stepsCompensated,
            int stepsFailed,
            String failureReason
    ) {
        /**
         * Creates a successful compensation result.
         *
         * @param sagaId the saga ID
         * @param stepsCompensated number of steps compensated
         * @return success result
         */
        public static CompensationResult success(String sagaId, int stepsCompensated) {
            return new CompensationResult(sagaId, true, stepsCompensated, 0, null);
        }

        /**
         * Creates a failed compensation result.
         *
         * @param sagaId the saga ID
         * @param stepsCompensated number of steps that were compensated before failure
         * @param stepsFailed number of steps that failed to compensate
         * @param reason the failure reason
         * @return failure result
         */
        public static CompensationResult failure(String sagaId, int stepsCompensated,
                                                  int stepsFailed, String reason) {
            return new CompensationResult(sagaId, false, stepsCompensated, stepsFailed, reason);
        }

        /**
         * Creates a result indicating no compensation was needed.
         *
         * @param sagaId the saga ID
         * @return no-op result
         */
        public static CompensationResult noCompensationNeeded(String sagaId) {
            return new CompensationResult(sagaId, true, 0, 0, "No steps required compensation");
        }

        /**
         * Returns true if compensation was successful.
         *
         * @return true if successful
         */
        public boolean isSuccess() {
            return success;
        }
    }
}
