package com.theyawns.framework.saga;

/**
 * Represents the status of an individual step within a saga.
 *
 * <p>Step lifecycle:
 * <pre>
 * PENDING → COMPLETED (success)
 *         → FAILED (error)
 *         → SKIPPED (not executed due to earlier failure)
 *         → COMPENSATED (rollback completed)
 * </pre>
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
public enum StepStatus {

    /**
     * Step has not yet been executed.
     */
    PENDING,

    /**
     * Step executed successfully.
     */
    COMPLETED,

    /**
     * Step execution failed.
     */
    FAILED,

    /**
     * Step was skipped due to an earlier failure.
     */
    SKIPPED,

    /**
     * Step has been compensated (rolled back).
     */
    COMPENSATED;

    /**
     * Returns true if this step needs compensation.
     * Only COMPLETED steps need to be compensated on rollback.
     *
     * @return true if compensation is needed
     */
    public boolean needsCompensation() {
        return this == COMPLETED;
    }

    /**
     * Returns true if this step is in a terminal state.
     *
     * @return true if terminal
     */
    public boolean isTerminal() {
        return this == COMPLETED || this == FAILED || this == SKIPPED || this == COMPENSATED;
    }
}
