package com.theyawns.framework.persistence.postgres;

import com.theyawns.framework.persistence.DlqStorePersistence;
import com.theyawns.framework.persistence.PersistableDeadLetterEntry;
import com.theyawns.framework.persistence.postgres.entity.DeadLetterEntity;
import com.theyawns.framework.persistence.postgres.repository.DeadLetterRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.Optional;

/**
 * PostgreSQL implementation of {@link DlqStorePersistence}.
 *
 * <p>Uses JDBC upsert semantics ({@code INSERT ... ON CONFLICT DO UPDATE}) since
 * DLQ entries transition through status changes (PENDING → REPLAYED/DISCARDED)
 * and only the latest state matters.
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
public class PostgresDlqStorePersistence implements DlqStorePersistence {

    private static final Logger logger = LoggerFactory.getLogger(PostgresDlqStorePersistence.class);

    private static final String UPSERT_SQL =
            "INSERT INTO domain_dead_letters (dlq_entry_id, original_event_id, event_type, topic_name, " +
            "event_data, failure_reason, failure_timestamp_millis, source_service, saga_id, correlation_id, " +
            "replay_count, status, updated_at) " +
            "VALUES (?, ?, ?, ?, ?::jsonb, ?, ?, ?, ?, ?, ?, ?, NOW()) " +
            "ON CONFLICT (dlq_entry_id) DO UPDATE SET " +
            "replay_count = EXCLUDED.replay_count, " +
            "status = EXCLUDED.status, " +
            "updated_at = NOW()";

    private final DeadLetterRepository repository;
    private final JdbcTemplate jdbcTemplate;

    /**
     * Creates a new PostgresDlqStorePersistence.
     *
     * @param repository the JPA repository
     * @param jdbcTemplate the JDBC template for upsert operations
     */
    public PostgresDlqStorePersistence(DeadLetterRepository repository, JdbcTemplate jdbcTemplate) {
        this.repository = repository;
        this.jdbcTemplate = jdbcTemplate;
    }

    @Override
    @Transactional
    public void persist(PersistableDeadLetterEntry entry) {
        jdbcTemplate.update(UPSERT_SQL,
                entry.dlqEntryId(),
                entry.originalEventId(),
                entry.eventType(),
                entry.topicName(),
                entry.eventData(),
                entry.failureReason(),
                entry.failureTimestampMillis(),
                entry.sourceService(),
                entry.sagaId(),
                entry.correlationId(),
                entry.replayCount(),
                entry.status());
        logger.debug("Persisted DLQ entry: dlqEntryId={}, status={}", entry.dlqEntryId(), entry.status());
    }

    @Override
    @Transactional
    public void persistBatch(List<PersistableDeadLetterEntry> entries) {
        if (entries.isEmpty()) {
            return;
        }

        jdbcTemplate.batchUpdate(UPSERT_SQL, entries, entries.size(),
                (ps, entry) -> {
                    ps.setString(1, entry.dlqEntryId());
                    ps.setString(2, entry.originalEventId());
                    ps.setString(3, entry.eventType());
                    ps.setString(4, entry.topicName());
                    ps.setString(5, entry.eventData());
                    ps.setString(6, entry.failureReason());
                    ps.setLong(7, entry.failureTimestampMillis());
                    ps.setString(8, entry.sourceService());
                    ps.setString(9, entry.sagaId());
                    ps.setString(10, entry.correlationId());
                    ps.setInt(11, entry.replayCount());
                    ps.setString(12, entry.status());
                });
        logger.debug("Batch persisted {} DLQ entries", entries.size());
    }

    @Override
    @Transactional(readOnly = true)
    public Optional<PersistableDeadLetterEntry> load(String dlqEntryId) {
        return repository.findByDlqEntryId(dlqEntryId)
                .map(this::fromEntity);
    }

    @Override
    @Transactional(readOnly = true)
    public Iterable<String> loadPendingKeys() {
        return repository.findAllPendingDlqEntryIds();
    }

    @Override
    @Transactional
    public void delete(String dlqEntryId) {
        repository.deleteById(dlqEntryId);
        logger.debug("Deleted DLQ entry: dlqEntryId={}", dlqEntryId);
    }

    @Override
    public boolean isAvailable() {
        try {
            jdbcTemplate.queryForObject("SELECT 1", Integer.class);
            return true;
        } catch (Exception e) {
            logger.warn("PostgreSQL persistence unavailable: {}", e.getMessage());
            return false;
        }
    }

    private PersistableDeadLetterEntry fromEntity(DeadLetterEntity entity) {
        return new PersistableDeadLetterEntry(
                entity.getDlqEntryId(),
                entity.getOriginalEventId(),
                entity.getEventType(),
                entity.getTopicName(),
                entity.getEventData(),
                entity.getFailureReason(),
                entity.getFailureTimestampMillis(),
                entity.getSourceService(),
                entity.getSagaId(),
                entity.getCorrelationId(),
                entity.getReplayCount(),
                entity.getStatus()
        );
    }
}
