package com.theyawns.framework.persistence.postgres;

import com.theyawns.framework.persistence.EventStorePersistence;
import com.theyawns.framework.persistence.PersistenceAutoConfiguration;
import com.theyawns.framework.persistence.ViewStorePersistence;
import com.theyawns.framework.persistence.postgres.repository.EventStoreRepository;
import com.theyawns.framework.persistence.postgres.repository.ViewStoreRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.boot.autoconfigure.AutoConfigureBefore;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.autoconfigure.domain.EntityScan;
import org.springframework.context.annotation.Bean;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.springframework.jdbc.core.JdbcTemplate;

/**
 * Auto-configuration for the PostgreSQL persistence provider.
 *
 * <p>Activates when:
 * <ul>
 *   <li>{@code framework.persistence.enabled=true}</li>
 *   <li>The PostgreSQL JDBC driver is on the classpath</li>
 *   <li>No other {@link EventStorePersistence} or {@link ViewStorePersistence} bean exists</li>
 * </ul>
 *
 * <p>This configuration registers before {@link PersistenceAutoConfiguration} so that
 * the persistence provider beans are available when the MapStore adapters are created.
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
@AutoConfiguration
@AutoConfigureBefore(PersistenceAutoConfiguration.class)
@ConditionalOnProperty(name = "framework.persistence.enabled", havingValue = "true")
@ConditionalOnClass(name = "org.postgresql.Driver")
@EnableJpaRepositories(basePackages = "com.theyawns.framework.persistence.postgres.repository")
@EntityScan(basePackages = "com.theyawns.framework.persistence.postgres.entity")
public class PostgresPersistenceAutoConfiguration {

    private static final Logger logger = LoggerFactory.getLogger(PostgresPersistenceAutoConfiguration.class);

    /**
     * Creates the PostgreSQL event store persistence provider.
     *
     * @param repository the JPA repository
     * @param jdbcTemplate the JDBC template
     * @return the persistence provider
     */
    @Bean
    @ConditionalOnMissingBean(EventStorePersistence.class)
    public EventStorePersistence eventStorePersistence(EventStoreRepository repository,
                                                       JdbcTemplate jdbcTemplate) {
        logger.info("Creating PostgreSQL EventStorePersistence");
        return new PostgresEventStorePersistence(repository, jdbcTemplate);
    }

    /**
     * Creates the PostgreSQL view store persistence provider.
     *
     * @param repository the JPA repository
     * @param jdbcTemplate the JDBC template
     * @return the persistence provider
     */
    @Bean
    @ConditionalOnMissingBean(ViewStorePersistence.class)
    public ViewStorePersistence viewStorePersistence(ViewStoreRepository repository,
                                                     JdbcTemplate jdbcTemplate) {
        logger.info("Creating PostgreSQL ViewStorePersistence");
        return new PostgresViewStorePersistence(repository, jdbcTemplate);
    }
}
