package com.theyawns.framework.security.identity;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.boot.autoconfigure.AutoConfigurations;
import org.springframework.boot.test.context.runner.ApplicationContextRunner;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Unit tests for {@link ServiceIdentityAutoConfiguration}.
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
@DisplayName("ServiceIdentityAutoConfiguration - Conditional bean creation")
class ServiceIdentityAutoConfigurationTest {

    private final ApplicationContextRunner contextRunner = new ApplicationContextRunner()
            .withConfiguration(AutoConfigurations.of(ServiceIdentityAutoConfiguration.class));

    @Test
    @DisplayName("should not create beans when service-identity is disabled")
    void shouldNotCreateBeansWhenDisabled() {
        contextRunner
                .withPropertyValues(
                        "framework.security.service-identity.enabled=false",
                        "framework.security.service-identity.name=test-service",
                        "framework.security.service-identity.shared-secret=test-secret")
                .run(context -> {
                    assertThat(context).doesNotHaveBean(ServiceIdentity.class);
                    assertThat(context).doesNotHaveBean(EventAuthenticator.class);
                });
    }

    @Test
    @DisplayName("should not create beans when property is absent")
    void shouldNotCreateBeansWhenPropertyAbsent() {
        contextRunner
                .run(context -> {
                    assertThat(context).doesNotHaveBean(ServiceIdentity.class);
                    assertThat(context).doesNotHaveBean(EventAuthenticator.class);
                });
    }

    @Test
    @DisplayName("should create beans when service-identity is enabled")
    void shouldCreateBeansWhenEnabled() {
        contextRunner
                .withPropertyValues(
                        "framework.security.service-identity.enabled=true",
                        "framework.security.service-identity.name=order-service",
                        "framework.security.service-identity.shared-secret=my-secret-key")
                .run(context -> {
                    assertThat(context).hasSingleBean(ServiceIdentity.class);
                    assertThat(context).hasSingleBean(EventAuthenticator.class);
                    assertThat(context).hasSingleBean(ServiceIdentityProperties.class);

                    final ServiceIdentity identity = context.getBean(ServiceIdentity.class);
                    assertThat(identity.getServiceName()).isEqualTo("order-service");
                });
    }

    @Test
    @DisplayName("should bind properties correctly")
    void shouldBindPropertiesCorrectly() {
        contextRunner
                .withPropertyValues(
                        "framework.security.service-identity.enabled=true",
                        "framework.security.service-identity.name=inventory-service",
                        "framework.security.service-identity.shared-secret=another-secret")
                .run(context -> {
                    final ServiceIdentityProperties props = context.getBean(ServiceIdentityProperties.class);
                    assertThat(props.isEnabled()).isTrue();
                    assertThat(props.getName()).isEqualTo("inventory-service");
                    assertThat(props.getSharedSecret()).isEqualTo("another-secret");
                });
    }

    @Test
    @DisplayName("toString should redact shared secret")
    void toStringShouldRedactSecret() {
        contextRunner
                .withPropertyValues(
                        "framework.security.service-identity.enabled=true",
                        "framework.security.service-identity.name=test-service",
                        "framework.security.service-identity.shared-secret=super-secret-value")
                .run(context -> {
                    final ServiceIdentityProperties props = context.getBean(ServiceIdentityProperties.class);
                    assertThat(props.toString()).contains("REDACTED");
                    assertThat(props.toString()).doesNotContain("super-secret-value");
                });
    }
}
