package com.theyawns.ecommerce.gateway.error;

import com.theyawns.ecommerce.gateway.filter.CorrelationIdFilter;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.server.ServerWebExchange;

/**
 * Fallback handler invoked by Spring Cloud Gateway's CircuitBreaker filter
 * when a downstream service's circuit breaker is open.
 *
 * <p>Each route is configured with {@code fallbackUri: forward:/fallback/{service}},
 * which routes to this controller. Returns a consistent 503 JSON error response
 * identifying the unavailable service.
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
@RestController
public class CircuitBreakerFallbackHandler {

    /**
     * Handles circuit breaker fallback for the given service.
     *
     * @param serviceName the downstream service that triggered the circuit breaker
     * @param exchange the current server web exchange
     * @return 503 response with error details
     */
    @RequestMapping("/fallback/{serviceName}")
    public ResponseEntity<GatewayErrorResponse> fallback(
            @PathVariable final String serviceName,
            final ServerWebExchange exchange) {
        final String correlationId = exchange.getAttribute(CorrelationIdFilter.CORRELATION_ID_ATTR);
        final String path = exchange.getRequest().getPath().value();

        final GatewayErrorResponse response = new GatewayErrorResponse(
                HttpStatus.SERVICE_UNAVAILABLE.value(),
                "CIRCUIT_BREAKER_OPEN",
                "Service '" + serviceName + "' is temporarily unavailable",
                correlationId,
                path);

        return ResponseEntity.status(HttpStatus.SERVICE_UNAVAILABLE).body(response);
    }
}
