package com.theyawns.framework.persistence.mapstore;

import com.hazelcast.nio.serialization.genericrecord.GenericRecord;
import com.hazelcast.nio.serialization.genericrecord.GenericRecordBuilder;
import com.theyawns.framework.persistence.OutboxStorePersistence;
import com.theyawns.framework.persistence.PersistableOutboxEntry;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.Properties;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

/**
 * Unit tests for {@link OutboxMapStore}.
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
@DisplayName("OutboxMapStore - MapStore adapter for outbox persistence")
@ExtendWith(MockitoExtension.class)
class OutboxMapStoreTest {

    @Mock
    private OutboxStorePersistence persistence;

    private OutboxMapStore mapStore;

    @BeforeEach
    void setUp() {
        mapStore = new OutboxMapStore(persistence);
    }

    private GenericRecord createOutboxRecord(String eventId, String status) {
        GenericRecord eventRecord = GenericRecordBuilder.compact("CustomerCreatedEvent")
                .setString("eventType", "CustomerCreatedEvent")
                .setString("customerId", "cust-001")
                .setString("name", "John Doe")
                .build();

        return GenericRecordBuilder.compact("OutboxEntry")
                .setString("eventId", eventId)
                .setString("eventType", "CustomerCreatedEvent")
                .setGenericRecord("eventRecord", eventRecord)
                .setInt32("retryCount", 0)
                .setString("status", status)
                .setInt64("createdAt", 1700000000000L)
                .setNullableInt64("lastAttemptAt", null)
                .setString("failureReason", null)
                .setString("claimantId", null)
                .setNullableInt64("claimedAt", null)
                .build();
    }

    @Test
    @DisplayName("should store a single outbox entry via persistence provider")
    void shouldStoreSingleEntry() {
        // Arrange
        GenericRecord record = createOutboxRecord("evt-001", "PENDING");

        // Act
        mapStore.store("evt-001", record);

        // Assert
        ArgumentCaptor<PersistableOutboxEntry> captor =
                ArgumentCaptor.forClass(PersistableOutboxEntry.class);
        verify(persistence).persist(captor.capture());

        PersistableOutboxEntry entry = captor.getValue();
        assertEquals("evt-001", entry.eventId());
        assertEquals("CustomerCreatedEvent", entry.eventType());
        assertEquals("PENDING", entry.status());
        assertEquals(0, entry.retryCount());
        assertEquals(1700000000000L, entry.createdAtMillis());
        assertNotNull(entry.eventData());
        assertTrue(entry.eventData().contains("CustomerCreatedEvent"));
    }

    @Test
    @DisplayName("should batch store multiple outbox entries")
    void shouldBatchStoreEntries() {
        // Arrange
        Map<String, GenericRecord> entries = new HashMap<>();
        entries.put("evt-001", createOutboxRecord("evt-001", "PENDING"));
        entries.put("evt-002", createOutboxRecord("evt-002", "CLAIMED"));

        // Act
        mapStore.storeAll(entries);

        // Assert
        @SuppressWarnings("unchecked")
        ArgumentCaptor<List<PersistableOutboxEntry>> captor = ArgumentCaptor.forClass(List.class);
        verify(persistence).persistBatch(captor.capture());
        assertEquals(2, captor.getValue().size());
    }

    @Test
    @DisplayName("should not persist empty batch")
    void shouldNotPersistEmptyBatch() {
        // Act
        mapStore.storeAll(Map.of());

        // Assert
        verifyNoInteractions(persistence);
    }

    @Test
    @DisplayName("should load outbox entry from persistence and reconstruct GenericRecord")
    void shouldLoadEntry() {
        // Arrange
        GenericRecord eventRecord = GenericRecordBuilder.compact("CustomerCreatedEvent")
                .setString("eventType", "CustomerCreatedEvent")
                .setString("customerId", "cust-001")
                .build();
        String eventDataJson = GenericRecordJsonConverter.toJson(eventRecord);

        PersistableOutboxEntry pe = new PersistableOutboxEntry(
                "evt-001", "CustomerCreatedEvent", eventDataJson,
                2, "FAILED", 1700000000000L, 1700000001000L,
                "timeout", "member-1", 1700000000500L);

        when(persistence.load("evt-001")).thenReturn(Optional.of(pe));

        // Act
        GenericRecord loaded = mapStore.load("evt-001");

        // Assert
        assertNotNull(loaded);
        assertEquals("evt-001", loaded.getString("eventId"));
        assertEquals("CustomerCreatedEvent", loaded.getString("eventType"));
        assertEquals(2, loaded.getInt32("retryCount"));
        assertEquals("FAILED", loaded.getString("status"));
        assertEquals(1700000000000L, loaded.getInt64("createdAt"));
        assertEquals(1700000001000L, loaded.getNullableInt64("lastAttemptAt"));
        assertEquals("timeout", loaded.getString("failureReason"));
        assertEquals("member-1", loaded.getString("claimantId"));
        assertEquals(1700000000500L, loaded.getNullableInt64("claimedAt"));

        // Verify nested eventRecord is reconstructed
        GenericRecord nestedEvent = loaded.getGenericRecord("eventRecord");
        assertNotNull(nestedEvent);
        assertEquals("cust-001", nestedEvent.getString("customerId"));
    }

    @Test
    @DisplayName("should return null when entry not found")
    void shouldReturnNullWhenNotFound() {
        // Arrange
        when(persistence.load(anyString())).thenReturn(Optional.empty());

        // Act
        GenericRecord result = mapStore.load("nonexistent");

        // Assert
        assertNull(result);
    }

    @Test
    @DisplayName("should delegate loadAllKeys to persistence for non-delivered entries")
    void shouldDelegateLoadAllKeys() {
        // Arrange
        when(persistence.loadNonDeliveredKeys()).thenReturn(List.of("evt-001", "evt-002"));

        // Act
        Iterable<String> keys = mapStore.loadAllKeys();

        // Assert
        List<String> keyList = new java.util.ArrayList<>();
        keys.forEach(keyList::add);
        assertEquals(2, keyList.size());
        assertTrue(keyList.contains("evt-001"));
        assertTrue(keyList.contains("evt-002"));
    }

    @Test
    @DisplayName("should load all entries for given keys")
    void shouldLoadAllEntries() {
        // Arrange
        GenericRecord eventRecord = GenericRecordBuilder.compact("Evt")
                .setString("eventType", "Evt")
                .build();
        String json = GenericRecordJsonConverter.toJson(eventRecord);

        when(persistence.load("evt-001")).thenReturn(Optional.of(
                new PersistableOutboxEntry("evt-001", "Evt", json,
                        0, "PENDING", 100L, null, null, null, null)));
        when(persistence.load("evt-002")).thenReturn(Optional.of(
                new PersistableOutboxEntry("evt-002", "Evt", json,
                        0, "CLAIMED", 200L, null, null, null, null)));

        // Act
        Map<String, GenericRecord> result = mapStore.loadAll(List.of("evt-001", "evt-002"));

        // Assert
        assertEquals(2, result.size());
        assertEquals("PENDING", result.get("evt-001").getString("status"));
        assertEquals("CLAIMED", result.get("evt-002").getString("status"));
    }

    @Test
    @DisplayName("should skip missing entries in loadAll")
    void shouldSkipMissingInLoadAll() {
        // Arrange
        GenericRecord eventRecord = GenericRecordBuilder.compact("Evt")
                .setString("eventType", "Evt")
                .build();
        String json = GenericRecordJsonConverter.toJson(eventRecord);

        when(persistence.load("evt-001")).thenReturn(Optional.of(
                new PersistableOutboxEntry("evt-001", "Evt", json,
                        0, "PENDING", 100L, null, null, null, null)));
        when(persistence.load("evt-002")).thenReturn(Optional.empty());

        // Act
        Map<String, GenericRecord> result = mapStore.loadAll(List.of("evt-001", "evt-002"));

        // Assert
        assertEquals(1, result.size());
        assertTrue(result.containsKey("evt-001"));
        assertFalse(result.containsKey("evt-002"));
    }

    @Test
    @DisplayName("should delete entry via persistence provider")
    void shouldDeleteEntry() {
        // Act
        mapStore.delete("evt-001");

        // Assert
        verify(persistence).delete("evt-001");
    }

    @Test
    @DisplayName("should delete all entries via persistence provider")
    void shouldDeleteAllEntries() {
        // Act
        mapStore.deleteAll(List.of("evt-001", "evt-002", "evt-003"));

        // Assert
        verify(persistence).delete("evt-001");
        verify(persistence).delete("evt-002");
        verify(persistence).delete("evt-003");
    }

    @Test
    @DisplayName("should reject null persistence provider")
    void shouldRejectNullPersistence() {
        assertThrows(IllegalArgumentException.class, () -> new OutboxMapStore(null));
    }

    @Test
    @DisplayName("should set mapName on init")
    void shouldSetMapNameOnInit() {
        // Act
        mapStore.init(null, new Properties(), "framework_OUTBOX");

        // Store — verify it works after init
        GenericRecord record = createOutboxRecord("evt-001", "PENDING");
        mapStore.store("evt-001", record);

        // Assert
        verify(persistence).persist(any(PersistableOutboxEntry.class));
    }

    @Test
    @DisplayName("should handle nullable fields in round-trip conversion")
    void shouldHandleNullableFieldsInRoundTrip() {
        // Arrange — entry with all nullable fields set to null
        GenericRecord eventRecord = GenericRecordBuilder.compact("TestEvent")
                .setString("eventType", "TestEvent")
                .build();
        String json = GenericRecordJsonConverter.toJson(eventRecord);

        PersistableOutboxEntry pe = new PersistableOutboxEntry(
                "evt-001", "TestEvent", json,
                0, "PENDING", 1700000000000L,
                null, null, null, null);

        // Act
        GenericRecord record = OutboxMapStore.toGenericRecord(pe);
        PersistableOutboxEntry roundTripped = OutboxMapStore.toPersistableEntry(record);

        // Assert
        assertEquals("evt-001", roundTripped.eventId());
        assertEquals("TestEvent", roundTripped.eventType());
        assertEquals("PENDING", roundTripped.status());
        assertEquals(0, roundTripped.retryCount());
        assertNull(roundTripped.lastAttemptAtMillis());
        assertNull(roundTripped.failureReason());
        assertNull(roundTripped.claimantId());
        assertNull(roundTripped.claimedAtMillis());
    }
}
