package com.theyawns.ecommerce.gateway;

import java.util.List;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.cloud.gateway.route.RouteDefinition;
import org.springframework.cloud.gateway.route.RouteDefinitionLocator;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Tests that all gateway routes are properly configured.
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
@SpringBootTest
@DisplayName("GatewayRouteConfig - Route validation")
class GatewayRouteConfigTest {

    private static final int EXPECTED_ROUTE_COUNT = 8;

    @Autowired
    private RouteDefinitionLocator routeDefinitionLocator;

    @Test
    @DisplayName("should have expected number of routes configured")
    void shouldHaveExpectedRouteCount() {
        final List<RouteDefinition> routes = routeDefinitionLocator.getRouteDefinitions()
                .collectList()
                .block();

        assertThat(routes).hasSize(EXPECTED_ROUTE_COUNT);
    }

    @Test
    @DisplayName("should configure account-service route")
    void shouldConfigureAccountServiceRoute() {
        assertRouteExists("account-service", "/api/customers/**", "http://localhost:8081");
    }

    @Test
    @DisplayName("should configure inventory-service route")
    void shouldConfigureInventoryServiceRoute() {
        assertRouteExists("inventory-service", "/api/products/**", "http://localhost:8082");
    }

    @Test
    @DisplayName("should configure inventory-saga route")
    void shouldConfigureInventorySagaRoute() {
        assertRouteExists("inventory-saga", "/api/saga/inventory/**", "http://localhost:8082");
    }

    @Test
    @DisplayName("should configure order-service route")
    void shouldConfigureOrderServiceRoute() {
        assertRouteExists("order-service", "/api/orders/**", "http://localhost:8083");
    }

    @Test
    @DisplayName("should configure order-sagas route")
    void shouldConfigureOrderSagasRoute() {
        assertRouteExists("order-sagas", "/api/sagas/**", "http://localhost:8083");
    }

    @Test
    @DisplayName("should configure order-metrics route")
    void shouldConfigureOrderMetricsRoute() {
        assertRouteExists("order-metrics", "/api/metrics/**", "http://localhost:8083");
    }

    @Test
    @DisplayName("should configure payment-service route")
    void shouldConfigurePaymentServiceRoute() {
        assertRouteExists("payment-service", "/api/payments/**", "http://localhost:8084");
    }

    @Test
    @DisplayName("should configure payment-saga route")
    void shouldConfigurePaymentSagaRoute() {
        assertRouteExists("payment-saga", "/api/saga/payment/**", "http://localhost:8084");
    }

    /**
     * Asserts that a route with the given ID, path predicate, and URI exists.
     *
     * @param routeId the expected route ID
     * @param expectedPath the expected path predicate pattern
     * @param expectedUri the expected target URI
     */
    private void assertRouteExists(final String routeId, final String expectedPath, final String expectedUri) {
        final List<RouteDefinition> routes = routeDefinitionLocator.getRouteDefinitions()
                .collectList()
                .block();

        assertThat(routes).isNotNull();

        final RouteDefinition route = routes.stream()
                .filter(r -> routeId.equals(r.getId()))
                .findFirst()
                .orElse(null);

        assertThat(route)
                .as("Route '%s' should exist", routeId)
                .isNotNull();

        assertThat(route.getUri().toString())
                .as("Route '%s' URI", routeId)
                .isEqualTo(expectedUri);

        assertThat(route.getPredicates())
                .as("Route '%s' predicates", routeId)
                .isNotEmpty();

        final String predicateArgs = route.getPredicates().get(0).getArgs().toString();
        assertThat(predicateArgs)
                .as("Route '%s' path predicate", routeId)
                .contains(expectedPath);
    }
}
