package com.theyawns.ecommerce.gateway.filter;

import java.util.UUID;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.cloud.gateway.filter.GatewayFilterChain;
import org.springframework.mock.http.server.reactive.MockServerHttpRequest;
import org.springframework.mock.web.server.MockServerWebExchange;
import reactor.core.publisher.Mono;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

/**
 * Unit tests for {@link CorrelationIdFilter}.
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
@DisplayName("CorrelationIdFilter - Correlation ID propagation")
class CorrelationIdFilterTest {

    private CorrelationIdFilter filter;
    private GatewayFilterChain chain;

    @BeforeEach
    void setUp() {
        filter = new CorrelationIdFilter();
        chain = mock(GatewayFilterChain.class);
        when(chain.filter(any())).thenReturn(Mono.empty());
    }

    @Test
    @DisplayName("should generate correlation ID when not present in request")
    void shouldGenerateCorrelationIdWhenNotPresent() {
        final MockServerWebExchange exchange = MockServerWebExchange.from(
                MockServerHttpRequest.get("/api/customers").build());

        filter.filter(exchange, chain).block();

        final String correlationId = exchange.getAttribute(CorrelationIdFilter.CORRELATION_ID_ATTR);
        assertThat(correlationId).isNotNull().isNotBlank();
        // Verify it's a valid UUID
        assertThat(UUID.fromString(correlationId)).isNotNull();
    }

    @Test
    @DisplayName("should propagate existing correlation ID from request")
    void shouldPropagateExistingCorrelationId() {
        final String existingId = "existing-correlation-123";
        final MockServerWebExchange exchange = MockServerWebExchange.from(
                MockServerHttpRequest.get("/api/customers")
                        .header(CorrelationIdFilter.CORRELATION_ID_HEADER, existingId)
                        .build());

        filter.filter(exchange, chain).block();

        final String correlationId = exchange.getAttribute(CorrelationIdFilter.CORRELATION_ID_ATTR);
        assertThat(correlationId).isEqualTo(existingId);
    }

    @Test
    @DisplayName("should add correlation ID to response headers")
    void shouldAddCorrelationIdToResponseHeaders() {
        final MockServerWebExchange exchange = MockServerWebExchange.from(
                MockServerHttpRequest.get("/api/customers").build());

        filter.filter(exchange, chain).block();

        final String responseHeader = exchange.getResponse().getHeaders()
                .getFirst(CorrelationIdFilter.CORRELATION_ID_HEADER);
        assertThat(responseHeader).isNotNull().isNotBlank();
    }

    @Test
    @DisplayName("should store correlation ID in exchange attributes")
    void shouldStoreCorrelationIdInExchangeAttributes() {
        final String existingId = "attr-test-456";
        final MockServerWebExchange exchange = MockServerWebExchange.from(
                MockServerHttpRequest.get("/api/customers")
                        .header(CorrelationIdFilter.CORRELATION_ID_HEADER, existingId)
                        .build());

        filter.filter(exchange, chain).block();

        assertThat((String) exchange.getAttribute(CorrelationIdFilter.CORRELATION_ID_ATTR))
                .isEqualTo(existingId);
    }

    @Test
    @DisplayName("should generate new ID when header is blank")
    void shouldGenerateNewIdWhenHeaderIsBlank() {
        final MockServerWebExchange exchange = MockServerWebExchange.from(
                MockServerHttpRequest.get("/api/customers")
                        .header(CorrelationIdFilter.CORRELATION_ID_HEADER, "   ")
                        .build());

        filter.filter(exchange, chain).block();

        final String correlationId = exchange.getAttribute(CorrelationIdFilter.CORRELATION_ID_ATTR);
        assertThat(correlationId).isNotBlank();
        assertThat(correlationId.trim()).isNotEqualTo("");
    }

    @Test
    @DisplayName("should have order -4 (highest priority among custom filters)")
    void shouldHaveCorrectOrder() {
        assertThat(filter.getOrder()).isEqualTo(-4);
    }
}
