package com.theyawns.ecommerce.gateway.filter;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.cloud.gateway.filter.GatewayFilterChain;
import org.springframework.mock.http.server.reactive.MockServerHttpRequest;
import org.springframework.mock.web.server.MockServerWebExchange;
import reactor.core.publisher.Mono;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

/**
 * Unit tests for {@link RequestLoggingFilter}.
 *
 * <p>Verifies that the filter executes without error and maintains correct
 * ordering. Log output verification is intentionally omitted — logging
 * is a side effect best validated through integration/acceptance tests.
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
@DisplayName("RequestLoggingFilter - Request/response logging")
class RequestLoggingFilterTest {

    private RequestLoggingFilter filter;
    private GatewayFilterChain chain;

    @BeforeEach
    void setUp() {
        filter = new RequestLoggingFilter();
        chain = mock(GatewayFilterChain.class);
        when(chain.filter(any())).thenReturn(Mono.empty());
    }

    @Test
    @DisplayName("should execute filter without error for GET request")
    void shouldExecuteFilterForGetRequest() {
        final MockServerWebExchange exchange = MockServerWebExchange.from(
                MockServerHttpRequest.get("/api/customers").build());
        exchange.getAttributes().put(CorrelationIdFilter.CORRELATION_ID_ATTR, "test-123");

        filter.filter(exchange, chain).block();

        // Filter should complete without error
        assertThat(exchange.getResponse().getStatusCode()).isNull(); // No status override
    }

    @Test
    @DisplayName("should execute filter without error for POST request")
    void shouldExecuteFilterForPostRequest() {
        final MockServerWebExchange exchange = MockServerWebExchange.from(
                MockServerHttpRequest.post("/api/orders").build());
        exchange.getAttributes().put(CorrelationIdFilter.CORRELATION_ID_ATTR, "test-456");

        filter.filter(exchange, chain).block();

        assertThat(exchange.getResponse().getStatusCode()).isNull();
    }

    @Test
    @DisplayName("should handle missing correlation ID gracefully")
    void shouldHandleMissingCorrelationId() {
        final MockServerWebExchange exchange = MockServerWebExchange.from(
                MockServerHttpRequest.get("/api/products").build());
        // No correlation ID set in attributes

        filter.filter(exchange, chain).block();

        // Should not throw
        assertThat(exchange.getResponse().getStatusCode()).isNull();
    }

    @Test
    @DisplayName("should have order -1 (lowest priority among custom filters)")
    void shouldHaveCorrectOrder() {
        assertThat(filter.getOrder()).isEqualTo(-1);
    }
}
