package com.theyawns.ecommerce.gateway.filter;

import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.simple.SimpleMeterRegistry;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.cloud.gateway.filter.GatewayFilterChain;
import org.springframework.mock.http.server.reactive.MockServerHttpRequest;
import org.springframework.mock.web.server.MockServerWebExchange;
import reactor.core.publisher.Mono;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

/**
 * Unit tests for {@link RequestTimingFilter}.
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
@DisplayName("RequestTimingFilter - Request duration measurement")
class RequestTimingFilterTest {

    private MeterRegistry meterRegistry;
    private RequestTimingFilter filter;
    private GatewayFilterChain chain;

    @BeforeEach
    void setUp() {
        meterRegistry = new SimpleMeterRegistry();
        filter = new RequestTimingFilter(meterRegistry);
        chain = mock(GatewayFilterChain.class);
        when(chain.filter(any())).thenReturn(Mono.empty());
    }

    @Test
    @DisplayName("should execute filter without error")
    void shouldExecuteFilterWithoutError() {
        final MockServerWebExchange exchange = MockServerWebExchange.from(
                MockServerHttpRequest.get("/api/customers").build());

        filter.filter(exchange, chain).block();

        // Filter should complete without error
        assertThat(exchange.getResponse().getStatusCode()).isNull();
    }

    @Test
    @DisplayName("should normalize paths with UUIDs")
    void shouldNormalizePathsWithUuids() {
        final String path = "/api/customers/550e8400-e29b-41d4-a716-446655440000/orders";
        assertThat(filter.normalizePath(path)).isEqualTo("/api/customers/{id}/orders");
    }

    @Test
    @DisplayName("should normalize paths with numeric IDs")
    void shouldNormalizePathsWithNumericIds() {
        final String path = "/api/products/12345/reviews";
        assertThat(filter.normalizePath(path)).isEqualTo("/api/products/{id}/reviews");
    }

    @Test
    @DisplayName("should leave paths without IDs unchanged")
    void shouldLeaveCleanPathsUnchanged() {
        final String path = "/api/customers";
        assertThat(filter.normalizePath(path)).isEqualTo("/api/customers");
    }

    @Test
    @DisplayName("should handle null path")
    void shouldHandleNullPath() {
        assertThat(filter.normalizePath(null)).isEqualTo("/");
    }

    @Test
    @DisplayName("should have order -3")
    void shouldHaveCorrectOrder() {
        assertThat(filter.getOrder()).isEqualTo(-3);
    }
}
