package com.theyawns.ecommerce.mcp.security;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Tests for {@link McpRole}.
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
@DisplayName("McpRole")
class McpRoleTest {

    @Test
    @DisplayName("VIEWER should access read-only tools")
    void viewerShouldAccessReadOnlyTools() {
        assertThat(McpRole.VIEWER.canAccess("queryView")).isTrue();
        assertThat(McpRole.VIEWER.canAccess("getEventHistory")).isTrue();
        assertThat(McpRole.VIEWER.canAccess("inspectSaga")).isTrue();
        assertThat(McpRole.VIEWER.canAccess("listSagas")).isTrue();
        assertThat(McpRole.VIEWER.canAccess("getMetrics")).isTrue();
    }

    @Test
    @DisplayName("VIEWER should not access write tools")
    void viewerShouldNotAccessWriteTools() {
        assertThat(McpRole.VIEWER.canAccess("submitEvent")).isFalse();
        assertThat(McpRole.VIEWER.canAccess("runDemo")).isFalse();
    }

    @Test
    @DisplayName("OPERATOR should access read and write tools")
    void operatorShouldAccessReadAndWriteTools() {
        assertThat(McpRole.OPERATOR.canAccess("queryView")).isTrue();
        assertThat(McpRole.OPERATOR.canAccess("getEventHistory")).isTrue();
        assertThat(McpRole.OPERATOR.canAccess("inspectSaga")).isTrue();
        assertThat(McpRole.OPERATOR.canAccess("listSagas")).isTrue();
        assertThat(McpRole.OPERATOR.canAccess("getMetrics")).isTrue();
        assertThat(McpRole.OPERATOR.canAccess("submitEvent")).isTrue();
        assertThat(McpRole.OPERATOR.canAccess("runDemo")).isTrue();
    }

    @Test
    @DisplayName("ADMIN should access all tools")
    void adminShouldAccessAllTools() {
        assertThat(McpRole.ADMIN.canAccess("queryView")).isTrue();
        assertThat(McpRole.ADMIN.canAccess("getEventHistory")).isTrue();
        assertThat(McpRole.ADMIN.canAccess("inspectSaga")).isTrue();
        assertThat(McpRole.ADMIN.canAccess("listSagas")).isTrue();
        assertThat(McpRole.ADMIN.canAccess("getMetrics")).isTrue();
        assertThat(McpRole.ADMIN.canAccess("submitEvent")).isTrue();
        assertThat(McpRole.ADMIN.canAccess("runDemo")).isTrue();
    }

    @Test
    @DisplayName("should deny access to unknown tool name")
    void shouldDenyUnknownTool() {
        assertThat(McpRole.ADMIN.canAccess("unknownTool")).isFalse();
        assertThat(McpRole.OPERATOR.canAccess("deleteSomething")).isFalse();
        assertThat(McpRole.VIEWER.canAccess("")).isFalse();
    }

    @Test
    @DisplayName("getAllowedTools should return correct set size per role")
    void getAllowedToolsShouldReturnCorrectSize() {
        assertThat(McpRole.VIEWER.getAllowedTools()).hasSize(5);
        assertThat(McpRole.OPERATOR.getAllowedTools()).hasSize(7);
        assertThat(McpRole.ADMIN.getAllowedTools()).hasSize(7);
    }
}
