package com.theyawns.ecommerce.mcp.security;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Tests for {@link ToolAuthorizer}.
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
@DisplayName("ToolAuthorizer")
class ToolAuthorizerTest {

    private final ObjectMapper objectMapper = new ObjectMapper();

    @AfterEach
    void tearDown() {
        ToolAuthorizer.clearRequestRole();
    }

    @Test
    @DisplayName("should permit access when session role allows tool")
    void shouldPermitWhenSessionRoleAllows() {
        ToolAuthorizer authorizer = new ToolAuthorizer(McpRole.OPERATOR);

        assertThat(authorizer.checkAccess("queryView")).isNull();
        assertThat(authorizer.checkAccess("submitEvent")).isNull();
    }

    @Test
    @DisplayName("should deny access when session role disallows tool")
    void shouldDenyWhenSessionRoleDisallows() throws JsonProcessingException {
        ToolAuthorizer authorizer = new ToolAuthorizer(McpRole.VIEWER);

        String result = authorizer.checkAccess("submitEvent");

        assertThat(result).isNotNull();
        Map<String, Object> parsed = objectMapper.readValue(result, new TypeReference<>() {});
        assertThat(parsed.get("error")).isEqualTo("access_denied");
        assertThat(parsed.get("tool")).isEqualTo("submitEvent");
    }

    @Test
    @DisplayName("should deny access when no role is set")
    void shouldDenyWhenNoRole() throws JsonProcessingException {
        ToolAuthorizer authorizer = new ToolAuthorizer(null);

        String result = authorizer.checkAccess("queryView");

        assertThat(result).isNotNull();
        Map<String, Object> parsed = objectMapper.readValue(result, new TypeReference<>() {});
        assertThat(parsed.get("error")).isEqualTo("access_denied");
    }

    @Test
    @DisplayName("should prefer request role over session role")
    void shouldPreferRequestRoleOverSessionRole() {
        ToolAuthorizer authorizer = new ToolAuthorizer(McpRole.ADMIN);

        // Session role is ADMIN (can access submitEvent)
        assertThat(authorizer.checkAccess("submitEvent")).isNull();

        // Set per-request role to VIEWER (cannot access submitEvent)
        ToolAuthorizer.setRequestRole(McpRole.VIEWER);
        assertThat(authorizer.checkAccess("submitEvent")).isNotNull();

        // Clear request role — falls back to session role ADMIN
        ToolAuthorizer.clearRequestRole();
        assertThat(authorizer.checkAccess("submitEvent")).isNull();
    }

    @Test
    @DisplayName("getCurrentRole should return request role when set")
    void getCurrentRoleShouldReturnRequestRole() {
        ToolAuthorizer authorizer = new ToolAuthorizer(McpRole.VIEWER);

        assertThat(authorizer.getCurrentRole()).isEqualTo(McpRole.VIEWER);

        ToolAuthorizer.setRequestRole(McpRole.ADMIN);
        assertThat(authorizer.getCurrentRole()).isEqualTo(McpRole.ADMIN);
    }

    @Test
    @DisplayName("getCurrentRole should return session role when no request role")
    void getCurrentRoleShouldReturnSessionRole() {
        ToolAuthorizer authorizer = new ToolAuthorizer(McpRole.OPERATOR);

        assertThat(authorizer.getCurrentRole()).isEqualTo(McpRole.OPERATOR);
    }

    @Test
    @DisplayName("getSessionRole should return the original session role")
    void getSessionRoleShouldReturnOriginal() {
        ToolAuthorizer authorizer = new ToolAuthorizer(McpRole.VIEWER);

        assertThat(authorizer.getSessionRole()).isEqualTo(McpRole.VIEWER);

        // Even after setting request role, session role stays the same
        ToolAuthorizer.setRequestRole(McpRole.ADMIN);
        assertThat(authorizer.getSessionRole()).isEqualTo(McpRole.VIEWER);
    }

    @Test
    @DisplayName("should return valid JSON error on denial")
    void shouldReturnValidJsonOnDenial() throws JsonProcessingException {
        ToolAuthorizer authorizer = new ToolAuthorizer(McpRole.VIEWER);

        String result = authorizer.checkAccess("runDemo");

        Map<String, Object> parsed = objectMapper.readValue(result, new TypeReference<>() {});
        assertThat(parsed).containsKey("error");
        assertThat(parsed).containsKey("tool");
        assertThat(parsed).containsKey("message");
        assertThat(parsed.get("tool")).isEqualTo("runDemo");
    }
}
