package com.theyawns.framework.outbox;

import com.hazelcast.nio.serialization.genericrecord.GenericRecord;
import com.hazelcast.nio.serialization.genericrecord.GenericRecordBuilder;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.time.Instant;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Tests for {@link OutboxEntry}.
 *
 * <p>Validates construction defaults, field accessors, and status transitions.
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
@DisplayName("OutboxEntry - Construction and status transitions")
class OutboxEntryTest {

    private GenericRecord testRecord;

    @BeforeEach
    void setUp() {
        testRecord = GenericRecordBuilder.compact("TestEvent")
                .setString("eventId", "test-1")
                .setString("eventType", "TestCreated")
                .build();
    }

    @Nested
    @DisplayName("Construction defaults")
    class ConstructionDefaults {

        @Test
        @DisplayName("should set eventId from constructor")
        void shouldSetEventIdFromConstructor() {
            final OutboxEntry entry = new OutboxEntry("evt-123", "OrderCreated", testRecord);

            assertThat(entry.getEventId()).isEqualTo("evt-123");
        }

        @Test
        @DisplayName("should set eventType from constructor")
        void shouldSetEventTypeFromConstructor() {
            final OutboxEntry entry = new OutboxEntry("evt-123", "OrderCreated", testRecord);

            assertThat(entry.getEventType()).isEqualTo("OrderCreated");
        }

        @Test
        @DisplayName("should set eventRecord from constructor")
        void shouldSetEventRecordFromConstructor() {
            final OutboxEntry entry = new OutboxEntry("evt-123", "OrderCreated", testRecord);

            assertThat(entry.getEventRecord()).isSameAs(testRecord);
        }

        @Test
        @DisplayName("should default status to PENDING")
        void shouldDefaultStatusToPending() {
            final OutboxEntry entry = new OutboxEntry("evt-123", "OrderCreated", testRecord);

            assertThat(entry.getStatus()).isEqualTo(OutboxEntry.Status.PENDING);
        }

        @Test
        @DisplayName("should default retryCount to 0")
        void shouldDefaultRetryCountToZero() {
            final OutboxEntry entry = new OutboxEntry("evt-123", "OrderCreated", testRecord);

            assertThat(entry.getRetryCount()).isEqualTo(0);
        }

        @Test
        @DisplayName("should set createdAt to a non-null value")
        void shouldSetCreatedAtToNonNull() {
            final Instant before = Instant.now();
            final OutboxEntry entry = new OutboxEntry("evt-123", "OrderCreated", testRecord);
            final Instant after = Instant.now();

            assertThat(entry.getCreatedAt()).isNotNull();
            assertThat(entry.getCreatedAt()).isAfterOrEqualTo(before);
            assertThat(entry.getCreatedAt()).isBeforeOrEqualTo(after);
        }

        @Test
        @DisplayName("should default lastAttemptAt to null")
        void shouldDefaultLastAttemptAtToNull() {
            final OutboxEntry entry = new OutboxEntry("evt-123", "OrderCreated", testRecord);

            assertThat(entry.getLastAttemptAt()).isNull();
        }

        @Test
        @DisplayName("should default failureReason to null")
        void shouldDefaultFailureReasonToNull() {
            final OutboxEntry entry = new OutboxEntry("evt-123", "OrderCreated", testRecord);

            assertThat(entry.getFailureReason()).isNull();
        }

        @Test
        @DisplayName("should default claimantId to null")
        void shouldDefaultClaimantIdToNull() {
            final OutboxEntry entry = new OutboxEntry("evt-123", "OrderCreated", testRecord);

            assertThat(entry.getClaimantId()).isNull();
        }

        @Test
        @DisplayName("should default claimedAt to null")
        void shouldDefaultClaimedAtToNull() {
            final OutboxEntry entry = new OutboxEntry("evt-123", "OrderCreated", testRecord);

            assertThat(entry.getClaimedAt()).isNull();
        }
    }

    @Nested
    @DisplayName("Constructor validation")
    class ConstructorValidation {

        @Test
        @DisplayName("should reject null eventId")
        void shouldRejectNullEventId() {
            assertThatThrownBy(() -> new OutboxEntry(null, "OrderCreated", testRecord))
                    .isInstanceOf(NullPointerException.class)
                    .hasMessageContaining("eventId");
        }

        @Test
        @DisplayName("should reject null eventType")
        void shouldRejectNullEventType() {
            assertThatThrownBy(() -> new OutboxEntry("evt-123", null, testRecord))
                    .isInstanceOf(NullPointerException.class)
                    .hasMessageContaining("eventType");
        }

        @Test
        @DisplayName("should reject null eventRecord")
        void shouldRejectNullEventRecord() {
            assertThatThrownBy(() -> new OutboxEntry("evt-123", "OrderCreated", null))
                    .isInstanceOf(NullPointerException.class)
                    .hasMessageContaining("eventRecord");
        }
    }

    @Nested
    @DisplayName("Setters")
    class Setters {

        @Test
        @DisplayName("should update retryCount via setter")
        void shouldUpdateRetryCountViaSetter() {
            final OutboxEntry entry = new OutboxEntry("evt-123", "OrderCreated", testRecord);

            entry.setRetryCount(3);

            assertThat(entry.getRetryCount()).isEqualTo(3);
        }

        @Test
        @DisplayName("should update status via setter")
        void shouldUpdateStatusViaSetter() {
            final OutboxEntry entry = new OutboxEntry("evt-123", "OrderCreated", testRecord);

            entry.setStatus(OutboxEntry.Status.DELIVERED);

            assertThat(entry.getStatus()).isEqualTo(OutboxEntry.Status.DELIVERED);
        }

        @Test
        @DisplayName("should reject null status")
        void shouldRejectNullStatus() {
            final OutboxEntry entry = new OutboxEntry("evt-123", "OrderCreated", testRecord);

            assertThatThrownBy(() -> entry.setStatus(null))
                    .isInstanceOf(NullPointerException.class)
                    .hasMessageContaining("status");
        }

        @Test
        @DisplayName("should update lastAttemptAt via setter")
        void shouldUpdateLastAttemptAtViaSetter() {
            final OutboxEntry entry = new OutboxEntry("evt-123", "OrderCreated", testRecord);
            final Instant now = Instant.now();

            entry.setLastAttemptAt(now);

            assertThat(entry.getLastAttemptAt()).isEqualTo(now);
        }

        @Test
        @DisplayName("should update failureReason via setter")
        void shouldUpdateFailureReasonViaSetter() {
            final OutboxEntry entry = new OutboxEntry("evt-123", "OrderCreated", testRecord);

            entry.setFailureReason("Connection timed out");

            assertThat(entry.getFailureReason()).isEqualTo("Connection timed out");
        }

        @Test
        @DisplayName("should update claimantId via setter")
        void shouldUpdateClaimantIdViaSetter() {
            final OutboxEntry entry = new OutboxEntry("evt-123", "OrderCreated", testRecord);

            entry.setClaimantId("member-uuid-1");

            assertThat(entry.getClaimantId()).isEqualTo("member-uuid-1");
        }

        @Test
        @DisplayName("should update claimedAt via setter")
        void shouldUpdateClaimedAtViaSetter() {
            final OutboxEntry entry = new OutboxEntry("evt-123", "OrderCreated", testRecord);
            final Instant now = Instant.now();

            entry.setClaimedAt(now);

            assertThat(entry.getClaimedAt()).isEqualTo(now);
        }
    }

    @Nested
    @DisplayName("Status transitions")
    class StatusTransitions {

        @Test
        @DisplayName("should transition from PENDING to DELIVERED")
        void shouldTransitionFromPendingToDelivered() {
            final OutboxEntry entry = new OutboxEntry("evt-123", "OrderCreated", testRecord);
            assertThat(entry.getStatus()).isEqualTo(OutboxEntry.Status.PENDING);

            entry.setStatus(OutboxEntry.Status.DELIVERED);

            assertThat(entry.getStatus()).isEqualTo(OutboxEntry.Status.DELIVERED);
        }

        @Test
        @DisplayName("should transition from PENDING to CLAIMED")
        void shouldTransitionFromPendingToClaimed() {
            final OutboxEntry entry = new OutboxEntry("evt-123", "OrderCreated", testRecord);
            assertThat(entry.getStatus()).isEqualTo(OutboxEntry.Status.PENDING);

            entry.setStatus(OutboxEntry.Status.CLAIMED);

            assertThat(entry.getStatus()).isEqualTo(OutboxEntry.Status.CLAIMED);
        }

        @Test
        @DisplayName("should transition from PENDING to FAILED")
        void shouldTransitionFromPendingToFailed() {
            final OutboxEntry entry = new OutboxEntry("evt-123", "OrderCreated", testRecord);
            assertThat(entry.getStatus()).isEqualTo(OutboxEntry.Status.PENDING);

            entry.setStatus(OutboxEntry.Status.FAILED);

            assertThat(entry.getStatus()).isEqualTo(OutboxEntry.Status.FAILED);
        }

        @Test
        @DisplayName("should allow tracking retry count alongside status")
        void shouldAllowTrackingRetryCountAlongsideStatus() {
            final OutboxEntry entry = new OutboxEntry("evt-123", "OrderCreated", testRecord);

            entry.setRetryCount(1);
            entry.setFailureReason("Network error");
            entry.setLastAttemptAt(Instant.now());

            assertThat(entry.getStatus()).isEqualTo(OutboxEntry.Status.PENDING);
            assertThat(entry.getRetryCount()).isEqualTo(1);
            assertThat(entry.getFailureReason()).isEqualTo("Network error");
            assertThat(entry.getLastAttemptAt()).isNotNull();
        }
    }

    @Nested
    @DisplayName("Status enum")
    class StatusEnum {

        @Test
        @DisplayName("should have four status values")
        void shouldHaveFourStatusValues() {
            assertThat(OutboxEntry.Status.values()).hasSize(4);
        }

        @Test
        @DisplayName("should contain PENDING, CLAIMED, DELIVERED, and FAILED")
        void shouldContainExpectedValues() {
            assertThat(OutboxEntry.Status.valueOf("PENDING")).isEqualTo(OutboxEntry.Status.PENDING);
            assertThat(OutboxEntry.Status.valueOf("CLAIMED")).isEqualTo(OutboxEntry.Status.CLAIMED);
            assertThat(OutboxEntry.Status.valueOf("DELIVERED")).isEqualTo(OutboxEntry.Status.DELIVERED);
            assertThat(OutboxEntry.Status.valueOf("FAILED")).isEqualTo(OutboxEntry.Status.FAILED);
        }
    }

    @Nested
    @DisplayName("toString")
    class ToStringTests {

        @Test
        @DisplayName("should include eventId in toString")
        void shouldIncludeEventIdInToString() {
            final OutboxEntry entry = new OutboxEntry("evt-123", "OrderCreated", testRecord);

            assertThat(entry.toString()).contains("evt-123");
        }

        @Test
        @DisplayName("should include eventType in toString")
        void shouldIncludeEventTypeInToString() {
            final OutboxEntry entry = new OutboxEntry("evt-123", "OrderCreated", testRecord);

            assertThat(entry.toString()).contains("OrderCreated");
        }

        @Test
        @DisplayName("should include status in toString")
        void shouldIncludeStatusInToString() {
            final OutboxEntry entry = new OutboxEntry("evt-123", "OrderCreated", testRecord);

            assertThat(entry.toString()).contains("PENDING");
        }
    }
}
