package com.theyawns.ecommerce.order.saga;

import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.nio.serialization.genericrecord.GenericRecord;
import com.hazelcast.topic.ITopic;
import com.hazelcast.topic.Message;
import com.hazelcast.topic.MessageListener;
import com.theyawns.ecommerce.common.events.PaymentProcessedEvent;
import com.theyawns.ecommerce.order.service.OrderOperations;
import jakarta.annotation.PostConstruct;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

/**
 * Saga event listener for the Order Service.
 *
 * <p>Listens for saga-related events that trigger order state transitions:
 * <ul>
 *   <li>{@link PaymentProcessedEvent} - Triggers order confirmation (saga step 3)</li>
 * </ul>
 *
 * <p>This component connects the Order Service to the choreographed saga
 * for order fulfillment. When payment is processed (step 2), the order
 * service automatically confirms the order (step 3) and marks the saga
 * as COMPLETED.
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
@Component
public class OrderSagaListener {

    private static final Logger logger = LoggerFactory.getLogger(OrderSagaListener.class);

    private final OrderOperations orderService;
    private final HazelcastInstance hazelcast;

    /**
     * Creates a new OrderSagaListener.
     *
     * @param orderService the order service for order operations
     * @param hazelcast the Hazelcast instance for topic subscriptions
     */
    public OrderSagaListener(OrderOperations orderService, HazelcastInstance hazelcast) {
        this.orderService = orderService;
        this.hazelcast = hazelcast;
    }

    /**
     * Registers listeners for saga-related topics on startup.
     */
    @PostConstruct
    public void registerListeners() {
        logger.info("Registering order saga event listeners");

        ITopic<GenericRecord> paymentProcessedTopic = hazelcast.getTopic("PaymentProcessed");
        paymentProcessedTopic.addMessageListener(new PaymentProcessedListener());

        logger.info("Order saga listeners registered successfully");
    }

    /**
     * Listener for PaymentProcessed events.
     *
     * <p>When payment is processed as part of a saga, confirms the order
     * and marks the saga as COMPLETED. This is the final step (step 3)
     * in the Order Fulfillment saga happy path.
     */
    class PaymentProcessedListener implements MessageListener<GenericRecord> {

        @Override
        public void onMessage(Message<GenericRecord> message) {
            GenericRecord record = message.getMessageObject();

            String sagaId = record.getString("sagaId");
            if (sagaId == null || sagaId.isEmpty()) {
                logger.debug("PaymentProcessed event without sagaId - not a saga event, ignoring");
                return;
            }

            String orderId = record.getString("orderId");
            String correlationId = record.getString("correlationId");

            logger.info("Received PaymentProcessed saga event: orderId={}, sagaId={}", orderId, sagaId);

            try {
                orderService.confirmOrderForSaga(orderId, sagaId, correlationId)
                        .whenComplete((order, error) -> {
                            if (error != null) {
                                logger.error("Failed to confirm order {} for saga: {}",
                                        orderId, sagaId, error);
                                // Compensation will be handled in Day 7
                            } else {
                                logger.info("Order confirmed via saga: orderId={}, status={}, sagaId={}",
                                        orderId, order.getStatus(), sagaId);
                            }
                        });
            } catch (Exception e) {
                logger.error("Error initiating order confirmation for saga: {} (orderId: {})",
                        sagaId, orderId, e);
            }
        }
    }
}
