package com.theyawns.ecommerce.order.saga;

import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.nio.serialization.genericrecord.GenericRecord;
import com.hazelcast.topic.ITopic;
import com.hazelcast.topic.Message;
import com.hazelcast.topic.MessageListener;
import com.theyawns.ecommerce.common.events.PaymentFailedEvent;
import com.theyawns.ecommerce.common.events.PaymentProcessedEvent;
import com.theyawns.ecommerce.order.service.OrderOperations;
import com.theyawns.framework.dlq.DeadLetterEntry;
import com.theyawns.framework.dlq.DeadLetterQueueOperations;
import com.theyawns.framework.idempotency.IdempotencyGuard;
import com.theyawns.framework.resilience.ResilienceException;
import com.theyawns.framework.resilience.ResilientOperations;
import com.theyawns.framework.tracing.EventSpanDecorator;
import io.micrometer.tracing.Span;
import jakarta.annotation.PostConstruct;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

import java.util.concurrent.CompletableFuture;
import java.util.function.Supplier;

/**
 * Saga event listener for the Order Service.
 *
 * <p>Listens for saga-related events that trigger order state transitions:
 * <ul>
 *   <li>{@link PaymentProcessedEvent} - Triggers order confirmation (saga step 3)</li>
 *   <li>{@link PaymentFailedEvent} - Triggers order cancellation compensation</li>
 * </ul>
 *
 * <p>This component connects the Order Service to the choreographed saga
 * for order fulfillment. When payment is processed (step 2), the order
 * service automatically confirms the order (step 3) and marks the saga
 * as COMPLETED.
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
@Component
public class OrderSagaListener {

    private static final Logger logger = LoggerFactory.getLogger(OrderSagaListener.class);

    private final OrderOperations orderService;
    private final HazelcastInstance hazelcast;
    private EventSpanDecorator eventSpanDecorator;
    private ResilientOperations resilientServiceInvoker;
    private IdempotencyGuard idempotencyGuard;
    private DeadLetterQueueOperations deadLetterQueue;

    /**
     * Creates a new OrderSagaListener.
     *
     * @param orderService the order service for order operations
     * @param hazelcast the shared Hazelcast client for cross-service topic subscriptions
     */
    public OrderSagaListener(OrderOperations orderService,
                             @Qualifier("hazelcastClient") HazelcastInstance hazelcast) {
        this.orderService = orderService;
        this.hazelcast = hazelcast;
    }

    /**
     * Sets the event span decorator for distributed tracing (optional).
     *
     * @param eventSpanDecorator the span decorator
     */
    @Autowired(required = false)
    public void setEventSpanDecorator(EventSpanDecorator eventSpanDecorator) {
        this.eventSpanDecorator = eventSpanDecorator;
    }

    /**
     * Sets the resilient service invoker for circuit breaker protection (optional).
     *
     * <p>When set, all saga service calls are wrapped with circuit breaker and retry
     * decoration. When not set (e.g., resilience disabled), calls delegate directly.
     *
     * @param resilientServiceInvoker the resilient service invoker
     */
    @Autowired(required = false)
    public void setResilientOperations(ResilientOperations resilientServiceInvoker) {
        this.resilientServiceInvoker = resilientServiceInvoker;
    }

    /**
     * Sets the idempotency guard for duplicate event detection (optional).
     *
     * @param idempotencyGuard the idempotency guard
     */
    @Autowired(required = false)
    public void setIdempotencyGuard(IdempotencyGuard idempotencyGuard) {
        this.idempotencyGuard = idempotencyGuard;
    }

    /**
     * Sets the dead letter queue for failed event capture (optional).
     *
     * @param deadLetterQueue the DLQ operations
     */
    @Autowired(required = false)
    public void setDeadLetterQueue(DeadLetterQueueOperations deadLetterQueue) {
        this.deadLetterQueue = deadLetterQueue;
    }

    /**
     * Executes an async operation with circuit breaker protection if available.
     *
     * @param name the circuit breaker instance name
     * @param operation the async operation to execute
     * @param <T> the return type
     * @return the CompletableFuture result
     */
    private <T> CompletableFuture<T> executeWithResilience(
            final String name, final Supplier<CompletableFuture<T>> operation) {
        if (resilientServiceInvoker != null) {
            return resilientServiceInvoker.executeAsync(name, operation);
        }
        return operation.get();
    }

    /**
     * Registers listeners for saga-related topics on startup.
     */
    @PostConstruct
    public void registerListeners() {
        logger.info("Registering order saga event listeners");

        ITopic<GenericRecord> paymentProcessedTopic = hazelcast.getTopic("PaymentProcessed");
        paymentProcessedTopic.addMessageListener(new PaymentProcessedListener());

        ITopic<GenericRecord> paymentFailedTopic = hazelcast.getTopic("PaymentFailed");
        paymentFailedTopic.addMessageListener(new PaymentFailedListener());

        logger.info("Order saga listeners registered successfully");
    }

    /**
     * Sends a failed event to the dead letter queue if available,
     * otherwise falls back to logging.
     *
     * @param record the event record that failed processing
     * @param topicName the ITopic name
     * @param error the failure cause
     */
    private void sendToDeadLetterQueue(GenericRecord record, String topicName, Throwable error) {
        String eventId = record.getString("eventId");
        if (deadLetterQueue != null) {
            try {
                deadLetterQueue.add(DeadLetterEntry.builder()
                        .originalEventId(eventId)
                        .eventType(record.getString("eventType"))
                        .topicName(topicName)
                        .eventRecord(record)
                        .failureReason(error.getMessage())
                        .sourceService("order-service")
                        .sagaId(record.getString("sagaId"))
                        .correlationId(record.getString("correlationId"))
                        .build());
                logger.warn("Event {} sent to DLQ after failure: {}", eventId, error.getMessage());
            } catch (Exception dlqError) {
                logger.error("Failed to send event {} to DLQ: {}", eventId, dlqError.getMessage());
            }
        } else {
            if (error instanceof ResilienceException) {
                logger.warn("Circuit breaker open, saga step deferred: eventId={}", eventId);
            } else {
                logger.error("Failed to process event: {}", eventId, error);
            }
        }
    }

    /**
     * Listener for PaymentProcessed events.
     *
     * <p>When payment is processed as part of a saga, confirms the order
     * and marks the saga as COMPLETED. This is the final step (step 3)
     * in the Order Fulfillment saga happy path.
     */
    class PaymentProcessedListener implements MessageListener<GenericRecord> {

        @Override
        public void onMessage(Message<GenericRecord> message) {
            GenericRecord record = message.getMessageObject();

            String eventId = record.getString("eventId");
            if (idempotencyGuard != null && eventId != null && !idempotencyGuard.tryProcess(eventId)) {
                logger.debug("Duplicate event {} already processed, skipping", eventId);
                return;
            }

            String sagaId = record.getString("sagaId");
            if (sagaId == null || sagaId.isEmpty()) {
                logger.debug("PaymentProcessed event without sagaId - not a saga event, ignoring");
                return;
            }

            String orderId = record.getString("orderId");
            String correlationId = record.getString("correlationId");

            logger.info("Received PaymentProcessed saga event: orderId={}, sagaId={}", orderId, sagaId);

            Span span = null;
            if (eventSpanDecorator != null) {
                span = eventSpanDecorator.startSagaSpan("PaymentProcessed", sagaId,
                        "OrderFulfillment", 3);
            }
            final Span currentSpan = span;

            try {
                executeWithResilience("order-confirmation",
                        () -> orderService.confirmOrderForSaga(orderId, sagaId, correlationId)
                ).whenComplete((order, error) -> {
                    if (error != null) {
                        sendToDeadLetterQueue(record, "PaymentProcessed", error);
                        if (eventSpanDecorator != null) {
                            eventSpanDecorator.recordError(currentSpan, error);
                        }
                    } else {
                        logger.info("Order confirmed via saga: orderId={}, status={}, sagaId={}",
                                orderId, order.getStatus(), sagaId);
                    }
                    if (eventSpanDecorator != null) {
                        eventSpanDecorator.endSpan(currentSpan);
                    }
                });
            } catch (Exception e) {
                logger.error("Error initiating order confirmation for saga: {} (orderId: {})",
                        sagaId, orderId, e);
                if (eventSpanDecorator != null) {
                    eventSpanDecorator.recordError(currentSpan, e);
                    eventSpanDecorator.endSpan(currentSpan);
                }
            }
        }
    }

    /**
     * Listener for PaymentFailed events.
     *
     * <p>When payment fails as part of a saga, cancels the order and marks
     * the saga as COMPENSATED. This compensates step 0 (OrderCreated) and
     * finalizes the compensation flow.
     */
    class PaymentFailedListener implements MessageListener<GenericRecord> {

        @Override
        public void onMessage(Message<GenericRecord> message) {
            GenericRecord record = message.getMessageObject();

            String eventId = record.getString("eventId");
            if (idempotencyGuard != null && eventId != null && !idempotencyGuard.tryProcess(eventId)) {
                logger.debug("Duplicate event {} already processed, skipping", eventId);
                return;
            }

            String sagaId = record.getString("sagaId");
            if (sagaId == null || sagaId.isEmpty()) {
                logger.debug("PaymentFailed event without sagaId - not a saga event, ignoring");
                return;
            }

            String orderId = record.getString("orderId");
            String correlationId = record.getString("correlationId");
            String failureReason = record.getString("failureReason");

            logger.info("Received PaymentFailed saga event for order cancellation: orderId={}, sagaId={}, reason={}",
                    orderId, sagaId, failureReason);

            Span span = null;
            if (eventSpanDecorator != null) {
                span = eventSpanDecorator.startSagaSpan("PaymentFailed", sagaId,
                        "OrderFulfillment", 3);
            }
            final Span currentSpan = span;

            try {
                executeWithResilience("order-cancellation",
                        () -> orderService.cancelOrderForSaga(
                                orderId,
                                "Payment failed: " + failureReason,
                                sagaId,
                                correlationId
                        )
                ).whenComplete((order, error) -> {
                    if (error != null) {
                        sendToDeadLetterQueue(record, "PaymentFailed", error);
                        if (eventSpanDecorator != null) {
                            eventSpanDecorator.recordError(currentSpan, error);
                        }
                    } else {
                        logger.info("Order cancelled via saga compensation: orderId={}, status={}, sagaId={}",
                                orderId, order.getStatus(), sagaId);
                    }
                    if (eventSpanDecorator != null) {
                        eventSpanDecorator.endSpan(currentSpan);
                    }
                });
            } catch (Exception e) {
                logger.error("Error initiating order cancellation for saga compensation: {} (orderId: {})",
                        sagaId, orderId, e);
                if (eventSpanDecorator != null) {
                    eventSpanDecorator.recordError(currentSpan, e);
                    eventSpanDecorator.endSpan(currentSpan);
                }
            }
        }
    }
}
