package com.theyawns.ecommerce.mcp.security;

import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.web.filter.OncePerRequestFilter;

import java.io.IOException;

/**
 * Servlet filter that validates API keys on HTTP/SSE MCP requests.
 *
 * <p>Active only when the MCP server runs with {@code spring.main.web-application-type=servlet}
 * (Docker profile). Reads the {@code X-API-Key} header from each request, resolves the
 * corresponding {@link McpRole}, and stores it in a {@link ThreadLocal} for
 * {@link ToolAuthorizer} to read during tool invocation.
 *
 * <p>Requests to health/actuator endpoints are permitted without authentication.
 * All other requests require a valid API key.
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
public class McpApiKeyFilter extends OncePerRequestFilter {

    private static final Logger logger = LoggerFactory.getLogger(McpApiKeyFilter.class);

    /** HTTP header name for API key. */
    public static final String API_KEY_HEADER = "X-API-Key";

    private final McpSecurityProperties properties;

    /**
     * Creates a new McpApiKeyFilter.
     *
     * @param properties the security properties for key→role resolution
     */
    public McpApiKeyFilter(final McpSecurityProperties properties) {
        this.properties = properties;
    }

    @Override
    protected void doFilterInternal(final HttpServletRequest request,
                                     final HttpServletResponse response,
                                     final FilterChain filterChain)
            throws ServletException, IOException {

        final String path = request.getRequestURI();

        // Permit actuator/health endpoints without authentication
        if (path.startsWith("/actuator")) {
            filterChain.doFilter(request, response);
            return;
        }

        final String apiKey = request.getHeader(API_KEY_HEADER);
        if (apiKey == null || apiKey.isBlank()) {
            logger.warn("Missing API key in request to {}", path);
            sendUnauthorized(response, "Missing API key. Provide X-API-Key header.");
            return;
        }

        final McpRole role = properties.resolveRole(apiKey);
        if (role == null) {
            logger.warn("Invalid API key in request to {}", path);
            sendUnauthorized(response, "Invalid API key.");
            return;
        }

        try {
            ToolAuthorizer.setRequestRole(role);
            filterChain.doFilter(request, response);
        } finally {
            ToolAuthorizer.clearRequestRole();
        }
    }

    private void sendUnauthorized(final HttpServletResponse response, final String message)
            throws IOException {
        response.setStatus(HttpServletResponse.SC_UNAUTHORIZED);
        response.setContentType("application/json");
        response.getWriter().write("{\"error\":\"unauthorized\",\"message\":\"" + message + "\"}");
    }
}
