package com.theyawns.ecommerce.mcp.security;

import java.util.Set;

/**
 * Roles for MCP server tool access control.
 *
 * <p>Each role defines a set of tools that the holder is permitted to invoke:
 * <ul>
 *   <li><strong>VIEWER</strong> — Read-only access to queries, metrics, and saga inspection</li>
 *   <li><strong>OPERATOR</strong> — Read + write: can also submit events and run demo scenarios</li>
 *   <li><strong>ADMIN</strong> — Full access (same as OPERATOR today; future-proofed for
 *       admin-only tools such as DLQ management or configuration changes)</li>
 * </ul>
 *
 * @author Generated by Claude Code
 * @since 3.0
 * @see ToolAuthorizer
 */
public enum McpRole {

    /**
     * Read-only access. Can query views, inspect sagas, list sagas, read event
     * history, view metrics, and inspect DLQ entries. Cannot modify state.
     */
    VIEWER(Set.of("queryView", "getEventHistory", "inspectSaga", "listSagas", "getMetrics",
            "listDlqEntries", "inspectDlqEntry")),

    /**
     * Read + write access. Includes all VIEWER permissions plus the ability to
     * submit events, run demo scenarios, and replay DLQ entries.
     */
    OPERATOR(Set.of("queryView", "getEventHistory", "inspectSaga", "listSagas", "getMetrics",
            "submitEvent", "runDemo", "listDlqEntries", "inspectDlqEntry", "replayDlqEntry")),

    /**
     * Full administrative access. Includes all OPERATOR permissions.
     */
    ADMIN(Set.of("queryView", "getEventHistory", "inspectSaga", "listSagas", "getMetrics",
            "submitEvent", "runDemo", "listDlqEntries", "inspectDlqEntry", "replayDlqEntry"));

    private final Set<String> allowedTools;

    McpRole(final Set<String> allowedTools) {
        this.allowedTools = allowedTools;
    }

    /**
     * Checks whether this role permits access to the named tool.
     *
     * @param toolName the tool name (e.g., "queryView", "submitEvent")
     * @return true if this role can invoke the tool
     */
    public boolean canAccess(final String toolName) {
        return allowedTools.contains(toolName);
    }

    /**
     * Returns the set of tool names this role can access.
     *
     * @return unmodifiable set of allowed tool names
     */
    public Set<String> getAllowedTools() {
        return allowedTools;
    }
}
