package com.theyawns.ecommerce.order.saga.orchestrated;

import com.theyawns.ecommerce.common.domain.Order;
import com.theyawns.ecommerce.common.dto.OrchestratedStepResponse;
import com.theyawns.ecommerce.common.dto.OrderDTO;
import com.theyawns.ecommerce.common.dto.OrderLineItemDTO;
import com.theyawns.ecommerce.order.service.OrderOperations;
import com.theyawns.framework.saga.orchestrator.SagaContext;
import com.theyawns.framework.saga.orchestrator.SagaDefinition;
import com.theyawns.framework.saga.orchestrator.SagaStepResult;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.time.Duration;
import java.util.List;
import java.util.Map;
import java.util.concurrent.CompletableFuture;

/**
 * Factory that creates a {@link SagaDefinition} for the Order Fulfillment saga.
 *
 * <p>Defines a 4-step saga:
 * <ol>
 *   <li><strong>CreateOrder</strong>: Creates the order locally (compensation: cancel order)</li>
 *   <li><strong>ReserveStock</strong>: HTTP call to inventory-service (compensation: release stock)</li>
 *   <li><strong>ProcessPayment</strong>: HTTP call to payment-service (compensation: refund payment)</li>
 *   <li><strong>ConfirmOrder</strong>: Confirms the order locally (no compensation — final step)</li>
 * </ol>
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
@Component
public class OrderFulfillmentSagaFactory {

    private static final Logger logger = LoggerFactory.getLogger(OrderFulfillmentSagaFactory.class);

    private final OrderOperations orderOps;
    private final SagaServiceClientOperations serviceClient;

    /**
     * Creates a new factory.
     *
     * @param orderOps the order operations service
     * @param serviceClient the HTTP client for remote service calls
     */
    public OrderFulfillmentSagaFactory(final OrderOperations orderOps,
                                        final SagaServiceClientOperations serviceClient) {
        this.orderOps = orderOps;
        this.serviceClient = serviceClient;
    }

    /**
     * Creates a new Order Fulfillment saga definition.
     *
     * @return the saga definition
     */
    public SagaDefinition create() {
        return SagaDefinition.builder()
                .name("OrderFulfillment")

                // Step 0: Create Order
                .step("CreateOrder")
                    .action(this::createOrderAction)
                    .compensation(this::createOrderCompensation)
                    .timeout(Duration.ofSeconds(15))
                    .build()

                // Step 1: Reserve Stock
                .step("ReserveStock")
                    .action(this::reserveStockAction)
                    .compensation(this::reserveStockCompensation)
                    .timeout(Duration.ofSeconds(15))
                    .build()

                // Step 2: Process Payment
                .step("ProcessPayment")
                    .action(this::processPaymentAction)
                    .compensation(this::processPaymentCompensation)
                    .timeout(Duration.ofSeconds(15))
                    .build()

                // Step 3: Confirm Order (final step — no compensation)
                .step("ConfirmOrder")
                    .action(this::confirmOrderAction)
                    .noCompensation()
                    .timeout(Duration.ofSeconds(10))
                    .build()

                .sagaTimeout(Duration.ofSeconds(60))
                .build();
    }

    // ========== Step 0: Create Order ==========

    private CompletableFuture<SagaStepResult> createOrderAction(final SagaContext context) {
        logger.debug("Executing CreateOrder action");

        OrderDTO dto = buildOrderDTO(context);

        return orderOps.createOrderPlain(dto)
                .thenApply(order -> {
                    context.put("orderId", order.getOrderId());
                    logger.debug("Order created: {}", order.getOrderId());
                    return SagaStepResult.success(Map.of("orderId", order.getOrderId()));
                })
                .exceptionally(ex -> {
                    String msg = ex.getCause() != null ? ex.getCause().getMessage() : ex.getMessage();
                    logger.error("CreateOrder failed: {}", msg);
                    return SagaStepResult.failure("CreateOrder failed: " + msg);
                });
    }

    private CompletableFuture<SagaStepResult> createOrderCompensation(final SagaContext context) {
        String orderId = context.get("orderId", String.class);
        logger.debug("Compensating CreateOrder: orderId={}", orderId);

        if (orderId == null) {
            return CompletableFuture.completedFuture(SagaStepResult.success());
        }

        return orderOps.cancelOrder(orderId, "Orchestrated saga compensation", "orchestrator")
                .thenApply(order -> SagaStepResult.success())
                .exceptionally(ex -> {
                    String msg = ex.getCause() != null ? ex.getCause().getMessage() : ex.getMessage();
                    logger.error("CreateOrder compensation failed: {}", msg);
                    return SagaStepResult.failure("CancelOrder failed: " + msg);
                });
    }

    // ========== Step 1: Reserve Stock ==========

    private CompletableFuture<SagaStepResult> reserveStockAction(final SagaContext context) {
        String productId = context.get("productId", String.class);
        Integer quantity = context.get("quantity", Integer.class);
        String orderId = context.get("orderId", String.class);

        logger.debug("Executing ReserveStock action: productId={}, quantity={}, orderId={}",
                productId, quantity, orderId);

        return CompletableFuture.supplyAsync(() -> {
            OrchestratedStepResponse response = serviceClient.reserveStock(productId, quantity, orderId);
            if (response.success()) {
                return SagaStepResult.success(response.data());
            } else {
                return SagaStepResult.failure(response.errorMessage());
            }
        });
    }

    private CompletableFuture<SagaStepResult> reserveStockCompensation(final SagaContext context) {
        String orderId = context.get("orderId", String.class);
        logger.debug("Compensating ReserveStock: orderId={}", orderId);

        return CompletableFuture.supplyAsync(() -> {
            OrchestratedStepResponse response = serviceClient.releaseStock(orderId,
                    "Orchestrated saga compensation");
            if (response.success()) {
                return SagaStepResult.success();
            } else {
                return SagaStepResult.failure(response.errorMessage());
            }
        });
    }

    // ========== Step 2: Process Payment ==========

    private CompletableFuture<SagaStepResult> processPaymentAction(final SagaContext context) {
        String orderId = context.get("orderId", String.class);
        String customerId = context.get("customerId", String.class);
        String amount = context.get("amount", String.class);
        String currency = context.get("currency", String.class);
        String method = context.get("paymentMethod", String.class);

        logger.debug("Executing ProcessPayment action: orderId={}, amount={}", orderId, amount);

        return CompletableFuture.supplyAsync(() -> {
            OrchestratedStepResponse response = serviceClient.processPayment(
                    orderId, customerId, amount, currency, method);
            if (response.success()) {
                // Store paymentId from response for potential compensation
                Object paymentId = response.data().get("paymentId");
                if (paymentId != null) {
                    context.put("paymentId", paymentId.toString());
                }
                return SagaStepResult.success(response.data());
            } else {
                return SagaStepResult.failure(response.errorMessage());
            }
        });
    }

    private CompletableFuture<SagaStepResult> processPaymentCompensation(final SagaContext context) {
        String paymentId = context.get("paymentId", String.class);
        logger.debug("Compensating ProcessPayment: paymentId={}", paymentId);

        if (paymentId == null) {
            return CompletableFuture.completedFuture(SagaStepResult.success());
        }

        return CompletableFuture.supplyAsync(() -> {
            OrchestratedStepResponse response = serviceClient.refundPayment(paymentId,
                    "Orchestrated saga compensation");
            if (response.success()) {
                return SagaStepResult.success();
            } else {
                return SagaStepResult.failure(response.errorMessage());
            }
        });
    }

    // ========== Step 3: Confirm Order ==========

    private CompletableFuture<SagaStepResult> confirmOrderAction(final SagaContext context) {
        String orderId = context.get("orderId", String.class);
        logger.debug("Executing ConfirmOrder action: orderId={}", orderId);

        return orderOps.confirmOrder(orderId)
                .thenApply(order -> SagaStepResult.success())
                .exceptionally(ex -> {
                    String msg = ex.getCause() != null ? ex.getCause().getMessage() : ex.getMessage();
                    logger.error("ConfirmOrder failed: {}", msg);
                    return SagaStepResult.failure("ConfirmOrder failed: " + msg);
                });
    }

    // ========== Helpers ==========

    /**
     * Builds an OrderDTO from the saga context data.
     */
    @SuppressWarnings("unchecked")
    private OrderDTO buildOrderDTO(final SagaContext context) {
        OrderDTO dto = new OrderDTO();
        dto.setCustomerId(context.get("customerId", String.class));
        dto.setCustomerName((String) context.getOrDefault("customerName", null));
        dto.setCustomerEmail((String) context.getOrDefault("customerEmail", null));
        dto.setShippingAddress(context.get("shippingAddress", String.class));

        Object lineItemsObj = context.get("lineItems");
        if (lineItemsObj instanceof List) {
            dto.setLineItems((List<OrderLineItemDTO>) lineItemsObj);
        }

        return dto;
    }
}
