package com.theyawns.ecommerce.order.saga.orchestrated;

import com.theyawns.ecommerce.common.dto.OrchestratedStepResponse;

/**
 * Interface for HTTP calls to remote services during orchestrated saga execution.
 *
 * <p>Extracted as an interface (following the Java 25 + Mockito pattern) so that
 * tests can mock the HTTP client without requiring a running remote service.
 *
 * @author Generated by Claude Code
 * @since 3.0
 * @see SagaServiceClient
 */
public interface SagaServiceClientOperations {

    /**
     * Reserves stock for an order via inventory-service.
     *
     * @param productId the product ID
     * @param quantity the quantity to reserve
     * @param orderId the order ID
     * @return the step response
     */
    OrchestratedStepResponse reserveStock(String productId, int quantity, String orderId);

    /**
     * Releases previously reserved stock via inventory-service (compensation).
     *
     * @param orderId the order ID
     * @param reason the release reason
     * @return the step response
     */
    OrchestratedStepResponse releaseStock(String orderId, String reason);

    /**
     * Processes a payment via payment-service.
     *
     * @param orderId the order ID
     * @param customerId the customer ID
     * @param amount the payment amount
     * @param currency the currency code
     * @param method the payment method
     * @return the step response
     */
    OrchestratedStepResponse processPayment(String orderId, String customerId,
                                              String amount, String currency, String method);

    /**
     * Refunds a payment via payment-service (compensation).
     *
     * @param paymentId the payment ID
     * @param reason the refund reason
     * @return the step response
     */
    OrchestratedStepResponse refundPayment(String paymentId, String reason);
}
