package com.theyawns.ecommerce.order.saga.orchestrated;

import com.theyawns.ecommerce.common.dto.OrchestratedStepResponse;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Component;
import org.springframework.web.client.RestClient;

import java.util.Map;

/**
 * HTTP client for calling remote service endpoints during orchestrated saga execution.
 *
 * <p>Makes POST requests to inventory-service and payment-service orchestrated endpoints.
 * On HTTP errors, returns {@link OrchestratedStepResponse#failure} rather than throwing,
 * so the orchestrator can handle failures gracefully.
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
@Component
public class SagaServiceClient implements SagaServiceClientOperations {

    private static final Logger logger = LoggerFactory.getLogger(SagaServiceClient.class);

    private final RestClient inventoryClient;
    private final RestClient paymentClient;

    /**
     * Creates a new SagaServiceClient.
     *
     * @param restClientBuilder the Spring RestClient builder
     * @param inventoryBaseUrl the inventory-service base URL
     * @param paymentBaseUrl the payment-service base URL
     */
    public SagaServiceClient(
            RestClient.Builder restClientBuilder,
            @Value("${framework.saga.orchestrator.services.inventory.base-url:http://localhost:8082}")
            String inventoryBaseUrl,
            @Value("${framework.saga.orchestrator.services.payment.base-url:http://localhost:8084}")
            String paymentBaseUrl) {
        this.inventoryClient = restClientBuilder.clone().baseUrl(inventoryBaseUrl).build();
        this.paymentClient = restClientBuilder.clone().baseUrl(paymentBaseUrl).build();
    }

    @Override
    public OrchestratedStepResponse reserveStock(final String productId, final int quantity,
                                                   final String orderId) {
        logger.debug("Calling inventory-service to reserve stock: productId={}, quantity={}, orderId={}",
                productId, quantity, orderId);
        try {
            return inventoryClient.post()
                    .uri("/api/saga/inventory/reserve-stock")
                    .contentType(MediaType.APPLICATION_JSON)
                    .body(Map.of("productId", productId, "quantity", quantity, "orderId", orderId))
                    .retrieve()
                    .body(OrchestratedStepResponse.class);
        } catch (Exception e) {
            logger.error("Failed to reserve stock: {}", e.getMessage(), e);
            return OrchestratedStepResponse.failure("Reserve stock failed: " + e.getMessage());
        }
    }

    @Override
    public OrchestratedStepResponse releaseStock(final String orderId, final String reason) {
        logger.debug("Calling inventory-service to release stock: orderId={}, reason={}", orderId, reason);
        try {
            return inventoryClient.post()
                    .uri("/api/saga/inventory/release-stock")
                    .contentType(MediaType.APPLICATION_JSON)
                    .body(Map.of("orderId", orderId, "reason", reason))
                    .retrieve()
                    .body(OrchestratedStepResponse.class);
        } catch (Exception e) {
            logger.error("Failed to release stock: {}", e.getMessage(), e);
            return OrchestratedStepResponse.failure("Release stock failed: " + e.getMessage());
        }
    }

    @Override
    public OrchestratedStepResponse processPayment(final String orderId, final String customerId,
                                                      final String amount, final String currency,
                                                      final String method) {
        logger.debug("Calling payment-service to process payment: orderId={}, amount={}", orderId, amount);
        try {
            return paymentClient.post()
                    .uri("/api/saga/payment/process")
                    .contentType(MediaType.APPLICATION_JSON)
                    .body(Map.of(
                            "orderId", orderId,
                            "customerId", customerId,
                            "amount", amount,
                            "currency", currency,
                            "method", method
                    ))
                    .retrieve()
                    .body(OrchestratedStepResponse.class);
        } catch (Exception e) {
            logger.error("Failed to process payment: {}", e.getMessage(), e);
            return OrchestratedStepResponse.failure("Process payment failed: " + e.getMessage());
        }
    }

    @Override
    public OrchestratedStepResponse refundPayment(final String paymentId, final String reason) {
        logger.debug("Calling payment-service to refund payment: paymentId={}, reason={}", paymentId, reason);
        try {
            return paymentClient.post()
                    .uri("/api/saga/payment/refund")
                    .contentType(MediaType.APPLICATION_JSON)
                    .body(Map.of("paymentId", paymentId, "reason", reason))
                    .retrieve()
                    .body(OrchestratedStepResponse.class);
        } catch (Exception e) {
            logger.error("Failed to refund payment: {}", e.getMessage(), e);
            return OrchestratedStepResponse.failure("Refund payment failed: " + e.getMessage());
        }
    }
}
