package com.theyawns.framework.domain;

import com.hazelcast.nio.serialization.genericrecord.GenericRecord;

import java.io.Serializable;

/**
 * Interface for all domain objects in the event sourcing framework.
 * Domain objects represent the current state of an entity, derived from
 * applying a sequence of events.
 *
 * <p>Key characteristics:
 * <ul>
 *   <li>Uniquely identified by a key of type K</li>
 *   <li>Serializable to GenericRecord for Hazelcast storage</li>
 *   <li>Can be hydrated from GenericRecord</li>
 *   <li>State is derived from events, not directly mutated</li>
 * </ul>
 *
 * @param <K> The key type used to identify this domain object
 * @author Generated by Claude Code
 * @since 1.0
 */
public interface DomainObject<K> extends Serializable {

    /**
     * Returns the unique identifier for this domain object.
     *
     * @return the key identifying this object
     */
    K getKey();

    /**
     * Serializes this domain object to a GenericRecord for storage in Hazelcast.
     * The GenericRecord format allows schema evolution and cross-language compatibility.
     *
     * @return GenericRecord representation of this domain object
     */
    GenericRecord toGenericRecord();

    /**
     * Returns the schema name used for GenericRecord serialization.
     * This should be unique per domain object type.
     *
     * @return the schema name for this domain object type
     */
    String getSchemaName();
}