package com.theyawns.ecommerce.gateway.error;

import com.theyawns.ecommerce.gateway.filter.CorrelationIdFilter;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.mock.http.server.reactive.MockServerHttpRequest;
import org.springframework.mock.web.server.MockServerWebExchange;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Tests for {@link CircuitBreakerFallbackHandler}.
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
@DisplayName("CircuitBreakerFallbackHandler - Fallback responses")
class CircuitBreakerFallbackHandlerTest {

    private CircuitBreakerFallbackHandler handler;

    @BeforeEach
    void setUp() {
        handler = new CircuitBreakerFallbackHandler();
    }

    @Test
    @DisplayName("should return 503 status")
    void shouldReturn503Status() {
        final MockServerWebExchange exchange = createExchange(null);

        final ResponseEntity<GatewayErrorResponse> response = handler.fallback("order-service", exchange);

        assertThat(response.getStatusCode()).isEqualTo(HttpStatus.SERVICE_UNAVAILABLE);
        assertThat(response.getBody()).isNotNull();
        assertThat(response.getBody().getStatus()).isEqualTo(503);
    }

    @Test
    @DisplayName("should include service name in message")
    void shouldIncludeServiceNameInMessage() {
        final MockServerWebExchange exchange = createExchange(null);

        final ResponseEntity<GatewayErrorResponse> response = handler.fallback("payment-service", exchange);

        assertThat(response.getBody()).isNotNull();
        assertThat(response.getBody().getMessage()).contains("payment-service");
    }

    @Test
    @DisplayName("should include correlation ID from exchange")
    void shouldIncludeCorrelationId() {
        final MockServerWebExchange exchange = createExchange("test-corr-123");

        final ResponseEntity<GatewayErrorResponse> response = handler.fallback("account-service", exchange);

        assertThat(response.getBody()).isNotNull();
        assertThat(response.getBody().getCorrelationId()).isEqualTo("test-corr-123");
    }

    @Test
    @DisplayName("should set CIRCUIT_BREAKER_OPEN error code")
    void shouldSetCircuitBreakerOpenErrorCode() {
        final MockServerWebExchange exchange = createExchange(null);

        final ResponseEntity<GatewayErrorResponse> response = handler.fallback("inventory-service", exchange);

        assertThat(response.getBody()).isNotNull();
        assertThat(response.getBody().getErrorCode()).isEqualTo("CIRCUIT_BREAKER_OPEN");
    }

    private MockServerWebExchange createExchange(final String correlationId) {
        final MockServerHttpRequest request = MockServerHttpRequest
                .get("/fallback/test-service")
                .build();
        final MockServerWebExchange exchange = MockServerWebExchange.from(request);
        if (correlationId != null) {
            exchange.getAttributes().put(CorrelationIdFilter.CORRELATION_ID_ATTR, correlationId);
        }
        return exchange;
    }
}
