package com.theyawns.ecommerce.gateway.filter;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.cloud.gateway.filter.GatewayFilterChain;
import org.springframework.cloud.gateway.filter.GlobalFilter;
import org.springframework.core.Ordered;
import org.springframework.http.HttpStatusCode;
import org.springframework.http.server.reactive.ServerHttpRequest;
import org.springframework.stereotype.Component;
import org.springframework.web.server.ServerWebExchange;
import reactor.core.publisher.Mono;

/**
 * Global filter that logs inbound requests and outbound responses.
 *
 * <p>Each log entry includes the HTTP method, URI path, correlation ID
 * (set by {@link CorrelationIdFilter}), and — for responses — the
 * HTTP status code. This provides a clear audit trail for debugging
 * and operational monitoring.
 *
 * <p>Filter order: {@code -1} (runs last among custom filters, so all
 * context like correlation ID and rate limit decisions are available).
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
@Component
public class RequestLoggingFilter implements GlobalFilter, Ordered {

    private static final Logger logger = LoggerFactory.getLogger(RequestLoggingFilter.class);

    @Override
    public Mono<Void> filter(final ServerWebExchange exchange, final GatewayFilterChain chain) {
        final ServerHttpRequest request = exchange.getRequest();
        final String method = request.getMethod() != null ? request.getMethod().name() : "UNKNOWN";
        final String path = request.getURI().getPath();
        final String correlationId = exchange.getAttribute(CorrelationIdFilter.CORRELATION_ID_ATTR);

        logger.info(">>> {} {} [correlationId={}]", method, path, correlationId);

        return chain.filter(exchange)
                .doFinally(signalType -> {
                    final HttpStatusCode status = exchange.getResponse().getStatusCode();
                    final int statusValue = status != null ? status.value() : 0;
                    logger.info("<<< {} {} -> {} [correlationId={}]",
                            method, path, statusValue, correlationId);
                });
    }

    @Override
    public int getOrder() {
        return -1;
    }
}
