package com.theyawns.framework.vectorstore;

import com.hazelcast.core.HazelcastInstance;
import com.theyawns.framework.edition.ConditionalOnEnterpriseFeature;
import com.theyawns.framework.edition.EditionDetector.EnterpriseFeature;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.autoconfigure.AutoConfiguration;
import org.springframework.boot.autoconfigure.AutoConfigureBefore;
import org.springframework.boot.autoconfigure.condition.ConditionalOnBean;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;

/**
 * Auto-configuration for the Enterprise vector store using Hazelcast {@code VectorCollection}.
 *
 * <p>This configuration is activated when:
 * <ol>
 *   <li>A {@link HazelcastInstance} bean is present</li>
 *   <li>Enterprise Edition is detected with the VECTOR_STORE feature available</li>
 * </ol>
 *
 * <p>It runs <strong>before</strong> {@link VectorStoreAutoConfiguration} in {@code framework-core},
 * so the Enterprise bean is registered first. When present, the core configuration's
 * {@code @ConditionalOnMissingBean} safety-net skips creating the {@link NoOpVectorStoreService}.
 *
 * <p>If this module is not on the classpath (i.e., community build without {@code -Penterprise}),
 * the core configuration creates a {@link NoOpVectorStoreService} fallback as usual.
 *
 * @author Generated by Claude Code
 * @since 2.0
 * @see HazelcastVectorStoreService
 * @see VectorStoreAutoConfiguration
 */
@AutoConfiguration
@AutoConfigureBefore(VectorStoreAutoConfiguration.class)
@ConditionalOnBean(HazelcastInstance.class)
@EnableConfigurationProperties(VectorStoreProperties.class)
public class EnterpriseVectorStoreAutoConfiguration {

    private static final Logger logger = LoggerFactory.getLogger(EnterpriseVectorStoreAutoConfiguration.class);

    /**
     * Creates the Enterprise {@link HazelcastVectorStoreService} bean.
     *
     * <p>Only created when the Enterprise Edition is detected and the VECTOR_STORE
     * feature is available (i.e., {@code com.hazelcast.vector.VectorCollection} is
     * on the classpath).
     *
     * @param hazelcastInstance the Hazelcast Enterprise instance
     * @param properties the vector store configuration properties
     * @return the Enterprise vector store service
     */
    @Bean
    @ConditionalOnEnterpriseFeature(EnterpriseFeature.VECTOR_STORE)
    public VectorStoreService hazelcastVectorStoreService(
            final HazelcastInstance hazelcastInstance,
            final VectorStoreProperties properties) {
        logger.info("Creating HazelcastVectorStoreService (Enterprise VectorCollection with HNSW indexing)");
        return new HazelcastVectorStoreService(hazelcastInstance, properties);
    }
}
