package com.theyawns.framework.vectorstore;

import com.hazelcast.config.Config;
import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.vector.Metric;
import com.hazelcast.vector.SearchOptions;
import com.hazelcast.vector.SearchResult;
import com.hazelcast.vector.SearchResults;
import com.hazelcast.vector.VectorCollection;
import com.hazelcast.vector.VectorCollectionConfig;
import com.hazelcast.vector.VectorDocument;
import com.hazelcast.vector.VectorIndexConfig;
import com.hazelcast.vector.VectorValues;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Enterprise vector store implementation using Hazelcast {@code VectorCollection}
 * with HNSW (Hierarchical Navigable Small World) indexing.
 *
 * <p>This implementation uses Hazelcast Enterprise's native vector search data structure,
 * which provides O(log n) approximate nearest-neighbor search via an HNSW index. This is
 * significantly faster than brute-force cosine similarity for large datasets.
 *
 * <p>The {@code VectorCollection} stores documents with:
 * <ul>
 *   <li>String keys (item IDs)</li>
 *   <li>String values (JSON-serialized metadata)</li>
 *   <li>Float vector embeddings (indexed by HNSW)</li>
 * </ul>
 *
 * <p>HNSW parameters are configured via {@link VectorStoreProperties}:
 * <ul>
 *   <li>{@code maxConnections} — max edges per node in the HNSW graph (default: 16)</li>
 *   <li>{@code efConstruction} — beam width during index construction (default: 200)</li>
 *   <li>{@code metric} — distance metric: COSINE, DOT, or EUCLIDEAN (default: COSINE)</li>
 *   <li>{@code indexName} — HNSW index name (default: "default")</li>
 * </ul>
 *
 * @author Generated by Claude Code
 * @since 2.0
 * @see VectorStoreService
 * @see NoOpVectorStoreService
 */
public class HazelcastVectorStoreService implements VectorStoreService {

    private static final Logger logger = LoggerFactory.getLogger(HazelcastVectorStoreService.class);

    private final VectorCollection<String, String> collection;
    private final String indexName;

    /**
     * Creates a new HazelcastVectorStoreService.
     *
     * <p>Configures a {@link VectorCollectionConfig} with an HNSW index based on the
     * provided properties and registers it with the Hazelcast instance. Then obtains
     * a reference to the {@link VectorCollection}.
     *
     * @param hazelcast the Hazelcast Enterprise instance
     * @param properties the vector store configuration properties
     */
    public HazelcastVectorStoreService(final HazelcastInstance hazelcast,
                                       final VectorStoreProperties properties) {
        this.indexName = properties.getIndexName();

        final Metric metric = Metric.valueOf(properties.getMetric().toUpperCase());

        final VectorIndexConfig indexConfig = new VectorIndexConfig()
                .setName(indexName)
                .setDimension(properties.getDimension())
                .setMetric(metric)
                .setMaxDegree(properties.getMaxConnections())
                .setEfConstruction(properties.getEfConstruction());

        final VectorCollectionConfig collectionConfig =
                new VectorCollectionConfig(properties.getCollectionName())
                        .addVectorIndexConfig(indexConfig);

        final Config config = hazelcast.getConfig();
        config.addVectorCollectionConfig(collectionConfig);

        this.collection = VectorCollection.getCollection(hazelcast, properties.getCollectionName());

        logger.info("HazelcastVectorStoreService initialized with collection '{}', " +
                        "dimension={}, metric={}, maxDegree={}, efConstruction={}, indexName='{}'",
                properties.getCollectionName(), properties.getDimension(),
                metric, properties.getMaxConnections(), properties.getEfConstruction(), indexName);
    }

    @Override
    public void storeEmbedding(final String id, final float[] embedding,
                               final Map<String, Object> metadata) {
        final String jsonMetadata = metadataToJson(metadata);
        final VectorDocument<String> document = VectorDocument.of(
                jsonMetadata,
                VectorValues.of(indexName, embedding)
        );
        collection.putAsync(id, document).toCompletableFuture().join();
        logger.debug("Stored embedding for id={} (dimension={})", id, embedding.length);
    }

    @Override
    public List<SimilarityResult> findSimilar(final float[] queryVector, final int limit) {
        final SearchResults<String, String> searchResults = collection.searchAsync(
                VectorValues.of(indexName, queryVector),
                SearchOptions.builder()
                        .limit(limit)
                        .includeValue()
                        .build()
        ).toCompletableFuture().join();

        final List<SimilarityResult> results = new ArrayList<>();
        for (final SearchResult<String, String> hit : searchResults) {
            final Map<String, Object> metadata = jsonToMetadata(hit.getValue());
            results.add(new SimilarityResult(hit.getKey(), hit.getScore(), metadata));
        }

        return results;
    }

    @Override
    public List<SimilarityResult> findSimilarById(final String id, final int limit) {
        final VectorDocument<String> document = collection.getAsync(id)
                .toCompletableFuture().join();

        if (document == null) {
            logger.debug("No embedding found for id={}", id);
            return List.of();
        }

        // Retrieve the stored vector and search for similar items
        final VectorDocument<String> docWithVectors = collection.getAsync(id)
                .toCompletableFuture().join();

        // We need the vector to search, so get it from the document's vectors
        // Search for limit+1 to account for excluding the query item itself
        // Since we may not have direct access to the vector from getAsync,
        // we perform a self-search to find neighbors
        final SearchResults<String, String> searchResults = collection.searchAsync(
                VectorValues.of(indexName, getVectorForId(id)),
                SearchOptions.builder()
                        .limit(limit + 1)
                        .includeValue()
                        .build()
        ).toCompletableFuture().join();

        final List<SimilarityResult> results = new ArrayList<>();
        for (final SearchResult<String, String> hit : searchResults) {
            if (!hit.getKey().equals(id)) {
                final Map<String, Object> metadata = jsonToMetadata(hit.getValue());
                results.add(new SimilarityResult(hit.getKey(), hit.getScore(), metadata));
            }
            if (results.size() >= limit) {
                break;
            }
        }

        return results;
    }

    @Override
    public boolean isAvailable() {
        return true;
    }

    @Override
    public String getImplementationType() {
        return "Hazelcast VectorCollection (Enterprise)";
    }

    /**
     * Retrieves the stored vector for the given ID by performing a search that includes vectors.
     *
     * <p>This is needed for {@link #findSimilarById(String, int)} because the standard
     * {@code getAsync} may not include vector data without explicit configuration.
     *
     * @param id the document ID
     * @return the stored embedding vector
     * @throws IllegalStateException if no vector is found for the given ID
     */
    private float[] getVectorForId(final String id) {
        final VectorDocument<String> document = collection.getAsync(id)
                .toCompletableFuture().join();

        if (document == null) {
            throw new IllegalStateException("No document found for id=" + id);
        }

        final VectorValues vectors = document.getVectors();
        if (vectors instanceof VectorValues.SingleVectorValues single) {
            return single.vector();
        }

        throw new IllegalStateException("Unable to retrieve vector for id=" + id);
    }

    /**
     * Converts metadata map to a simple JSON string for storage as the document value.
     *
     * @param metadata the metadata map (may be null)
     * @return JSON string representation
     */
    private String metadataToJson(final Map<String, Object> metadata) {
        if (metadata == null || metadata.isEmpty()) {
            return "{}";
        }

        final StringBuilder sb = new StringBuilder("{");
        boolean first = true;
        for (final Map.Entry<String, Object> entry : metadata.entrySet()) {
            if (!first) {
                sb.append(",");
            }
            sb.append("\"").append(escapeJson(entry.getKey())).append("\":");
            final Object value = entry.getValue();
            if (value instanceof String) {
                sb.append("\"").append(escapeJson((String) value)).append("\"");
            } else if (value instanceof Number) {
                sb.append(value);
            } else if (value == null) {
                sb.append("null");
            } else {
                sb.append("\"").append(escapeJson(value.toString())).append("\"");
            }
            first = false;
        }
        sb.append("}");
        return sb.toString();
    }

    /**
     * Parses a simple JSON string back into a metadata map.
     *
     * @param json the JSON string (may be null)
     * @return metadata map, or empty map if input is null/empty
     */
    @SuppressWarnings("unchecked")
    private Map<String, Object> jsonToMetadata(final String json) {
        if (json == null || json.isBlank() || "{}".equals(json)) {
            return Map.of();
        }

        // Simple JSON parser for flat key-value pairs
        final java.util.HashMap<String, Object> result = new java.util.HashMap<>();
        final String content = json.substring(1, json.length() - 1); // Strip outer braces
        if (content.isBlank()) {
            return Map.of();
        }

        int i = 0;
        while (i < content.length()) {
            // Skip whitespace and commas
            while (i < content.length() && (content.charAt(i) == ',' || content.charAt(i) == ' ')) {
                i++;
            }
            if (i >= content.length()) {
                break;
            }

            // Parse key
            if (content.charAt(i) != '"') {
                break;
            }
            i++; // Skip opening quote
            final int keyEnd = content.indexOf('"', i);
            if (keyEnd < 0) {
                break;
            }
            final String key = content.substring(i, keyEnd);
            i = keyEnd + 1;

            // Skip colon and whitespace
            while (i < content.length() && (content.charAt(i) == ':' || content.charAt(i) == ' ')) {
                i++;
            }

            // Parse value
            if (i >= content.length()) {
                break;
            }

            if (content.charAt(i) == '"') {
                // String value
                i++; // Skip opening quote
                final StringBuilder val = new StringBuilder();
                while (i < content.length() && content.charAt(i) != '"') {
                    if (content.charAt(i) == '\\' && i + 1 < content.length()) {
                        i++;
                        val.append(content.charAt(i));
                    } else {
                        val.append(content.charAt(i));
                    }
                    i++;
                }
                if (i < content.length()) {
                    i++; // Skip closing quote
                }
                result.put(key, val.toString());
            } else if (content.startsWith("null", i)) {
                result.put(key, null);
                i += 4;
            } else {
                // Number value
                final int valStart = i;
                while (i < content.length() && content.charAt(i) != ',' && content.charAt(i) != '}') {
                    i++;
                }
                final String numStr = content.substring(valStart, i).trim();
                try {
                    if (numStr.contains(".")) {
                        result.put(key, Double.parseDouble(numStr));
                    } else {
                        result.put(key, Long.parseLong(numStr));
                    }
                } catch (NumberFormatException e) {
                    result.put(key, numStr);
                }
            }
        }

        return result;
    }

    /**
     * Escapes special characters in a JSON string value.
     *
     * @param s the string to escape
     * @return escaped string
     */
    private String escapeJson(final String s) {
        return s.replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("\n", "\\n")
                .replace("\r", "\\r")
                .replace("\t", "\\t");
    }
}
