package com.theyawns.ecommerce.inventory.exception;

import com.theyawns.framework.resilience.NonRetryableException;

/**
 * Exception thrown when there is insufficient stock to fulfill a reservation.
 *
 * <p>Implements {@link NonRetryableException} because insufficient stock is a
 * deterministic business failure that will not resolve on retry.
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
public class InsufficientStockException extends RuntimeException implements NonRetryableException {

    private static final long serialVersionUID = 1L;

    private final String productId;
    private final int requestedQuantity;
    private final int availableQuantity;

    /**
     * Creates a new InsufficientStockException.
     *
     * @param productId the product ID
     * @param requestedQuantity the quantity requested
     * @param availableQuantity the quantity available
     */
    public InsufficientStockException(String productId, int requestedQuantity, int availableQuantity) {
        super(String.format("Insufficient stock for product %s: requested %d, available %d",
                productId, requestedQuantity, availableQuantity));
        this.productId = productId;
        this.requestedQuantity = requestedQuantity;
        this.availableQuantity = availableQuantity;
    }

    /**
     * Returns the product ID.
     *
     * @return the product ID
     */
    public String getProductId() {
        return productId;
    }

    /**
     * Returns the requested quantity.
     *
     * @return the requested quantity
     */
    public int getRequestedQuantity() {
        return requestedQuantity;
    }

    /**
     * Returns the available quantity.
     *
     * @return the available quantity
     */
    public int getAvailableQuantity() {
        return availableQuantity;
    }
}
