package com.theyawns.ecommerce.inventory.exception;

import com.theyawns.framework.resilience.NonRetryableException;

/**
 * Exception thrown when a product cannot be found.
 *
 * <p>Implements {@link NonRetryableException} because a missing product is a
 * deterministic business failure that will not resolve on retry.
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
public class ProductNotFoundException extends RuntimeException implements NonRetryableException {

    private static final long serialVersionUID = 1L;

    private final String productId;

    /**
     * Creates a new ProductNotFoundException.
     *
     * @param productId the ID of the product that was not found
     */
    public ProductNotFoundException(String productId) {
        super("Product not found: " + productId);
        this.productId = productId;
    }

    /**
     * Returns the product ID that was not found.
     *
     * @return the product ID
     */
    public String getProductId() {
        return productId;
    }
}
