package com.theyawns.framework.vectorstore;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Tests for {@link NoOpVectorStoreService}.
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
@DisplayName("NoOpVectorStoreService - Community Edition fallback")
class NoOpVectorStoreServiceTest {

    private NoOpVectorStoreService service;

    @BeforeEach
    void setUp() {
        service = new NoOpVectorStoreService();
    }

    @Test
    @DisplayName("should report as unavailable")
    void shouldReportUnavailable() {
        assertThat(service.isAvailable()).isFalse();
    }

    @Test
    @DisplayName("should report Community Edition implementation type")
    void shouldReportCommunityImplementationType() {
        assertThat(service.getImplementationType()).contains("Community");
    }

    @Test
    @DisplayName("storeEmbedding should be a no-op (not throw)")
    void storeEmbeddingShouldBeNoOp() {
        // Should not throw
        service.storeEmbedding("id-1", new float[]{1.0f, 0.0f}, Map.of("name", "test"));
        service.storeEmbedding("id-2", new float[]{0.0f, 1.0f}, null);
    }

    @Test
    @DisplayName("findSimilar should return empty list")
    void findSimilarShouldReturnEmpty() {
        List<SimilarityResult> results = service.findSimilar(new float[]{1.0f, 0.0f}, 10);
        assertThat(results).isEmpty();
    }

    @Test
    @DisplayName("findSimilarById should return empty list")
    void findSimilarByIdShouldReturnEmpty() {
        List<SimilarityResult> results = service.findSimilarById("any-id", 10);
        assertThat(results).isEmpty();
    }
}
