package com.theyawns.framework.persistence;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for {@link InMemoryViewStorePersistence}.
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
@DisplayName("InMemoryViewStorePersistence - In-memory view store for testing")
class InMemoryViewStorePersistenceTest {

    private InMemoryViewStorePersistence persistence;

    @BeforeEach
    void setUp() {
        persistence = new InMemoryViewStorePersistence();
    }

    @Test
    @DisplayName("should persist and load a single view entry")
    void shouldPersistAndLoadSingleView() {
        // Arrange
        PersistableView view = new PersistableView("cust-001", "{\"name\":\"John\"}", 1700000000000L);

        // Act
        persistence.persist("Customer_VIEW", view);
        Optional<PersistableView> loaded = persistence.loadView("Customer_VIEW", "cust-001");

        // Assert
        assertTrue(loaded.isPresent());
        assertEquals(view, loaded.get());
    }

    @Test
    @DisplayName("should upsert — second write replaces first")
    void shouldUpsertOnSecondWrite() {
        // Arrange
        PersistableView v1 = new PersistableView("cust-001", "{\"name\":\"John\"}", 100L);
        PersistableView v2 = new PersistableView("cust-001", "{\"name\":\"Jane\"}", 200L);

        // Act
        persistence.persist("Customer_VIEW", v1);
        persistence.persist("Customer_VIEW", v2);
        Optional<PersistableView> loaded = persistence.loadView("Customer_VIEW", "cust-001");

        // Assert
        assertTrue(loaded.isPresent());
        assertEquals("{\"name\":\"Jane\"}", loaded.get().viewData());
        assertEquals(200L, loaded.get().lastUpdatedMillis());
    }

    @Test
    @DisplayName("should persist batch with upsert semantics")
    void shouldPersistBatchWithUpsert() {
        // Arrange — pre-populate one entry
        persistence.persist("Batch_VIEW", new PersistableView("k1", "{\"v\":\"old\"}", 100L));

        List<PersistableView> batch = List.of(
                new PersistableView("k1", "{\"v\":\"new\"}", 200L),
                new PersistableView("k2", "{\"v\":\"fresh\"}", 200L)
        );

        // Act
        persistence.persistBatch("Batch_VIEW", batch);

        // Assert
        assertEquals("{\"v\":\"new\"}", persistence.loadView("Batch_VIEW", "k1").get().viewData());
        assertTrue(persistence.loadView("Batch_VIEW", "k2").isPresent());
    }

    @Test
    @DisplayName("should return empty when view not found")
    void shouldReturnEmptyWhenNotFound() {
        // Act
        Optional<PersistableView> result = persistence.loadView("NoSuchView", "no-key");

        // Assert
        assertFalse(result.isPresent());
    }

    @Test
    @DisplayName("should delete a single view entry")
    void shouldDeleteSingleEntry() {
        // Arrange
        persistence.persist("Del_VIEW", new PersistableView("k1", "{}", 100L));

        // Act
        persistence.delete("Del_VIEW", "k1");

        // Assert
        assertFalse(persistence.loadView("Del_VIEW", "k1").isPresent());
    }

    @Test
    @DisplayName("should delete all entries for a view name")
    void shouldDeleteAllForViewName() {
        // Arrange
        persistence.persist("Clear_VIEW", new PersistableView("k1", "{}", 100L));
        persistence.persist("Clear_VIEW", new PersistableView("k2", "{}", 200L));
        persistence.persist("Other_VIEW", new PersistableView("k3", "{}", 300L));

        // Act
        persistence.deleteAll("Clear_VIEW");

        // Assert
        assertFalse(persistence.loadView("Clear_VIEW", "k1").isPresent());
        assertFalse(persistence.loadView("Clear_VIEW", "k2").isPresent());
        assertTrue(persistence.loadView("Other_VIEW", "k3").isPresent());
    }

    @Test
    @DisplayName("should isolate entries by view name")
    void shouldIsolateByViewName() {
        // Arrange
        persistence.persist("ViewA", new PersistableView("k1", "{\"src\":\"A\"}", 100L));
        persistence.persist("ViewB", new PersistableView("k1", "{\"src\":\"B\"}", 200L));

        // Assert
        assertEquals("{\"src\":\"A\"}", persistence.loadView("ViewA", "k1").get().viewData());
        assertEquals("{\"src\":\"B\"}", persistence.loadView("ViewB", "k1").get().viewData());
    }

    @Test
    @DisplayName("should load all keys for a view name")
    void shouldLoadAllKeys() {
        // Arrange
        persistence.persist("Keys_VIEW", new PersistableView("k1", "{}", 100L));
        persistence.persist("Keys_VIEW", new PersistableView("k2", "{}", 200L));
        persistence.persist("Keys_VIEW", new PersistableView("k3", "{}", 300L));

        // Act
        List<String> keys = new ArrayList<>();
        persistence.loadAllKeys("Keys_VIEW").forEach(keys::add);

        // Assert
        assertEquals(3, keys.size());
        assertTrue(keys.contains("k1"));
        assertTrue(keys.contains("k2"));
        assertTrue(keys.contains("k3"));
    }

    @Test
    @DisplayName("should always report available")
    void shouldAlwaysBeAvailable() {
        assertTrue(persistence.isAvailable());
    }
}
