package com.theyawns.framework.persistence;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Tests for {@link InMemoryDlqStorePersistence}.
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
@DisplayName("InMemoryDlqStorePersistence")
class InMemoryDlqStorePersistenceTest {

    private InMemoryDlqStorePersistence persistence;

    @BeforeEach
    void setUp() {
        persistence = new InMemoryDlqStorePersistence();
    }

    private PersistableDeadLetterEntry createEntry(final String id, final String status) {
        return new PersistableDeadLetterEntry(
                id, "evt-" + id, "TestCreated", "TestTopic",
                "{\"eventId\":\"evt-" + id + "\"}", "Test failure",
                System.currentTimeMillis(), "test-service", "saga-1", "corr-1",
                0, status
        );
    }

    @Nested
    @DisplayName("Persist and load")
    class PersistAndLoad {

        @Test
        @DisplayName("should persist and load entry by ID")
        void shouldPersistAndLoad() {
            PersistableDeadLetterEntry entry = createEntry("dlq-001", "PENDING");
            persistence.persist(entry);

            Optional<PersistableDeadLetterEntry> loaded = persistence.load("dlq-001");

            assertThat(loaded).isPresent();
            assertThat(loaded.get().dlqEntryId()).isEqualTo("dlq-001");
            assertThat(loaded.get().originalEventId()).isEqualTo("evt-dlq-001");
            assertThat(loaded.get().status()).isEqualTo("PENDING");
        }

        @Test
        @DisplayName("should return empty for non-existent entry")
        void shouldReturnEmptyForNonExistent() {
            Optional<PersistableDeadLetterEntry> loaded = persistence.load("non-existent");
            assertThat(loaded).isEmpty();
        }

        @Test
        @DisplayName("should overwrite entry on upsert")
        void shouldOverwriteOnUpsert() {
            persistence.persist(createEntry("dlq-002", "PENDING"));
            persistence.persist(createEntry("dlq-002", "REPLAYED"));

            Optional<PersistableDeadLetterEntry> loaded = persistence.load("dlq-002");
            assertThat(loaded).isPresent();
            assertThat(loaded.get().status()).isEqualTo("REPLAYED");
        }
    }

    @Nested
    @DisplayName("Batch persist")
    class BatchPersist {

        @Test
        @DisplayName("should persist batch of entries")
        void shouldPersistBatch() {
            List<PersistableDeadLetterEntry> entries = List.of(
                    createEntry("dlq-b1", "PENDING"),
                    createEntry("dlq-b2", "PENDING"),
                    createEntry("dlq-b3", "DISCARDED")
            );
            persistence.persistBatch(entries);

            assertThat(persistence.load("dlq-b1")).isPresent();
            assertThat(persistence.load("dlq-b2")).isPresent();
            assertThat(persistence.load("dlq-b3")).isPresent();
        }
    }

    @Nested
    @DisplayName("Load pending keys")
    class LoadPendingKeys {

        @Test
        @DisplayName("should return only PENDING entry IDs")
        void shouldReturnOnlyPendingKeys() {
            persistence.persist(createEntry("dlq-p1", "PENDING"));
            persistence.persist(createEntry("dlq-p2", "REPLAYED"));
            persistence.persist(createEntry("dlq-p3", "PENDING"));
            persistence.persist(createEntry("dlq-p4", "DISCARDED"));

            List<String> keys = new ArrayList<>();
            persistence.loadPendingKeys().forEach(keys::add);

            assertThat(keys).containsExactlyInAnyOrder("dlq-p1", "dlq-p3");
        }

        @Test
        @DisplayName("should return empty when no pending entries")
        void shouldReturnEmptyWhenNoPending() {
            persistence.persist(createEntry("dlq-np1", "REPLAYED"));
            persistence.persist(createEntry("dlq-np2", "DISCARDED"));

            List<String> keys = new ArrayList<>();
            persistence.loadPendingKeys().forEach(keys::add);

            assertThat(keys).isEmpty();
        }
    }

    @Nested
    @DisplayName("Delete")
    class Delete {

        @Test
        @DisplayName("should delete entry")
        void shouldDeleteEntry() {
            persistence.persist(createEntry("dlq-del", "PENDING"));
            persistence.delete("dlq-del");

            assertThat(persistence.load("dlq-del")).isEmpty();
        }

        @Test
        @DisplayName("should not throw when deleting non-existent entry")
        void shouldNotThrowWhenDeletingNonExistent() {
            persistence.delete("non-existent");
            // No exception expected
        }
    }

    @Nested
    @DisplayName("Availability")
    class Availability {

        @Test
        @DisplayName("should always be available")
        void shouldAlwaysBeAvailable() {
            assertThat(persistence.isAvailable()).isTrue();
        }
    }
}
