package com.theyawns.framework.persistence;

import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.Timer;
import io.micrometer.core.instrument.simple.SimpleMeterRegistry;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.time.Instant;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for {@link PersistenceMetrics}.
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
@DisplayName("PersistenceMetrics - Micrometer instrumentation for persistence layer")
class PersistenceMetricsTest {

    private SimpleMeterRegistry registry;
    private PersistenceMetrics metrics;

    @BeforeEach
    void setUp() {
        registry = new SimpleMeterRegistry();
        metrics = new PersistenceMetrics(registry);
    }

    @Test
    @DisplayName("should reject null meter registry")
    void shouldRejectNullRegistry() {
        assertThrows(NullPointerException.class, () -> new PersistenceMetrics(null));
    }

    @Test
    @DisplayName("should record store count")
    void shouldRecordStoreCount() {
        // Act
        metrics.recordStore("Customer_ES", "event", Instant.now());
        metrics.recordStore("Customer_ES", "event", Instant.now());

        // Assert
        Counter counter = registry.find("persistence.store.count")
                .tag("mapName", "Customer_ES")
                .tag("storeType", "event")
                .counter();
        assertNotNull(counter);
        assertEquals(2.0, counter.count());
    }

    @Test
    @DisplayName("should record store duration")
    void shouldRecordStoreDuration() {
        // Act
        metrics.recordStore("Product_VIEW", "view", Instant.now().minusMillis(50));

        // Assert
        Timer timer = registry.find("persistence.store.duration")
                .tag("mapName", "Product_VIEW")
                .tag("storeType", "view")
                .timer();
        assertNotNull(timer);
        assertEquals(1, timer.count());
        assertTrue(timer.totalTime(java.util.concurrent.TimeUnit.MILLISECONDS) > 0);
    }

    @Test
    @DisplayName("should record batch store count and entry total")
    void shouldRecordBatchStore() {
        // Act
        metrics.recordBatchStore("Order_ES", "event", 25, Instant.now());

        // Assert
        Counter batchCounter = registry.find("persistence.store.batch.count")
                .tag("mapName", "Order_ES")
                .counter();
        assertNotNull(batchCounter);
        assertEquals(1.0, batchCounter.count());

        Counter entriesCounter = registry.find("persistence.store.batch.entries")
                .tag("mapName", "Order_ES")
                .counter();
        assertNotNull(entriesCounter);
        assertEquals(25.0, entriesCounter.count());
    }

    @Test
    @DisplayName("should accumulate batch entry counts")
    void shouldAccumulateBatchEntries() {
        // Act
        metrics.recordBatchStore("ES", "event", 10, Instant.now());
        metrics.recordBatchStore("ES", "event", 15, Instant.now());

        // Assert
        Counter entriesCounter = registry.find("persistence.store.batch.entries")
                .tag("mapName", "ES")
                .counter();
        assertNotNull(entriesCounter);
        assertEquals(25.0, entriesCounter.count());
    }

    @Test
    @DisplayName("should record batch store duration")
    void shouldRecordBatchDuration() {
        // Act
        metrics.recordBatchStore("ES", "event", 5, Instant.now().minusMillis(10));

        // Assert
        Timer timer = registry.find("persistence.store.batch.duration")
                .tag("mapName", "ES")
                .timer();
        assertNotNull(timer);
        assertEquals(1, timer.count());
    }

    @Test
    @DisplayName("should record load count and duration")
    void shouldRecordLoad() {
        // Act
        metrics.recordLoad("Customer_VIEW", Instant.now());

        // Assert
        Counter counter = registry.find("persistence.load.count")
                .tag("mapName", "Customer_VIEW")
                .counter();
        assertNotNull(counter);
        assertEquals(1.0, counter.count());

        Timer timer = registry.find("persistence.load.duration")
                .tag("mapName", "Customer_VIEW")
                .timer();
        assertNotNull(timer);
        assertEquals(1, timer.count());
    }

    @Test
    @DisplayName("should record load miss")
    void shouldRecordLoadMiss() {
        // Act
        metrics.recordLoadMiss("Order_VIEW");
        metrics.recordLoadMiss("Order_VIEW");

        // Assert
        Counter counter = registry.find("persistence.load.miss")
                .tag("mapName", "Order_VIEW")
                .counter();
        assertNotNull(counter);
        assertEquals(2.0, counter.count());
    }

    @Test
    @DisplayName("should record delete count")
    void shouldRecordDelete() {
        // Act
        metrics.recordDelete("Payment_ES");

        // Assert
        Counter counter = registry.find("persistence.delete.count")
                .tag("mapName", "Payment_ES")
                .counter();
        assertNotNull(counter);
        assertEquals(1.0, counter.count());
    }

    @Test
    @DisplayName("should record error with operation tag")
    void shouldRecordError() {
        // Act
        metrics.recordError("Customer_ES", "store");
        metrics.recordError("Customer_ES", "load");

        // Assert
        Counter storeError = registry.find("persistence.errors")
                .tag("mapName", "Customer_ES")
                .tag("operation", "store")
                .counter();
        assertNotNull(storeError);
        assertEquals(1.0, storeError.count());

        Counter loadError = registry.find("persistence.errors")
                .tag("operation", "load")
                .counter();
        assertNotNull(loadError);
        assertEquals(1.0, loadError.count());
    }

    @Test
    @DisplayName("should handle null mapName gracefully")
    void shouldHandleNullMapName() {
        // Act — should not throw
        metrics.recordStore(null, "event", Instant.now());
        metrics.recordLoad(null, Instant.now());
        metrics.recordDelete(null);

        // Assert
        Counter counter = registry.find("persistence.store.count")
                .tag("mapName", "unknown")
                .counter();
        assertNotNull(counter);
        assertEquals(1.0, counter.count());
    }
}
