package com.theyawns.framework.persistence.postgres.archival;

import com.theyawns.framework.persistence.PersistenceProperties;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.transaction.annotation.Transactional;

import java.time.Instant;
import java.time.temporal.ChronoUnit;

/**
 * Scheduled service that archives old events from {@code domain_events} to
 * {@code domain_events_archive}, then deletes the archived rows from the
 * main table.
 *
 * <p>This keeps the active event table bounded for long-running deployments
 * (production, trade shows). The archive table preserves full event history
 * for audit or replay if needed.
 *
 * <p>Only active when {@code framework.persistence.archival.enabled=true}.
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
public class EventArchivalService {

    private static final Logger logger = LoggerFactory.getLogger(EventArchivalService.class);

    private final JdbcTemplate jdbcTemplate;
    private final PersistenceProperties.ArchivalConfig config;

    /**
     * Creates a new EventArchivalService.
     *
     * @param jdbcTemplate the JDBC template for database operations
     * @param config the archival configuration
     */
    public EventArchivalService(final JdbcTemplate jdbcTemplate,
                                 final PersistenceProperties.ArchivalConfig config) {
        this.jdbcTemplate = jdbcTemplate;
        this.config = config;
        logger.info("EventArchivalService initialized: retentionHours={}, batchSize={}",
                config.getRetentionHours(), config.getBatchSize());
    }

    /**
     * Runs the archival process. Moves events older than the retention period
     * to the archive table in batches, then deletes them from the main table.
     *
     * <p>Scheduled via {@code framework.persistence.archival.run-interval-ms}.
     */
    @Scheduled(fixedDelayString = "${framework.persistence.archival.run-interval-ms:3600000}")
    @Transactional
    public void archiveOldEvents() {
        final Instant cutoff = Instant.now().minus(config.getRetentionHours(), ChronoUnit.HOURS);
        final long cutoffMillis = cutoff.toEpochMilli();

        logger.info("Starting event archival: cutoff={}, batchSize={}", cutoff, config.getBatchSize());

        // Step 1: Copy old, non-archived events to archive table
        int copied = jdbcTemplate.update(
                "INSERT INTO domain_events_archive " +
                "SELECT * FROM domain_events " +
                "WHERE archived = FALSE AND created_at < ? " +
                "ORDER BY created_at ASC " +
                "LIMIT ?",
                java.sql.Timestamp.from(cutoff),
                config.getBatchSize()
        );

        if (copied == 0) {
            logger.info("No events to archive (cutoff={})", cutoff);
            return;
        }

        // Step 2: Mark as archived in main table (matches the same rows we just copied)
        int marked = jdbcTemplate.update(
                "UPDATE domain_events SET archived = TRUE " +
                "WHERE archived = FALSE AND created_at < ? " +
                "AND ctid IN (" +
                "  SELECT ctid FROM domain_events " +
                "  WHERE archived = FALSE AND created_at < ? " +
                "  ORDER BY created_at ASC LIMIT ?" +
                ")",
                java.sql.Timestamp.from(cutoff),
                java.sql.Timestamp.from(cutoff),
                config.getBatchSize()
        );

        // Step 3: Delete archived rows from main table
        int deleted = jdbcTemplate.update(
                "DELETE FROM domain_events WHERE archived = TRUE"
        );

        logger.info("Event archival complete: copied={}, deleted={}", copied, deleted);
    }
}
