package com.theyawns.ecommerce.common.domain;

import com.hazelcast.nio.serialization.genericrecord.GenericRecord;
import com.hazelcast.nio.serialization.genericrecord.GenericRecordBuilder;
import com.theyawns.framework.domain.DomainObject;
import com.theyawns.ecommerce.common.dto.CustomerDTO;

import java.time.Instant;
import java.util.Objects;

/**
 * Customer domain object representing a customer account.
 *
 * <p>State is derived from applying customer events:
 * <ul>
 *   <li>CustomerCreatedEvent - creates a new customer</li>
 *   <li>CustomerUpdatedEvent - updates customer details</li>
 *   <li>CustomerStatusChangedEvent - activates, suspends, or closes account</li>
 * </ul>
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
public class Customer implements DomainObject<String> {

    private static final long serialVersionUID = 1L;
    public static final String SCHEMA_NAME = "Customer";

    /**
     * Customer status enumeration.
     */
    public enum Status {
        ACTIVE,
        SUSPENDED,
        CLOSED
    }

    private String customerId;
    private String email;
    private String name;
    private String address;
    private String phone;
    private Status status;
    private Instant createdAt;
    private Instant updatedAt;

    /**
     * Default constructor.
     */
    public Customer() {
    }

    /**
     * Constructor for new customer creation.
     *
     * @param customerId the unique customer ID
     * @param email the customer email
     * @param name the customer name
     * @param address the customer address
     */
    public Customer(String customerId, String email, String name, String address) {
        this.customerId = customerId;
        this.email = email;
        this.name = name;
        this.address = address;
        this.status = Status.ACTIVE;
        this.createdAt = Instant.now();
        this.updatedAt = this.createdAt;
    }

    /**
     * Creates a Customer from a GenericRecord.
     *
     * @param record the GenericRecord to hydrate from
     * @return the hydrated Customer
     */
    public static Customer fromGenericRecord(GenericRecord record) {
        if (record == null) {
            return null;
        }
        Customer customer = new Customer();
        customer.customerId = record.getString("customerId");
        customer.email = record.getString("email");
        customer.name = record.getString("name");
        customer.address = record.getString("address");
        customer.phone = record.getString("phone");

        String statusStr = record.getString("status");
        customer.status = statusStr != null ? Status.valueOf(statusStr) : Status.ACTIVE;

        Long createdAtMs = record.getInt64("createdAt");
        customer.createdAt = createdAtMs != null ? Instant.ofEpochMilli(createdAtMs) : null;

        Long updatedAtMs = record.getInt64("updatedAt");
        customer.updatedAt = updatedAtMs != null ? Instant.ofEpochMilli(updatedAtMs) : null;

        return customer;
    }

    @Override
    public String getKey() {
        return customerId;
    }

    @Override
    public GenericRecord toGenericRecord() {
        return GenericRecordBuilder.compact(SCHEMA_NAME)
                .setString("customerId", customerId)
                .setString("email", email)
                .setString("name", name)
                .setString("address", address)
                .setString("phone", phone)
                .setString("status", status != null ? status.name() : null)
                .setInt64("createdAt", createdAt != null ? createdAt.toEpochMilli() : 0)
                .setInt64("updatedAt", updatedAt != null ? updatedAt.toEpochMilli() : 0)
                .build();
    }

    @Override
    public String getSchemaName() {
        return SCHEMA_NAME;
    }

    /**
     * Converts this Customer to a DTO.
     *
     * @return the CustomerDTO
     */
    public CustomerDTO toDTO() {
        return new CustomerDTO(
                customerId,
                email,
                name,
                address,
                phone,
                status != null ? status.name() : null
        );
    }

    // Getters and Setters

    public String getCustomerId() {
        return customerId;
    }

    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Instant updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Customer customer = (Customer) o;
        return Objects.equals(customerId, customer.customerId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(customerId);
    }

    @Override
    public String toString() {
        return "Customer{" +
                "customerId='" + customerId + '\'' +
                ", email='" + email + '\'' +
                ", name='" + name + '\'' +
                ", status=" + status +
                '}';
    }
}
