package com.theyawns.ecommerce.common.domain;

import com.hazelcast.nio.serialization.genericrecord.GenericRecord;
import com.hazelcast.nio.serialization.genericrecord.GenericRecordBuilder;
import com.theyawns.ecommerce.common.dto.OrderLineItemDTO;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Objects;

/**
 * Represents a single line item within an order.
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
public class OrderLineItem implements Serializable {

    private static final long serialVersionUID = 1L;
    public static final String SCHEMA_NAME = "OrderLineItem";

    private String productId;
    private String productName;
    private String sku;
    private int quantity;
    private BigDecimal unitPrice;
    private BigDecimal lineTotal;

    /**
     * Default constructor.
     */
    public OrderLineItem() {
    }

    /**
     * Constructor with required fields.
     *
     * @param productId the product ID
     * @param productName the product name
     * @param sku the product SKU
     * @param quantity the quantity ordered
     * @param unitPrice the price per unit (must not be null)
     * @throws IllegalArgumentException if unitPrice is null
     */
    public OrderLineItem(String productId, String productName, String sku,
                         int quantity, BigDecimal unitPrice) {
        if (unitPrice == null) {
            throw new IllegalArgumentException(
                    "unitPrice cannot be null for product: " + productId +
                    ". Ensure product has a price set or provide price in order request.");
        }
        this.productId = productId;
        this.productName = productName;
        this.sku = sku;
        this.quantity = quantity;
        this.unitPrice = unitPrice;
        this.lineTotal = unitPrice.multiply(BigDecimal.valueOf(quantity));
    }

    /**
     * Creates an OrderLineItem from a GenericRecord.
     *
     * @param record the GenericRecord to hydrate from
     * @return the hydrated OrderLineItem
     */
    public static OrderLineItem fromGenericRecord(GenericRecord record) {
        if (record == null) {
            return null;
        }
        OrderLineItem item = new OrderLineItem();
        item.productId = record.getString("productId");
        item.productName = record.getString("productName");
        item.sku = record.getString("sku");
        item.quantity = record.getInt32("quantity");

        String unitPriceStr = record.getString("unitPrice");
        item.unitPrice = unitPriceStr != null ? new BigDecimal(unitPriceStr) : null;

        String lineTotalStr = record.getString("lineTotal");
        item.lineTotal = lineTotalStr != null ? new BigDecimal(lineTotalStr) : null;

        return item;
    }

    /**
     * Serializes this line item to a GenericRecord.
     *
     * @return GenericRecord representation
     */
    public GenericRecord toGenericRecord() {
        return GenericRecordBuilder.compact(SCHEMA_NAME)
                .setString("productId", productId)
                .setString("productName", productName)
                .setString("sku", sku)
                .setInt32("quantity", quantity)
                .setString("unitPrice", unitPrice != null ? unitPrice.toString() : null)
                .setString("lineTotal", lineTotal != null ? lineTotal.toString() : null)
                .build();
    }

    /**
     * Converts this line item to a DTO.
     *
     * @return the OrderLineItemDTO
     */
    public OrderLineItemDTO toDTO() {
        return new OrderLineItemDTO(productId, productName, sku, quantity, unitPrice);
    }

    // Getters and Setters

    public String getProductId() {
        return productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public String getSku() {
        return sku;
    }

    public void setSku(String sku) {
        this.sku = sku;
    }

    public int getQuantity() {
        return quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
        if (unitPrice != null) {
            this.lineTotal = unitPrice.multiply(BigDecimal.valueOf(quantity));
        }
    }

    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
        if (unitPrice != null) {
            this.lineTotal = unitPrice.multiply(BigDecimal.valueOf(quantity));
        }
    }

    public BigDecimal getLineTotal() {
        return lineTotal;
    }

    public void setLineTotal(BigDecimal lineTotal) {
        this.lineTotal = lineTotal;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        OrderLineItem that = (OrderLineItem) o;
        return Objects.equals(productId, that.productId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(productId);
    }

    @Override
    public String toString() {
        return "OrderLineItem{" +
                "productId='" + productId + '\'' +
                ", productName='" + productName + '\'' +
                ", quantity=" + quantity +
                ", unitPrice=" + unitPrice +
                ", lineTotal=" + lineTotal +
                '}';
    }
}
