package com.theyawns.ecommerce.common.domain;

import com.hazelcast.nio.serialization.genericrecord.GenericRecord;
import com.hazelcast.nio.serialization.genericrecord.GenericRecordBuilder;
import com.theyawns.framework.domain.DomainObject;
import com.theyawns.ecommerce.common.dto.ProductDTO;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.Objects;

/**
 * Product domain object representing an inventory item.
 *
 * <p>State is derived from applying product events:
 * <ul>
 *   <li>ProductCreatedEvent - creates a new product</li>
 *   <li>ProductUpdatedEvent - updates product details</li>
 *   <li>StockReceivedEvent - increases quantity on hand</li>
 *   <li>StockReservedEvent - reserves stock for an order</li>
 *   <li>StockReleasedEvent - releases reserved stock</li>
 *   <li>StockShippedEvent - decreases reserved and on-hand for shipment</li>
 * </ul>
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
public class Product implements DomainObject<String> {

    private static final long serialVersionUID = 1L;
    public static final String SCHEMA_NAME = "Product";

    /**
     * Product status enumeration.
     */
    public enum Status {
        ACTIVE,
        DISCONTINUED,
        OUT_OF_STOCK
    }

    private String productId;
    private String sku;
    private String name;
    private String description;
    private BigDecimal price;
    private int quantityOnHand;
    private int quantityReserved;
    private String category;
    private Status status;
    private Instant createdAt;
    private Instant updatedAt;

    /**
     * Default constructor.
     */
    public Product() {
    }

    /**
     * Constructor for new product creation.
     *
     * @param productId the unique product ID
     * @param sku the product SKU
     * @param name the product name
     * @param price the product price
     * @param quantityOnHand the initial quantity
     */
    public Product(String productId, String sku, String name, BigDecimal price, int quantityOnHand) {
        this.productId = productId;
        this.sku = sku;
        this.name = name;
        this.price = price;
        this.quantityOnHand = quantityOnHand;
        this.quantityReserved = 0;
        this.status = Status.ACTIVE;
        this.createdAt = Instant.now();
        this.updatedAt = this.createdAt;
    }

    /**
     * Creates a Product from a GenericRecord.
     *
     * @param record the GenericRecord to hydrate from
     * @return the hydrated Product
     */
    public static Product fromGenericRecord(GenericRecord record) {
        if (record == null) {
            return null;
        }
        Product product = new Product();
        product.productId = record.getString("productId");
        product.sku = record.getString("sku");
        product.name = record.getString("name");
        product.description = record.getString("description");

        String priceStr = record.getString("price");
        product.price = priceStr != null ? new BigDecimal(priceStr) : null;

        product.quantityOnHand = record.getInt32("quantityOnHand");
        product.quantityReserved = record.getInt32("quantityReserved");
        product.category = record.getString("category");

        String statusStr = record.getString("status");
        product.status = statusStr != null ? Status.valueOf(statusStr) : Status.ACTIVE;

        Long createdAtMs = record.getInt64("createdAt");
        product.createdAt = createdAtMs != null ? Instant.ofEpochMilli(createdAtMs) : null;

        Long updatedAtMs = record.getInt64("updatedAt");
        product.updatedAt = updatedAtMs != null ? Instant.ofEpochMilli(updatedAtMs) : null;

        return product;
    }

    @Override
    public String getKey() {
        return productId;
    }

    @Override
    public GenericRecord toGenericRecord() {
        return GenericRecordBuilder.compact(SCHEMA_NAME)
                .setString("productId", productId)
                .setString("sku", sku)
                .setString("name", name)
                .setString("description", description)
                .setString("price", price != null ? price.toString() : null)
                .setInt32("quantityOnHand", quantityOnHand)
                .setInt32("quantityReserved", quantityReserved)
                .setString("category", category)
                .setString("status", status != null ? status.name() : null)
                .setInt64("createdAt", createdAt != null ? createdAt.toEpochMilli() : 0)
                .setInt64("updatedAt", updatedAt != null ? updatedAt.toEpochMilli() : 0)
                .build();
    }

    @Override
    public String getSchemaName() {
        return SCHEMA_NAME;
    }

    /**
     * Returns the available quantity (on hand minus reserved).
     *
     * @return available quantity
     */
    public int getAvailableQuantity() {
        return quantityOnHand - quantityReserved;
    }

    /**
     * Checks if the requested quantity is available for reservation.
     *
     * @param quantity the quantity to check
     * @return true if available
     */
    public boolean canReserve(int quantity) {
        return getAvailableQuantity() >= quantity && status == Status.ACTIVE;
    }

    /**
     * Converts this Product to a DTO.
     *
     * @return the ProductDTO
     */
    public ProductDTO toDTO() {
        return new ProductDTO(
                productId,
                sku,
                name,
                description,
                price,
                quantityOnHand,
                quantityReserved,
                category,
                status != null ? status.name() : null
        );
    }

    // Getters and Setters

    public String getProductId() {
        return productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public String getSku() {
        return sku;
    }

    public void setSku(String sku) {
        this.sku = sku;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public int getQuantityOnHand() {
        return quantityOnHand;
    }

    public void setQuantityOnHand(int quantityOnHand) {
        this.quantityOnHand = quantityOnHand;
    }

    public int getQuantityReserved() {
        return quantityReserved;
    }

    public void setQuantityReserved(int quantityReserved) {
        this.quantityReserved = quantityReserved;
    }

    public String getCategory() {
        return category;
    }

    public void setCategory(String category) {
        this.category = category;
    }

    public Status getStatus() {
        return status;
    }

    public void setStatus(Status status) {
        this.status = status;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(Instant createdAt) {
        this.createdAt = createdAt;
    }

    public Instant getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Instant updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Product product = (Product) o;
        return Objects.equals(productId, product.productId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(productId);
    }

    @Override
    public String toString() {
        return "Product{" +
                "productId='" + productId + '\'' +
                ", sku='" + sku + '\'' +
                ", name='" + name + '\'' +
                ", price=" + price +
                ", available=" + getAvailableQuantity() +
                ", status=" + status +
                '}';
    }
}
