package com.theyawns.ecommerce.mcp.tools;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.theyawns.ecommerce.mcp.client.ServiceClientOperations;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.tool.annotation.Tool;
import org.springframework.stereotype.Service;

import java.util.Map;

/**
 * MCP tool for retrieving system metrics.
 *
 * <p>Allows AI assistants to query aggregated saga and event metrics
 * from the order service, providing visibility into system health
 * and throughput.
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
@Service
public class GetMetricsTool {

    private static final Logger logger = LoggerFactory.getLogger(GetMetricsTool.class);

    private final ServiceClientOperations serviceClient;
    private final ObjectMapper objectMapper;

    /**
     * Creates a new GetMetricsTool.
     *
     * @param serviceClient the REST client for service communication
     */
    public GetMetricsTool(ServiceClientOperations serviceClient) {
        this.serviceClient = serviceClient;
        this.objectMapper = new ObjectMapper().enable(SerializationFeature.INDENT_OUTPUT);
    }

    /**
     * Retrieves aggregated system metrics including saga counts and event throughput.
     *
     * @return JSON string with the metrics summary
     */
    @Tool(description = "Get system metrics including saga counts by status, "
            + "event throughput, and active saga gauges.")
    public String getMetrics() {

        logger.info("MCP getMetrics");

        try {
            Map<String, Object> metrics = serviceClient.getMetricsSummary();
            return toJson(metrics);
        } catch (Exception e) {
            logger.error("Failed to get metrics", e);
            return toJson(Map.of("error", "Failed to get metrics: " + e.getMessage()));
        }
    }

    private String toJson(Object value) {
        try {
            return objectMapper.writeValueAsString(value);
        } catch (JsonProcessingException e) {
            logger.error("Failed to serialize result", e);
            return "{\"error\": \"Failed to serialize result\"}";
        }
    }
}
