package com.theyawns.ecommerce.mcp.tools;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.theyawns.ecommerce.mcp.client.ServiceClientOperations;
import com.theyawns.ecommerce.mcp.security.ToolAuthorizer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.tool.annotation.Tool;
import org.springframework.ai.tool.annotation.ToolParam;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.Map;

/**
 * MCP tool for inspecting saga state by ID.
 *
 * <p>Allows AI assistants to retrieve detailed saga state including
 * step progress, timing, and failure information by delegating to
 * the order service's saga REST endpoint.
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
@Service
public class InspectSagaTool {

    private static final Logger logger = LoggerFactory.getLogger(InspectSagaTool.class);

    private final ServiceClientOperations serviceClient;
    private final ObjectMapper objectMapper;
    private ToolAuthorizer toolAuthorizer;

    /**
     * Creates a new InspectSagaTool.
     *
     * @param serviceClient the REST client for service communication
     */
    public InspectSagaTool(ServiceClientOperations serviceClient) {
        this.serviceClient = serviceClient;
        this.objectMapper = new ObjectMapper().enable(SerializationFeature.INDENT_OUTPUT);
    }

    /**
     * Sets the tool authorizer for role-based access control.
     *
     * @param toolAuthorizer the authorizer (injected only when security is enabled)
     */
    @Autowired(required = false)
    public void setToolAuthorizer(final ToolAuthorizer toolAuthorizer) {
        this.toolAuthorizer = toolAuthorizer;
    }

    /**
     * Inspects a saga by its ID, returning full state and step details.
     *
     * @param sagaId the saga identifier
     * @return JSON string with saga state details
     */
    @Tool(description = "Inspect a saga by its ID. Returns saga state including status, "
            + "step progress, timing, and failure details.")
    public String inspectSaga(
            @ToolParam(description = "The saga ID to inspect") String sagaId) {

        if (toolAuthorizer != null) {
            String denied = toolAuthorizer.checkAccess("inspectSaga");
            if (denied != null) {
                return denied;
            }
        }

        logger.info("MCP inspectSaga: sagaId={}", sagaId);

        try {
            Map<String, Object> result = serviceClient.getSaga(sagaId);
            return toJson(result);
        } catch (Exception e) {
            logger.error("Failed to inspect saga: {}", sagaId, e);
            return toJson(Map.of("error", "Failed to inspect saga: " + e.getMessage()));
        }
    }

    private String toJson(Object value) {
        try {
            return objectMapper.writeValueAsString(value);
        } catch (JsonProcessingException e) {
            logger.error("Failed to serialize result", e);
            return "{\"error\": \"Failed to serialize result\"}";
        }
    }
}
