package com.theyawns.ecommerce.mcp.tools;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.theyawns.ecommerce.mcp.client.ServiceClientOperations;
import com.theyawns.ecommerce.mcp.security.ToolAuthorizer;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.tool.annotation.Tool;
import org.springframework.ai.tool.annotation.ToolParam;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.Map;

/**
 * MCP tool for inspecting a single DLQ entry in detail.
 *
 * <p>Returns the full entry including event data, failure reason,
 * saga context, and replay count.
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
@Service
public class InspectDlqEntryTool {

    private static final Logger logger = LoggerFactory.getLogger(InspectDlqEntryTool.class);

    private final ServiceClientOperations serviceClient;
    private final ObjectMapper objectMapper;
    private ToolAuthorizer toolAuthorizer;

    /**
     * Creates a new InspectDlqEntryTool.
     *
     * @param serviceClient the REST client for service communication
     */
    public InspectDlqEntryTool(ServiceClientOperations serviceClient) {
        this.serviceClient = serviceClient;
        this.objectMapper = new ObjectMapper().enable(SerializationFeature.INDENT_OUTPUT);
    }

    /**
     * Sets the tool authorizer for role-based access control.
     *
     * @param toolAuthorizer the authorizer (injected only when security is enabled)
     */
    @Autowired(required = false)
    public void setToolAuthorizer(final ToolAuthorizer toolAuthorizer) {
        this.toolAuthorizer = toolAuthorizer;
    }

    /**
     * Inspects a DLQ entry by ID.
     *
     * @param dlqEntryId the DLQ entry ID
     * @param serviceName optional service name to query (null defaults to order-service)
     * @return JSON string with the full DLQ entry details
     */
    @Tool(description = "Inspect a dead letter queue entry by ID. Returns full details "
            + "including event data, failure reason, saga context, and replay count. "
            + "Use this to diagnose why an event failed before deciding to replay or discard.")
    public String inspectDlqEntry(
            @ToolParam(description = "The DLQ entry ID to inspect")
            String dlqEntryId,
            @ToolParam(description = "Service to query (optional, defaults to order)")
            String serviceName) {

        if (toolAuthorizer != null) {
            String denied = toolAuthorizer.checkAccess("inspectDlqEntry");
            if (denied != null) {
                return denied;
            }
        }

        logger.info("MCP inspectDlqEntry: id={}, serviceName={}", dlqEntryId, serviceName);

        try {
            Map<String, Object> entry = serviceClient.getDlqEntry(serviceName, dlqEntryId);
            return toJson(entry);
        } catch (Exception e) {
            logger.error("Failed to inspect DLQ entry: {}", dlqEntryId, e);
            return toJson(Map.of("error", "Failed to inspect DLQ entry: " + e.getMessage()));
        }
    }

    private String toJson(Object value) {
        try {
            return objectMapper.writeValueAsString(value);
        } catch (JsonProcessingException e) {
            logger.error("Failed to serialize result", e);
            return "{\"error\": \"Failed to serialize result\"}";
        }
    }
}
