package com.theyawns.ecommerce.mcp.tools;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.theyawns.ecommerce.mcp.client.ServiceClientOperations;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.tool.annotation.Tool;
import org.springframework.ai.tool.annotation.ToolParam;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Map;

/**
 * MCP tool for listing sagas with optional status filtering.
 *
 * <p>Allows AI assistants to browse saga instances, filter by status
 * (e.g., find all failed or compensating sagas), and limit results.
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
@Service
public class ListSagasTool {

    private static final Logger logger = LoggerFactory.getLogger(ListSagasTool.class);
    private static final int DEFAULT_LIMIT = 10;

    private final ServiceClientOperations serviceClient;
    private final ObjectMapper objectMapper;

    /**
     * Creates a new ListSagasTool.
     *
     * @param serviceClient the REST client for service communication
     */
    public ListSagasTool(ServiceClientOperations serviceClient) {
        this.serviceClient = serviceClient;
        this.objectMapper = new ObjectMapper().enable(SerializationFeature.INDENT_OUTPUT);
    }

    /**
     * Lists sagas with optional status and type filters.
     *
     * @param status optional status filter (STARTED, IN_PROGRESS, COMPLETED, COMPENSATING, COMPENSATED, FAILED, TIMED_OUT)
     * @param type optional saga type filter (e.g., "OrderFulfillment", "OrderFulfillmentOrchestrated")
     * @param limit maximum number of results (default: 10)
     * @return JSON string with the list of sagas
     */
    @Tool(description = "List sagas with optional status and type filters. "
            + "Statuses: STARTED, IN_PROGRESS, COMPLETED, COMPENSATING, COMPENSATED, FAILED, TIMED_OUT. "
            + "Types: OrderFulfillment (choreographed), OrderFulfillmentOrchestrated (orchestrated)")
    public String listSagas(
            @ToolParam(description = "Optional status filter: STARTED, IN_PROGRESS, COMPLETED, "
                    + "COMPENSATING, COMPENSATED, FAILED, or TIMED_OUT", required = false) String status,
            @ToolParam(description = "Optional saga type filter: OrderFulfillment or OrderFulfillmentOrchestrated",
                    required = false) String type,
            @ToolParam(description = "Maximum results (default: 10)", required = false) Integer limit) {

        logger.info("MCP listSagas: status={}, type={}, limit={}", status, type, limit);

        try {
            int effectiveLimit = (limit != null && limit > 0) ? limit : DEFAULT_LIMIT;
            List<Map<String, Object>> sagas = serviceClient.listSagas(status, type, effectiveLimit);
            return toJson(Map.of(
                    "status", status != null ? status : "ALL",
                    "type", type != null ? type : "ALL",
                    "count", sagas.size(),
                    "sagas", sagas
            ));
        } catch (Exception e) {
            logger.error("Failed to list sagas", e);
            return toJson(Map.of("error", "Failed to list sagas: " + e.getMessage()));
        }
    }

    private String toJson(Object value) {
        try {
            return objectMapper.writeValueAsString(value);
        } catch (JsonProcessingException e) {
            logger.error("Failed to serialize result", e);
            return "{\"error\": \"Failed to serialize result\"}";
        }
    }
}
