package com.theyawns.ecommerce.mcp.tools;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.theyawns.ecommerce.mcp.client.ServiceClientOperations;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.ai.tool.annotation.Tool;
import org.springframework.ai.tool.annotation.ToolParam;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Map;

/**
 * MCP tool for querying materialized views.
 *
 * <p>Allows AI assistants to query the current state of domain entities
 * by delegating to the appropriate microservice REST API.
 *
 * <p>Available views:
 * <ul>
 *   <li>{@code customer} - Customer accounts (Account Service, port 8081)</li>
 *   <li>{@code product} - Product catalog with stock levels (Inventory Service, port 8082)</li>
 *   <li>{@code order} - Customer orders (Order Service, port 8083)</li>
 *   <li>{@code payment} - Payment records (Payment Service, port 8084)</li>
 * </ul>
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
@Service
public class QueryViewTool {

    private static final Logger logger = LoggerFactory.getLogger(QueryViewTool.class);
    private static final int DEFAULT_LIMIT = 10;

    private final ServiceClientOperations serviceClient;
    private final ObjectMapper objectMapper;

    /**
     * Creates a new QueryViewTool.
     *
     * @param serviceClient the REST client for service communication
     */
    public QueryViewTool(ServiceClientOperations serviceClient) {
        this.serviceClient = serviceClient;
        this.objectMapper = new ObjectMapper().enable(SerializationFeature.INDENT_OUTPUT);
    }

    /**
     * Queries a materialized view to retrieve domain entity state.
     *
     * @param viewName the view to query: customer, product, order, or payment
     * @param key optional entity ID to retrieve a specific entity; omit to list entities
     * @param limit maximum results when listing (default: 10)
     * @return JSON string with the query results
     */
    @Tool(description = "Query a materialized view. Available views: customer, product, order, payment. "
            + "Provide a key to get a specific entity, or omit to list entities.")
    public String queryView(
            @ToolParam(description = "View to query: customer, product, order, or payment") String viewName,
            @ToolParam(description = "Optional: specific entity ID to retrieve", required = false) String key,
            @ToolParam(description = "Maximum results when listing (default: 10)", required = false) Integer limit) {

        logger.info("MCP queryView: view={}, key={}, limit={}", viewName, key, limit);

        try {
            if (key != null && !key.isBlank()) {
                Map<String, Object> result = serviceClient.getEntity(viewName, key);
                return toJson(result);
            } else {
                int effectiveLimit = (limit != null && limit > 0) ? limit : DEFAULT_LIMIT;
                List<Map<String, Object>> results = serviceClient.listEntities(viewName, effectiveLimit);
                return toJson(Map.of(
                        "view", viewName,
                        "count", results.size(),
                        "entities", results
                ));
            }
        } catch (IllegalArgumentException e) {
            return toJson(Map.of("error", e.getMessage()));
        }
    }

    private String toJson(Object value) {
        try {
            return objectMapper.writeValueAsString(value);
        } catch (JsonProcessingException e) {
            logger.error("Failed to serialize result", e);
            return "{\"error\": \"Failed to serialize result\"}";
        }
    }
}
