package com.theyawns.framework.security;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.autoconfigure.AutoConfigureBefore;
import org.springframework.boot.autoconfigure.condition.ConditionalOnClass;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.autoconfigure.condition.ConditionalOnWebApplication;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configurers.AbstractHttpConfigurer;
import org.springframework.security.web.SecurityFilterChain;

/**
 * Auto-configuration that permits all requests when security is disabled.
 *
 * <p>This configuration activates when:
 * <ul>
 *   <li>{@code framework.security.enabled=false} or the property is absent (default)</li>
 *   <li>Spring Security is on the classpath</li>
 *   <li>The application is a servlet web application</li>
 * </ul>
 *
 * <p>When Spring Security is on the classpath but security is disabled, Spring Boot's
 * default auto-configuration would lock down all endpoints. This configuration
 * prevents that by explicitly permitting all requests, preserving the open-by-default
 * behavior that existed before Spring Security was added to the classpath.
 *
 * @author Generated by Claude Code
 * @since 3.0
 * @see SecurityAutoConfiguration
 */
@Configuration("frameworkPermitAllSecurityAutoConfiguration")
@ConditionalOnClass(SecurityFilterChain.class)
@ConditionalOnWebApplication(type = ConditionalOnWebApplication.Type.SERVLET)
@ConditionalOnProperty(name = "framework.security.enabled", havingValue = "false", matchIfMissing = true)
@AutoConfigureBefore(name = "org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration")
public class PermitAllSecurityAutoConfiguration {

    private static final Logger logger = LoggerFactory.getLogger(PermitAllSecurityAutoConfiguration.class);

    /**
     * Creates a permit-all {@link SecurityFilterChain} that allows all requests
     * without authentication.
     *
     * @param http the {@link HttpSecurity} builder
     * @return the configured security filter chain
     * @throws Exception if configuration fails
     */
    @Bean
    @ConditionalOnMissingBean
    public SecurityFilterChain permitAllSecurityFilterChain(final HttpSecurity http) throws Exception {
        logger.info("Configuring permit-all SecurityFilterChain (framework.security.enabled=false)");

        http
                .csrf(AbstractHttpConfigurer::disable)
                .authorizeHttpRequests(auth -> auth.anyRequest().permitAll());

        return http.build();
    }
}
