package com.theyawns.framework.security;

import org.springframework.boot.context.properties.ConfigurationProperties;

import java.util.Arrays;
import java.util.Objects;

/**
 * Configuration properties for framework security.
 *
 * <p>Security is <strong>disabled by default</strong> to preserve backward compatibility.
 * When enabled, the framework configures a {@code SecurityFilterChain} (servlet) or
 * {@code SecurityWebFilterChain} (reactive) that validates JWT Bearer tokens using
 * Spring Boot's native OAuth2 Resource Server support.
 *
 * <p>JWT decoder configuration is handled by Spring Boot's standard properties:
 * <pre>{@code
 * spring.security.oauth2.resourceserver.jwt.issuer-uri=https://your-issuer.example.com
 * spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://your-issuer.example.com/.well-known/jwks.json
 * }</pre>
 *
 * <p>Example configuration in application.yml:
 * <pre>{@code
 * framework:
 *   security:
 *     enabled: true
 *     public-paths:
 *       - /actuator/**
 *       - /api/health
 * }</pre>
 *
 * @author Generated by Claude Code
 * @since 3.0
 * @see SecurityAutoConfiguration
 * @see PermitAllSecurityAutoConfiguration
 */
@ConfigurationProperties(prefix = "framework.security")
public class SecurityProperties {

    /**
     * Whether security (JWT authentication) is enabled.
     * Default: false (all endpoints are open).
     */
    private boolean enabled = false;

    /**
     * URL paths that are publicly accessible without authentication.
     * Supports Ant-style patterns (e.g., {@code /actuator/**}).
     * Default: {@code ["/actuator/**"]}
     */
    private String[] publicPaths = {"/actuator/**"};

    /**
     * Creates a new SecurityProperties with default values.
     */
    public SecurityProperties() {
        // Default constructor
    }

    /**
     * Returns whether security is enabled.
     *
     * @return true if JWT authentication is enabled
     */
    public boolean isEnabled() {
        return enabled;
    }

    /**
     * Sets whether security is enabled.
     *
     * @param enabled true to enable JWT authentication
     */
    public void setEnabled(final boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * Returns the public paths that do not require authentication.
     *
     * @return array of Ant-style path patterns
     */
    public String[] getPublicPaths() {
        return publicPaths;
    }

    /**
     * Sets the public paths that do not require authentication.
     *
     * @param publicPaths array of Ant-style path patterns
     * @throws NullPointerException if publicPaths is null
     */
    public void setPublicPaths(final String[] publicPaths) {
        this.publicPaths = Objects.requireNonNull(publicPaths, "publicPaths cannot be null");
    }

    @Override
    public String toString() {
        return "SecurityProperties{" +
                "enabled=" + enabled +
                ", publicPaths=" + Arrays.toString(publicPaths) +
                '}';
    }
}
