package com.theyawns.framework.saga;

import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.topic.ITopic;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.simple.SimpleMeterRegistry;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.mockito.junit.jupiter.MockitoSettings;
import org.mockito.quality.Strictness;
import org.springframework.context.ApplicationEventPublisher;

import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutionException;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.*;

/**
 * Unit tests for DefaultSagaCompensator.
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
@ExtendWith(MockitoExtension.class)
@MockitoSettings(strictness = Strictness.LENIENT)
@DisplayName("DefaultSagaCompensator - Saga compensation handling")
class DefaultSagaCompensatorTest {

    @Mock
    private SagaStateStore sagaStateStore;

    @Mock
    private HazelcastInstance hazelcast;

    @Mock
    private ITopic<DefaultSagaCompensator.CompensationRequest> topic;

    @Mock
    private ApplicationEventPublisher eventPublisher;

    private CompensationRegistry compensationRegistry;
    private MeterRegistry meterRegistry;
    private DefaultSagaCompensator compensator;

    @BeforeEach
    void setUp() {
        compensationRegistry = new CompensationRegistry();
        meterRegistry = new SimpleMeterRegistry();

        // Setup compensation mappings
        compensationRegistry.register("OrderCreated", "OrderCancelled", "order-service", 0);
        compensationRegistry.register("StockReserved", "StockReleased", "inventory-service", 1);
        compensationRegistry.register("PaymentProcessed", "PaymentRefunded", "payment-service", 2);

        // Setup Hazelcast topic mock
        when(hazelcast.getTopic(anyString())).thenReturn((ITopic) topic);

        compensator = new DefaultSagaCompensator(
                sagaStateStore,
                compensationRegistry,
                hazelcast,
                eventPublisher,
                meterRegistry
        );
    }

    @Nested
    @DisplayName("Constructor")
    class ConstructorTest {

        @Test
        @DisplayName("should reject null sagaStateStore")
        void shouldRejectNullSagaStateStore() {
            assertThrows(NullPointerException.class, () ->
                    new DefaultSagaCompensator(null, compensationRegistry, hazelcast, eventPublisher, meterRegistry));
        }

        @Test
        @DisplayName("should reject null compensationRegistry")
        void shouldRejectNullCompensationRegistry() {
            assertThrows(NullPointerException.class, () ->
                    new DefaultSagaCompensator(sagaStateStore, null, hazelcast, eventPublisher, meterRegistry));
        }

        @Test
        @DisplayName("should reject null hazelcast")
        void shouldRejectNullHazelcast() {
            assertThrows(NullPointerException.class, () ->
                    new DefaultSagaCompensator(sagaStateStore, compensationRegistry, null, eventPublisher, meterRegistry));
        }

        @Test
        @DisplayName("should accept null eventPublisher")
        void shouldAcceptNullEventPublisher() {
            assertDoesNotThrow(() ->
                    new DefaultSagaCompensator(sagaStateStore, compensationRegistry, hazelcast, null, meterRegistry));
        }

        @Test
        @DisplayName("should accept null meterRegistry")
        void shouldAcceptNullMeterRegistry() {
            assertDoesNotThrow(() ->
                    new DefaultSagaCompensator(sagaStateStore, compensationRegistry, hazelcast, eventPublisher, null));
        }
    }

    @Nested
    @DisplayName("canCompensate")
    class CanCompensateTest {

        @Test
        @DisplayName("should return false for null saga state")
        void shouldReturnFalseForNullSagaState() {
            assertFalse(compensator.canCompensate(null));
        }

        @Test
        @DisplayName("should return false for COMPLETED saga")
        void shouldReturnFalseForCompletedSaga() {
            SagaState saga = createSagaWithSteps(SagaStatus.COMPLETED);
            assertFalse(compensator.canCompensate(saga));
        }

        @Test
        @DisplayName("should return false for COMPENSATED saga")
        void shouldReturnFalseForCompensatedSaga() {
            SagaState saga = createSagaWithSteps(SagaStatus.COMPENSATED);
            assertFalse(compensator.canCompensate(saga));
        }

        @Test
        @DisplayName("should return false for FAILED saga")
        void shouldReturnFalseForFailedSaga() {
            SagaState saga = createSagaWithSteps(SagaStatus.FAILED);
            assertFalse(compensator.canCompensate(saga));
        }

        @Test
        @DisplayName("should return false for saga with no completed steps")
        void shouldReturnFalseForSagaWithNoCompletedSteps() {
            SagaState saga = SagaState.builder()
                    .sagaId("saga-123")
                    .sagaType("OrderFulfillment")
                    .status(SagaStatus.IN_PROGRESS)
                    .steps(new ArrayList<>())
                    .build();
            assertFalse(compensator.canCompensate(saga));
        }

        @Test
        @DisplayName("should return true for IN_PROGRESS saga with completed steps")
        void shouldReturnTrueForInProgressSagaWithCompletedSteps() {
            SagaState saga = createSagaWithSteps(SagaStatus.IN_PROGRESS);
            assertTrue(compensator.canCompensate(saga));
        }

        @Test
        @DisplayName("should return true for TIMED_OUT saga with completed steps")
        void shouldReturnTrueForTimedOutSagaWithCompletedSteps() {
            SagaState saga = createSagaWithSteps(SagaStatus.TIMED_OUT);
            // TIMED_OUT is actually terminal, let's use COMPENSATING instead
            SagaState compensatingSaga = createSagaWithSteps(SagaStatus.COMPENSATING);
            assertTrue(compensator.canCompensate(compensatingSaga));
        }
    }

    @Nested
    @DisplayName("compensate")
    class CompensateTest {

        @Test
        @DisplayName("should reject null saga state")
        void shouldRejectNullSagaState() {
            assertThrows(NullPointerException.class, () ->
                    compensator.compensate(null));
        }

        @Test
        @DisplayName("should return no compensation needed when nothing to compensate")
        void shouldReturnNoCompensationNeededWhenNothingToCompensate() throws Exception {
            SagaState saga = SagaState.builder()
                    .sagaId("saga-123")
                    .sagaType("OrderFulfillment")
                    .status(SagaStatus.COMPLETED)
                    .steps(new ArrayList<>())
                    .build();

            CompletableFuture<SagaCompensator.CompensationResult> future = compensator.compensate(saga);
            SagaCompensator.CompensationResult result = future.get();

            assertTrue(result.isSuccess());
            assertEquals(0, result.stepsCompensated());
        }

        @Test
        @DisplayName("should compensate completed steps in reverse order")
        void shouldCompensateCompletedStepsInReverseOrder() throws Exception {
            SagaState saga = createSagaWithSteps(SagaStatus.IN_PROGRESS);

            when(sagaStateStore.recordCompensationStarted(anyString())).thenReturn(saga);
            when(sagaStateStore.recordCompensationStep(anyString(), anyInt(), anyString(), anyString()))
                    .thenReturn(saga);
            when(sagaStateStore.completeSaga(anyString(), any(SagaStatus.class))).thenReturn(saga);

            CompletableFuture<SagaCompensator.CompensationResult> future = compensator.compensate(saga);
            SagaCompensator.CompensationResult result = future.get();

            assertTrue(result.isSuccess());
            assertEquals(2, result.stepsCompensated());

            // Verify compensation was started
            verify(sagaStateStore).recordCompensationStarted("saga-123");

            // Verify compensation requests were published
            ArgumentCaptor<DefaultSagaCompensator.CompensationRequest> requestCaptor =
                    ArgumentCaptor.forClass(DefaultSagaCompensator.CompensationRequest.class);
            verify(topic, times(2)).publish(requestCaptor.capture());

            List<DefaultSagaCompensator.CompensationRequest> requests = requestCaptor.getAllValues();
            // Should be in reverse order: step 1 (StockReserved) then step 0 (OrderCreated)
            assertEquals("StockReleased", requests.get(0).compensatingEventType());
            assertEquals("OrderCancelled", requests.get(1).compensatingEventType());
        }

        @Test
        @DisplayName("should update saga state to COMPENSATED on success")
        void shouldUpdateSagaStateToCompensatedOnSuccess() throws Exception {
            SagaState saga = createSagaWithSteps(SagaStatus.IN_PROGRESS);

            when(sagaStateStore.recordCompensationStarted(anyString())).thenReturn(saga);
            when(sagaStateStore.recordCompensationStep(anyString(), anyInt(), anyString(), anyString()))
                    .thenReturn(saga);
            when(sagaStateStore.completeSaga(anyString(), any(SagaStatus.class))).thenReturn(saga);

            compensator.compensate(saga).get();

            verify(sagaStateStore).completeSaga("saga-123", SagaStatus.COMPENSATED);
        }

        @Test
        @DisplayName("should publish Spring events for compensation requests")
        void shouldPublishSpringEventsForCompensationRequests() throws Exception {
            SagaState saga = createSagaWithSteps(SagaStatus.IN_PROGRESS);

            when(sagaStateStore.recordCompensationStarted(anyString())).thenReturn(saga);
            when(sagaStateStore.recordCompensationStep(anyString(), anyInt(), anyString(), anyString()))
                    .thenReturn(saga);
            when(sagaStateStore.completeSaga(anyString(), any(SagaStatus.class))).thenReturn(saga);

            compensator.compensate(saga).get();

            verify(eventPublisher, times(2)).publishEvent(any(DefaultSagaCompensator.CompensationRequest.class));
        }
    }

    @Nested
    @DisplayName("compensateStep")
    class CompensateStepTest {

        @Test
        @DisplayName("should reject null saga state")
        void shouldRejectNullSagaState() {
            SagaStepRecord step = createStep(1, "StockReserved", StepStatus.COMPLETED);
            assertThrows(NullPointerException.class, () ->
                    compensator.compensateStep(null, step));
        }

        @Test
        @DisplayName("should reject null step record")
        void shouldRejectNullStepRecord() {
            SagaState saga = createSagaWithSteps(SagaStatus.IN_PROGRESS);
            assertThrows(NullPointerException.class, () ->
                    compensator.compensateStep(saga, null));
        }

        @Test
        @DisplayName("should return failure when no compensation mapping exists")
        void shouldReturnFailureWhenNoCompensationMappingExists() throws Exception {
            SagaState saga = createSagaWithSteps(SagaStatus.IN_PROGRESS);
            SagaStepRecord unknownStep = createStep(5, "UnknownEvent", StepStatus.COMPLETED);

            SagaCompensator.CompensationResult result = compensator.compensateStep(saga, unknownStep).get();

            assertFalse(result.isSuccess());
            assertEquals(1, result.stepsFailed());
            assertTrue(result.failureReason().contains("No compensation mapping"));
        }

        @Test
        @DisplayName("should publish to correct topic")
        void shouldPublishToCorrectTopic() throws Exception {
            SagaState saga = createSagaWithSteps(SagaStatus.IN_PROGRESS);
            SagaStepRecord step = createStep(1, "StockReserved", StepStatus.COMPLETED);

            when(sagaStateStore.recordCompensationStep(anyString(), anyInt(), anyString(), anyString()))
                    .thenReturn(saga);

            compensator.compensateStep(saga, step).get();

            // Should publish to inventory-service-compensation topic
            verify(hazelcast).getTopic("inventory-service" + DefaultSagaCompensator.COMPENSATION_TOPIC_SUFFIX);
        }

        @Test
        @DisplayName("should create correct compensation request")
        void shouldCreateCorrectCompensationRequest() throws Exception {
            SagaState saga = createSagaWithSteps(SagaStatus.IN_PROGRESS);
            SagaStepRecord step = SagaStepRecord.builder()
                    .stepNumber(1)
                    .stepName("StockReserved")
                    .eventType("StockReserved")
                    .service("inventory-service")
                    .status(StepStatus.COMPLETED)
                    .eventId("evt-stock-123")
                    .build();

            when(sagaStateStore.recordCompensationStep(anyString(), anyInt(), anyString(), anyString()))
                    .thenReturn(saga);

            compensator.compensateStep(saga, step).get();

            ArgumentCaptor<DefaultSagaCompensator.CompensationRequest> captor =
                    ArgumentCaptor.forClass(DefaultSagaCompensator.CompensationRequest.class);
            verify(topic).publish(captor.capture());

            DefaultSagaCompensator.CompensationRequest request = captor.getValue();
            assertEquals("saga-123", request.sagaId());
            assertEquals("OrderFulfillment", request.sagaType());
            assertEquals(1, request.stepNumber());
            assertEquals("StockReserved", request.originalEventType());
            assertEquals("StockReleased", request.compensatingEventType());
            assertEquals("inventory-service", request.responsibleService());
            assertEquals("evt-stock-123", request.originalEventId());
        }
    }

    @Nested
    @DisplayName("Metrics")
    class MetricsTest {

        @Test
        @DisplayName("should increment compensations started counter")
        void shouldIncrementCompensationsStartedCounter() throws Exception {
            SagaState saga = createSagaWithSteps(SagaStatus.IN_PROGRESS);

            when(sagaStateStore.recordCompensationStarted(anyString())).thenReturn(saga);
            when(sagaStateStore.recordCompensationStep(anyString(), anyInt(), anyString(), anyString()))
                    .thenReturn(saga);
            when(sagaStateStore.completeSaga(anyString(), any(SagaStatus.class))).thenReturn(saga);

            compensator.compensate(saga).get();

            double startedCount = meterRegistry.counter("saga.compensations.started").count();
            assertEquals(1.0, startedCount, 0.001);
        }

        @Test
        @DisplayName("should increment compensations completed counter on success")
        void shouldIncrementCompensationsCompletedCounterOnSuccess() throws Exception {
            SagaState saga = createSagaWithSteps(SagaStatus.IN_PROGRESS);

            when(sagaStateStore.recordCompensationStarted(anyString())).thenReturn(saga);
            when(sagaStateStore.recordCompensationStep(anyString(), anyInt(), anyString(), anyString()))
                    .thenReturn(saga);
            when(sagaStateStore.completeSaga(anyString(), any(SagaStatus.class))).thenReturn(saga);

            compensator.compensate(saga).get();

            double completedCount = meterRegistry.counter("saga.compensations.completed").count();
            assertEquals(1.0, completedCount, 0.001);
        }

        @Test
        @DisplayName("should increment steps compensated counter")
        void shouldIncrementStepsCompensatedCounter() throws Exception {
            SagaState saga = createSagaWithSteps(SagaStatus.IN_PROGRESS);

            when(sagaStateStore.recordCompensationStarted(anyString())).thenReturn(saga);
            when(sagaStateStore.recordCompensationStep(anyString(), anyInt(), anyString(), anyString()))
                    .thenReturn(saga);
            when(sagaStateStore.completeSaga(anyString(), any(SagaStatus.class))).thenReturn(saga);

            compensator.compensate(saga).get();

            double stepsCount = meterRegistry.counter("saga.compensation.steps").count();
            assertEquals(2.0, stepsCount, 0.001);
        }
    }

    @Nested
    @DisplayName("CompensationResult")
    class CompensationResultTest {

        @Test
        @DisplayName("success factory method should create successful result")
        void successFactoryMethodShouldCreateSuccessfulResult() {
            SagaCompensator.CompensationResult result =
                    SagaCompensator.CompensationResult.success("saga-123", 3);

            assertTrue(result.isSuccess());
            assertEquals("saga-123", result.sagaId());
            assertEquals(3, result.stepsCompensated());
            assertEquals(0, result.stepsFailed());
            assertNull(result.failureReason());
        }

        @Test
        @DisplayName("failure factory method should create failed result")
        void failureFactoryMethodShouldCreateFailedResult() {
            SagaCompensator.CompensationResult result =
                    SagaCompensator.CompensationResult.failure("saga-123", 2, 1, "Step 3 failed");

            assertFalse(result.isSuccess());
            assertEquals("saga-123", result.sagaId());
            assertEquals(2, result.stepsCompensated());
            assertEquals(1, result.stepsFailed());
            assertEquals("Step 3 failed", result.failureReason());
        }

        @Test
        @DisplayName("noCompensationNeeded factory method should create no-op result")
        void noCompensationNeededFactoryMethodShouldCreateNoOpResult() {
            SagaCompensator.CompensationResult result =
                    SagaCompensator.CompensationResult.noCompensationNeeded("saga-123");

            assertTrue(result.isSuccess());
            assertEquals(0, result.stepsCompensated());
            assertEquals(0, result.stepsFailed());
            assertNotNull(result.failureReason()); // Contains explanation
        }
    }

    // Helper methods

    private SagaState createSagaWithSteps(SagaStatus status) {
        List<SagaStepRecord> steps = new ArrayList<>();
        steps.add(createStep(0, "OrderCreated", StepStatus.COMPLETED));
        steps.add(createStep(1, "StockReserved", StepStatus.COMPLETED));

        return SagaState.builder()
                .sagaId("saga-123")
                .sagaType("OrderFulfillment")
                .correlationId("corr-456")
                .status(status)
                .startedAt(Instant.now().minus(Duration.ofMinutes(1)))
                .currentStep(2)
                .totalSteps(4)
                .steps(steps)
                .build();
    }

    private SagaStepRecord createStep(int stepNumber, String eventType, StepStatus status) {
        return SagaStepRecord.builder()
                .stepNumber(stepNumber)
                .stepName(eventType)
                .eventType(eventType)
                .service(stepNumber == 0 ? "order-service" : "inventory-service")
                .status(status)
                .eventId("evt-" + stepNumber)
                .build();
    }
}
