package com.theyawns.framework.saga;

import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.Timer;
import io.micrometer.core.instrument.simple.SimpleMeterRegistry;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.time.Duration;
import java.util.concurrent.TimeUnit;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Unit tests for SagaMetrics.
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
@DisplayName("SagaMetrics")
class SagaMetricsTest {

    private MeterRegistry meterRegistry;
    private SagaMetrics metrics;
    private static final String SAGA_TYPE = "OrderFulfillment";

    @BeforeEach
    void setUp() {
        meterRegistry = new SimpleMeterRegistry();
        metrics = new SagaMetrics(meterRegistry);
    }

    @Nested
    @DisplayName("Constructor")
    class ConstructorTests {

        @Test
        @DisplayName("should create metrics with valid parameters")
        void shouldCreateMetricsWithValidParameters() {
            assertNotNull(metrics);
            assertEquals(meterRegistry, metrics.getMeterRegistry());
        }

        @Test
        @DisplayName("should throw on null meter registry")
        void shouldThrowOnNullMeterRegistry() {
            assertThrows(NullPointerException.class,
                    () -> new SagaMetrics(null));
        }

        @Test
        @DisplayName("should register gauge metrics on construction")
        void shouldRegisterGaugeMetricsOnConstruction() {
            assertNotNull(meterRegistry.find("saga.started.total").gauge());
            assertNotNull(meterRegistry.find("saga.completed.total").gauge());
            assertNotNull(meterRegistry.find("saga.compensated.total").gauge());
            assertNotNull(meterRegistry.find("saga.failed.total").gauge());
            assertNotNull(meterRegistry.find("saga.timedout.total").gauge());
            assertNotNull(meterRegistry.find("sagas.active.count").gauge());
            assertNotNull(meterRegistry.find("sagas.compensating.count").gauge());
        }
    }

    @Nested
    @DisplayName("Saga Lifecycle Counters")
    class LifecycleCounterTests {

        @Test
        @DisplayName("should record saga started")
        void shouldRecordSagaStarted() {
            metrics.recordSagaStarted(SAGA_TYPE);

            Counter counter = meterRegistry.find("saga.started")
                    .tag("sagaType", SAGA_TYPE)
                    .counter();

            assertNotNull(counter);
            assertEquals(1.0, counter.count());
            assertEquals(1, metrics.getSagasStartedTotal());
        }

        @Test
        @DisplayName("should record saga completed")
        void shouldRecordSagaCompleted() {
            metrics.recordSagaCompleted(SAGA_TYPE);

            Counter counter = meterRegistry.find("saga.completed")
                    .tag("sagaType", SAGA_TYPE)
                    .counter();

            assertNotNull(counter);
            assertEquals(1.0, counter.count());
            assertEquals(1, metrics.getSagasCompletedTotal());
        }

        @Test
        @DisplayName("should record saga compensated")
        void shouldRecordSagaCompensated() {
            metrics.recordSagaCompensated(SAGA_TYPE);

            Counter counter = meterRegistry.find("saga.compensated")
                    .tag("sagaType", SAGA_TYPE)
                    .counter();

            assertNotNull(counter);
            assertEquals(1.0, counter.count());
            assertEquals(1, metrics.getSagasCompensatedTotal());
        }

        @Test
        @DisplayName("should record saga failed")
        void shouldRecordSagaFailed() {
            metrics.recordSagaFailed(SAGA_TYPE);

            Counter counter = meterRegistry.find("saga.failed")
                    .tag("sagaType", SAGA_TYPE)
                    .counter();

            assertNotNull(counter);
            assertEquals(1.0, counter.count());
            assertEquals(1, metrics.getSagasFailedTotal());
        }

        @Test
        @DisplayName("should record saga timed out")
        void shouldRecordSagaTimedOut() {
            metrics.recordSagaTimedOut(SAGA_TYPE);

            Counter counter = meterRegistry.find("saga.timedout")
                    .tag("sagaType", SAGA_TYPE)
                    .counter();

            assertNotNull(counter);
            assertEquals(1.0, counter.count());
            assertEquals(1, metrics.getSagasTimedOutTotal());
        }

        @Test
        @DisplayName("should increment counters on multiple calls")
        void shouldIncrementCountersOnMultipleCalls() {
            metrics.recordSagaStarted(SAGA_TYPE);
            metrics.recordSagaStarted(SAGA_TYPE);
            metrics.recordSagaStarted(SAGA_TYPE);

            Counter counter = meterRegistry.find("saga.started")
                    .tag("sagaType", SAGA_TYPE)
                    .counter();

            assertNotNull(counter);
            assertEquals(3.0, counter.count());
            assertEquals(3, metrics.getSagasStartedTotal());
        }

        @Test
        @DisplayName("should create separate counters for different saga types")
        void shouldCreateSeparateCountersForDifferentSagaTypes() {
            metrics.recordSagaStarted("OrderFulfillment");
            metrics.recordSagaStarted("CustomerOnboarding");

            long counterCount = meterRegistry.find("saga.started")
                    .counters()
                    .size();

            assertEquals(2, counterCount);
        }
    }

    @Nested
    @DisplayName("Step Counters")
    class StepCounterTests {

        @Test
        @DisplayName("should record step completed")
        void shouldRecordStepCompleted() {
            metrics.recordStepCompleted(SAGA_TYPE);

            Counter counter = meterRegistry.find("saga.steps.completed")
                    .tag("sagaType", SAGA_TYPE)
                    .counter();

            assertNotNull(counter);
            assertEquals(1.0, counter.count());
        }

        @Test
        @DisplayName("should record step failed")
        void shouldRecordStepFailed() {
            metrics.recordStepFailed(SAGA_TYPE);

            Counter counter = meterRegistry.find("saga.steps.failed")
                    .tag("sagaType", SAGA_TYPE)
                    .counter();

            assertNotNull(counter);
            assertEquals(1.0, counter.count());
        }

        @Test
        @DisplayName("should record compensation step")
        void shouldRecordCompensationStep() {
            metrics.recordCompensationStep(SAGA_TYPE);

            Counter counter = meterRegistry.find("saga.compensation.steps")
                    .tag("sagaType", SAGA_TYPE)
                    .counter();

            assertNotNull(counter);
            assertEquals(1.0, counter.count());
        }

        @Test
        @DisplayName("should record compensation started")
        void shouldRecordCompensationStarted() {
            metrics.recordCompensationStarted(SAGA_TYPE);

            Counter counter = meterRegistry.find("saga.compensation.started")
                    .tag("sagaType", SAGA_TYPE)
                    .counter();

            assertNotNull(counter);
            assertEquals(1.0, counter.count());
        }

        @Test
        @DisplayName("should record compensation completed")
        void shouldRecordCompensationCompleted() {
            metrics.recordCompensationCompleted(SAGA_TYPE);

            Counter counter = meterRegistry.find("saga.compensation.completed")
                    .tag("sagaType", SAGA_TYPE)
                    .counter();

            assertNotNull(counter);
            assertEquals(1.0, counter.count());
        }

        @Test
        @DisplayName("should record compensation failed")
        void shouldRecordCompensationFailed() {
            metrics.recordCompensationFailed(SAGA_TYPE);

            Counter counter = meterRegistry.find("saga.compensation.failed")
                    .tag("sagaType", SAGA_TYPE)
                    .counter();

            assertNotNull(counter);
            assertEquals(1.0, counter.count());
        }
    }

    @Nested
    @DisplayName("Duration Timers")
    class DurationTimerTests {

        @Test
        @DisplayName("should record saga duration")
        void shouldRecordSagaDuration() {
            metrics.recordSagaDuration(SAGA_TYPE, Duration.ofMillis(250));

            Timer timer = meterRegistry.find("saga.duration")
                    .tag("sagaType", SAGA_TYPE)
                    .timer();

            assertNotNull(timer);
            assertEquals(1, timer.count());
            assertTrue(timer.totalTime(TimeUnit.MILLISECONDS) >= 250);
        }

        @Test
        @DisplayName("should record compensation duration")
        void shouldRecordCompensationDuration() {
            metrics.recordCompensationDuration(SAGA_TYPE, Duration.ofMillis(100));

            Timer timer = meterRegistry.find("saga.compensation.duration")
                    .tag("sagaType", SAGA_TYPE)
                    .timer();

            assertNotNull(timer);
            assertEquals(1, timer.count());
            assertTrue(timer.totalTime(TimeUnit.MILLISECONDS) >= 100);
        }

        @Test
        @DisplayName("should handle null duration gracefully")
        void shouldHandleNullDurationGracefully() {
            // Should not throw
            metrics.recordSagaDuration(SAGA_TYPE, null);
            metrics.recordCompensationDuration(SAGA_TYPE, null);

            Timer timer = meterRegistry.find("saga.duration")
                    .tag("sagaType", SAGA_TYPE)
                    .timer();

            // Timer should not be created when null duration is passed
            assertNull(timer);
        }

        @Test
        @DisplayName("should accumulate multiple duration recordings")
        void shouldAccumulateMultipleDurationRecordings() {
            metrics.recordSagaDuration(SAGA_TYPE, Duration.ofMillis(100));
            metrics.recordSagaDuration(SAGA_TYPE, Duration.ofMillis(200));
            metrics.recordSagaDuration(SAGA_TYPE, Duration.ofMillis(300));

            Timer timer = meterRegistry.find("saga.duration")
                    .tag("sagaType", SAGA_TYPE)
                    .timer();

            assertNotNull(timer);
            assertEquals(3, timer.count());
            assertTrue(timer.totalTime(TimeUnit.MILLISECONDS) >= 600);
        }
    }

    @Nested
    @DisplayName("Counter Caching")
    class CachingTests {

        @Test
        @DisplayName("should reuse cached counters for same saga type")
        void shouldReuseCachedCounters() {
            metrics.recordSagaStarted(SAGA_TYPE);
            metrics.recordSagaStarted(SAGA_TYPE);

            long counterCount = meterRegistry.find("saga.started")
                    .counters()
                    .stream()
                    .filter(c -> SAGA_TYPE.equals(c.getId().getTag("sagaType")))
                    .count();

            assertEquals(1, counterCount);
        }

        @Test
        @DisplayName("should reuse cached timers for same saga type")
        void shouldReuseCachedTimers() {
            metrics.recordSagaDuration(SAGA_TYPE, Duration.ofMillis(100));
            metrics.recordSagaDuration(SAGA_TYPE, Duration.ofMillis(200));

            long timerCount = meterRegistry.find("saga.duration")
                    .timers()
                    .stream()
                    .filter(t -> SAGA_TYPE.equals(t.getId().getTag("sagaType")))
                    .count();

            assertEquals(1, timerCount);
        }
    }

    @Nested
    @DisplayName("Gauge Values")
    class GaugeTests {

        @Test
        @DisplayName("should reflect lifecycle totals in gauges")
        void shouldReflectLifecycleTotalsInGauges() {
            metrics.recordSagaStarted(SAGA_TYPE);
            metrics.recordSagaStarted(SAGA_TYPE);
            metrics.recordSagaCompleted(SAGA_TYPE);
            metrics.recordCompensationStarted(SAGA_TYPE);
            metrics.recordSagaCompensated(SAGA_TYPE);
            metrics.recordSagaFailed(SAGA_TYPE);
            metrics.recordSagaTimedOut(SAGA_TYPE);

            assertEquals(2, metrics.getSagasStartedTotal());
            assertEquals(1, metrics.getSagasCompletedTotal());
            assertEquals(1, metrics.getSagasCompensatedTotal());
            assertEquals(1, metrics.getSagasFailedTotal());
            assertEquals(1, metrics.getSagasTimedOutTotal());

            // Gauges should match
            assertEquals(2.0, meterRegistry.find("saga.started.total").gauge().value());
            assertEquals(1.0, meterRegistry.find("saga.completed.total").gauge().value());
            assertEquals(1.0, meterRegistry.find("saga.compensated.total").gauge().value());
            assertEquals(1.0, meterRegistry.find("saga.failed.total").gauge().value());
            assertEquals(1.0, meterRegistry.find("saga.timedout.total").gauge().value());
        }

        @Test
        @DisplayName("should track active saga count")
        void shouldTrackActiveSagaCount() {
            metrics.recordSagaStarted(SAGA_TYPE);
            metrics.recordSagaStarted(SAGA_TYPE);
            metrics.recordSagaStarted(SAGA_TYPE);
            assertEquals(3, metrics.getSagasActiveCount());

            metrics.recordSagaCompleted(SAGA_TYPE);
            assertEquals(2, metrics.getSagasActiveCount());

            metrics.recordSagaFailed(SAGA_TYPE);
            assertEquals(1, metrics.getSagasActiveCount());

            // Active count gauge should match
            assertEquals(1.0, meterRegistry.find("sagas.active.count").gauge().value());
        }

        @Test
        @DisplayName("should track compensating saga count")
        void shouldTrackCompensatingSagaCount() {
            metrics.recordSagaStarted(SAGA_TYPE);
            metrics.recordSagaStarted(SAGA_TYPE);
            metrics.recordCompensationStarted(SAGA_TYPE);
            metrics.recordCompensationStarted(SAGA_TYPE);
            assertEquals(2, metrics.getSagasCompensatingCount());

            metrics.recordSagaCompensated(SAGA_TYPE);
            assertEquals(1, metrics.getSagasCompensatingCount());

            // Compensating count gauge should match
            assertEquals(1.0, meterRegistry.find("sagas.compensating.count").gauge().value());
        }
    }
}
