package com.theyawns.framework.saga;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Unit tests for SagaTimeoutConfig.
 *
 * @author Generated by Claude Code
 * @since 2.0
 */
@DisplayName("SagaTimeoutConfig - Timeout configuration properties")
class SagaTimeoutConfigTest {

    private SagaTimeoutConfig config;

    @BeforeEach
    void setUp() {
        config = new SagaTimeoutConfig();
    }

    @Nested
    @DisplayName("Default values")
    class DefaultValues {

        @Test
        @DisplayName("should have enabled=true by default")
        void shouldHaveEnabledTrueByDefault() {
            assertTrue(config.isEnabled());
        }

        @Test
        @DisplayName("should have check interval of 5 seconds by default")
        void shouldHaveCheckIntervalOfFiveSecondsByDefault() {
            assertEquals(Duration.ofSeconds(5), config.getCheckInterval());
        }

        @Test
        @DisplayName("should have default deadline of 30 seconds")
        void shouldHaveDefaultDeadlineOfThirtySeconds() {
            assertEquals(Duration.ofSeconds(30), config.getDefaultDeadline());
        }

        @Test
        @DisplayName("should have empty saga types map by default")
        void shouldHaveEmptySagaTypesMapByDefault() {
            assertTrue(config.getSagaTypes().isEmpty());
        }

        @Test
        @DisplayName("should have max batch size of 100 by default")
        void shouldHaveMaxBatchSizeOfOneHundredByDefault() {
            assertEquals(100, config.getMaxBatchSize());
        }

        @Test
        @DisplayName("should have auto compensate enabled by default")
        void shouldHaveAutoCompensateEnabledByDefault() {
            assertTrue(config.isAutoCompensate());
        }

        @Test
        @DisplayName("should have purge enabled by default")
        void shouldHavePurgeEnabledByDefault() {
            assertTrue(config.isPurgeEnabled());
        }

        @Test
        @DisplayName("should have purge older than 10 minutes by default")
        void shouldHavePurgeOlderThanTenMinutesByDefault() {
            assertEquals(Duration.ofMinutes(10), config.getPurgeOlderThan());
        }

        @Test
        @DisplayName("should have purge interval checks of 60 by default")
        void shouldHavePurgeIntervalChecksOfSixtyByDefault() {
            assertEquals(60, config.getPurgeIntervalChecks());
        }
    }

    @Nested
    @DisplayName("Setters and getters")
    class SettersAndGetters {

        @Test
        @DisplayName("setEnabled should update enabled flag")
        void setEnabledShouldUpdateFlag() {
            config.setEnabled(false);
            assertFalse(config.isEnabled());

            config.setEnabled(true);
            assertTrue(config.isEnabled());
        }

        @Test
        @DisplayName("setCheckInterval should update interval")
        void setCheckIntervalShouldUpdateInterval() {
            config.setCheckInterval(Duration.ofSeconds(10));
            assertEquals(Duration.ofSeconds(10), config.getCheckInterval());
        }

        @Test
        @DisplayName("setCheckInterval should reject null")
        void setCheckIntervalShouldRejectNull() {
            assertThrows(NullPointerException.class, () ->
                    config.setCheckInterval(null));
        }

        @Test
        @DisplayName("getCheckIntervalMillis should return milliseconds")
        void getCheckIntervalMillisShouldReturnMilliseconds() {
            config.setCheckInterval(Duration.ofSeconds(7));
            assertEquals(7000L, config.getCheckIntervalMillis());
        }

        @Test
        @DisplayName("setDefaultDeadline should update deadline")
        void setDefaultDeadlineShouldUpdateDeadline() {
            config.setDefaultDeadline(Duration.ofMinutes(2));
            assertEquals(Duration.ofMinutes(2), config.getDefaultDeadline());
        }

        @Test
        @DisplayName("setDefaultDeadline should reject null")
        void setDefaultDeadlineShouldRejectNull() {
            assertThrows(NullPointerException.class, () ->
                    config.setDefaultDeadline(null));
        }

        @Test
        @DisplayName("setMaxBatchSize should update batch size")
        void setMaxBatchSizeShouldUpdateBatchSize() {
            config.setMaxBatchSize(50);
            assertEquals(50, config.getMaxBatchSize());
        }

        @Test
        @DisplayName("setMaxBatchSize should reject zero")
        void setMaxBatchSizeShouldRejectZero() {
            assertThrows(IllegalArgumentException.class, () ->
                    config.setMaxBatchSize(0));
        }

        @Test
        @DisplayName("setMaxBatchSize should reject negative")
        void setMaxBatchSizeShouldRejectNegative() {
            assertThrows(IllegalArgumentException.class, () ->
                    config.setMaxBatchSize(-1));
        }

        @Test
        @DisplayName("setAutoCompensate should update flag")
        void setAutoCompensateShouldUpdateFlag() {
            config.setAutoCompensate(false);
            assertFalse(config.isAutoCompensate());

            config.setAutoCompensate(true);
            assertTrue(config.isAutoCompensate());
        }

        @Test
        @DisplayName("setPurgeEnabled should update flag")
        void setPurgeEnabledShouldUpdateFlag() {
            config.setPurgeEnabled(false);
            assertFalse(config.isPurgeEnabled());

            config.setPurgeEnabled(true);
            assertTrue(config.isPurgeEnabled());
        }

        @Test
        @DisplayName("setPurgeOlderThan should update duration")
        void setPurgeOlderThanShouldUpdateDuration() {
            config.setPurgeOlderThan(Duration.ofMinutes(30));
            assertEquals(Duration.ofMinutes(30), config.getPurgeOlderThan());
        }

        @Test
        @DisplayName("setPurgeOlderThan should reject null")
        void setPurgeOlderThanShouldRejectNull() {
            assertThrows(NullPointerException.class, () ->
                    config.setPurgeOlderThan(null));
        }

        @Test
        @DisplayName("setPurgeIntervalChecks should update value")
        void setPurgeIntervalChecksShouldUpdateValue() {
            config.setPurgeIntervalChecks(120);
            assertEquals(120, config.getPurgeIntervalChecks());
        }

        @Test
        @DisplayName("setPurgeIntervalChecks should reject zero")
        void setPurgeIntervalChecksShouldRejectZero() {
            assertThrows(IllegalArgumentException.class, () ->
                    config.setPurgeIntervalChecks(0));
        }

        @Test
        @DisplayName("setPurgeIntervalChecks should reject negative")
        void setPurgeIntervalChecksShouldRejectNegative() {
            assertThrows(IllegalArgumentException.class, () ->
                    config.setPurgeIntervalChecks(-1));
        }
    }

    @Nested
    @DisplayName("Saga type specific timeouts")
    class SagaTypeSpecificTimeouts {

        @Test
        @DisplayName("setSagaTypes should update saga types map")
        void setSagaTypesShouldUpdateMap() {
            Map<String, Duration> sagaTypes = new HashMap<>();
            sagaTypes.put("OrderFulfillment", Duration.ofSeconds(60));
            sagaTypes.put("PaymentProcessing", Duration.ofSeconds(45));

            config.setSagaTypes(sagaTypes);

            assertEquals(2, config.getSagaTypes().size());
            assertEquals(Duration.ofSeconds(60), config.getSagaTypes().get("OrderFulfillment"));
        }

        @Test
        @DisplayName("setSagaTypes with null should create empty map")
        void setSagaTypesWithNullShouldCreateEmptyMap() {
            config.setSagaTypes(null);
            assertNotNull(config.getSagaTypes());
            assertTrue(config.getSagaTypes().isEmpty());
        }

        @Test
        @DisplayName("getTimeoutForSagaType should return configured timeout")
        void getTimeoutForSagaTypeShouldReturnConfiguredTimeout() {
            Map<String, Duration> sagaTypes = new HashMap<>();
            sagaTypes.put("OrderFulfillment", Duration.ofSeconds(60));
            config.setSagaTypes(sagaTypes);

            assertEquals(Duration.ofSeconds(60), config.getTimeoutForSagaType("OrderFulfillment"));
        }

        @Test
        @DisplayName("getTimeoutForSagaType should return default for unconfigured type")
        void getTimeoutForSagaTypeShouldReturnDefaultForUnconfiguredType() {
            config.setDefaultDeadline(Duration.ofSeconds(30));

            assertEquals(Duration.ofSeconds(30), config.getTimeoutForSagaType("UnknownSaga"));
        }
    }

    @Nested
    @DisplayName("Constructor with parameters")
    class ConstructorWithParameters {

        @Test
        @DisplayName("constructor should set all parameters")
        void constructorShouldSetAllParameters() {
            SagaTimeoutConfig config = new SagaTimeoutConfig(
                    false,
                    Duration.ofSeconds(10),
                    Duration.ofMinutes(1)
            );

            assertFalse(config.isEnabled());
            assertEquals(Duration.ofSeconds(10), config.getCheckInterval());
            assertEquals(Duration.ofMinutes(1), config.getDefaultDeadline());
        }
    }

    @Nested
    @DisplayName("toString")
    class ToStringTest {

        @Test
        @DisplayName("toString should contain key information")
        void toStringShouldContainKeyInformation() {
            config.setEnabled(true);
            config.setCheckInterval(Duration.ofSeconds(5));
            config.setDefaultDeadline(Duration.ofSeconds(30));
            config.setMaxBatchSize(100);
            config.setAutoCompensate(true);

            String str = config.toString();

            assertTrue(str.contains("enabled=true"));
            assertTrue(str.contains("checkInterval="));
            assertTrue(str.contains("defaultDeadline="));
            assertTrue(str.contains("maxBatchSize=100"));
            assertTrue(str.contains("autoCompensate=true"));
            assertTrue(str.contains("purgeEnabled=true"));
            assertTrue(str.contains("purgeOlderThan="));
            assertTrue(str.contains("purgeIntervalChecks=60"));
        }
    }
}
