package com.theyawns.framework.dlq;

import com.hazelcast.core.HazelcastInstance;
import com.theyawns.framework.persistence.DlqStorePersistence;
import io.micrometer.core.instrument.MeterRegistry;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.autoconfigure.condition.ConditionalOnBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnMissingBean;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * Auto-configuration for the dead letter queue.
 *
 * <p>Enabled by default. Provides:
 * <ul>
 *   <li>{@link DeadLetterQueueOperations} — prefers shared cluster, falls back to embedded</li>
 *   <li>{@link DeadLetterQueueController} — REST admin endpoints</li>
 * </ul>
 *
 * <p>To disable, set:
 * <pre>
 * framework.dlq.enabled=false
 * </pre>
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
@Configuration
@ConditionalOnProperty(name = "framework.dlq.enabled", matchIfMissing = true)
@ConditionalOnBean(HazelcastInstance.class)
@EnableConfigurationProperties(DeadLetterQueueProperties.class)
public class DeadLetterQueueAutoConfiguration {

    private static final Logger logger = LoggerFactory.getLogger(DeadLetterQueueAutoConfiguration.class);

    /**
     * Creates the DeadLetterQueueOperations bean.
     * Prefers the shared cluster for cross-service visibility, falls back to embedded.
     *
     * @param hazelcastInstance the @Primary embedded Hazelcast instance
     * @param sharedHazelcast the shared Hazelcast client (nullable)
     * @param properties the DLQ properties
     * @param meterRegistry the meter registry
     * @param dlqStorePersistence the optional DLQ persistence provider
     * @return the DLQ operations
     */
    @Bean
    @ConditionalOnMissingBean
    public DeadLetterQueueOperations deadLetterQueueOperations(
            final HazelcastInstance hazelcastInstance,
            @Qualifier("hazelcastClient")
            @Autowired(required = false)
            final HazelcastInstance sharedHazelcast,
            final DeadLetterQueueProperties properties,
            final MeterRegistry meterRegistry,
            @Autowired(required = false)
            final DlqStorePersistence dlqStorePersistence) {
        HazelcastInstance hz = sharedHazelcast != null ? sharedHazelcast : hazelcastInstance;
        logger.info("Creating HazelcastDeadLetterQueue bean (instance={}, persistence={})",
                sharedHazelcast != null ? "shared cluster" : "embedded",
                dlqStorePersistence != null ? dlqStorePersistence.getClass().getSimpleName() : "none");
        return new HazelcastDeadLetterQueue(hz, properties, meterRegistry, dlqStorePersistence);
    }

    /**
     * Creates the DLQ admin REST controller.
     *
     * @param deadLetterQueue the DLQ operations
     * @return the DLQ controller
     */
    @Bean
    @ConditionalOnMissingBean
    public DeadLetterQueueController deadLetterQueueController(
            final DeadLetterQueueOperations deadLetterQueue) {
        logger.info("Creating DeadLetterQueueController bean");
        return new DeadLetterQueueController(deadLetterQueue);
    }

    /**
     * Creates the shared FaultInjectionState bean.
     *
     * @return the fault injection state
     */
    @Bean
    @ConditionalOnMissingBean
    public FaultInjectionState faultInjectionState() {
        logger.info("Creating FaultInjectionState bean");
        return new FaultInjectionState();
    }

    /**
     * Creates the fault injection REST controller.
     *
     * @param faultInjectionState the shared fault injection state
     * @return the fault injection controller
     */
    @Bean
    @ConditionalOnMissingBean
    public FaultInjectionController faultInjectionController(
            final FaultInjectionState faultInjectionState) {
        logger.info("Creating FaultInjectionController bean");
        return new FaultInjectionController(faultInjectionState);
    }
}
