package com.theyawns.framework.dlq;

import java.util.List;

/**
 * Interface for dead letter queue operations.
 *
 * <p>Extracted as an interface for Java 25 Mockito compatibility —
 * concrete Hazelcast-backed classes cannot be mocked with the inline
 * mock maker, but interfaces can.
 *
 * <p>The DLQ captures events that failed processing after resilience
 * mechanisms were exhausted. Entries can be replayed (re-published to
 * their original ITopic) or discarded by an administrator.
 *
 * @author Generated by Claude Code
 * @since 3.0
 * @see HazelcastDeadLetterQueue
 */
public interface DeadLetterQueueOperations {

    /**
     * Adds a failed event to the dead letter queue.
     *
     * @param entry the dead letter entry
     */
    void add(DeadLetterEntry entry);

    /**
     * Lists DLQ entries, most recent first.
     *
     * @param limit the maximum number of entries to return
     * @return list of DLQ entries
     */
    List<DeadLetterEntry> list(int limit);

    /**
     * Retrieves a single DLQ entry by its identifier.
     *
     * @param dlqEntryId the DLQ entry identifier
     * @return the entry, or null if not found
     */
    DeadLetterEntry getEntry(String dlqEntryId);

    /**
     * Replays a DLQ entry by re-publishing its event record
     * to the original ITopic.
     *
     * @param dlqEntryId the DLQ entry identifier
     * @throws IllegalStateException if the entry is not in PENDING status
     */
    void replay(String dlqEntryId);

    /**
     * Marks a DLQ entry as discarded.
     *
     * @param dlqEntryId the DLQ entry identifier
     * @throws IllegalStateException if the entry is not in PENDING status
     */
    void discard(String dlqEntryId);

    /**
     * Returns the number of entries currently in PENDING status.
     *
     * @return the pending entry count
     */
    long count();
}
