package com.theyawns.framework.dlq;

import com.hazelcast.core.HazelcastInstance;
import com.hazelcast.map.IMap;
import com.hazelcast.nio.serialization.genericrecord.GenericRecord;
import com.hazelcast.nio.serialization.genericrecord.GenericRecordBuilder;
import com.hazelcast.query.Predicates;
import com.hazelcast.topic.ITopic;
import com.theyawns.framework.persistence.DlqStorePersistence;
import com.theyawns.framework.persistence.PersistableDeadLetterEntry;
import com.theyawns.framework.persistence.mapstore.GenericRecordJsonConverter;
import io.micrometer.core.instrument.MeterRegistry;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.time.Instant;
import java.util.Collection;
import java.util.Comparator;
import java.util.List;
import java.util.Objects;
import java.util.stream.Collectors;

/**
 * Hazelcast IMap-backed implementation of {@link DeadLetterQueueOperations}.
 *
 * <p>Stores dead letter entries as Compact-serialized {@link GenericRecord}
 * values in Hazelcast IMap. The conversion between {@link DeadLetterEntry}
 * POJOs and GenericRecords happens in this class, keeping serialization
 * concerns out of the domain model.
 *
 * <p>Uses the shared cluster's IMap to store entries, making them accessible
 * from any service in the cluster. Falls back to the embedded instance if
 * no shared cluster is configured.
 *
 * <p>Replay publishes the event record to the original ITopic on the same
 * Hazelcast instance that hosts the DLQ map.
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
public class HazelcastDeadLetterQueue implements DeadLetterQueueOperations {

    private static final Logger logger = LoggerFactory.getLogger(HazelcastDeadLetterQueue.class);

    private static final String SCHEMA_NAME = "DeadLetterEntry";

    private final HazelcastInstance hazelcast;
    private final IMap<String, GenericRecord> dlqMap;
    private final DeadLetterQueueProperties properties;
    private final MeterRegistry meterRegistry;
    private final DlqStorePersistence persistence;

    /**
     * Creates a new HazelcastDeadLetterQueue without persistence.
     *
     * @param hazelcast the Hazelcast instance (shared cluster preferred)
     * @param properties the DLQ configuration properties
     * @param meterRegistry the meter registry for metrics
     */
    public HazelcastDeadLetterQueue(final HazelcastInstance hazelcast,
                                     final DeadLetterQueueProperties properties,
                                     final MeterRegistry meterRegistry) {
        this(hazelcast, properties, meterRegistry, null);
    }

    /**
     * Creates a new HazelcastDeadLetterQueue with optional persistence.
     *
     * <p>When persistence is provided, entries are persisted on add/replay/discard
     * and PENDING entries are recovered from persistence on startup.
     *
     * @param hazelcast the Hazelcast instance (shared cluster preferred)
     * @param properties the DLQ configuration properties
     * @param meterRegistry the meter registry for metrics
     * @param persistence the optional persistence provider (nullable)
     */
    public HazelcastDeadLetterQueue(final HazelcastInstance hazelcast,
                                     final DeadLetterQueueProperties properties,
                                     final MeterRegistry meterRegistry,
                                     final DlqStorePersistence persistence) {
        this.hazelcast = Objects.requireNonNull(hazelcast, "hazelcast cannot be null");
        this.properties = Objects.requireNonNull(properties, "properties cannot be null");
        this.meterRegistry = Objects.requireNonNull(meterRegistry, "meterRegistry cannot be null");
        this.persistence = persistence;
        this.dlqMap = hazelcast.getMap(properties.getMapName());
        logger.info("Initialized HazelcastDeadLetterQueue with map: {}, persistence: {}",
                properties.getMapName(), persistence != null ? persistence.getClass().getSimpleName() : "none");
        loadFromPersistence();
    }

    @Override
    public void add(final DeadLetterEntry entry) {
        Objects.requireNonNull(entry, "entry cannot be null");
        dlqMap.set(entry.getDlqEntryId(), toRecord(entry));
        persistIfAvailable(entry);
        meterRegistry.counter("dlq.entries.added").increment();
        logger.info("Added DLQ entry: dlqEntryId={}, originalEventId={}, eventType={}, sourceService={}",
                entry.getDlqEntryId(), entry.getOriginalEventId(),
                entry.getEventType(), entry.getSourceService());
    }

    @Override
    public List<DeadLetterEntry> list(final int limit) {
        final Collection<GenericRecord> allRecords = dlqMap.values();
        return allRecords.stream()
                .map(HazelcastDeadLetterQueue::fromRecord)
                .sorted(Comparator.comparing(DeadLetterEntry::getFailureTimestamp).reversed())
                .limit(limit)
                .collect(Collectors.toList());
    }

    @Override
    public DeadLetterEntry getEntry(final String dlqEntryId) {
        final GenericRecord record = dlqMap.get(dlqEntryId);
        return record != null ? fromRecord(record) : null;
    }

    @Override
    public void replay(final String dlqEntryId) {
        final GenericRecord record = dlqMap.get(dlqEntryId);
        if (record == null) {
            throw new IllegalArgumentException("DLQ entry not found: " + dlqEntryId);
        }

        final DeadLetterEntry entry = fromRecord(record);

        if (entry.getStatus() != DeadLetterEntry.Status.PENDING) {
            throw new IllegalStateException(
                    "Cannot replay entry in status " + entry.getStatus() + ": " + dlqEntryId);
        }
        if (entry.getReplayCount() >= properties.getMaxReplayAttempts()) {
            throw new IllegalStateException(
                    "Max replay attempts (" + properties.getMaxReplayAttempts() +
                            ") exceeded for entry: " + dlqEntryId);
        }

        // Re-publish to the original topic
        final GenericRecord eventRecord = entry.getEventRecord();
        if (eventRecord != null && entry.getTopicName() != null) {
            final ITopic<GenericRecord> topic = hazelcast.getTopic(entry.getTopicName());
            topic.publish(eventRecord);
        }

        // Update entry status
        entry.setReplayCount(entry.getReplayCount() + 1);
        entry.setStatus(DeadLetterEntry.Status.REPLAYED);
        dlqMap.set(dlqEntryId, toRecord(entry));
        persistIfAvailable(entry);

        meterRegistry.counter("dlq.entries.replayed").increment();
        logger.info("Replayed DLQ entry: dlqEntryId={}, originalEventId={}, topicName={}",
                dlqEntryId, entry.getOriginalEventId(), entry.getTopicName());
    }

    @Override
    public void discard(final String dlqEntryId) {
        final GenericRecord record = dlqMap.get(dlqEntryId);
        if (record == null) {
            throw new IllegalArgumentException("DLQ entry not found: " + dlqEntryId);
        }

        final DeadLetterEntry entry = fromRecord(record);

        if (entry.getStatus() != DeadLetterEntry.Status.PENDING) {
            throw new IllegalStateException(
                    "Cannot discard entry in status " + entry.getStatus() + ": " + dlqEntryId);
        }

        entry.setStatus(DeadLetterEntry.Status.DISCARDED);
        dlqMap.set(dlqEntryId, toRecord(entry));
        persistIfAvailable(entry);

        meterRegistry.counter("dlq.entries.discarded").increment();
        logger.info("Discarded DLQ entry: dlqEntryId={}, originalEventId={}",
                dlqEntryId, entry.getOriginalEventId());
    }

    @Override
    public long count() {
        final Collection<GenericRecord> pending = dlqMap.values(
                Predicates.equal("status", DeadLetterEntry.Status.PENDING.name()));
        return pending.size();
    }

    /**
     * Converts a DeadLetterEntry POJO to a Compact GenericRecord for IMap storage.
     *
     * @param entry the dead letter entry
     * @return the GenericRecord representation
     */
    static GenericRecord toRecord(final DeadLetterEntry entry) {
        return GenericRecordBuilder.compact(SCHEMA_NAME)
                .setString("dlqEntryId", entry.getDlqEntryId())
                .setString("originalEventId", entry.getOriginalEventId())
                .setString("eventType", entry.getEventType())
                .setString("topicName", entry.getTopicName())
                .setGenericRecord("eventRecord", entry.getEventRecord())
                .setString("failureReason", entry.getFailureReason())
                .setInt64("failureTimestamp", entry.getFailureTimestamp().toEpochMilli())
                .setString("sourceService", entry.getSourceService())
                .setString("sagaId", entry.getSagaId())
                .setString("correlationId", entry.getCorrelationId())
                .setInt32("replayCount", entry.getReplayCount())
                .setString("status", entry.getStatus().name())
                .build();
    }

    /**
     * Reconstitutes a DeadLetterEntry POJO from a Compact GenericRecord read from IMap.
     *
     * @param record the GenericRecord
     * @return the reconstituted dead letter entry
     */
    static DeadLetterEntry fromRecord(final GenericRecord record) {
        return DeadLetterEntry.reconstitute(
                record.getString("dlqEntryId"),
                record.getString("originalEventId"),
                record.getString("eventType"),
                record.getString("topicName"),
                record.getGenericRecord("eventRecord"),
                record.getString("failureReason"),
                Instant.ofEpochMilli(record.getInt64("failureTimestamp")),
                record.getString("sourceService"),
                record.getString("sagaId"),
                record.getString("correlationId"),
                record.getInt32("replayCount"),
                DeadLetterEntry.Status.valueOf(record.getString("status"))
        );
    }

    /**
     * Persists a DLQ entry if a persistence provider is available.
     *
     * @param entry the entry to persist
     */
    private void persistIfAvailable(final DeadLetterEntry entry) {
        if (persistence != null) {
            try {
                persistence.persist(toPersistableEntry(entry));
            } catch (Exception e) {
                logger.warn("Failed to persist DLQ entry {}: {}", entry.getDlqEntryId(), e.getMessage());
            }
        }
    }

    /**
     * Loads PENDING entries from persistence into the IMap on startup.
     */
    private void loadFromPersistence() {
        if (persistence == null || !persistence.isAvailable()) {
            return;
        }
        try {
            int recovered = 0;
            for (String key : persistence.loadPendingKeys()) {
                if (!dlqMap.containsKey(key)) {
                    persistence.load(key).ifPresent(persistable -> {
                        DeadLetterEntry entry = fromPersistableEntry(persistable);
                        dlqMap.set(entry.getDlqEntryId(), toRecord(entry));
                    });
                    recovered++;
                }
            }
            if (recovered > 0) {
                logger.info("Recovered {} PENDING DLQ entries from persistence", recovered);
            }
        } catch (Exception e) {
            logger.warn("Failed to load DLQ entries from persistence: {}", e.getMessage());
        }
    }

    /**
     * Converts a DeadLetterEntry to a PersistableDeadLetterEntry for database storage.
     *
     * @param entry the DLQ entry
     * @return the persistable representation
     */
    static PersistableDeadLetterEntry toPersistableEntry(final DeadLetterEntry entry) {
        String eventDataJson = null;
        if (entry.getEventRecord() != null) {
            try {
                eventDataJson = GenericRecordJsonConverter.toJson(entry.getEventRecord());
            } catch (Exception e) {
                logger.warn("Failed to serialize event record for DLQ entry {}: {}",
                        entry.getDlqEntryId(), e.getMessage());
            }
        }
        return new PersistableDeadLetterEntry(
                entry.getDlqEntryId(),
                entry.getOriginalEventId(),
                entry.getEventType(),
                entry.getTopicName(),
                eventDataJson,
                entry.getFailureReason(),
                entry.getFailureTimestamp().toEpochMilli(),
                entry.getSourceService(),
                entry.getSagaId(),
                entry.getCorrelationId(),
                entry.getReplayCount(),
                entry.getStatus().name()
        );
    }

    /**
     * Reconstitutes a DeadLetterEntry from a PersistableDeadLetterEntry loaded from the database.
     *
     * @param persistable the persistable entry
     * @return the reconstituted DLQ entry
     */
    static DeadLetterEntry fromPersistableEntry(final PersistableDeadLetterEntry persistable) {
        GenericRecord eventRecord = null;
        if (persistable.eventData() != null) {
            try {
                eventRecord = GenericRecordJsonConverter.fromJson(persistable.eventData());
            } catch (Exception e) {
                logger.warn("Failed to deserialize event record for DLQ entry {}: {}",
                        persistable.dlqEntryId(), e.getMessage());
            }
        }
        return DeadLetterEntry.reconstitute(
                persistable.dlqEntryId(),
                persistable.originalEventId(),
                persistable.eventType(),
                persistable.topicName(),
                eventRecord,
                persistable.failureReason(),
                Instant.ofEpochMilli(persistable.failureTimestampMillis()),
                persistable.sourceService(),
                persistable.sagaId(),
                persistable.correlationId(),
                persistable.replayCount(),
                DeadLetterEntry.Status.valueOf(persistable.status())
        );
    }
}
