package com.theyawns.framework.persistence;

import java.util.List;
import java.util.Optional;

/**
 * Provider-agnostic interface for persisting dead letter queue entries to durable storage.
 *
 * <p>Unlike the event store and outbox, the DLQ map lives on the shared Hazelcast cluster
 * (for cross-service visibility), which means MapStore cannot be used (MapStore requires
 * server-side Config, but services connect as clients). Instead, this interface is called
 * directly by {@link com.theyawns.framework.dlq.HazelcastDeadLetterQueue} on add, replay,
 * and discard operations.
 *
 * <p>On startup, PENDING entries are loaded from persistence back into the IMap to
 * recover entries that survived a restart.
 *
 * <p>Implementations must be thread-safe.
 *
 * @author Generated by Claude Code
 * @since 3.0
 * @see PersistableDeadLetterEntry
 */
public interface DlqStorePersistence {

    /**
     * Persists a single DLQ entry with upsert semantics.
     *
     * @param entry the DLQ entry to persist
     */
    void persist(PersistableDeadLetterEntry entry);

    /**
     * Persists a batch of DLQ entries with upsert semantics.
     *
     * @param entries the DLQ entries to persist
     */
    void persistBatch(List<PersistableDeadLetterEntry> entries);

    /**
     * Loads a single DLQ entry by its ID.
     *
     * @param dlqEntryId the DLQ entry identifier
     * @return the entry if found, or empty
     */
    Optional<PersistableDeadLetterEntry> load(String dlqEntryId);

    /**
     * Loads all DLQ entry IDs with PENDING status.
     *
     * <p>Used on startup to recover entries that need attention.
     * REPLAYED and DISCARDED entries are terminal and not recovered.
     *
     * @return IDs of PENDING entries
     */
    Iterable<String> loadPendingKeys();

    /**
     * Deletes a single DLQ entry from durable storage.
     *
     * @param dlqEntryId the DLQ entry identifier
     */
    void delete(String dlqEntryId);

    /**
     * Checks whether the persistence backend is available and healthy.
     *
     * @return true if the backend is reachable and ready
     */
    boolean isAvailable();
}
