package com.theyawns.framework.persistence;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;

/**
 * In-memory fallback implementation of {@link OutboxStorePersistence}.
 *
 * <p>Used when no external persistence provider (e.g., PostgreSQL) is available.
 * Data is lost on restart — suitable for development and testing only.
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
public class InMemoryOutboxStorePersistence implements OutboxStorePersistence {

    private static final Set<String> NON_DELIVERED_STATUSES = Set.of("PENDING", "CLAIMED", "FAILED");

    private final ConcurrentMap<String, PersistableOutboxEntry> store = new ConcurrentHashMap<>();

    @Override
    public void persist(PersistableOutboxEntry entry) {
        store.put(entry.eventId(), entry);
    }

    @Override
    public void persistBatch(List<PersistableOutboxEntry> entries) {
        for (PersistableOutboxEntry entry : entries) {
            store.put(entry.eventId(), entry);
        }
    }

    @Override
    public Optional<PersistableOutboxEntry> load(String eventId) {
        return Optional.ofNullable(store.get(eventId));
    }

    @Override
    public Iterable<String> loadNonDeliveredKeys() {
        List<String> keys = new ArrayList<>();
        for (PersistableOutboxEntry entry : store.values()) {
            if (NON_DELIVERED_STATUSES.contains(entry.status())) {
                keys.add(entry.eventId());
            }
        }
        return keys;
    }

    @Override
    public void delete(String eventId) {
        store.remove(eventId);
    }

    @Override
    public boolean isAvailable() {
        return true;
    }
}
