package com.theyawns.framework.persistence;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ConcurrentMap;

/**
 * In-memory fallback implementation of {@link DlqStorePersistence}.
 *
 * <p>Used when no external persistence provider (e.g., PostgreSQL) is available.
 * Data is lost on restart — suitable for development and testing only.
 *
 * @author Generated by Claude Code
 * @since 3.0
 */
public class InMemoryDlqStorePersistence implements DlqStorePersistence {

    private final ConcurrentMap<String, PersistableDeadLetterEntry> store = new ConcurrentHashMap<>();

    @Override
    public void persist(PersistableDeadLetterEntry entry) {
        store.put(entry.dlqEntryId(), entry);
    }

    @Override
    public void persistBatch(List<PersistableDeadLetterEntry> entries) {
        for (PersistableDeadLetterEntry entry : entries) {
            store.put(entry.dlqEntryId(), entry);
        }
    }

    @Override
    public Optional<PersistableDeadLetterEntry> load(String dlqEntryId) {
        return Optional.ofNullable(store.get(dlqEntryId));
    }

    @Override
    public Iterable<String> loadPendingKeys() {
        List<String> keys = new ArrayList<>();
        for (PersistableDeadLetterEntry entry : store.values()) {
            if ("PENDING".equals(entry.status())) {
                keys.add(entry.dlqEntryId());
            }
        }
        return keys;
    }

    @Override
    public void delete(String dlqEntryId) {
        store.remove(dlqEntryId);
    }

    @Override
    public boolean isAvailable() {
        return true;
    }
}
