package com.theyawns.framework.persistence;

import org.springframework.boot.context.properties.ConfigurationProperties;

/**
 * Configuration properties for the persistence layer.
 *
 * <p>Controls write-behind MapStore behavior including batch size, delay,
 * and coalescing settings. These properties map directly to Hazelcast's
 * {@code MapStoreConfig} parameters.
 *
 * <p>Example configuration in application.yml:
 * <pre>{@code
 * framework:
 *   persistence:
 *     enabled: true
 *     write-delay-seconds: 5
 *     write-batch-size: 100
 *     write-coalescing: false
 *     initial-load-mode: LAZY
 * }</pre>
 *
 * @author Generated by Claude Code
 * @since 3.0
 * @see PersistenceAutoConfiguration
 */
@ConfigurationProperties(prefix = "framework.persistence")
public class PersistenceProperties {

    /**
     * Whether persistence is enabled.
     * Default: false
     */
    private boolean enabled = false;

    /**
     * Number of seconds to delay before writing entries to the database.
     * Hazelcast batches writes during this window for efficiency.
     * Default: 5
     */
    private int writeDelaySeconds = 5;

    /**
     * Maximum number of entries to write in a single batch.
     * Default: 100
     */
    private int writeBatchSize = 100;

    /**
     * Whether to coalesce writes to the same key.
     * For event stores, this should be {@code false} (each event is unique).
     * For view stores, this can be {@code true} (only latest state matters).
     * Default: false
     */
    private boolean writeCoalescing = false;

    /**
     * Initial load mode for MapLoader.
     * LAZY: load entries on first access. EAGER: load all entries at startup.
     * Default: LAZY
     */
    private InitialLoadMode initialLoadMode = InitialLoadMode.LAZY;

    /**
     * Creates a new PersistenceProperties with default values.
     */
    public PersistenceProperties() {
        // Default constructor
    }

    /**
     * Returns whether persistence is enabled.
     *
     * @return true if persistence is enabled
     */
    public boolean isEnabled() {
        return enabled;
    }

    /**
     * Sets whether persistence is enabled.
     *
     * @param enabled true to enable persistence
     */
    public void setEnabled(final boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * Returns the write delay in seconds.
     *
     * @return the write delay in seconds
     */
    public int getWriteDelaySeconds() {
        return writeDelaySeconds;
    }

    /**
     * Sets the write delay in seconds.
     *
     * @param writeDelaySeconds the write delay (must be >= 0)
     */
    public void setWriteDelaySeconds(final int writeDelaySeconds) {
        if (writeDelaySeconds < 0) {
            throw new IllegalArgumentException("writeDelaySeconds must be >= 0, got: " + writeDelaySeconds);
        }
        this.writeDelaySeconds = writeDelaySeconds;
    }

    /**
     * Returns the maximum write batch size.
     *
     * @return the write batch size
     */
    public int getWriteBatchSize() {
        return writeBatchSize;
    }

    /**
     * Sets the maximum write batch size.
     *
     * @param writeBatchSize the write batch size (must be >= 1)
     */
    public void setWriteBatchSize(final int writeBatchSize) {
        if (writeBatchSize < 1) {
            throw new IllegalArgumentException("writeBatchSize must be at least 1, got: " + writeBatchSize);
        }
        this.writeBatchSize = writeBatchSize;
    }

    /**
     * Returns whether write coalescing is enabled.
     *
     * @return true if coalescing is enabled
     */
    public boolean isWriteCoalescing() {
        return writeCoalescing;
    }

    /**
     * Sets whether write coalescing is enabled.
     *
     * @param writeCoalescing true to enable coalescing
     */
    public void setWriteCoalescing(final boolean writeCoalescing) {
        this.writeCoalescing = writeCoalescing;
    }

    /**
     * Returns the initial load mode.
     *
     * @return the initial load mode
     */
    public InitialLoadMode getInitialLoadMode() {
        return initialLoadMode;
    }

    /**
     * Sets the initial load mode.
     *
     * @param initialLoadMode the initial load mode
     */
    public void setInitialLoadMode(final InitialLoadMode initialLoadMode) {
        if (initialLoadMode == null) {
            throw new IllegalArgumentException("initialLoadMode cannot be null");
        }
        this.initialLoadMode = initialLoadMode;
    }

    @Override
    public String toString() {
        return "PersistenceProperties{" +
                "enabled=" + enabled +
                ", writeDelaySeconds=" + writeDelaySeconds +
                ", writeBatchSize=" + writeBatchSize +
                ", writeCoalescing=" + writeCoalescing +
                ", initialLoadMode=" + initialLoadMode +
                '}';
    }

    /**
     * Initial load mode for MapLoader.
     */
    public enum InitialLoadMode {
        /** Load entries on first access. */
        LAZY,
        /** Load all entries at startup. */
        EAGER
    }
}
