package com.theyawns.framework.persistence;

/**
 * Persistence-layer representation of an outbox entry.
 *
 * <p>This record contains only serializable primitives and strings,
 * decoupled from Hazelcast {@code GenericRecord}. The nested
 * {@code eventRecord} is stored as a JSON string produced by
 * {@link com.theyawns.framework.persistence.mapstore.GenericRecordJsonConverter}.
 *
 * @param eventId            unique event identifier (IMap key)
 * @param eventType          Compact schema type name of the event
 * @param eventData          JSON representation of the nested eventRecord GenericRecord
 * @param retryCount         number of delivery attempts
 * @param status             outbox entry status (PENDING, CLAIMED, DELIVERED, FAILED)
 * @param createdAtMillis    epoch millis when the entry was created
 * @param lastAttemptAtMillis epoch millis of last delivery attempt (nullable)
 * @param failureReason      reason for last failure (nullable)
 * @param claimantId         member ID that claimed this entry (nullable)
 * @param claimedAtMillis    epoch millis when the entry was claimed (nullable)
 * @author Generated by Claude Code
 * @since 3.0
 * @see OutboxStorePersistence
 */
public record PersistableOutboxEntry(
        String eventId,
        String eventType,
        String eventData,
        int retryCount,
        String status,
        long createdAtMillis,
        Long lastAttemptAtMillis,
        String failureReason,
        String claimantId,
        Long claimedAtMillis
) {

    /**
     * Compact constructor with validation.
     */
    public PersistableOutboxEntry {
        if (eventId == null) {
            throw new IllegalArgumentException("eventId cannot be null");
        }
        if (eventType == null) {
            throw new IllegalArgumentException("eventType cannot be null");
        }
        if (eventData == null) {
            throw new IllegalArgumentException("eventData cannot be null");
        }
        if (status == null) {
            throw new IllegalArgumentException("status cannot be null");
        }
    }
}
