package com.theyawns.framework.persistence;

/**
 * Portable representation of a materialized view entry for database persistence.
 *
 * <p>This record decouples the persistence layer from Hazelcast's {@code GenericRecord}.
 * The MapStore adapters convert between Hazelcast types and this record before delegating
 * to the {@link ViewStorePersistence} provider.
 *
 * <p>Fields:
 * <ul>
 *   <li>{@code viewKey} — the IMap key (typically the domain object's ID)</li>
 *   <li>{@code viewData} — JSON string representation of the GenericRecord fields</li>
 *   <li>{@code lastUpdatedMillis} — last update timestamp as epoch milliseconds</li>
 * </ul>
 *
 * @author Generated by Claude Code
 * @since 3.0
 * @see ViewStorePersistence
 */
public record PersistableView(
        String viewKey,
        String viewData,
        long lastUpdatedMillis
) {

    /**
     * Creates a new PersistableView with validation.
     *
     * @throws IllegalArgumentException if viewKey or viewData is null
     */
    public PersistableView {
        if (viewKey == null) {
            throw new IllegalArgumentException("viewKey cannot be null");
        }
        if (viewData == null) {
            throw new IllegalArgumentException("viewData cannot be null");
        }
    }
}
