package com.theyawns.framework.persistence;

import java.util.Objects;

/**
 * Persistence-layer representation of a dead letter queue entry.
 *
 * <p>Contains only serializable primitives and strings, decoupled from
 * Hazelcast {@code GenericRecord}. The event data is stored as a JSON string
 * produced by {@code GenericRecordJsonConverter}.
 *
 * @param dlqEntryId            unique identifier for this DLQ entry
 * @param originalEventId       the original event's identifier
 * @param eventType             the event type (e.g., "OrderCreated")
 * @param topicName             the ITopic name for replay
 * @param eventData             JSON representation of the event GenericRecord (nullable)
 * @param failureReason         why processing failed
 * @param failureTimestampMillis when the failure occurred (epoch millis)
 * @param sourceService         the service that failed (nullable)
 * @param sagaId                the saga identifier (nullable)
 * @param correlationId         the correlation identifier (nullable)
 * @param replayCount           number of replay attempts
 * @param status                current status (PENDING, REPLAYED, DISCARDED)
 *
 * @author Generated by Claude Code
 * @since 3.0
 * @see DlqStorePersistence
 */
public record PersistableDeadLetterEntry(
        String dlqEntryId,
        String originalEventId,
        String eventType,
        String topicName,
        String eventData,
        String failureReason,
        long failureTimestampMillis,
        String sourceService,
        String sagaId,
        String correlationId,
        int replayCount,
        String status
) {

    /**
     * Compact constructor with validation.
     */
    public PersistableDeadLetterEntry {
        Objects.requireNonNull(dlqEntryId, "dlqEntryId is required");
        Objects.requireNonNull(originalEventId, "originalEventId is required");
        Objects.requireNonNull(eventType, "eventType is required");
        Objects.requireNonNull(topicName, "topicName is required");
        Objects.requireNonNull(status, "status is required");
    }
}
