package com.theyawns.framework.persistence;

import java.util.List;
import java.util.Optional;

/**
 * Provider-agnostic interface for persisting materialized view entries to durable storage.
 *
 * <p>Implementations of this interface are responsible for storing and loading
 * {@link PersistableView} records. The framework's MapStore adapters delegate
 * to this interface, keeping Hazelcast concerns separate from database concerns.
 *
 * <p>View persistence uses upsert semantics — newer entries replace older ones
 * for the same key. This matches the materialized view pattern where the latest
 * state is always the correct state.
 *
 * <p>Implementations must be thread-safe — Hazelcast's write-behind mechanism
 * may call {@link #persistBatch(String, List)} from multiple threads concurrently.
 *
 * @author Generated by Claude Code
 * @since 3.0
 * @see PersistableView
 * @see com.theyawns.framework.persistence.mapstore.ViewStoreMapStore
 */
public interface ViewStorePersistence {

    /**
     * Persists a single view entry to durable storage with upsert semantics.
     *
     * @param viewName the view name (e.g., "Customer_VIEW")
     * @param view the view entry to persist
     */
    void persist(String viewName, PersistableView view);

    /**
     * Persists a batch of view entries to durable storage with upsert semantics.
     *
     * <p>Implementations should use batch upsert for efficiency.
     * All entries in the batch belong to the same view.
     *
     * @param viewName the view name (e.g., "Customer_VIEW")
     * @param views the view entries to persist
     */
    void persistBatch(String viewName, List<PersistableView> views);

    /**
     * Loads a single view entry from durable storage.
     *
     * @param viewName the view name
     * @param viewKey the IMap key
     * @return the view entry if found, or empty
     */
    Optional<PersistableView> loadView(String viewName, String viewKey);

    /**
     * Loads all view keys for a given view name, used by MapLoader for initial load.
     *
     * @param viewName the view name
     * @return all view keys in the store
     */
    Iterable<String> loadAllKeys(String viewName);

    /**
     * Deletes a single view entry from durable storage.
     *
     * @param viewName the view name
     * @param viewKey the IMap key
     */
    void delete(String viewName, String viewKey);

    /**
     * Deletes all view entries for a given view name.
     *
     * @param viewName the view name
     */
    void deleteAll(String viewName);

    /**
     * Checks whether the persistence backend is available and healthy.
     *
     * @return true if the backend is reachable and ready
     */
    boolean isAvailable();
}
