package com.theyawns.ecommerce.account.controller;

import com.theyawns.ecommerce.account.service.CustomerService;
import com.theyawns.ecommerce.common.domain.Customer;
import com.theyawns.ecommerce.common.dto.CustomerDTO;
import jakarta.validation.Valid;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.concurrent.CompletableFuture;

/**
 * REST controller for customer account management.
 *
 * <p>Endpoints:
 * <ul>
 *   <li>POST /api/customers - Create a new customer</li>
 *   <li>GET /api/customers/{id} - Get customer by ID</li>
 *   <li>PUT /api/customers/{id} - Update customer information</li>
 *   <li>PATCH /api/customers/{id}/status - Change customer status</li>
 * </ul>
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
@RestController
@RequestMapping("/api/customers")
public class AccountController {

    private static final Logger logger = LoggerFactory.getLogger(AccountController.class);

    private final CustomerService customerService;

    /**
     * Creates a new AccountController.
     *
     * @param customerService the customer service
     */
    public AccountController(CustomerService customerService) {
        this.customerService = customerService;
    }

    /**
     * Creates a new customer account.
     *
     * @param dto the customer data
     * @return the created customer
     */
    @PostMapping
    public CompletableFuture<ResponseEntity<CustomerDTO>> createCustomer(@Valid @RequestBody CustomerDTO dto) {
        logger.info("REST: Creating customer with email: {}", dto.getEmail());

        return customerService.createCustomer(dto)
                .thenApply(customer -> {
                    CustomerDTO response = customer.toDTO();
                    logger.info("REST: Customer created with ID: {}", response.getCustomerId());
                    return ResponseEntity.status(HttpStatus.CREATED).body(response);
                });
    }

    /**
     * Retrieves a customer by ID.
     *
     * @param customerId the customer ID
     * @return the customer, or 404 if not found
     */
    @GetMapping("/{customerId}")
    public ResponseEntity<CustomerDTO> getCustomer(@PathVariable String customerId) {
        logger.debug("REST: Getting customer: {}", customerId);

        return customerService.getCustomer(customerId)
                .map(customer -> {
                    CustomerDTO dto = customer.toDTO();
                    return ResponseEntity.ok(dto);
                })
                .orElse(ResponseEntity.notFound().build());
    }

    /**
     * Updates an existing customer's information.
     *
     * @param customerId the customer ID
     * @param dto the updated customer data
     * @return the updated customer
     */
    @PutMapping("/{customerId}")
    public CompletableFuture<ResponseEntity<CustomerDTO>> updateCustomer(
            @PathVariable String customerId,
            @Valid @RequestBody CustomerDTO dto) {
        logger.info("REST: Updating customer: {}", customerId);

        return customerService.updateCustomer(customerId, dto)
                .thenApply(customer -> {
                    CustomerDTO response = customer.toDTO();
                    logger.info("REST: Customer updated: {}", customerId);
                    return ResponseEntity.ok(response);
                });
    }

    /**
     * Changes a customer's account status.
     *
     * @param customerId the customer ID
     * @param request the status change request
     * @return the updated customer
     */
    @PatchMapping("/{customerId}/status")
    public CompletableFuture<ResponseEntity<CustomerDTO>> changeStatus(
            @PathVariable String customerId,
            @RequestBody StatusChangeRequest request) {
        logger.info("REST: Changing status for customer {} to {}", customerId, request.status());

        return customerService.changeStatus(customerId, request.status(), request.reason())
                .thenApply(customer -> {
                    CustomerDTO response = customer.toDTO();
                    logger.info("REST: Customer status changed: {} -> {}", customerId, request.status());
                    return ResponseEntity.ok(response);
                });
    }

    /**
     * Request body for status change operations.
     *
     * @param status the new status (ACTIVE, SUSPENDED, CLOSED)
     * @param reason the reason for the change
     */
    public record StatusChangeRequest(String status, String reason) {
    }
}
