package com.theyawns.ecommerce.account.service;

import com.theyawns.ecommerce.common.domain.Customer;
import com.theyawns.ecommerce.common.dto.CustomerDTO;

import java.util.Optional;
import java.util.concurrent.CompletableFuture;

/**
 * Interface for customer account management operations.
 *
 * @author Generated by Claude Code
 * @since 1.0
 */
public interface CustomerService {

    /**
     * Creates a new customer account.
     *
     * @param dto the customer data
     * @return a future that completes with the created customer
     */
    CompletableFuture<Customer> createCustomer(CustomerDTO dto);

    /**
     * Updates an existing customer's information.
     *
     * @param customerId the customer ID
     * @param dto the updated customer data
     * @return a future that completes with the updated customer
     */
    CompletableFuture<Customer> updateCustomer(String customerId, CustomerDTO dto);

    /**
     * Changes a customer's account status.
     *
     * @param customerId the customer ID
     * @param newStatus the new status
     * @param reason the reason for the status change
     * @return a future that completes with the updated customer
     */
    CompletableFuture<Customer> changeStatus(String customerId, String newStatus, String reason);

    /**
     * Retrieves a customer by ID.
     *
     * @param customerId the customer ID
     * @return the customer, or empty if not found
     */
    Optional<Customer> getCustomer(String customerId);

    /**
     * Checks if a customer exists.
     *
     * @param customerId the customer ID
     * @return true if the customer exists
     */
    boolean customerExists(String customerId);
}
